### ISSUE TITLE
🐛 [firebase_auth] Apple authentication fails on iOS in secondary Firebase apps

### ISSUE THREAD

**Issue by rich-j** [firebase/flutterfire#10001]
## Bug report

Apple authentication fails on iOS when used with secondary Firebase apps. Although the failure is dependent on the state of the primary app authentication.

In our app we use multiple Firebase apps. When a secondary app is signed in using the Apple authentication provider, calls such as `firebaseAuth.currentUser!.getIdTokenResult()` can fail in the platform code with an exception `[firebase_auth/no-current-user] No user currently signed in`. How can there be no user when we just used the current user to call the method? I'm guessing that the platform code is attempting to validate the current sign in but is incorrectly checking the primary app's authentication for a valid sign in (our primary Firebase app doesn't always have a valid user signed in).

Creating a reproducible example shows that Apple authentication fails when given only a secondary app but succeeds when the app is primary. Other authentication providers (e.g. password, Google) work when given only a secondary app.

### Steps to reproduce

Use the below sample main code with a Firebase project configured with Apple authentication. Run the main code on an iOS simulator/device and observe a hard crash.

You can remove the `name` property from the `initializeApp` call to make the Firebase app primary and Apple authentication will succeed. Secondary Firebase app sign-in succeeds using other providers too.

---

### Sample code

```dart
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {

    // Remove the secondary app name to make the app the primary and Apple authentication will work
    final fbApp = await Firebase.initializeApp(name: "secondary", options: DefaultFirebaseOptions.currentPlatform);

    // // Other signins (e.g. password, Google) work with only a secondary app
    // final fbAuthPW = FirebaseAuth.instanceFor(app: fbApp);
    // final UserCredential authResultPW = await fbAuthPW.signInWithEmailAndPassword(email: "a@b.c", password: "pw");
    // if (fbAuthPW.currentUser == null) throw StateError("Failed PW signin");
    // final tokenPW = await fbAuthPW.currentUser!.getIdTokenResult();
    // print("Got PW token $tokenPW");

    // Apple signin works when the app is primary and will fail when only a secondary app.
    // When there are both primary and secondary apps Apple authentication sometimes works and sometimes fails.
    final fbAuthApple = FirebaseAuth.instanceFor(app: fbApp);
    final appleProvider = AppleAuthProvider();
    final UserCredential authResult = await fbAuthApple.signInWithProvider(appleProvider);

    if (fbAuthApple.currentUser == null) throw StateError("Failed Apple signin");
    print("Apple currentUser: ${fbAuthApple.currentUser}");
    final tokenApple = await fbAuthApple.currentUser!.getIdTokenResult();
    print("Got Apple token $tokenApple");

  } catch (ex, stacktrace) {
    print("Error $ex \n$stacktrace");
  }

  print("Complete");
  exit(0);    // Firebase is cached with Flutter restart so force a cold start for next test run
}
```

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.4)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.18.5
Flutter SDK 3.3.9
fb_auth_secondary 1.0.0+1

dependencies:
- firebase_auth 4.1.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.0.9 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.9.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.1.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 6.11.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.1.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.2 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.0.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.4
- lints 2.0.1
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- path 1.8.2
- plugin_platform_interface 2.1.3 [meta]
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- vector_math 2.1.2
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the detailed report @rich-j 
Using the code sample provided, I am seeing same behavior, ie, while trying to sign in with Apple, below gets logged in console, although the sign-in is successful:

```
email: darshankawar@gmail.com, phoneNumber: null, photoURL: null, providerId: apple.com, uid: 001119.ee589e491a4a45f5a80038fdf2b4cd79.0939), UserInfo(displayName: Darshan Kawar, email: darshankawar@gmail.com, phoneNumber: null, photoURL: https://lh3.googleusercontent.com/a-/AFdZucq1zPgzMYePvJovOko3qRRYfUom47yBQBDRUzGlCA=s96-c, providerId: password, uid: darshankawar@gmail.com)], refreshToken: , tenantId: null, uid: WZwNfLB8XIQc3pwOQjdGI7B6ct42)
flutter: Error [firebase_auth/no-current-user] No user currently signed in. 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:518:43)
<asynchronous suspension>
#3      MethodChannelUser.getIdTokenResult (package:firebase_auth_platform_interface/src/method_channel/method_channel_user.dart:64:36)
<asynchronous suspension>
#4      main (package:triage/main.dart:42:24)
<asynchronous suspension>
```

If we remove `name: "secondary", `, then above error does not occur.
