### ISSUE TITLE
🐛 [firebase_auth]  Crash OOM at java.lang.StringFactory.newStringFromChars(StringFactory.java:120)

### ISSUE THREAD

**Issue by Tom3652** [firebase/flutterfire#10004]
## Bug report

**Describe the bug**

Crash before OOM on a very simple App.
The crash occurred with the `firebase_auth: ^4.1.1` version because i have not released a new app version since June or July. 
I will be doing so shortly, but i would like to know if this error might still happen or if it's possible it has been fixed in the latest `firebase_auth`. 

Here is my report from crashlytics : 

![Capture d’écran 2022-11-27 à 15 06 57](https://user-images.githubusercontent.com/32631467/204139521-b25f79a6-7110-419a-a7c4-0fbb7f1ce452.png)

```
# Crashlytics - Stack trace
# Application: com.listeen.android
# Platform: android
# Version: 1.5.6 (22)
# Issue: 521bbffb3b18596b13c8652020eb9471
# Session: 6383585502920001165955D867C48F9B_DNE_0_v2
# Date: Sun Nov 27 2022 13:30:36 GMT+0100 (heure normale d’Europe centrale)

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 24468968 byte allocation with 6291456 free bytes and 13MB until OOM, target footprint 261041720, growth limit 268435456
       at java.lang.StringFactory.newStringFromChars(StringFactory.java:120)
       at java.lang.StringBuilder.toString(StringBuilder.java:413)
       at org.json.JSONStringer.toString(JSONStringer.java:443)
       at org.json.JSONObject.toString(JSONObject.java:702)
       at com.google.firebase.auth.internal.zzbg.zzd(zzbg.java:180)
       at com.google.firebase.auth.FirebaseAuth.zzH(FirebaseAuth.java:116)
       at com.google.firebase.auth.zzo.zza(zzo.java:3)
       at com.google.android.gms.internal.firebase-auth-api.zzrw.zzb(zzrw.java:31)
       at com.google.android.gms.internal.firebase-auth-api.zzui.zzj(zzui.java)
       at com.google.android.gms.internal.firebase-auth-api.zzuf.zzn(zzuf.java:33)
       at com.google.android.gms.internal.firebase-auth-api.zzth.zzn(zzth.java:2)
       at com.google.android.gms.internal.firebase-auth-api.zzqf.zzb(zzqf.java:4)
       at com.google.android.gms.internal.firebase-auth-api.zzuq.zza(zzuq.java:140)
       at com.google.android.gms.internal.firebase-auth-api.zztw.zzf(zztw.java:20)
       at com.google.android.gms.internal.firebase-auth-api.zzrm.zzp(zzrm.java:18)
       at com.google.android.gms.internal.firebase-auth-api.zzti.zzj(zzti.java:26)
       at com.google.android.gms.internal.firebase-auth-api.zzrw.zzc(zzrw.java:11)
       at com.google.android.gms.internal.firebase-auth-api.zzuj.run(zzuj.java:8)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

The whole trace is too big for a github comment, but i can send it as a file if needed.

You can [download](https://listeen.fr) my app to see what it is.

### Steps to reproduce

Sorry unfortunately this never happened to me before and it affects one of my users in production...

### Expected behavior

The app should not crash.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @Tom3652 
Since this is an OOM issue, it may probably be related to `firebase-android-sdk's BoM version. Can you confirm which version are you on for this production app ?

See [this](https://github.com/firebase/flutterfire/issues/8444#issuecomment-1186613561) for further reference.

**Comment by Tom3652** [comment]
Hi @darshankawar , sorry but i can't find any reference to `firebase-android-sdk` BoM in my gradle files
I have never used it explicitely anyway, is it written somewhere by firebase ?

**Comment by darshankawar** [comment]
You probably don't need to explicitly set in your gradle file. The version is updated in `firebase_core` package itself that we use.
The latest version of it is `31.0.3` per https://github.com/firebase/flutterfire/blob/master/packages/firebase_core/firebase_core/android/gradle.properties

So you may check which version of `firebase_core` is being used in your project and see corresponding `FirebaseSDKVersion` it has.

**Comment by Tom3652** [comment]
Hi @darshankawar thanks for the details. 
However i have already upgrade to the latest versions for my app development so i don't know if i can check back an old version from the online app bundle somehow :/ 

Now i have indeed : 

```
# https://firebase.google.com/support/release-notes/android
FirebaseSDKVersion=31.0.3
```

**Comment by darshankawar** [comment]
Thanks for the update. Keeping this issue open and labeling for team's attention based on crash log.

/cc @Lyokone

**Comment by Lyokone** [comment]
They were several changes to the native SDK dependency, do you still experience this crash with the latest version?

**Comment by Tom3652** [comment]
Well i have made a new release of my app today with using the latest firebase SDK version, i will see if that happens again.
I only have few hundreds of users so it might take some time :/
