### ISSUE TITLE
🐛 [firebase_auth] App crashes on sms / phone authentication

### ISSUE THREAD

**Issue by KubaStachecki** [firebase/flutterfire#10012]
## Bug report

**Describe the bug**
After mobile number is provided, the android app crashes. 

I added 
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.6'
and
    implementation 'androidx.browser:browser:1.4.0'

to bild.gradle dependencies, as suggested StackOverflow solutions.

App is using
    implementation platform('com.google.firebase:firebase-bom:31.1.0')

Here is the log:

```
Fatal Exception: java.lang.NoSuchMethodError: No direct method <init>(Ljava/util/Map;)V in class Lj$/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'j$.util.concurrent.ConcurrentHashMap' appears in base.apk!classes2.dex)
       at com.google.android.gms.internal.firebase-auth-api.zzbd.<init>(com.google.firebase:firebase-auth@@21.1.0:2)
       at com.google.android.gms.internal.firebase-auth-api.zzbz.zzn(com.google.firebase:firebase-auth@@21.1.0:1)
       at com.google.android.gms.internal.firebase-auth-api.zzit.zza(com.google.firebase:firebase-auth@@21.1.0:3)
       at com.google.android.gms.internal.firebase-auth-api.zzit.<clinit>(com.google.firebase:firebase-auth@@21.1.0:3)
       at com.google.android.gms.internal.firebase-auth-api.zzit.zza(com.google.firebase:firebase-auth@@21.1.0:1)
       at com.google.android.gms.internal.firebase-auth-api.zzcc.zza(com.google.firebase:firebase-auth@@21.1.0:3)
       at com.google.android.gms.internal.firebase-auth-api.zzcc.<clinit>(com.google.firebase:firebase-auth@@21.1.0:10)
       at com.google.android.gms.internal.firebase-auth-api.zzcc.zza(com.google.firebase:firebase-auth@@21.1.0:1)
       at com.google.android.gms.internal.firebase-auth-api.zzei.zza(com.google.firebase:firebase-auth@@21.1.0:4)
       at com.google.android.gms.internal.firebase-auth-api.zzei.<clinit>(com.google.firebase:firebase-auth@@21.1.0:4)
       at com.google.android.gms.internal.firebase-auth-api.zzei.zza(com.google.firebase:firebase-auth@@21.1.0:1)
       at com.google.firebase.auth.internal.zzk.<init>(com.google.firebase:firebase-auth@@21.1.0:1)
       at com.google.firebase.auth.internal.zzk.zza(com.google.firebase:firebase-auth@@21.1.0:2)
       at com.google.firebase.auth.internal.RecaptchaActivity.zzb(com.google.firebase:firebase-auth@@21.1.0:9)
       at com.google.android.gms.internal.firebase-auth-api.zzxe.<init>(com.google.firebase:firebase-auth@@21.1.0:14)
       at com.google.firebase.auth.internal.RecaptchaActivity.onResume(com.google.firebase:firebase-auth@@21.1.0:46)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1476)
       at android.app.Activity.performResume(Activity.java:8411)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4867)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4910)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2259)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8105)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

### Expected behavior

Sms or captcha verification -  the next step in the process.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at C:/Users/JS/AppData/Local/Android/Sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • ANDROID_HOME = C:/Users/JS/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  cloud_functions: ^4.0.5

  firebase_auth: ^4.1.4
  firebase_analytics: ^10.0.6
  firebase_dynamic_links: ^5.0.6
  firebase_database: ^10.0.6
  firebase_storage: ^11.0.6
  firebase_messaging: ^14.1.2
  firebase_crashlytics: ^3.0.6
  firebase_app_check: ^0.1.1+5```

</details>

---

**Comment by darshankawar** [comment]
@KubaStachecki 
Is it occuring on emulator or physical device ? If you have tried on emulator, can you also check on physical device and confirm ?
Also can you provide a complete minimal reproducible code sample that triggers the reported error ?


> I added coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.6' and implementation 'androidx.browser:browser:1.4.0'
> 
> to bild.gradle dependencies, as suggested StackOverflow solutions.

Did you add it after getting crash or before getting crash ? Can you provide link where it shows to add it ?

**Comment by KubaStachecki** [comment]
Hi!

I'm using a physical device. This crash happened on my device and in the production - occasionally, perhaps only at the first run when a captcha is required. I wasn't able to reproduce it in 100% of the cases yet with my project, I will update if I manage to do it. 

The same project works on IOS without issues.

Here is the StackOverflow suggestion that I tried, without luck:
https://stackoverflow.com/questions/65839861/app-crash-while-using-firebase-phone-auth-in-android/65840172#65840172

Here is my authentication code, just in case: 

```

_firebaseAuth.verifyPhoneNumber(

      codeAutoRetrievalTimeout: (String verificationId) {},
      phoneNumber: phoneNumber,
      timeout: Duration(seconds: 120),
      verificationCompleted: (AuthCredential credential) async {
        UserCredential result = await _firebaseAuth
            .signInWithCredential(credential)
            .onError((error, stackTrace) =>
                logErrorInFirestore(error, 'PhoneSignIn')
        )
            .catchError((onError) => throw PlatformException(
                  code: 'Authentication Error',
                  message: onError.message,
                ));
        },
      verificationFailed: (FirebaseAuthException e) {
      // show error

      },
      codeSent: (String verificationId, [int forceResendingToken]) {
     // show dialog and

                                  try {
                                     _firebaseAuth
                                        .signInWithCredential(credential)
                                        .then((var authRes) {
                                      var _firebaseUser = authRes.user;

                                    });
                                  } catch (e) {     
                          
                                  }
        
            });


```

**Comment by darshankawar** [comment]
I am unable to replicate this error using [plugin's example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example). Can you try the same and see if using it, you get same behavior or not ?




> Here is the StackOverflow suggestion that I tried, without luck:

That link is one year old and most probably not valid anymore, since the package has gone through lot of updates since then. Also you don't need to explicitly implement / specify `BoM` version in your gradle file.



> This crash happened on my device and in the production - occasionally, perhaps only at the first run when a captcha is required. I wasn't able to reproduce it in 100% of the cases yet with my project

If you see a concrete pattern / exact steps to replicate, share it here which would be helpful to debug further.

**Comment by mariopepe** [comment]
Hey, I think I am having this same issue with an app in production!
To me it happens with a **phone number that was never registered**, after that, logging back in is as smooth as oil. But if the phone number is a new one (new user), it never works at the first shoot.

My case, after many investigations, might be connected to AppCheck (SafetyNet, Play Integrity).

@KubaStachecki mind me asking if you have SafetyNet or Play Integrity enabled? I think this is the red thread of the story.
