### ISSUE TITLE
🐛 [cloud_firestore] Internal error in Cloud Firestore (24.4.0) 

### ISSUE THREAD

**Issue by Djihanegh** [firebase/flutterfire#10077]
## Bug report

**Describe the bug**
The Flutter android app crashes after a hot reload

---

### Debug Output

<details><summary>Click To Expand</summary>

```
E/AndroidRuntime( 9436): java.lang.RuntimeException: Internal error in Cloud Firestore (24.4.0).
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:539)
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$jx84dqgUsF4ojecSMurRqFLFD1Y.run(Unknown Source:2)
E/AndroidRuntime( 9436): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 9436): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 9436): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime( 9436): 	at android.app.ActivityThread.main(ActivityThread.java:7830)
E/AndroidRuntime( 9436): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9436): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 9436): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
E/AndroidRuntime( 9436): Caused by: java.lang.RuntimeException: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY)
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:330)
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$SynchronizedShutdownAwareExecutor$pKSAgg-ozJ8RbUveSl-44aUfFQw.run(Unknown Source:4)
E/AndroidRuntime( 9436): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/AndroidRuntime( 9436): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 9436): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/AndroidRuntime( 9436): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 9436): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:234)
E/AndroidRuntime( 9436):	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime( 9436): Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY)
E/AndroidRuntime( 9436): 	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
E/AndroidRuntime( 9436): 	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:658)
E/AndroidRuntime( 9436): 	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:325)
E/AndroidRuntime( 9436): 	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
E/AndroidRuntime( 9436): 	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:572)
E/AndroidRuntime( 9436): 	at android.database.sqlite.SQLiteDatabase.beginTransactionWithListener(SQLiteDatabase.java:535)
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.local.SQLitePersistence.runTransaction(SQLitePersistence.java:211)
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.local.SQLiteOverlayMigrationManager.buildOverlays(SQLiteOverlayMigrationManager.java:46)
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.local.SQLiteOverlayMigrationManager.run(SQLiteOverlayMigrationManager.java:42)
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.local.LocalStore.start(LocalStore.java:182)
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.core.ComponentProvider.initialize(ComponentProvider.java:156)
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.core.FirestoreClient.initialize(FirestoreClient.java:287)
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0$FirestoreClient(FirestoreClient.java:110)
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.core.-$$Lambda$FirestoreClient$Eq-cAcb1C1mM4tyiJsLJXZ13tyU.run(Unknown Source:8)
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:441)
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$Y9GO7zO2DX6MzQJ5TbKtKW_NzO0.call(Unknown Source:2)
E/AndroidRuntime( 9436): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:327)
E/AndroidRuntime( 9436): 	... 8 more
I/Process ( 9436): Sending signal. PID: 9436 SIG: 9
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.18.2
Flutter SDK 3.3.6

dependencies:
- app_to_foreground 0.0.3 [flutter]
- app_usage 2.0.0 [flutter]
- auto_size_text 3.0.0 [flutter]
- bg_launcher 0.0.1 [flutter plugin_platform_interface]
- bloc 8.1.0 [meta]
- cloud_firestore 4.0.4 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.5
- device_apps 2.2.0 [flutter]
- device_info_plus 4.1.3 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- enum_to_string 2.0.1
- firebase_core 2.1.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_appavailability 0.0.22 [flutter]
- flutter_background_service 2.4.5 [flutter flutter_background_service_platform_interface flutter_background_service_android flutter_background_service_ios]
- flutter_bloc 8.1.1 [flutter bloc provider]
- flutter_foreground_task 3.10.0 [flutter plugin_platform_interface platform shared_preferences shared_preferences_android shared_preferences_ios]
- flutter_local_notifications 11.0.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_overlay_window 0.3.2 [flutter]
- flutter_svg 1.1.6 [flutter meta path_drawing vector_math xml]
- freezed 2.2.0 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- freezed_annotation 2.2.0 [collection json_annotation meta]
- get 4.6.5 [flutter]
- get_it 7.2.0 [async collection]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- hive_generator 1.1.3 [build source_gen hive analyzer source_helper]
- injectable 1.5.3 [get_it]
- injectable_generator 1.5.4 [build source_gen path glob analyzer code_builder dart_style injectable collection]
- intl 0.17.0 [clock path]
- isar 3.0.5 [ffi js meta]
- isar_flutter_libs 3.0.5 [flutter isar]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- provider 6.0.4 [collection flutter nested]
- receive_intent 0.2.3 [flutter]
- share_plus 4.5.3 [cross_file meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- square_percent_indicater 0.1.0 [flutter]
- system_alert_window 1.2.1 [flutter]
- usage_stats 1.2.0 [flutter]
- uuid 3.0.7 [crypto]
- workmanager 0.5.0 [flutter]

dev dependencies:
- build_runner 2.3.2 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- isar_generator 3.0.5 [analyzer build dart_style dartx glob isar path source_gen xxh3]

transitive dependencies:
- _fe_analyzer_shared 47.0.0 [meta]
- _flutterfire_internals 1.0.7 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 4.7.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.1
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.3.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]   
- build_resolvers 2.0.10 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.7 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.4.2 [built_collection collection fixnum meta]
- characters 1.2.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 5.8.4 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.0.4 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.3.0 [built_collection built_value collection matcher meta]
- collection 1.16.0
- convert 3.1.0 [typed_data]
- cross_file 0.3.3+2 [js meta]
- crypto 3.0.2 [typed_data]
- dart_style 2.2.4 [analyzer args path pub_semver source_span]
- dartx 1.1.0 [characters collection crypto meta path time]
- dbus 0.7.8 [args ffi meta xml]
- device_info_plus_linux 3.0.0 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 3.0.0 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 3.0.0 [flutter meta plugin_platform_interface]
- device_info_plus_web 3.0.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 4.1.0 [device_info_plus_platform_interface ffi flutter win32]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- firebase_core_platform_interface 4.5.2 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.0.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.1
- flutter_background_service_android 3.0.3 [flutter flutter_background_service_platform_interface]
- flutter_background_service_ios 2.4.0 [flutter flutter_background_service_platform_interface]
- flutter_background_service_platform_interface 2.2.0 [flutter platform plugin_platform_interface]
- flutter_local_notifications_linux 1.0.0 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 6.0.0 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 3.1.0 [async path]
- glob 2.1.0 [async collection file path string_scanner]
- graphs 2.2.0 [collection]
- hive 2.2.3 [meta crypto]
- http 0.13.5 [async http_parser meta path]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- io 1.0.3 [meta path string_scanner]
- js 0.6.4
- json_annotation 4.7.0 [meta]
- lints 2.0.1
- logging 1.1.0
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- mime 1.0.2
- nested 1.0.0 [flutter]
- package_config 2.1.0 [path]
- path 1.8.2
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.0.20 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.5 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.3 [meta]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.2 [collection meta]
- pubspec_parse 1.2.1 [checked_yaml collection json_annotation pub_semver yaml]
- share_plus_linux 3.0.1 [cross_file share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 3.0.1 [share_plus_platform_interface flutter]
- share_plus_platform_interface 3.2.0 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- share_plus_web 3.1.0 [cross_file share_plus_platform_interface url_launcher flutter flutter_web_plugins meta mime]
- share_plus_windows 3.0.1 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences_android 2.0.14 [flutter shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.1.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.2 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.2.6 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.3 [analyzer collection source_gen]
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.1
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- time 2.1.2 [clock]
- timezone 0.9.0 [path]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.1 [collection]
- url_launcher 6.1.6 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.0.20 [flutter url_launcher_platform_interface]- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.1 [flutter plugin_platform_interface]
- url_launcher_web 2.0.13 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.2
- watcher 1.0.2 [async path]
- web_socket_channel 2.2.0 [async crypto stream_channel]
- win32 3.0.1 [ffi]
- xdg_directories 0.2.0+2 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- xxh3 1.0.1
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @Djihanegh 
For `java.lang.RuntimeException: Internal error in Cloud Firestore`, can you check if [this](https://github.com/firebase/flutterfire/issues/8265#issuecomment-1069563176) solution works in your case ?

For `android.database.sqlite.SQLiteDatabaseLockedException: database is locked`, it seems to be duplicate of https://github.com/firebase/flutterfire/issues/6087. You may go through underlying comments for further reference and see if it helps.

**Comment by Djihanegh** [comment]
Hi,



> Thanks for the report @Djihanegh For `java.lang.RuntimeException: Internal error in Cloud Firestore`, can you check if [this](https://github.com/firebase/flutterfire/issues/8265#issuecomment-1069563176) solution works in your case ?
> 
> For `android.database.sqlite.SQLiteDatabaseLockedException: database is locked`, it seems to be duplicate of #6087. You may go through underlying comments for further reference and see if it helps.

[this](https://github.com/firebase/flutterfire/issues/8265#issuecomment-1069563176)  solution doesn't work, i already have classpath `com.android.tools.build:gradle:4.1.0`  and NOT classpath `com.android.tools.build:gradle:4.2.2`

**Comment by darshankawar** [comment]
Thanks for the update. Does the error replicable consistently everytime you hot reload ? If yes, can you provide complete minimal reproducible code sample along with steps to replicate ?
