### ISSUE TITLE
🐛 [firebase_ui_auth] SignInScreen does not trigger AuthStateChange<UserCreated> when signing in with Google

### ISSUE THREAD

**Issue by JerryEsteban** [firebase/flutterfire#10124]
## Bug report

**Describe the bug**
When using SignInScreen with GoogleProvider, AuthStateChangeAction<UserCreated> doesn't get called (like when using EmailAuthProvider). 

### Steps to reproduce

1. Use SignInScreen with GoogleProvider.
2. Add actions: AuthStateChange<UserCreated> w/ log statements.
3. Run app and notice that nothing gets logged.

### Expected behavior

When a Google login is used for the first time, it should trigger AuthStateChange<UserCreated>.

**Comment by JerryEsteban** [comment]
FWIW, I noticed this exception that happens when using Google login vs email login:

E/flutter (26519): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (26519): #0      EmailVerificationController.user (package:firebase_ui_auth/src/email_verification.dart:68:36)
E/flutter (26519): #1      EmailVerificationController.reload (package:firebase_ui_auth/src/email_verification.dart:82:11)
E/flutter (26519): #2      EmailVerificationController.didChangeAppLifecycleState (package:firebase_ui_auth/src/email_verification.dart:63:7)
E/flutter (26519): #3      WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:692:16)
E/flutter (26519): #4      ServicesBinding._handleLifecycleMessage (package:flutter/src/services/binding.dart:256:5)
E/flutter (26519): #5      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197:49)
E/flutter (26519): #6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
E/flutter (26519): #7      _invoke2 (dart:ui/hooks.dart:186:13)
E/flutter (26519): #8      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
E/flutter (26519): #9      _Channel.push (dart:ui/channel_buffers.dart:132:31)
E/flutter (26519): #10     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
E/flutter (26519): #11     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
E/flutter (26519): #12     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)

**Comment by darshankawar** [comment]
@JerryEsteban 
Thanks for the report. Can you provide `flutter doctor -v`, plugin version you are using on which this error occurs, along with complete minimal reproducible code sample ?

**Comment by JerryEsteban** [comment]
Thanks @darshankawar

### Sample project

https://github.com/JerryEsteban/issue-10124/blob/main/lib/main.dart#L50

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6 21G115 darwin-arm, locale en-US)
    • Flutter version 3.3.10 on channel stable at /Users/estebangs/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (26 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/estebangs/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • Pixel 6 Pro (mobile) • 1A201FDEE0006L • android-arm64  • Android 13 (API 33)
    • macOS (desktop)      • macos          • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)         • chrome         • web-javascript • Google Chrome 108.0.5359.124
    ! Error: Jerry’s iPhone has recently restarted. Xcode will continue when Jerry’s iPhone is unlocked. (code -14)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.18.6
Flutter SDK 3.3.10
test_app 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- firebase_auth 4.2.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.4.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_ui_auth 1.1.3 [email_validator firebase_auth firebase_core firebase_dynamic_links firebase_ui_localizations firebase_ui_oauth flutter flutter_localizations flutter_svg]
- firebase_ui_oauth 1.1.3 [desktop_webview_auth firebase_auth firebase_ui_auth flutter_svg flutter]
- firebase_ui_oauth_google 1.0.10 [firebase_auth firebase_ui_oauth flutter google_sign_in]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.0.10 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.9.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.1.1 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- crypto 3.0.2 [typed_data]
- desktop_webview_auth 0.0.11 [crypto flutter http flutter_web_plugins plugin_platform_interface]
- email_validator 2.1.17
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 6.11.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.2.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.2 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_dynamic_links 5.0.9 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.3+24 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_ui_localizations 1.0.1 [flutter flutter_localizations intl path]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_svg 1.1.6 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- google_sign_in 5.4.2 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- google_sign_in_android 6.1.4 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.5.1 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.3.0 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.10.2 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.4
- lints 2.0.1
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- path 1.8.2
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- petitparser 5.1.0 [meta]
- plugin_platform_interface 2.1.3 [meta]
- quiver 3.1.0 [matcher]
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- vector_math 2.1.2
- xml 6.1.0 [collection meta petitparser]
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the code sample. Using it, seeing same behavior as reported.

**Comment by cybex-dev** [comment]
Same issue using Google Provider login with `firebase_auth_web`

Using BLoC code:

```dart
_firebaseAuth.userChanges().listen((user) {
  // trigger on any user/auth changes
  add(AuthUserChanged(authUser: user));
});

_firebaseAuth.authStateChanges().listen((user) {
  // trigger on any auth changes (e.g. login/logout)
  add(AuthUserChanged(authUser: user));
});
```

where I'd expect both `authStateChanges` and `userChanges` to trigger upon logging in with [google_sign_in](https://pub.dev/packages/google_sign_in) however neither do.

_Workaround?_: A page refresh (web) or hot reload

**Comment by Robertrobinson777** [comment]
Still facing this issue
RegisterScreen() does not trigger AuthStateChangeAction event
