### ISSUE TITLE
🐛 [futterfire_ui] Crash using auth providers 

### ISSUE THREAD

**Issue by Tom3652** [firebase/flutterfire#10158]
## Bug report

**Describe the bug**

I had opened #8555 and it seems fixed but i have still received crashes from Facebook And Twitter the 12 of December, my latest app release (in production) was made at the beginning of december using the latest version of all firebase plugins including this one.

Here is the facebook crash : 

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.listeen.android/com.facebook.FacebookActivity}: A valid Facebook app id must be set in the AndroidManifest.xml or set by calling FacebookSdk.setApplicationId before initializing the sdk.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.listeen.android/com.maru.twitter_login.chrome_custom_tabs.ChromeCustomTabsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

I have these crashes but i don't even use the Facebook authentication or Twitter login in my app, only Firebase basic login and using this plugin for UI and auth flow.

### Steps to reproduce

I am unable to reproduce this.

### Expected behavior

`flutterfire_ui` should not embed `facebook_auth` or `twitter_login` if not used. 

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details>
<summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@Tom3652 Not sure what exactly could be causing this, but can you confirm if you don't have any related entries in your manifest file ? Based on `java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference` error you posted, please check if [this](https://issuetracker.google.com/issues/200437477?pli=1) issue from native repo could be related / relevant.

**Comment by Tom3652** [comment]
Hi @darshankawar thanks for the link you provided. 
I can confirm that i have not any related entries in my manifest file, and i also confirm that this only happens with Nexus 5X phone's so far as it is said in the conversation.

**Comment by darshankawar** [comment]
Ok, I think it would be best to followup in that issue, so I will go ahead and close this. If you disagree, write in comments and I'll reopen it.
