### ISSUE TITLE
🐛 [firebase_auth] NPE: io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.removeEventListeners

### ISSUE THREAD

**Issue by rohansohonee1** [firebase/flutterfire#10164]
## Bug report

**Describe the bug**
NPE reported from firebase crashlytics.

### Steps to reproduce
Unable to reproduce.

### Expected behavior

Should not crash.

---

## Additional context
Stacktrace:
```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void fe.d$d.h(java.lang.Object)' on a null object reference
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.removeEventListeners(FlutterFirebaseAuthPlugin.java)
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.onDetachedFromEngine(FlutterFirebaseAuthPlugin.java)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java)
       at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java)
       at android.app.Activity.performDestroy(Activity.java:6442)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3877)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3908)
       at android.app.ActivityThread.access$1500(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1410)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:731)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
```

Device details:
```
Brand:LGE
Model:LG K8
Orientation: Portrait
RAM free: 240.06 MB
Disk free: 393.45 MB
Operating System
Version:Android 6.0
Orientation: Portrait
Rooted:No
Crash
Date:Dec 22, 2022, 6:52:46 AM
```
---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6.2 21G320 darwin-x64, locale en-US)                                                                                                                                                   Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

---

Pubspec.yaml
```
firebase_core: 2.3.0
firebase_auth: 4.1.3
```

**Comment by darshankawar** [comment]
Since this seems to be coming from production and no concrete steps to replicate and code sample, I'll label this for team's attention and insights.
May be similar to: https://github.com/firebase/flutterfire/issues/9210

**Comment by Lyokone** [comment]
Hello I'm going to take a look at this.
You can get readable bug report by following those steps: https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=flutter / https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=android

**Comment by rohansohonee1** [comment]
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void onCancel(java.lang.Object)' on a null object reference
https://github.com/firebase/flutterfire/blob/ab39d09e1a24ad6cfba25b35b2435aef342d8e87/packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java#L1822
