### ISSUE TITLE
🐛 [firebase_storage] FirebaseStorage.instance.ref().child("<path>").delete() throws 404 Not Found

### ISSUE THREAD

**Issue by AAGUPTA6209** [firebase/flutterfire#10205]
## Bug report

**Describe the bug**
I want to delete a folder in firebase storage through my flutter app on android.
For that I am using firebase_storage package.
But I am unable to delete the folder at specified path.

### Steps to reproduce

1. Just create a file in firebase storage as images/image.jpg.
2. Now try deleting images folder as: await FirebaseStorage.instance.ref().child("images").delete();

### Expected behavior

Bucket at the provided path must have been deleted.

### Sample code

```
final cloudPath = "images";
var ref = FirebaseStorage.instance.ref();
await ref.child(cloudPath).delete();
```
---

## Got this exception

```
E/StorageException(18184): StorageException has occurred.
E/StorageException(18184): Object does not exist at location.
E/StorageException(18184):  Code: -13010 HttpResult: 404
E/StorageException(18184): {  "error": {    "code": 404,    "message": "Not Found."  }}
E/StorageException(18184): java.io.IOException: {  "error": {    "code": 404,    "message": "Not Found."  }}  
E/StorageException(18184):      at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:445)
E/StorageException(18184):      at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(NetworkRequest.java:462)
E/StorageException(18184):      at com.google.firebase.storage.network.NetworkRequest.processResponseStream(NetworkRequest.java:453)
E/StorageException(18184):      at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:272)
E/StorageException(18184):      at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:289)
E/StorageException(18184):      at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:76)
E/StorageException(18184):      at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:68)
E/StorageException(18184):      at com.google.firebase.storage.DeleteStorageTask.run(DeleteStorageTask.java:59)
E/StorageException(18184):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/StorageException(18184):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/StorageException(18184):      at java.lang.Thread.run(Thread.java:1012)
```

**Comment by darshankawar** [comment]
@AAGUPTA6209 
As the error indicates, `Object does not exist at location.`, ie, it is unable to find `images` as mentioned in your code.
You should try `await FirebaseStorage.instance.ref().child("images/image.jpg").delete();` which will delete the said file from `images` path and ultimately `images` folder as well, if, the folder is also created programmatically.
See [this](https://stackoverflow.com/a/67006510) for your further reference and check if it helps in your case.

**Comment by AAGUPTA6209** [comment]
Thank you that helped, so deleting last file in folder automatically deletes the folder.
