### ISSUE TITLE
🐛 [firebase_realtime_database] Shows permission-denied error but client has access when tried at playground

### ISSUE THREAD

**Issue by fernan542** [firebase/flutterfire#10290]
## Bug report

**Describe the bug**
The app has Firebase Auth feature and specifically uses Facebook Auth.
When the user tried to register using Facebook Auth, the app sends request at backend (Go) to set the user's `emailVerification` status to `true` or verified. App will call reload function and will not proceed until it detected that the email is verified.

After the app detected that the user's email was verified, the app will move to main menu then the app shows an error that the user does not have permission when trying to access Firebase Realtime Database.
Rules on Firebase Realtime Database:
```
{
  "rules": {
    // Only verified users can access RtDb.
       ".read": "auth.uid !== null && auth.token.email_verified === true",
       ".write": "auth.uid !== null && auth.token.email_verified === true",
  }
}
```

In order to get rid of the error, the new registered user needs to completely restart the app.

### Expected behavior

The user should be able to use the app since it was already reloaded and verified without manually restarting the whole app.

## Additional context

One thing I guess is that the Firebase Realtime Database is not in-sync with the Firebase Auth's User status when app called `reload()`.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19042.1706], locale en-PH)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.74.3)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
firebase_database 10.0.9
flutter_facebook_auth: ^4.4.1+1
firebase_auth: ^4.2.0
firebase_core: ^2.4.0
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @fernan542 
Can you provide the complete error log ?

**Comment by fernan542** [comment]
Hello, thanks for your reply. Here's the full error log.
```
E/firebase_database( 3121): 	at io.flutter.plugins.firebase.database.FirebaseDatabasePlugin.lambda$setValue$3$io-flutter-plugins-firebase-database-FirebaseDatabasePlugin(FirebaseDatabasePlugin.java:208)
E/firebase_database( 3121): 	at io.flutter.plugins.firebase.database.FirebaseDatabasePlugin$$ExternalSyntheticLambda5.run(Unknown Source:6)
E/firebase_database( 3121): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/firebase_database( 3121): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/firebase_database( 3121): 	at java.lang.Thread.run(Thread.java:923)
E/firebase_database( 3121): Caused by: com.google.firebase.database.DatabaseException: Firebase Database error: Permission denied
E/firebase_database( 3121): 	at com.google.firebase.database.DatabaseError.toException(DatabaseError.java:230)
E/firebase_database( 3121): 	at com.google.firebase.database.core.utilities.Utilities$1.onComplete(Utilities.java:253)
E/firebase_database( 3121): 	at com.google.firebase.database.core.Repo$7.run(Repo.java:435)
E/firebase_database( 3121): 	at android.os.Handler.handleCallback(Handler.java:938)
E/firebase_database( 3121): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/firebase_database( 3121): 	at android.os.Looper.loop(Looper.java:233)
E/firebase_database( 3121): 	at android.app.ActivityThread.main(ActivityThread.java:8063)
E/firebase_database( 3121): 	at java.lang.reflect.Method.invoke(Native Method)
E/firebase_database( 3121): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
E/firebase_database( 3121): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
[log] [firebase_database/permission-denied] Client doesn't have permission to access the desired data.
```

**Comment by fernan542** [comment]
Found a resolution, the problem was that the Token from the previous user (unverified) was saved from the Realtime Database's instance which does not know that the user was updated or verified.

So I added this command to `force refresh` the token after successful email verification.
```
      final loginResult = await _facebookSignIn.login(
        permissions: facebookPermissions,
      );

      if (loginResult.accessToken != null) {
        final facebookAuthCredential = FacebookAuthProvider.credential(
          loginResult.accessToken!.token,
        );

        await _firebaseAuth.signInWithCredential(facebookAuthCredential);

        // Validate if account was already verified.
        if (_firebaseAuth.currentUser!.emailVerified) return;

        // Update fb auth status at backend.
        await _authApi.updateFirebaseUserEmailVerification(
          email: _firebaseAuth.currentUser!.email!,
        );

        // Refresh the token of firebase account so the other
        // dependencies like Realtime Database will be refresh too.
        await _firebaseAuth.currentUser!.getIdToken(true);
      }
```

Many thanks!
