### ISSUE TITLE
🐛 [flutterfire cli]  FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by fullflash** [firebase/flutterfire#10341]
Flutterfire config is not working 

https://firebase.flutter.dev/docs/overview/

```
flutterfire configure
⠦ Fetching available Firebase projects...                                                            
Unhandled exception:
FormatException: Unexpected character (at character 1)
{
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:612:36)
#5      runFirebaseCommand (package:flutterfire_cli/src/firebase.dart:95:25)
<asynchronous suspension>
#6      getProjects (package:flutterfire_cli/src/firebase.dart:114:20)
<asynchronous suspension>
#7      ConfigCommand._selectFirebaseProject (package:flutterfire_cli/src/commands/config.dart:300:24)
<asynchronous suspension>
#8      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:390:37)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     main (file:///Users/*****/.pub-cache/hosted/pub.dartlang.org/flutterfire_cli-0.2.7/bin/flutterfire.dart:57:5)
<asynchronous suspension>
```

```
Flutter (Channel stable, 3.3.8, on macOS 12.6.1 21G217 darwin-x64, locale
    en-TR)
    • Flutter version 3.3.8 on channel stable at /Users/fersmart/SDK_all/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (3 months ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0
```

flutterfire_cli 0.2.7.

**Comment by darshankawar** [comment]
@fullflash 
Please file `flutterfire configure` related issues in dedicated repo: https://github.com/invertase/flutterfire_cli/issues

I already see a similar issue there in which you can follow-up on: https://github.com/invertase/flutterfire_cli/issues/55

Closing from here.
