### ISSUE TITLE
🐛 [firebase_performance/unknown] Attempt to invoke virtual method 'void o6.e.c(int)' on a null object reference

### ISSUE THREAD

**Issue by PawanFyers** [firebase/flutterfire#10351]
## Bug report

**Describe the bug**
Firebase App Performance plugin throws null object reference Exception when `await metric.stop()` is called.

### Steps to reproduce
Call below from your network layer aka http call

```
HttpMetric? performanceMetric =
          FyAppPerformance.startNetworkMonitoring(url, requestType);
```

Pass your HTTP response with performanceMetric in below function.
```
if (performanceMetric != null) {
        FyAppPerformance.stopNetworkMonitoring(performanceMetric, response);
      }
```

Below function will be called.
```
///This Function is used to stop Network metric calculations
  static void stopNetworkMonitoring(
      HttpMetric metric, http.Response response) async {
    try {
      metric.responseContentType = response.headers['Content-Type'];
      metric.httpResponseCode = response.statusCode;
      metric.responsePayloadSize = response.contentLength;
      await metric.stop();
    } catch (exception, stackTrace) {
      fyPrint(
          "FyAppPerformance stopNetworkMonitoring Error : Resposne ${response.body}",
          recordCrash: true,
          exception: exception,
          stackTrace: stackTrace,
          fatal: true);
    }
  }
```

### Expected behavior
Firebase App Performance plugin should not throw null object reference Exception

---

## Additional context

```
# Crashlytics - Stack trace
# Application: com.fyers.trader2
# Platform: android
# Version: 2.0.3 (25)
# Issue: 9d710aa775863c762d4beeed75ca8006
# Session: 63D8B67D013700013B4CEE7BF2426F98_DNE_0_v2
# Date: Tue Jan 31 2023 13:15:31 GMT+0530 (India Standard Time)

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: [firebase_performance/unknown] Attempt to invoke virtual method 'void o6.e.c(int)' on a null object reference. Error thrown FyAppPerformance stopNetworkMonitoring Error : Resposne {"code":200,"message":"","s":"ok","overall":{"count_total":0,"pnl_perc":0,"total_current_value":0,"total_investment":0,"total_pl":0},"holdings":[]}.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:296)
       at MethodChannelHttpMetric.stop(method_channel_http_metric.dart:80)
       at FyAppPerformance.stopNetworkMonitoring(fy_app_performance.dart:42)

pool-32-thread-20:
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:461)
       at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
       at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

firebase-installations-executor-18:
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

ReferenceQueueDaemon:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:218)
       at java.lang.Daemons$Daemon.run(Daemons.java:140)
       at java.lang.Thread.run(Thread.java:923)

PlatformServiceBridgeHandlerThread:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:67)

pool-2-thread-1:
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

Okio Watchdog:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:313)
       at com.android.okhttp.okio.AsyncTimeout.access$000(AsyncTimeout.java:42)
       at com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:288)

GmsDynamite:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.google.android.gms.dynamite.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)

CleanupReference:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
       at Wj.run(Wj.java:3)

FinalizerWatchdogDaemon:
       at java.lang.Thread.sleep(Thread.java)
       at java.lang.Thread.sleep(Thread.java:442)
       at java.lang.Thread.sleep(Thread.java:358)
       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepForNanos(Daemons.java:391)
       at java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:420)
       at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:326)
       at java.lang.Daemons$Daemon.run(Daemons.java:140)
       at java.lang.Thread.run(Thread.java:923)

FrameMetricsAggregator:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:67)

Firebase-Messaging-Init:
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1120)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
       at java.lang.Thread.run(Thread.java:923)

FinalizerDaemon:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:274)
       at java.lang.Daemons$Daemon.run(Daemons.java:140)
       at java.lang.Thread.run(Thread.java:923)

Chrome_ProcessLauncherThread:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:67)

pool-9-thread-1:
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

awaitEvenIfOnMainThread task continuation executor1:
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
       at java.lang.Thread.run(Thread.java:923)

com.it_nomads.fluttersecurestorage.worker:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:67)

JavaBridge:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:67)

ScionFrontendApi:
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

GoogleApiHandler:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:67)

ConnectivityThread:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:67)

queued-work-looper:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:67)

pool-5-thread-1:
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

pool-4-thread-9:
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

firebase-installations-executor-17:
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

Firebase-Messaging-Topics-Io:
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1120)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
       at java.lang.Thread.run(Thread.java:923)

Crashlytics Exception Handler1:
       at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
       at java.lang.Thread.getStackTrace(Thread.java:1736)
       at java.lang.Thread.getAllStackTraces(Thread.java:1812)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateThreadsList(CrashlyticsReportDataCapture.java:295)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateExecutionData(CrashlyticsReportDataCapture.java:266)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateEventApplicationData(CrashlyticsReportDataCapture.java:216)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.captureEventData(CrashlyticsReportDataCapture.java:102)
       at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.persistEvent(SessionReportingCoordinator.java:274)
       at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.persistFatalEvent(SessionReportingCoordinator.java:127)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2.call(CrashlyticsController.java:203)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2.call(CrashlyticsController.java:188)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(CrashlyticsBackgroundWorker.java:105)
       at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
       at java.lang.Thread.run(Thread.java:923)

com.google.firebase.crashlytics.startup1:
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
       at java.lang.Thread.run(Thread.java:923)

com.it_nomads.fluttersecurestorage.worker:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:67)

Measurement Worker:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at ir.run(ir.java:7)

main:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:8051)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

MessengerIpcClient:
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1120)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
       at java.lang.Thread.run(Thread.java:923)
```

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-arm, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
dependencies:
  cached_network_image: ^3.2.1
  card_swiper: ^2.0.4
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  convert: ^3.0.2
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  device_info_plus: ^4.1.2
  el_tooltip: ^1.0.4
  equatable: ^2.0.5
  firebase_analytics: ^10.1.0
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.9
  firebase_messaging: ^14.2.1
  firebase_performance: ^0.9.0+9
  fl_chart: ^0.55.2
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.2.1
  flutter_bloc: ^8.1.1
  flutter_html:
    path: ./plugins/flutter_html-master
  flutter_html_all:
    path: ./plugins/flutter_html-master/packages/flutter_html_all
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: any
  flutter_secure_storage: ^5.0.2
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.0.3
  fluttertoast: ^8.1.2
  google_fonts: ^3.0.1
  hive: ^2.2.2
  hsdartlib:
    path: ./plugins/hsbroadcast_dartsdk_3.2.0
  http: ^0.13.4
  hydrated_bloc: ^9.0.0
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  just_the_tooltip:
    path: ./plugins/just_the_tooltip
  jwt_decoder: ^2.0.1
  local_auth: ^2.1.2
  lottie: ^1.2.2
  optiongreek:
    path: ./plugins/optiongreek
  package_info: ^2.0.2
  path_provider: ^2.0.10
  phone_number: ^0.12.0+2
  pinput: ^2.2.16
  pub_semver: ^2.1.1
  pull_to_refresh:
    git:
      url: https://github.com/ymback/flutter_pulltorefresh.git
  razorpay_flutter_customui: ^1.3.3
  share_plus: ^6.2.0
  signal_strength_indicator: ^0.4.1
  sms_autofill: ^2.2.0
  stream_transform: ^2.0.0
  table_sticky_headers:
    path: ./plugins/sticky-headers-table
  timelines: ^0.1.0
  timer_builder: ^2.0.0
  url_launcher: ^6.1.5
  visibility_detector: ^0.3.3
  web_socket_channel: ^2.2.0
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.19.2 #Refer: https://stackoverflow.com/a/68830052/2975475 for explanations
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @PawanFyers 


> FyAppPerformance.startNetworkMonitoring(url, requestType);

This method doesn't seem to be part of `firebase_performance` if I am not wrong. Can you provide complete minimal reproducible code sample without third party plugins that triggers the reported crash ?

Also, please check out plugin example and see if using it, the same crash occurs or not because I couldn't find the `startNetworkMonitoring` and `stopNetworkMonitoring` methods under `FirebasePerformance` class.

**Comment by VincentDR** [comment]
Same issues here ('with reason [firebase_performance/unknown] Attempt to invoke virtual method 'void c4.e.c(int)' on a null object reference') after upgrading from 'firebase_performance: ^0.9.0+1' to 'firebase_performance: ^0.9.0+10'.
Will update this with code and more info.

**Comment by noorbhatia** [comment]
Facing the same issue in some android devices in our production apps. @darshankawar  Any updates on this?

**Comment by yosikal** [comment]
Also facing the same issue on Android devices in our production app. This started happening after upgrading to firebase performance ^0.9.0+11 with firebase core ^2.5.0

**Comment by mulderpf** [comment]
I upgraded from Firebase Performance ^0.4.3 to ^0.9.0+11 and Firebase Core from ^0.5.3 to ^2.5.0 and using the exact same code as before for tracing http calls, I am now seeing the same error in production.  (The underlying code didn't change and has been running in production for about 2 years (around 8k users per day).

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: [firebase_performance/unknown] Attempt to invoke virtual method 'void com.google.firebase.perf.metrics.HttpMetric.setHttpResponseCode(int)' on a null object reference
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:315)
       at MethodChannelHttpMetric.stop(method_channel_http_metric.dart:80)
```

**Comment by votruk** [comment]
We're facing the same issue:
```
io.flutter.plugins.firebase.crashlytics.FlutterError: [firebase_performance/unknown] Attempt to invoke virtual method 'void nc.f.c(int)' on a null object reference. Error thrown Request failed.
```

I was compelled to remove the performance monitor until a fix is added. Unfortunately, I am unable to replicate the issue on my local system, and therefore, I am unable to provide any assistance at this time.

By the way, does anyone know if this issue is specifically related to a certain version of the plugin? Would downgrading the plugin to a previous version potentially resolve the problem?

**Comment by mulderpf** [comment]
@darshankawar Please can you look at the original code again, the author included the method that you said seemed to be part of a third-party plugin which only include code which calls this plugin, nothing else.  There is definitely an issue happening here and I am seeing a substantial number of crash reports with this issue in.

Here is my code and I am seeing the same thing (and same as the author tried to do with the null check, I try to throw away the errors, but they are still coming through on my Crashlytics (note, I only added in the extra try because I started seeing all these errors appear, but they still happen - this didn't happen in the previous version of the plugin I used with the same code):

`  Future<http.Response> getResponseFromUrl(String url,
      {Map<String, String> headers}) async {
    log.i('getResponseFromUrl(\'$url\', $headers');
    if (await _isConnected()) {
      Map<String, String> newheaders = _addUserAgentToHeaders(headers);
      log.v('Headers: $newheaders');
      String encodedUrl = Uri.encodeFull(url);
      Uri uri = Uri.parse(encodedUrl);
      final HttpMetric metric = FirebasePerformance.instance
          .newHttpMetric(encodedUrl, HttpMethod.Get);
      await metric.start();
      http.Response response;
      try {
        response = await _client.get(uri, headers: newheaders);
        metric
          ..responsePayloadSize = response.contentLength
          ..responseContentType = response.headers['Content-Type']
          ..requestPayloadSize = url.length
          ..httpResponseCode = response.statusCode;
      } catch (e) {
        throw new ConnectionError(
            'An error occurred trying to get the data. Error is: ${e.toString()}');
      } finally {
        try {
          metric.stop();
        } catch (e) {
          //Suppressing any error as this is not important.
        }
      }
      return response;
    } else
      throw new ConnectionError('No internet connection');
  }
`

**Comment by Scuuter** [comment]
I have the same issue in my app after upgrading packages from `firebase_core: 2.4.0, firebase_performance: 0.9.0+7` to `firebase_core: 2.5.0, firebase_performance: 0.9.0+11`

**Comment by darshankawar** [comment]
Thanks for all the reports and updates. I verified this behavior using plugin example on Android but was unable to replicate the crash.
Based on all the reports, I'll go ahead and label it for team's attention and action.

/cc @Lyokone

**Comment by ProFive** [comment]
The same issue 
FirebaseException: [firebase_performance/unknown] Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
