### ISSUE TITLE
🐛 cloud_firestore: ^3.5.1  java.lang.RuntimeException: Internal error in Cloud Firestore (24.4.2).

### ISSUE THREAD

**Issue by Vish88781** [firebase/flutterfire#10368]
## Bug report
java.lang.RuntimeException: Internal error in Cloud Firestore (24.4.2).
**Describe the bug**
 when  i  send data to firebase in release mode cloud firestore kill the app

### Steps to reproduce

1.  Run app on release mode 

2.  Insert Data using Firebase function 

 users.add(({
        "timestamp": event.timestamp,
        "odometer": event.odometer,
        "Date": DateTime.now(),
        // "distance": distanceTravel.value,
        "Permission": {"Permission":checkAllPermission.value},
        "PushType": 'locationCase',
        "location":  {
          "coords":  {
            "accuracy": event.coords.accuracy,
            "latitude" : event.coords.latitude,
            "longitude" : event.coords.longitude,
          },
          "timestamp": event.timestamp,
          "odometer": event.odometer,
        }
      })).then((value) => print("location push on firebase")).catchError(onError);}

3 > Error on console
E/AndroidRuntime(29240): FATAL EXCEPTION: main
E/AndroidRuntime(29240): Process: Package Name, PID: 29240
E/AndroidRuntime(29240): java.lang.RuntimeException: Internal error in Cloud Firestore (24.4.2).
E/AndroidRuntime(29240): 	at androidx.activity.p.run(:1)
E/AndroidRuntime(29240): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(29240): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(29240): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(29240): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
E/AndroidRuntime(29240): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29240): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(29240): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/AndroidRuntime(29240): Caused by: i3.g: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
E/AndroidRuntime(29240): 	at i3.I.o(:3)

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19045.2486], locale en-VG)
[√] Windows Version (Installed version of Windows is version 10 or higher)                       
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web   

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.19.0
Flutter SDK 3.7.0
appname1.0.0+1

dependencies:
- activity_recognition_flutter 4.2.0 [flutter]
- amazon_cognito_identity_dart_2 3.1.1 [convert crypto http js]
- android_alarm_manager_plus 2.1.0 [flutter]
- animated_text_kit 4.2.2 [flutter characters]
- app_settings 4.2.0 [flutter]
- app_tracking_transparency 2.0.3 [flutter]
- assets_audio_player 3.0.6 [flutter rxdart uuid http path_provider assets_audio_player_web]
- auto_size_text 3.0.0 [flutter]
- background_geolocation_firebase 1.0.0 [flutter]
- badges 2.0.3 [flutter]
- cached_network_image 3.2.3 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- camera 0.10.3 [camera_android camera_avfoundation camera_platform_interface camera_web flutter flutter_plugin_android_lifecycle quiver]
- cloud_firestore 3.5.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- connectivity_plus 2.3.9 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]    
- csv 5.0.1
- cupertino_icons 1.0.5
- data_connection_checker_tv 0.3.5-nullsafety
- datetime_picker_formfield 2.0.1 [flutter intl]
- device_info_plus 3.2.4 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- dio 4.0.6 [http_parser path]
- eva_icons_flutter 3.1.0 [flutter]
- exif 3.1.2 [args collection convert json_annotation sprintf]
- file 6.1.4 [meta path]
- firebase_auth 3.11.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.24.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_crashlytics 2.9.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_database 9.1.7 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_dynamic_links 4.3.11 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 12.0.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_background_geolocation 4.9.0 [flutter collection background_fetch]
- flutter_barcode_scanner 2.0.0 [flutter flutter_plugin_android_lifecycle]
- flutter_calendar_carousel 2.4.1 [intl flutter]
- flutter_datetime_picker 1.5.1 [flutter]
- flutter_feather_icons 2.0.0+1 [flutter]
- flutter_image_compress 1.1.3 [flutter]
- flutter_inappwebview 5.4.3+7 [flutter]
- flutter_local_notifications 12.0.4 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_rating_bar 4.0.1 [flutter]
- flutter_share 2.0.0 [flutter]
- flutter_speed_dial 6.2.0 [flutter]
- fluttericon 2.0.0 [flutter]
- font_awesome_flutter 10.3.0 [flutter]
- geocoding 2.0.5 [flutter geocoding_platform_interface]
- geolocator 9.0.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- get 4.6.5 [flutter]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- google_sign_in 5.4.4 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- http 0.13.5 [async http_parser meta path]
- image 3.3.0 [archive meta xml]
- image_picker 0.8.6+1 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- intl 0.17.0 [clock path]
- keyboard_actions 4.1.0 [flutter]
- launch_review 3.0.1 [flutter]
- local_auth 2.1.3 [flutter local_auth_android local_auth_ios local_auth_platform_interface local_auth_windows]
- location 4.4.0 [flutter location_platform_interface location_web]
- lottie 1.4.3 [archive flutter path vector_math]
- multiple_random_choice 0.1.3+1
- numeric_keyboard 1.1.0 [flutter]
- open_filex 3.4.0 [flutter ffi]
- optimize_battery 0.0.4 [flutter]
- otp_timer_button 1.1.0 [flutter]
- path 1.8.2
- path_provider 2.0.12 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- pdf 3.8.4 [archive barcode crypto image meta path_parsing vector_math xml]
- permission_handler 10.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- persistent_bottom_nav_bar 5.0.2 [flutter]
- pin_code_fields 7.4.0 [flutter]
- pinput 2.2.23 [flutter smart_auth universal_platform]
- place_picker 0.9.20-nullsafety [flutter http google_maps_flutter location]
- point_in_polygon 1.0.0 [flutter]
- polymaker 1.0.3 [google_maps_flutter geolocator provider flutter]
- shared_preferences 2.0.17 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferen
ces_web shared_preferences_windows]
- shimmer 2.0.0 [flutter]
- sqflite 2.2.4+1 [flutter sqflite_common path]
- timezone 0.9.1 [path]
- tutorial_coach_mark 1.2.4 [flutter]
- url_launcher 6.1.8 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_wind
ows]
- wakelock 0.6.2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- webview_flutter 3.0.4 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- change_app_package_name 1.1.0
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta s
ource_span stream_channel string_scanner term_glyph]

dependency overrides:
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]
- timezone 0.9.1 [path]

transitive dependencies:
- _flutterfire_internals 1.0.2 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- archive 3.3.6 [crypto path pointycastle]
- args 2.3.2
- assets_audio_player_web 3.0.6 [flutter flutter_web_plugins]
- async 2.10.0 [collection meta]
- background_fetch 1.1.4 [flutter]
- barcode 2.2.3 [meta qr]
- boolean_selector 2.1.1 [source_span string_scanner]
- cached_network_image_platform_interface 2.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.2 [flutter flutter_cache_manager cached_network_image_platform_interface]
- camera_android 0.10.3 [camera_platform_interface flutter flutter_plugin_android_lifecycle stream_transform]
- camera_avfoundation 0.9.11 [camera_platform_interface flutter stream_transform]
- camera_platform_interface 2.3.4 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.3.1+1 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.7.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.10 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.17.0
- connectivity_plus_linux 1.3.1 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.6 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.3 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.5 [connectivity_plus_platform_interface flutter_web_plugins flutter js]
- connectivity_plus_windows 1.2.2 [connectivity_plus_platform_interface flutter]
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+4 [js meta]
- crypto 3.0.2 [typed_data]
- dbus 0.7.4 [args ffi meta xml]
- device_info_plus_linux 2.1.1 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 2.2.3 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 2.6.1 [flutter meta plugin_platform_interface]
- device_info_plus_web 2.1.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 2.1.1 [device_info_plus_platform_interface ffi flutter win32]
- fake_async 1.3.1 [clock collection]
- ffi 1.2.1
- firebase_auth_platform_interface 6.10.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 4.6.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_web 1.7.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.3.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_platform_interface 0.2.2+7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.1+9 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_dynamic_links_platform_interface 0.2.3+15 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.2.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.2.0 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_local_notifications_linux 1.0.0 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 6.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- geocoding_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- geolocator_android 4.1.7 [flutter geolocator_platform_interface]
- geolocator_apple 2.2.5 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.7 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.6 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.1 [flutter geolocator_platform_interface]
- google_maps_flutter 2.2.3 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface]
- google_maps_flutter_android 2.4.3 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.1.13 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.2.5 [collection flutter plugin_platform_interface stream_transform]
- google_sign_in_android 6.1.5 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.5.1 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.3.0 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.10.2+1 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.5+5 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.10 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.6+6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- js 0.6.5 [meta]
- json_annotation 4.8.0 [meta]
- lints 2.0.1
- local_auth_android 1.0.17 [flutter flutter_plugin_android_lifecycle intl local_auth_platform_interface]
- local_auth_ios 1.0.12 [flutter intl local_auth_platform_interface]
- local_auth_platform_interface 1.0.6 [flutter plugin_platform_interface]
- local_auth_windows 1.0.5 [flutter local_auth_platform_interface]
- location_platform_interface 2.3.0 [flutter meta plugin_platform_interface]
- location_web 3.1.1 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- matcher 0.12.13 [meta stack_trace]
- material_color_utilities 0.2.0
- meta 1.8.0
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 1.0.2 [flutter flutter_blurhash]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.0.22 [flutter path_provider_platform_interface]
- path_provider_foundation 2.1.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.5 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.7 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_android 10.2.0 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.7 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.9.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.2 [flutter permission_handler_platform_interface]
- petitparser 5.1.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.3 [meta]
- pointycastle 3.6.2 [collection convert js]
- process 4.2.4 [file path platform]
- provider 6.0.5 [collection flutter nested]
- qr 3.0.1 [meta]
- quiver 3.2.1 [matcher]
- rxdart 0.27.7
- shared_preferences_android 2.0.15 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.1.3 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.3 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.1.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.3 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- smart_auth 1.0.8 [flutter flutter_web_plugins]
- source_span 1.9.1 [collection path term_glyph]
- sprintf 6.0.2
- sqflite_common 2.4.2+2 [synchronized path meta]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- synchronized 3.0.1
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- universal_platform 1.0.0+1
- url_launcher_android 6.0.23 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.18 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.2 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.2 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.1 [flutter plugin_platform_interface]
- url_launcher_web 2.0.14 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.3 [flutter url_launcher_platform_interface]
- uuid 3.0.7 [crypto]
- vector_math 2.1.4
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- webview_flutter_android 2.10.4 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.9.5 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 2.9.5 [flutter path webview_flutter_platform_interface]
- win32 2.6.1 [ffi]
- xdg_directories 0.2.0+3 [meta path process]
- xml 6.2.2 [collection meta petitparser]

```

</details>

---

**Comment by Vish88781** [comment]
@eBouvard  i will try

**Comment by darshankawar** [comment]
@Vish88781 
Also check [this](https://github.com/firebase/flutterfire/issues/8265#issuecomment-1069563176) and see if it helps in your case.

**Comment by Vish88781** [comment]
@darshankawar  thanks for response but @eBouvard  suggestion work for me

**Comment by volvicoasis** [comment]
Sorry but closing is not a good solution, we cant deliver application without minifyEnabled and shrinkResources in build.gradle as @eBouvard say. 
Please can you provide a bug fix, better than a workaround ....

**Comment by Djihanegh** [comment]
i'am not using the minifyEnabled and shrinkResources in build.gradle and still getting this bug...
