### ISSUE TITLE
🐛 Unable to run app in iOS due to exception running `pod install`

### ISSUE THREAD

**Issue by juicemia** [firebase/flutterfire#10455]
## Bug report

**Describe the bug**
I'm following the [Flutter Firebase lab](https://firebase.google.com/codelabs/firebase-auth-in-flutter-apps#4) and I'm
unable to run the app due to an exception being thrown from `pod install`. I don't think this is an issue with my Flutter
setup because I can run the getting started app successfully.

### Steps to reproduce

1. Clone https://github.com/flutter/codelabs
2. `cd` into `firebase-auth-flutterfire-ui/start`
3. `flutter pub add firebase_core`
4. `flutter pub add firebase_auth`
5. `flutter pub add flutterfire_ui`
6. Follow the lab until you complete [step 3](https://firebase.google.com/codelabs/firebase-auth-in-flutter-apps#3).
7. Try running the app using `flutter run`.

### Expected behavior

The app should open on my already running simulator.

### Sample project

https://github.com/flutter/codelabs/tree/main/firebase-auth-flutterfire-ui/start

---

## Additional context

I'm getting the following markdown template:

### Command
```
/Users/juice/.rbenv/versions/3.2.1/bin/pod install --verbose
```

### Report
* What did you do?
* What did you expect to happen?
* What happened instead?

### Stack

```
    CocoaPods : 1.11.3
        Ruby : ruby 3.2.1 (2023-02-08 revision 31819e82c8) [arm64-darwin21]
    RubyGems : 3.4.6
        Host : macOS 12.6 (21G115)
        Xcode : 14.2 (14C18)
            Git : git version 2.39.1
Ruby lib dir : /Users/juice/.rbenv/versions/3.2.1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', {
    'Debug' => :debug,
    'Profile' => :release,
    'Release' => :release,
}
def flutter_root
    generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
    unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
    end
    raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
flutter_ios_podfile_setup
target 'Runner' do
    use_frameworks!
    use_modular_headers!
    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    end
end
```

### Error

```
JSON::ParserError - unexpected token at '"src/core/ext/upb-generated/envoy/config/endpoint/v3/endpoint_components.'
2
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/3.2.0/json/common.rb:216:in `parse'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:748:in `from_string'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:722:in `from_file'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source.rb:188:in `specification'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/3.2.0/delegate.rb:348:in `block in delegating_block'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/3.2.0/delegate.rb:349:in `block in delegating_block'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:809:in `block in group_possibilities'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `reverse_each'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `group_possibilities'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:779:in `possibilities_for_requirement'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/Users/juice/.rbenv/versions/3.2.1/bin/pod:25:in `load'
/Users/juice/.rbenv/versions/3.2.1/bin/pod:25:in `<main>'
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.6 21G115 darwin-arm64, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.75.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.19.2
Flutter SDK 3.7.3
complete 1.0.0+1

dependencies:
- cloud_firestore 4.4.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth 4.2.6 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.5.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutterfire_ui 0.4.3+20 [cloud_firestore collection crypto desktop_webview_auth email_validator firebase_auth firebase_core firebase_database firebase_dynamic_links flutter flutter_facebook_auth flutter_localizations flutter_svg google_sign_in sign_in_with_apple twitter_login]
- google_sign_in 5.4.4 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.0.13 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.10.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.11.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.3.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.17.0
- crypto 3.0.2 [typed_data]
- desktop_webview_auth 0.0.11 [crypto flutter http flutter_web_plugins plugin_platform_interface]
- email_validator 2.1.17
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 6.11.8 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.2.5 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.3 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.1.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database 10.0.11 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_database_platform_interface 0.2.2+18 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.1+20 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_dynamic_links 5.0.12 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.3+27 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- flutter_facebook_auth 4.4.1+1 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_facebook_auth_platform_interface 3.2.0 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 3.2.0 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection js material_color_utilities meta path vector_math]
- flutter_svg 1.1.6 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- google_sign_in_android 6.1.6 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.5.1 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.3.0 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.10.2+1 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.5 [meta]
- lints 2.0.1
- matcher 0.12.13 [meta stack_trace]
- material_color_utilities 0.2.0
- meta 1.8.0
- path 1.8.2
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- petitparser 5.1.0 [meta]
- plugin_platform_interface 2.1.3 [meta]
- quiver 3.2.1 [matcher]
- sign_in_with_apple 3.3.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- twitter_login 4.3.1 [flutter crypto http]
- typed_data 1.3.1 [collection]
- vector_math 2.1.4
- xml 6.2.2 [collection meta petitparser]
```

</details>

---

**Comment by darshankawar** [comment]
@juicemia 
The reported error doesn't seem to be related to flutterfire plugins, but could be related to cocoapods.
Also since you are trying to follow the firebase codelab and you are seeing this error while trying to follow all the steps from it, I think it makes sense to report this in dedicated repo ie, in flutter website: https://github.com/flutter/website/issues

Alternatively you may also take a look at similar issues filed in cocoapods repo and see if they help: https://github.com/CocoaPods/CocoaPods/issues/11721

Closing from here as this doesn't seem to be related to any flutterfire plugin. If you disagree or get directed here again, please write in comments and I'll reopen it.

**Comment by juicemia** [comment]
Thank you for pointing me in the right direction @darshankawar.

**Comment by juicemia** [comment]
@darshankawar After opening the issue on the website repo you linked, I'm thinking this issue belongs here. Going through their issue template it seems like the issues are related to specific things on specific pages of the Flutter website. The issue I'm having is building the flutter app with a fresh install of the Firebase libraries on a working Flutter setup. That makes me think the issue is with the libraries that I've installed, and this is the repo for those libraries.

**Comment by darshankawar** [comment]
@juicemia 
My colleague tried to replicate the error by following the codelab and he didn't get the error upon running `pod install`, so it indicates the error you are getting could be due to your setup. I suggest you to take a look at the cocoapod issue link I shared earlier and also go through similar issues reported in that repo for further resolution. If required, you may file an issue in cocoapods repo.

**Comment by juicemia** [comment]
@darshankawar The issue you linked was useless, and the Cocoapods repo specifically says they automatically close issues opened with React Native and Flutter projects. I just ended up nuking my entire setup on my Mac and it's now working.
