### ISSUE TITLE
🐛 [google_sign_in] Google signin crash with FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by paraslamsong** [firebase/flutterfire#10583]
## Bug report

**Describe the bug**
App crashes (Android) on signing to google with 

    final googleSignIn = GoogleSignIn.standard();
    final GoogleSignInAccount? googleUser = await googleSignIn.signIn();

### Flutter dependencies 
 firebase_analytics: ^10.1.5
  cloud_firestore: ^4.4.4
  google_sign_in: ^6.0.2
  firebase_auth: ^4.2.10
  firebase_core_platform_interface: ^4.5.3
  firebase_messaging: ^14.2.6
  firebase_dynamic_links: ^5.0.16
  firebase_storage: ^11.0.15

```
**E/AndroidRuntime(15500): FATAL EXCEPTION: main**
E/AndroidRuntime(15500): Process: com.example.app, PID: 15500
E/AndroidRuntime(15500): **java.lang.NoClassDefFoundError**: Failed resolution of: Landroidx/activity/ComponentActivity;
E/AndroidRuntime(15500): 	at com.bumptech.glide.Glide.with(Glide.java:537)
E/AndroidRuntime(15500): 	at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule.providesGlideRequestManager(GlideModule.java:32)
E/AndroidRuntime(15500): 	at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.providesGlideRequestManager(GlideModule_ProvidesGlideRequestManagerFactory.java:43)
E/AndroidRuntime(15500): 	at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.get(GlideModule_ProvidesGlideRequestManagerFactory.java:32)
E/AndroidRuntime(15500): 	at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.get(GlideModule_ProvidesGlideRequestManagerFactory.java:11)
E/AndroidRuntime(15500): 	at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
E/AndroidRuntime(15500): 	at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get(FiamImageLoader_Factory.java:21)
E/AndroidRuntime(15500): 	at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get(FiamImageLoader_Factory.java:8)
E/AndroidRuntime(15500): 	at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
E/AndroidRuntime(15500): 	at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get(FirebaseInAppMessagingDisplay_Factory.java:61)
E/AndroidRuntime(15500): 	at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get(FirebaseInAppMessagingDisplay_Factory.java:16)
E/AndroidRuntime(15500): 	at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
E/AndroidRuntime(15500): 	at com.google.firebase.inappmessaging.display.internal.injection.components.DaggerAppComponent.providesFirebaseInAppMessagingUI(DaggerAppComponent.java:80)
E/AndroidRuntime(15500): 	at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar.buildFirebaseInAppMessagingUI(FirebaseInAppMessagingDisplayRegistrar.java:75)
E/AndroidRuntime(15500): 	at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar.lambda$mFT7XCE3YJXhnGdhKohfXnpd5DM(Unknown Source:0)
E/AndroidRuntime(15500): 	at com.google.firebase.inappmessaging.display.-$$Lambda$FirebaseInAppMessagingDisplayRegistrar$mFT7XCE3YJXhnGdhKohfXnpd5DM.create(Unknown Source:2)
E/AndroidRuntime(15500): 	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
E/AndroidRuntime(15500): 	at com.google.firebase.tracing.-$$Lambda$ComponentMonitor$nUgWIWAyyZxi6mRt6KSZMmA5LxE.create(Unknown Source:4)
E/AndroidRuntime(15500): 	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$ComponentRuntime(ComponentRuntime.java:140)
E/AndroidRuntime(15500): 	at com.google.firebase.components.-$$Lambda$ComponentRuntime$4FqOW9eOQsvFYo-HpMfxCOnPQr0.get(Unknown Source:4)
E/AndroidRuntime(15500): 	at com.google.firebase.components.Lazy.get(Lazy.java:53)
E/AndroidRuntime(15500): 	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:302)
E/AndroidRuntime(15500): 	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:292)
E/AndroidRuntime(15500): 	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
E/AndroidRuntime(15500): 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
E/AndroidRuntime(15500): 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
E/AndroidRuntime(15500): 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:249)
E/AndroidRuntime(15500): 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:66)
E/AndroidRuntime(15500): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
E/AndroidRuntime(15500): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
E/AndroidRuntime(15500): 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:58)
E/AndroidRuntime(15500): 	at android.app.ActivityThread.installProvider(ActivityThread.java:7459)
E/AndroidRuntime(15500): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6976)
E/AndroidRuntime(15500): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6747)
E/AndroidRuntime(15500): 	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
E/AndroidRuntime(15500): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
E/AndroidRuntime(15500): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15500): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(15500): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(15500): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
E/AndroidRuntime(15500): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15500): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(15500): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(15500): Caused by: java.lang.ClassNotFoundException: androidx.activity.ComponentActivity
E/AndroidRuntime(15500): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime(15500): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime(15500): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime(15500): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(15500): 	... 43 more
E/AndroidRuntime(15500): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/content/OnConfigurationChangedProvider;
E/AndroidRuntime(15500): 	... 43 more
E/AndroidRuntime(15500): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.OnConfigurationChangedProvider" on path: DexPathList[[zip file "/data/app/~~q2OfUXxLy6RTt9vwZMMOuA==/com.example.app-K2kps8-_AUeYEmF7YTlyxQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~q2OfUXxLy6RTt9vwZMMOuA==/com.example.app-K2kps8-_AUeYEmF7YTlyxQ==/lib/arm64, /data/app/~~q2OfUXxLy6RTt9vwZMMOuA==/com.example.app-K2kps8-_AUeYEmF7YTlyxQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(15500): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
E/AndroidRuntime(15500): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(15500): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(15500): 	... 43 more
I/Process (15500): Sending signal. PID: 15500 SIG: 9
Lost connection to device.
```

---

**Comment by darshankawar** [comment]
Thanks for the report @paraslamsong 
Looking at the error log, it seems to be pointing to `at com.bumptech.glide.Glide.with(Glide.java:537)` related to https://github.com/bumptech/glide package which is third party.

Can you narrow down the behavior only to using flutterfire plugins and see if you still get the same crash ? If so, please provide complete minimal code sample.
