### ISSUE TITLE
🐛 [firebase_messaging] App crashing on version 14.1.4

### ISSUE THREAD

**Issue by tyfoo1603** [firebase/flutterfire#10604]
## Bug report

**Describe the bug**

When we published the app with firebase_messaging version 14.1.4, it start getting crash on android devices.

```
android.os.Parcel.readParcelableCreator (Parcel.java:2830)
android.os.Parcel.readParcelable (Parcel.java:2781)
android.os.Parcel.readValue (Parcel.java:2684)
android.os.Parcel.readArrayMapInternal (Parcel.java:3053)
android.os.BaseBundle.initializeFromParcelLocked (BaseBundle.java:288)
android.os.BaseBundle.unparcel (BaseBundle.java:232)
android.os.Bundle.getParcelable (Bundle.java:940)
android.content.Intent.getParcelableExtra (Intent.java:7534)
io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate (FlutterFirebaseMessagingBackgroundExecutor.java:232)
io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.lambda$onHandleWork$0 (FlutterFirebaseMessagingBackgroundService.java:146)
io.flutter.plugins.firebase.messaging.-$$Lambda$FlutterFirebaseMessagingBackgroundService$MMnhHFRTKULlQAZ4ruNMt0KzQOI.run (lambda:4)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:233)
android.app.ActivityThread.main (ActivityThread.java:7225)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:499)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:962)
```

### Steps to reproduce

1. firebase_messaging version 14.1.4
2. Not sure how to reproduce this. Any background service would trigger it I assume.

### Expected behavior

No crash should happens.

---

## Additional context

Based on Crashlytic report issue device status, 96% is In Background. Not sure it would help the team to debug.
Phone model impacted:
- Oppo
- Xiaomi
- Samsung
- OnePlus
- Vivo

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[!] Flutter (Channel unknown, 3.3.9, on macOS 11.3.1 20E241 darwin-x64, locale en-MY)
    ! Flutter version 3.3.9 on channel unknown at /Users/michael/flutter
    ! Upstream repository unknown
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.76.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.18.5
Flutter SDK 3.3.9
myastro 5.9.1+5951

dependencies:
- android_intent_plus 3.1.5 [flutter platform meta]
- another_flushbar 1.12.29 [flutter]
- auto_route 5.0.4 [flutter path collection meta]
- barcode_widget 2.0.3 [barcode flutter]
- bloc 8.1.0 [meta]
- bloc_concurrency 0.2.0 [bloc stream_transform]
- carousel_slider 4.1.1 [flutter]
- clevertap_plugin 1.5.4 [flutter]
- collection 1.16.0
- connectivity_plus 3.0.2 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- content 1.0.0+1 [flutter cupertino_icons core myastro_core get_it package_info_plus dio_cache_interceptor auto_route bloc json_annotation platform carousel_slider smooth_page_indicator bloc_concurrency percent_indicator]
- core 1.1.0+1 [flutter ota_string flutter_bloc equatable intl supercharged flutter_secure_storage dio_cache_interceptor device_info_plus connectivity_plus url_launcher rxdart open_filex package_info_plus get_it dartz flutter_local_notifications flutter_jailbreak_detection firebase_crashlytics firebase_dynamic_links fuzzy flutter_svg shimmer build_runner json_annotation]
- dartz 0.10.1
- device_info_plus 8.0.0 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32]
- dio 4.0.6 [http_parser path]
- dio_cache_interceptor 3.3.1 [dio uuid string_scanner]
- dio_cache_interceptor_hive_store 3.2.0 [dio_cache_interceptor hive]
- enum_to_string 2.0.1
- equatable 2.0.5 [collection meta]
- expansion_widget 0.0.3 [flutter]
- firebase_analytics 10.0.7 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.4.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.0.7 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.0.8 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 14.1.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.9.0+7 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.1 [flutter bloc provider]
- flutter_calendar_carousel 2.4.1 [intl flutter]
- flutter_email_sender 5.2.0 [flutter]
- flutter_html 3.0.0-alpha.5 [html csslib collection numerus flutter]
- flutter_jailbreak_detection 1.8.0 [flutter]
- flutter_local_notifications 12.0.4 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_screenutil 5.6.0 [flutter]
- flutter_secure_storage 7.0.1 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_slidable 2.0.0 [flutter]
- flutter_svg 1.1.6 [flutter meta path_drawing vector_math xml]
- flutter_xlider 3.4.0 [flutter]
- fuzzy 0.4.0-nullsafety.0 [latinize]
- get_it 7.2.0 [async collection]
- hive 2.2.3 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- home 1.0.0+1 [flutter cupertino_icons core myastro_core get_it package_info_plus dio_cache_interceptor auto_route bloc json_annotation platform carousel_slider smooth_page_indicator whatsapp_stickers]
- intl 0.17.0 [clock path]
- json_annotation 4.7.0 [meta]
- jwt_decoder 2.0.1
- more 1.0.0+1 [flutter cupertino_icons core myastro_core get_it package_info_plus dio_cache_interceptor auto_route bloc json_annotation platform hive]
- myastro_core 1.0.0+1 [flutter cupertino_icons auto_route firebase_analytics firebase_messaging pedantic dio_cache_interceptor dio_cache_interceptor_hive_store firebase_performance_dio clevertap_plugin retry extended_image quiver flutter_calendar_carousel simple_tooltip share_plus scrollable_positioned_list flutter_html webview_flutter json_annotation url_launcher firebase_crashlytics permission_handler flutter_slidable flutter_native_timezone timezone jwt_decoder package_info_plus lottie open_filex dio path_provider flutter_archive core storefront more]
- open_filex 4.3.2 [flutter ffi]
- ota_string 0.0.4 [dio hive hive_flutter]
- package_info_plus 3.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- permission_handler 10.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- platform 3.1.0
- responsive_framework 0.2.0 [flutter collection]
- retry 3.1.0
- reward 1.0.0+1 [flutter cupertino_icons core myastro_core get_it package_info_plus dio_cache_interceptor auto_route bloc json_annotation flutter_svg carousel_slider smooth_page_indicator flutter_html expandable scroll_to_index barcode_widget expansion_widget timer_count_down]
- rxdart 0.27.7
- scroll_to_index 3.0.1 [flutter]
- scrollable_positioned_list 0.3.5 [flutter collection]
- share_plus 4.5.0 [cross_file meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shimmer 2.0.0 [flutter]
- simple_tooltip 1.2.0 [flutter]
- smooth_page_indicator 1.0.0+2 [flutter]
- storefront 1.0.0+1 [flutter cupertino_icons myastro core myastro_core get_it package_info_plus dio_cache_interceptor auto_route bloc json_annotation platform scroll_to_index]
- supercharged 2.1.1 [supercharged_dart flutter]
- system_info 1.0.1 [file_utils path]
- timer_count_down 2.2.1 [flutter]
- url_launcher 6.0.18 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- version 3.0.2
- webview_flutter 3.0.4 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- whatsapp_stickers 0.1.0-nullsafety.0 [flutter meta]

dev dependencies:
- analyzer 5.2.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- auto_route_generator 5.0.3 [build source_gen analyzer path build_runner code_builder dart_style xml args auto_route]
- bloc_test 9.1.0 [bloc diff_match_patch meta mocktail test]
- build_runner 2.3.2 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver archive async boolean_selector characters clock collection crypto matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- hive_generator 2.0.0 [build source_gen hive analyzer source_helper]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service archive async boolean_selector characters clock collection crypto fake_async file matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math webdriver]
- json_serializable 6.5.4 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- logger 1.1.0
- mockito 5.3.2 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- ota_generator 0.0.4 [analyzer build source_gen source_helper dio hive ota_string]
- widgetbook 2.4.1 [collection device_frame flutter freezed_annotation go_router provider widgetbook_models]

dependency overrides:
- firebase_core_platform_interface 4.5.2 [collection flutter flutter_test meta plugin_platform_interface]
- test_api 0.4.17 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]

transitive dependencies:
- _fe_analyzer_shared 50.0.0 [meta]
- _flutterfire_internals 1.0.11 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- archive 3.3.0 [crypto path]
- args 2.3.1
- async 2.9.0 [collection meta]
- barcode 2.2.3 [meta qr]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.3.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.1.0 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.4 [built_collection collection fixnum meta]
- characters 1.2.1
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 5.10.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.2.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.4.0 [built_collection built_value collection matcher meta]
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.0.1 [typed_data]
- coverage 1.5.0 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.3+4 [js meta]
- crypto 3.0.2 [typed_data]
- csslib 0.17.1 [source_span]
- cupertino_icons 1.0.4
- dart_style 2.2.4 [analyzer args path pub_semver source_span]
- dbus 0.7.8 [args ffi meta xml]
- device_frame 1.1.0 [freezed_annotation flutter]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- diff_match_patch 0.4.1
- expandable 5.0.1 [flutter]
- extended_image 6.3.2 [extended_image_library flutter meta]
- extended_image_library 3.4.1 [crypto flutter http_client_helper path path_provider]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.2 [meta path]
- file_utils 1.0.1 [globbing path]
- firebase_analytics_platform_interface 3.3.16 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.1+7 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_web 2.2.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.3.9 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.3+25 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.2.9 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.2.10 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance_dio 0.4.1 [flutter dio firebase_performance]
- firebase_performance_platform_interface 0.1.1+28 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.1+17 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]
- fixnum 1.0.0
- flutter_archive 5.0.0 [flutter]
- flutter_local_notifications_linux 2.0.0 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 6.0.0 [flutter plugin_platform_interface]
- flutter_native_timezone 2.0.0 [flutter_web_plugins flutter js]
- flutter_secure_storage_linux 1.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 2.0.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.1 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.1.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 1.1.3 [flutter flutter_secure_storage_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- freezed_annotation 2.1.0 [collection json_annotation meta]
- frontend_server_client 3.2.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- glob 2.0.2 [async collection file path string_scanner]
- globbing 1.0.0 [path]
- go_router 3.1.1 [collection flutter flutter_web_plugins logging meta]
- graphs 2.1.0 [collection]
- html 0.15.0 [csslib source_span]
- http 0.13.4 [async http_parser meta path]
- http_client_helper 2.0.2 [http]
- http_multi_server 3.2.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- io 1.0.3 [meta path string_scanner]
- js 0.6.4
- latinize 0.1.0-nullsafety.0
- lints 2.0.1
- logging 1.0.2
- lottie 1.2.2 [archive flutter path vector_math]
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- mime 1.0.3
- mocktail 0.2.0 [collection matcher test]
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- node_preamble 2.0.1
- numerus 1.1.1
- package_config 2.0.2 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.2
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.0.12 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.4 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- percent_indicator 4.2.2 [flutter]
- permission_handler_android 10.2.0 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.7 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.9.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.2 [flutter permission_handler_platform_interface]
- petitparser 5.1.0 [meta]
- plugin_platform_interface 2.1.3 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- provider 6.0.2 [collection flutter nested]
- pub_semver 2.1.1 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- qr 3.0.1 [meta]
- quiver 3.0.1+1 [matcher]
- share_plus_linux 3.0.0 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 3.0.1 [share_plus_platform_interface flutter]
- share_plus_platform_interface 3.2.0 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- share_plus_web 3.0.0 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 3.0.0 [share_plus_platform_interface flutter meta url_launcher]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.1.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.2.7 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.3 [analyzer collection source_gen]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.1 [source_span]
- supercharged_dart 2.1.1
- sync_http 0.3.1
- term_glyph 1.2.1
- test 1.23.1 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_core 0.4.24 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timezone 0.9.0 [path]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.1 [collection]
- url_launcher_android 6.0.19 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_linux 2.0.3 [flutter]
- url_launcher_macos 2.0.3 [flutter]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.6 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- vm_service 9.0.0
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- webdriver 3.0.0 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.0.0 [logging]
- webview_flutter_android 2.8.3 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.8.1 [flutter plugin_platform_interface]
- webview_flutter_wkwebview 2.7.1 [flutter webview_flutter_platform_interface]
- widgetbook_models 0.0.7 [freezed_annotation meta]
- win32 3.1.3 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by Lyokone** [comment]
Hey 👋 Please update to the latest version of firebase messaging (14.2.6) to check if it still occurs.

**Comment by tyfoo1603** [comment]
@Lyokone Thank you so much for the info!

Let me try it. By any chance, do you able to reproduce the crash? 
Cause I am unable to reproduce it with my android phone(model: huawei mate 20).

**Comment by tyfoo1603** [comment]
Regrettably, we continue to encounter the same issue even after upgrading to Firebase Messaging version 14.2.6.

**Comment by tyfoo1603** [comment]
Sure. Kindly refer following

```
buildscript {
    ext.kotlin_version = '1.7.20'
    repositories {
        google()
        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.8'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'
    }
}
```

**Comment by darshankawar** [comment]
@tyfoo1603 
I am unable to replicate this using the plugin example by sending app to background and tapping on notification. Maybe your case could be similar to https://github.com/firebase/flutterfire/issues/9244.
See if [this](https://github.com/firebase/flutterfire/issues/9244#issuecomment-1219323891) helps to replicate at your end or not.

**Comment by bksbora** [comment]
When i get notification , my app also crashes with this and previous version. Thank you so much all !
My dependencies :
```
 # Firebase
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  connectivity_plus: ^3.0.3
  firebase_messaging: ^14.3.0
  firebase_analytics: ^10.1.6
```

My log :
```
D/EGL_emulation(18848): app_time_stats: avg=2131.99ms min=5.42ms max=39487.25ms count=19
I/flutter (18848): User granted permission: AuthorizationStatus.authorized
I/flutter (18848): dZut7Sd4Rsq5t_yU2kkl7x:APA91bHXqVaCbjnMrSbLqPAfa3DMscjsTyuwEF_1bfHlEE1TZNriFkamlEtkZFwSjXrv1s4yfg31YN-jVeDTFzvn1QdMeA6wYtFE_gSJtkla_XFNmdMmeujl_t93OfwAjoMXJ6LJWmOq
D/EGL_emulation(18848): app_time_stats: avg=7.32ms min=1.70ms max=84.59ms count=57
D/FLTFireMsgReceiver(18848): broadcast received for message
I/flutter (18848): NOTIFICATION TITLE sdaasd
W/ple.bkswebpanel(18848): Accessing hidden method Landroid/os/WorkSource;->add(I)Z (unsupported,test-api, reflection, allowed)
W/ple.bkswebpanel(18848): Accessing hidden method Landroid/os/WorkSource;->add(ILjava/lang/String;)Z (unsupported,test-api, reflection, allowed)
W/ple.bkswebpanel(18848): Accessing hidden method Landroid/os/WorkSource;->get(I)I (unsupported, reflection, allowed)
W/ple.bkswebpanel(18848): Accessing hidden method Landroid/os/WorkSource;->getName(I)Ljava/lang/String; (unsupported, reflection, allowed)
D/AndroidRuntime(18848): Shutting down VM
E/AndroidRuntime(18848): FATAL EXCEPTION: main
E/AndroidRuntime(18848): Process: com.example.bkswebpanel, PID: 18848
E/AndroidRuntime(18848): java.lang.RuntimeException: Unable to create service com.example.bkswebpanel.java.MyFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "com.example.bkswebpanel.java.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/~~0msNww3nNwf6ErlMonHw5g==/com.example.bkswebpanel-pXTRncGEZe-aDSCFzykATQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~0msNww3nNwf6ErlMonHw5g==/com.example.bkswebpanel-pXTRncGEZe-aDSCFzykATQ==/lib/x86_64, /data/app/~~0msNww3nNwf6ErlMonHw5g==/com.example.bkswebpanel-pXTRncGEZe-aDSCFzykATQ==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(18848):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4498)
E/AndroidRuntime(18848):        at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
E/AndroidRuntime(18848):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2161)
E/AndroidRuntime(18848):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(18848):        at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(18848):        at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(18848):        at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(18848):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18848):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(18848):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(18848): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.bkswebpanel.java.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/~~0msNww3nNwf6ErlMonHw5g==/com.example.bkswebpanel-pXTRncGEZe-aDSCFzykATQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~0msNww3nNwf6ErlMonHw5g==/com.example.bkswebpanel-pXTRncGEZe-aDSCFzykATQ==/lib/x86_64, /data/app/~~0msNww3nNwf6ErlMonHw5g==/com.example.bkswebpanel-pXTRncGEZe-aDSCFzykATQ==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(18848):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime(18848):        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(18848):        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(18848):        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime(18848):        at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
E/AndroidRuntime(18848):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4467)
E/AndroidRuntime(18848):        ... 9 more
I/Process (18848): Sending signal. PID: 18848 SIG: 9
Lost connection to device.
```
As you can see i got my message but couldn't display it , it crashes immadiately.

**Comment by tyfoo1603** [comment]
@darshankawar Hi, we are still having same issue. I will try to replicate it with demo app.
