### ISSUE TITLE
🐛 [Database, Firestore, Auth] Cannot connect to remote emulators from client running in emulator

### ISSUE THREAD

**Issue by muzzah** [firebase/flutterfire#10668]
## Bug report

**Describe the bug**
I am running a flutter app using firebase libraries and cannot connect to the emulators even though I can do so through the command line.

I am configuring the firebase instance through code after having generated the firebase_options.dart file. I randomly at times seems to connect but 99% of the time the client cannot connect and shows the below errors

```
[cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
                            #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
                            #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
                            <asynchronous suspension>
                            #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:518:43)
                            <asynchronous suspension>
                            #3      MethodChannelDocumentReference.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_reference.dart:69:42)
                            <asynchronous suspension>
                            #4      _JsonDocumentReference.get (package:cloud_firestore/src/document_reference.dart:146:7)
                            <asynchronous suspension>
```

```
[firebase_auth/network-request-failed] Network error (such as timeout, interrupted connection or unreachable host) has occurred.
```

My firebase configuration
```
{
  "firestore": {
    "rules": "firestore.rules"
  },
  "emulators": {
    "firestore": {
      "port": 5000,
      "host": "0.0.0.0",
      "indexes": "firestore-indexes.json"
    },
    "auth": {
      "port": "5001",
      "host": "0.0.0.0"
    },
    "database": {
      "port": "5002",
      "host": "0.0.0.0"
    },
    "logging": {
      "host": "0.0.0.0"
    },
    "hub": {
      "host": "0.0.0.0"
    },
    "ui": {
      "enabled": true,
      "host": "0.0.0.0",
      "port": 4000
    }
  }
}
```

I can however connect to these emulators through the browser. I can bring up the emulator UI and make a Websocket connection request. What I do see is that the response contains an invalid host information coming from the emulator response
```
CONNECTING: WS://[host of docker container running firebase emulators]:5002/.WS?V=5&NS=local

CONNECTION READY

	{
   "t": "c",
   "d": {
      "t": "h",
      "d": {
         "ts": 1679933551181,
         "v": "5",
         "h": "0.0.0.0:5002",
         "s": "XXNtM4TOay33ANGcUoMv6xBXvEIYOKGw"
      }
   }
}	
```
### Steps to reproduce

1. Configure the firebase instances using firebase_options.dart. Specify to use the emulator on necessary firebase objects
2. Nothing else

### Expected behavior

Clients should connect

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.2.1 22D68 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability


```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.19.0
Flutter SDK 3.7.0
siia 1.0.0+1

dependencies:
- animated_bottom_navigation_bar 0.3.3 [flutter]
- animations 2.0.7 [flutter]
- cloud_firestore 4.3.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- crypto 3.0.2 [typed_data]
- cupertino_icons 1.0.5
- dotted_border 2.0.0+3 [flutter path_drawing]
- dropdown_button2 1.9.2 [flutter]
- equatable 2.0.5 [collection meta]
- firebase_analytics 10.1.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.2.5 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.4.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.0.11 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_database 10.0.9 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- fl_chart 0.55.2 [flutter equatable]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_intro 2.3.1 [flutter]
- flutter_keyboard_visibility 5.4.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection js material_color_utilities meta path vector_math]
- flutter_modular 5.0.3 [flutter_modular_annotations modular_core meta flutter]
- flutter_redux 0.10.0 [redux flutter]
- flutter_rounded_progress_bar 0.2.0 [flutter]
- flutter_translate 3.1.0 [flutter universal_io]
- form_field_validator 1.1.0 [flutter intl]
- get_it 7.2.0 [async collection]
- google_sign_in 5.4.3 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- http 0.13.5 [async http_parser meta path]
- im_stepper 1.0.1+1 [flutter]
- intl 0.17.0 [clock path]
- introduction_screen 2.1.0 [flutter dots_indicator]
- json_annotation 4.8.0 [meta]
- line_awesome_icons 1.0.4+2 [flutter]
- localstorage 4.0.0+1 [flutter path_provider]
- modal_bottom_sheet 3.0.0-pre [flutter]
- optional 6.1.0+1 [collection]
- path 1.8.2
- path_provider 2.0.12 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- quiver 3.2.1 [matcher]
- random_string 2.3.1
- redux 5.0.0
- scroll_to_index 3.0.1 [flutter]
- simple_animations 4.2.0 [flutter collection]
- supercharged 2.1.1 [supercharged_dart flutter]
- universal_platform 1.0.0+1
- web_socket_channel 2.3.0 [async crypto stream_channel]

dev dependencies:
- build_runner 2.3.3 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- json_serializable 6.6.0 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- mockito 5.3.2 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- test 1.22.0 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

transitive dependencies:
- _fe_analyzer_shared 52.0.0 [meta]
- _flutterfire_internals 1.0.12 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 5.4.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.2
- async 2.10.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.3.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.1.0 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.7 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.4.3 [built_collection collection fixnum meta]
- characters 1.2.1
- checked_yaml 2.0.2 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 5.10.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.2.1 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.4.0 [built_collection built_value collection matcher meta]
- collection 1.17.0
- convert 3.1.1 [typed_data]
- coverage 1.6.2 [args logging package_config path source_maps stack_trace vm_service]
- dart_style 2.2.4 [analyzer args path pub_semver source_span]
- dots_indicator 2.1.0 [flutter]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- firebase_analytics_platform_interface 3.3.17 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.1+8 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.11.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.2.4 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.2 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.3.11 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_platform_interface 0.2.2+17 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.1+19 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- fixnum 1.0.1
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_modular_annotations 0.0.2 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 3.2.0 [async path]
- glob 2.1.1 [async collection file path string_scanner]
- google_sign_in_android 6.1.5 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.5.1 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.3.0 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.10.2+1 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- graphs 2.2.0 [collection]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- io 1.0.4 [meta path string_scanner]
- js 0.6.5 [meta]
- logging 1.1.1
- matcher 0.12.13 [meta stack_trace]
- material_color_utilities 0.2.0
- meta 1.8.0
- mime 1.0.4
- modular_core 2.0.3+1 [characters meta modular_interfaces]
- modular_interfaces 2.0.2
- node_preamble 2.0.1
- package_config 2.1.0 [path]
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.0.22 [flutter path_provider_platform_interface]
- path_provider_foundation 2.1.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.5 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.0
- plugin_platform_interface 2.1.3 [meta]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.3 [collection meta]
- pubspec_parse 1.2.1 [checked_yaml collection json_annotation pub_semver yaml]
- shelf 1.4.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.1 [path shelf shelf_static]
- shelf_static 1.1.1 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.3 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.2.6 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.3 [analyzer collection source_gen]
- source_map_stack_trace 2.1.1 [path source_maps stack_trace]
- source_maps 0.10.11 [source_span]
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- supercharged_dart 2.1.1
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.20 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.1 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- vector_math 2.1.4
- vm_service 9.4.0
- watcher 1.0.2 [async path]
- webkit_inspection_protocol 1.2.0 [logging]
- win32 3.1.3 [ffi]
- xdg_directories 0.2.0+3 [meta path process]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by muzzah** [comment]
Closing, resolved for now

**Comment by darshankawar** [comment]
Even though you mentioned that issue is resolved but you didn't seem to close it :) , so will close based on above comment. If you come across this issue again, feel free to write in comments and I'll reopen it.
