### ISSUE TITLE
🐛 [firebase_messaging]  NoSuchMethodError: No top-level getter '_firebaseMessagingBackgroundHandler' declared.

### ISSUE THREAD

**Issue by MuhammadAliKust** [firebase/flutterfire#10688]
## Bug report

**Describe the bug**
Unable to receive notification in background. It work fine in debug mode but get following error in release mode.

```
E/flutter (30892): [ERROR:flutter/lib/ui/dart_runtime_hooks.cc(38)] Dart Error: Unhandled exception:
E/flutter (30892): NoSuchMethodError: No top-level getter '_firebaseMessagingBackgroundHandler' declared.
E/flutter (30892): Receiver: top-level
E/flutter (30892): Tried calling: _firebaseMessagingBackgroundHandler
E/flutter (30892): #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:225)
E/flutter (30892): #1      FfiTrampoline___getCallbackFromHandle$Method$FfiNative$Ptr (dart:ffi)
E/flutter (30892): #2      _getCallbackFromHandle (dart:ui/natives.dart:141)
E/flutter (30892): #3      PluginUtilities.getCallbackFromHandle.<anonymous closure> (dart:ui/plugins.dart:81)
E/flutter (30892): #4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535)
E/flutter (30892): #5      PluginUtilities.getCallbackFromHandle (dart:ui/plugins.dart:80)
E/flutter (30892): #6      _firebaseMessagingCallbackDispatcher.<anonymous closure> (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:40)
E/flutter (30892): #7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:555)
E/flutter (30892): #8      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:548)
E/flutter (30892): #9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393)
E/flutter (30892): #10     _invoke2 (dart:ui/hooks.dart:183)
E/flutter (30892): #11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40)
E/flutter (30892): #12     _Channel.push (dart:ui/channel_buffers.dart:130)
E/flutter (30892): #13     ChannelBuffers.push (dart:ui/channel_buffers.dart:326)
E/flutter (30892): #14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664)
E/flutter (30892): #15     _dispatchPlatformMessage (dart:ui/hooks.dart:86)
```

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by MuhammadAliKust** [comment]
I have added @pragma('vm:entry-point')

and now its working, kindly can you pls explain why this is happening now, because previously it was working without putting this annotation.

**Comment by danagbemava-nc** [comment]
See https://stackoverflow.com/questions/64314719/what-do-pragmavmprefer-inline-mean-in-flutter and https://mrale.ph/dartvm/compiler/aot/entry_point_pragma.html for more information on what `@pragma` does. 

Closing since this has been resolved
