### ISSUE TITLE
🐛 [firebase_messaging] java.lang.ClassNotFoundException: Didn't find class "io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingInitProvider" on path: DexPathList

### ISSUE THREAD

**Issue by hieudz** [firebase/flutterfire#10686]
## Bug report

**Describe the bug**
The app crash on start because of ClassNotFoundException  Didn't find class "io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingInitProvider". In The java/io/flutter/plugins/GeneratedPluginRegistrant.java file, I cannot see `FlutterFirebaseMessagingInitProvider` but I can see `FlutterFirebaseMessagingPlugin`

### Steps to reproduce

Not sure how to reproduce this on other projects. But on my project, I add jitsi_meet_wrapper: ^0.0.6 + very basic code for that package. Pub get + build => Build successful but crash on startup.

### Expected behavior

The app should run normally

### Sample project

I can't public it.

---

## Additional context

Here is the log
```
java.lang.RuntimeException: Unable to get provider io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingInitProvider: java.lang.ClassNotFoundException: Didn't find class "io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingInitProvider" on path: DexPathList[[zip file "/data/app/~~zmElmtz4jlf2FWJk_G3fsQ==/com.aye.aye_app-beyV2R_vcwnpdmAz-bDtkA==/base.apk"],nativeLibraryDirectories=[/data/app/~~zmElmtz4jlf2FWJk_G3fsQ==/com.aye.aye_app-beyV2R_vcwnpdmAz-bDtkA==/lib/arm64, /data/app/~~zmElmtz4jlf2FWJk_G3fsQ==/com.aye.aye_app-beyV2R_vcwnpdmAz-bDtkA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
E/AndroidRuntime(24002): 	at android.app.ActivityThread.installProvider(ActivityThread.java:8328)
E/AndroidRuntime(24002): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7828)
E/AndroidRuntime(24002): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7577)
E/AndroidRuntime(24002): 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
E/AndroidRuntime(24002): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
E/AndroidRuntime(24002): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(24002): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(24002): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(24002): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(24002): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24002): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(24002): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(24002): Caused by: java.lang.ClassNotFoundException: Didn't find class "io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingInitProvider" on path: DexPathList[[zip file "/data/app/~~zmElmtz4jlf2FWJk_G3fsQ==/com.aye.aye_app-beyV2R_vcwnpdmAz-bDtkA==/base.apk"],nativeLibraryDirectories=[/data/app/~~zmElmtz4jlf2FWJk_G3fsQ==/com.aye.aye_app-beyV2R_vcwnpdmAz-bDtkA==/lib/arm64, /data/app/~~zmElmtz4jlf2FWJk_G3fsQ==/com.aye.aye_app-beyV2R_vcwnpdmAz-bDtkA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
E/AndroidRuntime(24002): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime(24002): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(24002): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(24002): 	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
E/AndroidRuntime(24002): 	at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
E/AndroidRuntime(24002): 	at android.app.ActivityThread.installProvider(ActivityThread.java:8312)
E/AndroidRuntime(24002): 	... 11 more
E/AndroidRuntime(24086): FATAL EXCEPTION: main
```
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details>
<summary>Click To Expand</summary>

```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.8, on Microsoft Windows [Version 10.0.22621.1413], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.76.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

```
</details>
---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details>
<summary>Click To Expand</summary>

```
 _fe_analyzer_shared 46.0.0 [meta]
- _flutterfire_internals 1.0.12 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 4.6.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.3.1 [crypto path]
- args 2.3.1
- asn1lib 1.1.0
- async 2.10.0 [collection meta]
- back_button_interceptor 6.0.1 [collection flutter]
- bloc 7.2.1 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.3.0 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.9 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.4.0 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- camera_android 0.9.8+3 [camera_platform_interface flutter flutter_plugin_android_lifecycle stream_transform]
- camera_avfoundation 0.9.8+3 [camera_platform_interface flutter stream_transform]
- camera_platform_interface 2.2.0 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.2.1+6 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.2.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 5.10.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.2.1 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.1.26 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.3.15 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.2.0 [built_collection built_value collection matcher meta]
- convert 3.0.2 [typed_data]
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- dart_style 2.2.3 [analyzer args path pub_semver source_span]
- dartx 1.1.0 [characters collection crypto meta path time]
- dbus 0.7.8 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- facebook_auth_desktop 0.0.7 [flutter http flutter_secure_storage flutter_facebook_auth_platform_interface]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- firebase_analytics_platform_interface 3.3.17 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.1+8 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.11.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.2.4 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.2 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.3.11 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_platform_interface 0.2.2+17 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.1+19 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_dynamic_links_platform_interface 0.2.3+26 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.2.10 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.2.11 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config_platform_interface 1.1.29 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.1.18 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- firebase_storage_platform_interface 4.1.26 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.3.19 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.1
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_facebook_auth_platform_interface 4.1.1 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 4.1.1 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_inappwebview 5.7.2+3 [flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_local_notifications_linux 0.5.1 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_secure_storage 6.1.0 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_secure_storage_linux 1.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 1.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.1 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.1.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 1.1.3 [flutter flutter_secure_storage_platform_interface]
- flutter_sound_platform_interface 9.2.13 [flutter meta plugin_platform_interface logger]
- flutter_sound_web 9.2.13 [flutter_sound_platform_interface flutter logger flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 2.1.3 [async path]
- geocoding_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- geolocator_android 4.1.4 [flutter geolocator_platform_interface]
- geolocator_apple 2.2.1 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.6 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.6 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.1 [flutter geolocator_platform_interface]
- glob 2.1.0 [async collection file path string_scanner]
- google_sign_in_android 6.0.1 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.4.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.2.0 [flutter quiver]
- google_sign_in_web 0.10.2 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- graphs 2.1.0 [collection]
- html 0.15.1 [csslib source_span]
- http 0.13.5 [async http_parser meta path]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.5+2 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.5+6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- in_app_purchase_android 0.2.3+3 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_purchase_platform_interface 1.3.1 [flutter plugin_platform_interface]
- in_app_purchase_storekit 0.3.5+2 [collection flutter in_app_purchase_platform_interface json_annotation]
- io 1.0.3 [meta path string_scanner]
- jitsi_meet_wrapper_platform_interface 0.0.4 [collection flutter plugin_platform_interface]
- js 0.6.5 [meta]
- latlong2 0.8.1 [intl]
- lints 1.0.1
- lists 1.0.1 [meta]
- location_platform_interface 2.3.0 [flutter meta plugin_platform_interface]
- location_web 3.1.1 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- logger 1.1.0
- logging 1.0.2
- matcher 0.12.13 [meta stack_trace]
- material_color_utilities 0.2.0
- meta 1.8.0
- mgrs_dart 2.0.0 [unicode]
- mime 1.0.2
- nested 1.0.0 [flutter]
- octo_image 1.0.2 [flutter flutter_blurhash]
- os_detect 2.0.1
- package_config 2.1.0 [path]
- package_info_plus 3.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.2
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.0.19 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.2 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.3 [meta]
- pointycastle 3.6.1 [collection convert js]
- polylabel 1.0.1 [collection]
- pool 1.5.1 [async stack_trace]
- positioned_tap_detector_2 1.0.4 [flutter]
- process 4.2.4 [file path platform]
- proj4dart 2.0.0 [mgrs_dart wkt_parser meta]
- pub_semver 2.1.1 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.1.0 [matcher]
- recase 4.0.0
- shared_preferences_android 2.0.12 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.3.2 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.2 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- simple_gesture_detector 0.2.0 [flutter]
- sky_engine 0.0.99
- source_gen 1.2.2 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.2 [analyzer collection source_gen]
- source_span 1.9.1 [collection path term_glyph]
- sqflite 2.0.3+1 [flutter sqflite_common path]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- stream_transform 2.0.0
- string_scanner 1.2.0 [source_span]
- string_validator 0.3.0
- synchronized 3.0.0+2
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- time 2.1.2 [clock]
- timezone 0.8.0 [path]
- timing 1.0.0 [json_annotation]
- tuple 2.0.0 [quiver]
- typed_data 1.3.1 [collection]
- unicode 0.3.1 [lists]
- url_launcher 6.1.9 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.13 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- version 3.0.2
- video_player_android 2.3.8 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.5 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.4 [flutter plugin_platform_interface]
- video_player_web 2.0.12 [flutter flutter_web_plugins video_player_platform_interface]
- visibility_detector 0.3.3 [flutter]
- wakelock 0.6.2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- watcher 1.0.1 [async path]
- web_socket_channel 2.2.0 [async crypto stream_channel]
- webview_flutter 4.0.2 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 3.2.4 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.0.5 [flutter path webview_flutter_platform_interface]
- win32 2.7.0 [ffi]
- wkt_parser 2.0.0
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- xxh3 1.0.1
- yaml 3.1.1 [collection source_span string_scanner]
- youtube_player_iframe_web 2.0.2 [flutter flutter_web_plugins webview_flutter_platform_interface]
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @hieudz, have you enabled Multidex for your project? If you have not, can you try enabling it to see if it works?

> I can't make it public.

Your sample project does not need to be your actual project. Please provide any code sample that reproduces the project. 

Thank you

**Comment by danagbemava-nc** [comment]
Hi @hieudz, I'm not seeing the `firebase_messaging` plugin in your dependencies list. I see `firebase_messaging_web` & `firebase_messaging_platform_interface` but not the actual `firebase_messaging` plugin. Can you add that to your project to see if it works?

**Comment by danagbemava-nc** [comment]
Hi @hieudz, did you manually configure firebase for your project or did you use `flutterfire configure`? 

Also, since it seems like adding `jitsi_meet_wrapper` to your project causes the issue, it might be best if you file an issue over on their repo so they can share some insights

**Comment by hieudz** [comment]
I manually configure firebase.

I've just found out the root cause today. It's actually Kotlin version problem. I have to upgrade Kotlin to 1.8. (and gradle too)

Somehow build error doesn't capture it and throw this random error instead. 

After upgrading Kotlin, everything works fine
