### ISSUE TITLE
🐛 [firebase_messaging] Serious issue: on Android requestPermission() causes an exception

### ISSUE THREAD

**Issue by serhii-k** [firebase/flutterfire#10701]
## Bug report

**Describe the bug**
First of all I want to mention that I know about #9904. But this one is already closed without any real solution.

I've recently updated firebase plugins to the latest version, and released the app:

```
  firebase_core: ^2.8.0
  firebase_analytics: ^10.1.6
  firebase_crashlytics: ^3.0.17
  firebase_messaging: ^14.3.0
  firebase_remote_config: ^3.0.15
  flutter_local_notifications: ^13.0.0 # just in case, my app also depends on this plugin
```

Previously, I used a combination with firebase_messaging 12.0.1. That version didn't handle Android 13 notifications.

During the app startup I call:
```
firebaseMessaging.requestPermission();
```

Just to show the permission popup for users with Android 13. I thought it's a no-op for older versions.

After running a new release for 2 days, I see this report in Firebase Crashlytics console:
<img width="401" alt="Screen Shot 2023-04-01 at 11 58 08" src="https://user-images.githubusercontent.com/10563821/229284911-6c84903d-6836-471e-bb23-95534df0b94f.png">

<img width="794" alt="Screen Shot 2023-04-01 at 11 59 02" src="https://user-images.githubusercontent.com/10563821/229284914-70320825-b876-4836-87ea-de8aa3d0297e.png">

Here is the stack trace for devices with Android versions **less than** 13:
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: [firebase_messaging/unknown] Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
#00 pc 0x60f337 com.*** (StandardMethodCodec.decodeEnvelope [message_codecs.dart:653]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#01 pc 0x648827 com.*** (MethodChannel._invokeMethod [platform_channel.dart:315]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#02 pc 0x626167 com.*** (_SuspendState._createAsyncStarCallback.<anonymous closure> [async_patch.dart:353]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#03 pc 0x26074f com.*** (_FutureListener.handleValue [zone.dart:1660]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#04 pc 0x64cd0f com.*** (Future._propagateToListeners.handleValueCallback [future_impl.dart:767]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#05 pc 0x25c2cf com.*** (Future._propagateToListeners [future_impl.dart:796]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#06 pc 0x25d503 com.*** (Future._completeWithValue [future_impl.dart:567]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#07 pc 0x25d463 com.*** (Future._asyncCompleteWithValue.<anonymous closure> [future_impl.dart:640]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#08 pc 0x25cd47 com.*** (_microtaskLoop [schedule_microtask.dart:40]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#09 pc 0x64b5e7 com.*** (_startMicrotaskLoop [schedule_microtask.dart:49]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#10 pc 0x25ccbb com.*** (_startMicrotaskLoop [schedule_microtask.dart:44]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
```

And this is a stack trace for devices with Android 13:
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: [firebase_messaging/unknown] Unable to detect current Android Activity.
#00 pc 0x60f337 com.*** (StandardMethodCodec.decodeEnvelope [message_codecs.dart:653]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#01 pc 0x648827 com.*** (MethodChannel._invokeMethod [platform_channel.dart:315]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#02 pc 0x626167 com.*** (_SuspendState._createAsyncStarCallback.<anonymous closure> [async_patch.dart:353]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#03 pc 0x26074f com.*** (_FutureListener.handleValue [zone.dart:1660]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#04 pc 0x64cd0f com.*** (Future._propagateToListeners.handleValueCallback [future_impl.dart:767]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#05 pc 0x25c2cf com.*** (Future._propagateToListeners [future_impl.dart:796]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#06 pc 0x25d503 com.*** (Future._completeWithValue [future_impl.dart:567]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#07 pc 0x25d463 com.*** (Future._asyncCompleteWithValue.<anonymous closure> [future_impl.dart:640]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#08 pc 0x25cd47 com.*** (_microtaskLoop [schedule_microtask.dart:40]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#09 pc 0x64b5e7 com.*** (_startMicrotaskLoop [schedule_microtask.dart:49]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
#10 pc 0x25ccbb com.*** (_startMicrotaskLoop [schedule_microtask.dart:44]) (BuildId: bca64abfc2bc13d631bb8f1c8a3224fd)
```

So, I'm afraid there is a serious issue with the requestPermission() implementation.

### Steps to reproduce

Sorry, I can't reproduce any bug on my environment. Emulators don't show it, and my phone has Android 13.

### Expected behavior

requestPermission() works without any exception

### Sample project

---

## Additional context

Just in case, my app also depends on flutter_local_notificaions

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.7.9, on macOS 12.6.3 21G419 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.19.6
Flutter SDK 3.7.9
noname 3.6.0+3006000

dependencies:
- animations 2.0.7 [flutter]
- app_settings 4.2.0 [flutter]
- audio_service 0.18.9 [audio_service_platform_interface audio_service_web audio_session rxdart flutter_cache_manager clock js flutter flutter_web_plugins]
- audio_session 0.1.13 [flutter flutter_web_plugins rxdart meta]
- equatable 2.0.5 [collection meta]
- firebase_analytics 10.1.6 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.8.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.0.17 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 14.3.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 3.0.15 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_local_notifications 13.0.0 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection js material_color_utilities meta path vector_math]
- flutter_riverpod 1.0.4 [collection flutter meta riverpod state_notifier]
- flutter_timezone 1.0.4 [flutter_web_plugins flutter js]
- get_it 7.2.0 [async collection]
- in_app_purchase 3.1.5 [flutter in_app_purchase_android in_app_purchase_platform_interface in_app_purchase_storekit]
- in_app_purchase_android 0.2.4+3 [collection flutter in_app_purchase_platform_interface json_annotation]
- intl 0.17.0 [clock path]
- keep_screen_on 2.1.0 [flutter keep_screen_on_platform_interface]
- launch_review 3.0.1 [flutter]
- meta 1.8.0
- package_info 2.0.2 [flutter]
- path 1.8.2
- path_provider 2.0.14 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- pointycastle 3.7.1 [collection convert js]
- share_plus 6.3.1 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- sqflite 2.2.6 [flutter sqflite_common path]
- synchronized 3.0.1
- timezone 0.9.1 [path]
- url_launcher 6.1.10 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver archive async boolean_selector characters clock collection crypto js matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- test 1.22.0 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

transitive dependencies:
- _fe_analyzer_shared 57.0.0 [meta]
- _flutterfire_internals 1.0.18 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 5.9.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.3.2 [crypto path]
- args 2.4.0
- async 2.10.0 [collection meta]
- audio_service_platform_interface 0.1.0 [flutter plugin_platform_interface meta]
- audio_service_web 0.1.1 [audio_service_platform_interface rxdart js flutter flutter_web_plugins]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- collection 1.17.0
- convert 3.1.1 [typed_data]
- coverage 1.6.3 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.3+4 [js meta]
- crypto 3.0.2 [typed_data]
- dbus 0.7.8 [args ffi meta xml]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- firebase_analytics_platform_interface 3.3.23 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.1+14 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.5.3 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.2.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.3.17 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.2.16 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.2.17 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config_platform_interface 1.1.35 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.1.24 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_local_notifications_linux 3.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 6.0.0 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 3.2.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- glob 2.1.1 [async collection file path string_scanner]
- http 0.13.5 [async http_parser meta path]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- in_app_purchase_platform_interface 1.3.3 [flutter plugin_platform_interface]
- in_app_purchase_storekit 0.3.6+2 [collection flutter in_app_purchase_platform_interface json_annotation]
- io 1.0.4 [meta path string_scanner]
- js 0.6.5 [meta]
- json_annotation 4.8.0 [meta]
- keep_screen_on_platform_interface 2.0.0+1 [flutter plugin_platform_interface]
- lints 2.0.1
- logging 1.1.1
- matcher 0.12.13 [meta stack_trace]
- material_color_utilities 0.2.0
- mime 1.0.4
- node_preamble 2.0.2
- package_config 2.1.0 [path]
- path_provider_android 2.0.24 [flutter path_provider_platform_interface]
- path_provider_foundation 2.2.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.10 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.6 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.5 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 5.1.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.4 [meta]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.3 [collection meta]
- riverpod 1.0.3 [collection meta state_notifier]
- rxdart 0.27.7
- share_plus_platform_interface 3.2.0 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shelf 1.4.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.1 [path shelf shelf_static]
- shelf_static 1.1.1 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.3 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_map_stack_trace 2.1.1 [path source_maps stack_trace]
- source_maps 0.10.12 [source_span]
- source_span 1.9.1 [collection path term_glyph]
- sqflite_common 2.4.3 [synchronized path meta]
- stack_trace 1.11.0 [path]
- state_notifier 0.7.2+1 [meta]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- sync_http 0.3.1
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.20 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- typed_data 1.3.1 [collection]
- url_launcher_android 6.0.26 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.3 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.4 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.4 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.16 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.5 [flutter url_launcher_platform_interface]
- uuid 3.0.7 [crypto]
- vector_math 2.1.4
- vm_service 9.4.0
- watcher 1.0.2 [async path]
- web_socket_channel 2.3.0 [async crypto stream_channel]
- webdriver 3.0.1 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.2.0 [logging]
- win32 3.1.3 [ffi]
- xdg_directories 0.2.0+3 [meta path process]
- xml 6.2.2 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by serhii-k** [comment]
@darshankawar Thank you for replying to this issue. I confirm that the app was configured accordingly to the provided instructions (compile and target SDK was set to 33 in build.gradle, and exported="true" in the app manifest).

**Comment by darshankawar** [comment]
> During the app startup I call:
> 
> ```
> firebaseMessaging.requestPermission();
> ```

Is there a way for you to provide a complete minimal code sample that has this usage and triggers this error ?

Usually the `requestPermission()` method is called as such:

```
return await FirebaseMessaging.instance.requestPermission(
      alert: true,
      announcement: false,
      badge: true,
      carPlay: false,
      criticalAlert: false,
      provisional: false,
      sound: true,
    );
```

**Comment by serhii-k** [comment]
@darshankawar Sorry, I really can't reproduce this exception on my Android device. However, here's the minimal code that should provoke this exception.

pubspec.yaml:
```
  firebase_core: ^2.8.0
  firebase_analytics: ^10.1.6
  firebase_crashlytics: ^3.0.17
  firebase_messaging: ^14.3.0
  firebase_remote_config: ^3.0.15
  flutter_local_notifications: ^13.0.0 # just in case, my app also depends on this plugin
```

main.dart:
```
import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Firebase Core
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // Firebase Crashlytics
  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;
  PlatformDispatcher.instance.onError = (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    return true;
  };
  // flutter_local_notifications
  await initializeFlutterLocalNotificationsPlugin();
  //
  runApp(
    MaterialApp(
      home: FirebaseConfiguration(
        child: Scaffold(
          appBar: AppBar(),
        ),
      ),
    ),
  );
}

Future<void> initializeFlutterLocalNotificationsPlugin() async {
  final flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
  const kAndroidInitializationSettings =
      AndroidInitializationSettings('ic_stat_watch_later');
  const kDarwinInitializationSettings = DarwinInitializationSettings(
    requestAlertPermission: false,
    requestBadgePermission: false,
    requestSoundPermission: false,
  );
  const initializationSettings = InitializationSettings(
    android: kAndroidInitializationSettings,
    iOS: kDarwinInitializationSettings,
  );
  await flutterLocalNotificationsPlugin.initialize(
    initializationSettings,
    onDidReceiveNotificationResponse: (_) {},
  );
}

class FirebaseConfiguration extends StatefulWidget {
  final Widget child;

  const FirebaseConfiguration({
    super.key,
    required this.child,
  });

  @override
  State<FirebaseConfiguration> createState() => _FirebaseConfigurationState();
}

class _FirebaseConfigurationState extends State<FirebaseConfiguration> {
  @override
  void initState() {
    super.initState();
    _init();
  }

  Future<void> _init() async {
    final firebaseMessaging = FirebaseMessaging.instance;
    // Request the notification permission during the start up.
    await firebaseMessaging.requestPermission();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}
```

**Comment by darshankawar** [comment]
Thanks for the update. I tried using the code sample you provided on Pixel XL emulator (although not on Android 13), but was unable to replicate the exception.
I am going ahead and labeling this issue for team's attention and thoughts.

/cc @Lyokone

**Comment by MrPello** [comment]
We're seeing the same issues in our app. Our app is not using flutter_local_notifications but another notification plugin called awesome_notifications.

For us we're mostly seeing the error on Samsung devices and 99% of them were running "in background"

**Comment by Lyokone** [comment]
@serhii-k Do you know which version of firebase_messaging you used before upgrading to the latest version?

**Comment by MrPello** [comment]
Hi,

We went from 13.1.0 to 14.3.0.

[pubspecs.zip](https://github.com/firebase/flutterfire/files/11167308/pubspecs.zip)

**Comment by serhii-k** [comment]
@Lyokone Previously it was:
firebase_messaging: ^12.0.1

**Comment by jignesh-mind** [comment]
Any update on this?. I'm facing the exactly same issue.

**Comment by leossmith** [comment]
I am having the same issue with background messages. 

```
`I/flutter (10686): FlutterFire Messaging: An error occurred in your background messaging handler:
I/flutter (10686): [firebase_messaging/unknown] Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
````

Using latest version of firebase_messaging.

**Comment by jignesh-mind** [comment]
> I have the same issue with the latest version of firebase_messaging: ^14.6.2

Try new version they have solved this issues
firebase_messaging: ^14.6.3

**Comment by russellwheatley** [comment]
> My observations:
> 
> ### 1) On Android 13 the exception says "Unable to detect current Android Activity."
> Probably it happens here:
> 
> https://github.com/firebase/flutterfire/blob/d11440aba7e1172e69086dc12b07a94f27670fc8/packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebasePermissionManager.java#L57
> 
> When activity is null.
> 
> I'm trying to show the notification permission popup during the start up. So probably the activity has not yet been initialized at this stage.
> 
> ### 2) From the Firebase Console I see that this issue happens on:
> * practically every Pixel model
> * Sony devices
> * devices of a lot of Chinese manufacturers
> 
> BUT. For example, it has **never** happened on any Samsung device.

Hi @serhii-k, your observation is likely correct. Requesting permission relies on the activity to be started & available. If you're receiving that error, there isn't much to be done on FlutterFire side. You would need to design your application in a manner where you delay requesting permission to ensure the activity has been created and hasn't been closed out due to inactivity (e.g. in background state for a period of time).

**Comment by serhii-k** [comment]
Hello @russellwheatley, Thank you for the suggestions. I think you are right. I'm closing this issue for now.
