### ISSUE TITLE
🐛 [cloud_firestore] [Android] Fatal Exception: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by hukusuke1007** [firebase/flutterfire#10745]
## Bug report

While running the Android app, the following report was reported in the crash log.

```log
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.google.firebase.firestore.core.Query.matchesOrderBy(Query.java:14)
       at com.google.firebase.firestore.core.Query.matches(Query.java:12)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.lambda$getDocumentsMatchingQuery$3(SQLiteRemoteDocumentCache.java)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.lambda$processRowInBackground$2(SQLiteRemoteDocumentCache.java:6)
       at com.google.firebase.firestore.util.BackgroundQueue.lambda$execute$0(BackgroundQueue.java)
       at com.google.firebase.firestore.util.ThrottledForwardingExecutor.lambda$execute$0(ThrottledForwardingExecutor.java)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)
```

## Additional context
Occurs on Android versions 8, 9, 11.

pubspec.yaml

```
  firebase_core: ^2.9.0
  firebase_analytics: ^10.2.0
  cloud_firestore: ^4.5.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.1.0
  cloud_functions: ^4.1.0
  firebase_messaging: ^14.4.0
  firebase_crashlytics: ^3.1.0
  firebase_dynamic_links: ^5.1.0
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.2.1 22D68 darwin-arm64, locale
    ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

---

**Comment by hukusuke1007** [comment]
This is stack trace.
https://gist.github.com/hukusuke1007/911cbf702e213d13de0131022cb02abd

**Comment by darshankawar** [comment]
Thanks for the report @hukusuke1007 
Is it replicable locally ? If so, a minimal code sample would be helpful to debug further.

Also, looks related to https://github.com/firebase/flutterfire/issues/8444, which you can take a look for further reference.
