### ISSUE TITLE
🐛 [firebase_crashlytics] java.io.IOException: Unknown error while sending file, check network 

### ISSUE THREAD

**Issue by iLoveDocs** [firebase/flutterfire#10767]
## Bug report

I am building apk using: 

```
flutter build apk --obfuscate --split-debug-info=/Users/user/tmp/symb
```

[Docs](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter#add-sdk) suggest to upload the symbols using:

```
firebase crashlytics:symbols:upload --app=APP_ID PATH/TO/symbols
```

So, I ran: 

```
firebase crashlytics:symbols:upload --app=com.example.foo /Users/user/tmp/symb
```

After this I get the following error: 

```
i  Generating symbols for /Users/user/tmp/symb
i  Generated symbols for /Users/user/tmp/symb
i  Output Path: /var/folders/5x/h_n5w6vd6sd9czw1jxzzwp4h0000gn/T/crashlytics-3fd31ec5-feb2-4a03-a665-e193e2e0e23c/nativeSymbols/com.example.foo/breakpad
i  Uploading all generated symbols...
⚠  [CRASHLYTICS LOG DEBUG] Crashlytics Buildtools initialized.
[CRASHLYTICS LOG DEBUG] Uploading native symbol files from directory: /var/folders/5x/h_n5w6vd6sd9czw1jxzzwp4h0000gn/T/crashlytics-3fd31ec5-feb2-4a03-a665-e193e2e0e23c/nativeSymbols/com.example.foo/breakpad
[CRASHLYTICS LOG DEBUG] PUT file: /var/folders/5x/h_n5w6vd6sd9czw1jxzzwp4h0000gn/T/crashlytics-3fd31ec5-feb2-4a03-a665-e193e2e0e23c/nativeSymbols/com.example.foo/breakpad/app.android-arm64-arm64-349b90037e503a219d28a26ef22c904b.gz to URL: https://firebasecrashlyticssymbols.googleapis.com/v1/project/-/app/com.example.foo/upload/breakpad/349b90037e503a219d28a26ef22c904b
[CRASHLYTICS LOG DEBUG] PUT headers:
[CRASHLYTICS LOG DEBUG]         User-Agent = firebase-cli;crashlytics-buildtools/2.9.2
[CRASHLYTICS LOG DEBUG]         X-CRASHLYTICS-API-CLIENT-TYPE = firebase-cli;crashlytics-buildtools
[CRASHLYTICS LOG DEBUG]         X-CRASHLYTICS-API-CLIENT-VERSION = 2.9.2
[CRASHLYTICS LOG DEBUG] PUT response: [reqId=null] 400
java.io.IOException: Unknown error while sending file, check network [/var/folders/5x/h_n5w6vd6sd9czw1jxzzwp4h0000gn/T/crashlytics-3fd31ec5-feb2-4a03-a665-e193e2e0e23c/nativeSymbols/com.example.foo/breakpad/app.android-arm64-arm64-349b90037e503a219d28a26ef22c904b.gz; response: 400 HTTP/1.1 400 Bad Request]
        at com.google.firebase.crashlytics.buildtools.api.RestfulWebApi.sendFile(RestfulWebApi.java:109)
        at com.google.firebase.crashlytics.buildtools.api.RestfulWebApi.uploadFile(RestfulWebApi.java:119)
        at com.google.firebase.crashlytics.buildtools.api.FirebaseSymbolFileService.uploadNativeSymbolFile(FirebaseSymbolFileService.java:35)
        at com.google.firebase.crashlytics.buildtools.Buildtools.uploadNativeSymbolFiles(Buildtools.java:301)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeUploadSymbols(CommandLineHelper.java:194)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeCommand(CommandLineHelper.java:120)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:65)
        at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:111)


Error: java command failed with args: -jar,/Users/user/.cache/firebase/crashlytics/buildtools/crashlytics-buildtools-2.9.2.jar,-symbolGenerator,breakpad,-symbolFileCacheDir,/var/folders/5x/h_n5w6vd6sd9czw1jxzzwp4h0000gn/T/crashlytics-3fd31ec5-feb2-4a03-a665-e193e2e0e23c/nativeSymbols/com.example.foo/breakpad,-verbose,-uploadNativeSymbols,-googleAppId,com.example.foo,-clientName,firebase-cli;crashlytics-buildtools
user@iDecode-MBP foo %
```

## Flutter doctor: 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.8.0-13.0.pre.79, on macOS 13.3.1 22E261 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2022.3)
[✓] VS Code (version 1.77.1)
[✓] Connected device (3 available)
[✓] Network resources
```

### Additional context:

- Using `firebase_crashlytics: 3.0.17`
- Already setup Firebase Crashlytics on the dashboard and I'm seeing crashes getting reported there (for both debug/release version on both iOS/Android)

**Comment by darshankawar** [comment]
@iLoveDocs 
Can you confirm if the `app_id` you are passing is correct ?

**Comment by iLoveDocs** [comment]
@darshankawar  Yes, that's correct. I double checked it (copying the one I used in the command and then searching for it in the `AndroidManifest.xml` file with "Match Case" and "Words" enabled.

**Comment by darshankawar** [comment]
Thanks for the update. Looking at the stacktrace, the error seems to be occuring while trying to upload the files:


`java.io.IOException: Unknown error while sending file, check network`

And below also seems to be coming from native :

```
at com.google.firebase.crashlytics.buildtools.api.RestfulWebApi.sendFile(RestfulWebApi.java:109)
        at com.google.firebase.crashlytics.buildtools.api.RestfulWebApi.uploadFile(RestfulWebApi.java:119)
        at com.google.firebase.crashlytics.buildtools.api.FirebaseSymbolFileService.uploadNativeSymbolFile(FirebaseSymbolFileService.java:35)
        at com.google.firebase.crashlytics.buildtools.Buildtools.uploadNativeSymbolFiles(Buildtools.java:301)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeUploadSymbols(CommandLineHelper.java:194)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeCommand(CommandLineHelper.java:120)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:65)
        at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:111)
```

Are you by any chance behind a firewall or proxy ? 
You may also want to upgrade the plugin version and framework version to latest just to make sure.

**Comment by iLoveDocs** [comment]
@darshankawar 

No, I am not using any firewall/proxy. In fact there are no third party apps installed on my machine related to VPNs.

We are very close to releasing the app so unfortunately, I can't upgrade any plugin or framework at the moment. 

I wished the error was more clear as to what the issue is.

**Comment by darshankawar** [comment]
Thanks for the update and patience. I tried to replicate this using the plugin example and was able to build the apk properly:

```
Running Gradle task 'assembleRelease'...                          161.1s
✓  Built build/app/outputs/flutter-apk/app-release.apk (16.9MB).

```

But while trying to upload symbols using below command, I am getting `error: unknown option '--app'`, not sure if I am passing the correct app_id what it is looking for. I tried the package name as well as the firebase_app_id but it is still giving me the same error.

Also, coming back to the error you are receiving, it seems to be coming from native side and as you are trying to run the command to upload the symbols, that seems to be related to the firebase CLI itself.

`you need to use the [Firebase CLI](https://firebase.google.com/docs/cli) (v.11.9.0+) to upload Android symbols.`.
So maybe try to reach out to firebase tools repo ?

**Comment by iLoveDocs** [comment]
Ok, I'll reach out to them. Thanks

**Comment by iLoveDocs** [comment]
@darshankawar  Do you also know if there's any direct way to upload the `symbols.zip` file to Firebase console? 
Thanks
