### ISSUE TITLE
🐛 [cloud_firestore]java.lang.RuntimeException: Internal error in Cloud Firestore (24.4.5)

### ISSUE THREAD

**Issue by ashley-arta** [firebase/flutterfire#10941]
## Bug report

**Describe the bug**
Crash in Android release build. 
Symbolicated crash log is attached.
Although the crash goes away when I turn off `minifyEnabled` and `shrinkResources`, it is not a proper solution and has undesired consequences.
Also, adding `com.google.firebase.firestore` to the proguard file instead of turning off `minifyEnabled` and `shrinkResources` doesn't fix the issue.

Thank you for your help in advance!

## Additional context

symbolicated crash

```
023-05-10 17:39:50.897 7521-7521/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: , PID: 7521
    java.lang.RuntimeException: Internal error in Cloud Firestore (24.4.5).
        at A2.AsyncQueue$$ExternalSyntheticLambda1.com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(R8$$SyntheticClass:5)
                                                   com.google.firebase.firestore.util.AsyncQueue$$InternalSyntheticLambda$1$ee0bb9e76d873eb0dc9297d9a9af24cf74be4371507e5d9f6cdb6af965a9e57b$0.run
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8757)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
     Caused by: s1.i: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
        at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.0.2:8)
        at com.google.firebase.firestore.remote.FirestoreChannel.com.google.firebase.firestore.remote.FirestoreChannel.lambda$runBidiStreamingRpc$0(FirestoreChannel.java:1)
                                                                 $r8$lambda$ThFui-hvcsrVGYxlBtcTH5vVbvE
        at z2.FirestoreChannel$$ExternalSyntheticLambda2.com.google.firebase.firestore.remote.FirestoreChannel$$InternalSyntheticLambda$2$f566b4153b534aa8580aa93faa9c580a04c89fec85c27cb978c537b6c327c368$0.onComplete(Unknown Source:6)
        at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:3)
        at java.lang.Thread.run(Thread.java:1012)
     Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
        at com.google.android.gms.tasks.zzz.run(com.google.android.gms:play-services-tasks@@18.0.2:3)
        at com.google.firebase.firestore.util.ThrottledForwardingExecutor.com.google.firebase.firestore.util.ThrottledForwardingExecutor.lambda$execute$0(ThrottledForwardingExecutor.java:1)
                                                                          $r8$lambda$MfIJbVuxZtLwosAgPzPA-cU66Ko
        at A2.ThrottledForwardingExecutor$$ExternalSyntheticLambda0.com.google.firebase.firestore.util.ThrottledForwardingExecutor$$InternalSyntheticLambda$3$315eca65e330db056b7a49c0f4857da93273eb5e29c07cc873bd0f103d01177e$0.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012) 
     Caused by: java.lang.ExceptionInInitializerError
        at io.grpc.okhttp.OkHttpChannelBuilder.forTarget(Unknown Source:0)
        at io.grpc.okhttp.OkHttpChannelProvider.io.grpc.okhttp.OkHttpChannelProvider.builderForTarget(Unknown Source:0)
                                                builderForTarget
        at io.grpc.ChannelLogger.io.grpc.ManagedChannelBuilder.forTarget(ChannelLogger.java:2)
        at com.google.firebase.firestore.remote.GrpcCallProvider.com.google.firebase.firestore.remote.GrpcCallProvider.initChannel(GrpcCallProvider.java:4)
                                                                 com.google.firebase.firestore.remote.GrpcCallProvider.lambda$initChannelTask$6
                                                                 $r8$lambda$SCD5iiibQ8l4haiO8ofSfE0wIJg
        at z2.GrpcCallProvider$$ExternalSyntheticLambda4.com.google.firebase.firestore.remote.GrpcCallProvider$$InternalSyntheticLambda$1$24dfe1452828c34b25291fc0adb6cd3bc1502d531cb543765315882230811d05$0.call(Unknown Source:2)
        at com.google.android.gms.tasks.zzz.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
        at A2.E.a(ThrottledForwardingExecutor.java:1) 
        at A2.D.run(Unknown Source:4) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
        at java.lang.Thread.run(Thread.java:1012) 
     Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: V3.q1.values []
        at java.lang.Enum.enumValues(Enum.java:272)
        at java.lang.Enum.-$$Nest$smenumValues(Unknown Source:0)
        at java.lang.Enum$1.create(Enum.java:279)
        at java.lang.Enum$1.create(Enum.java:277)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
        at java.lang.Enum.getSharedConstants(Enum.java:291)
        at java.lang.Class.getEnumConstantsShared(Class.java:2461)
        at java.util.EnumSet.getUniverse(EnumSet.java:412)
        at java.util.EnumSet.noneOf(EnumSet.java:114)
        at java.util.EnumSet.of(EnumSet.java:240)
        at io.grpc.okhttp.OkHttpChannelBuilder.<clinit>(OkHttpChannelBuilder.java:11)
        at X3.p.forTarget(Unknown Source:0) 
        at X3.q.a(Unknown Source:0) 
        at V3.i.m(ChannelLogger.java:2) 
        at z2.Q.d(GrpcCallProvider.java:4) 
        at z2.O.call(Unknown Source:2) 
        at s1.O.run(com.google.android.gms:play-services-tasks@@18.0.2:1) 
        at A2.E.a(ThrottledForwardingExecutor.java:1) 
        at A2.D.run(Unknown Source:4) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
        at java.lang.Thread.run(Thread.java:1012) 
     Caused by: java.lang.NoSuchMethodException: V3.q1.values []
        at java.lang.Class.getMethod(Class.java:2103)
        at java.lang.Class.getDeclaredMethod(Class.java:2081)
        at java.lang.Enum.enumValues(Enum.java:269)
        at java.lang.Enum.-$$Nest$smenumValues(Unknown Source:0) 
        at java.lang.Enum$1.create(Enum.java:279) 
        at java.lang.Enum$1.create(Enum.java:277) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63) 
        at java.lang.Enum.getSharedConstants(Enum.java:291) 
        at java.lang.Class.getEnumConstantsShared(Class.java:2461) 
        at java.util.EnumSet.getUniverse(EnumSet.java:412) 
        at java.util.EnumSet.noneOf(EnumSet.java:114) 
        at java.util.EnumSet.of(EnumSet.java:240) 
        at X3.p.<clinit>(OkHttpChannelBuilder.java:11) 
        at X3.p.forTarget(Unknown Source:0) 
        at X3.q.a(Unknown Source:0) 
        at V3.i.m(ChannelLogger.java:2) 
        at z2.Q.d(GrpcCallProvider.java:4) 
        at z2.O.call(Unknown Source:2) 
        at s1.O.run(com.google.android.gms:play-services-tasks@@18.0.2:1) 
        at A2.E.a(ThrottledForwardingExecutor.java:1) 
        at A2.D.run(Unknown Source:4) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
        at java.lang.Thread.run(Thread.java:1012) 
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.2 22D49 darwin-arm64, locale en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
[✓] VS Code (version 1.78.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @ashley-arta, can you try the solution in https://stackoverflow.com/a/73415635/10630669 to see if it works for you?

If it does not, can you make sure you're using the latest versions of the flutterfire plugins? And please also provide a complete minimal reproducible code sample along with steps to reproduce.

Thank you

**Comment by ashley-arta** [comment]
> Hi @ashley-arta, can you try the solution in https://stackoverflow.com/a/73415635/10630669 to see if it works for you?
> 
> If it does not, can you make sure you're using the latest versions of the flutterfire plugins? And please also provide a complete minimal reproducible code sample along with steps to reproduce.
> 
> Thank you

sorry I haven't tried to create a minimal reproducible code sample, but it's verified that the stackoverflow solution works. thanks!

**Comment by danagbemava-nc** [comment]
Thanks for the confirmation. 

Closing this as solved.

**Comment by eli1stark** [comment]
@ashley-arta What solution worked for you?
