### ISSUE TITLE
🐛 [firebase_auth] Unable to use in background isolate

### ISSUE THREAD

**Issue by timsauvageot** [firebase/flutterfire#10959]
## Bug report

**Describe the bug**
Firebase Auth throws the following error when used in background isolate.

```
Unsupported operation: Background isolates do not support setMessageHandler(). Messages from the host platform always go to the root isolate.
E/flutter ( 3629): #0      BackgroundIsolateBinaryMessenger.setMessageHandler (package:flutter/src/services/_background_isolate_binary_messenger_io.dart:94:5)
E/flutter ( 3629): #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:639:23)
E/flutter ( 3629): #2      _runGuarded (dart:async/stream_controller.dart:815:24)
E/flutter ( 3629): #3      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207:7)
E/flutter ( 3629): #4      _ControllerStream._createSubscription (dart:async/stream_controller.dart:828:19)
E/flutter ( 3629): #5      _StreamImpl.listen (dart:async/stream_impl.dart:471:9)
E/flutter ( 3629): #6      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
E/flutter ( 3629): #7      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
E/flutter ( 3629): #8      _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
E/flutter ( 3629): #9      new MethodChannelFirebaseAuth.<anonymous closure> (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:73:12)

```
### Steps to reproduce

1. Add Firebase config files to linked repo.
2. Start app and press floating action button (bottom right). The error should then appear in the console.

### Expected behavior

Firebase auth should not throw an error and work the same as on the main isolate.

### Sample project

https://github.com/timsauvageot/firebase_background

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.0, on macOS 12.6 21G115 darwin-x64, locale de-DE)
    ! Warning: `flutter` on your path resolves to /Users/timsauvageot/development/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/timsauvageot/fvm/versions/3.10.0. Consider adding /Users/timsauvageot/fvm/versions/3.10.0/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/timsauvageot/development/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/timsauvageot/fvm/versions/3.10.0. Consider adding /Users/timsauvageot/fvm/versions/3.10.0/bin to the front of your path.
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 3 categories.

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.0.0
Flutter SDK 3.10.0
firebase_background 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- firebase_auth 4.6.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.3.0 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.17.1
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 6.15.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.5.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.5.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- lints 2.0.1
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- path 1.8.3
- plugin_platform_interface 2.1.4 [meta]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
```

</details>

---

**Comment by Lyokone** [comment]
Closing in favour of https://github.com/firebase/flutterfire/issues/10353
