### ISSUE TITLE
🐛 [firebase_storage] Native cast exception is thrown on Android when maximum requested data is too large

### ISSUE THREAD

**Issue by mcmah309** [firebase/flutterfire#11068]
## Bug report

**Describe the bug**
Native cast exception is thrown on Android when maximum requested data is too large, even though the real size of the data in storage could be anything, even one byte.

### Steps to reproduce

`
FirebaseStorage.instance.ref("example/path").getData(9223372036854775807);
`

9223372036854775807 is the max int for flutter android

output in the device logs:
`
Showing sdk gphone x86 64 logs:
I/flutter (14501): The Dart VM service is listening on http://127.0.0.1:36121/D_tygeOp1zY=/
E/AndroidRuntime(14501): FATAL EXCEPTION: pool-2-thread-2
E/AndroidRuntime(14501): Process: com.example.test, PID: 14501
E/AndroidRuntime(14501): java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
E/AndroidRuntime(14501):        at io.flutter.plugins.firebase.storage.FlutterFirebaseStoragePlugin.lambda$referenceGetData$3$io-flutter-plugins-firebase-storage-FlutterFirebaseStoragePlugin(FlutterFirebaseStoragePlugin.java:261)
E/AndroidRuntime(14501):        at io.flutter.plugins.firebase.storage.FlutterFirebaseStoragePlugin$$ExternalSyntheticLambda12.run(Unknown Source:6)
E/AndroidRuntime(14501):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/AndroidRuntime(14501):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/AndroidRuntime(14501):        at java.lang.Thread.run(Thread.java:1012)
`
### Expected behavior

Data should be returned when the file exists in storage or an exception in flutter is thrown, not a native exception.

## Additional context

Flutter does not catch native plugin exceptions, so app will just terminate.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
[√] Android Studio (version 2021.3)
[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
[√] VS Code (version 1.78.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

```

</details>

**Comment by mcmah309** [comment]
Note: this can be avoided by setting the value to value to 2147483647, which is the max size of an Integer in java. Any larger and you get the issue above. That limits retrievals to about 2 GB maximum. This should be change to support larger values or at the very least throw an exception on the dart side if anything more is passed in.

**Comment by danagbemava-nc** [comment]
The crash can be reproduced using the plugin example app along with the code snippet shared above. 
I added the lines below to the sample app. 

Tapping on the FAB triggers the crash

```
floatingActionButton: FloatingActionButton(
        onPressed: () {
          FirebaseStorage.instance.ref("example/path").getData(9223372036854775807);
        },
      ),
```

**Comment by Lyokone** [comment]
Hello @mcmah309, this was fixed as part of the rewriting of the storage plugin using pigeon. Feel free to reopen if you are still experiencing this on the latest version but I was unable to reproduce it. Thanks
