### ISSUE TITLE
🐛 [cloud_firestore] ava.lang.RuntimeException: Internal error in Cloud Firestore (24.6.0).

### ISSUE THREAD

**Issue by eli1stark** [firebase/flutterfire#11087]
## Bug report

**Describe the bug**
The app is crashing only in release, when I'm accessing Firestore.
In debug and profile application works fine.
Reproducible only on Android.
I get 2 different crashes, but it's the same problem.

### Steps to reproduce

1. Use dependencies I provided below.
2. Write code that interacts with Firestore. 
3. Build and sign release APK.
4. Install apk on real device 

### Crash logs:
<details><summary>Crash 1</summary>

```
java.lang.RuntimeException: Internal error in Cloud Firestore (24.6.0).
 at n3.D.run(:3)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:224)
 at android.app.ActivityThread.main(ActivityThread.java:7562)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: com.google.android.gms.tasks.RuntimeExecutionException: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
 at com.google.android.gms.tasks.zzw.getResult(Unknown Source:19)
 at t3.I.c(:1)
 at t3.B.onComplete(Unknown Source:6)
 at com.google.android.gms.tasks.zzi.run(Unknown Source:21)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at u3.j.run(Unknown Source:15)
 at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
 at com.google.android.gms.tasks.zzz.run(Unknown Source:17)
 at u3.B.a(:1)
 at u3.A.run(Unknown Source:4)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 ... 1 more
Caused by: java.lang.ExceptionInInitializerError
 at D4.p.forTarget(Unknown Source:0)
 at D4.q.a(:1)
 at B4.K0.b(:2)
 at t3.L.d(:2)
 at t3.K.call(Unknown Source:10)
 at com.google.android.gms.tasks.zzz.run(Unknown Source:4)
 ... 5 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: B4.E1.values []
 at java.lang.Enum.enumValues(Enum.java:270)
 at java.lang.Enum.access$000(Enum.java:61)
 at java.lang.Enum$1.create(Enum.java:277)
 at java.lang.Enum$1.create(Enum.java:275)
 at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
 at java.lang.Enum.getSharedConstants(Enum.java:289)
 at java.lang.Class.getEnumConstantsShared(Class.java:2428)
 at java.util.EnumSet.getUniverse(EnumSet.java:407)
 at java.util.EnumSet.noneOf(EnumSet.java:109)
 at java.util.EnumSet.of(EnumSet.java:235)
 at D4.p.<clinit>(Unknown Source:69)
 ... 11 more
Caused by: java.lang.NoSuchMethodException: B4.E1.values []
 at java.lang.Class.getMethod(Class.java:2072)
 at java.lang.Class.getDeclaredMethod(Class.java:2050)
 at java.lang.Enum.enumValues(Enum.java:267)
 ... 21 more
```

</details>

<details><summary>Crash 2</summary>

```
java.lang.ExceptionInInitializerError
	at com.google.android.gms.measurement.internal.R2.<init>(Unknown Source:34)
	at com.google.android.gms.measurement.internal.U1.<init>(:3)
	at com.google.android.gms.measurement.internal.U1.F(:4)
	at com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.initialize(:2)
	at com.google.android.gms.internal.measurement.w0.a(:4)
	at com.google.android.gms.internal.measurement.N0.run(Unknown Source:12)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: l2.h.values []
	at java.lang.Enum.enumValues(Enum.java:270)
	at java.lang.Enum.access$000(Enum.java:61)
	at java.lang.Enum$1.create(Enum.java:277)
	at java.lang.Enum$1.create(Enum.java:275)
	at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
	at java.lang.Enum.getSharedConstants(Enum.java:289)
	at java.lang.Class.getEnumConstantsShared(Class.java:2428)
	at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
	at java.util.EnumMap.<init>(EnumMap.java:138)
	at l2.i.<init>(Unknown Source:7)
	at l2.i.<clinit>(Unknown Source:5)
	... 9 more
Caused by: java.lang.NoSuchMethodException: l2.h.values []
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getDeclaredMethod(Class.java:2050)
	at java.lang.Enum.enumValues(Enum.java:267)
	... 19 more
```

</details>

### Expected behavior

App should not crash.

## Additional context

What I tried doesn't work.

### First try

```
release {
    signingConfig signingConfigs.release
    minifyEnabled true
    shrinkResources true
    proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
}
 ```

and **proguard-rules.pro**

```
-keep class com.google.android.gms.measurement.internal.** { *; }
-keep class io.grpc.** {*;}
```

### Second try

```
release {
    signingConfig signingConfigs.release
    minifyEnabled false
    shrinkResources false
    proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
}
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.3.1 22E772610a darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.78.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
firebase_core: 2.13.1
firebase_crashlytics: 3.3.2
firebase_analytics: 10.4.2
firebase_dynamic_links: 5.3.2
firebase_app_check: 0.1.4+2
firebase_auth: 4.6.2
cloud_firestore: 4.8.0
cloud_functions: 4.3.2
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @eli1stark, can you provide a complete minimal reproducible code sample in a repo that we can clone? I used the steps you have outlined above but I cannot reproduce the crash you're reporting.

**Comment by eli1stark** [comment]
Okay, it took me the whole day, but I narrowed down the issue very well.

Steps to reproduce:

1. Create Firebase project
2. Enable Authentication with Email and Password
3. Create Firestore database
4. Clone this repo: https://github.com/eli1stark/cloud_bug
5. Run `flutterfire configure`, choose your project, it will create necessary files, including firebase_options.dart
6. Run `flutter build apk`, this will create release apk, I pushed keystore file with key.properties, so you don't need to worry about creating the new one. This is burner keystore, you can safely use it.
7. Install APK on the physical Android device and launch the app.
8. If you don't have account press `createUserWithEmailAndPassword` button, if you have account press `signInWithEmailAndPassword` button.
9. Once you successfully signed in, press `Run transaction` button.
10. The app should crash.

The main parts of the project are `main.dart` which is 100 lines of code and `pubspec.yaml`.

To create a project I ran a standard template from VSCode for the flutter app and I had to modify `build.gradle` files a little bit in order to build the app successfully.

My investigation concluded that it has something to do with `android_intent_plus` package, if I remove it, Firestore doesn't crash, but it's super weird, why some random package is crashing Firestore and only in signed release mode. Debug release like `flutter run --release` works fine as well as regular debug and profile.

Please let me know whether you are able to reproduce it, I'm here to assist you.

**Comment by darshankawar** [comment]
@eli1stark 
Take a look at this similar issue and see if it helps in your case or not: https://github.com/firebase/flutterfire/issues/10941

Also, check what version of `classpath 'com.android.tools.build:gradle` you have in your app and try with latest version to see if it works or not.

**Comment by eli1stark** [comment]
For maintainers and everyone who encounters it, I created 2 branches, you can see exactly what I changed in attached commit links.

[`latest-gradle`](https://github.com/eli1stark/cloud_bug/commit/bfec693381a6ef6f9bf357a2bd12993e14ff6fda) - Updated gradle and google-services to the latest versions, minify enabled. In this case even firebase auth stops working. 

[`latest-gradle-no-minify`](https://github.com/eli1stark/cloud_bug/commit/6307a877e96ad7008dacacec9a0bd5d1dc9aaf77) - The same as previous branch but minify disabled. App does not crash, works fine.

Will I have any issues with firebase when using gradle 8?

And this is not normal that Android cuts the functionality of firebase packages. Can we resolve this somehow on the higher level? Or maybe mention it in the docs because scanning through `Flutterfire` issues there are many issues that are related to this problem in one or another way.

**Comment by eli1stark** [comment]
Gradle 8 doesn't build with some popular packages, it seems too cutting edge, I downgraded to 7.4.2. and created a new branch.

[`semi-latest-no-minify`](https://github.com/eli1stark/cloud_bug/commit/c9b8a1fd54ad57bbda9996899781bced96be0423) - The same as `latest-gradle-no-minify` but I downgraded gradle.

**Comment by darshankawar** [comment]
@eli1stark 
See https://github.com/firebase/flutterfire/issues/10825#issuecomment-1534694301 for your reference.
