### ISSUE TITLE
🐛 [firebase_auth] Unable to destroy activity java.lang.NullPointerException

### ISSUE THREAD

**Issue by mfizz1** [firebase/flutterfire#11291]
## Bug report

**Describe the bug**
Upon exit of app. Produces an poor exit, doesn't impact UX.

### Steps to reproduce

Difficult to replicate, similar null point errors have been reported before.

### Expected behavior

Graceful exit

## Additional context

<details><summary>Click To Expand</summary>

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.example.app/com.example.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void y3.c.b(java.lang.String, y3.c$a)' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5111)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5140)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7656)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:949)

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void y3.c.b(java.lang.String, y3.c$a)' on a null object reference
       at y3.a.e(:37)
       at b4.s1.w(:23)
       at b4.u.q(:10)
       at io.flutter.embedding.engine.c.w(:121)
       at io.flutter.embedding.engine.c.x(:16)
       at io.flutter.embedding.engine.c.y(:11)
       at io.flutter.embedding.engine.c.l(:10)
       at io.flutter.embedding.engine.a.f(:31)
       at io.flutter.embedding.android.e.u(:98)
       at io.flutter.embedding.android.d.onDestroy(:18)
       at android.app.Activity.performDestroy(Activity.java:8266)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5096)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5140)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7656)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:949)

awaitEvenIfOnMainThread task continuation executor1:
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at g1.x$a$a.a(:2)
       at g1.d.run(:5)
       at java.lang.Thread.run(Thread.java:923)
```
Further analysis of logcat shows:

```
07-16 04:03:50.016 21673 21673 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:123) 07-16 04:03:50.016 21673 21673 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:457) 07-16 04:03:50.016 21673 21673 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:767) 07-16 04:03:50.016 21673 21673 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:908) 07-16 04:03:50.016 21673 21673 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:8478) 07-16 04:03:50.016 21673 21673 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1355) 07-16 04:03:50.016 21673 21673 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5863) 07-16 04:03:50.016 21673 21673 E 
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output

<details><summary>Click To Expand</summary>

</details>

---

**Comment by Zoxive** [comment]
Getting the same error on app exit.

```
java.lang.RuntimeException: Unable to destroy activity {***.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
  at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5424)
  at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5457)
  at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
  at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:179)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loopOnce(Looper.java:201)
  at android.os.Looper.loop(Looper.java:288)
  at android.app.ActivityThread.main(ActivityThread.java:7918)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
  at io.flutter.plugin.common.BasicMessageChannel.setMessageHandler(BasicMessageChannel.java:132)
  at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthHostApi$-CC.setup(GeneratedAndroidFirebaseAuth.java:2366)
  at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.onDetachedFromEngine(FlutterFirebaseAuthPlugin.java:81)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:272)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:282)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:290)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:123)
  at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:457)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:767)
  at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:908)
  at android.app.Activity.performDestroy(Activity.java:8599)
  at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1452)
  at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5411)
```

**Comment by note11g** [comment]
me too.
it's cause crash when exiting app.
If it ends abnormally like this, the next time you run the app, the app may not run properly.

it's crash log.
```
E/AndroidRuntime(16787): java.lang.RuntimeException: Unable to destroy activity {io.spacet.gogo.gogo_mvp/io.spacet.gogo.gogo_mvp.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
E/AndroidRuntime(16787): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6080)
E/AndroidRuntime(16787): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6113)
E/AndroidRuntime(16787): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
E/AndroidRuntime(16787): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(16787): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime(16787): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(16787): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
E/AndroidRuntime(16787): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16787): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(16787): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(16787): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(16787): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16787): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/AndroidRuntime(16787): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(16787): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
E/AndroidRuntime(16787): 	at io.flutter.plugin.common.BasicMessageChannel.setMessageHandler(BasicMessageChannel.java:132)
E/AndroidRuntime(16787): 	at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthHostApi.setup(GeneratedAndroidFirebaseAuth.java:2366)
E/AndroidRuntime(16787): 	at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.onDetachedFromEngine(FlutterFirebaseAuthPlugin.java:81)
E/AndroidRuntime(16787): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:272)
E/AndroidRuntime(16787): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:282)
E/AndroidRuntime(16787): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:290)
E/AndroidRuntime(16787): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:123)
E/AndroidRuntime(16787): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:457)
E/AndroidRuntime(16787): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:767)
E/AndroidRuntime(16787): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:908)
E/AndroidRuntime(16787): 	at android.app.Activity.performDestroy(Activity.java:8864)
E/AndroidRuntime(16787): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1419)
E/AndroidRuntime(16787): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6067)
E/AndroidRuntime(16787): 	... 13 more
I/Process (16787): Sending signal. PID: 16787 SIG: 9
```

**Comment by bhumkong** [comment]
Same bug, but it happens on launch, causing my app crash (not every time).
Fixed by pinning dependencies:
```
firebase_auth: 4.6.3
firebase_auth_platform_interface: 6.15.3
```

**Comment by darshankawar** [comment]
Thanks for the report and potential fix.
A similar issue was fixed last year: https://github.com/firebase/flutterfire/issues/9210

/cc @Lyokone

**Comment by forYouDevelop** [comment]
I have the same issue on 4.7.0

**Comment by note11g** [comment]
I've submitted a PR (#11296) to fix this issue.
If you have a moment, I'd really appreciate it if you could kindly review it. Thank you so much!

@darshankawar

**Comment by mulderpf** [comment]
I upgraded my production app and I'm SWAMPED with thousands of these crashes.  It seems to happen when the app is trying to shut down.  I just tested it myself and it seems to happen when I close the app down.  This started from 4.7.0.

**Comment by fischja** [comment]
Same issue here
