### ISSUE TITLE
🐛 [firebase_auth] Task is not yet complete

### ISSUE THREAD

**Issue by Fudal** [firebase/flutterfire#11297]
## Bug report

**Describe the bug**
After update 4.7.0 my app is still crashing with errors:

```
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): Failed to handle message
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): java.lang.IllegalStateException: Task is not yet complete
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at com.google.android.gms.common.internal.Preconditions.checkState(com.google.android.gms:play-services-basement@@18.2.0:2)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at com.google.android.gms.tasks.zzw.zzf(com.google.android.gms:play-services-tasks@@18.0.2:1)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.0.2:1)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthUser.getIdToken(FlutterFirebaseAuthUser.java:95)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthUserHostApi.lambda$setup$1(GeneratedAndroidFirebaseAuth.java:3256)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthUserHostApi$$ExternalSyntheticLambda9.onMessage(Unknown Source:2)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at android.os.Handler.handleCallback(Handler.java:942)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at android.os.Looper.loopOnce(Looper.java:240)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at android.os.Looper.loop(Looper.java:351)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at android.app.ActivityThread.main(ActivityThread.java:8416)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at java.lang.reflect.Method.invoke(Native Method)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(28161): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

```
E/AndroidRuntime(28161): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(28161): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime(28161): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler$1.reply(BasicMessageChannel.java:222)
E/AndroidRuntime(28161): 	at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthUserHostApi$2.success(GeneratedAndroidFirebaseAuth.java:3247)
E/AndroidRuntime(28161): 	at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthUserHostApi$2.success(GeneratedAndroidFirebaseAuth.java:3244)
E/AndroidRuntime(28161): 	at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthUser.lambda$getIdToken$1(FlutterFirebaseAuthUser.java:88)
E/AndroidRuntime(28161): 	at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthUser$$ExternalSyntheticLambda2.onComplete(Unknown Source:2)
E/AndroidRuntime(28161): 	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
```

### Steps to reproduce

```
try {
      final FirebaseAuth auth = FirebaseAuth.instance;
      auth.tenantId = AppConfigValues.firebaseTenantId;
      final IdTokenResult? token = await auth.currentUser?.getIdTokenResult(true);
} on FirebaseAuthException catch (e) {
      // here is error:
      e = {FirebaseAuthException} [firebase_auth/channel-error] Unable to establish connection on channel.
       plugin = "firebase_auth"
       message = "Unable to establish connection on channel."
       code = "channel-error"
       stackTrace = null
       email = null
       credential = null
       phoneNumber = null
       tenantId = null
}
```
### Expected behavior
Working without errors

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale pl-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1.4)
[✓] VS Code (version 1.79.2)
Unknown architecture undefined_arch, defaulting to arm64
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

---

**Comment by cmenkemeller** [comment]
We are also experiencing the same issue after updating to 4.7.0

**Comment by kdokhanx98** [comment]
This issue is related to getIdTokenResult and getIdToken functions, please fix asap

**Comment by bhanuka96** [comment]
Temporary solution: I downgraded all plugins that require Dart 3 or a higher version. 

In this Dart setting, From `sdk: '>=3.0.0 <4.0.0'` to `sdk: ">=2.11.0 <3.0.0"`

**Comment by bhanuka96** [comment]
Temporary solution: I downgraded all plugins that require Dart 3 or a higher version and downgraded Flutter SDK. Now it's working fine.

In pubscpec.yaml, `">=2.11.0 <3.0.0"`
in flutter SDK: `3.7.12`

Downgrade all firebase plugins:

```
firebase_auth: 4.6.2
firebase_auth: 4.6.2
firebase_analytics: 10.4.2
firebase_core: 2.13.1
firebase_crashlytics: 3.3.2
firebase_database: 10.2.2
firebase_dynamic_links: 5.3.2
firebase_messaging: 14.6.2
firebase_storage: 11.2.2
```

**Comment by dgilperez** [comment]
@bhanuka96  do you really need to downgrade all Firebase packages, or just `firebase_auth`? And why 4.6.2 and now 4.6.3? Thanks :)

**Comment by bhanuka96** [comment]
@dgilperez I tried downgrading the `auth` plugin, but it didn't work. Then, I downgraded all the Firebase plugins. I didn't try other versions because I needed to know if other firebase plugin versions too. Ex: 6.2.3, supports different versions of Firebase core. It's boring to change version by version

**Comment by MCord** [comment]
downgrading these two dependencies seems to be functioning as a workaround

```
firebase_auth: 4.6.2 
firebase_core: 2.13.1
```

**Comment by bhumkong** [comment]
As a temporary solution I pinned these versions:
```
firebase_auth: 4.6.3
firebase_auth_platform_interface: 6.15.3
```

**Comment by Valansch** [comment]
> As a temporary solution I pinned these versions:
> 
> ```
> firebase_auth: 4.6.3
> firebase_auth_platform_interface: 6.15.3
> ```

Can confirmed this works for me. No need to pin firebase_core

**Comment by bizz84** [comment]
I've put together an example project that can be used to reproduce the issue consistently:

https://github.com/bizz84/firebase_id_token_bug

All is needed to reproduce the issue is to call `user.getIdToken(true)` after sign in.

### How to run the example project

- Create a new project in the Firebase console and note the project ID.
- Enable Email & Password as a sign in method
  
Then run these commands on the terminal:

```
flutterfire configure --project firebase-project-id
flutter run # use Android emulator as a target device
```

Once the app is running, register a new account using email and password.

At this point the app will crash with this error:

```
IllegalStateException: Task is not yet complete
```

**Comment by russellwheatley** [comment]
Taking a look. Thanks for your patience 🙏

**Comment by russellwheatley** [comment]
I have a fix, will get a release out once it is reviewed/merged.

**Comment by cmenkemeller** [comment]
> I have a fix, will get a release out once it is reviewed/merged. 

For those who want to track the PR-

https://github.com/firebase/flutterfire/pull/11362

**Comment by vytautas-pranskunas-** [comment]
@cmenkemeller there was a question for you in PR. PR is blocked :(

**Comment by vorachirag318** [comment]
@bhanuka96 I am using this package but still not issue resolved
firebase_auth: 4.6.2
firebase_analytics: 10.4.2
firebase_core: 2.13.1

**Comment by sarankumar-ns** [comment]
+1

**Comment by bhanuka96** [comment]
> @bhanuka96 I am using this package but still not issue resolved firebase_auth: 4.6.2 firebase_analytics: 10.4.2 firebase_core: 2.13.1

Try to `flutter clean` and delete `pubspec.lock` file and try again.

**Comment by vorachirag318** [comment]
@bhanuka96 When Firebase auth token expired, the refresh time  (FirebaseAuth.instance.currentUser?.getIdToken()) gets the app crashed and tries to flutter clean and pubspec.lock deleted. 

I am using this package 
firebase_auth: 4.6.2
firebase_analytics: 10.4.2
firebase_core: 2.13.1

**Comment by cmile-aditya-bhandare** [comment]
```
await FirebaseAuth.instance.currentUser
          ?.getIdToken()
          .then(
            (token) => {
         
              print("TOKEN-----$token"),
           
            },
          )
          .catchError(
            (error) => {
              print("TOKEN ERROR-----" + error.message),
            },
          );
```

I was getting the same error for the above method.
If I dont pass parameter to  `?.getIdToken()`
It is working for me  and able to print the token as well.

Im using these firebase version
```
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
```

**Comment by sunstar21** [comment]
> @bhanuka96 I am using this package but still not issue resolved firebase_auth: 4.6.2 firebase_analytics: 10.4.2 firebase_core: 2.13.1

4.6.3 works - tried it, after like 100 different things, literally changing the version by 1 worked

**Comment by bhanuka96** [comment]
@sunstar21 Just update to the latest version, they fixed the issue in it

**Comment by FetFrumos** [comment]
I have this issue with  firebase_auth ^4.7.2(last version).

It is helped for me

`firebase_auth: 4.6.3
firebase_auth_platform_interface: 6.15.3`

**Comment by vorachirag318** [comment]
@FetFrumos please delete pubspace.lock file and then again pub get then test it
