### ISSUE TITLE
🐛 [firebase_messaging] java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Object[]

### ISSUE THREAD

**Issue by kunalpowar** [firebase/flutterfire#11352]
## Bug report

**Describe the bug**
```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Object[]
	 at androidx.collection.SimpleArrayMap.allocArrays(SimpleArrayMap.java:58)
	 at androidx.collection.SimpleArrayMap.put(SimpleArrayMap.java:56)
	 at com.google.firebase.messaging.Constants$MessagePayloadKeys.extractDeveloperDefinedPayload(Constants.java:75)
	 at com.google.firebase.messaging.RemoteMessage.getData(RemoteMessage.java:6)
	 at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingUtils.remoteMessageToMap(FlutterFirebaseMessagingUtils.java:85)
	 at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin.onReceive(FlutterFirebaseMessagingPlugin.java:48)
	 at androidx.fragment.app.strictmode.FragmentReuseViolation.a(FragmentReuseViolation.java:59)
	 at l0.a$a.handleMessage(a.java:11)
	 at android.os.Handler.dispatchMessage(Handler.java:106)
	 at android.os.Looper.loopOnce(Looper.java:233)
	 at android.os.Looper.loop(Looper.java:344)
	 at android.app.ActivityThread.main(ActivityThread.java:8248)
	 at java.lang.reflect.Method.invoke(Method.java)
	 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
```

### Steps to reproduce
I am not able to reproduce this error. But I see a lot of instances of this causing a crash in production. 

## Additional context
This crash has existed from a very old version. I've updated the plugin as a fix, but this particular crash does not seem to go away. 

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.2 22D49 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Resolving dependencies...
Got dependencies.
Dart SDK 3.0.6
Flutter SDK 3.10.6
app 1.0.0+1

dependencies:
- android_intent_plus 4.0.1 [flutter platform meta]
- animated_text_kit 4.2.2 [flutter characters]
- appcheck 1.0.6 [flutter]
- badges 3.1.1 [flutter]
- built_collection 5.1.1
- built_value 8.6.1 [built_collection collection fixnum meta]
- cached_network_image 3.2.3 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- carousel_slider 4.2.1 [flutter]
- collection 1.17.1
- confetti 0.7.0 [flutter vector_math]
- connectivity_plus 4.0.1 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- cupertino_icons 1.0.5
- custom_sliding_segmented_control 1.7.5 [flutter]
- device_info_plus 9.0.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- diffutil_dart 4.0.0
- dio 5.3.0 [async http_parser meta path]
- dotlottie_loader 0.0.3 [archive flutter]
- equatable 2.0.5 [collection meta]
- fake_async 1.3.1 [clock collection]
- ferry 0.14.2+1 [gql rxdart gql_link gql_exec meta collection hive built_value ferry_exec normalize ferry_cache]
- ferry_cache 0.7.1+2 [ferry_exec meta rxdart normalize ferry_store collection pedantic]
- ferry_exec 0.3.1 [gql gql_exec gql_link meta async collection built_collection built_value]
- ferry_hive_store 0.5.1 [hive ferry_store rxdart collection]
- firebase_app_check 0.1.5+1 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.6.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.15.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.3.4 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 14.6.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.9.2+4 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_remote_config 4.2.4 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_storage 11.2.5 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- fl_chart 0.63.0 [equatable flutter]
- flame 1.8.1 [collection flutter meta ordered_set vector_math]
- flame_audio 2.0.4 [audioplayers flame flutter synchronized]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_animator 3.2.2 [flutter vector_math]
- flutter_contacts 1.1.7 [flutter]
- flutter_facebook_auth 5.0.11 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web facebook_auth_desktop]
- flutter_fancy_tree_view 1.1.1 [flutter]
- flutter_fortune_wheel 1.3.0 [flutter flutter_hooks quiver]
- flutter_inappwebview 5.7.2+3 [flutter]
- flutter_local_notifications 15.1.0+1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_native_splash 2.3.1 [args flutter flutter_web_plugins js html image meta path universal_io xml yaml]
- flutter_portal 1.1.4 [collection flutter vector_math]
- flutter_riverpod 2.3.6 [collection flutter meta riverpod state_notifier]
- flutter_screenutil 5.8.4 [flutter]
- flutter_staggered_animations 1.1.1 [flutter]
- flutter_svg 2.0.7 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_switch 0.3.2 [flutter]
- flutter_vibrate 1.3.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- flutter_windowmanager 0.2.0 [flutter]
- fpjs_pro_plugin 1.6.0 [flutter flutter_web_plugins js]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- go_router 8.2.0 [collection flutter flutter_web_plugins logging meta]
- google_fonts 4.0.4 [flutter http path_provider crypto]
- google_sign_in 6.1.4 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- gql 1.0.0 [collection meta source_span yaml]
- gql_code_builder 0.7.2 [analyzer built_collection built_value code_builder collection gql gql_exec path]
- gql_exec 1.0.0 [collection gql meta]
- gql_http_link 1.0.1 [gql gql_exec gql_link http http_parser meta]
- gql_link 1.0.0 [gql gql_exec meta]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- hypersdkflutter 4.0.1 [flutter]
- inai_flutter_sdk 0.1.5 [flutter webview_flutter http pay yaml url_launcher]
- instabug_flutter 11.5.0 [flutter meta stack_trace]
- interpolate_animated 0.0.1 [flutter]
- intl 0.18.0 [clock meta path]
- json_annotation 4.8.1 [meta]
- lottie 2.5.0 [archive flutter path vector_math]
- mocktail 0.3.0 [collection matcher test]
- move_to_background 1.0.2 [flutter]
- normalize 0.8.2+1 [gql collection]
- ntp 2.0.0
- once 1.5.3 [flutter shared_preferences package_info_plus]
- ota_update 5.1.0 [flutter]
- package_info_plus 4.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- path_provider 2.0.15 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 10.4.3 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- photo_view 0.14.0 [flutter]
- pubnub 4.2.3 [async cbor convert crypto encrypt form_data meta pedantic pool xml]
- rate_limiter 1.0.0
- restart_app 1.2.1 [flutter plugin_platform_interface flutter_web_plugins]
- retry 3.1.2
- rive 0.11.4 [collection flutter flutter_web_plugins http meta plugin_platform_interface rive_common]
- riverpod_annotation 2.1.1 [meta riverpod]
- rxdart 0.27.7
- scrollable_positioned_list 0.3.8 [flutter collection]
- share_plus 7.0.2 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- shared_preferences 2.2.0 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- simple_animations 5.0.2 [flutter collection]
- sms_autofill 2.3.0 [pin_input_text_field flutter]
- speech_balloon 0.0.4 [flutter]
- story_view 0.15.0 [flutter flutter_cache_manager rxdart video_player collection]
- supercharged 2.1.1 [supercharged_dart flutter]
- svg_path_parser 1.1.1 [string_scanner flutter]
- talker_flutter 3.1.7 [flutter talker group_button path_provider share_plus]
- tilt_extensions 0.0.1 [flutter flutter_riverpod]
- url_launcher 6.1.12 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_platform_interface 2.1.3 [flutter plugin_platform_interface]
- uuid 3.0.7 [crypto]
- video_player 2.7.0 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- visibility_detector 0.4.0+2 [flutter]

dev dependencies:
- analyzer 5.12.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_runner 2.4.6 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- convert 3.1.1 [typed_data]
- crypto 3.0.3 [typed_data]
- custom_lint 0.4.0 [analyzer analyzer_plugin args async ci cli_util collection freezed_annotation json_annotation meta package_config path pub_semver pubspec_parse rxdart uuid yaml]
- dlcov 4.2.1 [args lcov_parser]
- ferry_generator 0.8.2-dev.0 [gql gql_code_builder built_collection code_builder build path ferry_exec yaml dart_style glob built_value_generator built_value analyzer]
- flutter_lints 2.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- freezed 2.4.1 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- go_router_builder 2.2.2 [analyzer async build build_config collection meta path path_to_regexp source_gen source_helper]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service async boolean_selector characters clock collection fake_async file js matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math webdriver]
- json_serializable 6.7.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- lints 2.1.1
- patrol 2.1.0 [fixnum flutter flutter_test grpc integration_test meta path protobuf test_api]
- pigeon 10.0.0 [analyzer args collection meta path yaml]
- plugin_platform_interface 2.1.4 [meta]
- riverpod_generator 2.2.3 [analyzer build build_config collection crypto meta path riverpod_analyzer_utils riverpod_annotation source_gen]
- riverpod_lint 1.3.2 [analyzer analyzer_plugin collection custom_lint_builder meta path riverpod riverpod_analyzer_utils source_span yaml]
- source_gen 1.4.0 [analyzer async build dart_style glob path source_span yaml]

transitive dependencies:
- _fe_analyzer_shared 60.0.0 [meta]
- _flutterfire_internals 1.3.4 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer_plugin 0.11.2 [analyzer collection dart_style pub_semver yaml]
- ansicolor 2.0.1
- archive 3.3.7 [crypto path pointycastle]
- args 2.4.2
- asn1lib 1.4.0
- async 2.11.0 [collection meta]
- audioplayers 4.1.0 [audioplayers_android audioplayers_darwin audioplayers_linux audioplayers_platform_interface audioplayers_web audioplayers_windows file flutter http meta path_provider synchronized uuid]
- audioplayers_android 3.0.2 [audioplayers_platform_interface flutter]
- audioplayers_darwin 4.1.0 [audioplayers_platform_interface flutter]
- audioplayers_linux 2.1.0 [audioplayers_platform_interface flutter]
- audioplayers_platform_interface 5.0.1 [flutter meta plugin_platform_interface]
- audioplayers_web 3.1.0 [audioplayers_platform_interface flutter flutter_web_plugins js]
- audioplayers_windows 2.0.2 [audioplayers_platform_interface flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.2.0 [analyzer async build collection crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.10 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_value_generator 8.6.1 [analyzer build build_config built_collection built_value collection source_gen]
- cached_network_image_platform_interface 2.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.2 [flutter flutter_cache_manager cached_network_image_platform_interface]
- cbor 4.1.0 [typed_data convert meta]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- ci 0.1.0
- cli_util 0.4.0 [meta path]
- clock 1.1.1
- code_builder 4.5.0 [built_collection built_value collection matcher meta]
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- coverage 1.6.3 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.3+4 [js meta]
- csslib 0.17.3 [source_span]
- custom_lint_builder 0.4.0 [analyzer analyzer_plugin collection custom_lint custom_lint_core glob hotreloader meta path pubspec_parse rxdart]
- custom_lint_core 0.4.0 [analyzer analyzer_plugin collection custom_lint matcher meta path pubspec_parse source_span yaml]
- dart_style 2.3.1 [analyzer args path pub_semver source_span]
- dbus 0.7.8 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- facebook_auth_desktop 0.0.9 [flutter http flutter_secure_storage flutter_facebook_auth_platform_interface]
- ferry_store 0.5.3 [rxdart collection]
- ffi 2.0.2
- file 6.1.4 [meta path]
- firebase_app_check_platform_interface 0.0.9+1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.11+1 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.15.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.5.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.6.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.4 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.3 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.3 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance_platform_interface 0.1.4+4 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.4+4 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]
- firebase_remote_config_platform_interface 1.4.4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.4.4 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- firebase_storage_platform_interface 4.4.4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.6.5 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.1.0
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver async boolean_selector characters clock collection js matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math]
- flutter_facebook_auth_platform_interface 4.1.1 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 4.1.1 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_hooks 0.18.6 [flutter]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection js material_color_utilities meta path vector_math]
- flutter_secure_storage 8.0.0 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_secure_storage_linux 1.1.3 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.0.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.1 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.1.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 2.0.0 [flutter flutter_secure_storage_platform_interface]
- form_data 1.0.0-nullsafety.1
- frontend_server_client 3.2.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.2.1 [js meta]
- google_sign_in_android 6.1.15 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.6.2 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.1 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.12.0+1 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http js]
- googleapis_auth 1.4.1 [args crypto http http_parser js]
- graphs 2.3.1 [collection]
- group_button 5.3.0 [flutter]
- grpc 3.1.0 [archive async crypto fixnum googleapis_auth meta http http2 protobuf]
- hive 2.2.3 [meta crypto]
- hotreloader 3.0.6 [collection logging path stream_transform vm_service watcher]
- html 0.15.3 [csslib source_span]
- http 0.13.6 [async http_parser meta]
- http2 2.0.1
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.0.17 [archive meta xml]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- lcov_parser 0.1.2 [args path collection]
- logging 1.2.0
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- mime 1.0.4
- nm 0.5.0 [dbus]
- node_preamble 2.0.2
- octo_image 1.0.2 [flutter flutter_blurhash]
- ordered_set 5.0.1
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.3
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.0.27 [flutter path_provider_platform_interface]
- path_provider_foundation 2.2.3 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.11 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.6 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.7 [ffi flutter path path_provider_platform_interface win32]
- path_to_regexp 0.4.0
- pay 1.1.1 [flutter flutter_localizations pay_android pay_ios pay_platform_interface meta]
- pay_android 1.0.10 [flutter flutter_localizations pay_platform_interface flutter_svg]
- pay_ios 1.0.8 [flutter pay_platform_interface]
- pay_platform_interface 1.0.3 [flutter yaml]
- pedantic 1.11.1
- permission_handler_android 10.3.0 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.1.2 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.11.0+1 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.3 [flutter permission_handler_platform_interface]
- petitparser 5.4.0 [meta]
- pin_input_text_field 4.5.0 [flutter]
- platform 3.1.0
- pointycastle 3.7.3 [collection convert js]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- protobuf 2.1.0 [fixnum collection meta]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.1 [matcher]
- rive_common 0.1.0 [collection ffi flutter flutter_web_plugins graphs http meta plugin_platform_interface]
- riverpod 2.3.6 [meta stack_trace state_notifier]
- riverpod_analyzer_utils 0.3.1 [analyzer collection crypto custom_lint_core freezed_annotation meta path source_span]
- share_plus_platform_interface 3.2.1 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.1.4 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.2.2 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.2.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.1.0 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.2.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.2 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_helper 1.3.3 [analyzer collection source_gen]
- source_map_stack_trace 2.1.1 [path source_maps stack_trace]
- source_maps 0.10.12 [source_span]
- source_span 1.9.1 [collection path term_glyph]
- sqflite 2.2.8+4 [flutter sqflite_common path]
- sqflite_common 2.4.5 [synchronized path meta]
- stack_trace 1.11.0 [path]
- state_notifier 0.7.2+1 [meta]
- stream_channel 2.1.1 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- supercharged_dart 2.1.1
- sync_http 0.3.1
- synchronized 3.1.0
- talker 3.0.2 [talker_logger]
- talker_logger 3.0.1 [ansicolor]
- term_glyph 1.2.1
- test 1.24.1 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core matcher]
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.5.1 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timezone 0.9.2 [path]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_android 6.0.35 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_web 2.0.17 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.6 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.7 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.7
- vector_graphics_compiler 1.1.7 [args meta path_parsing xml vector_graphics_codec]
- vector_math 2.1.4
- video_player_android 2.4.9 [flutter video_player_platform_interface]
- video_player_avfoundation 2.4.6 [flutter video_player_platform_interface]
- video_player_platform_interface 6.1.0 [flutter plugin_platform_interface]
- video_player_web 2.0.16 [flutter flutter_web_plugins video_player_platform_interface]
- vm_service 11.3.0
- watcher 1.1.0 [async path]
- web_socket_channel 2.4.0 [async crypto stream_channel]
- webdriver 3.0.2 [matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.2.0 [logging]
- webview_flutter 3.0.4 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 2.10.4 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.9.5 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 2.9.5 [flutter path webview_flutter_platform_interface]
- win32 4.1.4 [ffi]
- win32_registry 1.1.0 [ffi win32]
- xdg_directories 1.0.0 [meta path process]
- xml 6.3.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
It seems to be an issue with cast to a map when it comes to remote messaging.
@kunalpowar 
Is there a way to know when this crash is triggered ? for example, when users try to enter to the app via notifications ?

**Comment by kunalpowar** [comment]
I've tried reproducing this bug by sending all possible messages that a user can get on our app without any luck.

I did find a old but similar thread [here](https://github.com/firebase/flutterfire/issues/4849). But the solution is not relevant anymore.

**Comment by darshankawar** [comment]
Thanks for the update.



> I did find a old but similar thread [here](https://github.com/firebase/flutterfire/issues/4849). B

Yes, I looked at this issue and probably the cast error may still be occuring. But that issue got closed due to inactivity. I'll keep this issue open and label for team's input to see if there's any feedback from them on the error reported.

/cc @russellwheatley. The same error occurred using latest plugin version, as reported originally https://github.com/firebase/flutterfire/issues/4849

**Comment by kunalpowar** [comment]
@russellwheatley I am not able to reproduce this with any scenario of messages/notifications sent from backend. We use Airship to send notifications to our app. I even simulated these and was not able to reproduce the crash.

**Comment by Lyokone** [comment]
@kunalpowar A lot of updates have been applied to Firebase Messaging, are you still reproducing this issue?

**Comment by kunalpowar** [comment]
@Lyokone I am not seeing any more cashes with the same trace. We are right now at `v14.9.3`. Closing this.
