### ISSUE TITLE
🐛 [firebase_ui_auth] Null check operator used on a null value at EmailVerificationController.user(email_verification.dart:68)

### ISSUE THREAD

**Issue by mfizz1** [firebase/flutterfire#11401]
## Bug report

**Describe the bug**
Getting a null check operator error when user registers for the first time and is then sent to email verification screen, waiting to verify their email. When the error occurs I get a varied response from the UI sometimes a blank screen, pressing back brings them back to login screen.

### Steps to reproduce

1. Register new account using Firebase UI
2. Email verification screen shown

### Expected behavior

Continue waiting for user to verify email

### Sample project
This is what I use for my registration screen in a column widget:

```dart
class LoginScreen extends StatelessWidget {
  const LoginScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Material(
      child: SignInScreen(
        providers: providers,
        actions: [
          ForgotPasswordAction(
            (context, email) {
              Navigator.push(
                context,
                forgotPass(email),
              );
            },
          ),
          AuthStateChangeAction<SignedIn>((context, state) {
            if (state.user!.emailVerified) {
              Navigator.pushReplacementNamed(context, '/admin');
            } else {
              Navigator.push(context, verifyEmail());
            }
          }),
          AuthStateChangeAction<UserCreated>((context, state) {
            Navigator.push(context, verifyEmail());
          })
        ],
      ),
    );
    // );; //signScreen();
  }

    MaterialPageRoute<dynamic> verifyEmail() {
    return MaterialPageRoute(
      builder: (context) => EmailVerificationScreen(
        headerBuilder: headerIcon(Icons.mark_email_unread),
        sideBuilder: sideIcon(Icons.mark_email_unread),
        actions: [
          EmailVerifiedAction(() {
            Navigator.pushReplacementNamed(context, '/login');
          }),
          AuthCancelledAction((context) {
            FirebaseUIAuth.signOut(context: context);
            Navigator.pop(context);
          }),
        ],
      ),
    );
  }

  MaterialPageRoute<dynamic> forgotPass(String? email) {
    return MaterialPageRoute(
      builder: (context) => ForgotPasswordScreen(
        headerBuilder: headerIcon(Icons.lock),
        sideBuilder: sideIcon(Icons.lock),
        email: email,
      ),
    );
  }
}
```

---

## Additional context

Error Details:

```bash
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value
       at EmailVerificationController.user(email_verification.dart:68)
       at EmailVerificationController.reload(email_verification.dart:82)
       at EmailVerificationController.didChangeAppLifecycleState(email_verification.dart:63)
       at WidgetsBinding.handleAppLifecycleStateChanged(binding.dart:713)
       at ServicesBinding._handleLifecycleMessage(binding.dart:261)
       at BasicMessageChannel.setMessageHandler.<fn>(platform_channel.dart:212)
       at _DefaultBinaryMessenger.setMessageHandler.<fn>(binding.dart:479)

ReferenceQueueDaemon:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:232)
       at java.lang.Daemons$Daemon.run(Daemons.java:140)
       at java.lang.Thread.run(Thread.java:1012)

OkHttp ConnectionPool:
       at java.lang.Object.wait(Object.java)
       at com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

pool-7-thread-1:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

Firebase Background Thread #2:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.concurrent.b.b(:12)
       at com.google.firebase.concurrent.b.a()
       at com.google.firebase.concurrent.a.run(:4)
       at java.lang.Thread.run(Thread.java:1012)

awaitEvenIfOnMainThread task continuation executor1:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at g1.x$a$a.a(:2)
       at g1.d.run(:5)
       at java.lang.Thread.run(Thread.java:1012)

queued-work-looper:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:186)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)

main:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:186)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

Firebase Background Thread #3:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.concurrent.b.b(:12)
       at com.google.firebase.concurrent.b.a()
       at com.google.firebase.concurrent.a.run(:4)
       at java.lang.Thread.run(Thread.java:1012)

DefaultDispatcher-worker-3:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:357)
       at kotlinx.coroutines.scheduling.a$c.l(:23)
       at kotlinx.coroutines.scheduling.a$c.r(:48)
       at kotlinx.coroutines.scheduling.a$c.n(:60)
       at kotlinx.coroutines.scheduling.a$c.run()

com.google.firebase.crashlytics.startup1:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at g1.x$a$a.a(:2)
       at g1.d.run(:5)
       at java.lang.Thread.run(Thread.java:1012)

FinalizerWatchdogDaemon:
       at java.lang.Thread.sleep(Thread.java)
       at java.lang.Thread.sleep(Thread.java:450)
       at java.lang.Thread.sleep(Thread.java:355)
       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepForNanos(Daemons.java:438)
       at java.lang.Daemons$FinalizerWatchdogDaemon.waitForProgress(Daemons.java:480)
       at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:369)
       at java.lang.Daemons$Daemon.run(Daemons.java:140)
       at java.lang.Thread.run(Thread.java:1012)

DefaultDispatcher-worker-2:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:357)
       at kotlinx.coroutines.scheduling.a$c.l(:23)
       at kotlinx.coroutines.scheduling.a$c.r(:48)
       at kotlinx.coroutines.scheduling.a$c.n(:60)
       at kotlinx.coroutines.scheduling.a$c.run()

Firebase Background Thread #1:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.concurrent.b.b(:12)
       at com.google.firebase.concurrent.b.a()
       at com.google.firebase.concurrent.a.run(:4)
       at java.lang.Thread.run(Thread.java:1012)

Crashlytics Exception Handler1:
       at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
       at java.lang.Thread.getStackTrace(Thread.java:1841)
       at java.lang.Thread.getAllStackTraces(Thread.java:1909)
       at g1.r.y(:16)
       at g1.r.o(:4)
       at g1.r.j(:45)
       at g1.r.d(:44)
       at g1.h0.r(:19)
       at g1.h0.s(:32)
       at g1.n$b.a(:49)
       at g1.n$b.call()
       at g1.k$c.then(:2)
       at com.google.android.gms.tasks.zze.run(:8)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at g1.x$a$a.a(:2)
       at g1.d.run(:5)
       at java.lang.Thread.run(Thread.java:1012)

FinalizerDaemon:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:203)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:224)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:300)
       at java.lang.Daemons$Daemon.run(Daemons.java:140)
       at java.lang.Thread.run(Thread.java:1012)

TokenRefresher:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:186)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)

DefaultDispatcher-worker-1:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:357)
       at kotlinx.coroutines.scheduling.a$c.l(:23)
       at kotlinx.coroutines.scheduling.a$c.r(:48)
       at kotlinx.coroutines.scheduling.a$c.n(:60)
       at kotlinx.coroutines.scheduling.a$c.run()

Firebase Background Thread #0:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.concurrent.b.b(:12)
       at com.google.firebase.concurrent.b.a()
       at com.google.firebase.concurrent.a.run(:4)
       at java.lang.Thread.run(Thread.java:1012)

Okio Watchdog:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:313)
       at com.android.okhttp.okio.AsyncTimeout.access$000(AsyncTimeout.java:42)
       at com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:288)

Firebase Blocking Thread #1:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
       at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:463)
       at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
       at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:939)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.concurrent.b.b(:12)
       at com.google.firebase.concurrent.b.a()
       at com.google.firebase.concurrent.a.run(:4)
       at java.lang.Thread.run(Thread.java:1012)

```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@mfizz1 
Thanks for the report. Can you provide your flutter doctor -v and plugin version you are using that is throwing the reported error ?
There was a similar issue fixed earlier [this](https://github.com/firebase/flutterfire/pull/10225) year that you can check and see if it helps in your case or not.

**Comment by mfizz1** [comment]
Updated the flutter doctor and plugin is as follows:

```bash
firebase_ui_auth:
    dependency: "direct main"
    description:
      name: firebase_ui_auth
      sha256: e439571fcad7ed48450eed8d64c70b93765526b876327055469806a51101eff0
      url: "https://pub.dev"
    source: hosted
    version: "1.6.2"
```

**Comment by mfizz1** [comment]
I have looked at the `UserCreated` state, but I am not sure how it would help in this case. The user is waiting for the email to be verified to move on the the "profile" page. This example is straight from the the docs. I saw last month, someone else raised this as an issue as well but it was closed without a fix #11052

**Comment by darshankawar** [comment]
Thanks for the update. I tried with the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_ui_auth/example) running on latest master version, registered new user, received email, verified but when clicked continue, I got dynamic link error, but while waiting to confirm, I didn't the reported error:

<img width="283" alt="Screenshot 2023-08-02 at 3 43 19 PM" src="https://github.com/firebase/flutterfire/assets/67046386/4a6546b5-c2b7-4bbb-b189-96c0862da313">
<img width="423" alt="Screenshot 2023-08-02 at 3 44 17 PM" src="https://github.com/firebase/flutterfire/assets/67046386/0b7a7f87-8f7a-4a8e-bfb0-a3730e1647d2">


Are there any exact steps or if you could provide a short video when the error triggers would be good to make this issue actionable.

**Comment by mfizz1** [comment]
I suppose the question is, what is the expected behaviour here? Once the user verifies email, should it automatically proceed to the next screen? Or does the user have to sign in again or change resume state? 

When you verified email, what happened on screen?

I will try producing the error locally.

**Comment by danagbemava-nc** [comment]
Hi @mfizz1, have you been able to reproduce this locally? I used the plugin example app to do a registration and I was able to register without any issues. 

As to what is supposed to happen when you verify your email, it depends on how you've setup your Auth States but with the plugin example app, you will be redirected to the profile page (and based on what I see in your code sample, the same thing should happen)

**Comment by mfizz1** [comment]
This is where it seems to be an issue. Whilst I am able to replicate the issue, in terms of the behaviour, it's not flagging up any issues.

The only way I am able to proceed to the screen after email verification, is to cycle to another app and back into this one. Which triggers something to go to profile page. Otherwise I'm waiting with the circular progress indicator.

I will try again today.

**Comment by mfizz1** [comment]
I have managed to produce locally! And noticed a lot more things. It is something to do with resuming from a paused state / cycling back the app. One of the other errors produced was:

```bash
════════ Exception caught by foundation library ════════════════════════════════
The following assertion was thrown while dispatching notifications for EmailVerificationController:
setState() called after dispose(): __EmailVerificationScreenContentState#a7daf(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack
#0      State.setState.<anonymous closure>
#1      State.setState
#2      __EmailVerificationScreenContentState._sendEmailVerification.<anonymous closure>
#3      ChangeNotifier.notifyListeners
#4      ValueNotifier.value=
#5      EmailVerificationController.reload
<asynchronous suspension>
The EmailVerificationController sending notification was: EmailVerificationController#72e1b(EmailVerificationState.verified)
════════════════════════════════════════════════════════════════════════════════
```

**Comment by darshankawar** [comment]
@mfizz1 
I tried again, this time, using the email client and app from same device and switched back and forth while email was being verified, but didn't get the above reported and originally reported error. Upon email verification, the user is taken to profile page as below:

<img width="181" alt="Screenshot 2023-08-07 at 4 58 13 PM" src="https://github.com/firebase/flutterfire/assets/67046386/e663ce99-663c-47a2-849e-03e04e841dee">

Based on the error report, I am going ahead and labeling for team's attention and input.

/cc @lesnitsky
