### ISSUE TITLE
🐛 [cloud_firestore] FirebaseFirestore trying to reach [DEFAULT] app when other app name used

### ISSUE THREAD

**Issue by OlegNovosad** [firebase/flutterfire#11437]
## Bug report

**Describe the bug**
I'm working on Flutter module, that will use some of Firebase tools underneath. Because this module might be used in other projects, I want to have a Firebase app with non `[DEFAULT]` name. All good so far, however `FirebaseFirestore` is still trying to reach out to `[DEFAULT]` app.

```dart
final getIt = GetIt.instance;

void main() {
   WidgetsFlutterBinding.ensureInitialized();
   
   // ...

   await Firebase.initializeApp(name: "module", options: 
   DefaultFirebaseOptions.currentPlatform);

   // ...

   await DI.setupDependencies("module");
}
```

Inside `DI.setupDependencies(...)`

```dart
final app = Firebase.app(firebaseAppName);

getIt.registerSingleton(FirebaseStorage.instanceFor(app: app));
getIt.registerSingleton(FirebaseAuth.instanceFor(app: app));
getIt.registerSingleton(FirebaseFirestore.instanceFor(app: app));
// NOTE: Not supported with custom firebase app name
// getIt.registerSingleton(FirebaseAnalytics.instanceFor(app: app));
// getIt.registerSingleton(FirebaseCrashlytics.instance);

final fs = FirebaseFirestore.instanceFor(app: app);
fs.collection("users").id; // Exception here
getIt<FirebaseFirestore>().collection("users").id; // This also does not work and throws the same exception
```

Exception stacktrace:

```
E/flutter ( 8030): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
E/flutter ( 8030): #0      MethodChannelFirebase.app
method_channel_firebase.dart:193
E/flutter ( 8030): #1      Firebase.app
firebase.dart:56
E/flutter ( 8030): #2      FirebaseFirestorePlatform.instance
platform_interface_firestore.dart:41
E/flutter ( 8030): #3      new FirebaseFirestorePlatform.instanceFor
platform_interface_firestore.dart:33
E/flutter ( 8030): #4      FirebaseFirestore._delegate
firestore.dart:50
E/flutter ( 8030): #5      FirebaseFirestore.collection
firestore.dart:71
E/flutter ( 8030): #6      DI.setupDependencies
di.dart:34
E/flutter ( 8030): #7      main
```

It fails here:

```dart
/// Returns a [FirebaseAppPlatform] by [name].
///
/// Returns the default Firebase app if no [name] is provided and throws a
/// [FirebaseException] if no app with the [name] has been created.
@override
FirebaseAppPlatform app([String name = defaultFirebaseAppName]) {
  if (appInstances.containsKey(name)) {
    return appInstances[name]!;
  }

  throw noAppExists(name);
}
```

The same with `FirebaseStorage` works good, e.g.:

```dart
await Firebase.initializeApp(name: "module", options: DefaultFirebaseOptions.currentPlatform);

final fs = FirebaseStorage.instanceFor(app: Firebase.app('module'));
logger.info((await fs.ref('test.png').getDownloadURL()));
```

Returns url.

### Steps to reproduce

1. Create firebase app
2. Initialize it with name, e.g. `await Firebase.initializeApp(name: "module", options: 
   DefaultFirebaseOptions.currentPlatform);`
3. Call `FirebaseFirestore.instanceFor("module")` any collection name and execute any call on that.
4. See error or incorrect behavior

NOTE: 
`FirebaseFirestore.instanceFor(app: app).app.name` returns proper name.

### Expected behavior

Firebase Firestore should work with custom app name.

### Sample project

https://github.com/OlegNovosad/firebase-issue

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.3 22E252 darwin-arm64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.0)
[✓] Connected device (4 available)
    ! Error: (null) needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the
      connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)
    ! Error: Oleg Novosad’s iPhone is busy: Loading metadata for the watch via Oleg Novosad’s iPhone. Xcode will continue when Oleg Novosad’s iPhone
      is finished. (code -10)
[✓] Network resources
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- cached_network_image 3.2.3 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- cloud_firestore 4.8.4 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- community_material_icon 5.9.55 [flutter]
- connectivity_plus 4.0.2 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- crypto 3.0.3 [typed_data]
- equatable 2.0.5 [collection meta]
- firebase_analytics 10.4.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.7.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.15.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.3.4 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_storage 11.2.5 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_svg 2.0.7 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- get_it 7.6.0 [async collection]
- go_router 10.0.0 [collection flutter flutter_web_plugins logging meta]
- google_fonts 5.1.0 [flutter http path_provider crypto]
- http 1.1.0 [async http_parser meta]
- internet_connection_checker 1.0.0+1
- intl 0.18.1 [clock meta path]
- json_annotation 4.8.1 [meta]
- logging 1.2.0
- package_info_plus 4.1.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- provider 6.0.5 [collection flutter nested]
- scroll_to_index 3.0.1 [flutter]
- timezone 0.9.2 [path]
- uuid 3.0.7 [crypto]

dev dependencies:
- build_runner 2.4.6 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- firebase_auth_mocks 0.12.0 [flutter firebase_auth firebase_core meta equatable dart_jsonwebtoken uuid firebase_auth_platform_interface mock_exceptions]
- firebase_storage_mocks 0.6.1 [flutter firebase_storage]
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 2.0.2 [lints]
- flutter_native_splash 2.3.1 [args flutter flutter_web_plugins js html image meta path universal_io xml yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service async boolean_selector characters clock collection fake_async file js matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math webdriver]
- json_serializable 6.7.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- mockito 5.4.2 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @OlegNovosad 
Can you provide us minimal reproducible code sample without third party package implementation that still shows the reported error ?
Also, is the project configured using google-services json file or using flutterfire configure cli tool ? If you could reconfigure using `flutterfire configure` and run your scenario again, does the error still persists ?

**Comment by OlegNovosad** [comment]
Reconfiguring with `flutterfire configure` worked. Thanks! Sorry for taking your time :)

**Comment by OlegNovosad** [comment]
@darshankawar please see repo here: https://github.com/OlegNovosad/firebase-issue

Also I have updated the description.

**Comment by OlegNovosad** [comment]
This is related only to Flutter Module, with Flutter App works fine.

**Comment by darshankawar** [comment]
Thanks for the repo @OlegNovosad 
I cloned it, updated it to sync it with my local firebase setup and tried to run but it gave me below compile error:

```
[!] App requires Multidex support
    Multidex support is required for your android app to build since the number of methods has exceeded 64k. See https://docs.flutter.dev/deployment/android#enabling-multidex-support for more information. You may pass the --no-multidex flag to skip Flutter's multidex support to use a manual solution.

    Your `android/app/src/main/AndroidManifest.xml` does not contain `android:name="${applicationName}"` under the `application` element. This may be due to creating your project with an old version of Flutter. Add the `android:name="${applicationName}"` attribute to your AndroidManifest.xml to enable Flutter's multidex support:

        <manifest xmlns:android="http://schemas.android.com/apk/res/android"
          ...
          <application
            ...
            android:name="${applicationName}"
            ...>

    You may also roll your own multidex support by following the guide at: https://developer.android.com/studio/build/multidex

Exception: Gradle task assembleDebug failed with exit code 1
```

Since it is complaining about multidex support, is your app created using older flutter version ? If so, does creating a new flutter project with latest version and integrating with firebase gives you same error ?

**Comment by OlegNovosad** [comment]
@darshankawar I'm not aware about this issue (not happening locally). If you look at `flutter doctor` output, you'll see that I'm using Flutter 3.10.6:

`[✓] Flutter (Channel stable, 3.10.6, on macOS 13.3 22E252 darwin-arm64, locale en-UA)`

Launch configuration is straightforward:

```json
{
   "name": "firebase_issue",
   "request": "launch",
   "type": "dart"
}
```

**Comment by darshankawar** [comment]
Ok, I fixed the issues I was getting and then was able to run it properly without any issues. I also tried below code snippet from the one you provided and used it in [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore/example) which compiled and ran properly. 

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(name: 'test', options: DefaultFirebaseOptions.currentPlatform, );
  await FirebaseFirestore.instanceFor(app: Firebase.app('test')).collection('firestore-example-app').doc('baby_driver');
  FirebaseFirestore.instance.settings = Settings(persistenceEnabled: true, sslEnabled: true, cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED);

  if (shouldUseFirestoreEmulator) {
    FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
  }


  runApp(FirestoreExampleApp());
}
```

Can you also check the plugin example implementation, although it doesn't make use of `instanceFor` but you can add as above and see if it helps further in your case or not.

**Comment by OlegNovosad** [comment]
As I mentioned before - it works fine for the Flutter Project but not for the Flutter Module. If you'll either run a host app with flutter module or build an aar using `flutter build aar` and inject it in native Android app - the stacktrace above will occur.

**Comment by darshankawar** [comment]
Thanks for the update. I am unable to replicate the reported behavior after building an aar, but based on the report, and initial findings as [mentioned](https://github.com/firebase/flutterfire/issues/11437#issuecomment-1671354549), keeping this issue open for team's attention.

**Comment by OlegNovosad** [comment]
Ok, so I did more testing. Looks like when building aar and injecting it into app - it works fine, however it still has issues when trying to develop Flutter Module and run the host app itself which makes it inconvenient during development of the module.

**Comment by barbl058** [comment]
It's happening to me as well, here my details:

Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.6 22G120 darwin-x64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed
[✓] Connected device (4 available)
[✓] Network resources
```

My app does an initialization by app name:

```dart
_app = Firebase.app(name);
// _app object initializes successfully with the expected name
_firestore = FirebaseFirestore.instanceFor(app: _app);
// _firestore object initializes successfully with the app and app name 
```

After this point any operation that uses the `_firestore` instance trigger the error, ie:
```dart
await _firestore?.enableNetwork();
```

It calls
```dart
Future<void> enableNetwork() {
  return _delegate.enableNetwork();
}
```

and delegate calls
```dart
FirebaseFirestorePlatform get _delegate {
  return _delegatePackingProperty ??= FirebaseFirestorePlatform.instanceFor(
    app: app,
    databaseURL: databaseURL,
  );
}
```

Until this point `app` still has my `_app` configuration and app name. In debug I can see the `instanceFor` method calling `FirebaseFirestorePlatform.instance` before injecting my app configuration by `delegateFor`, but `.instance` throws the error so `delegateFor` is never called.

<img width="860" alt="Screenshot 2023-10-04 at 8 29 35 AM" src="https://github.com/firebase/flutterfire/assets/87673569/a72685b8-5a2b-4deb-a594-2fc9238e569e">

Problem seems to be that `instance` getter creates another `Firebase.app()` instance (ignoring my provided `_app`):

<img width="723" alt="Screenshot 2023-10-04 at 8 44 56 AM" src="https://github.com/firebase/flutterfire/assets/87673569/f1f857d5-4929-4d88-8878-7b13a32e3404">

With no name so it falls into the `DEFAULT` one:

<img width="1045" alt="Screenshot 2023-10-04 at 8 30 35 AM" src="https://github.com/firebase/flutterfire/assets/87673569/53e0b178-6bd5-42f7-a499-2985ffa931b4">

`_delegate.app` calls

<img width="1058" alt="Screenshot 2023-10-04 at 8 52 56 AM" src="https://github.com/firebase/flutterfire/assets/87673569/8d272f60-45c4-4084-b8bb-268eb85229ec">

And since '[DEFAULT]' doesn't exists on my `appInstances`

<img width="544" alt="Screenshot 2023-10-04 at 8 53 08 AM" src="https://github.com/firebase/flutterfire/assets/87673569/757d433f-05c7-4818-a2cd-00af59a150b2">

the `noAppExists` error is thrown.

```
I/flutter (15515): [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
I/flutter (15515): #0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:193:5)
I/flutter (15515): #1      Firebase.app (package:firebase_core/src/firebase.dart:56:41)
I/flutter (15515): #2      FirebaseFirestorePlatform.instance (package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_firestore.dart:41:71)
I/flutter (15515): #3      new FirebaseFirestorePlatform.instanceFor (package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_firestore.dart:33:38)
I/flutter (15515): #4      FirebaseFirestore._delegate (package:cloud_firestore/src/firestore.dart:50:35)
```

I hope any piece of information could give a clue on the issue if there is one.

Thanks!

**Comment by Lyokone** [comment]
Hello @OlegNovosad, do you still experience this issue on the latest version? Thanks
