### ISSUE TITLE
🐛 [firebase_messaging] Android directBootAware messages configuration - dalvik.system.BaseDexClassLoader.findClass java.lang.ClassNotFoundException caused by .java.MyFirebaseMessagingService

### ISSUE THREAD

**Issue by guycalledseven** [firebase/flutterfire#11517]
## Bug report

After app is published with firebase_messaging package versions 14.1.4-14.2.3 and uses directBootAware messages, it starts getting crash report on android devices / crashes on first start:

```
dalvik.system.BaseDexClassLoader.findClass
java.lang.ClassNotFoundException
```

**Describe the bug**

After closely inspecting with debugger in Android Studio the real error comes from the wrong directBootAware service class configuration in `AndroidManifest.xml`:

```
E/AndroidRuntime( 7910): java.lang.RuntimeException: Unable to create service com.bundle.appname.java.MyFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "com.bundle.appname.java.MyFirebaseMessagingService"
```

There is already several auto-closed bug reports AFAIK for the same issue:
- https://github.com/firebase/flutterfire/issues/10604
- https://github.com/firebase/flutterfire/issues/2845

As well an huge amount of issues reported on eg. StackOverflow regarding same subject:
- https://stackoverflow.com/questions/63979561/java-lang-runtimeexception-unable-to-instantiate-service-com-samriddh-partner-j/76971409#76971409
- https://stackoverflow.com/questions/65034483/class-not-found-exception-on-firebase-messaging-flutter/76971343#76971343
- https://stackoverflow.com/questions/72403490/java-lang-runtimeexception-unable-to-create-service-error-when-receiving-a-fire

### Steps to reproduce

In firebase_messaging plugin documentation you state:
> "To use this plugin, please visit the [Cloud Messaging Usage documentation](https://firebase.google.com/docs/cloud-messaging)"

And on several places in firebase documentation, there is a reference to example configuration of `AndroidManifest.xml` in order to receive FCM messages in direct boot mode:

> Developers who want to send FCM messages to apps even before the device is unlocked can enable an Android app to receive messages when the device is in direct boot mode. For instance, you might want users of your app to receive alarm notifications even on a locked device.

Config in question:

```
<service
    android:name=".java.MyFirebaseMessagingService"
    android:exported="false"
    android:directBootAware="true">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>
```

References:
- https://firebase.google.com/docs/cloud-messaging/android/client
- https://firebase.google.com/docs/cloud-messaging/android/receive

### Expected behavior

firebase_messaging plugin works pretty great out of the box on IOS. 

My guess is that the flutter package documentation should be updated regarding specific directBootAware Android configuration, since IOS has no such concept and since both package and firebase documentationsare causing confusion.

I am not native Android developer, and if I want to receive messages while app is not started has a requirement to make native code Android code for a  custom `FlutterFirebaseMessagingService` class - I guess that this should be outlined in firebase_messaging plugin documentation as well - hence it is a very big difference in how eg. IOS and Android work while receiving messages for app which is not started.

I have opened the project in Android Studio and looked for the FlutterFirebaseMessagingService class in imported packages.

The fix that worked for me was using this class name io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingService in android/app/src/main/AndroidManifest.xml:

```
        <service
            android:name="io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>        
```

---

## Additional context

Error thrown is:

```
A Dart VM Service on sdk gphone64 arm64 is available at: http://127.0.0.1:57505/kQpPPSim0Cc=/
The Flutter DevTools debugger and profiler on sdk gphone64 arm64 is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:57505/kQpPPSim0Cc=/
I/FLTFireMsgService( 7910): FlutterFirebaseMessagingBackgroundService started!
W/iorasje.maxiapp( 7910): Accessing hidden method Landroid/os/WorkSource;->add(I)Z (unsupported,test-api, reflection, allowed)
W/iorasje.maxiapp( 7910): Accessing hidden method Landroid/os/WorkSource;->add(ILjava/lang/String;)Z (unsupported,test-api, reflection, allowed)
W/iorasje.maxiapp( 7910): Accessing hidden method Landroid/os/WorkSource;->get(I)I (unsupported, reflection, allowed)
W/iorasje.maxiapp( 7910): Accessing hidden method Landroid/os/WorkSource;->getName(I)Ljava/lang/String; (unsupported, reflection, allowed)
D/AndroidRuntime( 7910): Shutting down VM
E/AndroidRuntime( 7910): FATAL EXCEPTION: main
E/AndroidRuntime( 7910): Process: com.bundle.appname, PID: 7910
E/AndroidRuntime( 7910): java.lang.RuntimeException: Unable to create service com.bundle.appname.java.MyFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "com.bundle.appname.java.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/~~ibHaPZV5aaWwMAnc-AvRtw==/com.bundle.appname-9YVzDWVTlpQhJMDsqf87MA==/base.apk"],nativeLibraryDirectories=[/data/app/~~ibHaPZV5aaWwMAnc-AvRtw==/com.bundle.appname-9YVzDWVTlpQhJMDsqf87MA==/lib/arm64, /data/app/~~ibHaPZV5aaWwMAnc-AvRtw==/com.bundle.appname-9YVzDWVTlpQhJMDsqf87MA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime( 7910): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4664)
E/AndroidRuntime( 7910): 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
E/AndroidRuntime( 7910): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2264)
E/AndroidRuntime( 7910): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 7910): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime( 7910): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime( 7910): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime( 7910): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7910): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime( 7910): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/AndroidRuntime( 7910): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bundle.appname.java.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/~~ibHaPZV5aaWwMAnc-AvRtw==/com.bundle.appname-9YVzDWVTlpQhJMDsqf87MA==/base.apk"],nativeLibraryDirectories=[/data/app/~~ibHaPZV5aaWwMAnc-AvRtw==/com.bundle.appname-9YVzDWVTlpQhJMDsqf87MA==/lib/arm64, /data/app/~~ibHaPZV5aaWwMAnc-AvRtw==/com.bundle.appname-9YVzDWVTlpQhJMDsqf87MA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime( 7910): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime( 7910): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 7910): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 7910): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime( 7910): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
E/AndroidRuntime( 7910): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4626)
E/AndroidRuntime( 7910): 	... 9 more
I/Process ( 7910): Sending signal. PID: 7910 SIG: 9
Lost connection to device.
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.4.1 22F770820d darwin-arm64, locale en-HR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.1.0
Flutter SDK 3.13.1
maxiorasje 1.2.1+6

dependencies:
- cached_network_image 3.2.3 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- carousel_slider 4.2.1 [flutter]
- cupertino_icons 1.0.5
- firebase_analytics 10.4.5 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.15.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.6.7 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.9.2+5 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_html 3.0.0-beta.2 [html csslib collection list_counter flutter]
- flutter_svg 1.1.6 [flutter meta path_drawing vector_math xml]
- http 0.13.6 [async http_parser meta]
- intl 0.17.0 [clock path]
- modal_bottom_sheet 3.0.0-pre [flutter]
- shared_preferences 2.2.0 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- syncfusion_flutter_barcodes 20.4.54 [flutter syncfusion_flutter_core]
- url_launcher 6.1.12 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- webview_cookie_manager 2.0.6 [flutter]
- webview_flutter 3.0.4 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- flutter_lints 2.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

transitive dependencies:
- _flutterfire_internals 1.3.5 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- cached_network_image_platform_interface 2.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.2 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.3.0
- clock 1.1.1
- collection 1.17.2
- crypto 3.0.3 [typed_data]
- csslib 0.17.3 [source_span]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 6.1.4 [meta path]
- firebase_analytics_platform_interface 3.6.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.4+5 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.7.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 4.5.6 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.6 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance_platform_interface 0.1.4+5 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.4+5 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- html 0.15.4 [csslib source_span]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- lints 2.1.1
- list_counter 1.0.2
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- octo_image 1.0.2 [flutter flutter_blurhash]
- path 1.8.3
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.1.0 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.1.0 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.0 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.0 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.0 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.4.0 [meta]
- platform 3.1.1
- plugin_platform_interface 2.1.5 [meta]
- rxdart 0.27.7
- shared_preferences_android 2.2.0 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.3 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.0 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.3.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- sqflite 2.3.0 [flutter sqflite_common path]
- sqflite_common 2.5.0 [synchronized path meta]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- syncfusion_flutter_core 20.4.54 [vector_math flutter]
- synchronized 3.1.0
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- url_launcher_android 6.0.38 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.6 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.18 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.7 [flutter url_launcher_platform_interface]
- uuid 3.0.7 [crypto]
- vector_math 2.1.4
- web 0.1.4-beta
- webview_flutter_android 2.10.4 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.9.5 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 2.9.5 [flutter path webview_flutter_platform_interface]
- win32 5.0.7 [ffi]
- xdg_directories 1.0.2 [meta path]
- xml 6.3.0 [collection meta petitparser]
```

</details>

---

edit: wording

**Comment by darshankawar** [comment]
Thanks for the detailed report @guycalledseven 


> In firebase_messaging plugin documentation you state:
> 
> > "To use this plugin, please visit the [Cloud Messaging Usage documentation](https://firebase.google.com/docs/cloud-messaging)"
> 
> And on several places in firebase documentation, there is a reference to example configuration of `AndroidManifest.xml` in order to receive FCM messages in direct boot mode:
> 
> > Developers who want to send FCM messages to apps even before the device is unlocked can enable an Android app to receive messages when the device is in direct boot mode. For instance, you might want users of your app to receive alarm notifications even on a locked device.
> 
> Config in question:
> 
> ```
> <service
>     android:name=".java.MyFirebaseMessagingService"
>     android:exported="false"
>     android:directBootAware="true">
>     <intent-filter>
>         <action android:name="com.google.firebase.MESSAGING_EVENT" />
>     </intent-filter>
> </service>
> ```
> 
> References:
> 
> * https://firebase.google.com/docs/cloud-messaging/android/client
> * https://firebase.google.com/docs/cloud-messaging/android/receive

All these sections and links are pointing to native Android setup for messaging plugin. But from Flutter + firebase_messaging point of view, we need to refer to https://firebase.google.com/docs/cloud-messaging/flutter/client and just follow the steps mentioned in it to get messaging running.

Also, I looked at firebase_messaging plugin example in which it doesn't make use of the manifest file settings mentioned:

https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/android/app/src/main/AndroidManifest.xml

The native Android manifest file from the plugin example shows below:

https://github.com/firebase/flutterfire/blob/fd5a5f279b331a242ccf1ae1409f8b65022d6407/packages/firebase_messaging/firebase_messaging/android/src/main/AndroidManifest.xml#L13C61-L13C61

Moreover, As [documented in the Firebase doc](https://firebase.google.com/docs/cloud-messaging/android/receive), you need to enable the following in your app before you can receive messages when the screen is locked. The device is in direct boot mode when the screen is locked.

Please check above and see if it helps further in your case or not.
