### ISSUE TITLE
🐛 [FirebaseMessaging] Unable to get the FCM token.

### ISSUE THREAD

**Issue by aarjan** [firebase/flutterfire#11559]
## Bug report

I am unable to integrate Firebase messaging in the iOS app.

### Steps to reproduce
I have tried this numerous times.
```
flutter pub cache clean
flutter clean 
flutter pub get
 rm -rf ~/Library/Developer/Xcode/DerivedData/* Podfile.lock Pods
 pod deintegrate
 pod install --repo-update
```

## Additional context

<details><summary>This is the Xcode Runner output</summary>

```bash

2023-09-07 09:27:48.529641+0545 Runner[5929:1418866]  - <AppMeasurement>[I-ACS036001] Analytics screen reporting is disabled. UIViewController transitions will not be logged.
2023-09-07 09:27:48.699319+0545 Runner[5929:1418536] Metal API Validation Enabled
2023-09-07 09:27:48.802897+0545 Runner[5929:1418536] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
2023-09-07 09:27:48.887242+0545 Runner[5929:1418866] 10.12.0 - [FirebaseCore][I-COR000005] No app has been configured yet.
2023-09-07 09:27:48.888022+0545 Runner[5929:1418866] 10.12.0 - [FirebaseCore][I-COR000001] Configuring the default app.
2023-09-07 09:27:48.891380+0545 Runner[5929:1418866] 10.12.0 - [FirebaseCore][I-COR000033] Data Collection flag is not set.
2023-09-07 09:27:48.955472+0545 Runner[5929:1418536] [Firebase/Crashlytics] Version 10.12.0
2023-09-07 09:27:48.964330+0545 Runner[5929:1418866] 10.12.0 - [FirebaseInstallations][I-FIS002000] -[FIRInstallationsIDController createGetInstallationItemPromise], appName: __FIRAPP_DEFAULT
2023-09-07 09:27:48.965078+0545 Runner[5929:1418866] 10.12.0 - [FirebaseMessaging][I-FCM043000] Info is not found in Keychain. OSStatus: -25300. Keychain query: {
    acct = "com.neuroflip.tirimiri";
    class = genp;
    gena = "com.google.iid";
    "m_Limit" = "m_LimitAll";
    nleg = 1;
    "r_Attributes" = 1;
    "r_Data" = 1;
    svce = "com.google.iid.checkin";
}
2023-09-07 09:27:48.965142+0545 Runner[5929:1418866] 10.12.0 - [FirebaseMessaging][I-FCM033009] App reset detected but no valid checkin auth preferences found. Will not delete server token registrations.
2023-09-07 09:27:48.965666+0545 Runner[5929:1418866] 10.12.0 - [FirebaseMessaging][I-FCM002000] FIRMessaging library version 10.12.0
2023-09-07 09:27:48.965714+0545 Runner[5929:1418866] 10.12.0 - [GULReachability][I-REA902003] Monitoring the network status
2023-09-07 09:27:48.966292+0545 Runner[5929:1418866] 10.12.0 - [FirebaseMessaging][I-FCM043000] Info is not found in Keychain. OSStatus: -25300. Keychain query: {
    acct = "com.neuroflip.tirimiri";
    class = genp;
    gena = "com.google.iid-tokens";
    "m_Limit" = "m_LimitAll";
    nleg = 1;
    "r_Attributes" = 1;
    "r_Data" = 1;
    svce = "509403943773:*";
}
2023-09-07 09:27:49.144220+0545 Runner[5929:1418867] 10.12.0 - [FirebaseMessaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
2023-09-07 09:27:49.144466+0545 Runner[5929:1418867] 10.12.0 - [GoogleUtilities/AppDelegateSwizzler][I-SWZ001008] Successfully created App Delegate Proxy automatically. To disable the proxy, set the flag GoogleUtilitiesAppDelegateProxyEnabled to NO (Boolean) in the Info.plist
2023-09-07 09:27:49.144486+0545 Runner[5929:1418867] 10.12.0 - [FirebaseSessions][I-SES000000] Version 10.12.0. Expecting subscriptions from: [Crashlytics]
2023-09-07 09:27:49.144501+0545 Runner[5929:1418867] 10.12.0 - [FirebaseCrashlytics][I-CLS000000] [Crashlytics] Running on iPhone9,2, 14.2.0 (18B92)
2023-09-07 09:27:49.218521+0545 Runner[5929:1418897] 10.12.0 - [FirebaseCrashlytics][I-CLS000000] Registering Sessions SDK subscription for session data
2023-09-07 09:27:49.219306+0545 Runner[5929:1418897] 10.12.0 - [FirebaseSessions][I-SES000000] Registering Sessions SDK subscriber with name: Crashlytics, data collection enabled: false
2023-09-07 09:27:49.219374+0545 Runner[5929:1418897] 10.12.0 - [FirebaseCrashlytics][I-CLS000000] Session ID changed: b1463730f990415cab966bce6822126c
2023-09-07 09:27:49.251198+0545 Runner[5929:1418896] flutter: The Dart VM service is listening on http://127.0.0.1:55406/rn0Rs85fdKA=/
2023-09-07 09:27:49.259603+0545 Runner[5929:1418897] 10.12.0 - [FirebaseCrashlytics][I-CLS000000] [Crashlytics:Settings] Settings TTL expired
2023-09-07 09:27:49.259904+0545 Runner[5929:1418897] 10.12.0 - [FirebaseCrashlytics][I-CLS000000] [Crashlytics:Settings] Settings expired because build instance changed
2023-09-07 09:27:49.259949+0545 Runner[5929:1418897] 10.12.0 - [FirebaseAnalytics][I-ACS024000] Debug mode is on
2023-09-07 09:27:49.260161+0545 Runner[5929:1418897] 10.12.0 - [FirebaseAnalytics][I-ACS025028] AdMob and Firebase are in use in this app, but are not linked. For analytics data consistency and integrity, it is highly recommended that you link your AdMob app to the corresponding Firebase app and re-download the GoogleServices-Info.plist file. See https://support.google.com/admob/answer/6383165 for more information.
2023-09-07 09:27:49.260947+0545 Runner[5929:1418897] 10.12.0 - [FirebaseCrashlytics][I-CLS000000] Automatic data collection is disabled. Deleting 3 unsent reports over the limit of 4 to prevent disk space from filling up. To take action on these reports, call send/deleteUnsentReports. To turn on automatic data collection, call setCrashlyticsCollectionEnabled with true
2023-09-07 09:27:49.261013+0545 Runner[5929:1418897] 10.12.0 - [FirebaseCrashlytics][I-CLS000000] Root: /var/mobile/Containers/Data/Application/BE050426-2FE6-4963-888C-BB34B3EC4430/Library/Caches/com.crashlytics.data/com.neuroflip.tirimiri
2023-09-07 09:27:49.261071+0545 Runner[5929:1418897] 10.12.0 - [FirebaseCrashlytics][I-CLS000000] [Crashlytics:Crash:Reports:Event] Registered Firebase Analytics event listener to receive breadcrumb logs
2023-09-07 09:27:49.262227+0545 Runner[5929:1418897] 10.12.0 - [FirebaseCrashlytics][I-CLS000000] Automatic data collection is disabled.
2023-09-07 09:27:49.262313+0545 Runner[5929:1418897] 10.12.0 - [FirebaseCrashlytics][I-CLS000000] [Crashlytics:Crash] 4 unsent reports are available. Waiting for send/deleteUnsentReports to be called.
2023-09-07 09:27:49.262465+0545 Runner[5929:1418897] 10.12.0 - [GULReachability][I-REA902003] Monitoring the network status
2023-09-07 09:27:49.262570+0545 Runner[5929:1418897] 10.12.0 - [GULReachability][I-REA902003] Monitoring the network status
2023-09-07 09:27:49.262637+0545 Runner[5929:1418897] 10.12.0 - [FirebaseAnalytics][I-ACS023007] Analytics v.10.12.0 started
2023-09-07 09:27:49.263016+0545 Runner[5929:1418897] 10.12.0 - [FirebaseAnalytics][I-ACS023008] To disable debug logging set the following application argument: -noFIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2023-09-07 09:27:49.264265+0545 Runner[5929:1418897] 10.12.0 - [FirebaseAnalytics][I-ACS023009] Debug logging enabled
2023-09-07 09:27:49.264314+0545 Runner[5929:1418897] 10.12.0 - [FirebaseAnalytics][I-ACS023207] To enable verbose logging set the following application argument: -FIRAnalyticsVerboseLoggingEnabled (see http://goo.gl/RfcP7r)
2023-09-07 09:27:49.493881+0545 Runner[5929:1418872] 10.12.0 - [GULReachability][I-REA902004] Network status has changed. Code:2, status:Connected
2023-09-07 09:27:49.493951+0545 Runner[5929:1418872] 10.12.0 - [GULReachability][I-REA902004] Network status has changed. Code:2, status:Connected
2023-09-07 09:27:49.493999+0545 Runner[5929:1418872] 10.12.0 - [GULReachability][I-REA902004] Network status has changed. Code:2, status:Connected
2023-09-07 09:27:49.494447+0545 Runner[5929:1418872] 10.12.0 - [FirebaseInstallations][I-FIS002001] -[FIRInstallationsIDController installationWithValidAuthTokenForcingRefresh:0], appName: __FIRAPP_DEFAULT
2023-09-07 09:27:49.495004+0545 Runner[5929:1418872] 10.12.0 - [FirebaseAnalytics][I-ACS025026] Deferring to Firebase for event data collection
2023-09-07 09:27:49.504283+0545 Runner[5929:1418869] 10.12.0 - [FirebaseSessions][I-SES000000] Data Collection is disabled for all subscribers. Skipping this Session Event
2023-09-07 09:27:49.506757+0545 Runner[5929:1418897] 10.12.0 - [FirebaseAnalytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2023-09-07 09:27:49.507151+0545 Runner[5929:1418897] 10.12.0 - [FirebaseAnalytics][I-ACS029014] Successfully parsed a configuration. Version: 1693620627049953
2023-09-07 09:27:49.507463+0545 Runner[5929:1418897] 10.12.0 - [FirebaseAnalytics][I-ACS023016] Analytics is ready to receive events
2023-09-07 09:27:49.597104+0545 Runner[5929:1418866] 10.12.0 - [FirebaseAnalytics][I-ACS002002] APMExperimentAlarm scheduled to fire in approx. (s): 4726.207305908203
2023-09-07 09:27:49.642430+0545 Runner[5929:1418866] 10.12.0 - [FirebaseAnalytics][I-ACS023087] User property set. Name, value: ga_session_id (_sid), 1694058168
2023-09-07 09:27:49.824677+0545 Runner[5929:1418872] 10.12.0 - [FirebaseRemoteConfig][I-RCN000062] Loading database at path /var/mobile/Containers/Data/Application/BE050426-2FE6-4963-888C-BB34B3EC4430/Library/Application Support/Google/RemoteConfig/RemoteConfig.sqlite3
2023-09-07 09:27:49.994911+0545 Runner[5929:1418872] 10.12.0 - [FirebaseRemoteConfig][I-RCN000066] Successfully read configSettings. Minimum Fetch Interval:43200.000000, Fetch timeout: 60.000000
2023-09-07 09:27:49.995270+0545 Runner[5929:1418872] 10.12.0 - [FirebaseRemoteConfig][I-RCN000066] Successfully read configSettings. Minimum Fetch Interval:43200.000000, Fetch timeout: 60.000000
2023-09-07 09:27:49.997573+0545 Runner[5929:1418536] WF: === Starting WebFilter logging for process Runner
2023-09-07 09:27:49.997619+0545 Runner[5929:1418536] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2023-09-07 09:27:49.997656+0545 Runner[5929:1418536] WF: _WebFilterIsActive returning: NO
```

</details>

---

I get this when i call `FirebaseMessaging.instancegetToken()`
```console
2023-09-07 09:27:53.710104+0545 Runner[5929:1418877] flutter: [firebase_messaging/apns-token-not-set] APNS token has not been set yet. Please ensure the APNS token is available by calling `getAPNSToken()`.
2023-09-07 09:27:53.710198+0545 Runner[5929:1418877] flutter: 
#0      MethodChannelFirebaseMessaging._APNSTokenCheck (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:138:9)
<asynchronous suspension>
#1      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:244:5)
<asynchronous suspension>

```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.13.2, on macOS 12.6.8 21G725 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+2 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.6.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.4+5 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.7.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.6 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.6 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config_platform_interface 1.4.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.4.5 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- fixnum 1.1.0
- flutter_appauth_platform_interface 6.0.0 [flutter plugin_platform_interface]
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.16 [flutter]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- frontend_server_client 3.2.0 [async path]
- functions_client 1.3.2 [http yet_another_json_isolate]
- geolocator_android 4.2.2 [flutter geolocator_platform_interface uuid]
- geolocator_apple 2.2.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.7 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.6 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.2.0 [flutter geolocator_platform_interface]
- get 4.6.5 [flutter]
- glob 2.1.2 [async collection file path string_scanner]
- gotrue 1.12.0 [collection crypto http jwt_decode universal_io rxdart meta]
- graphs 2.3.1 [collection]
- hive 2.2.3 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- html 0.15.4 [csslib source_span]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_cropper_for_web 3.0.0 [flutter flutter_web_plugins image_cropper_platform_interface js]
- image_cropper_platform_interface 5.0.0 [flutter plugin_platform_interface http]
- image_picker_android 0.8.7+5 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.1 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.8+2 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.1 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- io 1.0.4 [meta path string_scanner]
- isar 3.1.0+1 [ffi js meta]
- isar_flutter_libs 3.1.0+1 [flutter isar]
- js 0.6.7 [meta]
- json_annotation 4.8.1 [meta]
- jwt_decode 0.3.1
- logging 1.2.0
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- mime 1.0.4
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 1.0.2 [flutter flutter_blurhash]
- os_detect 2.0.1
- package_config 2.1.0 [path]
- package_info_plus 4.1.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.1.1 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.0 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.1 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.4.0 [meta]
- platform 3.1.2
- plugin_platform_interface 2.1.6 [meta]
- pointycastle 3.7.3 [collection convert js]
- pool 1.5.1 [async stack_trace]
- postgrest 1.5.0 [http yet_another_json_isolate]
- process 4.2.4 [file path platform]
- provider 6.0.5 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- pub_updater 0.3.1 [http json_annotation process pub_semver]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- realtime_client 1.2.1 [collection meta web_socket_channel]
- share_plus_platform_interface 3.3.0 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences 2.2.1 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.1 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.3.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_gen 1.4.0 [analyzer async build dart_style glob path source_span yaml]
- source_span 1.10.0 [collection path term_glyph]
- sqflite 2.3.0 [flutter sqflite_common path]
- sqflite_common 2.5.0 [synchronized path meta]
- stack_trace 1.11.0 [path]
- storage_client 1.5.2 [http http_parser mime universal_io retry]
- stream_channel 2.1.1 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- supabase 1.11.2 [functions_client gotrue http postgrest realtime_client storage_client rxdart yet_another_json_isolate]
- synchronized 3.1.0
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.9.2 [path]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_android 6.1.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.6 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.7 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.20 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.8 [flutter url_launcher_platform_interface]
- uuid 3.0.7 [crypto]
- vector_graphics 1.1.7 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.7
- vector_graphics_compiler 1.1.7 [args meta path_parsing xml vector_graphics_codec]
- vector_math 2.1.4
- version 3.0.2
- visibility_detector 0.3.3 [flutter]
- watcher 1.1.0 [async path]
- web 0.1.4-beta
- web_socket_channel 2.4.0 [async crypto stream_channel]
- webview_flutter 4.2.4 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 3.9.5 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.5.1 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.7.4 [flutter path webview_flutter_platform_interface]
- win32 5.0.7 [ffi]
- win32_registry 1.1.1 [ffi win32]
- xdg_directories 1.0.3 [meta path]
- xml 6.3.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
- yet_another_json_isolate 1.1.1 [async]
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @aarjan, what happens when you call `getAPNSToken()`?

**Comment by aarjan** [comment]
> Hi @aarjan, what happens when you call getAPNSToken()?

@danagbemava-nc I get `null` result.
I have tried adding  APNs authentication Key and APNs Certificates, but it showed the same result with either of them.

**Comment by danagbemava-nc** [comment]
Hi @aarjan, can you try reaching out to firebase support? It seems like there might be an issue with the setup of your project.  Since APNs is required and when you try to retrieve it it returns null.

**Comment by aarjan** [comment]
@danagbemava-nc, is there anything to do with this console response,

```console
2023-09-07 09:27:48.887242+0545 Runner[5929:1418866] 10.12.0 - [FirebaseCore][I-COR000005] No app has been configured yet.
2023-09-07 09:27:48.888022+0545 Runner[5929:1418866] 10.12.0 - [FirebaseCore][I-COR000001] Configuring the default app.
2023-09-07 09:27:48.891380+0545 Runner[5929:1418866] 10.12.0 - [FirebaseCore][I-COR000033] Data Collection flag is not set.
2023-09-07 09:27:48.955472+0545 Runner[5929:1418536] [Firebase/Crashlytics] Version 10.12.0
2023-09-07 09:27:48.964330+0545 Runner[5929:1418866] 10.12.0 - [FirebaseInstallations][I-FIS002000] -[FIRInstallationsIDController createGetInstallationItemPromise], appName: __FIRAPP_DEFAULT
2023-09-07 09:27:48.965078+0545 Runner[5929:1418866] 10.12.0 - [FirebaseMessaging][I-FCM043000] Info is not found in Keychain. OSStatus: -25300. Keychain query: {
    acct = "com.neuroflip.tirimiri";
    class = genp;
    gena = "com.google.iid";
    "m_Limit" = "m_LimitAll";
    nleg = 1;
    "r_Attributes" = 1;
    "r_Data" = 1;
    svce = "com.google.iid.checkin";
}
```

**Comment by danagbemava-nc** [comment]
I don't think they're related to your issue. 

Have you by any chance disabled sizzling?

**Comment by aarjan** [comment]
> I don't think they're related to your issue.
> 
> Have you by any chance disabled swizzling?

Yes, i tried doing this too. 
I have added, ```FirebaseAppDelegateProxyEnabled : NO``` to Info.plist, but still i am unable to retrieve APN token.

I think this is occurring to many users, like in this thread https://github.com/firebase/flutterfire/issues/11548

**Comment by hazzo** [comment]
I'm facing this issue. It's annoying, because works correctly on my device on debug but once I uploaded to TestFlight y get this error (I captured with Sentry). This was working fine, I think it might be an Apple thing regarding iOS17.
