### ISSUE TITLE
🐛 [cloud_firestore][android] Failed to execute query using "Filter.Or" or "Filter.And" with Firestore Document Reference value.

### ISSUE THREAD

**Issue by nosborleal** [firebase/flutterfire#11557]
## Bug report

**Describe the bug**
Failed to execute query using "Filter.Or" or "Filter.And" with Firestore Document Reference value in android.

### Steps to reproduce

1. Perform a query using Filter.Or or Filter.And operator with document reference value in android.

### Expected behavior

Using libraries in node or java, the query using the same filter runs without a problem.

### Sample project

```
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:error_firestore/firebase_options.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firestore',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Home'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _loading = false;
  String _error = '';

  Future<void> _search() async {
    setState(() {
      _loading = true;
      _error = '';
    });
    try {
      final userRef = FirebaseFirestore.instance.collection('user').doc('doc1');
      final query = await FirebaseFirestore.instance
          .collection('devices')
          .where(Filter.and(
            Filter('active', isEqualTo: true),
            Filter.or(
              Filter('user_ref', isEqualTo: userRef),
              Filter('ignore_user', isEqualTo: true),
            ),
          ))
          .get();

      for (final device in query.docs) {
        if (kDebugMode) {
          print(device.id);
        }
      }
    } catch (e) {
      setState(() {
        _loading = false;
        _error = '$e';
      });
      rethrow;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Visibility(
              visible: _error.isNotEmpty,
              child: Text(
                'Error: $_error',
              ),
            ),
            Visibility(
              visible: _loading,
              child: const Center(
                child: CupertinoActivityIndicator(),
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _search,
        tooltip: 'Tap',
        child: const Icon(Icons.bug_report_outlined),
      ),
    );
  }
}

```

---

## Additional context

```
The following ArgumentError was thrown while activating platform stream on channel plugins.flutter.io/firebase_firestore/query/0f98711f-2931-47a5-81e4-a1f91725c484:
Invalid argument: Instance of '_JsonDocumentReference'

When the exception was thrown, this was the stack: 
#0      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:465:7)
#1      FirestoreMessageCodec.writeValue (package:cloud_firestore_platform_interface/src/method_channel/utils/firestore_message_codec.dart:122:13)
#2      StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:462:9)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#4      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:460:13)
#5      FirestoreMessageCodec.writeValue (package:cloud_firestore_platform_interface/src/method_channel/utils/firestore_message_codec.dart:122:13)
#6      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:455:9)
#7      FirestoreMessageCodec.writeValue (package:cloud_firestore_platform_interface/src/method_channel/utils/firestore_message_codec.dart:122:13)
#8      StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:462:9)
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#10     StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:460:13)
#11     FirestoreMessageCodec.writeValue (package:cloud_firestore_platform_interface/src/method_channel/utils/firestore_message_codec.dart:122:13)
#12     StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:462:9)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#14     MapView.forEach (dart:collection/maps.dart:346:10)
#15     StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:460:13)
#16     FirestoreMessageCodec.writeValue (package:cloud_firestore_platform_interface/src/method_channel/utils/firestore_message_codec.dart:122:13)
#17     StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:462:9)
#18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#19     StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:460:13)
#20     FirestoreMessageCodec.writeValue (package:cloud_firestore_platform_interface/src/method_channel/utils/firestore_message_codec.dart:122:13)
#21     FirestoreMessageCodec.writeValue (package:cloud_firestore_platform_interface/src/method_channel/utils/firestore_message_codec.dart:104:7)
#22     StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:462:9)
#23     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#24     StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:460:13)
#25     FirestoreMessageCodec.writeValue (package:cloud_firestore_platform_interface/src/method_channel/utils/firestore_message_codec.dart:122:13)
#26     StandardMethodCodec.encodeMethodCall (package:flutter/src/services/message_codecs.dart:603:18)
#27     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:299:34)
#28     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:483:12)
#29     EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:652:29)
#37     MethodChannelQuery.snapshots.<anonymous closure> (package:cloud_firestore_platform_interface/src/method_channel/method_channel_query.dart:164:11)
<asynchronous suspension>
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.13.2, on Ubuntu 23.04 6.2.0-31-generic, locale
    pt_BR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2)
[✓] VS Code (version unknown)
    ✗ Unable to determine VS Code version.
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.1.0
Flutter SDK 3.13.2
error_firestore 1.0.0+1

dependencies:
- cloud_firestore 4.9.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.6
- firebase_core 2.15.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

transitive dependencies:
- _flutterfire_internals 1.3.5 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 5.16.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.7.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.17.2
- fake_async 1.3.1 [clock collection]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.7.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- js 0.6.7 [meta]
- lints 2.1.1
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- path 1.8.3
- plugin_platform_interface 2.1.6 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- web 0.1.4-beta
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @nosborleal, thanks for reporting this. 

Please provide a complete minimal reproducible code sample in a repo that can clone so that we can investigate this issue. 

Thank you

**Comment by nosborleal** [comment]
I created an app to exemplify the problem.
Link: https://github.com/nosborleal/error_firestore_filter
Thank you very much in advance

**Comment by danagbemava-nc** [comment]
Thanks for the repro. 

Reproducible using the code sample shared above.
