### ISSUE TITLE
firebaseAuth. signInWithCredential(credential) return error 

### ISSUE THREAD

**Issue by armanhadifatah** [firebase/flutterfire#11568]
## Bug report

Using firebase auth for google sign in but when I call _firebaseAuth.signInWithCredential(credential) , I get this weird error 

`_TypeError (type 'List<Object?>' is not a subtype of type 'int?' in type cast)`

this is my code 

```
  Future<UserCredential> signInWithGoogle() async {
    final GoogleSignInAccount? googleUser = await GoogleSignIn().signIn();
    final GoogleSignInAuthentication? googleAuth =
        await googleUser?.authentication;
    final credential = GoogleAuthProvider.credential(
      accessToken: googleAuth?.accessToken,
      idToken: googleAuth?.idToken,
    );
    return await _firebaseAuth.signInWithCredential(credential);
  }
```
This was working before but it has been a day or two it doesn't work

**Comment by darshankawar** [comment]
@armanhadifatah 
The plugin example has below implementation. Please check the same in your case and see if it helps in your case or not:

```
Future<void> _signInWithGoogle() async {
    // Trigger the authentication flow
    final googleUser = await GoogleSignIn().signIn();

    // Obtain the auth details from the request
    final googleAuth = await googleUser?.authentication;

    if (googleAuth != null) {
      // Create a new credential
      final credential = GoogleAuthProvider.credential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );

      // Once signed in, return the UserCredential
      await auth.signInWithCredential(credential);
    }
  }
```

**Comment by armanhadifatah** [comment]
Your code is the same as mine , Like i said it was working and I didn't touch any thing , but now I get that error , if the error is with configuration or any thing else it should give me the error not 
`_TypeError (type 'List<Object?>' is not a subtype of type 'int?' in type cast)`

even if the error from myside this shouldn't be the error message

**Comment by sbenmeddour** [comment]
Same issue with email+password authentication.

```
      type 'List<Object?>' is not a subtype of type 'int?' in type cast
      #0      PigeonTotpSecret.decode (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:712:38)
      #1      _FirebaseAuthHostApiCodec.readValueOfType (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:812:33)
      #2      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:478:12)
      #3      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:523:23)
      #4      _FirebaseAuthHostApiCodec.readValueOfType (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:824:22)
      #5      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:478:12)
      #6      StandardMessageCodec.decodeMessage (package:flutter/src/services/message_codecs.dart:342:28)
      #7      BasicMessageChannel.send (package:flutter/src/services/platform_channel.dart:195:18)
      <asynchronous suspension>
      #8      FirebaseAuthHostApi.signInWithEmailAndPassword (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:1118:38)
      <asynchronous suspension>
      #9      MethodChannelFirebaseAuth.signInWithEmailAndPassword (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:333:22)
      <asynchronous suspension>
      #10     FirebaseAuth.signInWithEmailAndPassword (package:firebase_auth/src/firebase_auth.dart:585:9)
``` 


```
  firebase_core: 2.15.1
  firebase_crashlytics: 3.3.5
  firebase_auth: 4.9.0
  google_sign_in: 6.1.5
  sign_in_with_apple: 5.0.0
  crypto: 3.0.3
```

**Comment by darshankawar** [comment]
I am unable to replicate the reported error using plugin example with latest firebase_auth and firebase_core versions running on Android emulator. I was able to login with test account properly as below:

<img width="336" alt="Screenshot 2023-09-12 at 4 03 43 PM" src="https://github.com/firebase/flutterfire/assets/67046386/863b49ee-56f2-4124-b6b1-c95954fbe1c1">

@sbenmeddour You seem to be using specific versions of the listed plugins. Can you try with ^ ?

@armanhadifatah What plugin version are you using ?
