### ISSUE TITLE
🐛 [firebase_storage] Check if a file exists without throwing exceptions

### ISSUE THREAD

**Issue by kaminoan-dev** [firebase/flutterfire#11620]
## Bug report

**Describe the bug**
Currently there is no function or method to cleanly check if a file exits in Firebase Storage.

### Steps to reproduce

There are many ways that have been proposed to check if a file exists, which all consist on try-catch. 

```Dart
Future<bool> exists(String file) async {
      try {
          await _kStorageRef.child(file).getDownloadURL();
          return true;
      } catch (e) {
          return false;
      }
}
```

This however results in Flutterfire throwing exception logs into the console.

### Expected behavior

Have an `exists` async function in the `Reference` object which will return true or false depending on whether the file exists in Firebase Storage.

**Comment by ojciec-dev** [comment]
Same here. I was about to raise and issue but I found this one (and 10843).

It's worth mentioning that it's spamming my logs only on Android (real device) but not on iOS simulator. 

```
  firebase_storage: ^11.2.6
```

This is my usecase - the image can either be present on Firestore or not (user has an option to upload custom image) and here's my code

```dart
final FirebaseAuth _auth;
final FirebaseStorage _storage;
...

Future<String> getImageUrl(String category, String imageId) async {
    try {
      final String? userId = _auth.currentUser?.uid;
      final ref = _storage.ref('users/$userId/$category/$imageId');

      // Will print `StorageException has occurred.` + stacktrace if image is not present on Firestore. 
      // Works fine when image has already been uploaded.
      final url = await ref.getDownloadURL();
      print('url: $url');
      return url;
    } catch (e) {
      (e as FirebaseException).code == 'object-not-found'
          ? print('$category has no image for $imageId')
          : print('Error fetching image: $e');
      return '';
    }
}
```

```
E/StorageException(27402): StorageException has occurred.
E/StorageException(27402): Object does not exist at location.
E/StorageException(27402):  Code: -13010 HttpResult: 404
E/StorageException(27402): {  "error": {    "code": 404,    "message": "Not Found."  }}
E/StorageException(27402): java.io.IOException: {  "error": {    "code": 404,    "message": "Not Found."  }}
E/StorageException(27402): 	at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:445)
E/StorageException(27402): 	at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(NetworkRequest.java:462)
E/StorageException(27402): 	at com.google.firebase.storage.network.NetworkRequest.processResponseStream(NetworkRequest.java:453)
E/StorageException(27402): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:272)
E/StorageException(27402): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:289)
E/StorageException(27402): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:76)
E/StorageException(27402): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:68)
E/StorageException(27402): 	at com.google.firebase.storage.GetDownloadUrlTask.run(GetDownloadUrlTask.java:77)
E/StorageException(27402): 	at com.google.firebase.concurrent.LimitedConcurrencyExecutor.lambda$decorate$0$com-google-firebase-concurrent-LimitedConcurrencyExecutor(LimitedConcurrencyExecutor.java:65)
E/StorageException(27402): 	at com.google.firebase.concurrent.LimitedConcurrencyExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/StorageException(27402): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/StorageException(27402): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/StorageException(27402): 	at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory(CustomThreadFactory.java:47)
E/StorageException(27402): 	at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/StorageException(27402): 	at java.lang.Thread.run(Thread.java:1012)

W/getImageUrl: A34 has no image for 919a7efd-6df2-4992-8fc4-4af79dd02945
```

## Expected 
It's spamming my logs and there is no way to stop it. Please give us `exists` method or at least stop spamming logs. Thanks.

## Flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.82.2)
[✓] Connected device (4 available)
[✓] Network resources
```

**Comment by russellwheatley** [comment]
FlutterFire is just a wrapper around the Firebase native SDKs, we aren't going to write a custom API for this specific use case I'm afraid. You might want to create a ticket on the native SDK repos as we are downstream from them. If it is implemented there, we can cover that API.
