### ISSUE TITLE
🐛 [Firebase Crashlytics] Crash not reported at Firebase Console

### ISSUE THREAD

**Issue by patilvishwanath** [firebase/flutterfire#11640]
## Bug report

**Describe the bug**
I have added a force crash, app crashes, but the same is not being reported at Firebase Console. UnCaughtExceptions are being reported. 

### Expected behavior

For every app crashes, the same should be reoprted at. FirebaseConsole.

### Sample Code

<details><summary>Click To Expand</summary>

```
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
```

```
// Initialize Firebase.
WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );


```

```
// Pass all uncaught "fatal" errors from the framework to Crashlytics
    FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;

    // Pass all uncaught asynchronous errors that aren't handled
    // by the Flutter framework to Crashlytics
    PlatformDispatcher.instance.onError = (final error, final stack) {
      FirebaseCrashlytics.instance.recordError(
        error,
        stack,
      );
      return true;
    };
```

```
//Force crash app
FirebaseCrashlytics.instance.crash();
```

</details>

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5.1 22G90 darwin-x64, locale en-GB)
    • Flutter version 3.10.6 on channel stable at /Users/vishwanathpatil/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 months ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/vishwanathpatil/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: Connected device exceeded maximum allowed duration of 0:04:30.000000
    • 

[✓] Network resources
    • All expected network resources are available.

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
firebase_analytics 10.4.5 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]

firebase_analytics_platform_interface 3.6.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
firebase_analytics_web 0.5.4+5 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
firebase_core_web 2.7.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
firebase_crashlytics 3.3.5 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
firebase_crashlytics_platform_interface 3.6.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
firebase_messaging 14.5.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
firebase_messaging_platform_interface 4.5.6 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
firebase_messaging_web 3.5.6 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
firebase_performance 0.9.2+5 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
firebase_performance_platform_interface 0.1.4+5 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
firebase_performance_web 0.1.4+5 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @patilvishwanath 
Have you already check   https://firebase.google.com/docs/crashlytics/get-started?platform=flutter#configure-crash-handlers and see if it helps in your case or not ?

Also, if you try something like below, does it help ?

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  FlutterError.onError = (errorDetails) {
	// ERROR HANDLER THAT SENDS UNCAUGHT ERRORS TO CRASHLYTICS
    FirebaseCrashlytics.instance.recordFlutterFatalError(errorDetails);
  };
  runApp(MyApp());
```

Check if the call reaches `FlutterError.onError` for either recordFlutterError or recordFlutterFatalError  to be called.

**Comment by patilvishwanath** [comment]
@darshankawar I have tried the above code snippet, force crash simulated doesn't get reported. Although exceptions are getting reported as fatal.  Will check once again for crash whether call reaches `FlutterError.onError`

One more observation this api is not called - https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog  

which otherwise is called when app crash & restart.

**Comment by patilvishwanath** [comment]
@darshankawar I have cross checked impl, in case of uncaught exceptions call reaches, `FlutterError.onError`. But not in the case of Force Crash. For force crash get below exception : 

```
2023-09-29 13:28:37.706 25921-25921 AndroidRuntime          usap64                               E  FATAL EXCEPTION: main
                                                                                                    Process: com.abc.xyz, PID: 25921
                                                                                                    io.flutter.plugins.firebase.crashlytics.FirebaseCrashlyticsTestCrash: This is a test crash caused by calling .crash() in Dart.
                                                                                                    	at io.flutter.plugins.firebase.crashlytics.FlutterFirebaseCrashlyticsPlugin.lambda$crash$1(Unknown Source:2)
                                                                                                    	at io.flutter.plugins.firebase.crashlytics.FlutterFirebaseCrashlyticsPlugin.f(Unknown Source:0)
                                                                                                    	at io.flutter.plugins.firebase.crashlytics.d.run(Unknown Source:0)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:233)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8068)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
2023-09-29 13:28:41.304  6972-6972  FirebaseInitProvider    pid-6972                             I  FirebaseApp initialization successful
2023-09-29 13:28:41.373  6972-7021  FA                      pid-6972                             I  To enable faster debug mode event logging run:
                                                                                                      adb shell setprop debug.firebase.analytics.app net.oneplus.weather
2023-09-29 13:28:51.429  6972-7020  Fabric                  pid-6972                             E  Settings request failed.
                                                                                                    f.a.a.a.n.e.d$d: java.net.SocketTimeoutException: failed to connect to settings.crashlytics.com/185.38.109.109 (port 443) from /192.168.0.4 (port 47992) after 10000ms
                                                                                                    	at f.a.a.a.n.e.d.g(Unknown Source:15)
                                                                                                    	at f.a.a.a.n.g.m.a(Unknown Source:0)
                                                                                                    	at f.a.a.a.n.g.m.a(Unknown Source:70)
                                                                                                    	at f.a.a.a.n.g.k.a(Unknown Source:43)
                                                                                                    	at f.a.a.a.n.g.k.a(Unknown Source:2)
                                                                                                    	at f.a.a.a.n.g.r.b(Unknown Source:3)
                                                                                                    	at f.a.a.a.m.o(Unknown Source:29)
                                                                                                    	at f.a.a.a.m.c(Unknown Source:8)
                                                                                                    	at f.a.a.a.m.c(Unknown Source:0)
                                                                                                    	at f.a.a.a.h.a(Unknown Source:14)
                                                                                                    	at f.a.a.a.h.a(Unknown Source:2)
                                                                                                    	at f.a.a.a.n.c.a$b.call(Unknown Source:19)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    Caused by: java.net.SocketTimeoutException: failed to connect to settings.crashlytics.com/185.38.109.109 (port 443) from /192.168.0.4 (port 47992) after 10000ms
                                                                                                    	at libcore.io.IoBridge.connectErrno(IoBridge.java:190)
                                                                                                    	at libcore.io.IoBridge.connect(IoBridge.java:134)
                                                                                                    	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
                                                                                                    	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
                                                                                                    	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
                                                                                                    	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
                                                                                                    	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
                                                                                                    	at java.net.Socket.connect(Socket.java:621)
                                                                                                    	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
                                                                                                    	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
                                                                                                    	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
                                                                                                    	at com.google.firebase.perf.network.zzf.getResponseCode(Unknown Source:28)
                                                                                                    	at com.google.firebase.perf.network.zzc.getResponseCode(Unknown Source:2)
                                                                                                    	at f.a.a.a.n.e.d.g(Unknown Source:7)
                                                                                                    	at f.a.a.a.n.g.m.a(Unknown Source:0) 
                                                                                                    	at f.a.a.a.n.g.m.a(Unknown Source:70) 
                                                                                                    	at f.a.a.a.n.g.k.a(Unknown Source:43) 
                                                                                                    	at f.a.a.a.n.g.k.a(Unknown Source:2) 
                                                                                                    	at f.a.a.a.n.g.r.b(Unknown Source:3) 
                                                                                                    	at f.a.a.a.m.o(Unknown Source:29) 
                                                                                                    	at f.a.a.a.m.c(Unknown Source:8) 
                                                                                                    	at f.a.a.a.m.c(Unknown Source:0) 
                                                                                                    	at f.a.a.a.h.a(Unknown Source:14) 
                                                                                                    	at f.a.a.a.h.a(Unknown Source:2) 
                                                                                                    	at f.a.a.a.n.c.a$b.call(Unknown Source:19) 
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:923) 


has context menu
```

**Comment by darshankawar** [comment]
Thanks for the update @patilvishwanath 
Can you try the example from [documentation](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter#force-test-crash) for force crash and check if using it, you get an exception or does it get reported properly ?

**Comment by patilvishwanath** [comment]
@darshankawar  Thank you for the response.
I tried the example from the [documentation](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter#force-test-crash) , I observed a exception, the same is being captured & logged at Firebase console. At any point app didn't crash.

**Comment by VB10** [comment]
> @darshankawar Thank you for the response. I tried the example from the [documentation](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter#force-test-crash) , I observed a exception, the same is being captured & logged at Firebase console. At any point app didn't crash.

+1. I was able to catch it before implementing my project, but when I try a new project, it doesn't work. I've tried the native console, real devices, etc., but I get the same result everywhere.

```yaml

[✓] Flutter (Channel stable, 3.13.3, on macOS 13.4.1 22F770820d darwin-arm64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] VS Code (version 1.82.2)
[✓] Connected device (4 available)

```

**Comment by darshankawar** [comment]
@patilvishwanath 
I tried the plugin example running on Android emulator and checked that force crash does quit the app after throwing below error in the log:

```
Syncing files to device sdk gphone x86 64...
W/Parcel  (19291): Expecting binder but got null!
I/shlyticsexample(19291): Background concurrent copying GC freed 65775(4240KB) AllocSpace objects, 42(1544KB) LOS objects, 49% free, 3633KB/7266KB, paused 476us,13us total 125.539ms
D/AndroidRuntime(19291): Shutting down VM
E/AndroidRuntime(19291): FATAL EXCEPTION: main
E/AndroidRuntime(19291): Process: io.flutter.plugins.firebasecrashlyticsexample, PID: 19291
E/AndroidRuntime(19291): io.flutter.plugins.firebase.crashlytics.FirebaseCrashlyticsTestCrash: This is a test crash caused by calling .crash() in Dart.
E/AndroidRuntime(19291): 	at io.flutter.plugins.firebase.crashlytics.FlutterFirebaseCrashlyticsPlugin.lambda$crash$1(FlutterFirebaseCrashlyticsPlugin.java:85)
E/AndroidRuntime(19291): 	at io.flutter.plugins.firebase.crashlytics.FlutterFirebaseCrashlyticsPlugin$$ExternalSyntheticLambda3.run(Unknown Source:0)
E/AndroidRuntime(19291): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(19291): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19291): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(19291): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(19291): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(19291): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19291): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(19291): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
D/CompatibilityChangeReporter(19291): Compat change id reported: 194532703; UID 10159; state: ENABLED
I/Process (19291): Sending signal. PID: 19291 SIG: 9
Lost connection to device.
the Dart compiler exited unexpectedly.

```

The same also gets reported in the firebase console properly.  Can you try the same example at your end and check ?

> At any point app didn't crash.

What platform are you seeing this ? 

@VB10 You may check the same for iOS and see if it helps or not.

**Comment by patilvishwanath** [comment]
@darshankawar  I have checked for Android Platform.

**Comment by patilvishwanath** [comment]
@darshankawar waiting for your response. Kindly reply.

**Comment by darshankawar** [comment]
I am unable to replicate the reported error, but based on the report, keeping it open for team's input / attention.

**Comment by russellwheatley** [comment]
I've opened an issue on firebase-ios-sdk as it appears non-fatal crashes are not appearing in the Firebase console: https://github.com/firebase/firebase-ios-sdk/issues/12196

**Comment by patilvishwanath** [comment]
@russellwheatley @darshankawar Agree force crash is for testing purpose only & this works fine for iOS. But even for iOS it only displays native stack trace, even after adding force crash in flutter code. It should share appropriate source of crash / exception which cause the crash to happen.

For Android it doesn't crash the app at all.
