### ISSUE TITLE
🐛 [cloud_firestore] Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.setMethodCallHandler(io.flutter.plugin.common.MethodChannel$MethodCallHandler)' on a null object reference

### ISSUE THREAD

**Issue by Muta-Jonathan** [firebase/flutterfire#11740]
## Bug report

Am using flutter 
>Dart SDK 3.1.4
Flutter SDK 3.13.8
>   firebase_dependencies
> firebase_core: ^2.17.0
>  cloud_firestore: ^4.9.3

### Error am getting

```
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.setMethodCallHandler(io.flutter.plugin.common.MethodChannel$MethodCallHandler)' on a null object reference
                                                                                                    	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin.onDetachedFromEngine(FlutterFirebaseFirestorePlugin.java:132)
                                                                                                    	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:272)
                                                                                                    	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:282)
                                                                                                    	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:290)
                                                                                                    	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:123)
                                                                                                    	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:460)
                                                                                                    	at com.ryanheise.audioservice.AudioServicePlugin.disposeFlutterEngine(AudioServicePlugin.java:112)
                                                                                                    	at com.ryanheise.audioservice.AudioServicePlugin$AudioHandlerInterface.onDestroy(AudioServicePlugin.java:808)
                                                                                                    	at com.ryanheise.audioservice.AudioService.onDestroy(AudioService.java:363)
                                                                                                    	at android.app.ActivityThread.handleStopService(ActivityThread.java:4300)
                                                                                                    	at android.app.ActivityThread.access$2100(ActivityThread.java:236) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2006) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:264) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7684) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980) 

```
### Steps to reproduce

1. on building the app works fine
2.but on exit
3.It returns this error some times
### Expected behavior

It should exit without error

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.
My project can be found [here](https://github.com/Muta-Jonathan/AvventoRadio-flutter-Apk)

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.8, on Ubuntu 20.04.6 LTS 5.15.0-86-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] VS Code (version unknown)
    ✗ Unable to determine VS Code version.
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.1.4
Flutter SDK 3.13.8
avvento_radio 1.0.0+1

dependencies:
- animated_text_kit 4.2.2 [flutter characters]
- audio_video_progress_bar 2.0.1 [flutter]
- cached_network_image 3.3.0 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- chewie 1.5.0 [cupertino_icons flutter provider video_player wakelock]
- cloud_firestore 4.11.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- connectivity_plus 4.0.2 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- cupertino_icons 1.0.6
- double_back_to_close_app 2.1.0 [flutter]
- firebase_core 2.19.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- floating 2.0.1 [flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_animated_icons 1.0.1 [flutter cupertino_icons lottie]
- flutter_native_splash 2.3.4 [args flutter flutter_web_plugins js html image meta path universal_io xml yaml]
- get 4.6.6 [flutter]
- http 0.13.6 [async http_parser meta]
- jiffy 6.2.1 [intl]
- just_audio 0.9.35 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- just_audio_background 0.0.1-beta.10 [just_audio_platform_interface audio_service audio_session flutter flutter_web_plugins meta rxdart]
- provider 6.0.5 [collection flutter nested]
- rxdart 0.27.7
- share_plus 6.3.4 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- video_player 2.7.2 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- web_socket_channel 2.4.0 [async crypto stream_channel]

dev dependencies:
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

dependency overrides:
- cloud_firestore_platform_interface 6.0.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]

transitive dependencies:
- _flutterfire_internals 1.3.9 [collection firebase_core firebase_core_platform_interface flutter meta]
- archive 3.4.6 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- audio_service 0.18.12 [audio_service_platform_interface audio_service_web audio_session rxdart flutter_cache_manager clock js flutter flutter_web_plugins]
- audio_service_platform_interface 0.1.1 [flutter plugin_platform_interface meta]
- audio_service_web 0.1.1 [audio_service_platform_interface rxdart js flutter flutter_web_plugins]
- audio_session 0.1.16 [flutter flutter_web_plugins rxdart meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- cached_network_image_platform_interface 3.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.0 [meta path]
- clock 1.1.1
- cloud_firestore_web 3.8.1 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.17.2
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+6 [js meta]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- dbus 0.7.8 [args ffi meta xml]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 6.1.4 [meta path]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- html 0.15.4 [csslib source_span]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.1.3 [archive meta xml]
- intl 0.18.1 [clock meta path]
- js 0.6.7 [meta]
- json_annotation 4.8.1 [meta]
- just_audio_platform_interface 4.2.1 [flutter plugin_platform_interface]
- just_audio_web 0.4.8 [just_audio_platform_interface flutter flutter_web_plugins]
- lints 2.1.1
- lottie 1.4.3 [archive flutter path vector_math]
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- mime 1.0.4
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 2.0.0 [flutter]
- path 1.8.3
- path_provider 2.1.1 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.0 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.1 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.4.0 [meta]
- platform 3.1.3
- plugin_platform_interface 2.1.6 [meta]
- pointycastle 3.7.3 [collection convert js]
- share_plus_platform_interface 3.3.1 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.1 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.0 [flutter sqflite_common path]
- sqflite_common 2.5.0 [synchronized path meta]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_linux 3.0.6 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.20 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.8 [flutter url_launcher_platform_interface]
- uuid 4.1.0 [crypto sprintf]
- vector_math 2.1.4
- video_player_android 2.4.10 [flutter video_player_platform_interface]
- video_player_avfoundation 2.5.0 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.1 [flutter plugin_platform_interface]
- video_player_web 2.1.1 [flutter flutter_web_plugins video_player_platform_interface]
- wakelock 0.6.2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.1 [flutter wakelock_platform_interface win32]
- web 0.1.4-beta
- win32 3.1.4 [ffi]
- xdg_directories 1.0.3 [meta path]
- xml 6.3.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>

---

**Comment by darshankawar** [comment]
@Muta-Jonathan 
I looked at the repo you shared, but it seems to be a full fledged project containing other packages as well.
Can you provide us a bare minimal but runnable reproducible code sample that throws the reported error ?

**Comment by Muta-Jonathan** [comment]
thanks @darshankawar for the quick response just adding 
>firebase_core: ^2.19.0
>cloud_firestore: ^4.11.0
to any flutter new project will also trigger the error just as @thenishchalraj has stated

on back press exiting the app the issue is caused..

**Comment by Mikerobenics** [comment]
Same problem on back press.

**Comment by rittik679** [comment]
Please give me the solution. even it shows error in new project for just adding the cloud_firestore package. if i remove this package then app work perfectly so I think it is the problem of cloud_firestore package.

**Comment by thenishchalraj** [comment]
This is the problem with the package only @rittik679 .

I removed the package and now using supabase for my task. I needed to launch my app and because of this error it got delayed. But supabase is amazing: an opensource alternative to firebase.

**Comment by Mikerobenics** [comment]
Temporarily fixed this way:

```
@Override
  public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) {
    // channel.setMethodCallHandler(null);
    channel = null;

    removeEventListeners();

    binaryMessenger = null;
  }
```
>firebase_core: ^2.19.0
> cloud_firestore: ^4.11.0

**Comment by rittik679** [comment]
Is it working well @Mikerobenics ? Can you tell me how to initialize it ?

**Comment by thenishchalraj** [comment]
> Is it working well @Mikerobenics ? Can you tell me how to initialize it ?

Hey @rittik679
Yes it is working well. You can get it in the respective package that is found in the crash report. Or if you want a step here it is:

1. open the android module of app in android studio
2. run the app and make it crash
3. it crashes in file - FlutterFirebaseFirestorePlugin.java at line 132.
4. just comment the line which is mentioned in @Mikerobenics reply which is the main reason of crash
5. build and run the app again, it will work fine.

**Comment by rittik679** [comment]
Thank you Bro @thenishchalraj its working very well, Thank you so much and thank you for also recommending "Supabase".

**Comment by Vishal-1232** [comment]
@rittik679 @Mikerobenics @darshankawar where to find flutterfirebaseplugins.java file?

**Comment by Mikerobenics** [comment]
Hey @Vishal-1232 
I actually did this way:

1. Create packages folder on root of your Flutter project.
2. Download latest `cloud_firestore (4.11.0)` from here: [https://pub.dev/packages/cloud_firestore/versions/4.11.0.tar.gz](url)
3. Unarchive and copy paste `cloud_firestore-4.11.0` folder in previously created packages folder from **step 1.**
4. Open `pubspec.yaml` file in yoour IDE. Find `cloud_firestore: ^4.11.0` or whatever version you have and change to:
```
cloud_firestore:
  path: packages/cloud_firestore-4.11.0
```
5. Go to `/packages/cloud_firestore-4.11.0` and find `FlutterFirebaseFirestorePlugin.java` file. Fulll path: `packages/cloud_firestore-4.11.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java`
6. Open `FlutterFirebaseFirestorePlugin.java` file in your IDE and go to line **131**. You'll see `onDetachedFromEngine` method, just comment out `channel.setMethodCallHandler(null);` line.
7. Run `flutter clean` and `flutter pub get`.
8. Done :)

**Comment by rittik679** [comment]
Hey @Vishal-1232  Run command "flutter build apk" and then you will get the link of that file.

**Comment by Mikerobenics** [comment]
> Is it working well @Mikerobenics ? Can you tell me how to initialize it ?

Working flavesly for me as the temp fix ;) Latest versions of `firebase_auth`, `firebase_messaging` and `flutter_local_notifications` working normally with this too. Thanks)

**Comment by Muta-Jonathan** [comment]
> Is it working well @Mikerobenics ? Can you tell me how to initialize it ?

Thanks @rittik679 this is temp fix for sure @darshankawar this really needs a quick fix
