### ISSUE TITLE
🐛 [firebase_core] build ios failing - pod install failing: failed to parse json file at .../10.3.6/firebaseabtesting.podspec.json unexpected token at '' #12011

### ISSUE THREAD

**Issue by giorgio79** [firebase/flutterfire#11789]
### Description

Getting the error message as per subject when running pod install for my Flutter project. Any tips please? 

### Command

```
/usr/local/Cellar/cocoapods/1.14.1/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.14.1
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin23]
    RubyGems : 3.4.10
        Host : macOS 14.2 (23C5030f)
       Xcode : 15.0.1 (15A507)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /usr/local/Cellar/ruby/3.2.2_1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

### Error

```
JSON::ParserError - Failed to parse JSON at file: '/Users/sysprobs/.cocoapods/repos/trunk/Specs/d/c/1/FirebaseABTesting/10.3.0/FirebaseABTesting.podspec.json'.

unexpected token at ''
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-core-1.14.1/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-core-1.14.1/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-core-1.14.1/lib/cocoapods-core/specification.rb:752:in `from_string'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-core-1.14.1/lib/cocoapods-core/specification.rb:726:in `from_file'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-core-1.14.1/lib/cocoapods-core/source.rb:188:in `specification'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-1.14.1/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/delegate.rb:348:in `block in delegating_block'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-1.14.1/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:809:in `block in group_possibilities'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `reverse_each'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `group_possibilities'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:779:in `possibilities_for_requirement'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-1.14.1/lib/cocoapods/resolver.rb:94:in `resolve'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-1.14.1/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-1.14.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-1.14.1/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-1.14.1/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-1.14.1/lib/cocoapods/installer.rb:422:in `analyze'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-1.14.1/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-1.14.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-1.14.1/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-1.14.1/lib/cocoapods/installer.rb:162:in `install!'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-1.14.1/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-1.14.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.14.1/libexec/gems/cocoapods-1.14.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.14.1/libexec/bin/pod:25:in `load'
/usr/local/Cellar/cocoapods/1.14.1/libexec/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

### Firebase SDK Version

10.3.6

### Xcode Version

16

### Installation Method

CocoaPods

### Firebase Product(s)

AB Testing

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

and flutter doctor as well

```
[!] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.22621.2428], locale en-US)
    • Flutter version 3.13.9 on channel stable at D:\flutter
    ! Warning: `flutter` on your path resolves to D:\...\flutter, which is not inside your current Flutter SDK checkout at D:\flutter. Consider adding D:\flutter\bin to
      the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.9)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.83.1)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2428]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 118.0.5993.70
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 118.0.2088.69

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

**Comment by giorgio79** [comment]
looks to be some CloudFlare fiasco https://github.com/CocoaPods/CocoaPods/issues/12115
