### ISSUE TITLE
🐛 [firebase_storage] Can't read from any buckets other than the one referenced in `FirebaseOptions`

### ISSUE THREAD

**Issue by Lootwig** [firebase/flutterfire#11805]
## Bug report

Buckets that are not the one specified in `FirebaseOptions.storageBucket` can't be read from.

### Steps to reproduce

1. Create a firebase project with cloud storage enabled, and add a second bucket called 'second'. Set read+write to public.
2. Clone [the example project](https://github.com/Lootwig/buckets) and configure it with your project's info, specifying the default bucket's ID as value for your `FirebaseOptions.storageBucket`
3. Run the code
4. Observe exception on startup

### Expected behavior

The `getData()` call does not fail.

---

## Additional context

Replacing the `storageBucket` value in both the android app's `google-services.json` as well as `FirebaseOptions` with "second" allows accessing the second bucket, but no longer the default one.

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.13.7-0.0.pre.1, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
    ! Flutter version 3.13.7-0.0.pre.1 on channel [user-branch] at D:\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.18)
[√] Android Studio (version 2021.1)
[√] IntelliJ IDEA Ultimate Edition (version 2022.3)
[√] IntelliJ IDEA Ultimate Edition (version 2023.2)
[√] VS Code (version 1.81.1)
[√] VS Code, 64-bit edition (version 1.81.0)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 2 categories.

```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 3.1.3
Flutter SDK 3.13.7-0.0.pre.1                                                            
buckets 0.1.0                                                                           
                                                                                        
dependencies:                                                                           
- firebase_core 2.20.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 11.4.0 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]    
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection mater
ial_color_utilities meta source_span stream_channel string_scanner term_glyph web]

transitive dependencies:
- _flutterfire_internals 1.3.10 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.17.2
- fake_async 1.3.1 [clock collection]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 5.0.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.6.11 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter
_web_plugins http js meta]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- http 1.1.0 [async http_parser meta]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- lints 2.1.1
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- path 1.8.3
- plugin_platform_interface 2.1.6 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- web 0.1.4-beta

```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @Lootwig 

Can you provide the exception that you are seeing ?
I tried recreating the app based on your description, but not seem to be getting the error. Might be missing some steps to properly configure it.

**Comment by Lootwig** [comment]
@darshankawar 

Can you share the project you created privately? Configuration error might just as well be on my end, but seeing how there's a pretty straightforward workaround that doesn't involve changing the project settings I am not sure about it

Here's the console output I'm getting:

```
D/StreamDownloadTask(15758): java.io.IOException: Could not open resulting stream.
D/StreamDownloadTask(15758): 	at com.google.firebase.storage.StreamDownloadTask.createDownloadStream(StreamDownloadTask.java:145)
D/StreamDownloadTask(15758): 	at com.google.firebase.storage.StreamDownloadTask.access$000(StreamDownloadTask.java:36)
D/StreamDownloadTask(15758): 	at com.google.firebase.storage.StreamDownloadTask$1.call(StreamDownloadTask.java:167)
D/StreamDownloadTask(15758): 	at com.google.firebase.storage.StreamDownloadTask$1.call(StreamDownloadTask.java:164)
D/StreamDownloadTask(15758): 	at com.google.firebase.storage.StreamDownloadTask$StreamProgressWrapper.ensureStream(StreamDownloadTask.java:325)
D/StreamDownloadTask(15758): 	at com.google.firebase.storage.StreamDownloadTask$StreamProgressWrapper.access$100(StreamDownloadTask.java:262)
D/StreamDownloadTask(15758): 	at com.google.firebase.storage.StreamDownloadTask.run(StreamDownloadTask.java:175)
D/StreamDownloadTask(15758): 	at com.google.firebase.storage.StorageTask.lambda$getRunnable$7$com-google-firebase-storage-StorageTask(StorageTask.java:1077)
D/StreamDownloadTask(15758): 	at com.google.firebase.storage.StorageTask$$ExternalSyntheticLambda7.run(Unknown Source:2)
D/StreamDownloadTask(15758): 	at com.google.firebase.concurrent.LimitedConcurrencyExecutor.lambda$decorate$0$com-google-firebase-concurrent-LimitedConcurrencyExecutor(LimitedConcurrencyExecutor.java:65)
D/StreamDownloadTask(15758): 	at com.google.firebase.concurrent.LimitedConcurrencyExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
D/StreamDownloadTask(15758): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
D/StreamDownloadTask(15758): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
D/StreamDownloadTask(15758): 	at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory(CustomThreadFactory.java:47)
D/StreamDownloadTask(15758): 	at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(Unknown Source:4)
D/StreamDownloadTask(15758): 	at java.lang.Thread.run(Thread.java:1012)
E/StorageException(15758): StorageException has occurred.
E/StorageException(15758): Object does not exist at location.
E/StorageException(15758):  Code: -13010 HttpResult: 404
E/StorageException(15758): Could not open resulting stream.
E/StorageException(15758): java.io.IOException: Could not open resulting stream.
E/StorageException(15758): 	at com.google.firebase.storage.StreamDownloadTask.createDownloadStream(StreamDownloadTask.java:145)
E/StorageException(15758): 	at com.google.firebase.storage.StreamDownloadTask.access$000(StreamDownloadTask.java:36)
E/StorageException(15758): 	at com.google.firebase.storage.StreamDownloadTask$1.call(StreamDownloadTask.java:167)
E/StorageException(15758): 	at com.google.firebase.storage.StreamDownloadTask$1.call(StreamDownloadTask.java:164)
E/StorageException(15758): 	at com.google.firebase.storage.StreamDownloadTask$StreamProgressWrapper.ensureStream(StreamDownloadTask.java:325)
E/StorageException(15758): 	at com.google.firebase.storage.StreamDownloadTask$StreamProgressWrapper.access$100(StreamDownloadTask.java:262)
E/StorageException(15758): 	at com.google.firebase.storage.StreamDownloadTask.run(StreamDownloadTask.java:175)
E/StorageException(15758): 	at com.google.firebase.storage.StorageTask.lambda$getRunnable$7$com-google-firebase-storage-StorageTask(StorageTask.java:1077)
E/StorageException(15758): 	at com.google.firebase.storage.StorageTask$$ExternalSyntheticLambda7.run(Unknown Source:2)
E/StorageException(15758): 	at com.google.firebase.concurrent.LimitedConcurrencyExecutor.lambda$decorate$0$com-google-firebase-concurrent-LimitedConcurrencyExecutor(LimitedConcurrencyExecutor.java:65)
E/StorageException(15758): 	at com.google.firebase.concurrent.LimitedConcurrencyExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/StorageException(15758): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/StorageException(15758): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/StorageException(15758): 	at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory(CustomThreadFactory.java:47)
E/StorageException(15758): 	at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/StorageException(15758): 	at java.lang.Thread.run(Thread.java:1012)
E/StorageException(15758): StorageException has occurred.
E/StorageException(15758): Object does not exist at location.
E/StorageException(15758):  Code: -13010 HttpResult: 404
E/StorageException(15758): Could not open resulting stream.
E/StorageException(15758): java.io.IOException: Could not open resulting stream.
E/StorageException(15758): 	at com.google.firebase.storage.StreamDownloadTask.createDownloadStream(StreamDownloadTask.java:145)
E/StorageException(15758): 	at com.google.firebase.storage.StreamDownloadTask.access$000(StreamDownloadTask.java:36)
E/StorageException(15758): 	at com.google.firebase.storage.StreamDownloadTask$1.call(StreamDownloadTask.java:167)
E/StorageException(15758): 	at com.google.firebase.storage.StreamDownloadTask$1.call(StreamDownloadTask.java:164)
E/StorageException(15758): 	at com.google.firebase.storage.StreamDownloadTask$StreamProgressWrapper.ensureStream(StreamDownloadTask.java:325)
E/StorageException(15758): 	at com.google.firebase.storage.StreamDownloadTask$StreamProgressWrapper.access$100(StreamDownloadTask.java:262)
E/StorageException(15758): 	at com.google.firebase.storage.StreamDownloadTask.run(StreamDownloadTask.java:175)
E/StorageException(15758): 	at com.google.firebase.storage.StorageTask.lambda$getRunnable$7$com-google-firebase-storage-StorageTask(StorageTask.java:1077)
E/StorageException(15758): 	at com.google.firebase.storage.StorageTask$$ExternalSyntheticLambda7.run(Unknown Source:2)
E/StorageException(15758): 	at com.google.firebase.concurrent.LimitedConcurrencyExecutor.lambda$decorate$0$com-google-firebase-concurrent-LimitedConcurrencyExecutor(LimitedConcurrencyExecutor.java:65)
E/StorageException(15758): 	at com.google.firebase.concurrent.LimitedConcurrencyExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/StorageException(15758): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/StorageException(15758): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/StorageException(15758): 	at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory(CustomThreadFactory.java:47)
E/StorageException(15758): 	at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/StorageException(15758): 	at java.lang.Thread.run(Thread.java:1012)
E/flutter (15758): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_storage/object-not-found] No object exists at the desired reference.
E/flutter (15758): #0      FirebaseStorageHostApi.referenceGetData (package:firebase_storage_platform_interface/src/pigeon/messages.pigeon.dart:579:7)
E/flutter (15758): <asynchronous suspension>
E/flutter (15758): #1      MethodChannelReference.getData (package:firebase_storage_platform_interface/src/method_channel/method_channel_reference.dart:140:14)
E/flutter (15758): <asynchronous suspension>
E/flutter (15758): #2      main (package:buckets/main.dart:14:3)
E/flutter (15758): <asynchronous suspension>
E/flutter (15758): 
```

**Comment by darshankawar** [comment]
@Lootwig 
From the log, it shows below:

```
E/StorageException(15758): StorageException has occurred.
E/StorageException(15758): Object does not exist at location.
E/StorageException(15758):  Code: -13010 HttpResult: 404
E/StorageException(15758): Could not open resulting stream.
E/StorageException(15758): java.io.IOException: Could not open resulting stream.
```

As you have changed the bucket, are there any documents in it that `getData()` could retrieve ? Can you try by adding some data in that bucket and run again to check if you still get same error or not ?

**Comment by Lootwig** [comment]
The document from the putData line is created as expected.

And like I already mentioned in the description, changing the bucket name
in the options field lets me read it just fine, but then I can't access the
default bucket anymore.

**Comment by darshankawar** [comment]
Thanks for the update. Although I was able to see the log, it seems to be coming from native SDK and not from flutterfire, but based on the report and use case described, ie, trying to read from buckets other than one mentioned in FirebaseOptions, keeping this issue open for team's input.

**Comment by Lootwig** [comment]
@darshankawar when you say you were "able to see the log", are you talking about reproducing the issue or simply the console output I posted?

"coming from the native SDK" - does that mean I need to file another issue somewhere else? if so, please provide a link to the respective repository if it allows customers to file issues.

**Comment by Salvist** [comment]
I have this issues as well after trying to upgrade all of my firebase packages to the latest one as well as the [firebase iOS SDK](https://github.com/invertase/firestore-ios-sdk-frameworks) to 10.16.0.

```
final storage = FirebaseStorage.instanceFor(bucket: 'gs://second-bucket');
storage.ref().child('0000.txt').putString('Hello');
```
The code above was not putting the `0000.txt` file to the `second-bucket` and instead putting it in the default bucket.
I also tried to `listAll()` in the second bucket, what I get is all files in the default bucket.

I ended up downgrading all of my firebase packages and use firebase ios sdk 10.15.0 and it seems to be working fine now.

**Comment by Lootwig** [comment]
@Salvist what `firebase_storage` version did you downgrade to?

**Comment by Salvist** [comment]
@Lootwig Sorry, I just edited my comment above. It's ^11.2.8

**Comment by russellwheatley** [comment]
I've just tested this using the example app updating this [code here](https://github.com/firebase/flutterfire/blob/master/packages/firebase_storage/firebase_storage/example/lib/main.dart#L84-L115). I tested your code:

```
final storage = FirebaseStorage.instanceFor(bucket: 'gs://second-bucket');
storage.ref().child('0000.txt').putString('Hello');
```

I also tested using `putFile`, they both updated the second bucket.

**Comment by Lootwig** [comment]
@russellwheatley the problem I described is not about _writing_ the value, but about _reading_ it with `getFile()`. I've [stated before](https://github.com/firebase/flutterfire/issues/11805#issuecomment-1790698310) that the write succeeds, and into the expected bucket, but retrieving the data is what fails if the json & `FirebaseOptions` instance is not changed.

**Comment by Lootwig** [comment]
hey @darshankawar, do you intend to answer any of these questions I asked:

- [Can you share the project you created](https://github.com/firebase/flutterfire/issues/11805#issuecomment-1788763736)?
- [What do you mean by "you were able to see the log"](https://github.com/firebase/flutterfire/issues/11805#issuecomment-1792352743)?
- if this repo is the wrong place for this issue, [what is the right one](https://github.com/firebase/flutterfire/issues/11805#issuecomment-1792352743)?

**Comment by russellwheatley** [comment]
@Lootwig - I think I've found the bug, I'm preparing a PR at the moment 🙏
