### ISSUE TITLE
🐛 [firebase_messaging] Firebase messaging crashing on FlutterFirebaseMessagingBackgroundExecutor.java:236

### ISSUE THREAD

**Issue by urvesh-sm** [firebase/flutterfire#11901]
## Bug report

**Describe the bug**
I am using following firebase versions:
```
  firebase_core: ^2.19.0
  firebase_messaging: ^14.7.1
  firebase_crashlytics: ^3.4.1
  firebase_performance: ^0.9.3+1
  firebase_dynamic_links: ^5.4.1
  firebase_remote_config: ^4.3.1
  firebase_app_installations: ^0.2.3+5
  firebase_app_check: ^0.2.1+1
  firebase_in_app_messaging: ^0.7.4+1
```

And I am getting following crash log on crashlytics:

Stack 1:
```
# Crashlytics - Stack trace
# Platform: android
# Date: Wed Nov 15 2023 13:32:38 GMT+0530 (India Standard Time)

Fatal Exception: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: nh.z
       at android.os.Parcel.readParcelableCreator(Parcel.java:3042)
       at android.os.Parcel.readParcelable(Parcel.java:2964)
       at android.os.Parcel.readValue(Parcel.java:2866)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
       at android.os.BaseBundle.unparcel(BaseBundle.java:236)
       at android.os.Bundle.getParcelable(Bundle.java:951)
       at android.content.Intent.getParcelableExtra(Intent.java:7940)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate(FlutterFirebaseMessagingBackgroundExecutor.java:236)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.lambda$onHandleWork$0(FlutterFirebaseMessagingBackgroundService.java:149)
       at com.google.android.exoplayer2.drm.DrmSessionEventListener$EventDispatcher.lambda$drmKeysRestored$3(DrmSessionEventListener.java:202)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7697)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

Stack 2:
```
# Crashlytics - Stack trace
# Platform: android
# Date: Wed Nov 15 2023 09:12:25 GMT+0530 (India Standard Time)

Fatal Exception: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: we.z
       at android.os.Parcel.readParcelableCreator(Parcel.java:3372)
       at android.os.Parcel.readParcelable(Parcel.java:3275)
       at android.os.Parcel.readValue(Parcel.java:3177)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3575)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
       at android.os.BaseBundle.unparcel(BaseBundle.java:236)
       at android.os.Bundle.getParcelable(Bundle.java:1001)
       at android.content.Intent.getParcelableExtra(Intent.java:8292)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate(FlutterFirebaseMessagingBackgroundExecutor.java:236)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.lambda$onHandleWork$0(FlutterFirebaseMessagingBackgroundService.java:149)
       at com.google.android.exoplayer2.drm.DrmSessi
```

### Steps to reproduce

1. This happens whenever we create a messaging campaign and send it multiple users at same time.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
[✓] VS Code (version 1.84.2)
[!] Connected device
    ! No devices available
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Resolving dependencies...
Got dependencies.
Dart SDK 3.1.5
Flutter SDK 3.13.9
stable_money_flutter 1.6.81+161

dependencies:
- algo360sdk 1.0.3 [flutter plugin_platform_interface permission_handler]
- android_id 0.3.6 [flutter]
- another_flushbar 1.12.30 [flutter]
- appcheck 1.0.6 [flutter]
- basic_utils 5.5.4 [http logging json_annotation pointycastle]
- cached_network_image 3.3.0 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- common 0.0.1 [flutter freezed_annotation json_annotation vibration hooks_riverpod flutter_hooks]
- currency_text_input_formatter 2.1.10 [flutter intl]
- dashed_circular_progress_bar 0.0.6 [flutter]
- datadog_flutter_plugin 1.6.2 [flutter flutter_web_plugins js plugin_platform_interface json_annotation uuid meta]
- datadog_tracking_http_client 1.4.0 [flutter datadog_flutter_plugin uuid http]
- device_info_plus 9.1.0 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- dio 5.3.3 [async http_parser meta path]
- dots_indicator 3.0.0 [flutter]
- dotted_border 2.1.0 [flutter path_drawing]
- expandable_richtext 1.0.3 [flutter]
- facebook_app_events 0.19.0 [flutter]
- fading_edge_scrollview 3.0.0 [flutter]
- figma_squircle 0.5.3 [vector_math flutter]
- file_picker 6.0.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_analytics 10.6.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check 0.2.1+2 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_installations 0.2.4+2 [firebase_app_installations_platform_interface firebase_app_installations_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.20.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.4.2 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.4.2 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_in_app_messaging 0.7.4+1 [firebase_core firebase_core_platform_interface firebase_in_app_messaging_platform_interface flutter meta]
- firebase_messaging 14.7.2 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.9.3+2 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_remote_config 4.3.2 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- fixnum 1.1.0
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_branch_sdk 6.9.0 [flutter flutter_web_plugins plugin_platform_interface js]
- flutter_contacts 1.1.7+1 [flutter]
- flutter_holo_date_picker 1.1.3 [flutter auto_size_text]
- flutter_hooks 0.20.3 [flutter]
- flutter_html 3.0.0-beta.2 [html csslib collection list_counter flutter]
- flutter_inappwebview 6.0.0-beta.25 [flutter flutter_web_plugins js flutter_inappwebview_internal_annotations]
- flutter_jailbreak_detection 1.10.0 [flutter]
- flutter_local_notifications 16.1.0 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- flutter_native_splash 2.3.4 [args flutter flutter_web_plugins js html image meta path universal_io xml yaml]
- flutter_rating_bar 4.0.1 [flutter]
- flutter_screenutil 5.9.0 [flutter]
- flutter_secure_storage 9.0.0 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_staggered_animations 1.1.1 [flutter]
- flutter_staggered_grid_view 0.7.0 [flutter]
- flutter_svg 2.0.8 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- geolocator 10.1.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- go_router 12.0.0 [collection flutter flutter_web_plugins logging meta]
- google_sign_in 6.1.5 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- hooks_riverpod 2.4.4 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- html 0.15.4 [csslib source_span]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_picker 1.0.4 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- in_app_review 2.0.8 [flutter in_app_review_platform_interface]
- in_app_update 4.2.2 [flutter]
- intl 0.18.1 [clock meta path]
- isar 3.1.0+1 [ffi js meta]
- isar_flutter_libs 3.1.0+1 [flutter isar]
- jiffy 6.2.1 [intl]
- json_annotation 4.8.1 [meta]
- just_the_tooltip 0.0.12 [flutter]
- keyboard_actions 4.2.0 [flutter]
- linked_scroll_controller 0.2.0 [flutter]
- loading_animation_widget 1.2.0+4 [flutter]
- local_auth 2.1.7 [flutter local_auth_android local_auth_ios local_auth_platform_interface local_auth_windows]
- logging 1.2.0
- lottie 2.7.0 [archive flutter path vector_math]
- mime 1.0.4
- mime_type 1.0.0
- mixpanel_flutter 2.1.1 [flutter flutter_web_plugins js]
- moengage_flutter 6.0.0 [flutter moengage_flutter_android moengage_flutter_ios moengage_flutter_platform_interface moengage_flutter_web]
- package_info_plus 4.2.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- path 1.8.3
- path_provider 2.1.1 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- percent_indicator 4.2.3 [flutter]
- permission_handler 10.4.5 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- phone_number 2.0.1 [flutter meta]
- photo_view 0.14.0 [flutter]
- pin_code_fields 8.0.1 [flutter]
- pointycastle 3.7.3 [collection convert js]
- protobuf 3.1.0 [collection fixnum meta]
- reactive_date_range_picker 2.0.1 [flutter intl reactive_forms]
- reactive_date_time_picker 3.0.0 [flutter intl reactive_forms]
- reactive_forms 16.1.1 [flutter intl]
- riverpod_annotation 2.2.1 [meta riverpod]
- screenshot 2.1.0 [flutter]
- share_plus 7.2.1 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 3.0.0 [flutter]
- shorebird_code_push 1.1.3 [ffi meta]
- simple_gradient_text 1.3.0 [flutter]
- simple_progress_indicators 0.2.0 [flutter]
- smooth_corner 1.1.0 [flutter]
- sms_autofill 2.3.0 [pin_input_text_field flutter]
- story_view 0.14.0 [flutter flutter_cache_manager rxdart video_player collection]
- syncfusion_flutter_pdfviewer 20.4.54 [flutter vector_math async http uuid intl syncfusion_pdfviewer_platform_interface syncfusion_pdfviewer_web syncfusion_pdfviewer_macos syncfusion_pdfviewer_windows syncfusion_flutter_core syncfusion_flutter_pdf url_launcher]
- timer_count_down 2.2.2 [flutter]
- uni_links 0.5.1 [flutter uni_links_platform_interface uni_links_web]
- url_launcher 6.2.0 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- user_experior 4.0.2 [flutter]
- visibility_detector 0.4.0+2 [flutter]
- youtube_player_flutter 9.0.0-beta.0 [flutter flutter_inappwebview]

dev dependencies:
- build_runner 2.4.6 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- build_verify 3.1.0 [io path test]
- flutter_gen_runner 5.3.2 [flutter_gen_core build collection crypto glob path]
- flutter_lints 3.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]
- freezed 2.4.5 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- go_router_builder 2.3.3 [analyzer async build build_config collection meta path source_gen source_helper]
- isar_generator 3.1.0+1 [analyzer build dart_style dartx glob isar path source_gen xxh3]
- json_serializable 6.7.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]

transitive dependencies:
- _fe_analyzer_shared 61.0.0 [meta]
- _flutterfire_internals 1.3.10 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 5.13.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.4.6 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- auto_size_text 3.0.0 [flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.1 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.2.11 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.6.3 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 3.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- code_builder 4.7.0 [built_collection built_value collection matcher meta]
- collection 1.17.2
- color 3.0.0
- convert 3.1.1 [typed_data]
- coverage 1.6.4 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.3+6 [js meta]
- crypto 3.0.3 [typed_data]
- csslib 0.17.3 [source_span]
- dart_style 2.3.2 [analyzer args path pub_semver source_span]
- dartx 1.2.0 [characters collection crypto meta path time]
- dbus 0.7.8 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.7.4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+4 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_app_check_platform_interface 0.1.0+4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.1.0+4 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_app_installations_platform_interface 0.1.4+10 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_installations_web 0.1.3+10 [_flutterfire_internals firebase_app_installations_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.10 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+10 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_in_app_messaging_platform_interface 0.2.4+9 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.11 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.11 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance_platform_interface 0.1.4+10 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.4+10 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]
- firebase_remote_config_platform_interface 1.4.10 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.4.10 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_gen_core 5.3.2 [path yaml mime xml dartx color collection json_annotation glob dart_style args pub_semver]
- flutter_inappwebview_internal_annotations 1.1.0
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_riverpod 2.4.4 [collection flutter meta riverpod state_notifier]
- flutter_secure_storage_linux 1.2.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.0.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.1.2 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 3.0.0 [ffi flutter flutter_secure_storage_platform_interface path path_provider win32]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- frontend_server_client 3.2.0 [async path]
- geolocator_android 4.3.1 [flutter geolocator_platform_interface uuid]
- geolocator_apple 2.3.2 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.1.1 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.2.0 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.2.2 [flutter geolocator_platform_interface]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.2.2 [js meta]
- google_sign_in_android 6.1.20 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.6.4 [flutter google_sign_in_platform_interface pigeon]
- google_sign_in_platform_interface 2.4.2 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.12.0+5 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http js]
- graphs 2.3.1 [collection]
- http 0.13.6 [async http_parser meta]
- http_multi_server 3.2.1 [async]
- image 4.1.3 [archive meta xml]
- image_picker_android 0.8.8+2 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.1 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.8+2 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.1 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- in_app_review_platform_interface 2.0.5 [flutter url_launcher plugin_platform_interface platform]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- lints 3.0.0
- list_counter 1.0.2
- local_auth_android 1.0.35 [flutter flutter_plugin_android_lifecycle intl local_auth_platform_interface]
- local_auth_ios 1.1.4 [flutter intl local_auth_platform_interface]
- local_auth_platform_interface 1.0.8 [flutter plugin_platform_interface]
- local_auth_windows 1.0.10 [flutter local_auth_platform_interface]
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- moengage_flutter_android 1.0.0 [flutter moengage_flutter_platform_interface]
- moengage_flutter_ios 1.0.0 [flutter moengage_flutter_platform_interface]
- moengage_flutter_platform_interface 1.0.0 [flutter plugin_platform_interface]
- moengage_flutter_web 2.0.0 [flutter flutter_web_plugins moengage_flutter_platform_interface]
- node_preamble 2.0.2
- octo_image 2.0.0 [flutter]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.1 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.1 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 10.3.6 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.1.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.12.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.3 [flutter permission_handler_platform_interface]
- petitparser 5.4.0 [meta]
- pigeon 11.0.1 [analyzer args collection meta path yaml]
- pin_input_text_field 4.5.1 [flutter]
- platform 3.1.3
- plugin_platform_interface 2.1.6 [meta]
- pool 1.5.1 [async stack_trace]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.1 [matcher]
- riverpod 2.4.4 [meta stack_trace state_notifier]
- rxdart 0.27.7
- share_plus_platform_interface 3.3.1 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.1 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.2 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.4.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_map_stack_trace 2.1.1 [path source_maps stack_trace]
- source_maps 0.10.12 [source_span]
- source_span 1.10.0 [collection path term_glyph]
- sqflite 2.3.0 [flutter sqflite_common path]
- sqflite_common 2.5.0 [synchronized path meta]
- stack_trace 1.11.0 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.1 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- syncfusion_flutter_core 20.4.54 [vector_math flutter]
- syncfusion_flutter_pdf 20.4.54 [flutter intl xml syncfusion_flutter_core crypto convert]
- syncfusion_pdfviewer_macos 20.4.54 [flutter syncfusion_pdfviewer_platform_interface]
- syncfusion_pdfviewer_platform_interface 20.4.54 [flutter plugin_platform_interface]
- syncfusion_pdfviewer_web 20.4.54 [flutter flutter_web_plugins js meta syncfusion_pdfviewer_platform_interface]
- syncfusion_pdfviewer_windows 20.4.54 [flutter]
- synchronized 3.1.0
- term_glyph 1.2.1
- test 1.24.3 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core matcher]
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- test_core 0.5.3 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml test_api]
- time 2.1.3 [clock]
- timezone 0.9.2 [path]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- uni_links_platform_interface 1.0.0 [flutter plugin_platform_interface]
- uni_links_web 0.1.0 [flutter flutter_web_plugins uni_links_platform_interface]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_android 6.2.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.0 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.2.0 [flutter plugin_platform_interface]
- url_launcher_web 2.2.0 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.1.0 [flutter url_launcher_platform_interface]
- uuid 3.0.7 [crypto]
- vector_graphics 1.1.9+1 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.9+1
- vector_graphics_compiler 1.1.9+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- vibration 1.8.3 [flutter device_info_plus]
- video_player 2.7.2 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.4.10 [flutter video_player_platform_interface]
- video_player_avfoundation 2.5.0 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.1 [flutter plugin_platform_interface]
- video_player_web 2.1.1 [flutter flutter_web_plugins video_player_platform_interface]
- vm_service 11.10.0
- watcher 1.1.0 [async path]
- web 0.1.4-beta
- web_socket_channel 2.4.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.2.1 [logging]
- win32 5.0.9 [ffi]
- win32_registry 1.1.2 [ffi win32]
- xdg_directories 1.0.3 [meta path]
- xml 6.3.0 [collection meta petitparser]
- xxh3 1.0.1
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>

---

**Comment by urvesh-sm** [comment]
@danagbemava-nc but this issue was fixed in `14.6.3` here: https://github.com/firebase/flutterfire/issues/11142

**Comment by urvesh-sm** [comment]
> Hi @urvesh-sm, can you try upgrading your flutterfire dependencies to the latest versions to see if you still experience this issue?

@danagbemava-nc but it was fixed in `14.6.4` here: https://github.com/firebase/flutterfire/issues/11142

**Comment by danagbemava-nc** [comment]
Hi @urvesh-sm, the stack traces for this and #11142 are different. That is a `NullPointerException` and this is a `BadParcelableException`

That aside, is your campaign sent from a backend or is it from the messaging dashboard?

**Comment by urvesh-sm** [comment]
> Hi @urvesh-sm, the stack traces for this and #11142 are different. That is a `NullPointerException` and this is a `BadParcelableException`
> 
> That aside, is your campaign sent from a backend or is it from the messaging dashboard?

@danagbemava-nc We are using Firebase Console and MoEngage for push notification campaigns. But mostly its from MoEngage.

**Comment by danagbemava-nc** [comment]
Hi @urvesh-sm, sorry for the late reply. What are the OS versions of the devices that are experiencing this issue?

**Comment by urvesh-sm** [comment]
> Hi @urvesh-sm, sorry for the late reply. What are the OS versions of the devices that are experiencing this issue?

@danagbemava-nc stats on firebase crashlytics says:
```
57% on samsung
74% on Android 13
71% in background
```

And another similar unmarshalling exception log says:
```
25% on samsung
40% on Android 11
58% in background
```

**Comment by danagbemava-nc** [comment]
Hi @urvesh-sm, approximately, how many users do you send it to before you get this crash? Are you able to reproduce it locally?

**Comment by urvesh-sm** [comment]
> Hi @urvesh-sm, approximately, how many users do you send it to before you get this crash? Are you able to reproduce it locally?

@danagbemava-nc it not happening on internal devices that we test on. We are sending it to around more than 6000 users

**Comment by danagbemava-nc** [comment]
Thanks for the info. 

Labeling for further investigation based on the information shared above. 

Similar to https://github.com/firebase/flutterfire/issues/11142

**Comment by felipecastrosales** [comment]
Hey, any news about it? This is one of the most relevant in my Crashlytics from my app. 

In Crashlytics:

```
Devices: 89% Samsung
SO 45%: Android 13
Device state: 94% in background
```

[# Crashlytics - Stack trace.txt](https://github.com/firebase/flutterfire/files/14297131/Crashlytics.-.Stack.trace.txt)

**Comment by TarekkMA** [comment]
From #13002
> @pamafe1976 If you are using progaurd can you confirm that you are using these settings https://github.com/firebase/flutterfire/issues/9884#issuecomment-1451022470 (for com.google.firebase.messaging.**)

**Comment by pamafe1976** [comment]
@TarekkMA I'm not currently using proguard in this app.

Regards

**Comment by Lyokone** [comment]
Closing since we have no response from the author of this issue. Considering this is an issue about Proguard.
