### ISSUE TITLE
🐛 [firestore_core] Error: [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff

### ISSUE THREAD

**Issue by arashgm** [firebase/flutterfire#11943]
## Bug report

**Describe the bug**
This is an old topic that happens time to time for lots of our users . there are some threads regarding this issue but almost all of them are not answered properly or closed.
I am facing this right now on iOS simulator but with the same branch, same network , same user , it does not happen for android or emulator.
if i wait for some seconds or retry multiple times, the app initialization passes successfully.
i tried different approach like disabling the localPersistance on the setting or chaning source on `GetOptions` of the `DocumentReference` but none of them works.
when i clear the state of the app and open the app again (for example on e2e test), same error throws.     

Error Log: 
```
flutter: [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
flutter: 	#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
flutter: 	#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
flutter: 	<asynchronous suspension>
flutter: 	#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:510:43)
flutter: 	<asynchronous suspension>
flutter: 	#3      MethodChannelDocumentReference.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_reference.dart:69:42)
flutter: 	<asynchronous suspension>
flutter: 	#4      _JsonDocumentReference.get (package:cloud_firestore/src/document_reference.dart:148:7)
```

### Expected behavior

This Error should not happen or provide more information from underlying Firebase SDK

## Additional context

Similar issues: 
https://stackoverflow.com/questions/64875445/this-is-a-most-likely-a-transient-condition-and-may-be-corrected-by-retrying-wit
https://github.com/firebase/firebase-android-sdk/issues/3624
https://github.com/firebase/flutterfire/discussions/5708

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

  firebase_core: ^2.16.0

---

**Comment by darshankawar** [comment]
@arashgm 
Looking at the error log and also described in various similar issues, it doesn't seem to be an issue with the plugin, as it seem to be throwing the exception correctly saying `cloud_firestore/unavailable`, ie the request coming from server itself and not when plugin is sending the data through Dart. 
I suggest you to reach out to firebase support for further resolution.

**Comment by arashgm** [comment]
@darshankawar if its Server/Network issue why it is only happening on iOS? i was testing at the same time on my Android and iOS device , i am monitoring this error for almost three years and i always see that on iOS fresh install.

**Comment by darshankawar** [comment]
Thanks for the update @arashgm 
I tried the plugin example for firebase_core and cloud_firestore using latest plugin versions and on iOS emulator + device, but wasn't able to replicate it as reported.
Can you provide us concrete steps to replicate or fixed pattern that leads to the said error ? that'll help to properly analyze it further.

**Comment by arashgm** [comment]
@darshankawar thanks for checking and your effort, the difficult part here is that our app is a really big flutter app and i cannot easily cherry-pick some part to reproduce the steps or sharing the code. like you, i also checked the firebase_core samples before and could not reproduce the issue. unfortunately its not even happening now on the same simulator on fresh install . so even by preparing a small app there is no guaranty that i can reproduce the issue cause it happens time to time and not always. i just wonder that if was possible that underlying iOS SDK could provide more information that what is really gone wrong other than saying that it is a transient issue and you need to try again. 

Honestly its like that firebase engineers expects this error but cannot do anything regarding that other than telling users to try again, by trying again definitly the data is fetched but its a bit late and cause bad user experience.

**Comment by darshankawar** [comment]
Thanks for your feedback @arashgm . I think it may be widespread issue and not specific to Flutter / flutterfire setup itself, as, flutterfire plugins are thin wrappers around native SDKs and sends, receives data through dart.
At client side (here, flutterfire), it seems to be properly catching the exception.



> i also checked the firebase_core samples before and could not reproduce the issue. unfortunately its not even happening now on the same simulator on fresh install . so even by preparing a small app there is no guaranty that i can reproduce the issue cause it happens time to time and not always. i just wonder that if was possible that underlying iOS SDK could provide more information that what is really gone wrong other than saying that it is a transient issue and you need to try again.

For this, I would suggest to reach out to Firebase support, since this seems to be intermittent and a fix doesn't seem to be in flutterfire's control.
