### ISSUE TITLE
🐛 [firebase_auth] Getting error when calling getRedirectResult on Web

### ISSUE THREAD

**Issue by amrgetment** [firebase/flutterfire#12023]
## Bug report

After using FirebaseAuth.instance.signInWithRedirect(googleProvider) in flutter web, when the signIn flow concludes, i was redirected to my app, when i try calling FirebaseAuth.instance.getRedirectResult(); I am getting the following error:

```
Error: Expected a value of type 'FutureOr', but got
one of type 'Null'
at Object.throw_ [as throw]
(http://localhost:38321/dart_sdk.js:5080:11)
at Object.castError (http://localhost:38321/dart_sdk.js:5039:15)
at Object.cast [as as] (http://localhost:38321/dart_sdk.js:5356:17)
at FutureOr.as_FutureOr (http://localhost:38321/dart_sdk.js:4683:21)
at _AsyncCompleter.new.complete
(http://localhost:38321/dart_sdk.js:35321:55)
at http://localhost:38321/dart_sdk.js:62418:96
```

This is the expected behavior? can't find clear documentation on this topic..

Running in debug mode.

### Steps to reproduce

1. Initialize firebase_core on main function
`await Firebase.initializeApp( options: [firebase_options],   );`
2. Call the `FirebaseAuth.instance.getRedirectResult()` on flutter web
`  final UserCredential userCredential = await FirebaseAuth.instance.getRedirectResult();`
3. See error or incorrect behavior

### Expected behavior

Retrieve UserCredential as expected or null without exception as it stops the app

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

  firebase_auth: ^4.15.0
  google_sign_in: ^6.2.0

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.1 23B74 darwin-x64, locale en-EG)
    • Flutter version 3.16.3 on channel stable at /Users/apple/.pvotal/flutter
    • Upstream repository ssh://git@github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (7 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10248

[✓] VS Code (version 1.85.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.71

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

---

### Minimal reproducible

<details><summary>Click To Expand</summary>

```

Bug report
After using FirebaseAuth.instance.signInWithRedirect(googleProvider) in flutter web, when the signIn flow concludes, i was redirected to my app, when i try calling FirebaseAuth.instance.getRedirectResult(); I am getting the following error:

Error: Expected a value of type 'FutureOr', but got
one of type 'Null'
at Object.throw_ [as throw]
(http://localhost:38321/dart_sdk.js:5080:11)
at Object.castError (http://localhost:38321/dart_sdk.js:5039:15)
at Object.cast [as as] (http://localhost:38321/dart_sdk.js:5356:17)
at FutureOr.as_FutureOr (http://localhost:38321/dart_sdk.js:4683:21)
at _AsyncCompleter.new.complete
(http://localhost:38321/dart_sdk.js:35321:55)
at http://localhost:38321/dart_sdk.js:62418:96

This is the expected behavior? can't find clear documentation on this topic..

Running in debug mode.

Steps to reproduce
Steps to reproduce the behavior:

Initialize firebase_core on main function
await Firebase.initializeApp( options: [firebase_options],   );
2 Call the FirebaseAuth.instance.getRedirectResult() on flutter web
  final UserCredential userCredential = await FirebaseAuth.instance.getRedirectResult();
See error or incorrect behavior
Expected behavior
Retrieve UserCredential as expected.

Additional context
firebase_core: ^1.20.0
firebase_auth: ^3.6.2
extension_google_sign_in_as_googleapis_auth: ^2.0.6

Flutter doctor
Click To Expand
Flutter dependencies
Click To Expand
Minimal reproducible
Click To Expand
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart';

void main() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  UserCredential userCredential =
      await FirebaseAuth.instance.getRedirectResult();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

---

**Comment by amrgetment** [comment]
@darshankawar it happened as I want the **new** sign in with redirect instead of a popup as some browsers blocks the popups
```
  final GoogleAuthProvider authProvider = GoogleAuthProvider();
  await firebaseAuth.signInWithRedirect(authProvider);

```
related issue, but it uses popup sign in
https://github.com/firebase/flutterfire/issues/9305

**Comment by darshankawar** [comment]
@amrgetment thanks for the report and potential fix.


> final GoogleAuthProvider authProvider = GoogleAuthProvider();
>   await firebaseAuth.signInWithRedirect(authProvider);

This seems to be working as expected.



> * Call the `FirebaseAuth.instance.getRedirectResult()` on flutter web
>   `  final UserCredential userCredential = await FirebaseAuth.instance.getRedirectResult();`

This is throwing the reported error.

**Comment by amrgetment** [comment]
@darshankawar I don’t know why any js error stops my app, either here or auto request notification in firebase messaging
I tried to add
```
try{
  final UserCredential userCredential = await FirebaseAuth.instance.getRedirectResult();
}on Exception catch(err){
}
```

but it still crash my Flutter web app
Any idea why js errors crash and stops my app?
