### ISSUE TITLE
🐛 [cloud_firestore] Fatal Exception: java.lang.OutOfMemory Error while doing firebase cloud_firestore operation

### ISSUE THREAD

**Issue by sumittiware** [firebase/flutterfire#12038]
## Bug report

**Describe the bug**
We have identify the Out Of Memory, while doing some cloud_firestore operation this is then leaving the local persistence in inconsistent state where it is not able to fetch the data next time fails the query, not even from the internet.

##Stacktrace
This is the associated stacktrace we have found on the Firebase Crashlytics.
```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 413616 free bytes and 403KB until OOM, target footprint 134217728, growth limit 134217728; giving up on allocation because <1% of heap free after GC.
       at java.util.LinkedHashMap.newNode(LinkedHashMap.java:280)
       at java.util.HashMap.putVal(HashMap.java:630)
       at java.util.HashMap.put(HashMap.java:611)
       at com.google.protobuf.MapFieldLite.put(MapFieldLite.java:96)
       at com.google.protobuf.MessageSchema.decodeMapEntry(MessageSchema.java:4494)
       at com.google.protobuf.MessageSchema.parseMapField(MessageSchema.java:4683)
       at com.google.protobuf.MessageSchema.parseProto3Message(MessageSchema.java:5439)
       at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:5481)
       at com.google.protobuf.ArrayDecoders.mergeMessageField(ArrayDecoders.java:271)
       at com.google.protobuf.MessageSchema.parseOneofField(MessageSchema.java:4784)
       at com.google.protobuf.MessageSchema.parseProto3Message(MessageSchema.java:5447)
       at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:5481)
       at com.google.protobuf.ArrayDecoders.mergeMessageField(ArrayDecoders.java:271)
       at com.google.protobuf.ArrayDecoders.decodeMessageField(ArrayDecoders.java:241)
       at com.google.protobuf.MessageSchema.decodeMapEntryValue(MessageSchema.java:4418)
       at com.google.protobuf.MessageSchema.decodeMapEntry(MessageSchema.java:4475)
       at com.google.protobuf.MessageSchema.parseMapField(MessageSchema.java:4683)
       at com.google.protobuf.MessageSchema.parseProto3Message(MessageSchema.java:5439)
       at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:5481)
       at com.google.protobuf.ArrayDecoders.mergeMessageField(ArrayDecoders.java:271)
       at com.google.protobuf.MessageSchema.parseOneofField(MessageSchema.java:4784)
       at com.google.protobuf.MessageSchema.parseProto3Message(MessageSchema.java:5447)
       at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:5481)
       at com.google.protobuf.ArrayDecoders.mergeMessageField(ArrayDecoders.java:271)
       at com.google.protobuf.ArrayDecoders.decodeMessageField(ArrayDecoders.java:241)
       at com.google.protobuf.MessageSchema.decodeMapEntryValue(MessageSchema.java:4418)
       at com.google.protobuf.MessageSchema.decodeMapEntry(MessageSchema.java:4475)
       at com.google.protobuf.MessageSchema.parseMapField(MessageSchema.java:4683)
       at com.google.protobuf.MessageSchema.parseProto3Message(MessageSchema.java:5439)
       at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:5481)
       at com.google.protobuf.ArrayDecoders.mergeMessageField(ArrayDecoders.java:271)
       at com.google.protobuf.MessageSchema.parseOneofField(MessageSchema.java:4784)
       at com.google.protobuf.MessageSchema.parseProto3Message(MessageSchema.java:5447)
       at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:5481)
       at com.google.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1673)
       at com.google.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1762)
       at com.google.firebase.firestore.proto.MaybeDocument.parseFrom(MaybeDocument.java:352)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.decodeMaybeDocument(SQLiteRemoteDocumentCache.java:289)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.lambda$processRowInBackground$2$com-google-firebase-firestore-local-SQLiteRemoteDocumentCache(SQLiteRemoteDocumentCache.java:256)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache$$ExternalSyntheticLambda3.run(:12)
       at com.google.firebase.firestore.util.BackgroundQueue.lambda$execute$0$com-google-firebase-firestore-util-BackgroundQueue(BackgroundQueue.java:39)
       at com.google.firebase.firestore.util.BackgroundQueue$$ExternalSyntheticLambda0.run(:4)
       at com.google.firebase.firestore.util.ThrottledForwardingExecutor.lambda$execute$0$com-google-firebase-firestore-util-ThrottledForwardingExecutor(ThrottledForwardingExecutor.java:54)
       at com.google.firebase.firestore.util.ThrottledForwardingExecutor$$ExternalSyntheticLambda0.run(:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```
### Steps to reproduce

I was able to reproduce the crash on IOS, I continuously used the debug app on IOS till it crash, now when I try to use the app after the crash it fails load the data the data from firestore. Couldn't get the local stack-trace as it was very obfuscated. 

### Expected behavior
---
This is the code responsible for fetching the data from the firestore

```
 static Future<QuerySnapshot<T>?> forceFetchDataFromCacheOrServer<T>({
    required Query<T> query,
    SourceType sourceType = SourceType.Server,
    VoidCallback? onFailedQuery,
  }) async {
    QuerySnapshot<T>? result;

    try {
      result = await query
          .get(
            const GetOptions(),
          )
          .timeout(
            const Duration(seconds: CLOUD_FIRESTORE_TIMEOUT), // 30 secs
          );
    } catch (e, stack) {
      recordPageMessageFetchingError(error: e, stack: stack);
      onFailedQuery?.call();
    }
    return result;
  }
```
Please help with this issue!

**Comment by darshankawar** [comment]
Thanks for the report @sumittiware 
Looking at the error log, it seems to be coming from native side as I don't see any client side plugin related entries in it.


> static Future<QuerySnapshot<T>?> forceFetchDataFromCacheOrServer<T>({

Is this client side method or native ? 



> state where it is not able to fetch the data next time fails the query, not even from the internet.

have you tried by passing the source parameter in this case, ie cache or server while using `get()` to check if doing this, the OOM error still occurs or not ?

**Comment by sumittiware** [comment]
Hi @darshankawar, thanks for the response

 static Future<QuerySnapshot<T>?> forceFetchDataFromCacheOrServer<T>({ this is the client side function created by us.
 
Yes, I have tried passing sourceType as server but still the plugin was not able to fetch the data even from server. It returned empty repsponse even when Internet was there and sourceType was set to Server.

It seems there is some issue with the data Persistance in the firebase library.

**Comment by sumittiware** [comment]
For now I have updated my client code to clear the persistence data if we get the empty response from firebase, 

```
 static Future<QuerySnapshot<T>?> forceFetchDataFromCacheOrServer<T>({
    required Query<T> query,
    SourceType sourceType = SourceType.Server,
    VoidCallback? onFailedQuery,
  }) async {
    QuerySnapshot<T>? result;

    try {
      result = await query.get().timeout(
            const Duration(seconds: CLOUD_FIRESTORE_TIMEOUT),
          );
    } catch (e, stack) {
      final ConnectivityResult connectivityResult =
          await Connectivity().checkConnectivity();

      if (connectivityResult != ConnectivityResult.none) {
        // If there is internet and we are still getting empty response
        // Then considering this as an error state where there is some issue
        // with Firebase Cache and clearing the persistance data in this case.
        await FirebaseFirestore.instance.clearPersistence();
      }
      recordPageMessageFetchingError(error: e, stack: stack);
      onFailedQuery?.call();
    }
    return result;
  }
```
We have observed that the cloud_firebase works properly when user logs out and login again as we clear the Persistance when user login.

Will that cause any issue, please help as we need to fix the issue for user.

**Comment by sumittiware** [comment]
Ohkk above code is not working, bad idea to clearPersistance() here as it is giving exception and rejecting the method, but I want some workaround this issue. Please help!

**Comment by darshankawar** [comment]
@sumittiware Thanks for the updates.
I tried with the plugin example running on iOS but wasn't able to replicate the exception and by following below details you mentioned.

> I continuously used the debug app on IOS till it crash, now when I try to use the app after the crash it fails load the data the data from firestore.


If you have concrete replicable pattern and reproducible code that we can use so as to make the issue actionable.

**Comment by russellwheatley** [comment]
@sumittiware - if you look at the stack trace, you will note it is coming entirely from the android Firebase SDK. It seems the data returned from the query is huge which is likely causing an out of memory exception, or there are possible memory leaks (possibly retaining large objects that aren't being disposed of). This isn't an issue with FlutterFire but rather the design of your application. I would profile your app to see where memory is being allocated. The quick solution might be to query for smaller amounts of data (e.g. paginate your data).
