### ISSUE TITLE
🐛 [firebase_app_check] Error returned from API. code: 403 body: App attestation failed. Since PlayStore removal

### ISSUE THREAD

**Issue by dario-digregorio** [firebase/flutterfire#12093]
## Bug report

**Describe the bug**
Yesterday my app got removed because a policy issue from the PlayStore (without a warning :/ ) and since then AppCheck is not working anymore when ever my app calls `await FirebaseAppCheck.instance.getToken()` I get `FirebaseException ([firebase_app_check/unknown] com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.)`. 
Since yesterday evening my app is available again in the Play Store but it is still not working. I checked the AppCheck Setup, GoogleService.json, the fingerprint but it is still not working. Even more strange is that users that have a older version of my app already, also have this problem.

I have no idea where this problems comes from and how to resolve it. It is working on iOS devices though. This is really hurting my small business and need to fix this issue quick. 
I tried to use different and newer versions of the Firebase Plugins and tried to renew the Google Service json. I checked the setup in Firebase and checked the fingerprints and AppID.

I am also using a flavored setup with internal and production environment. 

Firebase:
![image](https://github.com/firebase/flutterfire/assets/32966133/583d4313-e1ae-4277-aa4d-a47c0c761129)

Google Play Store:
![image](https://github.com/firebase/flutterfire/assets/32966133/97ddc1cf-781f-4ce6-a760-587355697370)

Google-Service.json
![image](https://github.com/firebase/flutterfire/assets/32966133/f67392f3-5b15-4308-8c38-2ef2bd3681e9)

Google Cloud:
![image](https://github.com/firebase/flutterfire/assets/32966133/5bc90fdd-e414-400c-888e-467d89e97bfe)

### Steps to reproduce

Not really clear to me how to reproduce, since it did not work for me from one day to another

### Expected behavior

AppCheck should work when it is configured right and did work before on older versions of the app.

---

## Additional context
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22631.2861], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
[!] Android Studio (version 2021.2)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.85.1)
[√] VS Code (version 1.75.0-insider)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.2.3
Flutter SDK 3.16.5
yawa 1.2.3+100495298

dependencies:
- auto_route 7.8.3 [flutter path collection meta]
- cached_network_image 3.3.0 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- cloud_firestore 4.12.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- collection 1.18.0
- device_preview 1.1.0 [flutter flutter_localizations provider device_frame freezed_annotation json_annotation shared_preferences collection]
- firebase_analytics 10.6.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check 0.2.1+2 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.12.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.20.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.4.2 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.4.2 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]    
- firebase_messaging 14.7.2 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.9.3+2 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_remote_config 4.3.2 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]        
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_displaymode 0.6.0 [flutter]
- flutter_icons 1.1.1-nullsafety.0 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- flutter_map 5.0.0 [async collection flutter http latlong2 meta polylabel proj4dart vector_math]
- flutter_map_marker_cluster 1.2.0 [flutter flutter_map flutter_map_marker_popup latlong2]
- flutter_reorderable_grid_view 4.0.0 [equatable flutter]
- flutter_riverpod 2.3.10 [collection flutter meta riverpod state_notifier]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- geolocator 9.0.2 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- google_fonts 6.1.0 [flutter http path_provider crypto]
- google_mobile_ads 3.0.0 [meta flutter visibility_detector webview_flutter_android webview_flutter_wkwebview webview_flutter]
- google_sign_in 6.1.5 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- http 1.1.0 [async http_parser meta]
- in_app_review 2.0.6 [flutter in_app_review_platform_interface]
- intl 0.18.1 [clock meta path]
- is_ios_app_on_mac 0.0.1+2 [flutter plugin_platform_interface]
- lat_lng_to_timezone 0.2.0
- latlong2 0.9.0 [intl]
- package_info_plus 4.1.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- purchases_flutter 5.8.0 [flutter freezed_annotation json_annotation]
- rainbow_color 2.0.1 [rainbow_vis flutter]
- rive 0.11.14 [collection flutter flutter_web_plugins http meta plugin_platform_interface rive_common]
- riverpod_annotation 2.1.4 [meta riverpod]
- sensors_plus 3.1.0 [flutter flutter_web_plugins sensors_plus_platform_interface]
- shared_preferences 2.2.1 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 3.0.0 [flutter]
- solar_calculator 1.0.3
- timezone 0.9.2 [path]
- units_converter 2.1.1
- url_launcher 6.1.12 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- auto_route_generator 7.3.1 [build source_gen analyzer path build_runner code_builder dart_style xml args glob auto_route]
- build_runner 2.4.6 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- custom_lint 0.4.0 [analyzer analyzer_plugin args async ci cli_util collection freezed_annotation json_annotation meta package_config path pub_semver pubspec_parse rxdart uuid yaml]
- envied_generator 0.3.0+3 [envied build source_gen analyzer]
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]
- freezed 2.4.1 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service async boolean_selector characters clock collection fake_async file matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math web webdriver]
- json_serializable 6.7.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- mockito 5.4.2 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- network_image_mock 2.1.1 [flutter mockito]
- riverpod_generator 2.2.4 [analyzer build build_config collection crypto meta path riverpod_analyzer_utils riverpod_annotation source_gen]
- riverpod_lint 1.4.0 [analyzer analyzer_plugin collection custom_lint_builder meta path riverpod riverpod_analyzer_utils source_span yaml]

transitive dependencies:
- _fe_analyzer_shared 60.0.0 [meta]
- _flutterfire_internals 1.3.10 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 5.12.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- analyzer_plugin 0.11.2 [analyzer collection dart_style pub_semver yaml]
- animated_stack_widget 0.0.4 [flutter]
- archive 3.3.7 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.2.1 [analyzer async build collection crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.2.10 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.6.2 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 3.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- ci 0.1.0
- cli_util 0.4.0 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 6.0.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.8.2 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]   
- code_builder 4.6.0 [built_collection built_value collection matcher meta]
- convert 3.1.1 [typed_data]
- crypto 3.0.3 [typed_data]
- custom_lint_builder 0.4.0 [analyzer analyzer_plugin collection custom_lint custom_lint_core glob hotreloader meta path pubspec_parse rxdart]
- custom_lint_core 0.4.0 [analyzer analyzer_plugin collection custom_lint matcher meta path pubspec_parse source_span yaml]
- dart_style 2.3.2 [analyzer args path pub_semver source_span]
- device_frame 1.1.0 [freezed_annotation flutter]
- envied 0.3.0+3
- equatable 2.0.5 [collection meta]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 6.1.4 [meta path]
- firebase_analytics_platform_interface 3.7.4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+4 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]      
- firebase_app_check_platform_interface 0.1.0+4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.1.0+4 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]      
- firebase_auth_platform_interface 7.0.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.8.5 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.10 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+10 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.11 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.11 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]  
- firebase_performance_platform_interface 0.1.4+10 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.4+10 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js] 
- firebase_remote_config_platform_interface 1.4.10 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.4.10 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- fixnum 1.1.0
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver async boolean_selector characters clock collection matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math web]
- flutter_map_marker_popup 5.2.0 [flutter animated_stack_widget flutter_map latlong2 provider]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- frontend_server_client 3.2.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- geolocator_android 4.2.2 [flutter geolocator_platform_interface uuid]
- geolocator_apple 2.2.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.7 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.6 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.3 [flutter geolocator_platform_interface]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.2.2 [js meta]
- google_sign_in_android 6.1.20 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.6.3 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.2 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.12.0+5 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http js]
- graphs 2.3.1 [collection]
- hotreloader 3.0.6 [collection logging path stream_transform vm_service watcher]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.0.17 [archive meta xml]
- in_app_review_platform_interface 2.0.4 [flutter url_launcher plugin_platform_interface platform]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- json_annotation 4.8.1 [meta]
- lints 2.1.1
- lists 1.0.1 [meta]
- logging 1.2.0
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.10.0
- mgrs_dart 2.0.0 [unicode]
- mime 1.0.4
- nested 1.0.0 [flutter]
- octo_image 2.0.0 [flutter]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.3
- path_provider 2.1.1 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.1.1 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.1 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.4.0 [meta]
- platform 3.1.2
- plugin_platform_interface 2.1.6 [meta]
- pointycastle 3.7.3 [collection convert js]
- polylabel 1.0.1 [collection]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- proj4dart 2.1.0 [mgrs_dart wkt_parser meta]
- provider 6.0.5 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.1 [matcher]
- rainbow_vis 2.0.0 [meta collection]
- rive_common 0.2.6 [collection ffi flutter flutter_web_plugins graphs http meta plugin_platform_interface]
- riverpod 2.3.10 [meta stack_trace state_notifier]
- riverpod_analyzer_utils 0.3.1 [analyzer collection crypto custom_lint_core freezed_annotation meta path source_span]
- rxdart 0.27.7
- sensors_plus_platform_interface 1.1.3 [flutter meta plugin_platform_interface]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.3 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.0 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.3.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.4.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- sqflite 2.3.0 [flutter sqflite_common path]
- sqflite_common 2.5.0 [synchronized path meta]
- stack_trace 1.11.1 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- sync_http 0.3.1
- synchronized 3.1.0
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- unicode 0.3.1 [lists]
- url_launcher_android 6.0.38 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.6 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.18 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.7 [flutter url_launcher_platform_interface]
- uuid 3.0.7 [crypto]
- vector_math 2.1.4
- visibility_detector 0.3.3 [flutter]
- vm_service 11.10.0
- watcher 1.1.0 [async path]
- web 0.3.0
- web_socket_channel 2.4.0 [async crypto stream_channel]
- webdriver 3.0.2 [matcher path stack_trace sync_http]
- webview_flutter 4.2.3 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 3.9.3 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.5.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.7.3 [flutter path webview_flutter_platform_interface]
- win32 5.0.7 [ffi]
- wkt_parser 2.0.0
- xdg_directories 1.0.2 [meta path]
- xml 6.3.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @dario-digregorio 
I ran the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_check/firebase_app_check/example) on Android emulator with which I didn't get the reported error. It printed the debug token in the console as expected.
Can you take a look at the example and check at your end ?

**Comment by dario-digregorio** [comment]
I can reproduce the error also on my physical iOS device now.
I also tried the example repo and replaced my Bundle Identifier used `flutterfire configure` to use my firebase configuration and appCheck and I still get this error. I used a physical iOS device this time:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_app_check/unknown] The operation couldn’t be completed. The server responded with an error: 
 - URL: https://firebaseappcheck.googleapis.com/v1/projects/yawa-d998b/apps/{{APP_ID}}:exchangeDebugToken 
 - HTTP status code: 403 
 - Response body: {
  "error": {
    "code": 403,
    "message": "App attestation failed.",
    "status": "PERMISSION_DENIED"
  }
}
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
<asynchronous suspension>
#2      MethodChannelFirebaseAppCheck.getToken (package:firebase_app_check_platform_interface/src/method_channel/method_channel_firebase_app_check.dart:100:22)
<asynchronous suspension>
#3      _FirebaseAppCheck.build.<anonymous closure> (package:firebase_app_check_example/main.dart:128:17)
<asynchronous suspension>
```

**Comment by darshankawar** [comment]
> Not sure why it is in German though.

this is strange. Maybe coming from server side and DeviceCheck itself.
Can you take a look at https://github.com/firebase/flutterfire/issues/10567#issuecomment-1460228453 and https://github.com/firebase/flutterfire/issues/10567#issuecomment-1464829706 to check if it helps in your case or not ?

**Comment by dario-digregorio** [comment]
I am currently writing with a firebase engineer and he suggested the same solution. Unfortunately without success.

**Comment by darshankawar** [comment]
@dario-digregorio 
Are you atleast getting the debug token back ? Can you check if [this](https://stackoverflow.com/a/71893942) helps in your case ?

**Comment by dario-digregorio** [comment]
I tried it on a physical iOS but unfortunately I do not get a Debug Token inside the debug console. I am not even sure if it is necessary or iOS.
I used also an physical Android Device where I get a debug token. I pasted it into the Firebase Console but I still get the error.

**Comment by darshankawar** [comment]
Check if [this](https://stackoverflow.com/a/74031767) helps in your case or not.

**Comment by LabN36** [comment]
I'm also facing the same issue, its not working at all no matter whatever solution I try.

**Comment by dario-digregorio** [comment]
I tried that already but for some reason I don't get the iOS Debug token printed to the console. On Android I get one and pasted it to the Firebase Console but unfortunately it did not work. Apart from that as far as I understand this would fix that I could use AppCheck in Debug but I also get errors when using it in production.

**Comment by dario-digregorio** [comment]
I tested it on the AppCheck example now and although I get a very similar error, a Debug Token gets printed to the console. And I also get a token although I get this error:
```bash
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_app_check/unknown] The operation couldn’t be completed. The server responded with an error: 
 - URL: https://firebaseappcheck.googleapis.com/v1/projects/{{PROJECT_ID}}/apps/{{APP_ID}}:exchangeDebugToken 
 - HTTP status code: 403 
 - Response body: {
  "error": {
    "code": 403,
    "message": "App attestation failed.",
    "status": "PERMISSION_DENIED"
  }
}
```

**Comment by russellwheatley** [comment]
@dario-digregorio - nothing has changed on FlutterFire that would break your app. It sounds to me that something in your configuration (through no fault of your own) isn't working anymore. I would go check every aspect of configuration required via documentation and ensure it is setup correctly on Firebase console/GCP.

**Comment by dario-digregorio** [comment]
Since even older deployed versions have stopped working, I came to the conclusion that it should be a bug. I will close this issue and will reopen it when I managed to create a  reproduceable repo. Thank you anyway for your time and effort!
