### ISSUE TITLE
🐛 [firebase_messaging] Native crash in Android for v14.7.10

### ISSUE THREAD

**Issue by aykutuludag** [firebase/flutterfire#12135]
## Bug report

**Describe the bug**
It doesn't ask notification permission (some device and Android versions) and getting crash in native code in Android. Normally it asks for both Android&iOS

### Steps to reproduce

Standart plugin implementation for Android. It crashed in native when I call  **firebaseRequestPermission()** which is in below.

```
initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Pass all uncaught "fatal" errors from the framework to Crashlytics
  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;
  FlutterError.onError = (errorDetails) {
    FirebaseCrashlytics.instance.recordFlutterFatalError(errorDetails);
  };
  // Pass all uncaught asynchronous errors that aren't handled by the Flutter framework to Crashlytics
  PlatformDispatcher.instance.onError = (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    return true;
  };

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  FirebaseAnalytics analytics = FirebaseAnalytics.instance;
  analytics.setAnalyticsCollectionEnabled(true);
}

void firebaseForegroundReceiver(BuildContext context) {
  FirebaseMessaging.onMessage.listen((RemoteMessage message) {
    print('Got a message whilst in the foreground!');
    print('Message data: ${message.data}');

    if (message.notification != null) {
      print('Message also contained a notification: ${message.notification}');
      sendNotification(context, message.notification!.body.toString());
    } else {
      sendNotification(context, message.data.toString());

      print(message.data);
    }
  });
}

Future<void> firebaseRequestPermission() async {
  FirebaseMessaging messaging = FirebaseMessaging.instance;
  await messaging.requestPermission(
    alert: true,
    announcement: true,
    badge: true,
    carPlay: false,
    criticalAlert: false,
    provisional: false,
    sound: true,
  );
}

@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
  await Firebase.initializeApp();

  print("Handling a background message: ${message.messageId}");
}
```

### Expected behavior

Working without problem

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22621.2861], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.25)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.79.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.2.0
Flutter SDK 3.16.0

dependencies:
- alarm 3.0.2 [flutter flutter_fgbg shared_preferences]
- app_tracking_transparency 2.0.4 [flutter]
- firebase_analytics 10.8.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.24.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.4.9 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 14.7.10 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_inappwebview 6.0.0 [flutter flutter_inappwebview_platform_interface flutter_inappwebview_android flutter_inappwebview_ios flutter_inappwebview_macos flutter_inappwebview_web]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- flutter_native_splash 2.3.9 [args flutter flutter_web_plugins js html image meta path universal_io xml yaml ansicolor]
- flutter_timezone 1.0.8 [flutter_web_plugins flutter js]
- fluttertoast 8.2.4 [flutter flutter_web_plugins]
- font_awesome_flutter 10.6.0 [flutter]
- google_fonts 6.1.0 [flutter http path_provider crypto]
- google_mobile_ads 4.0.0 [meta flutter webview_flutter_android webview_flutter_wkwebview webview_flutter]
- in_app_purchase 3.1.12 [flutter in_app_purchase_android in_app_purchase_platform_interface in_app_purchase_storekit]
- intl 0.18.1 [clock meta path]
- share_plus 7.2.1 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- simple_shadow 0.3.1 [flutter]
- url_launcher 6.2.2 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- flutter_lints 3.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]       

transitive dependencies:
- _flutterfire_internals 1.3.16 [collection firebase_core firebase_core_platform_interface flutter meta]
- ansicolor 2.0.2
- archive 3.4.10 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+8 [meta web]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 7.0.0 [meta path]
- firebase_analytics_platform_interface 3.9.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+12 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.10.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.16 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.18 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.18 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_fgbg 0.3.0 [flutter]
- flutter_inappwebview_android 1.0.12 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_internal_annotations 1.1.1
- flutter_inappwebview_ios 1.0.13 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_macos 1.0.11 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_platform_interface 1.0.10 [flutter flutter_inappwebview_internal_annotations plugin_platform_interface]
- flutter_inappwebview_web 1.0.8 [flutter flutter_web_plugins js flutter_inappwebview_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- html 0.15.4 [csslib source_span]
- http 1.1.2 [async http_parser meta web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.1.3 [archive meta xml]
- in_app_purchase_android 0.3.0+16 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_purchase_platform_interface 1.3.6 [flutter plugin_platform_interface]
- in_app_purchase_storekit 0.3.8 [collection flutter in_app_purchase_platform_interface json_annotation]
- js 0.6.7 [meta]
- json_annotation 4.8.1 [meta]
- lints 3.0.0
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.10.0
- mime 1.0.4
- path 1.8.3
- path_provider 2.1.1 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.1 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- petitparser 6.0.2 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.7.3 [collection convert js]
- share_plus_platform_interface 3.3.1 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_android 6.2.1 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.2 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.0 [flutter plugin_platform_interface]
- url_launcher_web 2.2.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- uuid 4.2.2 [crypto sprintf meta]
- vector_math 2.1.4
- web 0.3.0
- webview_flutter 4.4.3 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 3.13.2 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.9.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.10.1 [flutter path webview_flutter_platform_interface]
- win32 5.2.0 [ffi]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>

---
**PlatformException(error, Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference**

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
	at io.flutter.plugins.firebase.messaging.b.m(SourceFile:1)
	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.n(SourceFile:1)
	at io.flutter.plugins.firebase.messaging.e.onMethodCall(SourceFile:1)
	at i6.k$a.a(SourceFile:1)
	at a6.c.l(SourceFile:1)
	at a6.c.m(SourceFile:1)
	at a6.c.f(SourceFile:1)
	at a6.b.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:651)
       at MethodChannel._invokeMethod(platform_channel.dart:322)
       at MethodChannel.invokeMapMethod(platform_channel.dart:522)
       at MethodChannelFirebaseMessaging.registerBackgroundMessageHandler(method_channel_messaging.dart:202)
```
![image](https://github.com/firebase/flutterfire/assets/18382503/99ecb42d-d363-4239-adf0-c64257069c8e)

**Comment by aykutuludag** [comment]
Another bug:

![image](https://github.com/firebase/flutterfire/assets/18382503/8be463dc-de0d-4645-b6e6-efd7e85df442)

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: [firebase_messaging/unknown] Attempt to invoke virtual method 'int android.content.Context.checkSelfPermission(java.lang.String)' on a null object reference
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:651)
       at MethodChannel._invokeMethod(platform_channel.dart:322)
       at MethodChannel.invokeMapMethod(platform_channel.dart:522)
       at MethodChannelFirebaseMessaging.requestPermission(method_channel_messaging.dart:295)
       at .firebaseRequestPermission(firebase_utils.dart:52)
```

**Comment by darshankawar** [comment]
Thanks for the report @aykutuludag 
Can you take a look at [this](https://github.com/firebase/flutterfire/issues/10955#issuecomment-1549226973) and check if it helps in your case or not ?


> It doesn't ask notification permission (some device and Android versions)

See https://firebase.google.com/docs/cloud-messaging/flutter/receive which is applicable for Android 13 and newer and check if it helps or not.

**Comment by aykutuludag** [comment]
> [this](https://github.com/firebase/flutterfire/issues/10955#issuecomment-1549226973)

I don't think so because I downgrade to firebase messaging v14.7.4 now everything seems to working perfectly. There is no crash and it ask notification permission again. Problem is seems to be in v14.7.10

**Comment by darshankawar** [comment]
> Another bug in Android.

Please file a new issue for this so that we can track and address it separately.

**Comment by darshankawar** [comment]
I am unable to replicate the reported crash using the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) running on latest versions and on Android emulator, as it requested the permissions properly.  @aykutuludag  Can you use the same plugin example and check at your end if you still get the reported behavior ?

**Comment by kdrgrgn** [comment]
I'm having the same problem. Please help @aykutuludag  @darshankawar

**Comment by aykutuludag** [comment]
> I'm having the same problem. onBackgroundMessage is triggered when app is in foreground on android, then there is a crash Please help @aykutuludag @darshankawar

For now, I'm using 14.7.4 and there is no error. Just downgrade the plugin.

**Comment by darshankawar** [comment]
Thanks for the update. Based on the report and as I was unable to replicate it, keeping the issue open for team's attention / tracking.

**Comment by Lyokone** [comment]
Hello @aykutuludag, I've tried to reproduce on the latest version without success. Can you try to create a complete example that we could `git clone` easily to see what's going on.
You have a couple of other dependencies, and one of them might interact unexpectedly with messaging
