### ISSUE TITLE
🐛 [firebase_dynamic_links] FirebaseDynamicLinks.instance.buildShortLink() No response, No Errors.

### ISSUE THREAD

**Issue by azhon** [firebase/flutterfire#12152]
## Bug report

**Describe the bug**

`FirebaseDynamicLinks.instance.buildShortLink()` using Flutter, no response,no errors.
[as the same issues](https://github.com/firebase/flutterfire/issues/8881)

### Steps to reproduce

- Important!
Turn off Basic Google services in the settings, and my network cannot access Google.com (because I am in China), and then the above problem will occur.

- Phone Setting
<img width="360" alt="image" src="https://github.com/firebase/flutterfire/assets/20559556/dc6533b2-bf36-43ce-886b-6344112d1732">

### Expected behavior

Return a Dynamic Links

### Android Logcat

```
2024-01-12 16:46:40.691 23901-24056 GoogleApiManager com.odbpo.aaa   W  The service for com.google.firebase.dynamiclinks.internal.DynamicLinksClient is not available: ConnectionResult{statusCode=SERVICE_DISABLED, resolution=null, message=null}
2024-01-12 16:46:40.694 23901-24056 GoogleA...bility com.odbpo.aaa   W  GMS core API Availability. ConnectionResult=3, tag=null
                                                                           java.lang.IllegalArgumentException
                                                                           	at com.google.android.gms.common.GoogleApiAvailability.zae(com.google.android.gms:play-services-base@@18.0.1:2)
                                                                           	at com.google.android.gms.common.GoogleApiAvailability.zah(com.google.android.gms:play-services-base@@18.0.1:6)
                                                                           	at com.google.android.gms.common.api.internal.GoogleApiManager.zaG(com.google.android.gms:play-services-base@@18.0.1:1)
                                                                           	at com.google.android.gms.common.api.internal.zabq.zar(com.google.android.gms:play-services-base@@18.0.1:21)
                                                                           	at com.google.android.gms.common.api.internal.zabq.zao(com.google.android.gms:play-services-base@@18.0.1:13)
                                                                           	at com.google.android.gms.common.api.internal.zabq.zap(com.google.android.gms:play-services-base@@18.0.1:8)
                                                                           	at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(com.google.android.gms:play-services-base@@18.0.1:64)
                                                                           	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           	at android.os.Looper.loop(Looper.java:236)
                                                                           	at android.os.HandlerThread.run(HandlerThread.java:67)
2024-01-12 16:46:40.723 23901-23901 EgretLoader      com.odbpo.aaa   D  EgretLoader(Context context)
2024-01-12 16:46:40.723 23901-23901 EgretLoader      com.odbpo.aaa   D  The context is not activity
2024-01-12 16:46:40.736 23901-23901 Platfor...roller com.odbpo.aaa   I  Hosting view in view hierarchy for platform view: 3
2024-01-12 16:46:40.738 23901-23945 FrameEvents      com.odbpo.aaa   E  updateAcquireFence: Did not find frame.
2024-01-12 16:46:40.781 23901-23945 FrameEvents      com.odbpo.aaa   E  updateAcquireFence: Did not find frame.
2024-01-12 16:46:41.594 23901-23945 FrameEvents      com.odbpo.aaa   E  updateAcquireFence: Did not find frame.
2024-01-12 16:46:41.605 23901-23945 chatty           com.odbpo.aaa  I  uid=10498(com.odbpo.aaa) RenderThread identical 1 line
2024-01-12 16:46:41.627 23901-23945 FrameEvents      com.odbpo.aaa   E  updateAcquireFence: Did not find frame.
2024-01-12 16:46:49.620 23901-23945 FrameEvents      com.odbpo.aaa   E  updateAcquireFence: Did not find frame.

```
### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---
## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.13.0, on macOS 12.5 21G72 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.5)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
firebase_core: ^2.24.2
firebase_analytics: ^10.7.4
firebase_dynamic_links: ^5.4.8
```

</details>

---

**Comment by darshankawar** [comment]
@azhon 
The Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

More at [firebase.google.com/support/dynamic-links-faq](https://firebase.google.com/support/dynamic-links-faq)
Closing based on it.
