### ISSUE TITLE
🐛 [firebase_storage] Disable plugin-internal logging

### ISSUE THREAD

**Issue by Lootwig** [firebase/flutterfire#12161]
Calling `Reference.getDownloadUrl()` on a non-existing object results in the attached output on the console.

While the devs of the Android SDK might consider this useful information for their work, none of this is relevant for consumers of the SDK - in fact, the ONE thing that would be useful - the actual path of the missing object - is not even mentioned and not even included in the exception that is thrown **in addition** to this output.

Instead, the exception has to be caught and manually paired with the reference whose `.getDownloadUrl()` call threw it.

```
E/StorageException(31113): StorageException has occurred.
E/StorageException(31113): Object does not exist at location.
E/StorageException(31113):  Code: -13010 HttpResult: 404
E/StorageException(31113): Not Found
E/StorageException(31113): java.io.IOException: Not Found
E/StorageException(31113): 	at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:415)
E/StorageException(31113): 	at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(NetworkRequest.java:432)
E/StorageException(31113): 	at com.google.firebase.storage.network.NetworkRequest.processResponseStream(NetworkRequest.java:423)
E/StorageException(31113): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:265)
E/StorageException(31113): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:282)
E/StorageException(31113): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:76)
E/StorageException(31113): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:68)
E/StorageException(31113): 	at com.google.firebase.storage.GetDownloadUrlTask.run(GetDownloadUrlTask.java:77)
E/StorageException(31113): 	at com.google.firebase.concurrent.LimitedConcurrencyExecutor.lambda$decorate$0$com-google-firebase-concurrent-LimitedConcurrencyExecutor(LimitedConcurrencyExecutor.java:65)
E/StorageException(31113): 	at com.google.firebase.concurrent.LimitedConcurrencyExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/StorageException(31113): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/StorageException(31113): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/StorageException(31113): 	at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory(CustomThreadFactory.java:47)
E/StorageException(31113): 	at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/StorageException(31113): 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by darshankawar** [comment]
@Lootwig 
Can you take a look at [this](https://github.com/firebase/flutterfire/issues/7474) issue and see if it resembles your case and can be followed-up in ?

**Comment by Lootwig** [comment]
@darshankawar it does not, the exceptions aren't thrown in dart, but that's where the SDK is imported from, so consumers should be provided with a way to reduce the log clutter from the indirect dependency

**Comment by Lyokone** [comment]
I've managed to reproduce the issue. it seems that logcat logs are added to the ouput only using Android Studio (I don't see any native logs using Terminal or VSCode). 

It appears that we cannot prevent those logs from our side. You can try to open an issue on Firebase Android SDK repository or try to configure your Logcat output.
