### ISSUE TITLE
🐛 [flutter_core] Android release build crashing at startup

### ISSUE THREAD

**Issue by abhibhaw** [firebase/flutterfire#12181]
## Bug report

**Describe the bug**
I'm trying flutter mobile otp authentication, I'm using the packages   firebase_auth: ^4.16.0, firebase_core: ^2.24.2. Debug build is working fine but release build is breaking at startup with logs:
```
E/AndroidRuntime(15264): FATAL EXCEPTION: pool-2-thread-4
E/AndroidRuntime(15264): Process: com.gepton.milkton_executive, PID: 15264
E/AndroidRuntime(15264): java.lang.IllegalAccessError: Field 'com.google.firebase.concurrent.ExecutorsRegistrar.a' is inaccessible to class 'W.k' (declaration of 'W.k' appears in /data/app/~~HOuSAXvYvBkPgub-Ke2NvQ==/com.gepton.milkton_executive-qrPzhF6mQywW2cyOPZ-Yyg==/base.apk)
E/AndroidRuntime(15264):        at W.k.a(Unknown Source:0)
E/AndroidRuntime(15264):        at I.j.get(Unknown Source:16)
E/AndroidRuntime(15264):        at I.x.get(Unknown Source:13)
E/AndroidRuntime(15264):        at I.p.e(Unknown Source:8)
E/AndroidRuntime(15264):        at I.F.e(Unknown Source:10)
E/AndroidRuntime(15264):        at com.google.firebase.auth.FirebaseAuthRegistrar.lambda$getComponents$0(Unknown Source:50)
E/AndroidRuntime(15264):        at com.google.firebase.auth.h0.a(Unknown Source:11)
E/AndroidRuntime(15264):        at I.j.get(Unknown Source:16)
E/AndroidRuntime(15264):        at I.x.get(Unknown Source:13)
E/AndroidRuntime(15264):        at I.p.e(Unknown Source:8)
E/AndroidRuntime(15264):        at I.p.a(Unknown Source:4)
E/AndroidRuntime(15264):        at D.i.i(Unknown Source:7)
E/AndroidRuntime(15264):        at com.google.firebase.auth.FirebaseAuth.getInstance(Unknown Source:0)
E/AndroidRuntime(15264):        at k0.l.i(Unknown Source:5)
E/AndroidRuntime(15264):        at T.f.run(Unknown Source:26)
E/AndroidRuntime(15264):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime(15264):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime(15264):        at java.lang.Thread.run(Thread.java:1012)
```
Have tried nearly everything to debug, been stuck here since last 15 days.

### Steps to reproduce

1. Run `flutter clean`
2. Run `flutter run --release`
3. App will crash on startup with error: `java.lang.IllegalAccessError: Field 'com.google.firebase.concurrent.ExecutorsRegistrar.a' is inaccessible to class 'W.k'`

### Expected behavior

App should start and authentication should work

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.7, on macOS 14.2.1 23C71 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.2.4
Flutter SDK 3.16.7
milkton_executive 5.0.0+50

dependencies:
- cupertino_icons 1.0.6
- firebase_auth 4.16.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.24.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_bloc 8.1.3 [bloc flutter provider]
- flutter_svg 2.0.9 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- google_fonts 6.1.0 [flutter http path_provider crypto]
- graphql_flutter 5.2.0-beta.6 [graphql gql_exec flutter meta path_provider path connectivity_plus hive plugin_platform_interface flutter_hooks]
- intl 0.19.0 [clock meta path]
- package_info_plus 5.0.1 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32]

dev dependencies:
- flutter_lints 3.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

transitive dependencies:
- _flutterfire_internals 1.3.16 [collection firebase_core firebase_core_platform_interface flutter meta]
- args 2.4.2
- async 2.11.0 [collection meta]
- bloc 8.1.2 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- connectivity_plus 5.0.2 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- crypto 3.0.3 [typed_data]
- dbus 0.7.10 [args ffi meta xml]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- firebase_auth_platform_interface 7.0.9 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.8.13 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.10.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.1.0
- flutter_hooks 0.20.4 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- gql 1.0.1-alpha+1705114622973 [collection meta source_span yaml]
- gql_dedupe_link 2.0.4-alpha+1705114623057 [async gql_exec gql_link meta]
- gql_error_link 1.0.0+1 [async gql_exec gql_link meta]
- gql_exec 1.1.1-alpha+1699813812660 [collection gql meta]
- gql_http_link 1.0.1+1 [gql gql_exec gql_link http http_parser meta]
- gql_link 1.0.1-alpha+1705114622987 [gql gql_exec meta]
- gql_transform_link 1.0.0 [gql_exec gql_link]
- graphql 5.2.0-beta.7 [meta path gql gql_exec gql_link gql_http_link gql_transform_link gql_error_link gql_dedupe_link hive normalize http collection web_socket_channel stream_channel rxdart uuid]
- hive 2.2.3 [meta crypto]
- http 1.1.2 [async http_parser meta web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- lints 3.0.0
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.10.0
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- normalize 0.8.2+1 [gql collection]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.3
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.1.1 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.1 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.1 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- petitparser 6.0.2 [meta]
- platform 3.1.3
- plugin_platform_interface 2.1.7 [meta]
- provider 6.1.1 [collection flutter nested]
- rxdart 0.27.7
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- uuid 4.3.3 [crypto sprintf meta fixnum]
- vector_graphics 1.1.9+1 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.9+1
- vector_graphics_compiler 1.1.9+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- web 0.3.0
- web_socket_channel 2.4.0 [async crypto stream_channel]
- win32 5.1.1 [ffi]
- xdg_directories 1.0.3 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>

---

**Comment by abhibhaw** [comment]
I don't know how but it got fixed :)

**Comment by Exnonull** [comment]
💀 i got same bug with firebase_auth: ^4.2.2 and firebase_core: ^2.4.1

```
E/AndroidRuntime(30210): FATAL EXCEPTION: pool-21-thread-4
E/AndroidRuntime(30210): Process: org.nfound, PID: 30210
E/AndroidRuntime(30210): java.lang.IllegalAccessError: Field 'com.google.firebase.concurrent.ExecutorsRegistrar.a' is inaccessible to class 'A0.i' (declaration of 'A0.i' appears in base.apk)
E/AndroidRuntime(30210):        at A0.i.c(Unknown Source:0)
E/AndroidRuntime(30210):        at E2.j.get(Unknown Source:16)
E/AndroidRuntime(30210):        at E2.z.get(Unknown Source:13)
E/AndroidRuntime(30210):        at E2.p.a(Unknown Source:8)
E/AndroidRuntime(30210):        at E2.H.a(Unknown Source:10)
E/AndroidRuntime(30210):        at com.google.firebase.auth.FirebaseAuthRegistrar.lambda$getComponents$0(Unknown Source:50)
E/AndroidRuntime(30210):        at com.google.firebase.auth.l0.c(Unknown Source:11)
E/AndroidRuntime(30210):        at E2.j.get(Unknown Source:16)
E/AndroidRuntime(30210):        at E2.z.get(Unknown Source:13)
E/AndroidRuntime(30210):        at E2.p.a(Unknown Source:8)
E/AndroidRuntime(30210):        at E2.p.get(Unknown Source:4)
E/AndroidRuntime(30210):        at y2.i.i(Unknown Source:5)
E/AndroidRuntime(30210):        at com.google.firebase.auth.FirebaseAuth.getInstance(Unknown Source:2)
E/AndroidRuntime(30210):        at B4.o.e(Unknown Source:5)
E/AndroidRuntime(30210):        at k0.N.run(SourceFile:23)
E/AndroidRuntime(30210):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(30210):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(30210):        at java.lang.Thread.run(Thread.java:919)
```

<details><summary>Flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.8, on Microsoft Windows [Version 10.0.19045.3930], locale ru-RU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.29)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.85.2)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>
<details><summary>Flutter dependencies</summary>

```
Dart SDK 3.2.5
Flutter SDK 3.16.8
NFound 1.9.0+81

dependencies:
- all_sensors 0.4.2 [flutter]
- android_id 0.3.6 [flutter]
- app_tracking_transparency 2.0.4 [flutter]
- audio_session 0.1.18 [flutter flutter_web_plugins rxdart meta]
- audio_waveforms 1.0.4 [flutter]
- audioplayers 5.2.1 [audioplayers_android audioplayers_darwin audioplayers_linux audioplayers_platform_interface audioplayers_web audioplayers_windows file flutter http meta path_provider synchronized uuid]
- card_swiper 3.0.1 [flutter]
- collection 1.18.0
- connectivity_plus 5.0.2 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- contacts_service 0.6.3 [flutter collection quiver]
- crypto 3.0.3 [typed_data]
- cupertino_http 1.3.0 [async ffi flutter http]
- device_info_plus 9.1.1 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- dotted_border 2.1.0 [flutter path_drawing]
- firebase_auth 4.16.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.24.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.7.10 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_app_badger 1.5.0 [flutter]
- flutter_callkit_incoming 2.0.1+2 [flutter json_annotation]
- flutter_exif_rotation 0.5.1 [flutter]
- flutter_facebook_auth 6.0.4 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_html 3.0.0-beta.2 [html csslib collection list_counter flutter]
- flutter_linkify 6.0.0 [flutter linkify]
- flutter_local_notifications 16.3.2 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_ringtone_player 4.0.0+2 [flutter flutter_lints path_provider plugin_platform_interface]
- flutter_sound 9.2.13 [path_provider recase uuid provider path synchronized logger flutter flutter_sound_platform_interface flutter_sound_web]
- flutter_svg 2.0.9 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_typeahead 5.0.2 [flutter flutter_keyboard_visibility pointer_interceptor]
- flutter_webrtc 0.9.47 [collection dart_webrtc flutter path_provider webrtc_interface]
- geolocator 10.1.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- google_maps_flutter 2.5.3 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface google_maps_flutter_web]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- http 1.2.0 [async http_parser meta web]
- huge_listview 2.0.11 [flutter quiver scrollable_positioned_list]
- image 4.1.4 [archive meta xml]
- image_cropper 5.0.1 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_picker 1.0.7 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- intl 0.18.1 [clock meta path]
- just_the_tooltip 0.0.12 [flutter]
- localstorage 4.0.1+4 [flutter path_provider]
- location 5.0.3 [flutter location_platform_interface location_web]
- logger 1.4.0
- package_info_plus 5.0.1 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32]
- pay 1.1.2 [flutter flutter_localizations pay_android pay_ios pay_platform_interface meta]
- permission_handler 11.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- photo_view 0.14.0 [flutter]
- pin_code_fields 8.0.1 [flutter]
- qr_code_scanner 1.0.1 [js flutter flutter_web_plugins]
- qr_flutter 4.1.0 [flutter qr]
- screenshot 2.1.0 [flutter]
- share_plus 7.2.1 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- sign_in_with_apple 5.0.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sms_mms 0.0.2+1 [flutter flutter_web_plugins plugin_platform_interface]
- uni_links 0.5.1 [flutter uni_links_platform_interface uni_links_web]
- upgrader 9.0.0 [flutter device_info_plus html http os_detect package_info_plus shared_preferences url_launcher version xml]
- url_launcher 6.2.4 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- wakelock_plus 1.1.4 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus js]
- web_socket_channel 2.4.0 [async crypto stream_channel]

dev dependencies:
- flutter_lints 3.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

transitive dependencies:
- _flutterfire_internals 1.3.16 [collection firebase_core firebase_core_platform_interface flutter meta]
- archive 3.4.10 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- audioplayers_android 4.0.3 [audioplayers_platform_interface flutter]
- audioplayers_darwin 5.0.2 [audioplayers_platform_interface flutter]
- audioplayers_linux 3.1.0 [audioplayers_platform_interface flutter]
- audioplayers_platform_interface 6.1.0 [flutter meta plugin_platform_interface]
- audioplayers_web 4.1.0 [audioplayers_platform_interface flutter flutter_web_plugins js]
- audioplayers_windows 3.1.0 [audioplayers_platform_interface flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+8 [meta web]
- csslib 0.17.3 [source_span]
- dart_webrtc 1.1.3 [collection js platform_detect webrtc_interface]
- dbus 0.7.10 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_auth_platform_interface 7.0.9 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.8.13 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.10.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 4.5.18 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.18 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_facebook_auth_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 5.0.0 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_sound_platform_interface 9.2.13 [flutter meta plugin_platform_interface logger]
- flutter_sound_web 9.2.13 [flutter_sound_platform_interface flutter logger flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- geolocator_android 4.3.1 [flutter geolocator_platform_interface uuid]
- geolocator_apple 2.3.5 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.0 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.2.0 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.2.2 [flutter geolocator_platform_interface]
- google_identity_services_web 0.3.0+2 [meta web]
- google_maps 6.3.0 [js js_wrapping meta]
- google_maps_flutter_android 2.6.2 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.4.1 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.4.3 [collection flutter plugin_platform_interface stream_transform]
- google_maps_flutter_web 0.5.4+3 [collection flutter flutter_web_plugins google_maps google_maps_flutter_platform_interface sanitize_html stream_transform]
- google_sign_in_android 6.1.21 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.3 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.3+2 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- html 0.15.4 [csslib source_span]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_cropper_for_web 3.0.0 [flutter flutter_web_plugins image_cropper_platform_interface js]
- image_cropper_platform_interface 5.0.0 [flutter plugin_platform_interface http]
- image_picker_android 0.8.9+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.2 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.9+1 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.3 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- js 0.6.7 [meta]
- js_wrapping 0.7.4 [js]
- json_annotation 4.8.1 [meta]
- linkify 5.0.0
- lints 3.0.0
- list_counter 1.0.2
- location_platform_interface 3.1.2 [flutter plugin_platform_interface]
- location_web 4.2.0 [flutter flutter_web_plugins http_parser js location_platform_interface]
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.10.0
- mime 1.0.4
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- os_detect 2.0.1
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.3
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- pay_android 1.0.11 [flutter flutter_localizations pay_platform_interface flutter_svg]
- pay_ios 1.0.11 [flutter pay_platform_interface]
- pay_platform_interface 1.0.4 [flutter yaml]
- permission_handler_android 12.0.3 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.3.0 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.1 [flutter flutter_web_plugins permission_handler_platform_interface]
- permission_handler_platform_interface 4.1.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.4
- platform_detect 2.0.11 [meta pub_semver]
- plugin_platform_interface 2.1.8 [meta]
- pointer_interceptor 0.10.1 [flutter flutter_web_plugins pointer_interceptor_ios pointer_interceptor_platform_interface pointer_interceptor_web]
- pointer_interceptor_ios 0.10.0+2 [flutter plugin_platform_interface pointer_interceptor_platform_interface]
- pointer_interceptor_platform_interface 0.10.0+1 [flutter plugin_platform_interface]
- pointer_interceptor_web 0.10.1+2 [flutter flutter_web_plugins plugin_platform_interface pointer_interceptor_platform_interface web]
- pointycastle 3.7.4 [collection convert js]
- provider 6.1.1 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- qr 3.0.1 [meta]
- quiver 3.2.1 [matcher]
- recase 4.1.0
- rxdart 0.27.7
- sanitize_html 2.1.0 [html meta]
- scrollable_positioned_list 0.3.8 [flutter collection]
- share_plus_platform_interface 3.3.1 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.5 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.9.2 [path]
- typed_data 1.3.2 [collection]
- uni_links_platform_interface 1.0.0 [flutter plugin_platform_interface]
- uni_links_web 0.1.0 [flutter flutter_web_plugins uni_links_platform_interface]
- url_launcher_android 6.2.2 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.1 [flutter plugin_platform_interface]
- url_launcher_web 2.2.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- uuid 3.0.7 [crypto]
- vector_graphics 1.1.9+2 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.9+2
- vector_graphics_compiler 1.1.9+2 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- version 3.0.2
- wakelock_plus_platform_interface 1.1.0 [flutter plugin_platform_interface meta]
- web 0.3.0
- webrtc_interface 1.1.2
- win32 5.2.0 [ffi]
- win32_registry 1.1.2 [ffi win32]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>

**Comment by Exnonull** [comment]
> 💀 i got same bug with firebase_auth: ^4.2.2 and firebase_core: ^2.4.1
> 
> ```
> E/AndroidRuntime(30210): FATAL EXCEPTION: pool-21-thread-4
> E/AndroidRuntime(30210): Process: org.nfound, PID: 30210
> E/AndroidRuntime(30210): java.lang.IllegalAccessError: Field 'com.google.firebase.concurrent.ExecutorsRegistrar.a' is inaccessible to class 'A0.i' (declaration of 'A0.i' appears in base.apk)
> E/AndroidRuntime(30210):        at A0.i.c(Unknown Source:0)
> E/AndroidRuntime(30210):        at E2.j.get(Unknown Source:16)
> E/AndroidRuntime(30210):        at E2.z.get(Unknown Source:13)
> E/AndroidRuntime(30210):        at E2.p.a(Unknown Source:8)
> E/AndroidRuntime(30210):        at E2.H.a(Unknown Source:10)
> E/AndroidRuntime(30210):        at com.google.firebase.auth.FirebaseAuthRegistrar.lambda$getComponents$0(Unknown Source:50)
> E/AndroidRuntime(30210):        at com.google.firebase.auth.l0.c(Unknown Source:11)
> E/AndroidRuntime(30210):        at E2.j.get(Unknown Source:16)
> E/AndroidRuntime(30210):        at E2.z.get(Unknown Source:13)
> E/AndroidRuntime(30210):        at E2.p.a(Unknown Source:8)
> E/AndroidRuntime(30210):        at E2.p.get(Unknown Source:4)
> E/AndroidRuntime(30210):        at y2.i.i(Unknown Source:5)
> E/AndroidRuntime(30210):        at com.google.firebase.auth.FirebaseAuth.getInstance(Unknown Source:2)
> E/AndroidRuntime(30210):        at B4.o.e(Unknown Source:5)
> E/AndroidRuntime(30210):        at k0.N.run(SourceFile:23)
> E/AndroidRuntime(30210):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> E/AndroidRuntime(30210):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> E/AndroidRuntime(30210):        at java.lang.Thread.run(Thread.java:919)
> ```
> 
> Flutter doctor
> Flutter dependencies

uh, it somehow fixed with https://github.com/firebase/flutterfire/issues/6681#issuecomment-885936163 but i don't sure about it's correct way to solve it

**Comment by Exnonull** [comment]
ok, i came to solution by adding

```
-keep class com.google.firebase.concurrent.** { *; }
```

to `proguard-rules.pro` file to disable obfuscation/minification on this class
was inspired by this https://github.com/firebase/flutterfire/issues/9884#issuecomment-1451022470

i don't sure why it required for me now, but i guess it somehow may be related to flutter upgrade, because firebase version did not changed since previous success builds (month passed).

**Comment by Exnonull** [comment]
after reinstalling android studio + flutter and playing a lot with gradle, kotlin, AGP, Java versions i understood something and this error was solved without anything.

if someone interested my current setup is:
```
Java 11 (because of gradle < 8)
gradle 7.5.1
AGP 7.3.1
google-services 4.3.15

desugar_jdk_libs 1.2.2
compiler/target version 34
multiDexEnabled, minifyEnabled, shrinkResources is true

Latest:
Android Studio (hedgehog)
flutter (3.16.9)
dart (3.2.6)
kotlin (1.9.22)
```

but i have a lot of other "incompatible version of Kotlin" errors that happens for me with most plugins even if i run examples of these plugins since android 14 was released.
