### ISSUE TITLE
Unable to start receiver io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver: java.lang.SecurityException: Not allowed to start service Intent

### ISSUE THREAD

**Issue by Jai05-techie** [firebase/flutterfire#12197]
Hello team,

The latest release of my app is experiencing crashes, and Firebase Crashlytics is reporting a security exception. This issue is specifically occurring on Android OS 10.

Below are the details
```
Flutter SDK: 3.13.9
firebase_messaging: ^14.7.10
dependencies:
implementation 'com.google.firebase:firebase-messaging:23.4.0'
```
<img width="567" alt="Screenshot 2024-01-25 at 12 19 33 PM" src="https://github.com/firebase/flutterfire/assets/62050139/4bb64065-f6cc-46db-8e36-8f5185c82d5c">

```
Fatal Exception: java.lang.RuntimeException
Unable to start receiver io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver: java.lang.SecurityException: Not allowed to start service Intent { cmp=com.myapplication/io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService (has extras) } without permission Background bind not allowed


Fatal Exception: java.lang.RuntimeException: Unable to start receiver io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver: java.lang.SecurityException: Not allowed to start service Intent { cmp=com.myapplication/io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService (has extras) } without permission Background bind not allowed
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3860)
       at android.app.ActivityThread.access$1500(ActivityThread.java:230)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1930)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:232)
       at android.app.ActivityThread.main(ActivityThread.java:7441)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

**Comment by darshankawar** [comment]
Do you have proper permissions configured in your manifest ?
`<uses-permission`
This again could be related to native Android sdk.


> implementation 'com.google.firebase:firebase-messaging:23.4.0'

If you lower the version, can you confirm if the same exception occurs or not ?
