### ISSUE TITLE
Fatal Exception: java.lang.SecurityException Not allowed to bind to service Intent

### ISSUE THREAD

**Issue by Jai05-techie** [firebase/flutterfire#12196]
Hello team, 

The latest release of my app is experiencing crashes, and Firebase Crashlytics is reporting a security exception. This issue is specifically occurring on Android OS 10. 

**Below are the details**

```
Flutter SDK: 3.13.9
firebase_messaging: ^14.7.10
dependencies:
implementation 'com.google.firebase:firebase-messaging:23.4.0'
```
<img width="542" alt="Screenshot 2024-01-25 at 12 01 34 PM" src="https://github.com/firebase/flutterfire/assets/62050139/f5bcd869-b6be-435d-a971-ca53e833ec07">

```
Fatal Exception: java.lang.SecurityException
Not allowed to bind to service Intent { act=9013 cmp=com.myapplication/com.google.firebase.sessions.SessionLifecycleService (has extras) }


Fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent { act=9013 cmp=com.myapplication/com.google.firebase.sessions.SessionLifecycleService (has extras) }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1741)
       at android.app.ContextImpl.bindService(ContextImpl.java:1651)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
       at com.google.firebase.sessions.SessionLifecycleServiceBinderImpl.bindToService(:52)
       at com.google.firebase.sessions.SessionLifecycleClient.bindToService(:20)
       at com.google.firebase.sessions.FirebaseSessions$1.invokeSuspend(FirebaseSessions.java:136)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:11)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:93)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:12)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by darshankawar** [comment]
@Jai05-techie 
Looking at the logs, they seem to be coming from native android sdk and not from flutterfire. In order to properly analyze the issue, we need a reproducible code sample that triggers such exception. Without it, we will not be able to make this issue actionable. Or you may also file the issue in native android firebase sdk.
