### ISSUE TITLE
🐛 [`cloud_firestore`] You cannot use `not_in` filters with `in` filters

### ISSUE THREAD

**Issue by Levi-Lesches** [firebase/flutterfire#12211]
## Bug report

Using `whereNotIn` with a `whereIn` query results in an error, [as it should](https://firebase.google.com/docs/firestore/query-data/queries#limitations_2). 

But the SDK/plugin itself can't handle this error gracefully, and asks me to report it.

<details><summary>Logs</summary>

```
E/FLTFirestoreMsgCodec(13711): An error occurred while parsing query arguments, this is most likely an error with this SDK.
E/FLTFirestoreMsgCodec(13711): java.lang.IllegalArgumentException: Invalid Query. You cannot use 'not_in' filters with 'in' filters.
E/FLTFirestoreMsgCodec(13711): 	at com.google.firebase.firestore.Query.validateNewFieldFilter(Query.java:583)
E/FLTFirestoreMsgCodec(13711): 	at com.google.firebase.firestore.Query.validateNewFilter(Query.java:593)
E/FLTFirestoreMsgCodec(13711): 	at com.google.firebase.firestore.Query.where(Query.java:405)
E/FLTFirestoreMsgCodec(13711): 	at com.google.firebase.firestore.Query.whereNotIn(Query.java:389)
E/FLTFirestoreMsgCodec(13711): 	at io.flutter.plugins.firebase.firestore.utils.PigeonParser.parseQuery(PigeonParser.java:204)
E/FLTFirestoreMsgCodec(13711): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin.lambda$queryGet$16(FlutterFirebaseFirestorePlugin.java:712)
E/FLTFirestoreMsgCodec(13711): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin$$ExternalSyntheticLambda12.run(Unknown Source:12)
E/FLTFirestoreMsgCodec(13711): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/FLTFirestoreMsgCodec(13711): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/FLTFirestoreMsgCodec(13711): 	at java.lang.Thread.run(Thread.java:1012)

E/flutter (13711): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [cloud_firestore/unknown] An error occurred while parsing query arguments, see native logs for more information. Please report this issue.
E/flutter (13711): #0      FirebaseFirestoreHostApi.queryGet (package:cloud_firestore_platform_interface/src/pigeon/messages.pigeon.dart:1130:7)
E/flutter (13711): <asynchronous suspension>
E/flutter (13711): #1      MethodChannelQuery.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_query.dart:118:11)
E/flutter (13711): <asynchronous suspension>
E/flutter (13711): #2      _JsonQuery.get (package:cloud_firestore/src/query.dart:436:9)
E/flutter (13711): <asynchronous suspension>
E/flutter (13711): #3      _WithConverterQuery.get (package:cloud_firestore/src/query.dart:991:22)
E/flutter (13711): <asynchronous suspension>
E/flutter (13711): #4      _extension#1.getAll (package:channil/src/services/database.dart:20:29)
E/flutter (13711): <asynchronous suspension>
E/flutter (13711): #5      BrowseViewModel.loadMoreUsers (package:channil/src/models/view/browse.dart:28:23)
E/flutter (13711): <asynchronous suspension>
E/flutter (13711): #6      BrowseViewModel.nextUser (package:channil/src/models/view/browse.dart:44:12)
E/flutter (13711): <asynchronous suspension>
E/flutter (13711): 
```
</details>

### Steps to reproduce

```dart
void getItems() => firestore.collection("data")
  .where("field", whereIn: ["a", "b"]),
  .where("field", whereNotIn: ["a", "b"]);
```

### Expected behavior

I suppose this should still be an error, but it should be caught by the Dart side of the plugin.

### Sample project

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
What would you like me to do? flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22631.3085], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.7.1)
[✓] Android Studio (version 2022.3)
[✓] VS Code, 64-bit edition (version 1.85.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
What would you like me to do? flutter pub deps -- --style=compact
Dart SDK 3.2.3
Flutter SDK 3.16.5
channil 1.0.0+1

dependencies:
- cloud_firestore 4.14.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- file_picker 6.1.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_auth 4.16.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.24.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 11.6.0 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- go_router 13.0.1 [collection flutter flutter_web_plugins logging meta]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- google_sign_in_web 0.12.3+2 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]
- very_good_analysis 5.1.0

transitive dependencies:
- _flutterfire_internals 1.3.16 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 6.1.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.9.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- firebase_auth_platform_interface 7.0.9 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.8.13 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.10.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 5.1.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.6.17 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- google_identity_services_web 0.3.0+2 [meta web]
- google_sign_in_android 6.1.21 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.3 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- http 1.2.0 [async http_parser meta web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- logging 1.2.0
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.10.0
- path 1.8.3
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- web 0.3.0
- win32 5.2.0 [ffi]
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @Levi-Lesches 
I am unable to replicate the reported error. Can you provide the database structure and the platform on which you are seeing the error ?

**Comment by Levi-Lesches** [comment]
I can't test on mobile right now, but here's the behavior I'm going for: 

![image](https://github.com/firebase/flutterfire/assets/20747538/3b270493-c05e-4546-8210-be920005f875)

```dart
Future<void> main() async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  final firestore = FirebaseFirestore.instance;
  final collection = firestore.collection("test1");
  final query = collection
    .where("a", whereIn: ["a", "b", "c"])
    .where("b", whereNotIn: ["x", "y", "z"]);
  final snapshot = await query.get();
  final data = snapshot.docs.first.data();
  runApp(TestApp(data));
}

class TestApp extends StatelessWidget {
  final Object data;
  const TestApp(this.data);

  @override
  Widget build(BuildContext context) => MaterialApp(
    home: Scaffold(
      body: Center(
        child: Text("Data is: $data"),
      ),
    ),
  );
}
```

On Web, for example, this results in: 
```
FirebaseError: Invalid query. You cannot use 'not-in' filters with 'in' filters.
```

On Android this should give the error noted above, but I can confirm again tonight when I'm back at my desk.

**Comment by darshankawar** [comment]
Thanks for the update. I was able to replicate this on Android, but not on web. I get below results:

1. Android:

```
Performing hot restart...
Syncing files to device sdk gphone64 x86 64...
Restarted application in 2,790ms.
E/FLTFirestoreMsgCodec( 9050): An error occurred while parsing query arguments, this is most likely an error with this SDK.
E/FLTFirestoreMsgCodec( 9050): java.lang.IllegalArgumentException: Invalid Query. You cannot use 'not_in' filters with 'in' filters.
E/FLTFirestoreMsgCodec( 9050): 	at com.google.firebase.firestore.Query.validateNewFieldFilter(Query.java:583)
E/FLTFirestoreMsgCodec( 9050): 	at com.google.firebase.firestore.Query.validateNewFilter(Query.java:593)
E/FLTFirestoreMsgCodec( 9050): 	at com.google.firebase.firestore.Query.where(Query.java:405)
E/FLTFirestoreMsgCodec( 9050): 	at com.google.firebase.firestore.Query.whereNotIn(Query.java:389)
E/FLTFirestoreMsgCodec( 9050): 	at io.flutter.plugins.firebase.firestore.utils.PigeonParser.parseQuery(PigeonParser.java:204)
E/FLTFirestoreMsgCodec( 9050): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin.lambda$queryGet$16(FlutterFirebaseFirestorePlugin.java:712)
E/FLTFirestoreMsgCodec( 9050): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin$$ExternalSyntheticLambda8.run(Unknown Source:12)
E/FLTFirestoreMsgCodec( 9050): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/FLTFirestoreMsgCodec( 9050): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/FLTFirestoreMsgCodec( 9050): 	at java.lang.Thread.run(Thread.java:1012)
W/DynamiteModule( 9050): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
E/flutter ( 9050): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [cloud_firestore/unknown] An error occurred while parsing query arguments, see native logs for more information. Please report this issue.
E/flutter ( 9050): #0      FirebaseFirestoreHostApi.queryGet (package:cloud_firestore_platform_interface/src/pigeon/messages.pigeon.dart:1130:7)
E/flutter ( 9050): <asynchronous suspension>
E/flutter ( 9050): #1      MethodChannelQuery.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_query.dart:118:11)
E/flutter ( 9050): <asynchronous suspension>
E/flutter ( 9050): #2      _JsonQuery.get (package:cloud_firestore/src/query.dart:436:9)
E/flutter ( 9050): <asynchronous suspension>
E/flutter ( 9050): #3      main (package:triage/main.dart:446:20)
E/flutter ( 9050): <asynchronous suspension>
E/flutter ( 9050): 
```

2. Web:

`FirebaseError: Invalid query. You cannot use 'not-in' filters with 'in' filters.`
