### ISSUE TITLE
[firebase_auth] App crash when use linkWithCredential method

### ISSUE THREAD

**Issue by hoangminhhung-addx** [firebase/flutterfire#12358]
## Bug report

Hi Firebase team

I am using Facebook Authentication to get access token and link via Firebase auth, but got crash 
```
  flutter_facebook_auth: 6.0.4
  firebase_auth: 4.16.0
  firebase_core: 2.24.2
  firebase_core_platform_interface: 5.0.0
  firebase_crashlytics: 3.4.9
  firebase_analytics: 10.8.0
  firebase_dynamic_links: 5.4.8
  firebase_messaging: 14.7.10
  firebase_performance: 0.9.3+8
  firebase_auth_platform_interface: 7.0.9
  firebase_auth_web: 5.8.13
  firebase_app_check: 0.2.1+8
  firebase_storage: 11.6.0
```

This is code
```
final facebookResult = await FacebookAuth.instance.login();
if (facebookResult.status == LoginStatus.success) {
      final facebookCredential = FacebookAuthProvider.credential(facebookResult.accessToken!.token);
      userCredential = await FirebaseAuth.instance.currentUser?.linkWithCredential(facebookCredential);
}
```
        
This is logs crash at line linkWithCredential
```
E/AndroidRuntime(22207): FATAL EXCEPTION: Firebase Blocking Thread #0
E/AndroidRuntime(22207): Process: *.dev, PID: 22207
E/AndroidRuntime(22207): java.lang.IllegalArgumentException: Given String is empty or null
E/AndroidRuntime(22207): 	at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(com.google.android.gms:play-services-basement@@18.2.0:2)
E/AndroidRuntime(22207): 	at com.google.android.gms.internal.firebase-auth-api.zzafa.<init>(com.google.firebase:firebase-auth@@22.3.0:5)
E/AndroidRuntime(22207): 	at com.google.android.gms.internal.firebase-auth-api.zzyj.zza(com.google.firebase:firebase-auth@@22.3.0:116)
E/AndroidRuntime(22207): 	at com.google.android.gms.internal.firebase-auth-api.zzyj.zza(com.google.firebase:firebase-auth@@22.3.0:20)
E/AndroidRuntime(22207): 	at com.google.android.gms.internal.firebase-auth-api.zzzg.zza(com.google.firebase:firebase-auth@@22.3.0:5)
E/AndroidRuntime(22207): 	at com.google.android.gms.internal.firebase-auth-api.zzadn.zza(com.google.firebase:firebase-auth@@22.3.0:20)
E/AndroidRuntime(22207): 	at com.google.android.gms.internal.firebase-auth-api.zzadn.zza(com.google.firebase:firebase-auth@@22.3.0:64)
E/AndroidRuntime(22207): 	at com.google.android.gms.internal.firebase-auth-api.zzacu.zza(com.google.firebase:firebase-auth@@22.3.0:164)
E/AndroidRuntime(22207): 	at com.google.android.gms.internal.firebase-auth-api.zzzd.zza(com.google.firebase:firebase-auth@@22.3.0:9)
E/AndroidRuntime(22207): 	at com.google.android.gms.internal.firebase-auth-api.zzyj.zza(com.google.firebase:firebase-auth@@22.3.0:90)
E/AndroidRuntime(22207): 	at com.google.android.gms.internal.firebase-auth-api.zzyj.zza(com.google.firebase:firebase-auth@@22.3.0:145)
E/AndroidRuntime(22207): 	at com.google.android.gms.internal.firebase-auth-api.zzacg.zza(com.google.firebase:firebase-auth@@22.3.0:115)
E/AndroidRuntime(22207): 	at com.google.android.gms.internal.firebase-auth-api.zzaat.zza(com.google.firebase:firebase-auth@@22.3.0:15)
E/AndroidRuntime(22207): 	at com.google.android.gms.internal.firebase-auth-api.zzadg.run(com.google.firebase:firebase-auth@@22.3.0:2)
E/AndroidRuntime(22207): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime(22207): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime(22207): 	at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory(CustomThreadFactory.java:47)
E/AndroidRuntime(22207): 	at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/AndroidRuntime(22207): 	at java.lang.Thread.run(Thread.java:1012)
```

Hope to hear team reply soon. Thanks a lot

**Comment by darshankawar** [comment]
Thanks for the report @hoangminhhung-addx 
I tried below code sample with which I was unable to replicate the reported error:

```
Future<void> _signInWithGoogle() async {
    // Trigger the authentication flow
    final googleUser = await GoogleSignIn().signIn();

    // Obtain the auth details from the request
    final googleAuth = await googleUser?.authentication;

    if (googleAuth != null) {
      // Create a new credential
      final credential = GoogleAuthProvider.credential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );

      // Once signed in, return the UserCredential
      final userCredential = await auth.signInWithCredential(credential);

      final emailCredential = EmailAuthProvider.credential(
        email: '',
        password: '',
      );
      await userCredential.user?.linkWithCredential(emailCredential);
    }
  }
```

Can you upgrade to latest auth plugin version and other related plugins to make sure you are on greatest version and try again ?
You can also use the [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example) and check at your end if you still get same error or not.

I also noticed that you are using specific version of the plugins, and not using ^.

**Comment by hoangminhhung-addx** [comment]
Hi @darshankawar , thanks u. it works

**Comment by darshankawar** [comment]
Closing as resolved.
