### ISSUE TITLE
🐛 [firebase_database] Uncaught MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)

### ISSUE THREAD

**Issue by ahmed-raza-92** [firebase/flutterfire#12380]
## Bug report

**Describe the bug**
I am using realtime database in my flutter app using firebase_database. I am running my app on local it's running okay but when it deploy it on firebase hosting and try to run it, it shows this error.

## Additional context

Uncaught MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)
    at Object.c (https://trivia-262f8.web.app/main.dart.js:4371:19)
    at https://trivia-262f8.web.app/main.dart.js:78941:15
    at aDA.a (https://trivia-262f8.web.app/main.dart.js:5720:62)
    at aDA.$2 (https://trivia-262f8.web.app/main.dart.js:42124:14)
    at aCM.$1 (https://trivia-262f8.web.app/main.dart.js:42118:21)
    at azs.awb (https://trivia-262f8.web.app/main.dart.js:43054:34)
    at azs.xu (https://trivia-262f8.web.app/main.dart.js:43056:21)
    at aw8.$0 (https://trivia-262f8.web.app/main.dart.js:42552:11)
    at Object.yT (https://trivia-262f8.web.app/main.dart.js:5860:40)
    at ac.oa (https://trivia-262f8.web.app/main.dart.js:42487:3)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[!] Flutter (Channel stable, 3.16.5, on macOS 14.0 23A344 darwin-arm64, locale en-PK)
    • Flutter version 3.16.5 on channel stable at /Users/ahmed/development/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.7/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/ahmed/development/flutter. Consider adding /Users/ahmed/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (9 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use “git” directly to perform update checks and upgrades.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ahmed/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
[✓] Connected device (3 available)
    • Ahmed (mobile)  • 00008110-00163D242E6B801E • ios            • iOS 17.3.1 21D61
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 122.0.6261.57
    ! Device adb-4XDEXOM78DLZ59TS-nQRLEm._adb-tls-connect._tcp. is offline.
[✓] Network resources
    • All expected network resources are available.
! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 3.2.3
Flutter SDK 3.16.5
thumbsi_admin 1.0.0+1

dependencies:
- carousel_slider 4.2.1 [flutter]
- cloud_firestore 4.15.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.6
- date_time_picker 2.1.0 [flutter intl]
- equatable 2.0.5 [collection meta]
- file_picker 6.1.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_auth 4.16.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.25.4 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_database 10.4.6 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_storage 11.6.2 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_bloc 8.1.3 [bloc flutter provider]
- fluttertoast 8.2.4 [flutter flutter_web_plugins]
- google_fonts 6.1.0 [flutter http path_provider crypto]
- http 1.2.0 [async http_parser meta web]
- lottie 3.0.0 [archive flutter path vector_math]
- utility_extensions 0.0.10 [flutter]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

transitive dependencies:
- _flutterfire_internals 1.3.22 [collection firebase_core firebase_core_platform_interface flutter meta]
- archive 3.4.10 [crypto path pointycastle]
- async 2.11.0 [collection meta]
- bloc 8.1.2 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 6.1.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.10.1 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.18.0
- convert 3.1.1 [typed_data]
- crypto 3.0.3 [typed_data]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- firebase_auth_platform_interface 7.0.9 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.8.13 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.11.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- firebase_database_platform_interface 0.2.5+22 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.3+22 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_storage_platform_interface 5.1.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.6.19 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.7 [meta]
- lints 2.1.1
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.10.0
- nested 1.0.0 [flutter]
- path 1.8.3
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.7.4 [collection convert js]
- provider 6.1.1 [collection flutter nested]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- web 0.3.0
- win32 5.2.0 [ffi]
- xdg_directories 1.0.4 [meta path]

```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @ahmed-raza-92, I just deployed the firebase_database example app to firebase hosting and it works just fine for me.

Can you try running `flutter clean && flutter pub get` before you build the app for the web? 

Can you also upgrade to the latest version of flutter stable to see if you still experience this issue?

**Comment by ahmed-raza-92** [comment]
Hi @danagbemava-nc Thanks for your quick response. Sure I will do that and let you know the results in a while
