### ISSUE TITLE
🐛 [firebase_core_web] Build error with flutter version 3.19.1

### ISSUE THREAD

**Issue by thomas4Bitcraft** [firebase/flutterfire#12407]
## Bug report

I use the following package versions in flutter

```
  firebase_core: ^2.25.4
  firebase_analytics: ^10.8.6
  firebase_messaging: ^14.7.16
```

Since flutter 3.19.1 the build `flutter build web` fails with the following error. Is there a way to build a web application with the latest flutter version and firebase?

```
../../.pub-cache/hosted/pub.dev/firebase_core_web-2.11.5/lib/src/interop/package_web_tweaks.dart:19:12: Error: Type 'web.TrustedTypePolicyFactory' not found.
  external web.TrustedTypePolicyFactory? get nullableTrustedTypes;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/firebase_core_web-2.11.5/lib/src/interop/package_web_tweaks.dart:24:41: Error: Type 'web.TrustedTypePolicy' not found.
extension CreateScriptUrlWithoutArgs on web.TrustedTypePolicy {
                                        ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/firebase_core_web-2.11.5/lib/src/interop/package_web_tweaks.dart:27:12: Error: Type 'web.TrustedScriptURL' not found.
  external web.TrustedScriptURL createScriptURLNoArgs(
           ^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/firebase_core_web-2.11.5/lib/src/interop/package_web_tweaks.dart:36:30: Error: Type 'web.TrustedScript' not found.
  external set trustedScript(web.TrustedScript value);
                             ^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/firebase_core_web-2.11.5/lib/src/firebase_core_web.dart:119:19: Error: 'TrustedTypePolicy' isn't a type.
        final web.TrustedTypePolicy policy =
                  ^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/firebase_core_web-2.11.5/lib/src/firebase_core_web.dart:122:15: Error: Method not found: 'TrustedTypePolicyOptions'.
          web.TrustedTypePolicyOptions(
              ^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/firebase_core_web-2.11.5/lib/src/firebase_core_web.dart:120:24: Error: The getter 'trustedTypes' isn't defined for the class 'Window'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'trustedTypes'.
            web.window.trustedTypes.createPolicy(
                       ^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/firebase_core_web-2.11.5/lib/src/interop/package_web_tweaks.dart:36:34: Error: 'TrustedScript' isn't a type.
  external set trustedScript(web.TrustedScript value);
                                 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/firebase_core_web-2.11.5/lib/src/interop/package_web_tweaks.dart:19:46: Error: Type 'invalid-type' is not a valid type in the signature of `dart:js_interop` external APIs or APIs converted via `toJS`. The only valid types are: JS types from `dart:js_interop`, @staticInterop types, void, bool, num, double, int, String, extension types that erases to one of these types, or a type parameter that is bound to a static interop type.
Use one of the valid types instead.
  external web.TrustedTypePolicyFactory? get nullableTrustedTypes;
                                             ^
../../.pub-cache/hosted/pub.dev/firebase_core_web-2.11.5/lib/src/interop/package_web_tweaks.dart:27:33: Error: JS interop or Native class required for 'external' extension members.
Try adding a JS interop annotation to the on type class of the extension.
  external web.TrustedScriptURL createScriptURLNoArgs(
                                ^
../../.pub-cache/hosted/pub.dev/firebase_core_web-2.11.5/lib/src/interop/package_web_tweaks.dart:36:16: Error: Type 'invalid-type' is not a valid type in the signature of `dart:js_interop` external APIs or APIs converted via `toJS`. The only valid types are: JS types from `dart:js_interop`, @staticInterop types, void, bool, num, double, int, String, extension types that erases to one of these types, or a type parameter that is bound to a static interop type.
Use one of the valid types instead.
  external set trustedScript(web.TrustedScript value);
               ^
Unhandled exception:
Unsupported operation: Unsupported invalid type InvalidType(<invalid>) (InvalidType). Encountered while compiling file:///Users/thomasbrandauer/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.5/lib/src/interop/package_web_tweaks.dart, which contains the type: FunctionType(<invalid> Function(String)).
#0      ProgramCompiler._typeCompilationError (package:dev_compiler/src/kernel/compiler.dart:3678)
#1      ProgramCompiler._newEmitType (package:dev_compiler/src/kernel/compiler.dart:3471)
#2      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:3379)
#3      ProgramCompiler.visitFunctionType (package:dev_compiler/src/kernel/compiler.dart:3731)
#4      ProgramCompiler._emitFunctionTagged (package:dev_compiler/src/kernel/compiler.dart:3307)
#5      ProgramCompiler.visitFunctionExpression (package:dev_compiler/src/kernel/compiler.dart:7573)
#6      FunctionExpression.accept (package:kernel/ast.dart:8606)
#7      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#8      ProgramCompiler.visitReturnStatement (package:dev_compiler/src/kernel/compiler.dart:5182)
#9      ReturnStatement.accept (package:kernel/ast.dart:10159)
#10     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:4520)
#11     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:4553)
#12     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:4259)
#13     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2829)
#14     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:4296)
#15     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:4255)
#16     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:4060)
#17     ProgramCompiler._emitLibraryFunction (package:dev_compiler/src/kernel/compiler.dart:3262)
#18     MappedIterator.moveNext (dart:_internal/iterable.dart:403)
#19     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202)
#20     new _GrowableList.of (dart:core-patch/growable_array.dart:152)
#21     new List.of (dart:core-patch/array_patch.dart:39)
#22     Iterable.toList (dart:core/iterable.dart:497)
#23     ProgramCompiler._emitLibraryProcedures (package:dev_compiler/src/kernel/compiler.dart:3188)
#24     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:785)
#25     List.forEach (dart:core-patch/growable_array.dart:416)
#26     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:505)
#27     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:223)
#28     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:794)
<asynchronous suspension>
#29     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:654)
<asynchronous suspension>
#30     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1303)
<asynchronous suspension>
Finished with error: the Dart compiler exited unexpectedly.
Failed to compile application.
```

**Comment by russellwheatley** [comment]
Run `flutter pub upgrade`, it will fix this issue 👍

**Comment by thomas4Bitcraft** [comment]
@russellwheatley I have done that, but the issue still persists. I have these dependency_overrides, can they cause this issue?

```
dependency_overrides:
  win32: ^5.2.0
  js: ^0.7.1
  flutter_layout_grid: ^2.0.5
  intl: ^0.19.0
  web: ^0.5.0
```

**Comment by miphik** [comment]
the same problem @russellwheatley could you please reopen this issue?

**Comment by thomas4Bitcraft** [comment]
@russellwheatley I also checked out the current master branch using

  ```
firebase_core_web:
    git:
      url: https://github.com/firebase/flutterfire.git
      ref: master
      path: packages/firebase_core/firebase_core_web
```

but the error still persists.

**Comment by russellwheatley** [comment]
@thomas4Bitcraft - This is an issue with your setup. It might be the dependency overrides.

I just ran:
```bash
flutter create test_web_upgrade
flutter pub add firebase_core firebase_messaging firebase_analytics

```
Imported core, analytics and messaging into project.

Ran:
```
flutter pub get
flutter build web
```
It worked.
