### ISSUE TITLE
🐛 Cloud Firestore crashes the app due to SQLite storage lock in offline mode

### ISSUE THREAD

**Issue by bitex39** [firebase/flutterfire#12403]
```
E/SQLiteLog(26300): (5) database is locked in "PRAGMA journal_mode"
E/SQLiteDatabase(26300): Failed to open database '/data/user/0/com.iustitia.greenmining/databases/firestore.%5BDEFAULT%5D.ius-greenmining.%28default%29'.
E/SQLiteDatabase(26300): android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY[5]): , while compiling: PRAGMA journal_mode
E/SQLiteDatabase(26300): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/SQLiteDatabase(26300): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1505)
E/SQLiteDatabase(26300): 	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:1092)
E/SQLiteDatabase(26300): 	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:639)
E/SQLiteDatabase(26300): 	at android.database.sqlite.SQLiteConnection.setJournalFromConfiguration(SQLiteConnection.java:546)
E/SQLiteDatabase(26300): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:402)
E/SQLiteDatabase(26300): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:226)
E/SQLiteDatabase(26300): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:743)
E/SQLiteDatabase(26300): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:288)
E/SQLiteDatabase(26300): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:255)
E/SQLiteDatabase(26300): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1581)
E/SQLiteDatabase(26300): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1522)
E/SQLiteDatabase(26300): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1163)
E/SQLiteDatabase(26300): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:470)
E/SQLiteDatabase(26300): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:413)
E/SQLiteDatabase(26300): 	at com.google.firebase.firestore.local.SQLitePersistence.start(SQLitePersistence.java:138)
E/SQLiteDatabase(26300): 	at com.google.firebase.firestore.core.ComponentProvider.initialize(ComponentProvider.java:150)
E/SQLiteDatabase(26300): 	at com.google.firebase.firestore.core.FirestoreClient.initialize(FirestoreClient.java:296)
E/SQLiteDatabase(26300): 	at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0$com-google-firebase-firestore-core-FirestoreClient(FirestoreClient.java:114)
E/SQLiteDatabase(26300): 	at com.google.firebase.firestore.core.FirestoreClient$$ExternalSyntheticLambda14.run(Unknown Source:8)
E/SQLiteDatabase(26300): 	at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:444)
E/SQLiteDatabase(26300): 	at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda0.call(Unknown Source:2)
E/SQLiteDatabase(26300): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:330)
E/SQLiteDatabase(26300): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$ExternalSyntheticLambda2.run(Unknown Source:4)
E/SQLiteDatabase(26300): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
E/SQLiteDatabase(26300): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/SQLiteDatabase(26300): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
E/SQLiteDatabase(26300): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/SQLiteDatabase(26300): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/SQLiteDatabase(26300): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
E/SQLiteDatabase(26300): 	at java.lang.Thread.run(Thread.java:1012)
D/AndroidRuntime(26300): Shutting down VM
E/AndroidRuntime(26300): FATAL EXCEPTION: main
E/AndroidRuntime(26300): Process: com.iustitia.greenmining, PID: 26300
E/AndroidRuntime(26300): java.lang.RuntimeException: Internal error in Cloud Firestore (24.10.1).
E/AndroidRuntime(26300): 	at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:545)
E/AndroidRuntime(26300): 	at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda6.run(Unknown Source:2)
E/AndroidRuntime(26300): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(26300): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26300): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(26300): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(26300): 	at android.app.ActivityThread.main(ActivityThread.java:8741)
E/AndroidRuntime(26300): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26300): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(26300): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(26300): Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to gain exclusive lock to the Cloud Firestore client's offline persistence. This generally means you are using Cloud Firestore from multiple processes in your app. Keep in mind that multi-process Android apps execute the code in your Application class in all processes, so you may need to avoid initializing Cloud Firestore in your Application class. If you are intentionally using Cloud Firestore from multiple processes, you can only enable offline persistence (that is, call setPersistenceEnabled(true)) in one of them.
E/AndroidRuntime(26300): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:333)
E/AndroidRuntime(26300): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$ExternalSyntheticLambda2.run(Unknown Source:4)
E/AndroidRuntime(26300): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
E/AndroidRuntime(26300): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/AndroidRuntime(26300): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
E/AndroidRuntime(26300): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime(26300): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime(26300): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
E/AndroidRuntime(26300): 	at java.lang.Thread.run(Thread.java:1012)
E/AndroidRuntime(26300): Caused by: java.lang.RuntimeException: Failed to gain exclusive lock to the Cloud Firestore client's offline persistence. This generally means you are using Cloud Firestore from multiple processes in your app. Keep in mind that multi-process Android apps execute the code in your Application class in all processes, so you may need to avoid initializing Cloud Firestore in your Application class. If you are intentionally using Cloud Firestore from multiple processes, you can only enable offline persistence (that is, call setPersistenceEnabled(true)) in one of them.
```

**Comment by danagbemava-nc** [comment]
Hi @bitex39, what version of `cloud_firestore` are you using? How are you using `cloud_firestore` in your project? Are you able to to provide a minimal reproducible code sample so that we can investigate this issue? 

Thank you

**Comment by bitex39** [comment]
cloud_firestore: 4.15.5

**Comment by danagbemava-nc** [comment]
Do you use cloud firestore in the background? Like maybe in a firebase_messaging onBackgroundMessage handler or some other process that might be run in the background?
