### ISSUE TITLE
🐛 [firebase_core] Firebase.initializeApp(); throws PlatformException

### ISSUE THREAD

**Issue by abdulkash** [firebase/flutterfire#12414]
## Bug report

**Describe the bug**
`await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);` throws PlatformException during initialization in main function

```
I/flutter (26200): │ ⛔ 	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@18.0.2:8)
I/flutter (26200): │ ⛔ 	at io.flutter.plugins.firebase.core.FlutterFirebaseCorePlugin.lambda$firebaseAppToMap$0$io-flutter-plugins-firebase-core-FlutterFirebaseCorePlugin(FlutterFirebaseCorePlugin.java:87)
I/flutter (26200): │ ⛔ 	at io.flutter.plugins.firebase.core.FlutterFirebaseCorePlugin$$ExternalSyntheticLambda3.run(Unknown Source:6)
I/flutter (26200): │ ⛔ 	... 3 more
I/flutter (26200): │ ⛔ Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.auth.FirebaseUser com.google.firebase.auth.FirebaseAuth.getCurrentUser()' on a null object reference
I/flutter (26200): │ ⛔ 	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@18.0.2:5)
I/flutter (26200): │ ⛔ 	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@18.0.2:8)
I/flutter (26200): │ ⛔ 	at io.flutter.plugins.firebase.core.FlutterFirebasePluginRegistry.lambda$getPluginConstantsForFirebaseApp$0(FlutterFirebasePluginRegistry.java:55)
I/flutter (26200): │ ⛔ 	at io.flutter.plugins.firebase.core.FlutterFirebasePluginRegistry$$ExternalSyntheticLambda1.run(Unknown Source:4)
I/flutter (26200): │ ⛔ 	... 3 more
I/flutter (26200): │ ⛔ Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.auth.FirebaseUser com.google.firebase.auth.FirebaseAuth.getCurrentUser()' on a null object reference
I/flutter (26200): │ ⛔ 	at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.lambda$getPluginConstantsForFirebaseApp$16(FlutterFirebaseAuthPlugin.java:674)
I/flutter (26200): │ ⛔ 	at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin$$ExternalSyntheticLambda12.run(Unknown Source:4)
I/flutter (26200): │ ⛔ 	... 3 more
I/flutter (26200): │ ⛔ , null)
I/flutter (26200): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

### Steps to reproduce

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  } catch (e) {
    logger.e(e.toString());
  }

  // Set up the SettingsController, which will glue user settings to multiple
  // Flutter Widgets.
  final settingsController = SettingsController(SettingsService());

  // Load the user's preferred theme while the splash screen is displayed.
  // This prevents a sudden theme change when the app is first displayed.Render
  await settingsController.loadSettings();

  // Initialize flutter downloader for downloading books
  await FlutterDownloader.initialize(
      debug: kDebugMode, // optional: set to false to disable printing logs to console (default: true)
      ignoreSsl: true // option: set to false to disable working with http links (default: false)
      );
  await FlutterDownloader.registerCallback(BookProvider.downloadCallback);

  // Initialize Appodeal for ads
  _adsInit();

  final dir = await getApplicationDocumentsDirectory();
  Hive.defaultDirectory = dir.path;

  // Run the app and pass in the SettingsController. The app listens to the
  // SettingsController for changes, then passes it further down to the
  // SettingsView.
  runApp(MyApp(settingsController: settingsController));
}

```

### Expected behavior

Intialize firebase without any error

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on Linux, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1
```

</details>

---

**Comment by Lyokone** [comment]
Hello @abdulkash, can you produce minimal reproducing code without any other external dependencies? Thanks

**Comment by abdulkash** [comment]
Here @Lyokone 
`
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  } catch (e) {
    logger.e(e.toString());
  }
  runApp(MyApp());
}

`

**Comment by Lyokone** [comment]
You can check [example apps](https://github.com/firebase/flutterfire/tree/master/packages/firebase_core/firebase_core/example) and [tutorials](https://firebase.google.com/docs/flutter/setup?platform=ios) to see how to configure Firebase with Flutter. 

The code you are providing doesn't seem linked to the logs you are giving. Without a complete example (which means a GitHub repository I can clone that will produce the issue). I'll be unable to help you
