### ISSUE TITLE
🐛 [cloud_firestore] Generated whereDocumentId not working

### ISSUE THREAD

**Issue by Gopinathp** [firebase/flutterfire#12421]
## Bug report
cloud_firestore: ^4.15.6
cloud_firestore_odm: ^1.0.0-dev.83

cloud_firestore_odm_generator: ^1.0.0-dev.83

With the above versions of dependencies, I have generated the cloud firestore code using code generation plugin for my schema.

child: FirestoreQueryBuilder(
            query: creatorsRef.whereDocumentId(isEqualTo:"1cZZL06nxrY5Yy9ASZtu").reference, builder:...)

I am getting the following error. Similar issue is happening in iOS.

/FLTFirestoreMsgCodec(26660): An error occurred while parsing query arguments, this is most likely an error with this SDK.
E/FLTFirestoreMsgCodec(26660): java.lang.IllegalArgumentException: Invalid query. When querying with FieldPath.documentId() you must provide a valid String or DocumentReference, but it was of type: null
E/FLTFirestoreMsgCodec(26660): 	at com.google.firebase.firestore.Query.parseDocumentIdValue(Query.java:527)
E/FLTFirestoreMsgCodec(26660): 	at com.google.firebase.firestore.Query.parseFieldFilter(Query.java:439)
E/FLTFirestoreMsgCodec(26660): 	at com.google.firebase.firestore.Query.parseFilter(Query.java:485)
E/FLTFirestoreMsgCodec(26660): 	at com.google.firebase.firestore.Query.where(Query.java:400)
E/FLTFirestoreMsgCodec(26660): 	at com.google.firebase.firestore.Query.whereEqualTo(Query.java:109)
E/FLTFirestoreMsgCodec(26660): 	at io.flutter.plugins.firebase.firestore.utils.PigeonParser.parseQuery(PigeonParser.java:180)
E/FLTFirestoreMsgCodec(26660): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin.querySnapshot(FlutterFirebaseFirestorePlugin.java:897)
E/FLTFirestoreMsgCodec(26660): 	at io.flutter.plugins.firebase.firestore.GeneratedAndroidFirebaseFirestore$FirebaseFirestoreHostApi$-CC.lambda$setup$20(GeneratedAndroidFirebaseFirestore.java:2492)
E/FLTFirestoreMsgCodec(26660): 	at io.flutter.plugins.firebase.firestore.GeneratedAndroidFirebaseFirestore$FirebaseFirestoreHostApi$$ExternalSyntheticLambda3.onMessage(Unknown Source:2)
E/FLTFirestoreMsgCodec(26660): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
E/FLTFirestoreMsgCodec(26660): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/FLTFirestoreMsgCodec(26660): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/FLTFirestoreMsgCodec(26660): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/FLTFirestoreMsgCodec(26660): 	at android.os.Handler.handleCallback(Handler.java:938)
E/FLTFirestoreMsgCodec(26660): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/FLTFirestoreMsgCodec(26660): 	at android.os.Looper.loopOnce(Looper.java:210)
E/FLTFirestoreMsgCodec(26660): 	at android.os.Looper.loop(Looper.java:299)
E/FLTFirestoreMsgCodec(26660): 	at android.app.ActivityThread.main(ActivityThread.java:8293)
E/FLTFirestoreMsgCodec(26660): 	at java.lang.reflect.Method.invoke(Native Method)
E/FLTFirestoreMsgCodec(26660): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/FLTFirestoreMsgCodec(26660): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

### Steps to reproduce

2. '...'
3. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.20.0-1.2.pre, on macOS 13.5 22G74 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.87.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.4.0-99.1.beta
Flutter SDK 3.20.0-1.2.pre
meetbase 0.0.11+011

dependencies:
- app_links 3.5.0 [flutter plugin_platform_interface flutter_web_plugins gtk]
- backdrop 0.9.1 [flutter]
- cached_network_image 3.3.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- cloud_firestore 4.15.6 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_firestore_odm 1.0.0-dev.83 [cloud_firestore flutter json_annotation meta]
- cloud_functions 4.6.6 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- collection 1.18.0
- cupertino_icons 1.0.6
- extension_google_sign_in_as_googleapis_auth 2.0.12 [flutter google_sign_in googleapis_auth http meta]
- firebase_analytics 10.8.7 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.17.6 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.25.5 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.4.16 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 14.7.17 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 4.3.15 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_storage 11.6.7 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- firebase_ui_auth 1.13.1 [email_validator firebase_auth firebase_core firebase_dynamic_links firebase_ui_localizations firebase_ui_oauth firebase_ui_shared flutter flutter_localizations meta]
- firebase_ui_firestore 1.6.2 [cloud_firestore firebase_ui_localizations firebase_ui_shared flutter]
- firebase_ui_oauth_apple 1.2.19 [firebase_auth firebase_ui_oauth flutter]
- firebase_ui_oauth_google 1.3.1 [firebase_auth firebase_ui_oauth flutter google_sign_in]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_adaptive_scaffold 0.1.8 [flutter]
- flutter_credit_card 4.0.1 [flutter plugin_platform_interface flutter_web_plugins]
- flutter_expandable_fab 2.0.0 [flutter]
- flutter_hooks 0.20.5 [flutter]
- flutter_local_notifications 16.3.2 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_stripe 10.0.0 [flutter meta stripe_android stripe_ios stripe_platform_interface]
- flutter_timezone 1.0.8 [flutter_web_plugins flutter js]
- fluttertoast 8.2.4 [flutter flutter_web_plugins]
- font_awesome_flutter 10.7.0 [flutter]
- go_router 13.2.0 [collection flutter flutter_web_plugins logging meta]
- google_fonts 6.2.0 [flutter http path_provider crypto]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- googleapis 13.0.0 [_discoveryapis_commons http]
- googleapis_auth 1.5.0 [args crypto google_identity_services_web http http_parser]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- hooks_riverpod 2.4.10 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- http 1.2.0 [async http_parser meta web]
- icons_plus 5.0.0 [flutter flutter_svg]
- image_picker 1.0.7 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- in_app_purchase 3.1.13 [flutter in_app_purchase_android in_app_purchase_platform_interface in_app_purchase_storekit]
- instagram_public_api 0.2.0 [flutter http]
- intl 0.18.1 [clock meta path]
- introduction_screen 3.1.12 [flutter collection dots_indicator flutter_keyboard_visibility]
- json_annotation 4.8.1 [meta]
- logger 2.0.2+1
- lottie 3.1.0 [archive flutter http path vector_math]
- permission_handler 11.3.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- photo_view 0.14.0 [flutter]
- provider 6.1.2 [collection flutter nested]
- rounded_loading_button 2.1.0 [flutter rxdart]
- share_plus 7.2.2 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- timeago 3.6.1 [intl]
- url_launcher 6.2.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- webview_flutter 4.7.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- youtube_data_api 1.0.4 [flutter http html xml2json collection]

dev dependencies:
- build_runner 2.4.8 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- cloud_firestore_odm_generator 1.0.0-dev.83 [analyzer build build_config cloud_firestore_odm collection freezed_annotation graphs json_annotation meta recase source_gen source_helper]
- flutter_gen_runner 5.4.0 [flutter_gen_core build collection crypto glob path]
- flutter_lints 3.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- hive_generator 2.0.1 [build source_gen hive analyzer source_helper]
- json_serializable 6.7.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- test 1.25.2 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]

transitive dependencies:
- _discoveryapis_commons 1.0.6 [http http_parser meta]
- _fe_analyzer_shared 67.0.0 [meta]
- _flutterfire_internals 1.3.23 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.4.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.4.10 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.1 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.1 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 6.1.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.10.6 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.5.17 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.7.0 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js web]
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- color 3.0.0
- convert 3.1.1 [typed_data]
- coverage 1.7.2 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.3+8 [meta web]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- dart_style 2.3.6 [analyzer args collection path pub_semver source_span]
- dartx 1.2.0 [characters collection crypto meta path time]
- dbus 0.7.10 [args ffi meta xml]
- desktop_webview_auth 0.0.15 [crypto flutter http flutter_web_plugins plugin_platform_interface]
- dots_indicator 2.1.2 [flutter]
- email_validator 2.1.17
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.9.7 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+19 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 7.1.6 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.9.6 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.11.5 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- firebase_crashlytics_platform_interface 3.6.23 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links 5.4.15 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+23 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.25 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.6.6 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta web]
- firebase_remote_config_platform_interface 1.4.23 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.4.23 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- firebase_storage_platform_interface 5.1.10 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.7.1 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta web]
- firebase_ui_localizations 1.10.2 [flutter flutter_localizations path]
- firebase_ui_oauth 1.5.1 [desktop_webview_auth firebase_auth firebase_ui_auth firebase_ui_shared flutter_svg flutter]
- firebase_ui_shared 1.4.1 [flutter]
- fixnum 1.1.0
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_gen_core 5.4.0 [path yaml mime xml dartx color collection json_annotation glob dart_style args pub_semver]
- flutter_keyboard_visibility 5.4.1 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_riverpod 2.4.10 [collection flutter meta riverpod state_notifier]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- frontend_server_client 3.2.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.3.0+2 [meta web]
- google_sign_in_android 6.1.21 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.4 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.3+3 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- graphs 2.3.1 [collection]
- gtk 2.1.0 [ffi flutter meta]
- hive 2.2.3 [meta crypto]
- html 0.15.4 [csslib source_span]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.9+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.2 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.9+1 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.4 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- in_app_purchase_android 0.3.1 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_purchase_platform_interface 1.3.7 [flutter plugin_platform_interface]
- in_app_purchase_storekit 0.3.12 [collection flutter in_app_purchase_platform_interface json_annotation]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- leak_tracker 10.0.3 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.2 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.0 [leak_tracker matcher meta]
- lints 3.0.0
- logging 1.2.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- mime 1.0.5
- nested 1.0.0 [flutter]
- node_preamble 2.0.2
- octo_image 2.0.0 [flutter]
- package_config 2.1.0 [path]
- path 1.9.0
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 12.0.5 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.0 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.1 [flutter flutter_web_plugins permission_handler_platform_interface]
- permission_handler_platform_interface 4.2.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.7.4 [collection convert js]
- pool 1.5.1 [async stack_trace]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- recase 4.1.0
- riverpod 2.5.0 [meta stack_trace state_notifier]
- rxdart 0.27.7
- share_plus_platform_interface 3.3.1 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.5 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.2 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_map_stack_trace 2.1.1 [path source_maps stack_trace]
- source_maps 0.10.12 [source_span]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.2 [flutter sqflite_common path]
- sqflite_common 2.5.3 [synchronized path meta]
- stack_trace 1.11.1 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- stripe_android 10.0.0 [flutter]
- stripe_ios 10.0.0 [flutter]
- stripe_platform_interface 10.0.0 [flutter freezed_annotation json_annotation meta plugin_platform_interface]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.7.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- test_core 0.6.0 [analyzer args async boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel test_api vm_service yaml]
- time 2.1.4 [clock]
- timezone 0.9.2 [path]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- url_launcher_android 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.2.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- uuid 4.3.3 [crypto sprintf meta fixnum]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- vm_service 14.0.0
- watcher 1.1.0 [async path]
- web 0.4.2
- web_socket_channel 2.4.3 [async crypto stream_channel web]
- webkit_inspection_protocol 1.2.1 [logging]
- webview_flutter_android 3.15.0 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.12.0 [flutter path webview_flutter_platform_interface]
- win32 5.2.0 [ffi]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- xml2json 6.2.2 [xml]
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>

---

**Comment by Gopinathp** [comment]
Similar issue in other generated query.

For the following odm generated code,

```
sessions =
          chatSessionsRef.whereCelebrityId(isEqualTo: widget.creatorInfo.id);
debugPrint("buildChatUi query= ${sessions.reference.parameters}");
```
the condition is automatically added and hence the queries are not working. [FieldPath([celebrityId]), ==, null]
`flutter: buildChatUi query= {where: [[FieldPath([celebrityId]), ==, sadhguru], [FieldPath([celebrityId]), ==, null]], orderBy: [], startAt: null, startAfter: null, endAt: null, endBefore: null, limit: null, limitToLast: null}
`

**Comment by Lyokone** [comment]
Hello @Gopinathp, can you open this issue in the [appropriate repository](https://github.com/firebaseextended/firestoreodm-flutter)? Thanks
