### ISSUE TITLE
🐛 [firebase_analytics] Android crashes in release mode: FlutterJNI was detached from native C++

### ISSUE THREAD

**Issue by chrallard** [firebase/flutterfire#12440]
## Bug report

Flutter: 3.16.7
firebase_analytics: 10.8.8
firebase_core: 2.26.0
Android API 34
AGP 8

The firebase_analytics package is causing my app to crash in release mode, debug is fine.

```
W/FlutterJNI( 6756): Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 2
```

Removing the package from `pubspec.yaml` allows the app to run again.

Note that iOS and web are working, and that this wasn't happening prior to supporting Android API 34 and AGP 8.

### Steps to reproduce

1. Add the firebase_analytics package.
2. Run the app on Android in release mode.

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.2.4
Flutter SDK 3.16.7

dependencies:
- adaptive_scrollbar 2.1.2 [flutter rxdart hovering]
- auto_route 7.8.4 [flutter path collection meta]
- auto_size_text 3.0.0 [flutter]
- cached_network_image 3.3.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- calendar_view 1.0.4 [flutter]
- carousel_slider 4.2.1 [flutter]
- collection 1.18.0
- confetti 0.7.0 [flutter vector_math]
- crop_image 1.0.12 [flutter]
- currency_text_input_formatter 2.1.11 [flutter intl]
- defer_pointer 0.0.2 [flutter equatable]
- dotted_border 2.1.0 [flutter path_drawing]
- dotted_line 3.2.2 [flutter]
- dropdown_search 5.0.6 [flutter]
- easy_localization 3.0.4 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- entry 0.0.9 [flutter flutter_web_plugins simple_animations]
- equatable 2.0.5 [collection meta]
- file_picker 5.5.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_analytics 10.8.8 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.26.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.7.18 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_bloc 8.1.4 [bloc flutter provider]
- flutter_colorpicker 1.0.3 [flutter]
- flutter_dropzone 3.0.7 [flutter flutter_dropzone_platform_interface flutter_dropzone_web]
- flutter_google_places_sdk 0.3.7 [flutter flutter_google_places_sdk_platform_interface flutter_google_places_sdk_ios flutter_google_places_sdk_web flutter_google_places_sdk_android flutter_google_places_sdk_windows flutter_google_places_sdk_linux flutter_google_places_sdk_macos]
- flutter_quill 9.2.12 [flutter flutter_localizations intl dart_quill_delta collection quiver equatable meta html flutter_colorpicker markdown html2md charcode url_launcher flutter_keyboard_visibility device_info_plus super_clipboard]
- flutter_quill_extensions 9.2.12 [flutter http path meta universal_html cross_file flutter_quill photo_view video_player youtube_player_flutter url_launcher super_clipboard gal gal_linux image_picker]
- flutter_slidable 3.0.1 [flutter]
- flutter_staggered_grid_view 0.4.1 [flutter]
- flutter_stripe 9.6.0 [flutter meta stripe_android stripe_ios stripe_platform_interface]
- flutter_stripe_web 4.6.0 [flutter flutter_web_plugins freezed_annotation stripe_platform_interface js stripe_js]
- flutter_svg 2.0.9 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- get_it 7.6.7 [async collection]
- http 1.2.0 [async http_parser meta web]
- hydrated_bloc 9.1.4 [bloc hive meta synchronized]
- image_picker 1.0.7 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- infinite_scroll_pagination 3.2.0 [flutter sliver_tools]
- inflection3 0.5.3+2
- intercom_flutter 8.0.12 [flutter flutter_web_plugins intercom_flutter_platform_interface intercom_flutter_web]
- linked_scroll_controller 0.2.0 [flutter]
- mocktail 0.3.0 [collection matcher test]
- open_filex 4.4.0 [flutter ffi]
- package_info_plus 4.2.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 10.4.5 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- photo_view 0.14.0 [flutter]
- plaid_flutter 3.1.4 [flutter flutter_web_plugins plugin_platform_interface js]
- pointer_interceptor 0.9.1 [flutter]
- screenshot 2.1.0 [flutter]
- scrollable_positioned_list 0.3.8 [flutter collection]
- sentry_flutter 7.16.0 [flutter flutter_web_plugins sentry package_info_plus meta ffi]
- share_handler 0.0.20 [flutter share_handler_android share_handler_ios share_handler_platform_interface]
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- smooth_page_indicator 1.1.0 [flutter]
- timeago 3.6.1 [intl]
- tuple 2.0.2
- upgrader 7.1.0 [flutter device_info_plus html http os_detect package_info_plus shared_preferences url_launcher version xml]
- url_launcher 6.2.4 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.3.3 [crypto sprintf meta fixnum]
- web_socket_client 0.1.0 [web_socket_channel]
- webview_flutter 2.8.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_web 0.1.0+4 [flutter flutter_web_plugins webview_flutter_platform_interface]

dev dependencies:
- auto_route_generator 7.3.2 [build source_gen analyzer path build_runner code_builder dart_style xml args glob auto_route]
- bloc_test 9.1.6 [bloc diff_match_patch meta mocktail test]
- build_runner 2.4.8 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 2.0.3 [lints]
- flutter_native_splash 2.3.10 [args flutter flutter_web_plugins js html image meta path universal_io xml yaml ansicolor]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service async boolean_selector characters clock collection fake_async file matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math web webdriver]
- mockito 5.4.4 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- sentry_dart_plugin 1.7.1 [yaml injector ansicolor system_info2 file http crypto convert process properties]
- test 1.24.9 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]

dependency overrides:
- flutter_colorpicker 1.0.3 [flutter]
- gal 2.3.0 [flutter]
- gal_linux 0.1.0 [flutter gal path]
- pointer_interceptor 0.9.1 [flutter]
- sticky_and_expandable_list 1.1.3 [flutter]

transitive dependencies:
- _fe_analyzer_shared 64.0.0 [meta]
- _flutterfire_internals 1.3.24 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.2.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- ansicolor 2.0.2
- archive 3.4.10 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- bloc 8.1.3 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.0 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.1 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- charcode 1.3.1
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.1 [meta path]
- clock 1.1.1
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- convert 3.1.1 [typed_data]
- coverage 1.6.4 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.3+8 [meta web]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- dart_quill_delta 9.2.12 [collection diff_match_patch quiver]
- dart_style 2.3.4 [analyzer args collection path pub_semver source_span]
- device_info_plus 9.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- diff_match_patch 0.4.1
- easy_logger 0.0.2 [flutter]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 6.1.4 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.9.8 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+20 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.11.5 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- firebase_messaging_platform_interface 4.5.26 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.6.7 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta web]
- fixnum 1.1.0
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver async boolean_selector characters clock collection matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math web]
- flutter_dropzone_platform_interface 2.0.6 [flutter plugin_platform_interface]
- flutter_dropzone_web 3.0.13 [flutter flutter_web_plugins flutter_dropzone_platform_interface js]
- flutter_google_places_sdk_android 0.1.8 [flutter flutter_google_places_sdk_platform_interface]
- flutter_google_places_sdk_http 0.1.4 [flutter http latlong2 flutter_google_places_sdk_platform_interface freezed_annotation json_annotation]
- flutter_google_places_sdk_ios 0.1.3 [flutter flutter_google_places_sdk_platform_interface]
- flutter_google_places_sdk_linux 0.1.4 [flutter flutter_google_places_sdk_platform_interface flutter_google_places_sdk_http]
- flutter_google_places_sdk_macos 0.1.4 [flutter flutter_google_places_sdk_platform_interface flutter_google_places_sdk_http]
- flutter_google_places_sdk_platform_interface 0.2.7 [flutter freezed_annotation json_annotation plugin_platform_interface]
- flutter_google_places_sdk_web 0.1.6 [flutter flutter_web_plugins flutter_google_places_sdk_platform_interface js google_maps collection]
- flutter_google_places_sdk_windows 0.1.4 [flutter flutter_google_places_sdk_platform_interface flutter_google_places_sdk_http]
- flutter_inappwebview 5.8.0 [flutter]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- frontend_server_client 3.2.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- glob 2.1.2 [async collection file path string_scanner]
- globbing 1.0.0 [path]
- google_maps 6.3.0 [js js_wrapping meta]
- graphs 2.3.1 [collection]
- hive 2.2.3 [meta crypto]
- hovering 1.0.4 [flutter]
- html 0.15.4 [csslib source_span]
- html2md 1.3.1 [html collection]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.1.7 [archive meta xml]
- image_picker_android 0.8.9+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.2 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.9+1 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.3 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- injector 3.0.0
- intercom_flutter_platform_interface 2.0.0 [flutter plugin_platform_interface]
- intercom_flutter_web 1.0.2 [flutter flutter_web_plugins intercom_flutter_platform_interface uuid]
- intl 0.18.1 [clock meta path]
- io 1.0.4 [meta path string_scanner]
- irondash_engine_context 0.5.2 [flutter plugin_platform_interface]
- irondash_message_channel 0.6.0 [flutter ffi]
- js 0.6.7 [meta]
- js_wrapping 0.7.4 [js]
- json_annotation 4.8.1 [meta]
- latlong2 0.9.0 [intl]
- lints 2.1.1
- logging 1.2.0
- markdown 7.2.1 [args meta]
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.10.0
- mime 1.0.5
- nested 1.0.0 [flutter]
- node_preamble 2.0.2
- octo_image 2.0.0 [flutter]
- os_detect 2.0.1
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.3
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 10.3.6 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.1.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.12.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.3 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- pixel_snap 0.1.4 [flutter]
- platform 3.1.2
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.7.4 [collection convert js]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- properties 2.1.0 [meta test]
- provider 6.1.1 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.1 [matcher]
- rxdart 0.27.7
- sentry 7.16.0 [http meta stack_trace uuid]
- share_handler_android 0.0.7 [flutter share_handler_platform_interface]
- share_handler_ios 0.0.13 [flutter share_handler_platform_interface]
- share_handler_platform_interface 0.0.6 [flutter plugin_platform_interface]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.5 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.2 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- simple_animations 5.0.2 [flutter collection]
- sky_engine 0.0.99
- sliver_tools 0.2.12 [flutter]
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_map_stack_trace 2.1.1 [path source_maps stack_trace]
- source_maps 0.10.12 [source_span]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.2 [flutter sqflite_common path]
- sqflite_common 2.5.3 [synchronized path meta]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- stripe_android 9.6.0+2 [flutter]
- stripe_ios 9.6.0 [flutter]
- stripe_js 3.3.0 [freezed_annotation js json_annotation meta]
- stripe_platform_interface 9.6.0 [flutter freezed_annotation json_annotation meta plugin_platform_interface]
- super_clipboard 0.8.5 [flutter collection meta super_native_extensions]
- super_native_extensions 0.8.5 [flutter flutter_web_plugins meta ffi collection js path uuid irondash_engine_context irondash_message_channel device_info_plus pixel_snap]
- sync_http 0.3.1
- synchronized 3.1.0+1
- system_info2 4.0.0 [globbing path]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- test_core 0.5.9 [analyzer args async boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel test_api vm_service yaml]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- universal_html 2.2.4 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_android 6.2.2 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.1 [flutter plugin_platform_interface]
- url_launcher_web 2.2.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.10+1 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.10+1
- vector_graphics_compiler 1.1.10+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- version 3.0.2
- video_player 2.8.2 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.4.12 [flutter video_player_platform_interface]
- video_player_avfoundation 2.5.6 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.2 [flutter plugin_platform_interface]
- video_player_web 2.1.3 [flutter flutter_web_plugins video_player_platform_interface]
- vm_service 11.10.0
- watcher 1.1.0 [async path]
- web 0.3.0
- web_socket_channel 2.4.0 [async crypto stream_channel]
- webdriver 3.0.2 [matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.2.1 [logging]
- webview_flutter_android 2.10.4 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.9.5 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 2.9.5 [flutter path webview_flutter_platform_interface]
- win32 5.2.0 [ffi]
- win32_registry 1.1.2 [ffi win32]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
- youtube_player_flutter 8.1.2 [flutter flutter_inappwebview]
```

</details>

---

**Comment by Lyokone** [comment]
Hello @chrallard; couldn't reproduce the crash using the firebase_analytics plugin. Please provide a complete reproduction sample so we can investigate.

**Comment by alexprazeres** [comment]
I'm facing the same issue.
It's happens with some real devices and also in Android Simulator., must be --release mode

iOS is running fine

**Comment by alexprazeres** [comment]
E/AndroidRuntime(10909): FATAL EXCEPTION: ScionFrontendApi
E/AndroidRuntime(10909): Process: com.ib2gopag.vitoria, PID: 10909
E/AndroidRuntime(10909): java.lang.ExceptionInInitializerError
E/AndroidRuntime(10909):        at com.google.android.gms.measurement.internal.C2.<init>(Unknown Source:37)
E/AndroidRuntime(10909):        at com.google.android.gms.measurement.internal.n2.<init>(Unknown Source:183)
E/AndroidRuntime(10909):        at com.google.android.gms.measurement.internal.n2.c(Unknown Source:58)
E/AndroidRuntime(10909):        at com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.initialize(Unknown Source:17)
E/AndroidRuntime(10909):        at com.google.android.gms.internal.measurement.g0.a(Unknown Source:108)
E/AndroidRuntime(10909):        at com.google.android.gms.internal.measurement.d0$a.run(Unknown Source:12)
E/AndroidRuntime(10909):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime(10909):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime(10909):        at java.lang.Thread.run(Thread.java:1012)
E/AndroidRuntime(10909): Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.google.android.gms.measurement.internal.A2$a.values []
E/AndroidRuntime(10909):        at java.lang.Enum.enumValues(Enum.java:315)
E/AndroidRuntime(10909):        at java.lang.Enum.-$$Nest$smenumValues(Unknown Source:0)
E/AndroidRuntime(10909):        at java.lang.Enum$1.create(Enum.java:322)
E/AndroidRuntime(10909):        at java.lang.Enum$1.create(Enum.java:320)
E/AndroidRuntime(10909):        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
E/AndroidRuntime(10909):        at java.lang.Enum.getSharedConstants(Enum.java:334)
E/AndroidRuntime(10909):        at java.lang.Class.getEnumConstantsShared(Class.java:4036)
E/AndroidRuntime(10909):        at java.util.EnumMap.getKeyUniverse(EnumMap.java:749)
E/AndroidRuntime(10909):        at java.util.EnumMap.<init>(EnumMap.java:136)
E/AndroidRuntime(10909):        at com.google.android.gms.measurement.internal.A2.<init>(Unknown Source:7)
E/AndroidRuntime(10909):        at com.google.android.gms.measurement.internal.A2.<clinit>(Unknown Source:5)
E/AndroidRuntime(10909):        ... 9 more
E/AndroidRuntime(10909): Caused by: java.lang.NoSuchMethodException: com.google.android.gms.measurement.internal.A2$a.values []
E/AndroidRuntime(10909):        at java.lang.Class.getMethod(Class.java:2937)
E/AndroidRuntime(10909):        at java.lang.Class.getDeclaredMethod(Class.java:2914)
E/AndroidRuntime(10909):        at java.lang.Enum.enumValues(Enum.java:312)
E/AndroidRuntime(10909):        ... 19 more

**Comment by alexprazeres** [comment]
I managed to fix it by adding a proguard rule.

-keep class com.google.android.gms.measurement.internal.** { *; }
