### ISSUE TITLE
🐛 [firebase_auth/unknown] An internal error has occurred. [ Cleartext HTTP traffic to 10.0.2.2 not permitted ]

### ISSUE THREAD

**Issue by MarceloEsser** [firebase/flutterfire#12462]
## Bug report

**Describe the bug**
I add the cleartrafic configuration but this error stil happen. 

```
E/RecaptchaCallWrapper( 4536): Initial task failed for action RecaptchaAction(action=signUpPassword)with exception - An internal error has occurred. [ Cleartext HTTP traffic to 10.0.2.2 not permitted ]

#0      FirebaseAuthHostApi.createUserWithEmailAndPassword (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:1012:7)
<asynchronous suspension>
#1      MethodChannelFirebaseAuth.createUserWithEmailAndPassword (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:260:22)
<asynchronous suspension>
#2      FirebaseAuth.createUserWithEmailAndPassword (package:firebase_auth/src/firebase_auth.dart:246:7)
<asynchronous suspension>
#3      EmailAuthFlow.onSignedIn (package:firebase_ui_auth/src/flows/email_flow.dart:56:3)
<asynchronous suspension>
```

### Steps to reproduce

1. Create a new flutter project (3.19.2)
2. Add this packages to the project   firebase_core: ^2.26.0,  firebase_auth: ^4.17.8,  firebase_ui_auth: ^1.13.1
3. Implement the firebase ui as the doc says to do
4. Try to create an account

### Expected behavior

I would like to create an account and sign in with it

### [Sample project](https://github.com/MarceloEsser/genro-app-copy)

---

## Additional context
My emulators are on
![image](https://github.com/firebase/flutterfire/assets/28572176/b292683a-1896-4280-8d07-c20a6fc521b4)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.87.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.3.0
Flutter SDK 3.19.2
genro_app 1.0.0+1

dependencies:
- cupertino_icons 1.0.6
- firebase_auth 4.17.8 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.27.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_ui_auth 1.13.1 [email_validator firebase_auth firebase_core firebase_dynamic_links firebase_ui_localizations firebase_ui_oauth firebase_ui_shared flutter flutter_localizations meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- get_it 7.6.7 [async collection]
- go_router 13.2.0 [collection flutter flutter_web_plugins logging meta]
- provider 6.1.2 [collection flutter nested]

dev dependencies:
- flutter_lints 3.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.25 [collection firebase_core firebase_core_platform_interface flutter meta]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- crypto 3.0.3 [typed_data]
- desktop_webview_auth 0.0.15 [crypto flutter http flutter_web_plugins plugin_platform_interface]
- email_validator 2.1.17
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 7.1.8 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.9.8 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.11.5 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- firebase_dynamic_links 5.4.17 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+25 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_ui_localizations 1.10.2 [flutter flutter_localizations path]
- firebase_ui_oauth 1.5.1 [desktop_webview_auth firebase_auth firebase_ui_auth firebase_ui_shared flutter_svg flutter]
- firebase_ui_shared 1.4.1 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- http 1.2.0 [async http_parser meta web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.18.1 [clock meta path]
- js 0.6.7 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- logging 1.2.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- nested 1.0.0 [flutter]
- path 1.9.0
- path_parsing 1.0.1 [vector_math meta]
- petitparser 6.0.2 [meta]
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- vm_service 13.0.0
- web 0.4.2
- xml 6.5.0 [collection meta petitparser]
```

</details>

---

**Comment by MarceloEsser** [comment]
Just to keep de evidence, on iOS it works. I created an account on iOS emulator and signed in
![image](https://github.com/firebase/flutterfire/assets/28572176/94523829-ef4e-4526-81e7-4bc3f9bab929)

**Comment by Lyokone** [comment]
Please use the `search` function before posting new issues: https://github.com/firebase/flutterfire/issues/6486

**Comment by MarceloEsser** [comment]
I'm sorry, I think I wasn't clear enough... I searched the issue and I try to add clearTraffic AND the network configuration but the error persists. If you see, the sample project fixed in the issue contains both configurations.

**Comment by Lyokone** [comment]
You have added the tag to the wrong xml element. You need to add it to <application instead of <activity

**Comment by MarceloEsser** [comment]
wtf, I can't believe I did this... Sorry for open this issue and thank you for the support!
