### ISSUE TITLE
🐛 [cloud_firestore] Can't use Cloud Firestore with only non-default app

### ISSUE THREAD

**Issue by rstieger** [firebase/flutterfire#12479]
## Bug report

**Describe the bug**
I am trying to use Cloud Firestore with only a non-default app (for a library that should work whether or not the main application uses Firestore. However, FirebaseFunction.instanceFor(app:) throws an ```Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()``` 

### Steps to reproduce

```
  final notDefaultApp = await Firebase.initializeApp(
    name: 'notDefault',
    options: DefaultFirebaseOptions.currentPlatform,
  );
  print(Firebase.apps); // ensure that only FirebaseApp(notDefault) is printed
  final firestore = FirebaseFirestore.instanceFor(app: notDefaultApp);
```

Console output:
```
I/flutter (32277): [FirebaseApp(notDefault)]
E/flutter (32277): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
E/flutter (32277): #0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:193:5)
E/flutter (32277): #1      Firebase.app (package:firebase_core/src/firebase.dart:56:41)
E/flutter (32277): #2      FirebaseFirestorePlatform.instance (package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_firestore.dart:54:23)
E/flutter (32277): #3      new FirebaseFirestorePlatform.instanceFor (package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_firestore.dart:44:38)
E/flutter (32277): #4      FirebaseFirestore._delegate (package:cloud_firestore/src/firestore.dart:59:67)
E/flutter (32277): #5      FirebaseFirestore.settings= (package:cloud_firestore/src/firestore.dart:286:5)
E/flutter (32277): #6      main (package:cloud_firestore_example/main.dart:35:53)
E
```
### Expected behavior

No exception, can use non-default firestore instance normally.

### Sample project

Example code is at 
https://github.com/rstieger/flutterfire/tree/firebase-no-default/packages/cloud_firestore/cloud_firestore/example

Note that this example only fails for Android. The presence of GoogleServices-Info.plist creates a default app for iOS (this can be seen from the print output), so there is no failure. Deleting that file and the build steps that require it should allow a repro in iOS also.

---

## Additional context

The exception occurs in the platform interface, and other packages may have similar results, as there is a similar pattern used, where a default application is required before any non-default can be used.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.3.1 23D60 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.87.0)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.3.0
Flutter SDK 3.19.1
cloud_firestore_example 0.0.0

dependencies:
- cloud_firestore 4.15.9 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.27.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- http 1.2.1 [async http_parser meta web]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service async boolean_selector characters clock collection fake_async file leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math webdriver]

transitive dependencies:
- _flutterfire_internals 1.3.26 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 6.1.10 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.10.9 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- file 7.0.0 [meta path]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.12.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver async boolean_selector characters clock collection leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- path 1.9.0
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- process 5.0.2 [file path platform]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- sync_http 0.3.1
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- vm_service 13.0.0
- web 0.5.1
- webdriver 3.0.3 [matcher path stack_trace sync_http]
- ```

</details>

---

**Comment by Lyokone** [comment]
Hello @rstieger, it's not something that is supported by native SDK so we will not be able to support it on our end. You can open a feature request here: https://firebase.uservoice.com/forums/948424-general
