### ISSUE TITLE
io.flutter.plugins.firebase.messaging.b.d (Unknown Source:22) 

### ISSUE THREAD

**Issue by RamaSrinivas** [firebase/flutterfire#12506]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

Android

### Description

We are facing the following crashes on firebase but we are unable to replicate them at our end. We are facing this from past 6 mons, please help us to resolve this.

1. Fatal Exception: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 
    com.google.firebase.messaging.RemoteMessage
       at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:5024)
       at android.os.Parcel.readParcelableInternal(Parcel.java:4873)
       at android.os.Parcel.readValue(Parcel.java:4633)
       at android.os.Parcel.readValue(Parcel.java:4402)
       at android.os.Parcel.-$$Nest$mreadValue()
       at android.os.Parcel$LazyValue.apply(Parcel.java:4500)
       at android.os.Parcel$LazyValue.apply(Parcel.java:4459)
       at android.os.BaseBundle.unwrapLazyValueFromMapLocked(BaseBundle.java:415)
       at android.os.BaseBundle.getValueAt(BaseBundle.java:401)
       at android.os.BaseBundle.getValue(BaseBundle.java:381)
       at android.os.BaseBundle.getValue(BaseBundle.java:364)
       at android.os.BaseBundle.getValue(BaseBundle.java:357)
       at android.os.Bundle.getParcelable(Bundle.java:913)
       at android.content.Intent.getParcelableExtra(Intent.java:9769)
       at io.flutter.plugins.firebase.messaging.b.d(:22)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.l(:2)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.j()
       at zk.d.run(:4)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
       
       
  2.  Caused by java.lang.ClassNotFoundException: com.google.firebase.messaging.RemoteMessage
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:536)
       at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4990)
       at android.os.Parcel.readParcelableInternal(Parcel.java:4873)
       at android.os.Parcel.readValue(Parcel.java:4633)
       at android.os.Parcel.readValue(Parcel.java:4402)
       at android.os.Parcel.-$$Nest$mreadValue()
       at android.os.Parcel$LazyValue.apply(Parcel.java:4500)
       at android.os.Parcel$LazyValue.apply(Parcel.java:4459)
       at android.os.BaseBundle.unwrapLazyValueFromMapLocked(BaseBundle.java:415)
       at android.os.BaseBundle.getValueAt(BaseBundle.java:401)
       at android.os.BaseBundle.getValue(BaseBundle.java:381)
       at android.os.BaseBundle.getValue(BaseBundle.java:364)
       at android.os.BaseBundle.getValue(BaseBundle.java:357)
       at android.os.Bundle.getParcelable(Bundle.java:913)
       at android.content.Intent.getParcelableExtra(Intent.java:9769)
       at io.flutter.plugins.firebase.messaging.b.d(:22)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.l(:2)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.j()
       at zk.d.run(:4)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

### Reproducing the issue

Crashes we are gettiong from firebase.

### Firebase Core version

^2.15.0

### Flutter Version

firebase_messaging: ^14.7.8

### Flutter dependencies

```json

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by Lyokone** [comment]
It looks like some classes are not found, it's weird that you don't get consistent crash. Could you try [this comment](https://github.com/firebase/flutterfire/issues/9884#issuecomment-1451022470), by adjusting your proguards settings?
You should try to keep
```
-keep class com.google.firebase.messaging.** { *; }
```

**Comment by RamaSrinivas** [comment]
Sure will check and update. Thanks for the promt response.
