### ISSUE TITLE
[firebase_core]: <Unhandled Exception: PlatformException(java.lang.Exception: Failed to load FirebaseOptions>

### ISSUE THREAD

**Issue by sanjaycdev** [firebase/flutterfire#12526]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Analytics, App Check, App Installations, Auth, Cloud Functions, Crashlytics, Database, In-App Messaging, Messaging, ML Custom, Performance, Remote Config, Storage, Other

### Which platforms are affected?

Android

### Description

its happening after removing imperative apply of Flutter's Gradle plugins which is deprecated. ie. after migrate to the new, declarative apply issue started. checked by creating new project also facing same issue .
Any project created on flutter 3.19 is facing this error.

### Reproducing the issue

call init in project created with flutter 3.19 (projects have declarative apply of Flutter's Gradle plugins)
  await Firebase.initializeApp();

### Firebase Core version

2.27.0

### Flutter Version

3.19.4

### Relevant Log Output

```shell
E/flutter ( 6708): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(java.lang.Exception: Failed to load FirebaseOptions from resource. Check that you have defined values.xml correctly., Exception, Cause: null, Stacktrace: java.lang.Exception: Failed to load FirebaseOptions from resource. Check that you have defined values.xml correctly.
E/flutter ( 6708): 	at io.flutter.plugins.firebase.core.FlutterFirebaseCorePlugin.lambda$optionsFromResource$4$io-flutter-plugins-firebase-core-FlutterFirebaseCorePlugin(FlutterFirebaseCorePlugin.java:207)
E/flutter ( 6708): 	at io.flutter.plugins.firebase.core.FlutterFirebaseCorePlugin$$ExternalSyntheticLambda2.run(Unknown Source:4)
E/flutter ( 6708): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/flutter ( 6708): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/flutter ( 6708): 	at java.lang.Thread.run(Thread.java:1012)
E/flutter ( 6708): , null)
E/flutter ( 6708): #0      FirebaseCoreHostApi.optionsFromResource (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:242:7)
E/flutter ( 6708): <asynchronous suspension>
E/flutter ( 6708): #1      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:89:25)
E/flutter ( 6708): <asynchronous suspension>
E/flutter ( 6708): #2      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:31)
E/flutter ( 6708): <asynchronous suspension>
E/flutter ( 6708): #3      main (package:myapp/flavours/main_dev.dart:22:3)
E/flutter ( 6708): <asynchronous suspension>
E/flutter ( 6708): 
D/ProfileInstaller( 6708): Installing profile for in.roseapp.app.rose_app.dev
I/pp.rose_app.dev( 6708): Compiler allocated 4703KB to compile void android.view.ViewRootImpl.performTraversals()
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

- _flutterfire_internals 1.3.26 [collection firebase_core firebase_core_platform_interface flutter meta]
- animated_checkmark 1.0.1 [flutter]
- archive 3.4.10 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- audio_session 0.1.18 [flutter flutter_web_plugins rxdart meta]
- back_button_interceptor 6.0.2 [collection flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.1 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- clock 1.1.1
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cross_file 0.3.4+1 [meta web]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- dbus 0.7.10 [args ffi meta xml]
- easy_logger 0.0.2 [flutter]
- equatable 2.0.5 [collection meta]
- eventify 1.0.1
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_auth_platform_interface 7.1.9 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.10.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.12.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- firebase_dynamic_links_platform_interface 0.2.6+25 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.28 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.7.0 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta web]
- fixnum 1.1.0
- flexi_chip 1.0.8 [flutter widget_event animated_checkmark]
- flutter_chat_types 3.6.2 [equatable json_annotation meta]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_secure_storage_linux 1.2.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.0.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.1.2 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 3.0.0 [ffi flutter flutter_secure_storage_platform_interface path path_provider win32]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- html 0.15.4 [csslib source_span]
- http 1.2.1 [async http_parser meta web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_cropper_for_web 3.0.0 [flutter flutter_web_plugins image_cropper_platform_interface js]
- image_cropper_platform_interface 5.0.0 [flutter plugin_platform_interface http]
- image_picker_android 0.8.9+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.2.0 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.9+1 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.3 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- iris_method_channel 2.0.1 [flutter flutter_web_plugins ffi async js]
- js 0.6.7 [meta]
- json_annotation 4.8.1 [meta]
- just_audio_platform_interface 4.2.2 [flutter plugin_platform_interface]
- just_audio_web 0.4.9 [just_audio_platform_interface flutter flutter_web_plugins]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- linkify 5.0.0
- lints 2.1.1
- logging 1.2.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- mime 1.0.5
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 2.0.0 [flutter]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 12.0.5 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.2 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.1 [flutter flutter_web_plugins permission_handler_platform_interface]
- permission_handler_platform_interface 4.2.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.7.4 [collection convert js]
- provider 6.1.2 [collection flutter nested]
- riverpod 2.5.1 [collection meta stack_trace state_notifier]
- rxdart 0.27.7
- sentry 7.18.0 [http meta stack_trace uuid]
- share_plus_platform_interface 3.4.0 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.5 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.3.0 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- smart_auth 1.1.1 [flutter flutter_web_plugins]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.2 [flutter sqflite_common path]
- sqflite_common 2.5.3 [synchronized path meta]
- stack_trace 1.11.1 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.9.2 [path]
- typed_data 1.3.2 [collection]
- universal_platform 1.0.0+1
- url_launcher_android 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.0 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- uuid 4.3.3 [crypto sprintf meta fixnum]
- vector_graphics 1.1.10+1 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.10+1
- vector_graphics_compiler 1.1.10+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- video_player_android 2.4.12 [flutter video_player_platform_interface]
- video_player_avfoundation 2.5.6 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.2 [flutter plugin_platform_interface]
- video_player_web 2.1.3 [flutter flutter_web_plugins video_player_platform_interface]
- vm_service 13.0.0
- wakelock_plus_platform_interface 1.1.0 [flutter plugin_platform_interface meta]
- web 0.5.1
- widget_event 1.2.6 [flutter]
- win32 5.2.0 [ffi]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]


```

</details>

### Additional context and comments

integrated firebase through GUI mode , CLI not used. 
developing for Android and Ios only ,no web

**Comment by sanjaycdev** [comment]
update : i tried with cli mode in new project  its working as expected . `options`  parameter seems required  which is passed when its configured through cli mode

**Comment by russellwheatley** [comment]
You need to add google-services to you build.gradle setup. [See this PR](https://github.com/firebase/flutterfire/pull/12412).

Specifically these two lines:

https://github.com/firebase/flutterfire/pull/12412/files#diff-310d3e41a24c38a733198c7003a94cdc9b28cbc98b79213cf012e2084faa7775R5

https://github.com/firebase/flutterfire/pull/12412/files#diff-87094a45314cb1d3edcb398c11246ddcbcdc2fd9568b580d8a911a412083b4d6R23

Google services plugin is what bundles the google-services.json file into your app.

**Comment by sanjaycdev** [comment]
@russellwheatley  it doesn't help thanks for the response,
But finally figured out . 
https://stackoverflow.com/questions/78213917/how-to-fix-failed-to-load-firebaseoptions-from-resource-check-that-you-have-def/78215218#78215218

**Comment by woelmer** [comment]
The suggested fix by @russellwheatley worked for me
