### ISSUE TITLE
[firebase_messaging]: ClassNotFoundException when unmarshalling: com.google.firebase.messaging.s0

### ISSUE THREAD

**Issue by Tom3652** [firebase/flutterfire#12563]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

Android

### Description

The app is crashing in release mode with live users because of a `ClassNotFoundException`.

### Reproducing the issue

I have no clue how to reproduce it since it happened in release mode, my app is live on the store.

### Firebase Core version

firebase_core: ^2.27.2

### Flutter Version

3.19.5

### Relevant Log Output

```shell
# Crashlytics - Stack trace
# Application: com.myapp_name
# Platform: android
# Version: 2.5.0 (32)
# Issue: 8508f82b9d1bb6c2997a2e115cb8f8db
# Session: 660ACB9A02C1000179AB9688C6CDD84A_DNE_0_v2
# Date: Mon Apr 01 2024 18:46:21 GMT+0200 (heure d’été d’Europe centrale)

Fatal Exception: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.firebase.messaging.s0
       at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:5012)
       at android.os.Parcel.readParcelableInternal(Parcel.java:4861)
       at android.os.Parcel.readValue(Parcel.java:4621)
       at android.os.Parcel.readValue(Parcel.java:4390)
       at android.os.Parcel.-$$Nest$mreadValue()
       at android.os.Parcel$LazyValue.apply(Parcel.java:4488)
       at android.os.Parcel$LazyValue.apply(Parcel.java:4447)
       at android.os.BaseBundle.unwrapLazyValueFromMapLocked(BaseBundle.java:415)
       at android.os.BaseBundle.getValueAt(BaseBundle.java:401)
       at android.os.BaseBundle.getValue(BaseBundle.java:381)
       at android.os.BaseBundle.getValue(BaseBundle.java:364)
       at android.os.BaseBundle.getValue(BaseBundle.java:357)
       at android.os.Bundle.getParcelable(Bundle.java:913)
       at android.content.Intent.getParcelableExtra(Intent.java:9149)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate(FlutterFirebaseMessagingBackgroundExecutor.java:1)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.lambda$onHandleWork$0(FlutterFirebaseMessagingBackgroundService.java:1)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8248)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

Caused by java.lang.ClassNotFoundException: com.google.firebase.messaging.s0
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:536)
       at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4978)
       at android.os.Parcel.readParcelableInternal(Parcel.java:4861)
       at android.os.Parcel.readValue(Parcel.java:4621)
       at android.os.Parcel.readValue(Parcel.java:4390)
       at android.os.Parcel.-$$Nest$mreadValue()
       at android.os.Parcel$LazyValue.apply(Parcel.java:4488)
       at android.os.Parcel$LazyValue.apply(Parcel.java:4447)
       at android.os.BaseBundle.unwrapLazyValueFromMapLocked(BaseBundle.java:415)
       at android.os.BaseBundle.getValueAt(BaseBundle.java:401)
       at android.os.BaseBundle.getValue(BaseBundle.java:381)
       at android.os.BaseBundle.getValue(BaseBundle.java:364)
       at android.os.BaseBundle.getValue(BaseBundle.java:357)
       at android.os.Bundle.getParcelable(Bundle.java:913)
       at android.content.Intent.getParcelableExtra(Intent.java:9149)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate(FlutterFirebaseMessagingBackgroundExecutor.java:1)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.lambda$onHandleWork$0(FlutterFirebaseMessagingBackgroundService.java:1)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8248)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
```


### Flutter dependencies

<!--- Look below for instructions on how to share your Flutter Dependencies. --->

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.3.3
Flutter SDK 3.19.5
myappname 2.5.0+32

dependencies:
- app_settings 5.1.1 [flutter plugin_platform_interface]
- apple_maps_flutter 1.3.0 [flutter]
- audio_session 0.1.18 [flutter flutter_web_plugins rxdart meta]
- audio_waveforms 1.0.5 [flutter]
- audioplayers 6.0.0 [audioplayers_android audioplayers_darwin audioplayers_linux audioplayers_platform_interface audioplayers_web audioplayers_windows file flutter http meta path_provider synchronized uuid]
- auto_size_text 3.0.0 [flutter]
- cached_network_image 3.3.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- collection 1.18.0
- connectivity_plus 6.0.1 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm]
- cupertino_icons 1.0.6
- desktop_drop 0.4.4 [flutter flutter_web_plugins cross_file]
- dio 5.4.2+1 [async http_parser meta path]
- edge_detection 1.1.3 [flutter]
- extended_image 8.2.0 [extended_image_library flutter meta]
- file_picker 8.0.0+1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32 cross_file]
- file_selector 1.0.3 [file_selector_android file_selector_ios file_selector_linux file_selector_macos file_selector_platform_interface file_selector_web file_selector_windows flutter]
- firebase_analytics 10.9.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check 0.2.1+19 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.18.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.27.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.4.20 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_in_app_messaging 0.7.4+19 [firebase_core firebase_core_platform_interface firebase_in_app_messaging_platform_interface flutter meta]
- firebase_messaging 14.7.21 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.9.3+19 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_remote_config 4.3.19 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_storage 11.6.11 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- fl_chart 0.67.0 [equatable flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_app_badger 1.5.0 [flutter]
- flutter_calendar_carousel 2.4.2 [intl flutter]
- flutter_email_sender 6.0.2 [flutter]
- flutter_image_compress 2.2.0 [flutter flutter_image_compress_platform_interface flutter_image_compress_common flutter_image_compress_web flutter_image_compress_macos flutter_image_compress_ohos]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_pdfview 1.3.2 [flutter]
- flutter_secure_storage 9.0.0 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_staggered_grid_view 0.7.0 [flutter]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- fluttercontactpicker 4.7.0 [flutter contact_picker_platform_interface contact_picker_web]
- gallery_saver 2.3.3 [flutter path_provider http path]
- geocoding 3.0.0 [flutter geocoding_platform_interface geocoding_android geocoding_ios]
- geolocator 11.0.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- google_maps_flutter 2.6.0 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface google_maps_flutter_web]
- google_mlkit_text_recognition 0.11.0 [flutter google_mlkit_commons]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- http 1.2.1 [async http_parser meta web]
- image_editor 1.4.0 [flutter image_editor_platform_interface image_editor_common image_editor_ohos]
- image_picker 1.0.7 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- in_app_review 2.0.9 [flutter in_app_review_platform_interface]
- linkify 5.0.0
- local_auth 2.2.0 [flutter local_auth_android local_auth_darwin local_auth_platform_interface local_auth_windows]
- maps_launcher 2.2.1 [flutter flutter_web_plugins url_launcher]
- package_info_plus 6.0.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32]
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- pdf 3.10.8 [archive barcode bidi crypto image meta path_parsing vector_math xml]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- printing 5.12.0 [ffi flutter flutter_web_plugins http image js meta pdf pdf_widget_wrapper plugin_platform_interface]
- provider 6.1.2 [collection flutter nested]
- pull_to_refresh_flutter3 2.0.2 [flutter]
- purchases_flutter 6.24.0 [flutter freezed_annotation json_annotation]
- record 5.0.5 [flutter uuid record_platform_interface record_web record_windows record_linux record_android record_darwin]
- rive 0.13.1 [collection flutter flutter_web_plugins http meta plugin_platform_interface rive_common]
- screenshot 2.3.0 [flutter]
- share_plus 8.0.2 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi web win32]
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 6.0.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- snapping_sheet_2 3.1.5 [flutter]
- syncfusion_flutter_datepicker 25.1.37 [flutter intl syncfusion_flutter_core]
- url_launcher 6.2.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.3.3 [crypto sprintf meta fixnum]
- visibility_detector 0.4.0+2 [flutter]

dev dependencies:
- build_runner 2.4.9 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 3.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- hive_generator 2.0.1 [build source_gen hive analyzer source_helper]

transitive dependencies:
- _fe_analyzer_shared 67.0.0 [meta]
- _flutterfire_internals 1.3.27 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.4.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.4.10 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- audioplayers_android 5.0.0 [audioplayers_platform_interface flutter]
- audioplayers_darwin 6.0.0 [audioplayers_platform_interface flutter]
- audioplayers_linux 4.0.0 [audioplayers_platform_interface flutter]
- audioplayers_platform_interface 7.0.0 [collection flutter meta plugin_platform_interface]
- audioplayers_web 5.0.0 [audioplayers_platform_interface flutter flutter_web_plugins web]
- audioplayers_windows 4.0.0 [audioplayers_platform_interface flutter]
- barcode 2.2.6 [meta qr]
- bidi 2.0.10
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.1 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.1 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.1 [meta path]
- clock 1.1.1
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- connectivity_plus_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- contact_picker_platform_interface 4.7.0 [flutter meta plugin_platform_interface]
- contact_picker_web 4.7.0 [flutter flutter_web_plugins js contact_picker_platform_interface]
- convert 3.1.1 [typed_data]
- cross_file 0.3.4+1 [meta web]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- dart_style 2.3.6 [analyzer args collection path pub_semver source_span]
- dbus 0.7.10 [args ffi meta xml]
- equatable 2.0.5 [collection meta]
- extended_image_library 4.0.3 [crypto flutter http_client_helper js path path_provider web]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 7.0.0 [meta path]
- file_selector_android 0.5.0+7 [file_selector_platform_interface flutter plugin_platform_interface]
- file_selector_ios 0.5.1+8 [file_selector_platform_interface flutter]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_web 0.9.4+1 [file_selector_platform_interface flutter flutter_web_plugins web]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.10.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.6 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js web]
- firebase_app_check_platform_interface 0.1.0+21 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.1.1+1 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js web]
- firebase_auth_platform_interface 7.2.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.10.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.13.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- firebase_crashlytics_platform_interface 3.6.27 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_in_app_messaging_platform_interface 0.2.4+27 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.29 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.7.1 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta web]
- firebase_performance_platform_interface 0.1.4+27 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.5 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js web]
- firebase_remote_config_platform_interface 1.4.27 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.5.0 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js web]
- firebase_storage_platform_interface 5.1.14 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.8.1 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta web]
- fixnum 1.1.0
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_image_compress_common 1.0.5 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_macos 1.0.2 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_ohos 0.0.2 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_platform_interface 1.0.5 [flutter plugin_platform_interface cross_file]
- flutter_image_compress_web 0.1.4+1 [flutter flutter_web_plugins flutter_image_compress_platform_interface js]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_secure_storage_linux 1.2.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.0.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.1.2 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 3.0.0 [ffi flutter flutter_secure_storage_platform_interface path path_provider win32]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- frontend_server_client 4.0.0 [async path]
- geocoding_android 3.3.0 [flutter geocoding_platform_interface]
- geocoding_ios 3.0.1 [flutter geocoding_platform_interface]
- geocoding_platform_interface 3.2.0 [flutter meta plugin_platform_interface]
- geolocator_android 4.5.4 [flutter geolocator_platform_interface meta uuid]
- geolocator_apple 2.3.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.2 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 3.0.0 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.2.3 [flutter geolocator_platform_interface]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.3.1+1 [meta web]
- google_maps 7.1.0 [js js_wrapping meta web]
- google_maps_flutter_android 2.7.0 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.5.2 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.6.0 [collection flutter plugin_platform_interface stream_transform]
- google_maps_flutter_web 0.5.6+2 [collection flutter flutter_web_plugins google_maps google_maps_flutter_platform_interface sanitize_html stream_transform web]
- google_mlkit_commons 0.6.1 [flutter]
- google_sign_in_android 6.1.22 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.5 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.4 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- graphs 2.3.1 [collection]
- hive 2.2.3 [meta crypto]
- html 0.15.4 [csslib source_span]
- http_client_helper 3.0.0 [http]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.1.7 [archive meta xml]
- image_editor_common 1.0.1 [flutter image_editor_platform_interface]
- image_editor_ohos 0.0.5 [flutter image_editor_platform_interface]
- image_editor_platform_interface 1.0.1 [flutter platform plugin_platform_interface]
- image_picker_android 0.8.9+5 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.3 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.9+2 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.4 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- in_app_review_platform_interface 2.0.5 [flutter url_launcher plugin_platform_interface platform]
- intl 0.18.1 [clock meta path]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- js_wrapping 0.7.4 [js]
- json_annotation 4.8.1 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- local_auth_android 1.0.37 [flutter flutter_plugin_android_lifecycle intl local_auth_platform_interface]
- local_auth_darwin 1.2.2 [flutter intl local_auth_platform_interface]
- local_auth_platform_interface 1.0.10 [flutter plugin_platform_interface]
- local_auth_windows 1.0.10 [flutter local_auth_platform_interface]
- logging 1.2.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- mime 1.0.5
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 2.0.0 [flutter]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- pdf_widget_wrapper 1.0.3 [flutter pdf]
- permission_handler_android 12.0.5 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.4 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.1 [flutter flutter_web_plugins permission_handler_platform_interface]
- permission_handler_platform_interface 4.2.1 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.7.4 [collection convert js]
- pool 1.5.1 [async stack_trace]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- qr 3.0.1 [meta]
- record_android 1.1.0 [flutter record_platform_interface]
- record_darwin 1.0.1 [flutter record_platform_interface]
- record_linux 0.7.1 [flutter record_platform_interface]
- record_platform_interface 1.0.2 [flutter plugin_platform_interface]
- record_web 1.0.5 [flutter flutter_web_plugins js record_platform_interface]
- record_windows 1.0.2 [flutter record_platform_interface path]
- rive_common 0.3.3 [collection ffi flutter flutter_web_plugins graphs http meta plugin_platform_interface]
- rxdart 0.27.7
- sanitize_html 2.1.0 [html meta]
- share_plus_platform_interface 3.4.0 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.5 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.3.0 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 2.0.0 [flutter flutter_web_plugins sign_in_with_apple_platform_interface]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.2 [flutter sqflite_common path]
- sqflite_common 2.5.4 [synchronized path meta]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- syncfusion_flutter_core 25.1.37 [vector_math flutter]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- url_launcher_android 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.0 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- vm_service 13.0.0
- watcher 1.1.0 [async path]
- web 0.5.1
- web_socket_channel 2.4.4 [async crypto stream_channel web]
- win32 5.3.0 [ffi]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>

### Additional context and comments

The whole stack trace was too huge for Github but i have pasted the 2 first relevant logs output. 

Feel free to tell me if you need more !

**Comment by russellwheatley** [comment]
How often is this occurring, @Tom3652?  

Is this your app version?
```
# Version: 2.5.0 (32)
```
Is this occurring on a particular android version?

**Comment by Tom3652** [comment]
Hi @russellwheatley !

It occurred already 4 times since my latest app release yesterday, i have sent the issue right after. 
> Version: 2.5.0 (32)
 
This is indeed my app version on the store.

It seems to be happening only on Android 11 and 14 so far, on at least 2 different phones : 

![Capture d’écran 2024-04-02 à 16 14 59](https://github.com/firebase/flutterfire/assets/32631467/044a9e7b-bcc7-4fa6-8655-21924bc7b7d7)
![Capture d’écran 2024-04-02 à 16 14 45](https://github.com/firebase/flutterfire/assets/32631467/29628998-ccb2-4d33-9e48-36a809d23e8e)

**Comment by Lyokone** [comment]
Hello, can you try the solution provided here: https://github.com/firebase/flutterfire/issues/12506
