### ISSUE TITLE
🐛 [firebase_core] Allow app initialization without credentials

### ISSUE THREAD

**Issue by fcoelho** [firebase/flutterfire#12658]
## What feature would you like to see?

I'd like to be able to access a database that provides anonymous access -- and for which I cannot generate credentials -- without credentials using FlutterFire. With the JS SDK, it's possible to initialize an app and subscribe to updates without explicit credentials:

```js
import { initializeApp } from "firebase/app";
import { getDatabase, onValue, ref } from "firebase/database";

async function main() {
  const app = initializeApp({
    databaseURL: "https://hacker-news.firebaseio.com",
  });

  const db = getDatabase(app);

  onValue(ref(db, "v0/updates"), (snapshot) => {
    console.log("on value callback:", snapshot.key, snapshot.val());
  });
}

main();
```

This is not possible with FlutterFire, which throws an error if I try to initialize the app without valid `apiKey`/`appId`/etc values:

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: const FirebaseOptions(
      apiKey: "",
      appId: "",
      messagingSenderId: "",
      projectId: "hacker-news",
      databaseURL: "https://hacker-news.firebaseio.com",
   ),
 );
}
```

```shell
$ flutter run
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:210:7)
<asynchronous suspension>
#1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
<asynchronous suspension>
#2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
<asynchronous suspension>
#3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:31)
<asynchronous suspension>
#4      main (package:myvohn/main.dart:7:3)
<asynchronous suspension>
```

**Comment by russellwheatley** [comment]
@fcoelho - thank you for the suggestion but this would be something of a major refactor for FlutterFire which isn't necessary. The client side credentials are not sensitive and there is no problem with using them.

**Comment by fcoelho** [comment]
@russellwheatley that's okay and thanks for the info. I don't know how I can get client-side credentials for this though since I can't use `FirebaseAuth.instance` before the app is initialised. Could you point me to some documentation I can read on this?
