### ISSUE TITLE
[flutterfire_configure]: Error: write EPIPE

### ISSUE THREAD

**Issue by altamisatmaja** [firebase/flutterfire#12991]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Description

[debug] [2024-06-23T20:01:55.019Z] Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:962:11)
    at Socket._write (node:net:974:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Ora.start (/usr/local/lib/node_modules/firebase-tools/node_modules/ora/index.js:304:17)
    at Command.actionFn (/usr/local/lib/node_modules/firebase-tools/lib/commands/projects-list.js:48:73)
    at /usr/local/lib/node_modules/firebase-tools/lib/command.js:228:25
[error] 
[error] Error: An unexpected error has occurred.

------
i've to try re-auth and re-install via npm and curl. but its not solved

### Reproducing the issue

-

### Firebase Core version

3.1.0

### Flutter Version

3.22.2

### Relevant Log Output

```shell
[debug] [2024-06-23T20:01:54.640Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=1000
[debug] [2024-06-23T20:01:55.019Z] Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:962:11)
    at Socket._write (node:net:974:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Ora.start (/usr/local/lib/node_modules/firebase-tools/node_modules/ora/index.js:304:17)
    at Command.actionFn (/usr/local/lib/node_modules/firebase-tools/lib/commands/projects-list.js:48:73)
    at /usr/local/lib/node_modules/firebase-tools/lib/command.js:228:25
[error] 
[error] Error: An unexpected error has occurred.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1

```

</details>

**Comment by russellwheatley** [comment]
Hey @altamisatmaja - could you open an issue on the relevant repository for the FlutterFire CLI: https://github.com/invertase/flutterfire_cli

Please provide relevant context for a reproduction, thanks 🙏
