### ISSUE TITLE
 [FirebaseAuth]: Unhandled Exception: type 'List<Object?>' is not a subtype of type 'PigeonUserInfo' in type cast

### ISSUE THREAD

**Issue by myproblemchild** [firebase/flutterfire#13167]
I'm having the same issue as in #13077, no suggestions from that thread or other sources worked so far. It seems I can't reopen the issue #13077, so I'm creating a new one.

```
try {
      final googleAccount = await _googleSignIn?.signIn();
      final googleAuth = await googleAccount?.authentication;
      final googleCredential = GoogleAuthProvider.credential(
        accessToken: googleAuth?.accessToken,
        idToken: googleAuth?.idToken,
      );
      await FirebaseAuth.instance.signInWithCredential(googleCredential);
    } catch (error, st) {
      //
    }
```
And I see it's printing
```
I/flutter (31925): error caught: type 'List<Object?>' is not a subtype of type 'PigeonUserDetails?' in type cast #0      PigeonUserCredential.decode (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:432:23)
I/flutter (31925): #1      _FirebaseAuthHostApiCodec.readValueOfType (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:830:37)
I/flutter (31925): #2      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
I/flutter (31925): #3      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:522:23)
I/flutter (31925): #4      _FirebaseAuthHostApiCodec.readValueOfType (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:840:22)
I/flutter (31925): #5      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
I/flutter (31925): #6      StandardMessageCodec.decodeMessage (package:flutter/src/services/message_codecs.dart:341:28)
I/flutter (31925): #7      BasicMessageChannel.send (package:flutter/src/services/platform_channel.dart:218:18)
```

Versions:
```
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.1
  firebase_crashlytics: ^4.0.4
  firebase_analytics: ^11.2.1
```

_Originally posted by @myproblemchild in https://github.com/firebase/flutterfire/issues/13077#issuecomment-2274270689_

**Comment by Lyokone** [comment]
Hello, I'm not reproducing this issue. Can you run `flutter clean` and try again?

**Comment by Lyokone** [comment]
Hello @myproblemchild, please follow the bug template so we can help you better.

**Comment by RafaelZasas** [comment]
Hi, My team and I are seeing the same issue. Are there any available resources to fix this issue?
