### ISSUE TITLE
🐛 [CLOUD FIRESTORE] Support for Combining array_contains_any and not_in Filters in Firestore

### ISSUE THREAD

**Issue by rrakesh28** [firebase/flutterfire#13210]
### Is your feature request related to a problem?
Yes, currently, when using Firestore in a Flutter application, there is a limitation that prevents combining array_contains_any filters with not_in filters in a single query. This results in an IllegalArgumentException being thrown. This limitation makes it difficult to perform complex queries that are required in many real-world applications.

### Describe the solution you'd like
I would like Firestore to support combining array_contains_any and not_in filters in a single query. This would allow developers to create more complex and powerful queries directly in Firestore, without needing to split the query into multiple parts or refactor the data structure.

### Additional context
Firebase Core Version: 3.0.0
Flutter Version: 3.22.3

Relevant Error Message:
```bash
java.lang.IllegalArgumentException: Invalid Query. You cannot use 'array_contains_any' filters with 'not_in' filters.
E/FLTFirestoreMsgCodec(30812): java.lang.IllegalArgumentException: Invalid Query. You cannot use 'array_contains_any' filters with 'not_in' filters.
E/FLTFirestoreMsgCodec(30812):     at com.google.firebase.firestore.Query.validateNewFieldFilter(Query.java:584)
E/FLTFirestoreMsgCodec(30812):     at com.google.firebase.firestore.Query.validateNewFilter(Query.java:594)
E/FLTFirestoreMsgCodec(30812):     at com.google.firebase.firestore.Query.where(Query.java:406)
E/FLTFirestoreMsgCodec(30812):     at com.google.firebase.firestore.Query.whereArrayContainsAny(Query.java:315)
E/FLTFirestoreMsgCodec(30812):     at io.flutter.plugins.firebase.firestore.utils.PigeonParser.parseQuery(PigeonParser.java:209)
```

Supporting this combination of filters would greatly enhance the flexibility and power of Firestore queries, especially in complex applications.

**Comment by Lyokone** [comment]
Hello @rrakesh28, unfortunately, it's not a feature request for FlutterFire, but directly for Firebase. You can request new features here: https://firebase.uservoice.com/forums/948424-general
