### ISSUE TITLE
[firebase_core & cloud_firestore]: Cannot pod install for macos

### ISSUE THREAD

**Issue by jimmyff** [firebase/flutterfire#13239]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Other

### Which platforms are affected?

macOS

### Description

Hey, I'm really struggling getting macos to build, I'm getting the following error:

```
[!] CocoaPods could not find compatible versions for pod "FirebaseFirestore":
  In Podfile:
    FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `8.15.0`)

    cloud_firestore (from `Flutter/ephemeral/.symlinks/plugins/cloud_firestore/macos`) was resolved to 5.3.0, which depends on
      Firebase/Firestore (~> 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseFirestore (~> 11.0.0)
```

relevant pubspec.lock:
```
  firebase_core:
    dependency: "direct main"
    description:
      name: firebase_core
      sha256: "06537da27db981947fa535bb91ca120b4e9cb59cb87278dbdde718558cafc9ff"
      url: "https://pub.dev"
    source: hosted
    version: "3.4.0"
  firebase_core_platform_interface:
    dependency: transitive
    description:
      name: firebase_core_platform_interface
      sha256: f7d7180c7f99babd4b4c517754d41a09a4943a0f7a69b65c894ca5c68ba66315
      url: "https://pub.dev"
    source: hosted
    version: "5.2.1"
  cloud_firestore:
    dependency: "direct main"
    description:
      name: cloud_firestore
      sha256: "77ac40d66a0fd585ca1e80ef3cbfd9df34462103bd4c1cf5950cb7d1f4c2e188"
      url: "https://pub.dev"
    source: hosted
    version: "5.3.0"
```

### Reproducing the issue

```Podfile
platform :osx, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  # Added by jimmy: https://firebase.flutter.dev/docs/firestore/overview/
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.15.0'

  use_frameworks!
  use_modular_headers!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
  end
end

```

### Firebase Core version

3.4.0

### Flutter Version

channel beta, 3.24.0-0.2.pre

### Relevant Log Output

```shell
jimmyff@jimmyff-mbp14 macos % pod install --repo-update --verbose 
  Preparing

Updating local specs repositories
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in
  repo update

Updating spec repo `trunk`
  CDN: trunk Relative path: deprecated_podspecs.txt, has ETag? W/"66d1e2d9-c07ce"
  CDN: trunk Relative path downloaded: deprecated_podspecs.txt, save ETag: W/"66d1e53f-c07ce"
  CDN: trunk Going to update 63 files
  CDN: trunk Relative path: CocoaPods-version.yml, has ETag? "66d1e53f-38"
  CDN: trunk Relative path: all_pods_versions_0_3_5.txt, has ETag? W/"66d1e53f-c80"
  CDN: trunk Relative path: all_pods_versions_0_6_a.txt, has ETag? W/"66d1e2d9-440"
  CDN: trunk Relative path: all_pods_versions_0_8_4.txt, has ETag? W/"66d1e2d9-42c"
  CDN: trunk Relative path: all_pods_versions_0_9_f.txt, has ETag? W/"66d1e53f-8b8"
  CDN: trunk Relative path: all_pods_versions_0_a_c.txt, has ETag? W/"66d1e53f-691"
  CDN: trunk Relative path: all_pods_versions_0_b_5.txt, has ETag? W/"66d1e53f-67e"
  CDN: trunk Relative path: all_pods_versions_1_8_e.txt, has ETag? W/"66d1e2d9-b2c"
  CDN: trunk Relative path: all_pods_versions_2_4_b.txt, has ETag? W/"66d1e2d9-83e"
  CDN: trunk Relative path: all_pods_versions_2_c_c.txt, has ETag? W/"66d1e53f-58c"
  CDN: trunk Relative path: all_pods_versions_2_d_6.txt, has ETag? W/"66d1e2d9-829"
  CDN: trunk Relative path: all_pods_versions_2_f_7.txt, has ETag? W/"66d1e2d9-500"
  CDN: trunk Relative path: all_pods_versions_3_1_8.txt, has ETag? W/"66d1e2d9-389"
  CDN: trunk Relative path: all_pods_versions_3_7_4.txt, has ETag? W/"66d1e53f-381"
  CDN: trunk Relative path: all_pods_versions_3_8_6.txt, has ETag? W/"66d1e53f-47f"
  CDN: trunk Relative path: all_pods_versions_3_b_6.txt, has ETag? W/"66d1e2d9-586"
  CDN: trunk Relative path: all_pods_versions_3_c_c.txt, has ETag? W/"66d1e2d9-62b"
  CDN: trunk Relative path: all_pods_versions_4_2_7.txt, has ETag? W/"66d1e2d9-621"
  CDN: trunk Relative path: all_pods_versions_4_2_c.txt, has ETag? W/"66d1e53f-4f0"
  CDN: trunk Relative path: all_pods_versions_4_7_f.txt, has ETag? W/"66d1e53f-976"
  CDN: trunk Relative path: all_pods_versions_5_4_9.txt, has ETag? W/"66d1e53f-a38"
  CDN: trunk Relative path: all_pods_versions_5_9_a.txt, has ETag? W/"66d1e2d9-79e"
  CDN: trunk Relative path: all_pods_versions_6_1_e.txt, has ETag? W/"66d1e2d9-56a"
  CDN: trunk Relative path: all_pods_versions_6_3_6.txt, has ETag? W/"66d1e2d9-9e4"
  CDN: trunk Relative path: all_pods_versions_6_8_6.txt, has ETag? W/"66d1e2d9-5e4"
  CDN: trunk Relative path: all_pods_versions_6_d_6.txt, has ETag? W/"66d1e2d9-52f"
  CDN: trunk Relative path: all_pods_versions_6_f_6.txt, has ETag? W/"66d1e53f-56d"
  CDN: trunk Relative path: all_pods_versions_7_1_d.txt, has ETag? W/"66d1e53f-752"
  CDN: trunk Relative path: all_pods_versions_7_4_b.txt, has ETag? W/"66d1e53f-5d2"
  CDN: trunk Relative path: all_pods_versions_7_9_1.txt, has ETag? W/"66d1e53f-3e5"
  CDN: trunk Relative path: all_pods_versions_7_c_c.txt, has ETag? W/"66d1e2d9-3a7"
  CDN: trunk Relative path: all_pods_versions_7_e_f.txt, has ETag? W/"66d1e2d9-2e0"
  CDN: trunk Relative path: all_pods_versions_8_1_e.txt, has ETag? W/"66d1e53f-421"
  CDN: trunk Relative path: all_pods_versions_8_3_c.txt, has ETag? W/"66d1e53f-579"
  CDN: trunk Relative path: all_pods_versions_8_8_9.txt, has ETag? W/"66d1e53f-493"
  CDN: trunk Relative path: all_pods_versions_8_b_d.txt, has ETag? W/"66d1e2d9-68f"
  CDN: trunk Relative path: all_pods_versions_8_e_2.txt, has ETag? W/"66d1e2d9-54e"
  CDN: trunk Relative path: all_pods_versions_9_1_0.txt, has ETag? W/"66d1e2d9-b2d"
  CDN: trunk Relative path: all_pods_versions_9_b_5.txt, has ETag? W/"66d1e53f-afe"
  CDN: trunk Relative path: all_pods_versions_a_d_a.txt, has ETag? W/"66d1e53f-377"
  CDN: trunk Relative path: all_pods_versions_a_d_d.txt, has ETag? W/"66d1e53f-52b"
  CDN: trunk Relative path: all_pods_versions_a_f_4.txt, has ETag? W/"66d1e53f-c26"
  CDN: trunk Relative path: all_pods_versions_b_3_c.txt, has ETag? W/"66d1e53f-f7b"
  CDN: trunk Relative path: all_pods_versions_b_b_9.txt, has ETag? W/"66d1e53f-46a"
  CDN: trunk Relative path: all_pods_versions_b_c_7.txt, has ETag? W/"66d1e53f-6bd"
  CDN: trunk Relative path: all_pods_versions_b_e_b.txt, has ETag? W/"66d1e53f-3b3"
  CDN: trunk Relative path: all_pods_versions_c_0_4.txt, has ETag? W/"66d1e53f-660"
  CDN: trunk Relative path: all_pods_versions_c_1_1.txt, has ETag? W/"66d1e2d9-3ac"
  CDN: trunk Relative path: all_pods_versions_c_8_0.txt, has ETag? W/"66d1e2d9-47b"
  CDN: trunk Relative path: all_pods_versions_c_8_7.txt, has ETag? W/"66d1e53f-a50"
  CDN: trunk Relative path: all_pods_versions_c_c_6.txt, has ETag? W/"66d1e53f-51e"
  CDN: trunk Relative path: all_pods_versions_c_e_3.txt, has ETag? W/"66d1e2d9-647"
  CDN: trunk Relative path: all_pods_versions_d_4_0.txt, has ETag? W/"66d1e53f-587"
  CDN: trunk Relative path: all_pods_versions_d_c_1.txt, has ETag? W/"66d1e53f-7e9"
  CDN: trunk Relative path: all_pods_versions_d_c_2.txt, has ETag? W/"66d1e2d9-8d1"
  CDN: trunk Relative path: all_pods_versions_e_2_0.txt, has ETag? W/"66d1e2d9-3d4"
  CDN: trunk Relative path: all_pods_versions_e_2_1.txt, has ETag? W/"66d1e53f-9c3"
  CDN: trunk Relative path: all_pods_versions_e_3_b.txt, has ETag? W/"66d1e53f-ea8"
  CDN: trunk Relative path: all_pods_versions_e_7_d.txt, has ETag? W/"66d1e2d9-525"
  CDN: trunk Relative path: all_pods_versions_e_9_8.txt, has ETag? W/"66d1e53f-702"
  CDN: trunk Relative path: all_pods_versions_e_d_4.txt, has ETag? W/"66d1e2d9-6df"
  CDN: trunk Relative path: all_pods_versions_f_2_a.txt, has ETag? W/"66d1e53f-7ed"
  CDN: trunk Relative path: all_pods_versions_f_8_8.txt, has ETag? W/"66d1e53f-796"
  CDN: trunk Relative path not modified: CocoaPods-version.yml
  CDN: trunk Relative path downloaded: all_pods_versions_0_8_4.txt, save ETag: W/"66d1e53f-42c"
  CDN: trunk Relative path not modified: all_pods_versions_0_3_5.txt
  CDN: trunk Relative path not modified: all_pods_versions_0_9_f.txt
  CDN: trunk Relative path not modified: all_pods_versions_0_b_5.txt
  CDN: trunk Relative path downloaded: all_pods_versions_2_d_6.txt, save ETag: W/"66d1e53f-829"
  CDN: trunk Relative path not modified: all_pods_versions_2_f_7.txt
  CDN: trunk Relative path not modified: all_pods_versions_4_2_7.txt
  CDN: trunk Relative path not modified: all_pods_versions_7_1_d.txt
  CDN: trunk Relative path not modified: all_pods_versions_7_4_b.txt
  CDN: trunk Relative path downloaded: all_pods_versions_0_6_a.txt, save ETag: W/"66d1e53f-440"
  CDN: trunk Relative path not modified: all_pods_versions_3_b_6.txt
  CDN: trunk Relative path not modified: all_pods_versions_5_4_9.txt
  CDN: trunk Relative path not modified: all_pods_versions_6_3_6.txt
  CDN: trunk Relative path not modified: all_pods_versions_7_9_1.txt
  CDN: trunk Relative path not modified: all_pods_versions_8_1_e.txt
  CDN: trunk Relative path not modified: all_pods_versions_8_3_c.txt
  CDN: trunk Relative path not modified: all_pods_versions_0_a_c.txt
  CDN: trunk Relative path not modified: all_pods_versions_3_8_6.txt
  CDN: trunk Relative path not modified: all_pods_versions_4_2_c.txt
  CDN: trunk Relative path downloaded: all_pods_versions_8_b_d.txt, save ETag: W/"66d1e53f-68f"
  CDN: trunk Relative path not modified: all_pods_versions_8_e_2.txt
  CDN: trunk Relative path not modified: all_pods_versions_9_b_5.txt
  CDN: trunk Relative path not modified: all_pods_versions_1_8_e.txt
  CDN: trunk Relative path not modified: all_pods_versions_2_c_c.txt
  CDN: trunk Relative path not modified: all_pods_versions_3_1_8.txt
  CDN: trunk Relative path not modified: all_pods_versions_3_c_c.txt
  CDN: trunk Relative path downloaded: all_pods_versions_5_9_a.txt, save ETag: W/"66d1e53f-79e"
  CDN: trunk Relative path not modified: all_pods_versions_6_d_6.txt
  CDN: trunk Relative path downloaded: all_pods_versions_6_1_e.txt, save ETag: W/"66d1e53f-56a"
  CDN: trunk Relative path not modified: all_pods_versions_6_8_6.txt
  CDN: trunk Relative path not modified: all_pods_versions_6_f_6.txt
  CDN: trunk Relative path not modified: all_pods_versions_3_7_4.txt
  CDN: trunk Relative path not modified: all_pods_versions_4_7_f.txt
  CDN: trunk Relative path not modified: all_pods_versions_8_8_9.txt
  CDN: trunk Relative path not modified: all_pods_versions_a_d_a.txt
  CDN: trunk Relative path not modified: all_pods_versions_a_d_d.txt
  CDN: trunk Relative path not modified: all_pods_versions_a_f_4.txt
  CDN: trunk Relative path downloaded: all_pods_versions_7_e_f.txt, save ETag: W/"66d1e53f-2e0"
  CDN: trunk Relative path not modified: all_pods_versions_b_3_c.txt
  CDN: trunk Relative path not modified: all_pods_versions_c_0_4.txt
  CDN: trunk Relative path not modified: all_pods_versions_b_e_b.txt
  CDN: trunk Relative path not modified: all_pods_versions_c_8_7.txt
  CDN: trunk Relative path not modified: all_pods_versions_d_c_2.txt
  CDN: trunk Relative path not modified: all_pods_versions_b_c_7.txt
  CDN: trunk Relative path not modified: all_pods_versions_d_c_1.txt
  CDN: trunk Relative path not modified: all_pods_versions_e_2_0.txt
  CDN: trunk Relative path not modified: all_pods_versions_e_7_d.txt
  CDN: trunk Relative path downloaded: all_pods_versions_c_e_3.txt, save ETag: W/"66d1e53f-647"
  CDN: trunk Relative path not modified: all_pods_versions_e_d_4.txt
  CDN: trunk Relative path not modified: all_pods_versions_f_2_a.txt
  CDN: trunk Relative path not modified: all_pods_versions_f_8_8.txt
  CDN: trunk Relative path not modified: all_pods_versions_b_b_9.txt
  CDN: trunk Relative path not modified: all_pods_versions_c_8_0.txt
  CDN: trunk Relative path not modified: all_pods_versions_d_4_0.txt
  CDN: trunk Relative path not modified: all_pods_versions_e_2_1.txt
  CDN: trunk Relative path not modified: all_pods_versions_e_3_b.txt
  CDN: trunk Relative path not modified: all_pods_versions_e_9_8.txt
  CDN: trunk Relative path not modified: all_pods_versions_c_c_6.txt
  CDN: trunk Relative path downloaded: all_pods_versions_2_4_b.txt, save ETag: W/"66d1e6e2-83e"
  CDN: trunk Relative path downloaded: all_pods_versions_9_1_0.txt, save ETag: W/"66d1e6e2-b2d"
  CDN: trunk Relative path downloaded: all_pods_versions_c_1_1.txt, save ETag: W/"66d1e6e2-3ac"
  CDN: trunk Relative path downloaded: all_pods_versions_7_c_c.txt, save ETag: W/"66d1e6e2-3a7"

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-RunnerTests`: (``)

Fetching external sources
-> Pre-downloading: `FirebaseFirestore` from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `8.15.0`
  > Copying FirebaseFirestore from
  `/Users/jimmyff/Library/Caches/CocoaPods/Pods/External/FirebaseFirestore/e4fb610867400ab6d3feb96b8d6fe477` to
  `Pods/FirebaseFirestore`
-> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
-> Fetching podspec for `cloud_firestore` from `Flutter/ephemeral/.symlinks/plugins/cloud_firestore/macos`
cloud_firestore: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
-> Fetching podspec for `firebase_auth` from `Flutter/ephemeral/.symlinks/plugins/firebase_auth/macos`
firebase_auth: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
-> Fetching podspec for `firebase_core` from `Flutter/ephemeral/.symlinks/plugins/firebase_core/macos`
firebase_core: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
-> Fetching podspec for `firebase_storage` from `Flutter/ephemeral/.symlinks/plugins/firebase_storage/macos`
firebase_storage: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
-> Fetching podspec for `shared_preferences_foundation` from `Flutter/ephemeral/.symlinks/plugins/shared_preferences_foundation/darwin`

Resolving dependencies of `Podfile`
  CDN: trunk Relative path: all_pods_versions_0_3_5.txt modified during this run! Returning local
  CDN: trunk Relative path: Specs/0/3/5/Firebase/11.1.0/Firebase.podspec.json exists! Returning local because
  checking is only performed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/11.0.0/Firebase.podspec.json exists! Returning local because
  checking is only performed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/11.0.0/Firebase.podspec.json exists! Returning local because
  checking is only performed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/11.0.0/Firebase.podspec.json exists! Returning local because
  checking is only performed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/11.0.0/Firebase.podspec.json exists! Returning local because
  checking is only performed in repo update
  CDN: trunk Relative path: all_pods_versions_c_0_4.txt modified during this run! Returning local
  CDN: trunk Relative path: Specs/c/0/4/Flutter/3.13.0/Flutter.podspec.json exists! Returning local because
  checking is only performed in repo update
  CDN: trunk Relative path: all_pods_versions_8_b_d.txt modified during this run! Returning local
  CDN: trunk Relative path: Specs/8/b/d/FirebaseCore/11.1.0/FirebaseCore.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/11.0.0/Firebase.podspec.json exists! Returning local because
  checking is only performed in repo update
[!] CocoaPods could not find compatible versions for pod "FirebaseFirestore":
  In Podfile:
    FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `8.15.0`)

    cloud_firestore (from `Flutter/ephemeral/.symlinks/plugins/cloud_firestore/macos`) was resolved to 5.3.0, which depends on
      Firebase/Firestore (~> 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseFirestore (~> 11.0.0)

/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
<internal:kernel>:90:in `tap'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:257:in `process_topmost_state'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:94:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:422:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:162:in `install!'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `<main>'
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

### Additional context and comments

[✓] Flutter (Channel beta, 3.24.0-0.2.pre, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
    • Flutter version 3.24.0-0.2.pre on channel beta at /Users/jimmyff/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7c6b7e9ca4 (4 weeks ago), 2024-07-30 14:26:44 +0700
    • Engine revision 6e4deceb38
    • Dart version 3.5.0 (build 3.5.0-323.2.beta)
    • DevTools version 2.37.2

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

**Comment by jimmyff** [comment]
I solved this by deleting macos directory, recreating with flutter create, then changing the deployment in xcode and podfile. I was then able to build
