### ISSUE TITLE
When Fetching data from fibaseFireStore im getting this error 

### ISSUE THREAD

**Issue by Roshan-pcy** [firebase/flutterfire#13440]
E/GoogleApiManager(  669): Failed to get service from broker. 
E/GoogleApiManager(  669): java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
E/GoogleApiManager(  669): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
E/GoogleApiManager(  669): 	at android.os.Parcel.createException(Parcel.java:2995)
E/GoogleApiManager(  669): 	at android.os.Parcel.readException(Parcel.java:2978)
E/GoogleApiManager(  669): 	at android.os.Parcel.readException(Parcel.java:2920)
E/GoogleApiManager(  669): 	at ampx.a(:com.google.android.gms@243734029@24.37.34 (190400-679256246):36)
E/GoogleApiManager(  669): 	at amoe.z(:com.google.android.gms@243734029@24.37.34 (190400-679256246):143)
E/GoogleApiManager(  669): 	at alvf.run(:com.google.android.gms@243734029@24.37.34 (190400-679256246):54)
E/GoogleApiManager(  669): 	at android.os.Handler.handleCallback(Handler.java:942)
E/GoogleApiManager(  669): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/GoogleApiManager(  669): 	at bqrp.mt(:com.google.android.gms@243734029@24.37.34 (190400-679256246):1)
E/GoogleApiManager(  669): 	at bqrp.dispatchMessage(:com.google.android.gms@243734029@24.37.34 (190400-679256246):5)
E/GoogleApiManager(  669): 	at android.os.Looper.loopOnce(Looper.java:211)
E/GoogleApiManager(  669): 	at android.os.Looper.loop(Looper.java:300)
E/GoogleApiManager(  669): 	at android.os.HandlerThread.run(HandlerThread.java:67)

then code is 
Future<void> fetchValueFromFirestore() async {
  try {
    print("Fetching data from Firestore...");
    final firestore = FirebaseFirestore.instance;

    DocumentSnapshot snapshot = await firestore
        .collection('ads')
        .doc('123')
        .get();

    if (snapshot.exists) {
      adload = snapshot['adss'];
      openAd = snapshot['openads'];
      print("Data fetched successfully: $adload, $openAd");
    } else {
      print("Document does not exist");
    }
  } catch (e) {
    print("Error fetching Firestore data: ${e.toString()}");
  }
}

data is getting currectly still this error showing in console
<img width="717" alt="image" src="https://github.com/user-attachments/assets/88a137e1-51c8-4a62-b040-3d75c8635aff">

version is using : cloud_firestore: ^5.2.1
tested physical device Api level 33

**Comment by SelaseKay** [comment]
I'm unable to reproduce this issue. This does not seem to be related to `cloud_firestore`. It could be coming from other libraries your app depends on. Kindly try running the `cloud_firestore` example app on this repo and provide feedback on the outcome. Also, please share your dependencies.

**Comment by Lyokone** [comment]
You are using the template for Documentation. Please use the correct issue template.

**Comment by Roshan-pcy** [comment]
could u explain what do u mean by template for documentation? any idea

**Comment by vedatsalmis** [comment]
I'am facing same error. it is occured when any function which is using firestore functions is called for the first time. for second call, there is no error.

**Comment by vedatsalmis** [comment]
> any solution for that when we call second time there is no error so , then how u slaved this problem?

The problem is not solved. While the application is opening, I am pulling some data from firestore in the background. After pulling that data, this error occurs. However, when I try to pull other data from firestore while the application is open, this error does not occur. I started to encounter this problem after upgrading Flutter. Then I created a new project and added only firestore and firebase core packages and tested the same thing and I encountered the same error again. This error message does not harm the application's operation, but I cannot understand why it occurs.

**Comment by Roshan-pcy** [comment]
same for me also it is not affecting my app  performance ,but i do not know how to solve that problem i tried all , but it is showing once at first time when app load.
