### ISSUE TITLE
[Firebase Analytics]:  (Xcode): Undefined symbols: IOS crashes Flutter 3.24.3 with Analytics Error

### ISSUE THREAD

**Issue by tyypgzl** [firebase/flutterfire#13549]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

iOS

### Description

I create new flutter project with this command `fvm flutter create . --project-name mypretty --org dev.tagstudio --platform=android,ios -e.`
Adding firebase deps on pubspec with this version.
```
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
```
and run this command flutterfire configure. select project ...etc
Everythink is succesful until this step. I run project in ios 17.0 and throw this exception message.
```
Launching lib/main.dart on iPhone 11 in debug mode...
Xcode build done.                                           16.6s
Failed to build iOS app
Error (Xcode): Undefined symbols:

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 11.

Exited (1).
```

resolved to remove analytics package, why not running with analytics on ios?

`flutter run -v` result 
```
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "documentLocationInCreatingWorkspace" : {
                       "_type" : {
                         "_name" : "DocumentLocation"
                       },
                       "concreteTypeName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "Xcode3ProjectDocumentLocation"
                       },
                       "url" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "file:\/\/\/Users\/tayyipguzel\/Desktop\/brick_test\/ios\/Pods\/Pods.xcodeproj#Timestamp=751443174.883219&XcodeLocation=%7
                         B%22Selection%22:%7B%22Editor%22:%22Xcode3BuildSettingsEditor%22,%22Target%22:%22PromisesSwift%22,%22Xcode3BuildSettingsEd
                         itorLocations%22:%5B%7B%22Selected%20Build%20Properties%22:%5B%22IPHONEOS_DEPLOYMENT_TARGET%22%5D%7D%5D%7D%7D"
                       }
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Target Integrity"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported
                       deployment target versions is 12.0 to 17.0.99."
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Warning"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Run script build phase 'FlutterFire: \"flutterfire upload-crashlytics-symbols\"' will be run during every build
                       because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or
                       configure it to run in every build by unchecking \"Based on dependency analysis\" in the script phase."
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Warning"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Ignoring duplicate libraries: '-lc++'"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Warning"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found"
                     }
                   }
                 ]
               }
             },
             "metadataRef" : {
               "_type" : {
                 "_name" : "Reference"
               },
               "id" : {
                 "_type" : {
                   "_name" : "String"
                 },
                 "_value" : "0~z9UqQ8xptk9BAlIH-ZC2oW4POL5gstqteLJCG0H2zUKeTnHCJro-sHilkREtAnx5iIU48tgLr1t3YxAW2N99vA=="
               },
               "targetType" : {
                 "_type" : {
                   "_name" : "TypeDefinition"
                 },
                 "name" : {
                   "_type" : {
                     "_name" : "String"
                   },
                   "_value" : "ActionsInvocationMetadata"
                 }
               }
             },
             "metrics" : {
               "_type" : {
                 "_name" : "ResultMetrics"
               },
               "errorCount" : {
                 "_type" : {
                   "_name" : "Int"
                 },
                 "_value" : "2"
               },
               "warningCount" : {
                 "_type" : {
                   "_name" : "Int"
                 },
                 "_value" : "7"
               }
             }
           }
[   +5 ms] Failed to build iOS app
[   +1 ms] Error (Xcode): Undefined symbols:
           
[   +1 ms] Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
           
[        ] Could not build the application for the simulator.
[        ] Error launching application on iPhone 11.
[   +1 ms] "flutter run" took 23,721ms.
[  +22 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:874:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[ +204 ms] ensureAnalyticsSent: 203ms
[        ] Running 2 shutdown hooks
[   +7 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
```

### Reproducing the issue

1- create flutter project with 3.24.3 version
2- add firebase deps as bellow
```
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
```
3- run flutter pub get and cd ios && pod install
4- run on ios 17 emulator

### Firebase Core version

3.6.0

### Flutter Version

3.24.3

### Relevant Log Output

```shell
Launching lib/main.dart on iPhone 11 in debug mode...
Xcode build done.                                           16.6s
Failed to build iOS app
Error (Xcode): Undefined symbols:

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 11.

Exited (1).
```
```


### Flutter dependencies

<!--- Look below for instructions on how to share your Flutter Dependencies. --->

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.5.3
Flutter SDK 3.24.3
mypretty 0.1.0

dependencies:
- firebase_analytics 11.3.3 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 3.6.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.1.3 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 4.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.44 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- firebase_analytics_platform_interface 4.2.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.10+2 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.3.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.18.1 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.6.44 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 4.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 14.2.5
- web 1.1.0

```

</details>

**Comment by SelaseKay** [comment]
Hi @tyypgzl, this issue seems to be related to https://github.com/firebase/flutterfire/issues/13277. What Xcode version are you using?

**Comment by tyypgzl** [comment]
@SelaseKay Xcode 15.0

**Comment by SelaseKay** [comment]
Kindly try updating your Xcode to see if it resolves your issue.

**Comment by tyypgzl** [comment]
I cant upgrade the version of xcode right now, new versions are not working on my old project, any solution?

**Comment by SelaseKay** [comment]
Hi @tyypgzl, unfortunately, as far as I know, the only way to resolve this issue is by upgrading your Xcode.

**Comment by rakib205** [comment]
Same issue.

**Comment by nevil-softices** [comment]
same issue: Xcode v15.2

**Comment by stilus-tayyipguzel** [comment]
I update xcode to 16.1 and resolved for me.

**Comment by russellwheatley** [comment]
Thank you for confirming upgrade to Xcode 16.1 resolved the issue for you, @tyypgzl 🙏
