### ISSUE TITLE
[firebase_in_app_messaging]: java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'

### ISSUE THREAD

**Issue by mehmetartun** [firebase/flutterfire#13560]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

In-App Messaging

### Which platforms are affected?

Android

### Description

When running the example for the plugin I get the following error about not finding **com.google.android.gms** and the functionality doesn't work. Also, I don't get the installation ID as described in the docs, I get it through the package `firebase_app_installations` but I'm not able receive any in-app messages even when specifying this as test device id:
```text
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Connecting to VM Service at ws://127.0.0.1:52644/5suRnfzT95I=/ws
Connected to the VM Service.
D/TrafficStats(29818): tagSocket(151) with statsTag=0xffffffff, statsUid=-1
W/iolo.fcmflutter(29818): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (unsupported, reflection, allowed)
I/flutter (29818): App Installation ID: cHIavCkOR7qBhtxTvMUlpb
W/iolo.fcmflutter(29818): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (unsupported, reflection, allowed)
I/FIAM.Headless(29818): Successfully fetched 1 messages from backend
I/FIAM.Headless(29818): Already impressed campaign copy of Test In App ? : false
I/FIAM.Headless(29818): App foreground rate limited ? : true
D/ProfileInstaller(29818): Installing profile for com.vidiolo.fcmflutter
E/GoogleApiManager(29818): Failed to get service from broker. 
E/GoogleApiManager(29818): java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
E/GoogleApiManager(29818): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3183)
E/GoogleApiManager(29818): 	at android.os.Parcel.createException(Parcel.java:3167)
E/GoogleApiManager(29818): 	at android.os.Parcel.readException(Parcel.java:3150)
E/GoogleApiManager(29818): 	at android.os.Parcel.readException(Parcel.java:3092)
E/GoogleApiManager(29818): 	at angb.a(:com.google.android.gms@244333029@24.43.33 (190400-689789078):36)
E/GoogleApiManager(29818): 	at anei.z(:com.google.android.gms@244333029@24.43.33 (190400-689789078):143)
E/GoogleApiManager(29818): 	at amln.run(:com.google.android.gms@244333029@24.43.33 (190400-689789078):54)
E/GoogleApiManager(29818): 	at android.os.Handler.handleCallback(Handler.java:959)
E/GoogleApiManager(29818): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/GoogleApiManager(29818): 	at bsuh.mC(:com.google.android.gms@244333029@24.43.33 (190400-689789078):1)
E/GoogleApiManager(29818): 	at bsuh.dispatchMessage(:com.google.android.gms@244333029@24.43.33 (190400-689789078):5)
E/GoogleApiManager(29818): 	at android.os.Looper.loopOnce(Looper.java:232)
E/GoogleApiManager(29818): 	at android.os.Looper.loop(Looper.java:317)
E/GoogleApiManager(29818): 	at android.os.HandlerThread.run(HandlerThread.java:85)
I/iolo.fcmflutter(29818): Background concurrent mark compact GC freed 14MB AllocSpace bytes, 12(240KB) LOS objects, 80% free, 6066KB/29MB, paused 516us,10.066ms total 69.966ms
```

Installed versions
```yaml
  firebase_app_installations: ^0.3.1+4
  firebase_core: ^3.6.0
  firebase_in_app_messaging: ^0.8.0+8
  flutter:
    sdk: flutter
```

```text
flutter doctor -v
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
    • Flutter version 3.24.4 on channel stable at /Users/mehmetartun/Utilities/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (5 days ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/mehmetartun/Library/Android/sdk
    • Platform android-34, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile)                • 2C161FDH200G7G        • android-arm64  • Android 14 (API 34)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 130.0.6723.70
    ! Error: Browsing on the local area network for Mehmet XR. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Reproducing the issue

Try to run the example of the `firebase_in_app_messaging` plugin on Android. (I am running on real device)

### Firebase Core version

3.6.0  and (0.8.0+8 for firebase_in_app_messaging)

### Flutter Version

3.24.4

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by mehmetartun** [comment]
Flutter dependencies

```text
Dart SDK 3.5.4
Flutter SDK 3.24.4
firebase_in_app_messaging_example 0.0.0

dependencies:
- firebase_app_installations 0.3.1+4 [firebase_app_installations_platform_interface firebase_app_installations_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 3.6.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_in_app_messaging 0.8.0+8 [firebase_core firebase_core_platform_interface firebase_in_app_messaging_platform_interface flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

transitive dependencies:
- _flutterfire_internals 1.3.44 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- firebase_app_installations_platform_interface 0.1.4+44 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_installations_web 0.1.6+2 [_flutterfire_internals firebase_app_installations_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.3.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.18.1 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_in_app_messaging_platform_interface 0.2.4+44 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 14.2.5
- web 1.1.0
```

**Comment by SelaseKay** [comment]
Hi @mehmetartun, thanks for the report. However, there's no mention of FlutterFire in the stack trace. You can follow [this issue tracker](https://issuetracker.google.com/issues/369219148) for more info.
