### ISSUE TITLE
[core]: Windows desktop build error, firebase_cpp_sdk_windows does not contain a CMakeLists.txt file

### ISSUE THREAD

**Issue by charneykaye** [firebase/flutterfire#16912]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Core

### Description

I have added firebase analytics to my app and I expected to be able to build the app. Everything is going OK for Android, iOS, and macOS desktop. However, for Windows desktop, when trying to build the app, I get a build error that CMakeLists.txt not found in expected build artifacts.

### Reproducing the issue

1. Create Flutter 3.5.4 app
2. Install Firebase Analytics via Flutterfire https://firebase.flutter.dev/docs/cli

### Firebase Core version

3.8.0

### Flutter Version

3.5.4

### Relevant Log Output

```shell
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:119 (add_subdirectory):
  The source directory

    X:/StarHarvesterZero/build/windows/x64/extracted/firebase_cpp_sdk_windows

  does not contain a CMakeLists.txt file.


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:125 (get_target_property):
  get_target_property() called with non-existent target "firebase_app".


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:126 (string):
  string sub-command REPLACE requires at least four arguments.


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:127 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  firebase_app


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:125 (get_target_property):
  get_target_property() called with non-existent target "firebase_auth".


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:126 (string):
  string sub-command REPLACE requires at least four arguments.


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:127 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  firebase_auth


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:125 (get_target_property):
  get_target_property() called with non-existent target "firebase_storage".


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:126 (string):
  string sub-command REPLACE requires at least four arguments.


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:127 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  firebase_storage


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:125 (get_target_property):
  get_target_property() called with non-existent target "firebase_firestore".


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:126 (string):
  string sub-command REPLACE requires at least four arguments.


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:127 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  firebase_firestore


Error: Unable to generate build files
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by charneykaye** [comment]
I have attempted a Flutter upgrade, project clean and regenerate my windows CMakeFiles.txt (which ended up being identical). The pubspec.yaml is the same but some of the transitive dependencies resolved to newer versions. Now I am seeing different errors. The vibe is that I'm missing some C libraries required to build firebase locally.

```
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_desktop.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_desktop.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_log.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_log.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_options.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_options.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_common.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_common.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_mutex_windows.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_mutex_windows.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_date_provider.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_date_provider.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_controller_desktop.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_controller_desktop.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_log_stdio.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_log_stdio.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_idl_parser.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_idl_parser.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_google_services_resource.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_google_services_resource.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_logger.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_logger.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_callback.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_callback.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_cleanup_notifier.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_cleanup_notifier.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_util.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_util.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_storage_desktop.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_storage_desktop.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_scheduler.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_scheduler.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_zlibwrapper.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_zlibwrapper.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_base64.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_base64.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant_util.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant_util.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_util.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_util.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_reference_counted_future_impl.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_reference_counted_future_impl.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_filesystem_desktop_windows.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_filesystem_desktop_windows.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_thread_cpp11.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_thread_cpp11.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_deflate.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_deflate.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_inflate.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_inflate.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_crc32.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_crc32.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_gzipheader.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_gzipheader.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_adler32.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_adler32.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_zutil.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_zutil.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_trees.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_trees.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_inftrees.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_inftrees.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_inffast.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_inffast.obj)' or at ''; linking object as if no debug info [X:\StarHarvesterZero\build\windows\x64\runner\star_harvester_zero.vcxproj]
√ Built build\windows\x64\runner\Debug\star_harvester_zero.exe
Debug service listening on ws://127.0.0.1:58088/DvUoMOmpidg=/ws
Syncing files to device Windows...
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: MissingPluginException(No implementation found for method Analytics#setDefaultEventParameters on channel plugins.flutter.io/firebase_analytics)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      FirebaseAnalytics.setDefaultEventParameters (package:firebase_analytics/src/firebase_analytics.dart:167:5)
<asynchronous suspension>
#2      main (package:star_harvester_zero/main.dart:88:5)
<asynchronous suspension>
```

**Comment by charneykaye** [comment]
Maybe related to https://github.com/firebase/flutterfire/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen
