### ISSUE TITLE
🐛 [firebase_core] MissingPluginException(No implementation found for method Firebase#initializeCore) on specific devices

### ISSUE THREAD

**Issue by tgpsantos** [firebase/flutterfire#4997]
## Bug report

**Describe the bug**
Hello! Recently we redesigned our app to use Flutter. We are now proceding to a full rollback, and a significant part of our users are complaining to have problems initializing the app: they only see a black screen, or get stuck in the launcher.

After digging a little deeper (there were no crashlytics events) we realized that this error is happening with devices that are "relatively" old, and are failing when `Firebase.initializeApp()` gets called. This is the error log:

<details><summary>MissingPluginException error</summary>

```
E/flutter ( 6080): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
E/flutter ( 6080): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 6080): <asynchronous suspension>
E/flutter ( 6080): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 6080): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:345:41)
E/flutter ( 6080): #3      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:30:36)
E/flutter ( 6080): #4      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:75:13)
E/flutter ( 6080): #5      Firebase.initializeApp (package:firebase_core/src/firebase.dart:44:25)
```

</details>

Example of devices that have this problem:
- Huawei Y6 2017
- Samsung S4
- Huawei p8 (ALE-L21)
- Cat S60
- Samsung J3 2016
- Neffos Y5
- P8 Lite
- LG G7

This error happens both in debug or release versions.

Is there any reason why this is happening only on these devices, while properly working on the others? 

I'll gladly provide more info. This is of uttermost importance to us, as it is preventing many users from using our app in production.

### Steps to reproduce

Simply run `initializeApp` on the devices that were mentioned. Other similarly old devices should probably have the same issue. Recent devices work flawlessly in all the plugins used from firebase (core, auth, crashlytics, remote config, etc)

### Aditional info

- 'com.google.gms:google-services:4.3.5'
- 'com.android.tools.build:gradle:4.0.2'
- distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip (tried with 6.1.1 as well)

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1316], locale pt-PT)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.4
Flutter SDK 1.22.5

dependencies:
_preview chewie video_player connectivity volume_control auto_size_text sensors webview_flutter preload_page_view clipboard firebase_dynamic_links flutter_tts audioplayers fi
rebase_analytics firebase_crashlytics path_provider firebase_storage flutter_ffmpeg wakelock percent_indicator animated_overflow fl_chart disk_space shared_preferences intl f
lutter_holo_date_picker animations flutter_rating_bar package_info font_awesome_flutter sign_in_with_apple permission_handler sliver_tools image_picker image_cropper implicit
ly_animated_reorderable_list flutter_slidable in_app_update upgrader firebase_remote_config firebase_messaging version url_launcher cached_network_image shimmer]
- e2e 0.2.4+4 [flutter flutter_test]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_launcher_icons 0.7.5 [image args yaml]

dev dependencies:
- flutter_driver 0.0.0 [file json_rpc_2 meta path web_socket_channel vm_service_client webdriver flutter flutter_test fuchsia_remote_debug_protocol archive args async boolean
_selector characters charcode clock collection convert crypto fake_async matcher platform process pub_semver source_span stack_trace stream_channel string_scanner sync_http t
erm_glyph test_api typed_data vector_math]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_cha
nnel string_scanner term_glyph typed_data]
- pedantic 1.9.2 [meta]

transitive dependencies:
- cloud_firestore 0.16.0 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cloud_firestore_platform_interface 3.0.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.3.0+1 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- firebase 7.3.0 [http http_parser js]
- firebase_analytics 7.0.1 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth 0.20.0+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_auth_platform_interface 3.0.1 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+6 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics 0.4.0+1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_crashlytics_platform_interface 1.1.6 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_dynamic_links 0.7.0+1 [flutter firebase_core]
- firebase_messaging 8.0.0-dev.14 [meta flutter firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web]
- firebase_messaging_platform_interface 1.0.0-dev.10 [flutter meta firebase_core plugin_platform_interface]
- firebase_messaging_web 0.1.0-dev.5 [flutter flutter_web_plugins meta firebase_core firebase_core_web firebase_messaging_platform_interface js service_worker]
- firebase_remote_config 0.6.0 [flutter firebase_core]
- firebase_storage 7.0.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]
- firebase_storage_platform_interface 1.0.4 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_web 0.1.1+3 [async crypto firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_facebook_login 3.0.0 [flutter collection]
- fuchsia_remote_debug_protocol 0.0.0 [json_rpc_2 process web_socket_channel flutter_test flutter_driver archive args async boolean_selector charcode clock collection convert
 crypto fake_async file matcher meta path platform pub_semver source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math vm_se
rvice_client webdriver]
- google_sign_in 4.5.9 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.1+1 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]

```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @tgpsantos 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/4455.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by tgpsantos** [comment]
@markusaksli-nc that issue seems to be related to a release issue when using minify/proguard. 

My implementation works flawlessly in most devices, except on a couple of smartphones (which I mentioned). It seems it's a completely different problem, therefore could you kindly reopen this issue? Thank you for your attention

**Comment by markusaksli-nc** [comment]
Yeah on a closer read you are right. I don't have any of these devices to test this so I'll label it for now.

**Comment by tgpsantos** [comment]
@markusaksli-nc thank you for your consideration. 

Updated list of devices above, we've just got a feedback that is happening on Asus ZenFone 3

**Comment by tgpsantos** [comment]
Added Samsung J3 2016 and Neffos Y5

**Comment by tgpsantos** [comment]
Added P8 lite and LG G7

**Comment by Lyokone** [comment]
Hello, we don't reproduce this issue on the latest version so I'll close it for now.
If you still have the issue, feels free to reopen the issue.
