### ISSUE TITLE
🐛 [firebase_auth] Linking an already linked phone number with a different user succeeds instead of throwing exception on Android

### ISSUE THREAD

**Issue by vinnytwice** [firebase/flutterfire#5196]
I use phone verification ( I use Bloc ) and once verified link the new AuthCredential to the legged in  firebase user using `firebase_auth: 0.18.3`package. 
```
class PhoneAuthenticationBloc
    extends Bloc<AuthenticationEvent, AuthenticationState> {
  final UserRepository _userRepository;


  PhoneAuthenticationBloc({@required UserRepository userRepository})
      : assert(userRepository != null),
        _userRepository = userRepository;

  String verificationId = "";


  @override
  AuthenticationState get initialState => Uninitialized();

  @override
  Stream<AuthenticationState> mapEventToState(
      AuthenticationEvent event) async* {
    // phone verification
    if (event is VerifyPhoneNumberEvent) {
      print('VerifyPhoneNumberEvent received');
      yield VerifyingState();
      yield* _mapVerifyPhoneNumberToState(event);
    }
    if (event is PhoneCodeSentEvent) {
      print('PhoneCodeSentEvent received');
      yield OtpSentState();
    }
    if (event is VerificationCompletedEvent) {
      print('VerificationCompletedEvent received');
      yield VerificationCompleteState(firebaseUser: event.firebaseUser, isVerified: event.isVerified);
    }
    if (event is VerificationExceptionEvent) {
      print('VerificationExceptionEvent received');
      yield VerificationExceptionState(message: event.message);
    }

    if ( event is PhoneCodeAutoRetrievalTimeoutEvent){
      yield PhoneCodeAutoRetrievalTimeoutState(verificationId: event.verificationId);
    }

    if(event is SendVerificationCodeEvent) {
      yield VerifyingState();
      yield*_mapVerificationCodeToState(event);
    }


  }

  Stream<AuthenticationState> _mapVerifyPhoneNumberToState(VerifyPhoneNumberEvent event) async* {
    print('_mapVerifyPhoneNumberToState  started');

    final phoneVerificationCompleted = (AuthCredential authCredential) {
      print('_mapVerifyPhoneNumberToState PhoneVerificationCompleted');
      _userRepository.getCurrentUser().catchError((onError) {
        print('_mapVerifyPhoneNumberToState PhoneVerificationCompleted error: $onError');
      }).then((user) {
        add(VerificationCompletedEvent(firebaseUser: user, isVerified:  true));
      });
    };
    final phoneVerificationFailed = (FirebaseAuthException authException) {
      print('_mapVerifyPhoneNumberToState PhoneVerificationFailed');
      print(authException.message);
      add(VerificationExceptionEvent(onError.toString()));
    };
    final phoneCodeSent = (String verificationId, [int forceResent]) {
      print('_mapVerifyPhoneNumberToState PhoneCodeSent');
      this.verificationId = verificationId;
      add(PhoneCodeSentEvent());
    };
    final phoneCodeAutoRetrievalTimeout = (String verificationId) {
      print('_mapVerifyPhoneNumberToState PhoneCodeAutoRetrievalTimeout');
      this.verificationId = verificationId;
      add(PhoneCodeAutoRetrievalTimeoutEvent(verificationId: verificationId));
    };

    await _userRepository.verifyPhone(
        phoneNumber: event.phoneNumber,
        timeOut: Duration(seconds: 0),
        phoneVerificationFailed: phoneVerificationFailed,
        phoneVerificationCompleted: phoneVerificationCompleted,
        phoneCodeSent: phoneCodeSent,
        autoRetrievalTimeout: phoneCodeAutoRetrievalTimeout);
  }


  Stream<AuthenticationState> _mapVerificationCodeToState(SendVerificationCodeEvent event) async* {
    print('_mapVerificationCodeToState started');
    UserCredential result = await _userRepository.verifyAndLinkAuthCredentials(verificationId: verificationId, smsCode: event.smsCode)
          .catchError((e){
            print('verifyAndLinkAuthCredentials error: $e');
      });
      print(result);

      if (result != null) {
        yield VerificationCompleteState(firebaseUser: result.user, isVerified: true);
      } else {
        yield OtpExceptionState(message: "Invalid otp!", verificationId: verificationId);
      }
  }
}
```
and the two method called from the other repository are:
```
Future<void> verifyPhone(
      {@required String phoneNumber,
      @required Duration timeOut,
      @required PhoneVerificationFailed phoneVerificationFailed,
      @required PhoneVerificationCompleted phoneVerificationCompleted,
      @required PhoneCodeSent phoneCodeSent,
      @required PhoneCodeAutoRetrievalTimeout autoRetrievalTimeout}) async {

    await _firebaseAuth.verifyPhoneNumber(
        phoneNumber: phoneNumber,
        timeout: timeOut,
        verificationCompleted: phoneVerificationCompleted,
        verificationFailed: phoneVerificationFailed,
        codeSent: phoneCodeSent,
        codeAutoRetrievalTimeout: autoRetrievalTimeout);
  }

  Future<UserCredential> verifyAndLinkAuthCredentials(
  {@required String verificationId, @required String smsCode}) async {
    AuthCredential authCredential = PhoneAuthProvider.credential(
        verificationId: verificationId, smsCode: smsCode);
    User user = _firebaseAuth.currentUser;
    print('user phone number is ${user.phoneNumber}'); // prints correct phone number

    /// New : relink if already phone verified
    
    return user.phoneNumber.isNotEmpty
        ? user.reauthenticateWithCredential(authCredential).catchError((e){
      print('UserRepository.verifyAndLinkAuthCredentials() reauthenticateWithCredential error: $e');
    })
        : user.linkWithCredential(authCredential).catchError((e) {
      print('UserRepository.verifyAndLinkAuthCredentials() linkWithCredential error: $e');
    });



    /// Old only working for new numbers 
    // return user.linkWithCredential(authCredential).catchError((e) {
    //   print('UserRepository.verifyAndLinkAuthCredentials() linkWithCredential error: $e');
    // });
  }
```
I have mixed behaviours:
1. I have the correct behaviour when I try to use an already verified number ( my own phone number on Android ) associated with an account ( my own ), `codeSent` callback isn't called and `phoneVerificationCompleted` is called.

2. Using a different phone number ( my own phone number on Android ) for the same account ( my own ), correctly throws the error [firebase_auth/user-mismatch] The supplied credentials do not correspond to the previously signed in user.

3. If instead I try to use the same phone number ( my own phone number on Android already associated with my own account ) to verify phone for another account it should thow an error ( and it used to throw it ) but instead it behaves just the same, `codeSent` callback isn't called and `phoneVerificationCompleted` is called, while in Firebase console the phone number doesn't get associated with the second account ( which is correct ). 

Can you see why is this 3rd case succeeds instead of failing?

Flutter doctor -v:
```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E287 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/vinnytwice/Developer/flutter
    • Framework revision 7891006299 (3 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/vinnytwice/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Thank you very much.

**Comment by markusaksli-nc** [comment]
Hi @vinnytwice 
Could you please provide your `flutter pub deps -- --style=compact`?
The description was a bit confusing so am I understanding correctly that when trying to link an already linked phone number to a different user it doesn't throw an error but just never does anything?
Thank you

**Comment by vinnytwice** [comment]
@markusaksli-nc Hi, when trying to link an already linked phone number to a different user it doesn't throw an error but phoneVerificationCompleted call back is called like when the phone verification succeds.

**Comment by vinnytwice** [comment]
@markusaksli-nc here it is:
```
Dart SDK 2.10.4
Flutter SDK 1.22.5
fixit_cloud_biking 1.0.0+1

dependencies:
- audioplayers 0.15.1 [uuid path_provider flutter flutter_web_plugins]
- basic_utils 1.9.3 [http logging json_annotation]
- cloud_firestore 0.14.3 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cupertino_icons 0.1.3
- equatable 1.2.3 [collection meta]
- firebase_analytics 5.0.16 [meta flutter firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.18.2 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.2 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_database 4.3.0 [flutter firebase_core]
- firebase_messaging 7.0.3 [meta flutter firebase_core]
- firebase_remote_config 0.4.2 [flutter firebase_core]
- firebase_storage 5.0.1 [flutter firebase_core firebase_core_platform_interface firebase_storage_platform_interface quiver]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 3.2.0 [flutter bloc provider]
- flutter_local_notifications 1.4.4+2 [flutter platform flutter_local_notifications_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_map 0.8.2 [flutter tuple latlong positioned_tap_detector transparent_image async flutter_image cached_network_image sqflite path_provider vector_math]
- flutter_map_marker_cluster 0.2.7 [flutter flutter_map latlong]
- flutter_map_tappable_polyline 0.3.1 [flutter flutter_map]
- flutter_slidable 0.5.5 [flutter]
- font_awesome_flutter 8.11.0 [flutter]
- geolocator 6.0.0+4 [flutter geolocator_platform_interface]
- google_sign_in 4.5.1 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- http 0.12.2 [http_parser path pedantic]
- image_picker 0.6.7+7 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- intl 0.16.1 [path]
- latlong 0.6.1 [logging console_log_handler validate intl]
- meta 1.3.0-nullsafety.3
- path_provider 1.6.11 [flutter path_provider_platform_interface path_provider_macos path_provider_linux]
- scrollable_positioned_list 0.1.7 [flutter meta]
- sembast 2.4.7+6 [meta path synchronized]
- smooth_star_rating 1.1.1 [flutter]
- sprintf 4.1.0
- uuid 2.2.0 [crypto convert]

dev dependencies:
- bloc_test 4.0.0 [bloc mockito test meta]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- _fe_analyzer_shared 6.0.0 [meta]
- analyzer 0.39.15 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- ansicolor 1.0.2
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- bloc 3.0.0 [meta rxdart]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- cached_network_image 2.2.0+1 [flutter flutter_cache_manager]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- cli_util 0.1.4 [path]
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 2.2.0 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.3
- console_log_handler 1.1.6 [logging intl ansicolor]
- convert 2.1.1 [charcode typed_data]
- coverage 0.14.0 [args logging package_config path source_maps stack_trace vm_service]
- crypto 2.1.5 [collection convert typed_data]
- csslib 0.16.2 [source_span]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- file 5.2.1 [intl meta path]
- firebase 7.3.0 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 2.1.3 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_storage_platform_interface 1.0.1 [flutter meta collection firebase_core plugin_platform_interface]
- flutter_cache_manager 1.4.1 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_image 3.0.0 [flutter]
- flutter_local_notifications_platform_interface 1.0.1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 1.0.8 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- geolocator_platform_interface 1.0.4 [flutter meta plugin_platform_interface vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.1+1 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- html 0.14.0+3 [csslib source_span]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image_picker_platform_interface 1.1.0 [flutter meta http plugin_platform_interface]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.3-nullsafety.2
- json_annotation 3.0.1
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- mime 0.9.6+3
- mockito 4.1.1 [collection matcher meta test_api]
- nested 0.0.4 [flutter]
- node_interop 1.1.1 [js]
- node_io 1.1.1 [node_interop path]
- node_preamble 1.4.12
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.1
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+3 [flutter]
- path_provider_platform_interface 1.0.2 [flutter meta platform plugin_platform_interface]
- pedantic 1.10.0-nullsafety.2
- platform 2.2.1
- plugin_platform_interface 1.0.2 [meta]
- pool 1.5.0-nullsafety.2 [async stack_trace]
- positioned_tap_detector 1.0.3 [flutter]
- process 3.0.13 [file intl meta path platform]
- provider 4.3.1 [flutter nested collection]
- pub_semver 1.4.4 [collection]
- quiver 2.1.3 [matcher meta]
- rxdart 0.23.1
- shelf 0.7.7 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 2.0.0 [path shelf shelf_static]
- shelf_static 0.2.8 [convert http_parser mime path shelf]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_map_stack_trace 2.1.0-nullsafety.3 [path stack_trace source_maps]
- source_maps 0.10.10-nullsafety.2 [source_span]
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.3.1 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test 1.16.0-nullsafety.5 [analyzer async boolean_selector coverage http http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.12-nullsafety.5 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- transparent_image 1.0.0
- tuple 1.0.3 [quiver]
- typed_data 1.3.0-nullsafety.3 [collection]
- validate 1.7.0
- vector_math 2.1.0-nullsafety.3
- vm_service 4.1.0 [meta]
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- webkit_inspection_protocol 0.7.3 [logging]
- xdg_directories 0.1.0 [path process flutter]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

**Comment by markusaksli-nc** [comment]
Could you try upgrading to the latest `firebase_auth: ^0.20.1` and see if the issue still persists?

**Comment by vinnytwice** [comment]
@markusaksli-nc well I have to upgrade all firebase plugins cause firebase_auth: ^0.20.1 depends on lates core etc etc.. but I can't seem to find compatible versions for all the firebase packages I use. Can you help me with the right ones? I tried:

```
#  firebase_core: ^1.0.0
  firebase_core: ^0.7.0

  firebase_auth: ^0.20.1

  firebase_database: ^6.1.0

#  firebase_messaging: ^9.0.0
  firebase_messaging: ^7.0.3 # Because firebase_messaging 7.0.3 depends on firebase_core ^0.5.0+1 and no versions of firebase_messaging match >7.0.3 <8.0.0, firebase_messaging ^7.0.3 requires firebase_core ^0.5.0+1.

#  firebase_storage: ^8.0.0
  firebase_storage: ^7.0.0

#  firebase_remote_config: 0.9.0-dev.0
  firebase_remote_config: ^0.6.0 # Because firebase_remote_config >=0.6.0 <0.9.0-dev.0 depends on firebase_core ^0.7.0 and fixit_cloud_biking depends on firebase_core ^1.0.0, firebase_remote_config >=0.6.0 <0.9.0-dev.0 is forbidden.

#  firebase_analytics: ^7.1.0 # Because firebase_analytics >=7.1.0 depends on firebase_core ^1.0.0 and fixit_cloud_biking depends on firebase_core ^0.7.0, firebase_analytics >=7.1.0 is forbidden.
  firebase_analytics: ^7.0.1

#  cloud_firestore: ^1.0.0 # Because cloud_firestore >=1.0.0 depends on firebase_core ^1.0.0 and fixit_cloud_biking depends on firebase_core ^0.7.0, cloud_firestore >=1.0.0 is forbidden.
  cloud_firestore: 0.16.0+1 # Because cloud_firestore >=0.16.0 <0.17.0-1.0.nullsafety.0 depends on firebase_core_platform_interface ^3.0.1 and firebase_storage >=8.0.0 depends on firebase_core_platform_interface ^4.0.0, cloud_firestore >=0.16.0 <0.17.0-1.0.nullsafety.0 is incompatible with firebase_storage >=8.0.0.
#  cloud_firestore: 0.16.0
```

Thank you very much again

**Comment by markusaksli-nc** [comment]
I was able to reproduce this using `firebase_auth: ^1.0.0`.
<details>
 <summary>flutter doctor -v</summary>

```console
[√] Flutter (Channel master, 2.1.0-11.0.pre.98, on Microsoft Windows [Version 10.0.19041.804], locale et-EE)
    • Flutter version 2.1.0-11.0.pre.98 at C:\Development\flutter_master
    • Framework revision 2f7d9d3d26 (4 hours ago), 2021-03-04 03:25:49 -0500
    • Engine revision 91120b358a
    • Dart version 2.13.0 (build 2.13.0-101.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882
    • Flutter plugin version 54.0.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.7148.57
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.804]
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 88.0.705.81

• No issues found!
```
</details>

When linking the number to the existing user I got
```
W/System  (25545): Ignoring header X-Firebase-Locale because its value was null.
I/System.out(25545): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(25545): (HTTPLog)-Static: isSBSettingEnabled false
E/flutter (25545): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: [firebase_auth/unknown] com.google.firebase.FirebaseException: User has already been linked to the given provider.
E/flutter (25545): #0      MethodChannelUser.linkWithCredential (package:firebase_auth_platform_interface/src/method_channel/method_channel_user.dart:92:7)
E/flutter (25545): <asynchronous suspension>
E/flutter (25545): #1      User.linkWithCredential (package:firebase_auth/src/user.dart:181:7)
E/flutter (25545): <asynchronous suspension>
E/flutter (25545): #2      _PhoneSignInSectionState._verifyPhoneNumber.<anonymous closure> (package:triage/signin_page.dart:670:9)
E/flutter (25545): <asynchronous suspension>
E/flutter (25545): 
```
But when trying to link the verified number to another user even though it is in use already I got
```
W/System  (25545): Ignoring header X-Firebase-Locale because its value was null.
I/System.out(25545): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(25545): (HTTPLog)-Static: isSBSettingEnabled false
W/FirebaseAuth(25545): [SmsRetrieverHelper] Timed out waiting for SMS.
E/FirebaseAuth(25545): [SmsRetrieverHelper] Verification code received with no active retrieval session.
```

FYI @vinnytwice since you are using analytics you will run into https://github.com/FirebaseExtended/flutterfire/issues/5202

**Comment by vinnytwice** [comment]
@markusaksli-nc Hi . Indeed trying to verify an already verified phone would throw that error, that's why I changed it to
```
User user = _firebaseAuth.currentUser;
    print('user phone number is ${user.phoneNumber}'); // prints correct phone number

    /// New : relink if already phone verified
    
    return user.phoneNumber.isNotEmpty
        ? user.reauthenticateWithCredential(authCredential).catchError((e){
      print('UserRepository.verifyAndLinkAuthCredentials() reauthenticateWithCredential error: $e');
    })
        : user.linkWithCredential(authCredential).catchError((e) {
      print('UserRepository.verifyAndLinkAuthCredentials() linkWithCredential error: $e');
    });
```
 this way it will simply reauthenticate user.
 
 Too bad to see that this issue could be reproduced with the latest updates. 
 
 The weird thing is that for a few tries it did throw an error when trying to link a verified number to another user, but then an hour later stopped throwing it and call the wrong callback..
 It's good enough that in the system it doesn't mess-up users/phone numbers..
 Thanks for the link, so it's analytics the guilty pack.
 Hope both issues get resolved soon enough. 
 Thanks again.
 Cheers.

**Comment by yamauchieduardo** [comment]
Any update of this issues? This issue  is CRITICAL and could do a mess in a database if don't fixed. CC @Ehesp

**Comment by russellwheatley** [comment]
Hey @vinnytwice, After combing SO for an answer, it appears that the way to check if a phone number exists on an account already, requires a manual step. Here is [one solution](https://stackoverflow.com/a/56945520) that I found to be the cleanest. If you think this is a bug, you ought to raise an issue on the respective [firebase-android-sdk](https://github.com/firebase/firebase-android-sdk) which FlutterFire thinly wraps around.
