### ISSUE TITLE
🐛 [flutterfire_ui] SMS Auth Code Flow Gets stuck with: Bad state: Future already completed

### ISSUE THREAD

**Issue by alarmatwork** [firebase/flutterfire#8016]
## Bug report

**Describe the bug**
SMS Code Flow fails sometimes on Phone Auth method. 

```
flutter: ‼️ 14:39:08.058876 ERROR    Global Loggy - ERROR:Bad state: Future already completed
flutter: #0      _AsyncCompleter.complete (dart:async/future_impl.dart:44:31)
#1      PhoneAuthFlow.verifySMSCode (package:flutterfire_ui/src/auth/flows/phone_auth_flow.dart:93:23)
#2      _SMSCodeInputViewState.submit (package:flutterfire_ui/src/auth/views/sms_code_input_view.dart:39:12)
#3      _SMSCodeInputViewState.build.<anonymous closure>.<anonymous closure> (package:flutterfire_ui/src/auth/views/sms_code_input_view.dart:75:21)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:21)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:269:7)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#10     GestureBinding.handleEvent <…>

══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following StateError was thrown while handling a gesture:
Bad state: Future already completed

When the exception was thrown, this was the stack:
#1      PhoneAuthFlow.verifySMSCode (package:flutterfire_ui/src/auth/flows/phone_auth_flow.dart:93:23)
#2      _SMSCodeInputViewState.submit (package:flutterfire_ui/src/auth/views/sms_code_input_view.dart:39:12)
#3      _SMSCodeInputViewState.build.<anonymous closure>.<anonymous closure> (package:flutterfire_ui/src/auth/views/sms_code_input_view.dart:75:21)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:21)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:269:7)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:448:20)
#11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:424:22)
#12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:326:11)
#13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:379:7)
#14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:343:5)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:301:7)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:284:7)
#20     _invoke1 (dart:ui/hooks.dart:170:10)
#21     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 4 frames from dart:async)



```
### Steps to reproduce
1. Choose Phone Sign In for the existing user on fresh device.
2. Will enter phone number (marked as test phone in Firebase auth)
3.  Will enter SMS confirmation code as set for the test number
4. Will see the error logs
5. Will continue seeing SMS Auth Code screen without any error message

Sometimes it works as expected, sometimes it does not.

### Expected behavior

Flow would continue or generate some error message.

### Sample project
```
SignInScreen(
      providerConfigs: [
        // EmailProviderConfiguration(),
        PhoneProviderConfiguration(),
      ],
    );
```

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.10.0-1.0.pre.423, on macOS 12.2 21D49 darwin-arm, locale en-EE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
flutter pub deps -- --style=compact
Dart SDK 2.17.0-79.0.dev
Flutter SDK 2.10.0-1.0.pre.423
play_faire 1.0.1+1

dependencies:
- cloud_firestore 3.1.7 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- date_picker_timeline 1.2.3 [flutter intl]
- firebase_analytics 9.1.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.3.6 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 4.0.5 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_form_builder 7.1.0 [flutter intl]
- flutter_hooks 0.18.2 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_loggy 2.0.1 [flutter loggy rxdart]
- flutter_picker 2.0.2 [flutter]
- flutterfire_ui 0.3.2 [cloud_firestore collection crypto desktop_webview_auth email_validator firebase_auth firebase_core firebase_database firebase_dynamic_links flutter flutter_facebook_auth flutter_localizations flutter_svg google_sign_in sign_in_with_apple twitter_login]
- fluttertoast 8.0.8 [flutter flutter_web_plugins]
- form_builder_extra_fields 7.1.0 [flutter flutter_form_builder flutter_chips_input flutter_colorpicker dropdown_search signature flutter_touch_spin intl flutter_typeahead flutter_datetime_picker_bdaya flutter_rating_bar]
- form_builder_phone_field 1.0.0-beta.0 [flutter flutter_form_builder phone_number country_pickers]
- form_builder_validators 7.4.0 [flutter flutter_localizations intl collection]
- freezed_annotation 1.1.0 [collection json_annotation meta]
- hooks_riverpod 1.0.3 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- intl 0.17.0 [clock path]
- intro_slider 3.0.3 [flutter]
- loggy 2.0.1+1 [stack_trace]
- mixpanel_flutter 1.4.4 [flutter flutter_web_plugins js]
- package_info_plus 1.3.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- share_plus 3.0.4 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.0.12 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- url_launcher 6.0.18 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- build_runner 2.1.7 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_gen_runner 4.1.5 [flutter_gen_core build]
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]
- freezed 1.1.1 [analyzer build build_config collection meta source_gen freezed_annotation]
- json_serializable 6.1.4 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- sentry_flutter 6.3.0 [flutter flutter_web_plugins sentry package_info_plus]

transitive dependencies:
- _fe_analyzer_shared 34.0.0 [meta]
- analyzer 3.2.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.1.11 [crypto path]
- args 2.3.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.2.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.6 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.4 [built_collection collection fixnum meta]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 5.4.12 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.7 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- color 3.0.0
- convert 3.0.1 [typed_data]
- country_pickers 2.0.0 [flutter]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.2.1 [analyzer args path pub_semver source_span]
- dartx 1.0.0 [characters collection crypto meta path time]
- desktop_webview_auth 0.0.2 [crypto flutter http]
- dropdown_search 2.0.1 [flutter]
- email_validator 2.0.1
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.0.5 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+6 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.1.11 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.7 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.4 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database 9.0.6 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_database_platform_interface 0.2.0+5 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.0+5 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_dynamic_links_platform_interface 0.2.0+5 [firebase_core flutter meta plugin_platform_interface]
- fixnum 1.0.0
- flutter_chips_input 1.10.0 [flutter]
- flutter_colorpicker 1.0.3 [flutter]
- flutter_datetime_picker_bdaya 2.0.0 [flutter]
- flutter_facebook_auth 3.5.7 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_facebook_auth_platform_interface 2.7.1 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 2.6.0+2 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_gen_core 4.1.5 [path yaml mime xml dartx color collection json_annotation dart_style analyzer args pub_semver source_span]
- flutter_keyboard_visibility 5.1.1 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_rating_bar 4.0.0 [flutter]
- flutter_riverpod 1.0.3 [collection flutter meta riverpod state_notifier]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- flutter_touch_spin 2.0.0 [flutter intl]
- flutter_typeahead 3.2.4 [flutter flutter_keyboard_visibility]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- frontend_server_client 2.1.2 [async path]
- glob 2.0.2 [async collection file path string_scanner]
- google_sign_in 5.2.3 [flutter google_sign_in_platform_interface google_sign_in_web]
- google_sign_in_platform_interface 2.1.1 [flutter quiver]
- google_sign_in_web 0.10.0+4 [flutter flutter_web_plugins google_sign_in_platform_interface js pedantic]
- graphs 2.1.0 [collection]
- http 0.13.4 [async http_parser meta path]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.1.1 [archive meta xml]
- io 1.0.3 [meta path string_scanner]
- js 0.6.4
- json_annotation 4.4.0 [meta]
- lints 1.0.1
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- mime 1.0.1
- package_config 2.0.2 [path]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.1
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.4.0 [meta]
- phone_number 0.12.0+1 [flutter meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.0 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1+1 [matcher]
- riverpod 1.0.3 [collection meta state_notifier]
- rxdart 0.27.3
- sentry 6.3.0 [http meta stack_trace uuid]
- share_plus_linux 2.0.4 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 2.0.2 [share_plus_platform_interface flutter]
- share_plus_platform_interface 2.0.1 [flutter meta mime plugin_platform_interface]
- share_plus_web 2.0.4 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 2.0.3 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences_android 2.0.10 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.0.9 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.0.4 [file flutter path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.0.4 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sign_in_with_apple 3.3.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- signature 5.0.0 [flutter image]
- sky_engine 0.0.99
- source_gen 1.2.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.1 [analyzer collection source_gen]
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.2+1 [meta]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- time 2.1.0 [clock]
- timing 1.0.0 [json_annotation]
- twitter_login 4.0.1 [flutter crypto http]
- typed_data 1.3.0 [collection]
- url_launcher_android 6.0.14 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.14 [flutter url_launcher_platform_interface]
- url_launcher_linux 2.0.3 [flutter]
- url_launcher_macos 2.0.3 [flutter]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.7 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- uuid 3.0.5 [crypto]
- vector_math 2.1.2
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- win32 2.3.10 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
I tried the scenario mentioned couple of times using latest stable (2.10.0) but was unable to see the mentioned error log.
I was able to go through the auth flow properly without any issues.

Labeling it based on the error log reported.

**Comment by alarmatwork** [comment]
OK, I will update to latest and will do some addition testing and debugging to give more clear scenario.
You mentioned 2.10.0, but flutterfire latest version is flutterfire_ui: ^0.3.3

**Comment by klartraum-medien** [comment]
I encounter this problem often as well. 

It's easy to reproduce, too: 

1. Navigate to the "Enter SMS code" screen
2. Enter a wrong verification code on purpose, hit "verify" button
3. Enter the correct verification code, hit "verify" button

Expected behavior: 
Pressing the "verify" button with the corrected verification code now logs the user in. 

Observed behavior: 
Pressing the "verify" button does nothing. Login is impossible, unless the user restarts the auth flow.
The console logs: 

```
======== Exception caught by gesture ===============================================================
The following StateError was thrown while handling a gesture:
Bad state: Future already completed

When the exception was thrown, this was the stack: 
#1      PhoneAuthFlow.verifySMSCode (package:flutterfire_ui/src/auth/flows/phone_auth_flow.dart:93:23)
#2      _SMSCodeInputViewState.submit (package:flutterfire_ui/src/auth/views/sms_code_input_view.dart:39:12)
#3      _SMSCodeInputViewState.build.<anonymous closure>.<anonymous closure> (package:flutterfire_ui/src/auth/views/sms_code_input_view.dart:75:21)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1004:21)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:247:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:612:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:269:7)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:449:20)
#11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
#12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
#13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
#14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#17     _invoke1 (dart:ui/hooks.dart:167:13)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided one frame from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#c6574
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(218.5, 350.9)
  finalLocalPosition: Offset(179.2, 12.8)
  button: 1
  sent tap down
====================================================================================================
```

**My analysis**
Upon hitting the "verify" button, the following method in `phone_auth_flow.dart` is called: 

`  @override
  void verifySMSCode(String code) {
    _smsCodeCompleter.complete(code);
  }`

The problem is that the `complete` method may only be called once at most, after which it will throw the `Bad state: Future already completed` error. That is why pressing the verify button can never work after trying it once.
