### ISSUE TITLE
🐛 [flutterfire_ui] "Error registering plugin flutter_facebook_auth" when not using flutter_facebook_auth

### ISSUE THREAD

**Issue by etienn01** [firebase/flutterfire#8091]
## Bug report

**Describe the bug**
I'm using `flutterfire_ui` on Android with the following:
- `AuthFlowBuilder<EmailFlowController>`
- `AuthFlowBuilder<OAuthController>`
  -  `GoogleProviderConfiguration`
  - `AppleProviderConfiguration`

Despite the fact that I've never used `flutter_facebook_auth` the following stack-trace appears in the logs (via logcat, not visible when running `flutter run`):
```
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: Error registering plugin flutter_facebook_auth, app.meedu.flutter_facebook_auth.FlutterFacebookAuthPlugin
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at com.facebook.internal.Validate.sdkInitialized(Validate.kt:129)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at com.facebook.login.LoginManager.<init>(LoginManager.java:92)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at com.facebook.login.LoginManager.getInstance(LoginManager.java:118)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at app.meedu.flutter_facebook_auth.FacebookAuth.<init>(FacebookAuth.java:28)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at app.meedu.flutter_facebook_auth.FlutterFacebookAuthPlugin.<init>(FlutterFacebookAuthPlugin.java:20)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:64)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at java.lang.reflect.Method.invoke(Native Method)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1009)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:199)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:459)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at android.app.Activity.performCreate(Activity.java:8050)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at android.app.Activity.performCreate(Activity.java:8030)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at android.os.Handler.dispatchMessage(Handler.java:106)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at android.os.Looper.loopOnce(Looper.java:201)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at android.os.Looper.loop(Looper.java:288)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at java.lang.reflect.Method.invoke(Native Method)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
14:29:09.375 23450 23450 E GeneratedPluginRegistrant: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Note that this does not prevent the app from working normally.

### Steps to reproduce

1. Add `flutterfire_ui` as dependency
2. Run the app
3. Watch the output of `adb logcat`
4. See the previously mentioned stack-trace

### Expected behavior

There should not be any stack-trace as I'm not using `flutter_facebook_auth` as a direct dependency in my app.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-x64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful,
      please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.0
Flutter SDK 2.10.0

dependencies:
- cached_network_image 3.2.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- device_info 2.0.3 [flutter device_info_platform_interface]
- firebase_analytics 9.1.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.3.6 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.5.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 4.0.5 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 11.2.6 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_markdown 0.6.9 [flutter markdown meta path]
- flutter_native_timezone 2.0.0 [flutter_web_plugins flutter js]
- flutterfire_ui 0.3.2 [cloud_firestore collection crypto desktop_webview_auth email_validator firebase_auth firebase_core firebase_database firebase_dynamic_links flutter flutter_facebook_auth flutter_localizations flutter_svg google_sign_in sign_in_with_apple twitter_login]
- http 0.13.4 [async http_parser meta path]
- image_picker 0.8.4+6 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- in_app_purchase 2.0.1 [flutter in_app_purchase_platform_interface in_app_purchase_android in_app_purchase_storekit]
- intl 0.17.0 [clock path]
- logging 1.0.2
- package_info_plus 1.3.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- pedantic 1.11.1
- photo_view 0.13.0 [flutter]
- rate_my_app 1.1.1+1 [shared_preferences flutter_rating_bar flutter]
- share 2.0.4 [meta mime flutter]
- shared_preferences 2.0.12 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- timeago 3.2.1
- tuple 2.0.0 [quiver]
- url_launcher 6.0.18 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- build_runner 2.1.7 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- fake_async 1.2.0 [clock collection]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]
- mockito 5.0.17 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- network_image_mock 2.0.1 [flutter mockito]
- path_provider 2.0.8 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- test 1.19.5 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

transitive dependencies:
- _fe_analyzer_shared 31.0.0 [meta]
- analyzer 2.8.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.2.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.6 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.4 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.0
- cloud_firestore 3.1.7 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_firestore_platform_interface 5.4.12 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.7 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.1 [typed_data]
- coverage 1.0.3 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.2 [flutter js meta]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.2.1 [analyzer args path pub_semver source_span]
- desktop_webview_auth 0.0.2 [crypto flutter http]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- email_validator 2.0.1
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.0.5 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+6 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.1.11 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.7 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.4 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.1.13 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database 9.0.6 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_database_platform_interface 0.2.0+5 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.0+5 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_dynamic_links_platform_interface 0.2.0+5 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.1.6 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.2.7 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_facebook_auth 3.5.7 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_facebook_auth_platform_interface 2.7.1 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 2.6.0+2 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_rating_bar 4.0.0 [flutter]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- frontend_server_client 2.1.2 [async path]
- glob 2.0.2 [async collection file path string_scanner]
- google_sign_in 5.2.3 [flutter google_sign_in_platform_interface google_sign_in_web]
- google_sign_in_platform_interface 2.1.1 [flutter quiver]
- google_sign_in_web 0.10.0+4 [flutter flutter_web_plugins google_sign_in_platform_interface js pedantic]
- graphs 2.1.0 [collection]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.1.5 [flutter flutter_web_plugins image_picker_platform_interface pedantic]
- image_picker_platform_interface 2.4.3 [flutter http plugin_platform_interface cross_file]
- in_app_purchase_android 0.2.2+1 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_purchase_platform_interface 1.3.1 [flutter plugin_platform_interface]
- in_app_purchase_storekit 0.2.1 [collection flutter in_app_purchase_platform_interface json_annotation meta]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.4.0 [meta]
- linkify 4.1.0
- markdown 4.0.1 [args charcode meta]
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- mime 1.0.1
- node_preamble 2.0.1
- octo_image 1.0.1 [flutter flutter_blurhash]
- package_config 2.0.2 [path]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider_android 2.0.11 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.7 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.0 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1+1 [matcher]
- rxdart 0.27.3
- shared_preferences_android 2.0.10 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.0.9 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.0.4 [file flutter path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.0.4 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.1.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sign_in_with_apple 3.3.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_gen 1.2.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.2 [flutter sqflite_common path]
- sqflite_common 2.2.0 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.9 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 1.0.0 [json_annotation]
- twitter_login 4.0.1 [flutter crypto http]
- typed_data 1.3.0 [collection]
- url_launcher_android 6.0.14 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.14 [flutter url_launcher_platform_interface]
- url_launcher_linux 2.0.3 [flutter]
- url_launcher_macos 2.0.3 [flutter]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.6 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- uuid 3.0.5 [crypto]
- vector_math 2.1.1
- vm_service 7.5.0
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.0.0 [logging]
- win32 2.3.10 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```
</details>

---

**Comment by darshankawar** [comment]
Thanks for the report. Using the steps to replicate above on Android, I do see a similar stacktrace using adb logcat.
```

E GeneratedPluginRegistrant: Error registering plugin flutter_facebook_auth,
E GeneratedPluginRegistrant: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
```

`Channel master, 2.11.0-0.0.pre.581`

**Comment by wer-mathurin** [comment]
This bug make the build failed on iOS.  And this prevent using the library completely for us :-(

The error is:
Parse Issue (Xcode): Module 'flutter_facebook_auth' not found

We are using the AuthFlowBuilder<EmailFlowController> process

**Comment by workerbee22** [comment]
Yep ... this is a show stopper for us too. Can't have such a major crash for Auth, when have not even used the FB provider.

**Comment by LarMaySee** [comment]
Error registering plugin flutter_facebook_auth, app.meedu.flutter_facebook_auth.FlutterFacebookAuthPlugin
E/GeneratedPluginRegistrant(31419): The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.

**Comment by MarijnFK** [comment]
Same error here, i am using the package flutter_facebook_auth: ^4.3.0
After some reading through the docs i found that i was missing the 'facebook_client_token'
Read here for instructions: https://facebook.meedu.app/docs/4.x.x/android

**Comment by lesnitsky** [comment]
we will be decoupling oauth providers from the core UI library, so this won't be an issue anymore

**Comment by workerbee22** [comment]
@lesnitsky any idea on the approximate timeframe for this?

**Comment by guizombas** [comment]
Having the same issue. Actually is a little funnier, it works on my machine but doesn't in my co-workers' 🤡. They also get an error in google authentication "unkown error occurred", don't know if it's related. The same thing happens in my android build. Anaways, is there any immediate solution ?

**Comment by rlee1990** [comment]
> we will be decoupling oauth providers from the core UI library, so this won't be an issue anymore

Any update on when this will happen?

**Comment by etienn01** [comment]
> They also get an error in google authentication "unkown error occurred", don't know if it's related.

@guizombas https://github.com/firebase/flutterfire/issues/8384

**Comment by darwin-morocho** [comment]
You can disable the auto initialization of the facebook sdk on android adding the next code in your AndroidManifest inside the application application

```
<meta-data android:name="com.facebook.sdk.AutoInitEnabled"
    android:value="false"/>
```

**Comment by MousyBusiness** [comment]
> You can disable the auto initialization of the facebook sdk on android adding the next code in your AndroidManifest inside the application application
> 
> ```
> <meta-data android:name="com.facebook.sdk.AutoInitEnabled"
>     android:value="false"/>
> ```

This did not work

**Comment by Technorocker** [comment]
Just came across this thread searching why the generatedPluginRegistrant is adding facebook, google and apple even though I dont use any of those anywhere in my app.

**Comment by Dev-Muhammad-Junaid** [comment]
I am having similar issues. I just integrated flutterfire_ui and used the basic EmailProviderConfiguration and my app in both ios and android is not building and showing facebook_auth not found or undefined.
Here is what its showing
https://imgur.com/a/v7kx43K
I am not even using it. Any suggestions?
