### ISSUE TITLE
🐛 [firebase_messaging] Some crash on Android on BackgroundService

### ISSUE THREAD

**Issue by aldychris** [firebase/flutterfire#8134]
## Bug report

**Describe the bug**
Since I update to 
```
  firebase_core: 1.12.0
  firebase_messaging: 11.2.6
```
I started to get crash around 6% of my user based on Crashlytic Data.

### Steps to reproduce

1. Use firebase_messaging: 11.2.6
2. Trigger push notification

### Expected behavior

Should not crash on some devices

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale en-MY)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.2)
[✓] Connected device (4 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
  firebase_core: 1.12.0
  firebase_crashlytics: 2.5.0
  firebase_analytics: 9.1.0
  firebase_performance: 0.8.0+5
  firebase_messaging: 11.2.6
  firebase_dynamic_links: 4.0.5
  flutter_local_notifications: 9.2.0
```

</details>

### Error Logs

<details><summary>Click To Expand</summary>

```
Fatal Exception: android.os.BadParcelableException
Parcelable protocol requires subclassing from Parcelable on class com.google.firebase.messaging.n0

Fatal Exception: android.os.BadParcelableException: Parcelable protocol requires subclassing from Parcelable on class com.google.firebase.messaging.n0
       at android.os.Parcel.readParcelableCreator(Parcel.java:2830)
       at android.os.Parcel.readParcelable(Parcel.java:2781)
       at android.os.Parcel.readValue(Parcel.java:2684)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
       at android.os.BaseBundle.unparcel(BaseBundle.java:232)
       at android.os.Bundle.getParcelable(Bundle.java:940)
       at android.content.Intent.getParcelableExtra(Intent.java:7534)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate(FlutterFirebaseMessagingBackgroundExecutor.java:232)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.lambda$onHandleWork$0(FlutterFirebaseMessagingBackgroundService.java:146)
       at io.flutter.plugins.firebase.messaging.-$$Lambda$FlutterFirebaseMessagingBackgroundService$MMnhHFRTKULlQAZ4ruNMt0KzQOI.run(lambda:4)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:239)
       at android.app.ActivityThread.main(ActivityThread.java:7227)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)
```

</details>

---

---

**Comment by rpsnaik** [comment]
Facing the same crash

`android.os.Parcel.readParcelableCreator (Parcel.java:2855)
android.os.Parcel.readParcelable (Parcel.java:2781)
android.os.Parcel.readValue (Parcel.java:2684)
android.os.Parcel.readArrayMapInternal (Parcel.java:3053)
android.os.BaseBundle.initializeFromParcelLocked (BaseBundle.java:288)
android.os.BaseBundle.unparcel (BaseBundle.java:232)
android.os.Bundle.getParcelable (Bundle.java:940)
android.content.Intent.getParcelableExtra (Intent.java:7534)
io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate (FlutterFirebaseMessagingBackgroundExecutor.java:22)
io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.lambda$onHandleWork$0 (FlutterFirebaseMessagingBackgroundService.java:2)
io.flutter.plugins.firebase.messaging.-$$Lambda$FlutterFirebaseMessagingBackgroundService$MMnhHFRTKULlQAZ4ruNMt0KzQOI.run (-.java:4)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:233)
android.app.ActivityThread.main (ActivityThread.java:7225)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:499)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:962)`

**Comment by darshankawar** [comment]
Since the crash seems to be coming from production and without lack of proper reproducible use case, I'll go ahead and label it for further insights from the team.
I do see `FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate (FlutterFirebaseMessagingBackgroundExecutor.java:22)` entry in the log which might be helpful to debug further for the team.

There has been a similar crash report which got closed due to inactivity: https://github.com/FirebaseExtended/flutterfire/issues/7443

/cc @russellwheatley

**Comment by russellwheatley** [comment]
Hey @aldychris, is this still an issue you're experiencing?

**Comment by aldychris** [comment]
Hi @russellwheatley I dont see any more crash report on my crashlytic console in these past 7days. I will close this ticket..
Thanks

**Comment by rpsnaik** [comment]
@aldychris What changes you made to get rid of this crash ? please let me know
