### ISSUE TITLE
🐛 [firebase_database] Client is offline

### ISSUE THREAD

**Issue by Tom3652** [firebase/flutterfire#8220]
## Bug report

**Describe the bug**

I am having this error : 

```
I/RepoOperation(20534): get for query /chats falling back to disk cache after error: Client is offline
E/firebase_database(20534): An unknown error occurred handling native method call Query#get
E/firebase_database(20534): java.util.concurrent.ExecutionException: java.lang.Exception: Client is offline
E/firebase_database(20534): 	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@18.0.1:5)
E/firebase_database(20534): 	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@18.0.1:8)
E/firebase_database(20534): 	at io.flutter.plugins.firebase.database.FirebaseDatabasePlugin.lambda$queryGet$8$io-flutter-plugins-firebase-database-FirebaseDatabasePlugin(FirebaseDatabasePlugin.java:248)
E/firebase_database(20534): 	at io.flutter.plugins.firebase.database.FirebaseDatabasePlugin$$ExternalSyntheticLambda17.call(Unknown Source:4)
E/firebase_database(20534): 	at com.google.android.gms.tasks.zzz.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
E/firebase_database(20534): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/firebase_database(20534): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/firebase_database(20534): 	at java.lang.Thread.run(Thread.java:923)
E/firebase_database(20534): Caused by: java.lang.Exception: Client is offline
E/firebase_database(20534): 	at com.google.firebase.database.connection.PersistentConnectionImpl.lambda$get$1$com-google-firebase-database-connection-PersistentConnectionImpl(PersistentConnectionImpl.java:441)
E/firebase_database(20534): 	at com.google.firebase.database.connection.PersistentConnectionImpl$$ExternalSyntheticLambda4.run(Unknown Source:8)
E/firebase_database(20534): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/firebase_database(20534): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/firebase_database(20534): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/firebase_database(20534): 	... 3 more
```

20% of the time. When i was using ```.once()``` i have never had this issue.  

The client is indeed online because all my other queries work fine.  

Also, I have thought that maybe ```firebase_database``` take time to initialize itself or something, i have called ```await FirebaseDatabase.instance.goOnline()``` before but this doesn't help :/ 

The problem with ```.once()``` is that it returns sometimes a value that doesn't match the one in DB i don't know why, so i would rather be using ```.get()``` to : 

> Gets the most up-to-date result for this query.

It's also written `falling back to disk cache after error`. What does it mean please ? Does `firebase_database` try to read data from local cache ? I thought it was only writing to disk cache to retry failed writes later.

### Steps to reproduce

I don't know how to reproduce it, but i have it more often in my test project when i query right after app start. 
If i add a 3-5 sec delay it works better.  
In my real app the delay is already more or less 3 seconds.

### Expected behavior

The query should not throw Client is offline when client is online.  
In case the `Client is offline` from a DB perspective, please provide another error to understand what is the real error (database failed to established a connection for example).

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.1
Flutter SDK 2.10.2
myappname 1.0.0+1

dependencies:
- app_settings 4.1.1 [flutter]
- app_tracking_transparency 2.0.2+1 [flutter]
- apple_maps_flutter 1.1.0 [flutter]
- audioplayers 0.20.1 [uuid path_provider http flutter flutter_web_plugins]
- auto_size_text 3.0.0 [flutter]
- badges 2.0.2 [flutter]
- cached_network_image 3.2.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- clipboard 0.1.3 [flutter]
- cloud_functions 3.2.9 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- confetti 0.6.0 [flutter vector_math]
- connectivity_plus 2.2.1 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- country_code_picker 2.0.2 [flutter modal_bottom_sheet collection universal_platform]
- crypto 3.0.1 [collection typed_data]
- cupertino_back_gesture 0.1.0 [flutter]
- cupertino_icons 1.0.4
- device_display_brightness 0.0.6 [flutter]
- disk_space 0.2.1 [flutter]
- emoji_picker_flutter 1.1.2 [flutter shared_preferences]
- extended_image 6.0.1 [extended_image_library flutter meta]
- extended_tabs 2.3.0 [flutter]
- firebase_analytics 9.1.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.3.9 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.13.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.5.3 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_database 9.0.8 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_dynamic_links 4.0.8 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 11.2.8 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.8.0+7 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_storage 10.2.9 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_app_badger 1.3.0 [flutter]
- flutter_arc_text 0.5.0 [characters flutter]
- flutter_contacts 1.1.3 [flutter]
- flutter_email_sender 5.1.0 [flutter]
- flutter_facebook_auth 4.1.1 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_ffmpeg 0.4.2 [flutter]
- flutter_image_compress 1.1.0 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_native_text_input 2.1.1 [flutter]
- flutter_staggered_grid_view 0.6.1 [flutter]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- geocoding 2.0.2 [flutter geocoding_platform_interface]
- geolocator 8.2.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- google_fonts 2.3.1 [flutter http path_provider crypto]
- google_maps_flutter 2.1.2 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- google_mobile_ads 1.1.0 [meta flutter]
- google_sign_in 5.2.4 [flutter google_sign_in_platform_interface google_sign_in_web]
- hive 2.0.6 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- http 0.13.4 [async http_parser meta path]
- image_editor 1.0.2 [flutter]
- in_app_purchase 3.0.1 [flutter in_app_purchase_android in_app_purchase_platform_interface in_app_purchase_storekit]
- in_app_review 2.0.4 [flutter in_app_review_platform_interface]
- logger 1.1.0
- package_info_plus 1.4.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- path 1.8.0
- path_provider 2.0.9 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- percent_indicator 4.0.0 [flutter]
- perfect_volume_control 1.0.5 [flutter]
- permission_handler 9.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- photo_manager 2.0.0-dev.14 [flutter]
- provider 6.0.2 [collection flutter nested]
- pull_to_refresh 2.0.0 [flutter]
- record 3.0.2 [flutter record_platform_interface record_web]
- rive 0.8.1 [collection flutter graphs http meta]
- screen_capture_event 1.0.0+1 [flutter permission_handler]
- scrollable_positioned_list 0.2.3 [flutter collection]
- share_plus 3.1.0 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.0.13 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 3.3.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sliver_tools 0.2.5 [flutter]
- sqflite 2.0.2 [flutter sqflite_common path]
- translator 0.1.7 [http]
- url_launcher 6.0.20 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.6 [crypto]
- video_compress 3.1.1 [flutter]
- video_player 2.2.19 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_thumbnail 0.4.6 [flutter]
- visibility_detector 0.2.2 [flutter]

dev dependencies:
- build_runner 2.1.7 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]
- hive_generator 1.1.2 [build source_gen hive analyzer source_helper]

transitive dependencies:
- _fe_analyzer_shared 36.0.0 [meta]
- analyzer 3.3.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.2.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.6 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.4 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- clock 1.1.0
- cloud_functions_platform_interface 5.1.1 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.2.9 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- connectivity_plus_linux 1.3.0 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.1 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.0 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.0 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.0 [connectivity_plus_platform_interface flutter]
- convert 3.0.1 [typed_data]
- csslib 0.17.1 [source_span]
- dart_style 2.2.2 [analyzer args path pub_semver source_span]
- dbus 0.7.1 [args ffi meta xml]
- extended_image_library 3.1.2 [crypto flutter http_client_helper path path_provider]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase 9.0.2 [http http_parser js]
- firebase_analytics_platform_interface 3.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+8 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.2.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.9 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.5 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_platform_interface 0.2.1+1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.0+7 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_dynamic_links_platform_interface 0.2.1+1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.2.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.2.9 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance_platform_interface 0.1.1+1 [firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.0+7 [firebase firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]
- firebase_storage_platform_interface 4.1.1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.2.10 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.0
- flutter_blurhash 0.6.4 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_facebook_auth_platform_interface 3.0.1 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 3.0.0+1 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- frontend_server_client 2.1.2 [async path]
- geocoding_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- geolocator_android 3.1.0 [flutter geolocator_platform_interface]
- geolocator_apple 2.1.1+1 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.3 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.4 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.0 [flutter geolocator_platform_interface]
- glob 2.0.2 [async collection file path string_scanner]
- google_maps_flutter_platform_interface 2.1.5 [collection flutter plugin_platform_interface stream_transform]
- google_sign_in_platform_interface 2.1.2 [flutter quiver]
- google_sign_in_web 0.10.0+5 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- graphs 2.1.0 [collection]
- html 0.15.0 [csslib source_span]
- http_client_helper 2.0.2 [http]
- http_multi_server 3.2.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- in_app_purchase_android 0.2.2+2 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_purchase_platform_interface 1.3.1 [flutter plugin_platform_interface]
- in_app_purchase_storekit 0.3.0+1 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_review_platform_interface 2.0.3 [flutter url_launcher plugin_platform_interface platform]
- intl 0.17.0 [clock path]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.4.0 [meta]
- lints 1.0.1
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- mime 1.0.1
- modal_bottom_sheet 2.0.0 [flutter]
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 1.0.1 [flutter flutter_blurhash]
- package_config 2.0.2 [path]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider_android 2.0.12 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_android 9.0.2+1 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.3 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.0 [flutter permission_handler_platform_interface]
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.0 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1+1 [matcher]
- record_platform_interface 0.2.0 [flutter plugin_platform_interface]
- record_web 0.2.1 [flutter flutter_web_plugins record_platform_interface]
- rxdart 0.27.3
- share_plus_linux 2.0.4 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 2.0.2 [share_plus_platform_interface flutter]
- share_plus_platform_interface 2.0.1 [flutter meta mime plugin_platform_interface]
- share_plus_web 2.0.4 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 2.0.3 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences_android 2.0.11 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.0 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.3 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_gen 1.2.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.1 [analyzer collection source_gen]
- source_span 1.8.1 [collection path term_glyph]
- sqflite_common 2.2.0 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- universal_platform 1.0.0+1
- url_launcher_android 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.9 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.0 [flutter url_launcher_platform_interface]
- vector_math 2.1.1
- video_player_android 2.3.0 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.0 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.0 [flutter plugin_platform_interface]
- video_player_web 2.0.7 [flutter flutter_web_plugins video_player_platform_interface]
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- win32 2.4.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by OlegNovosad** [comment]
Keep on seeing the same error on the first run 👆

**Comment by darshankawar** [comment]
> Does `firebase_database` try to read data from local cache ? I thought it was only writing to disk cache to retry failed writes later.

When a write request is triggered, it writes to local db first and then if sync with server is successful, the request will be carried out.

Since you are using `.get()`, can you explicitly enable disk persistence for the Firebase Realtime Database before it can read data from it by calling `FirebaseDatabase.instance.setPersistenceEnabled(true);` at the start of the app and see if you still get the said error ?

**Comment by darshankawar** [comment]
@Tom3652 
I would also suggest you to reach out to [firebase support](https://firebase.google.com/support) to check what they have to say about it.

**Comment by Tom3652** [comment]
I have got an answer from Firebase support : 

> The error says that the connection to the database was not possible and that is why the client is marked as offline. You mentioned that this only happens when the app is starting, which could mean that there could be a problem while making the connections to the service or loading the credentials or libraries necessary to connect.
 
> Now, it could be working better with once because this operation looks first in the local cache instead of checking for an updated value on the server. The get operation does the contrary, first it will look at the server and if it fails it will look at the local cache. 

> I tried to verify the behavior using the [Firebase Realtime Database Android SDK](https://github.com/firebase/quickstart-android/tree/master/database) but I was not able to reproduce it. I don't see a problem with the service, it is more like a problem on how the connection is established. It would be good to contact the Flutter support team so they can also investigate the issue.

> We are in touch if something else happens.

**Comment by Tom3652** [comment]
Hi @darshankawar, do you expect something else from me for this issue ?  

I guess that if the client is offline at the moment of the query, there should be a way to ensure that the database is online first (and not `goOnline()` because i have tried it and it doesn't help with this) ? 
Or at least not throwing an error like this ?

I am more about turning it into a feature request than a bug request then, that would be to handle this case internally.  
What do you think ?

**Comment by darshankawar** [comment]
Sorry for coming back a bit late on this.


> there should be a way to ensure that the database is online first (and not `goOnline()` because i have tried it and it doesn't help with this) ? Or at least not throwing an error like this ?
> 
> I am more about turning it into a feature request than a bug request then, that would be to handle this case internally. What do you think ?

Check [this](https://stackoverflow.com/a/63415042) SO answer from a former firebase member. Although that is for firestore, but I am sure the same would be applicable for database plugin too. See if that comment helps a bit further.

**Comment by Tom3652** [comment]
Alright thanks for the update i understand, i will be using .once() for now because there doesn't seem to be any retry on the `.get()` unfortunately, it simply falls back on the cache and finds nothing so returns nothing. 

The .once() however seems to be retrying from the server if there is no internet connectivity for example, until there is a concrete response (unless it finds from the cache first apparently, but i don't cache anything to avoid this).

**Comment by darshankawar** [comment]
I'll label it for team's insights on this though to know what would be the possible root-cause for this.

/cc @russellwheatley

**Comment by utekau** [comment]
I'm also suffering due to the same issue. I'm sure that there is an internet connection up but got "Client is offline" message.

**Comment by puf** [comment]
*firebaser here*

This is actually a known issue in our native SDKs for Android, iOS and Web, which give up too soon when getting the value from the server on startup. We have a [fix](https://github.com/firebase/firebase-android-sdk/pull/3485) going out for this in version 20.0.5 of the Android SDK for the Realtime Database. Once that lands and is picked up in FlutterFire too, the problem should disappear.
