### ISSUE TITLE
🐛 [firebase_messaging] FirebaseMessaging.instance.getInitialMessage() not working with Splash Screen

### ISSUE THREAD

**Issue by richmondgingingon** [firebase/flutterfire#8242]
I have integrated Firebase Cloud Messaging to my Flutter mobile app with the help of GetX State Management. Also I used Laravel with Firebase Admin SDK to send notification to my app.

The notification is working fine on both foreground state and background state (paused). The problem starts when I click the notification where the app is in terminated state (app closed). Do I have to set a delay between the splashscreen and main page?

I get this error
```
Unhandled Exception: 
You are trying to use contextless 
navigation without a GetMaterialApp or Get.key
```

Here is my main.dart
 ```
   //open notif content from terminated state of the app
    FirebaseMessaging.instance.getInitialMessage().then((message) {
      if (message != null) {
        if (FirebaseAuth.instance.currentUser == null) {
          Get.offAllNamed(Routes.LOGIN);
        } else {
          final redirectRoute = message.data['route'];
          if (redirectRoute != null) {
            print('TERMINATED');
            bottomnavbarController.updateIndex(int.parse(redirectRoute));
          }
        }
      }
    });
   

  @override
  Widget build(BuildContext context) {
    final authController = Get.put(AuthController(), permanent: true);
    return FutureBuilder(
      future: Future.delayed(const Duration(seconds: 6)),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          return Obx(
            () => GetMaterialApp(
              debugShowCheckedModeBanner: false,              
              title: "Application",
              theme: ThemeData(
                appBarTheme: const AppBarTheme(
                    elevation: 0.2,
                    foregroundColor: Colors.black,
                    backgroundColor: Colors.white),
              ),
              initialRoute: authController.isSkipIntro.isTrue
                  ? authController.isAuthAndVerified.isTrue
                      ? Routes.PAGEWRAPPER
                      : Routes.LOGIN
                  : Routes.INTRODUCTION,
              getPages: AppPages.routes,
            ),
          );
        }

        return FutureBuilder(
          future: authController.firstInitialize(),
          builder: (context, snapshot) {
            return const SplashScreen();
          },
        );
      },
    );
  }
```

Here is my bottom nav controller
```
class BottomnavbarController extends GetxController {
  final bottomNavIndex = 0.obs;  
  
  void updateIndex(int index){
    bottomNavIndex.value = index;
    Get.offAllNamed(Routes.PAGEWRAPPER);
  }
}
```

I have tried to do this but error still occur
```
//open notif content from terminated state of the app
FirebaseMessaging.instance.getInitialMessage().then((message) {
  if (message != null) {
    print('TERMINATED');
    if (FirebaseAuth.instance.currentUser != null) {
      final redirectRoute = message.data['route'];
      if (redirectRoute != null) {    
        //adding delay here since my splashscreen have the same delay        
        Future.delayed(const Duration(seconds: 6));
        bottomnavbarController.updateIndex(int.parse(redirectRoute));
      }
    } else {
      Get.offAllNamed(Routes.LOGIN);
    }
  }
});
```

Here is the log
```
Launching lib\main.dart on RNE L22 in release mode...
Running Gradle task 'assembleRelease'...                           76.4s
√  Built build\app\outputs\flutter-apk\app-release.apk (10.0MB).
Installing build\app\outputs\flutter-apk\app.apk...                 3.4s

Flutter run key commands.
h List all available interactive commands.       
c Clear the screen
q Quit (terminate the application on the device).
W/FlutterJNI(10061): FlutterJNI.loadLibrary called more than once
W/FlutterJNI(10061): FlutterJNI.prefetchDefaultFontManager called more than once
W/FlutterJNI(10061): FlutterJNI.init called more than once
W/FlutterJNI(10239): FlutterJNI.loadLibrary called more than once
W/FlutterJNI(10239): FlutterJNI.init called more than once
I/flutter (10239): Handling a background message: 0:1646807530074172%f77b2610f77b2610
I/flutter (10239): TERMINATED
E/flutter (10239): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: You are trying to use contextless navigation without
E/flutter (10239):       a GetMaterialApp or Get.key.
E/flutter (10239):       If you are testing your app, you can use:
E/flutter (10239):       [Get.testMode = true], or if you are running your app on
E/flutter (10239):       a physical device or emulator, you must exchange your [MaterialApp]
E/flutter (10239):       for a [GetMaterialApp].
E/flutter (10239):
E/flutter (10239): #0      GetNavigation.global (package:get/get_navigation/src/extension_navigation.dart:1094)
E/flutter (10239): #1      GetNavigation.offAllNamed (package:get/get_navigation/src/extension_navigation.dart:786)
E/flutter (10239): #2      BottomnavbarController.updateIndex (package:prototypeapp/app/modules/bottomnavbar/controllers/bottomnavbar_controller.dart:9)
E/flutter (10239): #3      _MyAppState.initState.<anonymous closure> (package:prototypeapp/main.dart:64)
E/flutter (10239): #4      _rootRunUnary (dart:async/zone.dart:1434)
E/flutter (10239): <asynchronous suspension>
E/flutter (10239): 
I/flutter (10239): Null check operator used on a null value
I/flutter (10239): #0      PageRedirect.page (package:get/get_navigation/src/routes/route_middleware.dart:199)
I/flutter (10239): #1      GetMaterialApp.initialRoutesGenerate (package:get/get_navigation/src/root/get_material_app.dart:348)
I/flutter (10239): #2      _WidgetsAppState.build.<anonymous closure> (package:flutter/src/widgets/app.dart:1556)
I/flutter (10239): #3      NavigatorState.restoreState (package:flutter/src/widgets/navigator.dart:3290)
I/flutter (10239): #4      RestorationMixin._doRestore (package:flutter/src/widgets/restoration.dart:887)
I/flutter (10239): #5      RestorationMixin.didChangeDependencies (package:flutter/src/widgets/restoration.dart:873)
I/flutter (10239): #6      NavigatorState.didChangeDependencies (package:flutter/src/widgets/navigator.dart:3336)
I/flutter (10239): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4914)
I/flutter (10239): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (10239): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (10239): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (10239): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (10239): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (10239): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (10239): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (10239): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (10239): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (10239): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (10239): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (10239): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (10239): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (10239): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (10239): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (10239): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (10239): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (10239): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (10239): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (10239): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (10239): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (10239): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (10239): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (10239): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (10239): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (10239): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (10239): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (10239): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (10239): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (10239): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (10239): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (10239): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (10239): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (10239): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (10239): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (10239): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (10239): #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (10239): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (10239): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (10239): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (10239): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (10239): #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (10239): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (10239): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (10239): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (10239): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (10239): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (10239): #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (10239): #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (10239): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (10239): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (10239): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (10239): #60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
I/flutter (10239): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (10239): #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (10239): #63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
I/flutter (10239): #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (10239): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (10239): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (10239): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (10239): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (10239): #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (10239): #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (10239): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (10239): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (10239): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (10239): #74     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
I/flutter (10239): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (10239): #76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (10239): #77     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
I/flutter (10239): #78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (10239): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (10239): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (10239): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (10239): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (10239): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (10239): #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (10239): #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (10239): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (10239): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (10239): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (10239): #89     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (10239): #90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (10239): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (10239): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (10239): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (10239): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (10239): #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (10239): #96     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (10239): #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (10239): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (10239): #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
```

**Comment by darshankawar** [comment]
@richmondgingingon 
Since you are using GetX which is third party plugin, we won't exactly know if the issue you are facing is due to its usage or due to messaging plugin itself. 
I suggest you to try out plugin example and see if you still get the same error or not.
Also, try your code without using GetX if possible and just use core messaging code implementation and see if you get similar error from the framework still if clicking the notification where the app is in terminated state (app closed).

**Comment by richmondgingingon** [comment]
@darshankawar
Here is a sample without  GetX

main.dart
```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:learningapp/home_screen.dart';
import 'package:learningapp/login_screen.dart';
import 'package:learningapp/result_screen.dart';
import 'package:learningapp/splash_screen.dart';

import 'local_notification_service.dart';

//receive notif if app is on background even if app terminated
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  // ignore: avoid_print
  print('Handling a background message: ${message.messageId}');
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    LocalNotificationService.initialize(context);
    //open notif content from terminated state of the app
    FirebaseMessaging.instance.getInitialMessage().then((message) async {
      if (message != null) {
        final redirectRoute = message.data['route'];
        if (redirectRoute != null) {
          print('TERMINATED');
          print('redirectRoute $redirectRoute');
          Navigator.pushReplacementNamed(context, '$redirectRoute');
        }
      }
    });

    //only works if app in foreground
    FirebaseMessaging.onMessage.listen((message) {
      LocalNotificationService.display(message);
    });

    //onclick notif system tray only works if app in background but not terminated
    FirebaseMessaging.onMessageOpenedApp.listen((message) {
      final redirectRoute = message.data['route'];
      if (redirectRoute != null) {
        print('BACKGROUND');
        print('redirectRoute $redirectRoute');
        Navigator.pushReplacementNamed(context, '$redirectRoute');
      }
    });
  }

  bool isAuth = false;

  Future<bool> _checkIfLoggedIn() async {
    final currentUser = FirebaseAuth.instance.currentUser;
    print(currentUser);
    if (currentUser != null) {
      return isAuth = true;
    }
    return isAuth = false;
  }

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: Future.delayed(const Duration(seconds: 3)),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          print('isAuth : $isAuth');
          return MaterialApp(
            title: 'Flutter Demo',
            theme: ThemeData(
              primarySwatch: Colors.blue,
            ),
            initialRoute: isAuth ? 'home' : 'login',
            routes: {
              'home': (context) => const HomeScreen(),
              'login': (context) => const LoginScreen(),
              'result': (context) => const ResultScreen(),
            },
          );
        }

        return FutureBuilder(
          future: _checkIfLoggedIn(),
          builder: (context, snapshot) {
            return const SplashScreen();
          },
        );
      },
    );
  }
}
```

local_notification_service class
```
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

class LocalNotificationService {
  static final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

  static void initialize(BuildContext context) {
    const InitializationSettings initializationSettings =
        InitializationSettings(
            android: AndroidInitializationSettings('@mipmap/ic_launcher'));

    flutterLocalNotificationsPlugin.initialize(
      initializationSettings,
      onSelectNotification: ((redirectRoute) async {
        if (redirectRoute != null) {
          print('FOREGROUND');
          print('redirectRoute $redirectRoute');
          Navigator.pushReplacementNamed(context, redirectRoute);
        }
      }),
    );
  }

  static void display(RemoteMessage remoteMessage) async {
    try {
      final id = DateTime.now().millisecondsSinceEpoch ~/ 1000;
      const NotificationDetails notificationDetails = NotificationDetails(
        android: AndroidNotificationDetails(
          "learningapp",
          "learningapp channel",
          importance: Importance.max,
          priority: Priority.high,
          color: Color(0xFF42A5F5),
        ),
      );

      await flutterLocalNotificationsPlugin.show(
        id,
        remoteMessage.notification!.title,
        remoteMessage.notification!.body,
        notificationDetails,
        payload: remoteMessage.data['route'],
      );
    } on Exception catch (e) {
      // ignore: avoid_print
      print(e);
    }
  }
}
```

In this case, all states won't redirect. Please guide me to fix this.
Here is the log for foreground state when I tap on the notification. background state both (paused and terminated) also return this same log.
```
I/flutter ( 7611): FOREGROUND
I/flutter ( 7611): redirectRoute result
E/flutter ( 7611): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 7611): #0      Navigator.of (package:flutter/src/widgets/navigator.dart:2561)
E/flutter ( 7611): #1      Navigator.pushReplacementNamed (package:flutter/src/widgets/navigator.dart:1739)
E/flutter ( 7611): #2      LocalNotificationService.initialize.<anonymous closure> (package:learningapp/local_notification_service.dart:20)
E/flutter ( 7611): #3      LocalNotificationService.initialize.<anonymous closure> (package:learningapp/local_notification_service.dart:16)
E/flutter ( 7611): #4      AndroidFlutterLocalNotificationsPlugin._handleMethod (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:460)
E/flutter ( 7611): #5      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:414)       
E/flutter ( 7611): #6      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:407)
E/flutter ( 7611): #7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377)
E/flutter ( 7611): #8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:374)
E/flutter ( 7611): #9      _invoke2.<anonymous closure> (dart:ui/hooks.dart:190)
E/flutter ( 7611): #10     _rootRun (dart:async/zone.dart:1426)
E/flutter ( 7611): #11     _CustomZone.run (dart:async/zone.dart:1328)
E/flutter ( 7611): #12     _CustomZone.runGuarded (dart:async/zone.dart:1236)
E/flutter ( 7611): #13     _invoke2 (dart:ui/hooks.dart:189)  
E/flutter ( 7611): #14     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42)
E/flutter ( 7611): #15     _Channel.push (dart:ui/channel_buffers.dart:132)
E/flutter ( 7611): #16     ChannelBuffers.push (dart:ui/channel_buffers.dart:329)
E/flutter ( 7611): #17     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:583)
E/flutter ( 7611): #18     _dispatchPlatformMessage (dart:ui/hooks.dart:89)
E/flutter ( 7611):
```

**Comment by darshankawar** [comment]
@richmondgingingon 
Thanks for the code and log. Looking at the stactrace: its pointing to below line:

`_MyAppState.initState.<anonymous closure> (package:learningapp/main.dart:60)` indicating when you are initializing below method:

```
void initState() {
    super.initState();
    LocalNotificationService.initialize(context);
    //open notif content from terminated state of the app
    FirebaseMessaging.instance.getInitialMessage().then((message) async {
      if (message != null) {
        final redirectRoute = message.data['route'];
        if (redirectRoute != null) {
          print('TERMINATED');
          print('redirectRoute $redirectRoute');
          Navigator.of(context).pushReplacementNamed(redirectRoute);
        }
      }
    });
```
is throwing the null exception. So I guess the context could be null while you are tryingo to call `LocalNotificationService.initialize(context);` which is coming from `flutter_local_notifications` plugin. So I suggest you to recheck your implementation and see why the context could be null in that case.

**Comment by richmondgingingon** [comment]
@darshankawar 
It's weird because I have printed the context and turns out it is not null. I tried to flutter clean and rerun for foreground, background (paused state) & background (terminated state).

The result shows foreground and background (paused state) returns null. The weird thing is in terminated state it still returns null but it redirects to that specific page that I have set on `redirectRoute`.

Here is the foreground log
```
I/flutter (10594): FOREGROUND
I/flutter (10594): redirectRoute result
E/flutter (10594): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (10594): #0      Navigator.of (package:flutter/src/widgets/navigator.dart:2561)
E/flutter (10594): #1      LocalNotificationService.initialize.<anonymous closure> (package:learningapp/local_notification_service.dart:20)
E/flutter (10594): #2      LocalNotificationService.initialize.<anonymous closure> (package:learningapp/local_notification_service.dart:16)
E/flutter (10594): #3      AndroidFlutterLocalNotificationsPlugin._handleMethod (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:460)
E/flutter (10594): #4      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:414)
E/flutter (10594): #5      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:407)
E/flutter (10594): #6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377)
E/flutter (10594): #7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:374)
E/flutter (10594): #8      _invoke2.<anonymous closure> (dart:ui/hooks.dart:190)
E/flutter (10594): #9      _rootRun (dart:async/zone.dart:1426)
E/flutter (10594): #10     _CustomZone.run (dart:async/zone.dart:1328)
E/flutter (10594): #11     _CustomZone.runGuarded (dart:async/zone.dart:1236)
E/flutter (10594): #12     _invoke2 (dart:ui/hooks.dart:189)       
E/flutter (10594): #13     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42)
E/flutter (10594): #14     _Channel.push (dart:ui/channel_buffers.dart:132)
E/flutter (10594): #15     ChannelBuffers.push (dart:ui/channel_buffers.dart:329)
E/flutter (10594): #16     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:583)
E/flutter (10594): #17     _dispatchPlatformMessage (dart:ui/hooks.dart:89)
```

Here is the background (paused state) log
```
I/flutter (10594): BACKGROUND
I/flutter (10594): redirectRoute result
E/flutter (10594): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (10594): #0      Navigator.of (package:flutter/src/widgets/navigator.dart:2561)
E/flutter (10594): #1      _MyAppState.initState.<anonymous closure> (package:learningapp/main.dart:63)
E/flutter (10594): #2      _rootRunUnary (dart:async/zone.dart:1434)
E/flutter (10594): #3      _CustomZone.runUnary (dart:async/zone.dart:1335)
E/flutter (10594): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
E/flutter (10594): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
E/flutter (10594): #6      _DelayedData.perform (dart:async/stream_impl.dart:591)
E/flutter (10594): #7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)
E/flutter (10594): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663)
E/flutter (10594): #9      _rootRun (dart:async/zone.dart:1418)    
E/flutter (10594): #10     _CustomZone.run (dart:async/zone.dart:1328)
E/flutter (10594): #11     _CustomZone.runGuarded (dart:async/zone.dart:1236)
E/flutter (10594): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
E/flutter (10594): #13     _rootRun (dart:async/zone.dart:1426)    
E/flutter (10594): #14     _CustomZone.run (dart:async/zone.dart:1328)
E/flutter (10594): #15     _CustomZone.runGuarded (dart:async/zone.dart:1236)
E/flutter (10594): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
E/flutter (10594): #17     _microtaskLoop (dart:async/schedule_microtask.dart:40)
E/flutter (10594): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
```

Here is the background (terminated state) log
```
I/flutter (11098): TERMINATED
I/flutter (11098): redirectRoute result
E/flutter (11098): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (11098): #0      Navigator.of (package:flutter/src/widgets/navigator.dart:2561)
E/flutter (11098): #1      _MyAppState.initState.<anonymous closure> (package:learningapp/main.dart:47)
E/flutter (11098): #2      _MyAppState.initState.<anonymous closure> (package:learningapp/main.dart:40)
E/flutter (11098): #3      _rootRunUnary (dart:async/zone.dart:1434)
E/flutter (11098): <asynchronous suspension>
E/flutter (11098):
I/flutter (11098): isAuth : true
```

**Comment by richmondgingingon** [comment]
Nevermind, I have an alternative solution for now.

Here is my main
```
//open notif content from terminated state of the app
FirebaseMessaging.instance.getInitialMessage().then((message) {
  if (message != null) {
    print('TERMINATED');
    final redirectRoute = message.data['route'];
    print('redirectRoute $redirectRoute');
    Future.delayed(const Duration(seconds: 6));
    bottomnavbarController.updateIndex(int.parse(redirectRoute));
    Get.offAllNamed(Routes.PAGEWRAPPER);
  }
});
//only works if app in foreground
FirebaseMessaging.onMessage.listen((message) {
  LocalNotificationService.display(message);
});
//onclick notif system tray only works if app in background but not terminated
FirebaseMessaging.onMessageOpenedApp.listen((message) {
  final redirectRoute = message.data['route'];
  if (redirectRoute != null) {
    print('BACKGROUND');
    print('redirectRoute $redirectRoute');
    bottomnavbarController.updateIndex(int.parse(redirectRoute));
    Get.offAllNamed(Routes.PAGEWRAPPER);
  }
});

return Obx(
  () => GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: "Application",
      theme: ThemeData(
        appBarTheme: const AppBarTheme(
            elevation: 0.2,
            foregroundColor: Colors.black,
            backgroundColor: Colors.white),
      ),
      initialRoute: authController.isSkipIntro.isTrue
          ? authController.isAuthAndVerified.isTrue
              ? Routes.PAGEWRAPPER
              : Routes.LOGIN
          : Routes.INTRODUCTION,
      getPages: AppPages.routes,
      unknownRoute: AppPages.routes[11] // added this default route if route returns null
  ),
);
```

I added this  `unknownRoute: AppPages.routes[11]` on `GetMaterialApp`  if the route is null which passing an array to the index of pagewrapper inside apppages class since the route in getInitialMessage() returns null. I still don't know why this is happening. Maybe it is a bug for GetX plugin.
