### ISSUE TITLE
🐛 [flutterfire_ui] "ClientID not set" when clicking "Logout" icon in Web target

### ISSUE THREAD

**Issue by dvoloshyn** [firebase/flutterfire#8246]
## Bug report

"Logout" icon does not work on ProfileScreen complaining `ClientID not set. Either set it on a <meta name=\"google-signin-client_id\" content=\"CLIENT_ID\" /> tag, or pass clientId when calling init()`
But works as expected after adding the following to the index.html:
`<meta name="google-signin-client_id" content="my client id">`

### Steps to reproduce

1. Run: flutter run -d chrome
2. Sign in
3. Click logout icon in the top right corner
4. Observe no reaction from the UI side and see the stacktrace in the console

<details><summary>Click To Expand</summary>

```
Error: Assertion failed: file:///home/dvoloshyn/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.10.0+5/lib/google_sign_in_web.dart:77:9
appClientId != null
"ClientID not set. Either set it on a <meta name=\"google-signin-client_id\" content=\"CLIENT_ID\" /> tag, or pass clientId when calling init()"
    at Object.throw_ [as throw] (http://localhost:3000/dart_sdk.js:5067:11)
    at Object.assertFailed (http://localhost:3000/dart_sdk.js:4992:15)
    at google_sign_in_web.GoogleSignInPlugin.new.init (http://localhost:3000/packages/google_sign_in_web/google_sign_in_web.dart.lib.js:107:42)
    at init.next (<anonymous>)
    at runBody (http://localhost:3000/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:3000/dart_sdk.js:40621:7)
    at google_sign_in_web.GoogleSignInPlugin.new.init (http://localhost:3000/packages/google_sign_in_web/google_sign_in_web.dart.lib.js:104:20)
    at google_sign_in.GoogleSignIn.new.[_ensureInitialized] (http://localhost:3000/packages/google_sign_in/google_sign_in.dart.lib.js:297:121)
    at google_sign_in.GoogleSignIn.new._callMethod (http://localhost:3000/packages/google_sign_in/google_sign_in.dart.lib.js:282:39)
    at _callMethod.next (<anonymous>)
    at runBody (http://localhost:3000/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:3000/dart_sdk.js:40621:7)
    at google_sign_in.GoogleSignIn.new.[_callMethod] (http://localhost:3000/packages/google_sign_in/google_sign_in.dart.lib.js:281:20)
    at google_sign_in.GoogleSignIn.new._addMethodCall (http://localhost:3000/packages/google_sign_in/google_sign_in.dart.lib.js:315:39)
    at _addMethodCall.next (<anonymous>)
    at runBody (http://localhost:3000/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:3000/dart_sdk.js:40621:7)
    at google_sign_in.GoogleSignIn.new.[_addMethodCall] (http://localhost:3000/packages/google_sign_in/google_sign_in.dart.lib.js:312:20)
    at google_sign_in.GoogleSignIn.new.signOut (http://localhost:3000/packages/google_sign_in/google_sign_in.dart.lib.js:365:34)
    at google_provider.GoogleProviderImpl.new.signOut$ (http://localhost:3000/packages/flutterfire_ui/src/auth/configs/email_link_provider_configuration.dart.lib.js:10243:33)
    at signOut$.next (<anonymous>)
    at runBody (http://localhost:3000/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:3000/dart_sdk.js:40621:7)
    at google_provider.GoogleProviderImpl.new.signOut (http://localhost:3000/packages/flutterfire_ui/src/auth/configs/email_link_provider_configuration.dart.lib.js:10242:20)
    at MappedIterator.new.<anonymous> (http://localhost:3000/packages/flutterfire_ui/src/auth/oauth/oauth_providers.dart.lib.js:102:113)
    at MappedIterator.new.moveNext (http://localhost:3000/dart_sdk.js:24262:71)
    at JsIterator.next (http://localhost:3000/dart_sdk.js:6873:21)
    at Function.wait (http://localhost:3000/dart_sdk.js:34990:20)
    at signOut (http://localhost:3000/packages/flutterfire_ui/src/auth/oauth/oauth_providers.dart.lib.js:103:28)
    at signOut.next (<anonymous>)
    at runBody (http://localhost:3000/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:3000/dart_sdk.js:40621:7)
    at Function.signOut (http://localhost:3000/packages/flutterfire_ui/src/auth/oauth/oauth_providers.dart.lib.js:99:20)
    at signOut (http://localhost:3000/packages/flutterfire_ui/src/auth/configs/email_link_provider_configuration.dart.lib.js:13110:46)
    at signOut.next (<anonymous>)
    at runBody (http://localhost:3000/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:3000/dart_sdk.js:40621:7)
    at Function.signOut (http://localhost:3000/packages/flutterfire_ui/src/auth/configs/email_link_provider_configuration.dart.lib.js:13107:20)
    at http://localhost:3000/packages/flutterfire_ui/src/auth/configs/email_link_provider_configuration.dart.lib.js:5850:449
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:3000/packages/flutter/src/material/icon_button.dart.lib.js:40468:31)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:3000/packages/flutter/src/gestures/recognizer.dart.lib.js:190:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:3000/packages/flutter/src/gestures/tap.dart.lib.js:409:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:3000/packages/flutter/src/gestures/tap.dart.lib.js:217:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:3000/packages/flutter/src/gestures/tap.dart.lib.js:166:23)
    at tap.TapGestureRecognizer.new.handleEvent (http://localhost:3000/packages/flutter/src/gestures/recognizer.dart.lib.js:426:16)
    at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:3000/packages/flutter/src/gestures/pointer_router.dart.lib.js:86:9)
    at http://localhost:3000/packages/flutter/src/gestures/pointer_router.dart.lib.js:112:26
    at LinkedMap.new.forEach (http://localhost:3000/dart_sdk.js:27679:11)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:3000/packages/flutter/src/gestures/pointer_router.dart.lib.js:110:29)
    at pointer_router.PointerRouter.new.route (http://localhost:3000/packages/flutter/src/gestures/pointer_router.dart.lib.js:105:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:3000/packages/flutter/src/gestures/binding.dart.lib.js:364:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:3000/packages/flutter/src/gestures/binding.dart.lib.js:352:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:3000/packages/flutter/src/rendering/layer.dart.lib.js:5427:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:3000/packages/flutter/src/gestures/binding.dart.lib.js:328:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:3000/packages/flutter/src/gestures/binding.dart.lib.js:302:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:3000/packages/flutter/src/gestures/binding.dart.lib.js:292:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:3000/packages/flutter/src/gestures/binding.dart.lib.js:283:54)
    at Object.invoke1 (http://localhost:3000/dart_sdk.js:190405:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:3000/dart_sdk.js:171081:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:3000/dart_sdk.js:171963:49)
    at http://localhost:3000/dart_sdk.js:172401:28
    at http://localhost:3000/dart_sdk.js:172357:16
    at loggedHandler (http://localhost:3000/dart_sdk.js:172062:11)

```

</details>

### Expected behavior

Either the logout button should work without specifying google-signin-client_id in index.html or this should be clearly documented

### Sample project

<details><summary>Click To Expand</summary>

```
FlutterFireUIAuth.configureProviders([
    const GoogleProviderConfiguration(
        clientId: 'my client id'),
  ], app: firebaseApp);

home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return const SignInScreen(showAuthActionSwitch: false);
          }
          return const ProfileScreen();
        },
      ),
```

</details>

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on Manjaro Linux 5.16.11-2-MANJARO, locale en_US.UTF-8)
    • Flutter version 2.10.3 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (7 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/dvoloshyn/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /home/dvoloshyn/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/dvoloshyn/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401
    • Flutter plugin version 65.1.2
    • Dart plugin version 211.7808
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /home/dvoloshyn/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.6777.52
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Chromium 99.0.4844.51 Arch Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.1
Flutter SDK 2.10.3
myapp 1.0.0+1

dependencies:
- cloud_firestore 3.1.10 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.4
- firebase_auth 3.3.9 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.13.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutterfire_ui 0.3.5+1 [cloud_firestore collection crypto desktop_webview_auth email_validator firebase_auth firebase_core firebase_database firebase_dynamic_links flutter flutter_facebook_auth flutter_localizations flutter_svg google_sign_in sign_in_with_apple twitter_login]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 5.5.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.10 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- desktop_webview_auth 0.0.5 [crypto flutter http]
- email_validator 2.0.1
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 6.2.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.9 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.5 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database 9.0.8 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_database_platform_interface 0.2.1+1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.0+7 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_dynamic_links 4.0.8 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.1+1 [firebase_core flutter meta plugin_platform_interface]
- flutter_facebook_auth 4.1.1 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_facebook_auth_platform_interface 3.0.1 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 3.0.0+1 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- google_sign_in 5.2.4 [flutter google_sign_in_platform_interface google_sign_in_web]
- google_sign_in_platform_interface 2.1.2 [flutter quiver]
- google_sign_in_web 0.10.0+5 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- lints 1.0.1
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- petitparser 4.4.0 [meta]
- plugin_platform_interface 2.1.2 [meta]
- quiver 3.0.1+1 [matcher]
- sign_in_with_apple 3.3.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- twitter_login 4.0.1 [flutter crypto http]
- typed_data 1.3.0 [collection]
- vector_math 2.1.1
- xml 5.3.1 [collection meta petitparser]

```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report. I do see the same behavior upon running the code snippet provided using latest stable version.

`flutterfire_ui: ^0.3.5+1`

```
`Error: Assertion failed: file:///home/dvoloshyn/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.10.0+5/lib/google_sign_in_web.dart:77:9
appClientId != null
"ClientID not set. Either set it on a <meta name=\"google-signin-client_id\" content=\"CLIENT_ID\" /> tag, or pass clientId when calling init()"
    at Object.throw_ [as throw] (http://localhost:3000/dart_sdk.js:5067:11)
    at Object.assertFailed (http://localhost:3000/dart_sdk.js:4992:15)
    at google_sign_in_web.GoogleSignInPlugin.new.init (http://localhost:3000/packages/google_sign_in_web/google_sign_in_web.dart.lib.js:107:42)
    at init.next (<anonymous>)
    at runBody (http://localhost:3000/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:3000/dart_sdk.js:40621:7)
    at google_sign_in_web.GoogleSignInPlugin.new.init (http://localhost:3000/packages/google_sign_in_web/google_sign_in_web.dart.lib.js:104:20)
    at google_sign_in.GoogleSignIn.new.[_ensureInitialized] (http://localhost:3000/packages/google_sign_in/google_sign_in.dart.lib.js:297:121)
    at google_sign_in.GoogleSignIn.new._callMethod (http://localhost:3000/packages/google_sign_in/google_sign_in.dart.lib.js:282:39)
    at _callMethod.next (<anonymous>)
    at runBody (http://localhost:3000/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:3000/dart_sdk.js:40621:7)
    at google_sign_in.GoogleSignIn.new.[_callMethod] (http://localhost:3000/packages/google_sign_in/google_sign_in.dart.lib.js:281:20)
    at google_sign_in.GoogleSignIn.new._addMethodCall (http://localhost:3000/packages/google_sign_in/google_sign_in.dart.lib.js:315:39)
    at _addMethodCall.next (<anonymous>)`
```

The error is pointing to `google_sign_in_web-0.10.0+5` while using `GoogleProviderConfiguration` as the auth provider.
