### ISSUE TITLE
[cloud_firestore] Hot restart on web throws when setting firestore settings or enablePersistence()

### ISSUE THREAD

**Issue by dvoloshyn** [firebase/flutterfire#8336]
## Bug report

Setting Firestore settings or enabling web persistence breaks hot restart. As hot reload is unavailable on web it's kind of a blocker.

### Steps to reproduce

1. Set firestore settings or enablePersistence() in main()
2. Run in chrome
3. Trigger hot restart
4. Observe the exceptions

### Expected behavior

Set settings and enablePersistence() should be idempotent in a way that:
- Settings the same settings multiple times should be no-op
- enablePersistence() should be no-op if it's already enabled

Until it's fixed properly we need a workaround. For example a way to detect if firestore already initialized, if firebase already initialized or, at least, that it's a hot restart instead of a cold start

### Sample project

<details><summary>Click To Expand</summary>

```
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final app = await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform);
  final store = FirebaseFirestore.instanceFor(app: app);
  store.settings = const Settings(
    persistenceEnabled: true,
    cacheSizeBytes: 40 * 1000 * 1000,
  );
  await store.enablePersistence();
  runApp(const MaterialApp());
}
```

</details>

---

## Additional context

<details><summary>Set settings exception. Click To Expand</summary>

```
FirebaseError: Firestore has already been started and its settings can no longer be changed. You can only modify settings before calling any other methods on a Firestore object.
    at new Br (https://www.gstatic.com/firebasejs/8.10.1/firebase-firestore.js:1:52445)
    at Sp.dp._setSettings (https://www.gstatic.com/firebasejs/8.10.1/firebase-firestore.js:1:270102)
    at Mg.settings (https://www.gstatic.com/firebasejs/8.10.1/firebase-firestore.js:1:313340)
    at firestore.Firestore._fromJsObject.settings (http://localhost:3000/packages/cloud_firestore_web/src/interop/utils/utils.dart.lib.js:221:28)
    at cloud_firestore_web.FirebaseFirestoreWeb.new.set settings [as settings] (http://localhost:3000/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:844:27)
    at cloud_firestore.FirebaseFirestore.__.set settings [as settings] (http://localhost:3000/packages/cloud_firestore/cloud_firestore.dart.lib.js:1486:33)
    at main (http://localhost:3000/packages/worldofgoals/main.dart.lib.js:173:22)
    at main.next (<anonymous>)
    at http://localhost:3000/dart_sdk.js:40571:33
    at _RootZone.runUnary (http://localhost:3000/dart_sdk.js:40441:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:3000/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:3000/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:3000/dart_sdk.js:35969:17)
    at _Future.new.[_completeWithValue] (http://localhost:3000/dart_sdk.js:35817:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:3000/dart_sdk.js:35838:35)
    at Object._microtaskLoop (http://localhost:3000/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:3000/dart_sdk.js:40714:13)
    at http://localhost:3000/dart_sdk.js:36191:9
```

</details>

<details><summary>enablePersistence() exception. Click To Expand</summary>

```
Error: [cloud_firestore/failed-precondition] Firestore has already been started and persistence can no longer be enabled. You can only enable persistence before calling any other methods on a Firestore object.
    https://www.gstatic.com/firebasejs/8.10.1/firebase-firestore.js 1:52445   new Br
https://www.gstatic.com/firebasejs/8.10.1/firebase-firestore.js 1:281107  kp
https://www.gstatic.com/firebasejs/8.10.1/firebase-firestore.js 1:311723  forceOwnership
https://www.gstatic.com/firebasejs/8.10.1/firebase-firestore.js 1:311855  enableIndexedDbPersistence
https://www.gstatic.com/firebasejs/8.10.1/firebase-firestore.js 1:315750  enablePersistence
packages/cloud_firestore_web/src/interop/firestore.dart 61:31             enablePersistence
packages/firebase_core/src/internals.dart 87:21                           guardWebExceptions
packages/cloud_firestore_web/src/internals.dart 11:20                     convertWebExceptions
packages/cloud_firestore_web/cloud_firestore_web.dart 156:12              enablePersistence
packages/cloud_firestore/src/firestore.dart 94:22                         enablePersistence
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54        runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5        _async
packages/cloud_firestore/src/firestore.dart 91:33                         enablePersistence
packages/worldofgoals/main.dart 16:14                                     main
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50        <fn>
dart-sdk/lib/async/zone.dart 1685:54                                      runUnary
dart-sdk/lib/async/future_impl.dart 159:18                                handleValue
dart-sdk/lib/async/future_impl.dart 766:44                                handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                                _propagateToListeners
dart-sdk/lib/async/future_impl.dart 601:5                                 [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 639:7                                 callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                          _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                           _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15       <fn>


    at Object.createErrorWithStack (http://localhost:3000/dart_sdk.js:5080:12)
    at Function._throw (http://localhost:3000/dart_sdk.js:20337:18)
    at Function.throwWithStackTrace (http://localhost:3000/dart_sdk.js:20334:18)
    at async._AsyncCallbackEntry.new.callback (http://localhost:3000/dart_sdk.js:40851:18)
    at Object._microtaskLoop (http://localhost:3000/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:3000/dart_sdk.js:40714:13)
    at http://localhost:3000/dart_sdk.js:36191:9
```

</details>

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on Manjaro Linux 5.16.11-2-MANJARO, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.1
Flutter SDK 2.10.3

dependencies:
- cloud_firestore 3.1.10 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.4
- firebase_auth 3.3.11 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.13.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutterfire_ui 0.3.6+1 [cloud_firestore collection crypto desktop_webview_auth email_validator firebase_auth firebase_core firebase_database firebase_dynamic_links flutter flutter_facebook_auth flutter_localizations flutter_svg google_sign_in sign_in_with_apple twitter_login]
- go_router 3.0.5 [collection flutter flutter_web_plugins logging]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 5.5.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.10 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- desktop_webview_auth 0.0.6 [crypto flutter http]
- email_validator 2.0.1
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 6.2.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.9 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.5 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database 9.0.8 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_database_platform_interface 0.2.1+1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.0+7 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_dynamic_links 4.1.1 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.2+1 [firebase_core flutter meta plugin_platform_interface]
- flutter_facebook_auth 4.1.2 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_facebook_auth_platform_interface 3.0.1 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 3.0.0+1 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- google_sign_in 5.2.4 [flutter google_sign_in_platform_interface google_sign_in_web]
- google_sign_in_platform_interface 2.1.2 [flutter quiver]
- google_sign_in_web 0.10.0+5 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- lints 1.0.1
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- petitparser 4.4.0 [meta]
- plugin_platform_interface 2.1.2 [meta]
- quiver 3.0.1+1 [matcher]
- sign_in_with_apple 3.3.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- twitter_login 4.0.1 [flutter crypto http]
- typed_data 1.3.0 [collection]
- vector_math 2.1.1
- xml 5.3.1 [collection meta petitparser]

```

</details>

---

**Comment by darshankawar** [comment]
@dvoloshyn 
There's similar open issue describing your case, https://github.com/firebase/flutterfire/issues/6216
Please follow-up in it for further updates.
Closing this as a duplicate.
