### ISSUE TITLE
🐛 [remote_config] Error on ios: Failed to get installations token.

### ISSUE THREAD

**Issue by jimmyff** [firebase/flutterfire#8377]
Remote config is failing to initalise on iOS (Android is working and live in production), i'm giving me the following error on iOS:

```
Exception has occurred.
FirebaseException ([firebase_remote_config/internal] Failed to get installations token. Error : Error Domain=com.firebase.installations Code=0 "Underlying error: unsupported URL" UserInfo={NSLocalizedFailureReason=Underlying error: unsupported URL, NSUnderlyingError=0x281fc5500 {Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x281fc51d0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <5A109819-E35F-49C4-B747-C25FB34C90C4>.<3>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <5A109819-E35F-49C4-B747-C25FB34C90C4>.<3>"
), NSLocalizedDescription=unsupported URL}}}.

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
<asynchronous suspension>
#2      MethodChannelFirebaseRemoteConfig.fetch (package:firebase_remote_config_platform_interface/src/method_channel/method_channel_firebase_remote_config.dart:132:7)
<asynchronous suspension>
#3      FbRemoteConfig.init (package:mobile/firebase/fb_remote_config.dart:54:7)
<asynchronous suspension>
#4      FbApi._initRemoteConfig (package:mobile/firebase_api.dart:162:5)
<asynchronous suspension>
#5      FbApi.init (package:mobile/firebase_api.dart:134:5)
<asynchronous suspension>
)
```

```
  firebase_remote_config:
    dependency: "direct main"
    description:
      name: firebase_remote_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
```

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3 21E230 darwin-x64, locale en-GB)
    • Flutter version 2.10.3 at /Users/jimmyff/flutter-sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jimmyff/Library/Android/sdk
    • Platform android-31, build-tools 29.0.3
    • Java binary at: /Applications/Development/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Development/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at /Applications/Development/IntelliJ IDEA.app
    ✗ Flutter plugin version 15.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 172.3317.48
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] IntelliJ IDEA Ultimate Edition (version EAP IU-172.1909.2)
    • IntelliJ at /Applications/Development/IntelliJ IDEA 2017.1.2 EAP.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.65.1)
    • VS Code at /Applications/Development/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • James’s iPhone (mobile) • 00008020-001A0D811A78002E • ios            • iOS 15.3.1 19D52
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome
      100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@jimmyff 
Thanks for the report. I am unable to replicate this using latest plugin version and with plugin example on iOS.
Are there any specific steps to replicate along with a minimal code ?

**Comment by jimmyff** [comment]
I'm afraid I do not know how to reproduce the issue, I've just cloned the `remote_config` example project and run that using my same credentials and it builds and runs correctly.

I've upgraded the problematic project to the latest packages & done cleans, fresh rebuilds and I'm unable to get past this. If I take all the `remote_config` code out, my app loads (firestore, analytics, auth etc) and operates correctly showing that the firebase credentials are all present and correct. Remote config runs perfectly on Android builds.

I am happy to share the code base with you but I cannot do this publicly.

Thanks

**Comment by jimmyff** [comment]
@darshankawar the bot didn't remove the blocked tag

**Comment by darshankawar** [comment]
Yes, there's known issue with the bot in this repo currently. I have read your response and looking to get further details from my side.

**Comment by darshankawar** [comment]
@jimmyff 
Looking at the error log provided, it seems to be failing due to below error:

`Error Domain=com.firebase.installations Code=0 "Underlying error: unsupported URL" UserInfo={NSLocalizedFailureReason=Underlying error: unsupported URL`

I suggest you to open this in native iOS firebase sdk github and see what they say. https://github.com/firebase/firebase-ios-sdk/issues

**Comment by jimmyff** [comment]
@darshankawar I have resolved the issue. It seems that when i renamed the project, the GoogleServices-info.plist file became out of date, providing a new version from firebase console resolved the issue.

Thank you for your assistance
