### ISSUE TITLE
🐛 [SMS] GMS core API Availability. ConnectionResult=19, tag=null

### ISSUE THREAD

**Issue by mdddj** [firebase/flutterfire#8436]
## Bug report

**Describe the bug**
When I execute this code
```dart
FirebaseAuth.instance.verifyPhoneNumber(
        phoneNumber: phoneNumber,
        verificationCompleted: (PhoneAuthCredential phoneAuthCredential) {
        },
        verificationFailed: (FirebaseAuthException error) {
          print(error);
        },
        codeSent: (
          String verificationId,
          int? forceResendingToken,
        ) {
          print('--$verificationId -- $forceResendingToken');          
        },
        codeAutoRetrievalTimeout: (String verificationId) {
          print('verificationId : $verificationId');
        });
```
console print
```dart
W/GoogleApiAvailability( 8821): GMS core API Availability. ConnectionResult=19, tag=null
W/GoogleApiAvailability( 8821): java.lang.IllegalArgumentException
W/GoogleApiAvailability( 8821): 	at com.google.android.gms.common.GoogleApiAvailability.zae(com.google.android.gms:play-services-base@@18.0.1:2)
W/GoogleApiAvailability( 8821): 	at com.google.android.gms.common.GoogleApiAvailability.zah(com.google.android.gms:play-services-base@@18.0.1:6)
W/GoogleApiAvailability( 8821): 	at com.google.android.gms.common.api.internal.GoogleApiManager.zaG(com.google.android.gms:play-services-base@@18.0.1:1)
W/GoogleApiAvailability( 8821): 	at com.google.android.gms.common.api.internal.zabq.zar(com.google.android.gms:play-services-base@@18.0.1:21)
W/GoogleApiAvailability( 8821): 	at com.google.android.gms.common.api.internal.zabq.onConnectionFailed(com.google.android.gms:play-services-base@@18.0.1:1)
W/GoogleApiAvailability( 8821): 	at com.google.android.gms.common.internal.zai.onConnectionFailed(com.google.android.gms:play-services-base@@18.0.1:1)
W/GoogleApiAvailability( 8821): 	at com.google.android.gms.common.internal.zzf.zzb(com.google.android.gms:play-services-basement@@18.0.1:2)
W/GoogleApiAvailability( 8821): 	at com.google.android.gms.common.internal.zza.zza(com.google.android.gms:play-services-basement@@18.0.1:3)
W/GoogleApiAvailability( 8821): 	at com.google.android.gms.common.internal.zzc.zze(com.google.android.gms:play-services-basement@@18.0.1:3)
W/GoogleApiAvailability( 8821): 	at com.google.android.gms.common.internal.zzb.handleMessage(com.google.android.gms:play-services-basement@@18.0.1:31)
W/GoogleApiAvailability( 8821): 	at android.os.Handler.dispatchMessage(Handler.java:107)
W/GoogleApiAvailability( 8821): 	at android.os.Looper.loop(Looper.java:224)
W/GoogleApiAvailability( 8821): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/GoogleApiAvailability( 8821): Unexpected error code 19
```

What happened to this? I couldn't find any solution online

**Comment by darshankawar** [comment]
@mdddj 
Does the device / emulator you are using has google play services enabled ?
Do you have the gms-services implementation included in your build. gradle ?
