### ISSUE TITLE
🐛 [firebase_remote_config 2.0.3] [web] TypeError: dart.global.firebase.remoteConfig is not a function

### ISSUE THREAD

**Issue by tgpsantos** [firebase/flutterfire#8457]
## Bug report

Hello guys,

I have a mobile project that I'm starting to convert to web platform. I'm using the most recent version of firebase remote config (2.0.3) and up-to-date flutter sdk (2.10.4)

When I run 

```dart
FirebaseRemoteConfig remoteConfig = FirebaseRemoteConfig.instance;
await remoteConfig.setConfigSettings(RemoteConfigSettings(minimumFetchInterval: const Duration(minutes: 10), fetchTimeout: const Duration(minutes: 1)));

```

I get the following stack trace.

`TypeError: dart.global.firebase.remoteConfig is not a function
    at Object.getRemoteConfigInstance (http://localhost:62737/packages/firebase_remote_config_web/src/interop/firebase_remote_config.dart.lib.js:314:81)
    at firebase_remote_config_web.FirebaseRemoteConfigWeb.new.get [_delegate] (http://localhost:62737/packages/firebase_remote_config_web/firebase_remote_config_web.dart.lib.js:76:75)
    at firebase_remote_config_web.FirebaseRemoteConfigWeb.new.setConfigSettings (http://localhost:62737/packages/firebase_remote_config_web/firebase_remote_config_web.dart.lib.js:162:11)
    at firebase_remote_config.FirebaseRemoteConfig.__.setConfigSettings (http://localhost:62737/packages/firebase_remote_config/firebase_remote_config.dart.lib.js:145:30)
    at remote_config.AgitRemoteConfig._privateConstructor.initSingleton (http://localhost:62737/packages/camera/routes/auth/widgets/auth_button.dart.lib.js:169296:33)
    at initSingleton.next (<anonymous>)
    at runBody (http://localhost:62737/dart_sdk.js:43013:34)
    at Object._async [as async] (http://localhost:62737/dart_sdk.js:43044:7)
`

I followed Flutter Fire steps to integrate web by adding the firebasejs script and firebase app init into the index.html file.

Thanks for any help in advance!

### Flutter doctor

<details><summary> Doctor summary (to see all details, run flutter doctor -v): </summary>
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1645], locale pt-PT)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 4.2)
[√] VS Code (version 1.66.1)
[√] VS Code, 32-bit edition (version 1.32.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

</details>

**Comment by tgpsantos** [comment]
I had added missing dependency in index.html but for some reason and to re-run the app to take effect. Problem solved!
