### ISSUE TITLE
🐛 [firebase_dynamic_links] NullPointerException

### ISSUE THREAD

**Issue by deepak786** [firebase/flutterfire#8516]
Exception from Crashlytics:

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void ce.j.c(java.lang.String, java.lang.Object)' on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void ce.j.c(java.lang.String, java.lang.Object)' on a null object reference
       at io.flutter.plugins.firebase.dynamiclinks.FlutterFirebaseDynamicLinksPlugin.lambda$onNewIntent$0(FlutterFirebaseDynamicLinksPlugin.java:10)
       at io.flutter.plugins.firebase.dynamiclinks.FlutterFirebaseDynamicLinksPlugin.$r8$lambda$ACUODnZRoJeRaRyWoWMxrpCGBr8(FlutterFirebaseDynamicLinksPlugin.java)
       at io.flutter.plugins.firebase.dynamiclinks.FlutterFirebaseDynamicLinksPlugin$$InternalSyntheticLambda$0$f4586827c97c7727f02d69929341fcf7a7aa3c29ff490a0a1dabaf6d8d894568$0.onSuccess(FlutterFirebaseDynamicLinksPlugin.java:4)
       at com.google.android.gms.tasks.zzm.run(zzm.java:25)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7806)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

![Screen Shot 2022-04-25 at 3 28 02 PM](https://user-images.githubusercontent.com/14223997/165066729-f814d6be-8d5e-4951-b534-712ffc8c8c2b.png)

There are no reproducible steps.

**Comment by darshankawar** [comment]
Since there doesn't seem to be any reproducible use case / code sample,  based on the error log, I'll keep it open for further investigation from team.

**Comment by russellwheatley** [comment]
Hey @deepak786, is this only started to occur in the latest Dynamic Links version?

**Comment by deepak786** [comment]
Hi @russellwheatley,

In the app version 3.4.5 (latest release), I'm using `firebase_dynamic_links: 4.1.1`.
In the app version 3.3.5, `firebase_dynamic_links: 4.0.5` is used.

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void je.j.c(java.lang.String, java.lang.Object)' on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void je.j.c(java.lang.String, java.lang.Object)' on a null object reference
       at io.flutter.plugins.firebase.dynamiclinks.FlutterFirebaseDynamicLinksPlugin.lambda$onNewIntent$0(FlutterFirebaseDynamicLinksPlugin.java:10)
       at io.flutter.plugins.firebase.dynamiclinks.FlutterFirebaseDynamicLinksPlugin.$r8$lambda$ACUODnZRoJeRaRyWoWMxrpCGBr8(FlutterFirebaseDynamicLinksPlugin.java)
       at io.flutter.plugins.firebase.dynamiclinks.FlutterFirebaseDynamicLinksPlugin$$InternalSyntheticLambda$0$f4586827c97c7727f02d69929341fcf7a7aa3c29ff490a0a1dabaf6d8d894568$0.onSuccess(FlutterFirebaseDynamicLinksPlugin.java:4)
       at com.google.android.gms.tasks.zzm.run(zzm.java:25)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7562)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```


Last 7 days report
![Screen Shot 2022-05-05 at 11 08 21 PM](https://user-images.githubusercontent.com/14223997/166981061-9086e6ce-3928-4a63-9ca4-d555d84ec2d5.png)

Last 90 days' report
![Screen Shot 2022-05-05 at 11 11 08 PM](https://user-images.githubusercontent.com/14223997/166981688-1f3e0d1a-7f46-4134-930f-85b05aebb19d.png)

**Comment by Lyokone** [comment]
@deepak786 Several versions have been released since you reported the NullPointerException, does it still happens?

**Comment by deepak786** [comment]
@Lyokone Yes, still has the same issue

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void xd.k.c(java.lang.String, java.lang.Object)' on a null object reference
       at io.flutter.plugins.firebase.dynamiclinks.FlutterFirebaseDynamicLinksPlugin.lambda$onNewIntent$0(FlutterFirebaseDynamicLinksPlugin.java:10)
       at io.flutter.plugins.firebase.dynamiclinks.FlutterFirebaseDynamicLinksPlugin.$r8$lambda$ACUODnZRoJeRaRyWoWMxrpCGBr8(FlutterFirebaseDynamicLinksPlugin.java)
       at io.flutter.plugins.firebase.dynamiclinks.FlutterFirebaseDynamicLinksPlugin$$InternalSyntheticLambda$0$f4586827c97c7727f02d69929341fcf7a7aa3c29ff490a0a1dabaf6d8d894568$0.onSuccess(FlutterFirebaseDynamicLinksPlugin.java:4)
       at com.google.android.gms.tasks.zzm.run(zzm.java:25)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
![Screen Shot 2022-10-04 at 1 24 28 PM](https://user-images.githubusercontent.com/14223997/193765360-1ea2ca5f-c8a0-4735-8c7c-c33f2be3dcd9.png)
![Screen Shot 2022-10-04 at 1 24 40 PM](https://user-images.githubusercontent.com/14223997/193765373-4ace56f1-483c-4136-9628-7dcbb794c427.png)


Version 3.6.5 and 3.6.6 is using the `firebase_dynamic_links: 4.3.7`

**Comment by russellwheatley** [comment]
Hey @deepak786, I've created a pull request that ought to address the problem. See here: https://github.com/firebase/flutterfire/pull/9879
