### ISSUE TITLE
🐛 [firebase_auth] NullPointerException: Attempt to invoke interface method 'java.lang.String com.google.firebase.auth.u0.x()' on a null object reference

### ISSUE THREAD

**Issue by stx** [firebase/flutterfire#8517]
## Bug report

We found this unhandled error on production on Flutter stable 2.10.4 w/firebase_auth 3.3.13. Only seen once ever, so quite rare.

Android Version: 12
Device: SM-G991W

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.google.firebase.auth.u0.x()' on a null object reference
    at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.parseUserInfoList(FlutterFirebaseAuthPlugin.java:3)
    at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.parseFirebaseUser(FlutterFirebaseAuthPlugin.java:14)
    at io.flutter.plugins.firebase.auth.IdTokenChannelStreamHandler.a(IdTokenChannelStreamHandler.java:5)
    at io.flutter.plugins.firebase.auth.m0.a
    at com.google.firebase.auth.p1.run(com.google.firebase:firebase-auth@@21.0.3:4)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8663)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 2.10.4 at /Users/james/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/james/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • Apollo (mobile) • da060dc78ac99566c39cb688206b34cb424a5ee1 • ios            • iOS 15.3.1 19D52
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 100.0.4896.75
    ! Error: Apollo is busy: Preparing the watch for development via Apollo. Xcode will continue when Apollo is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.2
Flutter SDK 2.10.4
tessie 4.4.3+251

dependencies:
- auto_size_text 3.0.0 [flutter]
- cached_network_image 3.2.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- clipboard 0.1.3 [flutter]
- cloud_firestore 3.1.11 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 3.2.11 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- collection 1.15.0
- cupertino_icons 1.0.4
- drift 1.5.0 [async convert collection meta stream_channel sqlite3]
- email_validator 2.0.1
- expandable 5.0.1 [flutter]
- file_picker 4.5.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_analytics 9.1.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.3.13 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.14.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 4.1.2 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 11.2.12 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flare_flutter 3.0.2 [collection flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_branch_sdk 5.0.0 [flutter flutter_web_plugins plugin_platform_interface js flutter_lints]
- flutter_map 0.14.0 [async collection flutter http intl latlong2 meta positioned_tap_detector_2 proj4dart transparent_image tuple vector_math]
- flutter_map_location_marker 3.1.0 [flutter flutter_compass flutter_map geolocator latlong2]
- flutter_map_marker_cluster 0.4.4 [flutter flutter_map latlong2 flutter_map_marker_popup]
- flutter_native_splash 2.1.5 [args flutter flutter_web_plugins image js lint meta path universal_io xml yaml]
- flutter_native_timezone 2.0.0 [flutter_web_plugins flutter js]
- flutter_secure_storage 5.0.2 [meta flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows]
- flutter_spinkit 5.1.0 [flutter]
- font_awesome_flutter 9.0.0 [flutter]
- geocoding 2.0.4 [flutter geocoding_platform_interface]
- get_it 7.2.0 [async collection]
- go_router 3.0.7 [collection flutter flutter_web_plugins logging]
- google_place 0.4.7 [http]
- http 0.13.4 [async http_parser meta path]
- in_app_review 2.0.4 [flutter in_app_review_platform_interface]
- intl 0.17.0 [clock path]
- latlong2 0.8.1 [intl]
- local_auth 1.1.11 [flutter flutter_plugin_android_lifecycle intl platform]
- location 4.3.0 [flutter location_platform_interface location_web]
- logger 1.1.0
- lottie 1.2.2 [archive flutter path vector_math]
- modal_bottom_sheet 2.0.1 [flutter]
- moor_flutter 4.1.0 [moor sqflite path flutter]
- package_info 2.0.2 [flutter]
- path 1.8.0
- path_provider 2.0.9 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- pinput 2.2.7 [flutter smart_auth]
- purchases_flutter 3.9.5 [flutter freezed_annotation json_annotation]
- qr_flutter 4.0.0 [flutter qr]
- recase 4.0.0
- reorderable_grid_view 2.2.2 [flutter]
- rxdart 0.27.3
- sentry_flutter 6.5.0-beta.1 [flutter flutter_web_plugins sentry package_info_plus meta]
- share_plus 4.0.3 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.0.13 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sqlite3_flutter_libs 0.5.5 [flutter]
- syncfusion_flutter_charts 20.1.47+1 [flutter intl vector_math syncfusion_flutter_core]
- syncfusion_flutter_core 20.1.47 [vector_math flutter]
- syncfusion_flutter_datepicker 20.1.47 [flutter intl syncfusion_flutter_core]
- timeago 3.2.2
- universal_html 2.0.8 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_platform 1.0.0+1
- url_launcher 6.0.20 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_web 2.0.9 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_strategy 0.2.0 [flutter_web_plugins]
- video_player 2.3.0 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- visibility_detector 0.2.2 [flutter]
- webview_flutter 3.0.2 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- build_runner 2.1.8 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- drift_dev 1.5.2 [charcode collection recase meta path json_annotation stream_transform args logging cli_util yaml io drift sqlite3 sqlparser analyzer analyzer_plugin source_span package_config pub_semver build build_resolvers build_config dart_style source_gen]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver archive async boolean_selector characters charcode clock collection crypto matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_launcher_icons 0.9.2 [args image path yaml]
- sentry_dart_plugin 1.0.0-beta.2 [yaml injector ansicolor package_config system_info2]
- test 1.19.5 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

dependency overrides:
- flutter_map 0.14.0 [async collection flutter http intl latlong2 meta positioned_tap_detector_2 proj4dart transparent_image tuple vector_math]

transitive dependencies:
- _fe_analyzer_shared 31.0.0 [meta]
- analyzer 2.8.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- analyzer_plugin 0.8.0 [analyzer collection dart_style pub_semver yaml]
- animated_stack_widget 0.0.4 [flutter]
- ansicolor 2.0.1
- archive 3.1.6 [crypto path]
- args 2.3.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.2.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.6 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.4 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 5.5.2 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.11 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.1.2 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.2.10 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- convert 3.0.1 [typed_data]
- coverage 1.0.3 [args logging package_config path source_maps stack_trace vm_service]
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.1 [source_span]
- dart_style 2.2.1 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- file_utils 1.0.1 [globbing path]
- firebase_analytics_platform_interface 3.1.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+9 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.2.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.11 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.5 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_dynamic_links_platform_interface 0.2.2+2 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.2.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.2.10 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_blurhash 0.6.4 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_compass 0.7.0 [flutter]
- flutter_lints 1.0.4 [lints]
- flutter_map_marker_popup 2.1.2 [flutter flutter_map latlong2 animated_stack_widget]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_secure_storage_linux 1.1.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 1.1.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.0 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.0.2 [flutter flutter_web_plugins flutter_secure_storage_platform_interface js]
- flutter_secure_storage_windows 1.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- freezed_annotation 1.1.0 [collection json_annotation meta]
- frontend_server_client 2.1.2 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- geocoding_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- geolocator 8.2.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- geolocator_android 3.1.5 [flutter geolocator_platform_interface]
- geolocator_apple 2.1.1+1 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.4 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.4 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.0 [flutter geolocator_platform_interface]
- glob 2.0.2 [async collection file path string_scanner]
- globbing 1.0.0 [path]
- graphs 2.1.0 [collection]
- html 0.15.0 [csslib source_span]
- http_multi_server 3.2.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.1.3 [archive meta xml]
- in_app_review_platform_interface 2.0.3 [flutter url_launcher plugin_platform_interface platform]
- injector 2.0.0
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.4.0 [meta]
- lint 1.8.2
- lints 1.0.1
- lists 1.0.1 [meta]
- location_platform_interface 2.3.0 [flutter meta plugin_platform_interface]
- location_web 3.1.1 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- mgrs_dart 2.0.0 [unicode]
- mime 1.0.1
- moor 4.6.1+1 [async convert collection drift meta stream_channel sqlite3]
- node_preamble 2.0.1
- octo_image 1.0.1 [flutter flutter_blurhash]
- package_config 2.0.2 [path]
- package_info_plus 1.4.2 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.5 [package_info_plus_platform_interface ffi flutter win32]
- path_provider_android 2.0.12 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.0 [async stack_trace]
- positioned_tap_detector_2 1.0.4 [flutter]
- process 4.2.4 [file path platform]
- proj4dart 2.0.0 [mgrs_dart wkt_parser meta]
- pub_semver 2.1.1 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- qr 2.1.0 [meta]
- quiver 3.0.1+1 [matcher]
- sentry 6.5.0-beta.1 [http meta stack_trace uuid]
- share_plus_linux 3.0.0 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 3.0.0 [share_plus_platform_interface flutter]
- share_plus_platform_interface 3.0.2 [flutter meta mime plugin_platform_interface]
- share_plus_web 3.0.0 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 3.0.0 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences_android 2.0.11 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.0 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.3 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.3.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.1.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- smart_auth 1.0.5 [flutter flutter_web_plugins]
- source_gen 1.2.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.2 [flutter sqflite_common path]
- sqflite_common 2.2.1 [synchronized path meta]
- sqlite3 1.5.1 [collection ffi meta]
- sqlparser 0.21.0 [meta collection source_span charcode]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- sync_http 0.3.0
- synchronized 3.0.0+2
- system_info2 2.0.3 [file_utils path]
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.9 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 1.0.0 [json_annotation]
- transparent_image 2.0.0
- tuple 2.0.0 [quiver]
- typed_data 1.3.0 [collection]
- unicode 0.3.1 [lists]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_android 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_windows 3.0.0 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.1
- video_player_android 2.3.2 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.1 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.1 [flutter plugin_platform_interface]
- video_player_web 2.0.7 [flutter flutter_web_plugins video_player_platform_interface]
- vm_service 7.5.0
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- webdriver 3.0.0 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.0.0 [logging]
- webview_flutter_android 2.8.5 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.8.1 [flutter plugin_platform_interface]
- webview_flutter_wkwebview 2.7.2 [flutter path webview_flutter_platform_interface]
- win32 2.5.1 [ffi]
- wkt_parser 2.0.0
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
Labeling it for further insights from the team as there doesn't seem to be any reproducible use case / code sample.

/cc @russellwheatley

**Comment by russellwheatley** [comment]
Hey @stx, thanks for the update! I'm curious to know if you're still seeing [this error](https://github.com/firebase/flutterfire/issues/8444) as well?

**Comment by stx** [comment]
@russellwheatley Looks like this issue and #8444 both persist in 3.3.17.

New trace:

```
java.lang.NullPointerException: Attempt to get length of null array
    at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:248)
    at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
    at java.util.ArrayList.add(ArrayList.java:467)
    at com.google.firebase.auth.internal.d1.M1(com.google.firebase:firebase-auth@@21.0.3:9)
    at com.google.firebase.auth.FirebaseAuth.N(com.google.firebase:firebase-auth@@21.0.3:9)
    at com.google.firebase.auth.r1.b(com.google.firebase:firebase-auth@@21.0.3:1)
    at g.c.a.e.g.h.zi.c(com.google.firebase:firebase-auth@@21.0.3:3)
    at g.c.a.e.g.h.gl.j(com.google.firebase:firebase-auth@@21.0.3:1)
    at g.c.a.e.g.h.dl.j(com.google.firebase:firebase-auth@@21.0.3:2)
    at g.c.a.e.g.h.fk.m(com.google.firebase:firebase-auth@@21.0.3:1)
    at g.c.a.e.g.h.ph.a(com.google.firebase:firebase-auth@@21.0.3:2)
    at g.c.a.e.g.h.ol.a(com.google.firebase:firebase-auth@@21.0.3:25)
    at g.c.a.e.g.h.uk.d(com.google.firebase:firebase-auth@@21.0.3:4)
    at g.c.a.e.g.h.ri.C(com.google.firebase:firebase-auth@@21.0.3:4)
    at g.c.a.e.g.h.gk.n(com.google.firebase:firebase-auth@@21.0.3:5)
    at g.c.a.e.g.h.zi.b(com.google.firebase:firebase-auth@@21.0.3:1)
    at g.c.a.e.g.h.hl.run(com.google.firebase:firebase-auth@@21.0.3:1)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)
```

**Comment by russellwheatley** [comment]
Closing this in favour of tracking on this issue: https://github.com/firebase/flutterfire/issues/8444
