### ISSUE TITLE
Debug session terminates each time i receive a  broadcast message

### ISSUE THREAD

**Issue by asif2304** [firebase/flutterfire#8534]
E/Parcel  (16721): Reading a NULL string not supported here.
V/ActivityThread(16721): scheduleReceiver info = ActivityInfo{4854d29 io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver} intent = Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11080010 pkg=com.gharelumart.kwickly_partner_app cmp=com.gharelumart.kwickly_partner_app/io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver (has extras) } sync = true hasCode = 227577283
**D/FLTFireMsgReceiver(16721): broadcast received for message**
V/ActivityThread(16721): scheduleReceiver info = ActivityInfo{601d047 com.google.firebase.iid.FirebaseInstanceIdReceiver} intent = Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11080010 pkg=com.gharelumart.kwickly_partner_app cmp=com.gharelumart.kwickly_partner_app/com.google.firebase.iid.FirebaseInstanceIdReceiver (has extras) } sync = true hasCode = 243963582
I/FLTFireMsgService(16721): Service has not yet started, messages will be queued.
W/FlutterJNI(16721): FlutterJNI.loadLibrary called more than once
I/ResourceExtractor(16721): Found extracted resources res_timestamp-1-1651141696053
W/FlutterJNI(16721): FlutterJNI.prefetchDefaultFontManager called more than once
W/FlutterJNI(16721): FlutterJNI.init called more than once
I/FLTFireBGExecutor(16721): Creating background FlutterEngine instance.
W/kly_partner_ap(16721): Accessing hidden method Landroid/os/WorkSource;->add(I)Z (unsupported,test-api, reflection, allowed)
W/kly_partner_ap(16721): Accessing hidden method Landroid/os/WorkSource;->add(ILjava/lang/String;)Z (unsupported,test-api, reflection, allowed)
W/kly_partner_ap(16721): Accessing hidden method Landroid/os/WorkSource;->get(I)I (unsupported, reflection, allowed)
W/kly_partner_ap(16721): Accessing hidden method Landroid/os/WorkSource;->getName(I)Ljava/lang/String; (unsupported, reflection, allowed)
D/FlutterGeolocator(16721): Geolocator foreground service connected
D/FlutterGeolocator(16721): Initializing Geolocator services
E/Parcel  (16721): Reading a NULL string not supported here.
D/AndroidRuntime(16721): Shutting down VM
E/AndroidRuntime(16721): FATAL EXCEPTION: main
E/AndroidRuntime(16721): Process: com.gharelumart.kwickly_partner_app, PID: 16721
E/AndroidRuntime(16721): java.lang.RuntimeException: Unable to create service com.example.kwickly_partner_app.java.MyFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "com.example.kwickly_partner_app.java.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/~~sVBxfxGKAboUu6Fku82dyQ==/com.gharelumart.kwickly_partner_app-byNGWL0XmeWcBKoMXUaHhQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~sVBxfxGKAboUu6Fku82dyQ==/com.gharelumart.kwickly_partner_app-byNGWL0XmeWcBKoMXUaHhQ==/lib/arm64, /data/app/~~sVBxfxGKAboUu6Fku82dyQ==/com.gharelumart.kwickly_partner_app-byNGWL0XmeWcBKoMXUaHhQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(16721): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4669)
E/AndroidRuntime(16721): 	at android.app.ActivityThread.access$100(ActivityThread.java:253)
E/AndroidRuntime(16721): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2206)
E/AndroidRuntime(16721): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16721): 	at android.os.Looper.loopOnce(Looper.java:233)
E/AndroidRuntime(16721): 	at android.os.Looper.loop(Looper.java:344)
E/AndroidRuntime(16721): 	at android.app.ActivityThread.main(ActivityThread.java:8191)
E/AndroidRuntime(16721): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16721): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(16721): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/AndroidRuntime(16721): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.kwickly_partner_app.java.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/~~sVBxfxGKAboUu6Fku82dyQ==/com.gharelumart.kwickly_partner_app-byNGWL0XmeWcBKoMXUaHhQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~sVBxfxGKAboUu6Fku82dyQ==/com.gharelumart.kwickly_partner_app-byNGWL0XmeWcBKoMXUaHhQ==/lib/arm64, /data/app/~~sVBxfxGKAboUu6Fku82dyQ==/com.gharelumart.kwickly_partner_app-byNGWL0XmeWcBKoMXUaHhQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(16721): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
E/AndroidRuntime(16721): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(16721): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(16721): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime(16721): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
E/AndroidRuntime(16721): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4638)
E/AndroidRuntime(16721): 	... 9 more
I/Process (16721): Sending signal. PID: 16721 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by asif2304** [comment]
V/ActivityThread(19976): scheduleReceiver info = ActivityInfo{17c92e5 io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver} intent = Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11080010 pkg=com.gharelumart.kwickly_partner_app cmp=com.gharelumart.kwickly_partner_app/io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver (has extras) } sync = true hasCode = 75746410
**D/FLTFireMsgReceiver(19976): broadcast received for message**
V/ActivityThread(19976): scheduleReceiver info = ActivityInfo{8542fe0 com.google.firebase.iid.FirebaseInstanceIdReceiver} intent = Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11080010 pkg=com.gharelumart.kwickly_partner_app cmp=com.gharelumart.kwickly_partner_app/com.google.firebase.iid.FirebaseInstanceIdReceiver (has extras) } sync = true hasCode = 201999670
E/Parcel  (19976): Reading a NULL string not supported here.
W/kly_partner_ap(19976): Accessing hidden method Landroid/os/WorkSource;->add(I)Z (unsupported,test-api, reflection, allowed)
W/kly_partner_ap(19976): Accessing hidden method Landroid/os/WorkSource;->add(ILjava/lang/String;)Z (unsupported,test-api, reflection, allowed)
W/kly_partner_ap(19976): Accessing hidden method Landroid/os/WorkSource;->get(I)I (unsupported, reflection, allowed)
W/kly_partner_ap(19976): Accessing hidden method Landroid/os/WorkSource;->getName(I)Ljava/lang/String; (unsupported, reflection, allowed)
**D/AndroidRuntime(19976): Shutting down VM
E/AndroidRuntime(19976): FATAL EXCEPTION: main**
E/AndroidRuntime(19976): Process: com.gharelumart.kwickly_partner_app, PID: 19976
E/AndroidRuntime(19976): java.lang.RuntimeException: Unable to create service com.example.kwickly_partner_app.java.MyFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "com.example.kwickly_partner_app.java.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/~~0-IrCz5ysQolCZvQEXhv-Q==/com.gharelumart.kwickly_partner_app-fxKmLEC2B0X81JMCa72aAA==/base.apk"],nativeLibraryDirectories=[/data/app/~~0-IrCz5ysQolCZvQEXhv-Q==/com.gharelumart.kwickly_partner_app-fxKmLEC2B0X81JMCa72aAA==/lib/arm64, /data/app/~~0-IrCz5ysQolCZvQEXhv-Q==/com.gharelumart.kwickly_partner_app-fxKmLEC2B0X81JMCa72aAA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(19976): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4669)
E/AndroidRuntime(19976): 	at android.app.ActivityThread.access$100(ActivityThread.java:253)
E/AndroidRuntime(19976): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2206)
E/AndroidRuntime(19976): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(19976): 	at android.os.Looper.loopOnce(Looper.java:233)
E/AndroidRuntime(19976): 	at android.os.Looper.loop(Looper.java:344)
E/AndroidRuntime(19976): 	at android.app.ActivityThread.main(ActivityThread.java:8191)
E/AndroidRuntime(19976): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19976): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(19976): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/AndroidRuntime(19976): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.kwickly_partner_app.java.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/~~0-IrCz5ysQolCZvQEXhv-Q==/com.gharelumart.kwickly_partner_app-fxKmLEC2B0X81JMCa72aAA==/base.apk"],nativeLibraryDirectories=[/data/app/~~0-IrCz5ysQolCZvQEXhv-Q==/com.gharelumart.kwickly_partner_app-fxKmLEC2B0X81JMCa72aAA==/lib/arm64, /data/app/~~0-IrCz5ysQolCZvQEXhv-Q==/com.gharelumart.kwickly_partner_app-fxKmLEC2B0X81JMCa72aAA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(19976): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
E/AndroidRuntime(19976): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(19976): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(19976): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime(19976): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
E/AndroidRuntime(19976): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4638)
E/AndroidRuntime(19976): 	... 9 more
I/Process (19976): Sending signal. PID: 19976 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by asif2304** [comment]
problem solved. AndroidManifest.xml was populated with <service></> snippets from documentation. Removed it and the app works fine now.
