### ISSUE TITLE
🐛 [cloud_firestore] Firebase Emulator Suite working for Auth but not Firestore

### ISSUE THREAD

**Issue by gerryau** [firebase/flutterfire#8578]
## Bug report

**Describe the bug**
When both useFirestoreEmulator(...) and useAuthEmulator(...) are called the package is unable to query the firestore. The app works fine on the production Firebase but not the emulator.

### Steps to reproduce

1. Run `firebase emulators:start`
│ Emulator       │ Host:Port      │ View in Emulator UI             │
├────────────────┼────────────────┼─────────────────────────────────┤
│ Authentication │ localhost:9099 │ http://localhost:4000/auth      │
├────────────────┼────────────────┼─────────────────────────────────┤
│ Functions      │ localhost:5001 │ http://localhost:4000/functions │
├────────────────┼────────────────┼─────────────────────────────────┤
│ Firestore      │ localhost:8081 │ http://localhost:4000/firestore │
├────────────────┼────────────────┼─────────────────────────────────┤
│ Database       │ localhost:9000 │ http://localhost:4000/database  │

2. Query firestore db
4. See error or incorrect behavior

### Expected behavior

Expect to be able to query firestore without errors but get an error instead.

### Sample project

```
const bool USE_FIRESTORE_EMULATOR = true;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  configureInjection(Environment.prod);
  if (USE_FIRESTORE_EMULATOR) {
    await Firebase.initializeApp(
      options: const FirebaseOptions(
          apiKey: "-------------------",
          authDomain: "--------------",
          databaseURL: "------------------",
          projectId: "----------------",
          storageBucket: "---------------------",
          messagingSenderId: "--------------",
          appId: "----------------------",
          measurementId: "-----------------"),
    );

    FirebaseFirestore.instance.settings = const Settings(
        host: 'localhost:8081', sslEnabled: false, persistenceEnabled: false);
    FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8081);
    FirebaseAuth.instance.useAuthEmulator('localhost', 9099);
  } else {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    ); 
  }
  runApp(AppHome());
}
```
---

### Error

```
[2022-05-04T06:52:53.571Z]  @firebase/firestore:
[2022-05-04T06:52:53.572Z]  @firebase/firestore:
WARNING: You are using the Auth Emulator, which is intended for local testing only.  Do not use with production credentials.
[2022-05-04T06:53:04.215Z]  @firebase/firestore:
Error: Invalid argument(s) (onError): The error handler of Future.then must return a value of the returned future's type
    at Object.throw_ [as throw] (http://localhost:34489/dart_sdk.js:5067:11)
    at _FutureListener.then.handleError (http://localhost:34489/dart_sdk.js:35384:25)
    at handleError (http://localhost:34489/dart_sdk.js:35947:51)
    at Function._propagateToListeners (http://localhost:34489/dart_sdk.js:35973:17)
    at _Future.new.[_completeError] (http://localhost:34489/dart_sdk.js:35823:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:34489/dart_sdk.js:35859:31)
    at Object._microtaskLoop (http://localhost:34489/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:34489/dart_sdk.js:40714:13)
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on Linux Mint 20.3 5.13.0-40-generic, locale en_AU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.2
Flutter SDK 2.10.5
sample_flutter_application 1.0.0+1

dependencies:
- another_flushbar 1.10.28 [flutter]
- auto_route 3.2.4 [flutter path collection meta universal_html]
- bloc 8.0.3 [meta]
- cloud_firestore 3.1.13 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.4
- dartz 0.10.1
- equatable 2.0.3 [collection meta]
- firebase_auth 3.3.16 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_oauth 1.2.0 [flutter firebase_auth firebase_core firebase_auth_oauth_platform_interface firebase_auth_oauth_web]
- firebase_core 1.15.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_bloc 8.0.1 [flutter bloc provider]
- freezed_annotation 2.0.1 [collection json_annotation meta]
- get_it 7.2.0 [async collection]
- injectable 1.5.3 [get_it]
- modal_bottom_sheet 2.0.1 [flutter]
- rive 0.8.4 [collection flutter graphs http meta]
- social_login_buttons 1.0.6+2 [flutter]
- uuid 3.0.6 [crypto]

dev dependencies:
- auto_route_generator 3.2.3 [build source_gen analyzer path build_runner code_builder dart_style auto_route]
- bloc_test 9.0.3 [bloc diff_match_patch meta mocktail test]
- build_runner 2.1.10 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- change_app_package_name 1.0.0
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]
- freezed 2.0.2 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- injectable_generator 1.5.3 [build source_gen path glob analyzer code_builder dart_style injectable collection]
- json_serializable 6.2.0 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- lint 1.8.2
- mocktail 0.3.0 [collection matcher test]

dependency overrides:
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]

transitive dependencies:
- _fe_analyzer_shared 38.0.0 [meta]
- analyzer 3.4.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.3.0 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.8 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.2.3 [built_collection collection fixnum meta]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- clock 1.1.0
- cloud_firestore_platform_interface 5.5.4 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.13 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.1 [typed_data]
- coverage 1.2.0 [args logging package_config path source_maps stack_trace vm_service]
- crypto 3.0.2 [typed_data]
- csslib 0.17.1 [source_span]
- dart_style 2.2.3 [analyzer args path pub_semver source_span]
- diff_match_patch 0.4.1
- fake_async 1.2.0 [clock collection]
- file 6.1.2 [meta path]
- firebase 9.0.2 [http http_parser js]
- firebase_auth_oauth_platform_interface 1.0.2 [flutter firebase_auth firebase_core]
- firebase_auth_oauth_web 1.1.0 [flutter flutter_web_plugins firebase firebase_auth firebase_core firebase_auth_oauth_platform_interface js]
- firebase_auth_platform_interface 6.2.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.13 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.5 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- frontend_server_client 2.1.2 [async path]
- glob 2.0.2 [async collection file path string_scanner]
- graphs 2.1.0 [collection]
- html 0.15.0 [csslib source_span]
- http 0.13.4 [async http_parser meta path]
- http_multi_server 3.2.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.5.0 [meta]
- lints 1.0.1
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- mime 1.0.2
- nested 1.0.0 [flutter]
- node_preamble 2.0.1
- package_config 2.0.2 [path]
- path 1.8.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.0 [async stack_trace]
- provider 6.0.2 [collection flutter nested]
- pub_semver 2.1.1 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- shelf 1.3.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.1.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.2.2 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.2 [analyzer collection source_gen]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test 1.21.1 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_core 0.4.13 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- universal_html 2.0.8 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_io 2.0.4 [collection crypto meta typed_data]
- vector_math 2.1.1
- vm_service 8.2.2
- watcher 1.0.1 [async path]
- web_socket_channel 2.2.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.0.0 [logging]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
@gerryau 
The official plugin example doesn't use both emulators at once.

<img width="836" alt="Screenshot 2022-05-04 at 3 56 44 PM" src="https://user-images.githubusercontent.com/67046386/166664729-2a41e5d2-0732-452d-b081-190bb13c3417.png">

Since you are trying to use both, it seems to be giving you the warning in the log: `WARNING: You are using the Auth Emulator, which is intended for local testing only.  Do not use with production credentials.`


Does the error `Error: Invalid argument(s) (onError): The error handler of Future.then must return a value of the returned future's type` occur if you only use `useFirestoreEmulator` ?

**Comment by gerryau** [comment]
Yes, I see the same error if I only use the useFirestoreEmulator method.

The code seems outdated because `DefaultFirebaseConfig.platformOptions` is no longer an option.
