### ISSUE TITLE
FCM delivery reports metrics fail with exception

### ISSUE THREAD

**Issue by Turburlar** [firebase/flutterfire#8622]
I have enabled delivery report metric to be query for my Flutter Android app by adding the following line to my AndroidManifest.xml.

`<meta-data android:name="delivery_metrics_exported_to_big_query_enabled" android:value="true" />`

In addition, I added the firebase_analytics package.

Now when a notification arrives, I get the following error message in the logs...

```

W/FirebaseMessaging(13202): Failed to send big query analytics payload.
W/FirebaseMessaging(13202): java.lang.IllegalArgumentException: Encoding{name="src/main/proto"} is not supported byt this factory. Supported encodings are: [Encoding{name="json"}, Encoding{name="proto"}].
W/FirebaseMessaging(13202): 	at com.google.android.datatransport.runtime.TransportFactoryImpl.getTransport(TransportFactoryImpl.java:51)
W/FirebaseMessaging(13202): 	at com.google.firebase.messaging.MessagingAnalytics.logToFirelog(MessagingAnalytics.java:341)
W/FirebaseMessaging(13202): 	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(MessagingAnalytics.java:81)
W/FirebaseMessaging(13202): 	at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(FirebaseMessagingService.java:183)
W/FirebaseMessaging(13202): 	at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:172)
W/FirebaseMessaging(13202): 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:161)
W/FirebaseMessaging(13202): 	at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(EnhancedIntentService.java:78)
W/FirebaseMessaging(13202): 	at com.google.firebase.messaging.-$$Lambda$EnhancedIntentService$NSk2h75eWhBOI4TsAFgvvtv1g9o.run(Unknown Source:6)
W/FirebaseMessaging(13202): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/FirebaseMessaging(13202): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/FirebaseMessaging(13202): 	at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.0.0:2)
W/FirebaseMessaging(13202): 	at java.lang.Thread.run(Thread.java:764)

```

**Comment by darshankawar** [comment]
@Turburlar 
This seems to be coming from native Android firebase sdk and not from flutterfire side. A similar [issue](https://github.com/firebase/firebase-android-sdk/issues/3628) was raised and it seemed to have been fixed per [this](https://github.com/firebase/firebase-android-sdk/issues/3628#issuecomment-1095356735) comment.

Closing from here, as this doesn't seem to be flutterfire plugin issue.

**Comment by Turburlar** [comment]
The bug symptomizes using FlutterFire, and requires action on the FlutterFire devs part to fix (bump the Android firebase sdk version to pull in the fix). Should this not be left open till that action is taken?

**Comment by darshankawar** [comment]
Thanks for the feedback. Reopening and labeling for insights from team on the potential fix at client side.

/cc @russellwheatley
