### ISSUE TITLE
[📚] Add nested custom objects to Firestore

### ISSUE THREAD

**Issue by georges-ph** [firebase/flutterfire#8679]
I'm following the [docs](https://firebase.google.com/docs/firestore/manage-data/add-data#custom_objects) to add nested custom objects to Firestore. But it doesn't show how to make it. I was able to make it work with a single one.

This is the first custom object:
```dart
import 'package:cloud_firestore/cloud_firestore.dart';

class User {
  String? id;
  String? name;
  SomeObject? object;

  User({
    this.id,
    this.name,
    this.object,
  });

  User.fromFirestore(
      DocumentSnapshot<Map<String, dynamic>> snapshot, SnapshotOptions? options)
      : id = snapshot.data()?['id'],
        name = snapshot.data()?['name'],
        object=snapshot.data()?['object'];

  Map<String, dynamic> toFirestore() {
    return {
      'id': id,
      'name': name,
      'object':object,
    };
  }

}
```

`SomeObject` is a class that has some strings and I added the same `fromFirestore()` and `toFirestore()` methods.

To add the document, I did the same as the docs:
```dart
User user = User(
  object: SomeObject(
    field1:"field1",
    field1:"field1",
  ),
);

await FirebaseFirestore.instance
    .collection("col")
    .doc("h")
    .withConverter(
      fromFirestore: User.fromFirestore,
      toFirestore: (User user, options) =>
          user.toFirestore(),
    )
    .set(user);
```

But the document is not added. I'm getting this error instead:
```
E/flutter (20492): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument: Instance of 'SomeObject'
E/flutter (20492): #0      StandardMessageCodec.writeValue
E/flutter (20492): #1      FirestoreMessageCodec.writeValue
E/flutter (20492): #2      StandardMessageCodec.writeValue.<anonymous closure>
E/flutter (20492): #3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
E/flutter (20492): #4      StandardMessageCodec.writeValue
E/flutter (20492): #5      FirestoreMessageCodec.writeValue
E/flutter (20492): #6      StandardMessageCodec.writeValue.<anonymous closure>
E/flutter (20492): #7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
E/flutter (20492): #8      StandardMessageCodec.writeValue
E/flutter (20492): #9      FirestoreMessageCodec.writeValue
E/flutter (20492): #10     StandardMethodCodec.encodeMethodCall
E/flutter (20492): #11     MethodChannel._invokeMethod
E/flutter (20492): #12     MethodChannel.invokeMethod
E/flutter (20492): #13     MethodChannelDocumentReference.set
E/flutter (20492): #14     _JsonDocumentReference.set
E/flutter (20492): #15     _WithConverterDocumentReference.set
E/flutter (20492): #16     _PriceState.build.<anonymous closure>
E/flutter (20492): #17     _PriceState.build.<anonymous closure>
E/flutter (20492): #18     _InkResponseState._handleTap
E/flutter (20492): #19     GestureRecognizer.invokeCallback
E/flutter (20492): #20     TapGestureRecognizer.handleTapUp
E/flutter (20492): #21     BaseTapGestureRecognizer._checkUp
E/flutter (20492): #22     BaseTapGestureRecognizer.handlePrimaryPointer
E/flutter (20492): #23     PrimaryPointerGestureRecognizer.handleEvent
E/flutter (20492): #24     PointerRouter._dispatch
E/flutter (20492): #25     PointerRouter._dispatchEventToRoutes.<anonymous closure>
E/flutter (20492): #26     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
E/flutter (20492): #27     PointerRouter._dispatchEventToRoutes
E/flutter (20492): #28     PointerRouter.route
E/flutter (20492): #29     GestureBinding.handleEvent
E/flutter (20492): #30     GestureBinding.dispatchEvent
E/flutter (20492): #31     RendererBinding.dispatchEvent
E/flutter (20492): #32     GestureBinding._handlePointerEventImmediately
E/flutter (20492): #33     GestureBinding.handlePointerEvent
E/flutter (20492): #34     GestureBinding._flushPointerEventQueue
E/flutter (20492): #35     GestureBinding._handlePointerDataPacket
E/flutter (20492): #36     _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (20492): #37     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (20492): #38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (20492): #39     _invoke1 (dart:ui/hooks.dart:170:10)
E/flutter (20492): #40     PlatformDispatcher._dispatch

```

**Comment by thisis184** [comment]
Using `withConverter` with nested custom objects, you need layer-by-layer (class-by-class) convert data type, either `fromJson` or `toJson`, like the example below: 

```
class User {
  String? name;
  SomeObject? object;
  List<Dog>? dogs;

  User({
    this.name,
    this.object,
    this.dogs,
  });

User.fromJson(Map<String, dynamic> json)
      : this(
          name: json['name']
          object: SomeObject.fromJson(json['object']),
          dogs: List<Dog>.from(
            json['dogs'].map((d) => Dog.fromJson(d))),
        );

Map<String, dynamic> toJson() {
    return {
      'name': name,
      'object': SomeObject().toJson,
      'dogs': List<dynamic>.from(dogs.map((x) => x.toJson())),
    };
  }

}
```

I hope this will help,
maybe you can give me an emoji to let me know,
cheers!

**Comment by russellwheatley** [comment]
We actually have a comprehensive example in the Firestore example app. [See here](https://github.com/firebase/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/example/lib/main.dart#L393-L435)
