### ISSUE TITLE
Bad state: field does not exist within the DocumentSnapshotPlatform

### ISSUE THREAD

**Issue by MuthuSubramaniam** [firebase/flutterfire#8706]
I Used to get data feeds from firestore, and loading in Dismissible in Flutter. Afer swiped few slides am getting the error shown below. Pls assist

```
Bad state: field does not exist within the DocumentSnapshotPlatform

The relevant error-causing widget was: 
  StreamBuilder<QuerySnapshot<Object?>> StreamBuilder:file:///Users/muthu/StudioProjects/toglr-app/lib/ui/home_page.dart:57:14
When the exception was thrown, this was the stack: 
#0      DocumentSnapshotPlatform.get._findKeyValueInMap (package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_document_snapshot.dart:87:7)
#1      DocumentSnapshotPlatform.get._findComponent (package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_document_snapshot.dart:105:23)
#2      DocumentSnapshotPlatform.get (package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_document_snapshot.dart:121:12)
#3      _JsonDocumentSnapshot.get (package:cloud_firestore/src/document_snapshot.dart:92:48)
#4      _JsonDocumentSnapshot.[] (package:cloud_firestore/src/document_snapshot.dart:96:40)
#5      _HomePageState.newsCard (package:toglr_news/ui/home_page.dart:121:32)
#6      _HomePageState._buildBody.<anonymous closure> (package:toglr_news/ui/home_page.dart:79:27)
#7      StreamBuilder.build (package:flutter/src/widgets/async.dart:442:81)
#8      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:124:48)
#9      StatefulElement.build (package:flutter/src/widgets/framework.dart:4870:27)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#13     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#18     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#20     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#24     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#31     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#33     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#39     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#40     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#43     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#44     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#45     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#49     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#52     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#54     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#58     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#61     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#63     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#67     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#71     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#75     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#78     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#79     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#83     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#85     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5787:32)
#86     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#89     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#91     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#95     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#98     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#100    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#102    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#106    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#108    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#111    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#113    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#116    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#117    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#118    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#121    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#122    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#126    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#129    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#131    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#134    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#135    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#138    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#139    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#140    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#144    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#147    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#148    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#149    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#150    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#151    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#152    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#153    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#154    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#158    _invoke (dart:ui/hooks.dart:151:10)
#159    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#160    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
```

**Comment by darshankawar** [comment]
@MuthuSubramaniam 
Can you provide `flutter doctor -v`, plugin version along with a complete minimal reproducible code sample that shows this error ?

Also take a look at [this](https://github.com/firebase/flutterfire/issues/3826#issuecomment-715591362) solution and see if it works for you.

**Comment by darshankawar** [comment]
Closing this as resolved per above comment.

**Comment by emer-son** [comment]
> i found my issue and one of the key is missing from firestore

hi, how do you resolved this? i'm facing the same issue. Thanks
