### ISSUE TITLE
🐛 [cloud_functions] The package fails always to call functions only on some devices (firebase_functions/unavailable)

### ISSUE THREAD

**Issue by Desno365** [firebase/flutterfire#8801]
## Bug report

**Describe the bug**
We had many users reporting that they were not able to use our application.
After further investigation using Crashlytics we found that some devices always fail to call all the Cloud Functions:

```
Non-fatal Exception:
 [firebase_functions/unavailable] UNAVAILABLE

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177)
<asynchronous suspension>
#2      MethodChannelHttpsCallable.call (package:cloud_functions_platform_interface/src/method_channel/method_channel_https_callable.dart:23)
<asynchronous suspension>
#3      HttpsCallable.call (package:cloud_functions/src/https_callable.dart:49)
<asynchronous suspension>
#4      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:870)
<asynchronous suspension>
#5      FunctionsManager._callFunction (package:waveful/controller/cloud/functions/functions_manager.dart:678)
<asynchronous suspension>
```

### Steps to reproduce

We were not able to reproduce the issue on one of our devices.
On Crashlytics we see that this error have impacted the following devices:
- Galaxy S20 FE, Android 12
- Galaxy A21s, Android 11
- realme GT Master Edition, Android 12
- realme C21-Y, Android 11
- and others

### Expected behavior

The expected behavior is that the call to the cloud function does not always fail.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Firebase dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.1
Flutter SDK 3.0.1
waveful 1.7.0+68

- cloud_firestore 3.1.17 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 3.2.16 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- firebase_analytics 9.1.9 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check 0.0.6+13 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.3.19 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.17.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.8.1 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 4.2.5 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 11.4.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 2.0.8 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_storage 10.2.17 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
```

</details>

---

**Comment by darshankawar** [comment]
> [firebase_functions/unavailable] UNAVAILABLE

This probably indicates an outage from firebase side. Going to close since it seems it's not this library which is causing issues.
