### ISSUE TITLE
🐛 [cloud_firestore] App crashes in release mode

### ISSUE THREAD

**Issue by rivella50** [firebase/flutterfire#8820]
## Bug report

**Describe the bug**
Android app crashes on startup with an ExceptionInInitializerError. This only happens in release mode, debug mode works just fine.
Two days ago also the release mode worked fine when i built the last app distribution release. At that time i had slightly older Firebase packages versions (e.g. 1.16.0 for firebase_core), but when i go back to these versions the app still crashes.

In release mode i can access and modify Firebase Authentication area, e.g. create an account.
But as soon as i try to access Firestore database it seems that there is something going wrong.

Even when i change my signingConfig to signignConfigs.debug in buildTypes->release (app/build.gradle) the error persists.

Please tell me if you need additional information. Thank you.

## Additional context

E/AndroidRuntime(10256): FATAL EXCEPTION: main
E/AndroidRuntime(10256): Process: my.package.staging, PID: 10256
E/AndroidRuntime(10256): java.lang.RuntimeException: Internal error in Cloud Firestore (24.1.2).
E/AndroidRuntime(10256): 	at com.google.firebase.firestore.f0.h.run(SourceFile:5)
E/AndroidRuntime(10256): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(10256): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10256): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(10256): 	at android.app.ActivityThread.main(ActivityThread.java:7698)
E/AndroidRuntime(10256): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10256): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(10256): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
E/AndroidRuntime(10256): Caused by: d.c.a.b.j.j: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
E/AndroidRuntime(10256): 	at d.c.a.b.j.N.n(SourceFile:8)
E/AndroidRuntime(10256): 	at com.google.firebase.firestore.e0.J.c(SourceFile:1)
E/AndroidRuntime(10256): 	at com.google.firebase.firestore.e0.l.a(Unknown Source:6)
E/AndroidRuntime(10256): 	at d.c.a.b.j.A.run(SourceFile:1)
E/AndroidRuntime(10256): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/AndroidRuntime(10256): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(10256): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/AndroidRuntime(10256): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(10256): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(10256): 	at com.google.firebase.firestore.f0.s$c$b.run(SourceFile:3)
E/AndroidRuntime(10256): 	at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime(10256): Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
E/AndroidRuntime(10256): 	at d.c.a.b.j.O.run(SourceFile:3)
E/AndroidRuntime(10256): 	at com.google.firebase.firestore.f0.C.a(SourceFile:1)
E/AndroidRuntime(10256): 	at com.google.firebase.firestore.f0.m.run(Unknown Source:4)
E/AndroidRuntime(10256): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(10256): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(10256): 	... 1 more
E/AndroidRuntime(10256): Caused by: java.lang.ExceptionInInitializerError
E/AndroidRuntime(10256): 	at f.b.n0.d.forTarget(SourceFile:1)
E/AndroidRuntime(10256): 	at f.b.n0.e.a(SourceFile:1)
E/AndroidRuntime(10256): 	at f.b.N.b(SourceFile:2)
E/AndroidRuntime(10256): 	at com.google.firebase.firestore.e0.M.e(SourceFile:4)
E/AndroidRuntime(10256): 	at com.google.firebase.firestore.e0.q.call(Unknown Source:2)
E/AndroidRuntime(10256): 	at d.c.a.b.j.O.run(SourceFile:1)
E/AndroidRuntime(10256): 	... 5 more
E/AndroidRuntime(10256): Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: f.b.k0.values []
E/AndroidRuntime(10256): 	at java.lang.Enum.enumValues(Enum.java:270)
E/AndroidRuntime(10256): 	at java.lang.Enum.access$000(Enum.java:61)
E/AndroidRuntime(10256): 	at java.lang.Enum$1.create(Enum.java:277)
E/AndroidRuntime(10256): 	at java.lang.Enum$1.create(Enum.java:275)
E/AndroidRuntime(10256): 	at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
E/AndroidRuntime(10256): 	at java.lang.Enum.getSharedConstants(Enum.java:289)
E/AndroidRuntime(10256): 	at java.lang.Class.getEnumConstantsShared(Class.java:2428)
E/AndroidRuntime(10256): 	at java.util.EnumSet.getUniverse(EnumSet.java:407)
E/AndroidRuntime(10256): 	at java.util.EnumSet.noneOf(EnumSet.java:109)
E/AndroidRuntime(10256): 	at java.util.EnumSet.of(EnumSet.java:235)
E/AndroidRuntime(10256): 	at f.b.n0.d.<clinit>(SourceFile:10)
E/AndroidRuntime(10256): 	... 11 more
E/AndroidRuntime(10256): Caused by: java.lang.NoSuchMethodException: f.b.k0.values []
E/AndroidRuntime(10256): 	at java.lang.Class.getMethod(Class.java:2072)
E/AndroidRuntime(10256): 	at java.lang.Class.getDeclaredMethod(Class.java:2050)
E/AndroidRuntime(10256): 	at java.lang.Enum.enumValues(Enum.java:267)
E/AndroidRuntime(10256): 	... 21 more

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (6 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.1
Flutter SDK 3.0.1
myVersion 1.0.7+7

dependencies:
- badges 2.0.2 [flutter]
- cached_network_image 3.2.1 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- camera 0.9.7+1 [camera_platform_interface camera_web flutter flutter_plugin_android_lifecycle quiver]
- cloud_firestore 3.1.17 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 3.2.16 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- email_validator 2.0.1
- file_picker 4.6.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_auth 3.3.19 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.17.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 11.4.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 10.2.17 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_cache_manager_firebase 2.0.1 [flutter flutter_cache_manager firebase_storage path_provider path]
- flutter_image_compress 1.1.0 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_native_splash 2.2.2 [args flutter flutter_web_plugins image js lint meta path universal_io xml yaml]
- flutter_phone_direct_caller 2.1.1 [flutter]
- flutter_riverpod 2.0.0-dev.9 [collection flutter meta riverpod state_notifier]
- flutter_sfsymbols 2.0.0 [flutter]
- flutter_spinkit 5.1.0 [flutter]
- get_it 7.2.0 [async collection]
- google_maps_flutter 2.1.6 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- grouped_list 5.1.1 [flutter]
- image 3.2.0 [archive meta xml]
- intl 0.17.0 [clock path]
- jiffy 5.0.0 [intl]
- package_info_plus 1.4.2 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- photo_view 0.14.0 [flutter]
- signature 5.0.1 [flutter image]
- sumup 0.4.0 [flutter]
- uni_links 0.5.1 [flutter uni_links_platform_interface uni_links_web]
- url_launcher 6.1.2 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.6 [crypto]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- mocktail 0.3.0 [collection matcher test]
- very_good_analysis 2.4.0

dependency overrides:
- advance_pdf_viewer 2.0.1 [flutter flutter_cache_manager numberpicker path_provider]

transitive dependencies:
- _fe_analyzer_shared 40.0.0 [meta]
- analyzer 4.1.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.3.0 [crypto path]
- args 2.3.1
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- camera_platform_interface 2.2.0 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.2.1+6 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 5.5.7 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.16 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.1.7 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.2.15 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- convert 3.0.2 [typed_data]
- coverage 1.3.2 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- fake_async 1.3.0 [clock collection]
- ffi 1.2.1
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 6.2.7 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.16 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.4.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.5.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.4.1 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.7 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.2.16 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.7.0 [flutter]
- flutter_plugin_android_lifecycle 2.0.6 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 2.1.3 [async path]
- glob 2.0.2 [async collection file path string_scanner]
- google_maps_flutter_platform_interface 2.1.7 [collection flutter plugin_platform_interface stream_transform]
- http 0.13.4 [async http_parser meta path]
- http_multi_server 3.2.0 [async]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- infinite_listview 1.1.0 [flutter]
- io 1.0.3 [meta path string_scanner]
- js 0.6.4
- lint 1.8.2
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- mime 1.0.2
- node_preamble 2.0.1
- numberpicker 2.1.1 [flutter infinite_listview]
- octo_image 1.0.2 [flutter flutter_blurhash]
- package_config 2.0.2 [path]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.5 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.1
- path_provider 2.0.10 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.14 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.9 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.7 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.1 [collection meta]
- quiver 3.1.0 [matcher]
- riverpod 2.0.0-dev.9 [collection meta stack_trace state_notifier]
- rxdart 0.27.4
- shelf 1.3.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.1.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.2 [collection path term_glyph]
- sqflite 2.0.2+1 [flutter sqflite_common path]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.2+1 [meta]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0+2
- term_glyph 1.2.0
- test 1.21.1 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.13 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- typed_data 1.3.1 [collection]
- uni_links_platform_interface 1.0.0 [flutter plugin_platform_interface]
- uni_links_web 0.1.0 [flutter flutter_web_plugins uni_links_platform_interface]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.11 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.2
- vm_service 8.3.0
- watcher 1.0.1 [async path]
- web_socket_channel 2.2.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.1.0 [logging]
- win32 2.6.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by rivella50** [comment]
Ok i have found the issue: I installed an additional plugin called advance_pdf_viewer yesterday which seems to have conflicting dependencies with cloud_firestore.
After replacing that package with another one the release build worked fine again on Android (device and simulator).
