### ISSUE TITLE
🐛 [firebase_crashlytics] An SSL error has occurred and a secure connection to the server cannot be made

### ISSUE THREAD

**Issue by Tom3652** [firebase/flutterfire#8953]
## Bug report

**Describe the bug**

I am unable to register an iOS app on crashlytics because of this error : 

```
======== Exception caught by gesture ===============================================================
The following _Exception was thrown while handling a gesture:
Exception

When the exception was thrown, this was the stack: 
#0      HomePage.build.<anonymous closure> (package:eurevia_user/home/home.dart:11:11)
#1      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#2      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)
#3      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
#4      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:232:7)
#5      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
#6      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#7      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#9      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:445:19)
#12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
#13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
#14     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
#15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#21     _invoke1 (dart:ui/hooks.dart:170:10)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#a05ac
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(169.0, 429.0)
  button: 1
  sent tap down
====================================================================================================
ATS failed system trust
Connection 4: system TLS Trust evaluation failed(-9802)
Connection 4: TLS Trust encountered error 3:-9802
Connection 4: encountered error(3:-9802)
Task <D684FEDE-A75E-4AFE-9923-CEC87B78187D>.<2> HTTP load failed, 0/0 bytes (error code: -1200 [3:-9802])
Task <D684FEDE-A75E-4AFE-9923-CEC87B78187D>.<2> finished with error [-1200] Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
    "<cert(0x15000e000) s: upload.video.google.com i: GTS CA 1C3>",
    "<cert(0x1500a2000) s: GTS CA 1C3 i: GTS Root R1>",
    "<cert(0x15001f400) s: GTS Root R1 i: GlobalSign Root CA>"
), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://firebaseinstallations.googleapis.com/v1/projects/eurevia-e/installations/, NSErrorFailingURLStringKey=https://firebaseinstallations.googleapis.com/v1/projects/eurevia-e/installations/, NSUnderlyingError=0x28199ad30 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x2826fb0c0>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x15000e000) s: upload.video.google.com i: GTS CA 1C3>",
    "<cert(0x1500a2000) s: GTS CA 1C3 i: GTS Root R1>",
    "<cert(0x15001f400) s: GTS Root R1 i: GlobalSign Root CA>"
)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <D684FEDE-A75E-4AFE-9923-CEC87B78187D>.<2>"
), _kCFStreamErrorCodeKey=-9802, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <D684FEDE-A75E-4AFE-9923-CEC87B78187D>.<2>, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x2826fb0c0>, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made.}
```

I specify that the `onTap` error is the one suggested in the [documentation](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter).

### Steps to reproduce

1. Follow the instructions mentioned [here](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter)

### Expected behavior

Crashlytics request should be working and the crash registered.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.3
Flutter SDK 3.0.2
myapp 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- firebase_analytics 9.1.10 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 1.18.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.8.2 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_performance 0.8.0+14 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- http 0.13.4 [async http_parser meta path]
- mqtt_client 9.6.8 [typed_data event_bus path crypto meta]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- crypto 3.0.2 [typed_data]
- event_bus 2.0.0
- fake_async 1.3.0 [clock collection]
- firebase 9.0.3 [http http_parser js]
- firebase_analytics_platform_interface 3.1.8 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+15 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.4.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.5 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.8 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_performance_platform_interface 0.1.1+8 [firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.0+14 [firebase firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- js 0.6.4
- lints 2.0.0
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- path 1.8.1
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- vector_math 2.1.2```

</details>

---

**Comment by Tom3652** [comment]
Alright the problem went away today it was working fine without additional setup so i will be guessing this was some internet issue. 
Also this should actually be an issue for the iOS SDK if there is one...
