### ISSUE TITLE
🐛 [firebase_core]: pod install not working with 1.19.1

### ISSUE THREAD

**Issue by MishaCM** [firebase/flutterfire#9022]
## Bug report

pod install is not working with v1.19.1
tried 
flutter clean
flutter pub get
pod install

also getting this error when tried to run the app with version 1.18.0 and below

E/flutter (11780): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (11780): #0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:205:7)
E/flutter (11780): <asynchronous suspension>
![Screenshot from 2022-07-01 22-25-28](https://user-images.githubusercontent.com/97153112/176938946-968636df-e01d-4ce1-b30c-30e95894edab.png)

E/flutter (11780): #1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
E/flutter (11780): <asynchronous suspension>
E/flutter (11780): #2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
E/flutter (11780): <asynchronous suspension>
E/flutter (11780): #3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:40:31)

**Comment by lgomeza** [comment]
Please help. Same issue here. Tried with versions `1.19.1`, `1.18.0`, `1.15.0` and none of them worked. In my case, pod install went through but the app got stuck when calling the Firebase `initializeApp` function

**Comment by arpitignite** [comment]
New SDKs don't compile and old SDK version are throwing PlatformException(channel-error on initializeApp.
🙄

**Comment by manjuhere** [comment]
Same here. Facing the same issue at runtime as app is getting stuck when calling the Firebase initializeApp function and threw the same Exception:

```
#0 FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:205)
#1 MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29)
#2 MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73)
#3 Firebase.initializeApp (package:firebase_core/src/firebase.dart:40)```
```

For reference my pubspec.yaml contains the following firebase packages: 

```
  firebase_core: 1.10.6
  firebase_messaging: 11.2.4
  firebase_performance: 0.8.0+3
```

**Comment by Fauzdar1** [comment]
Holy crap. I was just finishing the app, and now, it doesn't run. Adding `cloud_firestore` was the mistake I did on a perfectly running almost complete app. Now, neither `cloud_firestore` nor `firebase_database` works, same error. It's not even working now even after removing both of these.

```
E/flutter (27591): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (27591): #0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:205:7)
E/flutter (27591): <asynchronous suspension>
E/flutter (27591): #1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
E/flutter (27591): <asynchronous suspension>
E/flutter (27591): #2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
E/flutter (27591): <asynchronous suspension>
E/flutter (27591): #3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:40:31)
E/flutter (27591): <asynchronous suspension>
E/flutter (27591): #4      main (package:xxxxxx/main.dart:24:3)
E/flutter (27591): <asynchronous suspension>
E/flutter (27591): 
```

**Comment by Fauzdar1** [comment]
It's a recent one as it seems - You can see this StackOverFlow question [here](https://stackoverflow.com/questions/72833245/calling-firebase-initializeapp-returns-unable-to-establish-connection-on-chan) and this Flutterflow community issue [here](https://community.flutterflow.io/c/discuss-and-get-help/getting-blank-white-screen-on-local-device).

**Comment by MohamedHaro0on** [comment]
Same here. Facing the same issue at runtime as app is getting stuck when calling the Firebase initializeApp function and throwing the same Exception

**Comment by Fauzdar1** [comment]
Ok guys, I've fixed it after the StackOverFlow question I had shared got an answer. 

The solution is to upgrade any Firebase packages you're using and then, doing Flutter pub outdate/upgrade.

These are the versions I'm using if somebody needs help:

![image](https://user-images.githubusercontent.com/62703211/176990796-a0721f2d-2b5d-42a0-a7b4-5c6ad9ba8de7.png)

**Comment by woutervanwijk** [comment]
Also got it after a pub update. Fixed it by doing: `flutter clean` and removing the pubspec.lock

**Comment by arpitignite** [comment]
None of it seems to work for me.

How is it that the older releases in same codebase are working fine but trying to build the same codebase with same set of dependencies is cause issues?? Requires immediate attention as it is blocking the release of apps.

SOLUTION:
Problem seems to be with the core platform interface.
Add `firebase_core_platform_interface: 4.4.0` and adjust all other firebase deps to make them compatible with this library. I downgraded all versions to 36 day old release and it finally works. Back to business, but this has to be fixed soon...

**Comment by Paitomax** [comment]
> None of it seems to work for me.
> 
> How is it that the older releases in same codebase are working fine but trying to build the same codebase with same set of dependencies is cause issues?? Requires immediate attention as it is blocking the release of apps.
> 
> SOLUTION: Problem seems to be with the core platform interface. Add `firebase_core_platform_interface: 4.4.0` and adjust all other firebase deps to make them compatible with this library. I downgraded all versions to 36 day old release and it finally works. Back to business, but this has to be fixed soon...

@arpitignite, thanks. Here works using `firebase_core_platform_interface: 4.4.1`

```yaml
firebase_core: 1.18.0
firebase_auth: 3.3.20
firebase_analytics: 9.1.10
firebase_crashlytics: 2.8.2
firebase_performance: 0.8.0+14
firebase_remote_config: 2.0.9
firebase_messaging: 11.4.2
firebase_in_app_messaging: 0.6.0+16
firebase_dynamic_links: 4.2.6
firebase_database: 9.0.16
firebase_core_platform_interface: 4.4.1
```

**Comment by arpitignite** [comment]
@Paitomax It seems like it now even works with latest dependencies, all it needed was `firebase_core_platform_interface ` added explicitly. 

I suspect the issue was with one of the stale versions being used as internal libraries in either example or library and since iOS POD creates symlinks, it was cloning the whole repo.. May be I am completely wrong with the suspicion but this works for some reason.. 

ex: <img width="817" alt="Screenshot 2022-07-02 at 5 27 29 PM" src="https://user-images.githubusercontent.com/16299995/176999778-57275afe-4657-4834-995e-a42b8614897d.png">

**Comment by isegal** [comment]
@arpitignite does this work with a complete clean rebuild or a clean cloud-based build?

**Comment by arpitignite** [comment]
> @arpitignite does this work with a complete clean rebuild or a clean cloud-based build?

4.4.1 and below are working fine on clean build as well as cloud based CD. 

Current versions are still failing, I hadn't cleaned after updating the deps when testing. There is another issue with precompiled Cloud Firestore 9.2.0 throwing error when using with 3.2.1 cloud_firestore

**Comment by agumabanks** [comment]
all I did was upgrade the dependencies

**Comment by Paitomax** [comment]
> Also got it after a pub update. Fixed it by doing: `flutter clean` and removing the pubspec.lock

@arpitignite, I succefully compile with firebase current version after **complete clean**

```bash
flutter clean
rm -rf pubspec.lock ios/Pods ios/Podfile.lock ~/.pub-cache
flutter pub get
cd ios
pod install
```

**Comment by darshankawar** [comment]
Everyone in this thread, check [this](https://github.com/firebase/flutterfire/issues/9015#issuecomment-1173604569) and see if it helps to resolve the issue.

**Comment by hicnar** [comment]
@darshankawar Having to apply hacks like in the link you provided above in order that a new, presumably stable release of a library works is NOT how properly managed release process should work. Test it first with the dependencies you have, make sure it works then release it.

**Comment by MishaCM** [comment]
> > None of it seems to work for me.
> > How is it that the older releases in same codebase are working fine but trying to build the same codebase with same set of dependencies is cause issues?? Requires immediate attention as it is blocking the release of apps.
> > SOLUTION: Problem seems to be with the core platform interface. Add `firebase_core_platform_interface: 4.4.0` and adjust all other firebase deps to make them compatible with this library. I downgraded all versions to 36 day old release and it finally works. Back to business, but this has to be fixed soon...
> 
> @arpitignite, thanks. Here works using `firebase_core_platform_interface: 4.4.1`
> 
> ```yaml
> firebase_core: 1.18.0
> firebase_auth: 3.3.20
> firebase_analytics: 9.1.10
> firebase_crashlytics: 2.8.2
> firebase_performance: 0.8.0+14
> firebase_remote_config: 2.0.9
> firebase_messaging: 11.4.2
> firebase_in_app_messaging: 0.6.0+16
> firebase_dynamic_links: 4.2.6
> firebase_database: 9.0.16
> firebase_core_platform_interface: 4.4.1
> ```

Thank you for this!
I 

> None of it seems to work for me.
> 
> How is it that the older releases in same codebase are working fine but trying to build the same codebase with same set of dependencies is cause issues?? Requires immediate attention as it is blocking the release of apps.
> 
> SOLUTION: Problem seems to be with the core platform interface. Add `firebase_core_platform_interface: 4.4.0` and adjust all other firebase deps to make them compatible with this library. I downgraded all versions to 36 day old release and it finally works. Back to business, but this has to be fixed soon...

Thank you!


> firebase_core_platform_interface: 4.4.0



> > None of it seems to work for me.
> > How is it that the older releases in same codebase are working fine but trying to build the same codebase with same set of dependencies is cause issues?? Requires immediate attention as it is blocking the release of apps.
> > SOLUTION: Problem seems to be with the core platform interface. Add `firebase_core_platform_interface: 4.4.0` and adjust all other firebase deps to make them compatible with this library. I downgraded all versions to 36 day old release and it finally works. Back to business, but this has to be fixed soon...
> 
> @arpitignite, thanks. Here works using `firebase_core_platform_interface: 4.4.1`
> 
> ```yaml
> firebase_core: 1.18.0
> firebase_auth: 3.3.20
> firebase_analytics: 9.1.10
> firebase_crashlytics: 2.8.2
> firebase_performance: 0.8.0+14
> firebase_remote_config: 2.0.9
> firebase_messaging: 11.4.2
> firebase_in_app_messaging: 0.6.0+16
> firebase_dynamic_links: 4.2.6
> firebase_database: 9.0.16
> firebase_core_platform_interface: 4.4.1
> ```

It worked for me. Thanks a lot!

These are versions I used:
> firebase_core: 1.18.0
> firebase_messaging: 11.4.2
> firebase_core_platform_interface: 4.4.1

**Comment by MishaCM** [comment]
> > None of it seems to work for me.
> > How is it that the older releases in same codebase are working fine but trying to build the same codebase with same set of dependencies is cause issues?? Requires immediate attention as it is blocking the release of apps.
> > SOLUTION: Problem seems to be with the core platform interface. Add `firebase_core_platform_interface: 4.4.0` and adjust all other firebase deps to make them compatible with this library. I downgraded all versions to 36 day old release and it finally works. Back to business, but this has to be fixed soon...
> 
> @arpitignite, thanks. Here works using `firebase_core_platform_interface: 4.4.1`
> 
> ```yaml
> firebase_core: 1.18.0
> firebase_auth: 3.3.20
> firebase_analytics: 9.1.10
> firebase_crashlytics: 2.8.2
> firebase_performance: 0.8.0+14
> firebase_remote_config: 2.0.9
> firebase_messaging: 11.4.2
> firebase_in_app_messaging: 0.6.0+16
> firebase_dynamic_links: 4.2.6
> firebase_database: 9.0.16
> firebase_core_platform_interface: 4.4.1
> ```

It worked for me. Thanks a lot!

These are the versions I used:
> firebase_core: 1.18.0
> firebase_messaging: 11.4.2
> firebase_core_platform_interface: 4.4.1

**Comment by darshankawar** [comment]
> Everyone in this thread, check [this](https://github.com/firebase/flutterfire/issues/9015#issuecomment-1173604569) and see if it helps to resolve the issue.

Please try this solution and see if it works.

**Comment by PersianBlue** [comment]
I was also having these problems, tried the suggestions on similar questions using flutter pub outdated and individually upgrading each Firebase package, but that didn't solve the issue. 
Turns out my problem was Firebase doesn't seem to support Flutter apps for Windows desktop right now. When I switched to use Chrome as my platform, I was no longer having the unable to establish connection on channel error.  

If Windows desktop is indeed the issue (it wasn't even available in the firebase CLI [flutterfire config] as an option to add support for), hope they add support soon
