### ISSUE TITLE
[Firebase-messanging] Error:- Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference

### ISSUE THREAD

**Issue by AnilNeodove** [firebase/flutterfire#9059]
Error:- Facing crash sometime in some device when app is in background. stack-trace is below

java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference
	at io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString()
	at java.lang.StringBuilder.append(StringBuilder.java:202)
	at io.flutter.embedding.engine.dart.DartExecutor.executeDartCallback()
	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.c(:1)
	at io.flutter.plugins.firebase.messaging.a.run()
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5601)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

**Comment by darshankawar** [comment]
@AnilNeodove 
When you open an issue, please try to use new issue template and fill out requested details so that we'll have enough details to work with. Only sharing the error message won't help much to debug properly.

Can you provide `flutter doctor -v`, `pubspec.yaml` , platform on which you are seeing this error along with minimal code sample and steps to replicate ?
