### ISSUE TITLE
🐛 [cloud_firestore] Intermittent authentication failure errors when running Firestore transactions in Flutter

### ISSUE THREAD

**Issue by ghunter99** [firebase/flutterfire#9072]
## Bug report

I have two apps in the Apple App Store and Google Play Store that have been running without problems for over a year.
Both apps haven't been updated for several months.

In the last week, both apps have started intermittently (about 30% of the time) throwing authentication errors when running simple Firestore transactions. 

The error doesn't occur when signing in but after successfully authenticating.

The errors are thrown in the middle of a simple Firestore transaction when calling transaction.get 
  i.e. Future<DocumentSnapshot<T>> get<T extends Object?>()

The error message is:

`PlatformException(firebase_firestore, UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project., {code: unauthenticated, message: The request does not have valid authentication credentials for the operation.}, null)`

Because the transactions are often successful I'm guessing this is not the real reason the transaction failing.

I'm pulling my hair out because I haven't changed anything in the app or the way Firestore is configured.

### Steps to reproduce

1. I upgraded a test project to the latest Flutter version and Firebase packages
2. The project runs on iOS and Android and I authenticate using an email and password
3. I wrote a simple method to show the problem. I reduced the transaction to doing a simple transaction.get
  
  ```
Future<bool> testTransaction(BuildContext context, String userId) async {
    bool success = true;
    final userRef = FirebaseFirestore.instance.doc('users/$userId');
    try {
      await FirebaseFirestore.instance.runTransaction((transaction) async {
        final userSnapshot =
            await transaction.get<Map<String, dynamic>>(userRef);
        print('SUCCESSFUL TRANSACTION:\n'
            '${userSnapshot.exists ? 'user exists' : 'user does not exist'}');
        print('---\n');
      });
    } catch (e, s) {
      print('FAILED TRANSACTION:\n$e');
      print('STACK TRACE:\n$s');
      print('---\n');
      unawaited(showExceptionAlertDialog(
        context: context,
        title: 'Add timekeeper to lane failed',
        exception: e,
      ));
      success = false;
    }
    return success;
  }
```

4. Here's some debug output showing 2 successful transactions followed by a failed transaction with stack trace:

```
I/flutter ( 6717): SUCCESSFUL TRANSACTION:
I/flutter ( 6717): user exists
I/flutter ( 6717): ---
I/flutter ( 6717): SUCCESSFUL TRANSACTION:
I/flutter ( 6717): user exists
I/flutter ( 6717): ---
W/System  ( 6717): Ignoring header X-Firebase-Locale because its value was null.
I/flutter ( 6717): FAILED TRANSACTION:
I/flutter ( 6717): PlatformException(firebase_firestore, UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project., {code: unauthenticated, message: The request does not have valid authentication credentials for the operation.}, null)
I/flutter ( 6717): STACK TRACE:
I/flutter ( 6717): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
I/flutter ( 6717): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
I/flutter ( 6717): <asynchronous suspension>
I/flutter ( 6717): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:367:43)
I/flutter ( 6717): <asynchronous suspension>
I/flutter ( 6717): #3      MethodChannelTransaction.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_transaction.dart:46:42)
I/flutter ( 6717): <asynchronous suspension>
I/flutter ( 6717): #4      Transaction.get (package:cloud_firestore/src/transaction.dart:28:9)
I/flutter ( 6717): <asynchronous suspension>
I/flutter ( 6717): #5      FirestoreDatabase.testTransaction.<anonymous closure> (package:rlts/services/firestore_database.dart:589:13)
I/flutter ( 6717): <asynchronous suspension>
I/flutter ( 6717): #6      FirebaseFirestore.runTransaction.<anonymous closure> (package:cloud_firestore/src/firestore.dart:223:18)
I/flutter ( 6717): <asynchronous suspension>
I/flutter ( 6717): #7      MethodChannelFirebaseFirestore.runTransaction.<anonymous closure> (package:cloud_firestore_platform_interfa
I/flutter ( 6717): ---

```

### Expected behavior

I expect the transaction to work

### Sample project

I can provide a simple sample project but that will take a bit of work so I thought I post a bug report to see if anyone had any ideas first.

---

## Additional context

For my test project and I made the Firestore rules very simple so I don't think the rules causing any problems:

```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
		// Allow read/write access on all documents to any user signed in to the application
    match /{document=**} {
      allow read, write: if request.auth != null
    }
  }
}
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (4 available)
    ! Error: Gary’s iPhone SE is busy: Preparing the watch for development via Gary’s iPhone SE. Xcode will continue when Gary’s iPhone SE is finished. (code -10)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.5
Flutter SDK 3.0.4
rlts 0.1.5+7

dependencies:
- alert_dialogs 0.0.1 [flutter]
- audioplayers 0.19.1 [uuid path_provider http flutter flutter_web_plugins]
- badges 2.0.3 [flutter]
- cached_network_image 3.2.1 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- charcode 1.3.1
- cloud_firestore 3.2.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- collection 1.16.0
- cupertino_icons 1.0.5
- firebase_analytics 9.1.12 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.4.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.19.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 11.4.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 2.0.11 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_storage 10.3.1 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- firestore_service 0.0.1 [flutter cloud_firestore]
- fl_chart 0.36.4 [flutter equatable pedantic]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_app_badger 1.4.0 [flutter]
- flutter_hooks 0.18.5+1 [flutter]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_local_notifications 9.6.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_platform_widgets 1.9.5 [flutter]
- flutter_secure_storage 5.0.2 [meta flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows]
- flutter_staggered_animations 1.0.0 [flutter]
- font_awesome_flutter 9.2.0 [flutter]
- google_fonts 2.3.3 [flutter http path_provider crypto]
- google_sign_in 5.4.0 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- goswimclub_assets 0.0.1 [flutter]
- hooks_riverpod 2.0.0-dev.9 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- intl 0.17.0 [clock path]
- logger 1.1.0
- ntp 2.0.0
- package_info_plus 1.4.2 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- rxdart 0.27.4
- scrollable_positioned_list 0.3.2 [flutter collection]
- shared 0.0.1 [flutter]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- store_redirect 2.0.1 [flutter]
- string_validators 0.0.1 [flutter]
- the_apple_sign_in 1.1.1 [flutter]
- timeline_tile 2.0.0 [flutter]
- url_launcher 6.1.4 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.6 [crypto]
- version 2.0.3
- wakelock 0.5.6 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- webview_flutter 3.0.4 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- flutter_launcher_icons 0.9.3 [args image path yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- archive 3.3.0 [crypto path]
- args 2.3.1
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.5.10 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.19 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- dbus 0.7.4 [args ffi meta xml]
- equatable 2.0.3 [collection meta]
- fake_async 1.3.0 [clock collection]
- ffi 1.2.1
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.1.10 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+17 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.3.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.19 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.4.3 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.6.6 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.5.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.4.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config_platform_interface 1.1.10 [firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.0.16 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- firebase_storage_platform_interface 4.1.10 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.2.19 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_local_notifications_linux 0.5.0+1 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.6 [flutter]
- flutter_riverpod 2.0.0-dev.9 [collection flutter meta riverpod state_notifier]
- flutter_secure_storage_linux 1.1.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 1.1.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.0 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.0.2 [flutter flutter_web_plugins flutter_secure_storage_platform_interface js]
- flutter_secure_storage_windows 1.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- google_sign_in_android 6.0.1 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.4.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.2.0 [flutter quiver]
- google_sign_in_web 0.10.2 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image 3.2.0 [archive meta xml]
- image_picker_android 0.8.5+1 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.5+6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.5.0 [cross_file flutter http plugin_platform_interface]
- js 0.6.4
- linkify 4.1.0
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- octo_image 1.0.2 [flutter flutter_blurhash]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.5 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.1
- path_provider_android 2.0.16 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.10 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.7 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- quiver 3.1.0 [matcher]
- riverpod 2.0.0-dev.9 [collection meta stack_trace state_notifier]
- shared_preferences_android 2.0.12 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- sqflite 2.0.3 [flutter sqflite_common path]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.2+1 [meta]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0+2
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- typed_data 1.3.1 [collection]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.12 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.2
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- webview_flutter_android 2.8.14 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.9.1 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 2.8.1 [flutter path webview_flutter_platform_interface]
- win32 2.6.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @ghunter99 



> PlatformException(firebase_firestore, UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project., {code: unauthenticated, message: The request does not have valid authentication credentials for the operation.}, null)

Looking at this error, it seems the request is not reaching the server and hence the `unauthenticated` message code is being sent back to Dart.
Are you by any chance adding or overriding the new/existing params of firebase auth JWT ?

Or is there a way that you might be hitting / exceeded the number of transactions being hit ? It seems that this could be coming from server instead of client side. I suggest you to reach out to [firebase support](https://firebase.google.com/support) for further resolution and would be good if you could update us with their feedback as well.

**Comment by ghunter99** [comment]
Thanks @darshankawar, 
I'm not adding or overriding the new/existing params of firebase auth JWT, 
so I've followed your suggestion and filed a bug report with [firebase support](https://firebase.google.com/support)
I'll let you know what happens.

**Comment by blueeyestw** [comment]
I am also facing this issue. Didn't touch or update my app for about 3 months, now suddenly, when running firestore transactions, sometimes the transaction fails and returns this error:

`PlatformException(firebase_firestore, UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project., {code: unauthenticated, message: The request does not have valid authentication credentials for the operation.}, null)`

The error is the same for Android and iOS and happens about 20% of the time.

**Comment by ghunter99** [comment]
@blueeyestw sorry to hear you're experiencing similar issues - but also reassured that I'm not going crazy by myself.
Still waiting to hear back from [firebase support](https://firebase.google.com/support). Probably time to buy a support subscription.
@darshankawar I did find out something interesting though. 
My production apps have a Firebase project GCP resource location: **australia-southeast1**
I created an identical project with a location **nam5 (us-central)**
...and the problem disappears - which is pretty crazy
What's up with **australia-southeast1**?  a timezone/clock thing maybe? any ideas?

**Comment by blueeyestw** [comment]
@ghunter99 I have found a temporary work-around by changing my get calls inside the transaction

Before:
`      await firestore.runTransaction((transaction) async {
        DocumentSnapshot logDoc = await transaction.get(logRef);
        DocumentSnapshot workdaysDoc = await transaction.get(workdaysRef);
        DocumentSnapshot recordDoc = await transaction.get(recordRef);
        DocumentSnapshot userDoc = await transaction.get(userRef);
       ...rest of code...
`
After:
`      await firestore.runTransaction((transaction) async {
        DocumentSnapshot logDoc = await logRef.get();
        DocumentSnapshot workdaysDoc = await workdaysRef.get();
        DocumentSnapshot recordDoc = await recordRef.get();
        DocumentSnapshot userDoc = await userRef.get();
       ...rest of code...
`

**Comment by ghunter99** [comment]
Thanks for the suggested workaround @blueeyestw. Unfortunately, I rely on the atomic nature of the transaction.
Curious, what resource location is your project running in?

**Comment by darshankawar** [comment]
Thanks for further debugging and updates @ghunter99 




> What's up with **australia-southeast1**? a timezone/clock thing maybe? any ideas?

Maybe it has to do something with  configuration in GCP / Firebase project ? Can you maybe try to see if there's any difference in settings / config between these location / timezone that may be causing it ?

**Comment by blueeyestw** [comment]
> Thanks for the suggested workaround @blueeyestw. Unfortunately, I rely on the atomic nature of the transaction. Curious, what resource location is your project running in?

asia-northeast1

**Comment by emmerich** [comment]
We're seeing the same thing - over the past month or so we're getting a steadily increasing number of "client is offline" errors and it's down to the exact error you've posted. Our entire Firebase stack is in `us-central1`. 

What's crazy is that we're seeing 2 separate auth requests to Firebase using **the exact same JWT token** are both failing. We've also reached out to Firebase support but no luck.

**Comment by emmerich** [comment]
We just got feedback from the Firebase support team that they're experiencing intermittent issues with authentication in `us-central1` so in this case, seems like it was on their side.

**Comment by wgbnyes** [comment]
But attention, it's not just us-central1, because my application is configured for europe-west3 and I'm still facing this problem.

By the way, my application is in europe-west3 but I use the REST API of firestore, I don't know if this one is in us-central1...

**Comment by ghunter99** [comment]
@darshankawar  - so this morning (I'm in Australia GMT + 10 hrs) I started making a mcve ([minimal, complete and verifiable example](https://stackoverflow.com/help/minimal-reproducible-example)) and lo and behold the error has stopped happening! 
Hasn't happened for 12 hours. @blueeyestw, @emmerrich, @wgbynes - wondering if you've noticed any changes?

After a solid week of transactions failing with authentication errors approx 20-30% of the time, everything has been working in my test programs and production apps running in australia-southeast1 🤔

Asked the person I'm interacting with at firebase support if they had any information but haven't heard back.

Yesterday firebase support said they'd received similar support cases to mine in Default GCP resource locations: australia-southeast1, asia-northeast1 and us-east4

**Comment by wgbnyes** [comment]
Yes it's true, @ghunter99 . Looking at my logs, from yesterday to today I haven't received any of these errors.

**Comment by darshankawar** [comment]
@ghunter99 and everyone in this thread facing this issue, from the comments we saw earlier, it doesn't seem to be specific to FlutterFire and looks like an issue at Firebase level itself. I suggest everyone to please follow-up in firebase support as they seem to have acknowledged the issue and for further resolution.  Closing this from here. If anyone disagrees, write in comments and I'll reopen it.
