### ISSUE TITLE
🐛 [firebase_core] Your issue title here

### ISSUE THREAD

**Issue by deepsan98** [firebase/flutterfire#9088]
## Bug report

**Describe the bug**
When I launch the app, I get the following error:
```
E/flutter ( 2714): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 2714): #0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:205:7)
E/flutter ( 2714): <asynchronous suspension>
E/flutter ( 2714): #1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
E/flutter ( 2714): <asynchronous suspension>
E/flutter ( 2714): #2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
E/flutter ( 2714): <asynchronous suspension>
E/flutter ( 2714): #3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:42:31)
E/flutter ( 2714): <asynchronous suspension>
E/flutter ( 2714): #4      main (package:falabella/main.dart:31:3)
E/flutter ( 2714): <asynchronous suspension>
E/flutter ( 2714): 
```

### Steps to reproduce

1. Add these dependencies in `pubspec.yaml`:
```
firebase_core 1.19.1
firebase_crashlytics: ^2.8.4
firebase_analytics: ^9.1.12
```
2. Launch the app

### Expected behavior

The app should launch without any error message.

---

## Additional informations
I already have tried putting to put `firebase_core_platform_interface: 4.4.1` in `dependency_overrides` or in `dependencies`.
I only have 3 firebase packages (mentioned above) and they are all at last version available.

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.0.1 21A559 darwin-arm, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.69.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by mustafa-707** [comment]
same here ! , also im facing a problem with Firebase/Crashlytics in pod install 

```
[!] CocoaPods could not find compatible versions for pod "Firebase/Crashlytics":
  In snapshot (Podfile.lock):
    Firebase/Crashlytics (= 8.15.0)

  In Podfile:
    firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 2.8.5, which depends on
      Firebase/Crashlytics (= 9.2.0)


You have either:
 * changed the constraints of dependency `Firebase/Crashlytics` inside your development pod `firebase_crashlytics`.
   You should run `pod update Firebase/Crashlytics` to apply changes you've made.
```

**Comment by darshankawar** [comment]
@deepsan98 
Check similar SO link and underlying solution and see if they help : https://stackoverflow.com/questions/72833245/calling-firebase-initializeapp-returns-unable-to-establish-connection-on-chan/72835948#72835948

Also, see if this helps: https://github.com/firebase/flutterfire/issues/9028#issuecomment-1173073740

Moreover, try upgrading all your firebase plugins you are using to latest versions and see if it works:

https://pub.dev/packages/firebase_core/changelog#1192
https://pub.dev/packages/firebase_crashlytics/changelog#285
https://pub.dev/packages/firebase_analytics/changelog#920

Similar issue : https://github.com/firebase/flutterfire/issues/9022

**Comment by deepsan98** [comment]
@darshankawar I already tried all your suggested solutions before opening this issue.

And, #9022 is not similar to my issue. I don't think the issue described by @mustafa-707 has anything to do with my situation.

**Comment by ChristianEdwardPadilla** [comment]
Found the issue for me. It was that `firebase_core` was not being registered. This was an issue with my specific setup and not a bug with this repo at all. For those running into unexpected PlatformException, consider checking your native registration calls to be sure all your plugins' `registerWith` calls are being made.

**Comment by darshankawar** [comment]
@deepsan98 Check above comment / solution and see if its the case with you as well.

**Comment by darshankawar** [comment]
Thanks for the update @deepsan98 
I actually hit this error while running a sample `firebase_remote_config` example which had following dependencies:

`firebase_core` and `firebase_remote_config` and were on old versions. When I only updated `firebase_remote_config` to latest but kept `firebase_core` as-is, I got the same error as you reported:

<details>
<summary> console error log </summary>

```

Launching lib/main.dart on iPhone 13 in debug mode...
Upgrading AppFrameworkInfo.plist
Upgrading Podfile
Upgrading Info.plist
Running pod install...
Running Xcode build...
Xcode build done.                                           61.3s
Debug service listening on ws://127.0.0.1:52412/10T1n91UcO8=/ws
Syncing files to device iPhone 13...
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:205:7)
<asynchronous suspension>
#1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
<asynchronous suspension>
#2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
<asynchronous suspension>
#3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:42:31)
<asynchronous suspension>
#4      setupRemoteConfig (package:triage/main.dart:79:3)
<asynchronous suspension>

```

</details>

But when I upgraded `firebase_core` to latest version, ran again, it compiled and built the app properly:

```
  Launching lib/main.dart on iPhone 13 in debug mode...
Running Xcode build...
Xcode build done.                                           16.2s
Debug service listening on ws://127.0.0.1:52765/CPDnXJDu5lY=/ws
Syncing files to device iPhone 13...

```

So after upgrading plugin versions, try deleting the podfile.lock and then try running again and see if it helps.

**Comment by deepsan98** [comment]
I already updated all firebase dependencies to latest version and also tried to delete `podfile.lock`

Still not working

**Comment by deepsan98** [comment]
It is a typo. I am currently using `firebase_core: ^1.19.2`.

**Comment by KKimj** [comment]
Hello folks!

Can I use only latest version of `Firebase Core`, `1.19.2`?

I want to use `firebase_core: 1.18.0`, because of pre-compiled firebase-ios-sdk by [invertase/firestore-ios-sdk-frameworks](https://github.com/invertase/firestore-ios-sdk-frameworks).

Thanks!!
