### ISSUE TITLE
🐛 Android e2e test CI sometimes fails because of `Exception in thread "main" java.net.SocketException: Broken pipe (Write failed)`

### ISSUE THREAD

**Issue by nilsreichardt** [firebase/flutterfire#9168]
```
Building with Flutter multidex support enabled.
Error: Exception in thread "main" java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeChangeCipherSpec(SSLSocketOutputRecord.java:231)
	at java.base/sun.security.ssl.OutputRecord.changeWriteCiphers(OutputRecord.java:187)
	at java.base/sun.security.ssl.ChangeCipherSpec$T10ChangeCipherSpecProducer.produce(ChangeCipherSpec.java:118)
	at java.base/sun.security.ssl.Finished$T12FinishedProducer.onProduceFinished(Finished.java:395)
	at java.base/sun.security.ssl.Finished$T12FinishedProducer.produce(Finished.java:379)
	at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:436)
	at java.base/sun.security.ssl.ServerHelloDone$ServerHelloDoneConsumer.consume(ServerHelloDone.java:182)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
Running Gradle task 'assembleDebug'...                             74.6s
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:572)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:[61](https://github.com/firebase/flutterfire/runs/7431854072?check_suite_focus=true#step:11:62))
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:[65](https://github.com/firebase/flutterfire/runs/7431854072?check_suite_focus=true#step:11:66))
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

https://github.com/firebase/flutterfire/runs/7431854072?check_suite_focus=true

**Comment by darshankawar** [comment]
@nilsreichardt 
Could it be due to a network interruption while the CI tests were running ?

**Comment by nilsreichardt** [comment]
I don't think so because the issue happens too often for this. I think it happens with a 5% - 10% likelihood.

**Comment by darshankawar** [comment]
Ok, what's the gradle version CI is using ? It seems to be failing while trying to download dependencies and unable to do so throwing the log.



> at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
> 	at org.gradle.wrapper.Download.download(Download.java:44)
> 	at org.gradle.wrapper.Install$1.call(Install.java:[61](https://github.com/firebase/flutterfire/runs/7431854072?check_suite_focus=true#step:11:62))
> 	at org.gradle.wrapper.Install$1.call(Install.java:48)
> 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:[65](https://github.com/firebase/flutterfire/runs/7431854072?check_suite_focus=true#step:11:66))
> 	at org.gradle.wrapper.Install.createDist(Install.java:48)
> 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
> 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by nilsreichardt** [comment]
https://github.com/firebase/flutterfire/blob/c2771a425bd7260b11970e9e9e77ef40a39f9f16/tests/android/gradle/wrapper/gradle-wrapper.properties#L6

It's version `7.0.2`

**Comment by darshankawar** [comment]
Sorry, somehow missed this issue from my list. Keeping it open for further insights from the team.

**Comment by russellwheatley** [comment]
Closing as I haven't seen this crop up for some time in our android CI.
