### ISSUE TITLE
🐛 [firebase_messaging] Cannot receive FCM token on Xiaomi Device

### ISSUE THREAD

**Issue by huubao2309** [firebase/flutterfire#9208]
## 🐛 [firebase_messaging] Cannot receive FCM token on Xiaomi Device

- I'm using Xiaomi Device with Info

```
Device Model: Redmi 6
MIUI Version: 11.0.4(PCGMIXM)
Android Version: 9 PPRT 180610.011
```

- I cannot receive FCM token on my device.

- Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-x64, locale en-VN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
[✓] Connected device (4 available)
    ! Error: iPhone QC is not connected. Xcode will continue when iPhone QC is connected. (code -13)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

- I'm using library of Firebase at `pubspec.yaml`

```
  firebase_crashlytics: ^2.8.5
  firebase_messaging: ^12.0.1
  firebase_analytics: ^9.2.0
```

- At `build.gradle` of android app:

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:30.3.0')
    implementation 'com.google.firebase:firebase-crashlytics:18.2.11'
    implementation 'com.google.firebase:firebase-analytics:18.0.2'
}
```

- At `build.gradle` of android project:

```
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath 'com.google.gms:google-services:4.3.13'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
```

- And at `main_app.dart`

```
  void _registerTokenFCMNotification() async {
    try {
     final FirebaseMessaging firebaseMessaging = FirebaseMessaging.instance;
      final tokenFcm = await firebaseMessaging.getToken();
      print('firebase token: $tokenFcm');
    } catch (ex) {
      print('Error firebase at registerNotification: $ex');
    }
  }
```

- And when I running my app, exception:

```
firebase_messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:367:43)
<asynchronous suspension>
#3      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:224:11)
<asynchronous suspension>
#4      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:870:15)
```

**Comment by dwikresno** [comment]
how u solved this issue on xiaomi @huubao2309 ?

**Comment by dwikresno** [comment]
solved this issue by restart device :)
