### ISSUE TITLE
🐛 [FirebaseAuth] NullPointerException on GeneratedAndroidFirebaseAuth

### ISSUE THREAD

**Issue by fpasalioglu** [firebase/flutterfire#9210]
## Bug report
I have crash on Firebase console. This crash starts when I upgraded libraries versions. Log has FlutterFirebaseAuthPlugin.java so I think this crash caused by firebase_auth library.

<details><summary>Click To Expand</summary>

```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
       at io.flutter.plugin.common.BasicMessageChannel.setMessageHandler(BasicMessageChannel.java:132)
       at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$MultiFactorUserHostApi.setup(GeneratedAndroidFirebaseAuth.java:358)
       at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$MultiFactorUserHostApi$-CC.setup(GeneratedAndroidFirebaseAuth.java:3)
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.onDetachedFromEngine(FlutterFirebaseAuthPlugin.java:131)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:270)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:280)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:288)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:121)
       at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:425)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:699)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:715)
       at android.app.Activity.performDestroy(Activity.java:8428)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1343)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5330)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5374)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8131)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011) 

```

</details>

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1826], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.1)
[√] Android Studio (version 2021.2)
[√] Connected device (5 available)
[√] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.6
Flutter SDK 3.0.5
lopmeflutter 4.1.0+2022072201

dependencies:
- aliyun_oss_flutter 1.0.5 [flutter path http_parser crypto intl dio uuid]
- animated_bottom_navigation_bar 1.0.1 [flutter]
- auto_size_text 3.0.0 [flutter]
- bottom_picker 1.9.1 [flutter]
- cached_network_image 3.2.1 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- carousel_slider 4.1.1 [flutter]
- cookie_jar 3.0.1
- country_code_picker 2.0.2 [flutter modal_bottom_sheet collection universal_platform]
- crypto 3.0.2 [typed_data]
- cupertino_icons 1.0.5
- device_info_plus 3.2.4 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- dio 4.0.6 [http_parser path]
- dio_cache_interceptor 3.3.0 [dio uuid string_scanner]
- dio_cookie_manager 2.0.0 [cookie_jar dio]
- easy_localization 3.0.1 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- ffi 1.2.1
- firebase_analytics 9.2.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.5.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.20.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.8.6 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_inappwebview 5.4.3+7 [flutter]
- flutter_kronos 0.0.2+2 [flutter]
- flutter_launcher_icons 0.9.3 [args image path yaml]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_login_facebook 1.4.1 [flutter list_ext]
- flutter_switch 0.3.2 [flutter]
- flutter_vap 1.1.0 [flutter]
- fluttertoast 8.0.9 [flutter flutter_web_plugins]
- font_awesome_flutter 10.1.0 [flutter]
- google_sign_in 5.4.0 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- gradient_ui_widgets 1.0.2-nullsafety [flutter]
- image_cropper 2.0.3 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- in_app_purchase 3.0.6 [flutter in_app_purchase_android in_app_purchase_platform_interface in_app_purchase_storekit]
- intl 0.17.0 [clock path]
- json_annotation 4.6.0 [meta]
- live_flutter_plugin 1.0.11 [uuid flutter]
- nb_utils 4.5.2 [flutter shared_preferences fluttertoast connectivity_plus]
- new_version 0.3.1 [flutter package_info_plus http html url_launcher collection]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- permission_handler 10.0.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- pinch_zoom_image_last 0.4.1 [flutter]
- provider 6.0.3 [collection flutter nested]
- pull_to_refresh_flutter3 2.0.1 [flutter]
- responsive_sizer 3.1.0 [flutter]
- share_plus 4.0.10 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 4.1.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- smooth_page_indicator 1.0.0+2 [flutter]
- step_progress_indicator 1.0.2 [flutter]
- svgaplayer_flutter 2.1.2 [flutter protobuf http path_drawing archive]
- tencent_im_sdk_plugin 4.0.7 [flutter flutter_web_plugins json_annotation tencent_im_sdk_plugin_web tencent_im_sdk_plugin_platform_interface uuid]
- tencent_trtc_cloud 2.3.4 [flutter flutter_web_plugins js json_annotation]
- tpns_flutter_plugin 1.1.7 [flutter]
- url_launcher 6.1.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- wakelock 0.6.2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- archive 3.3.1 [crypto path]
- args 2.3.1
- asn1lib 1.1.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- connectivity_plus 2.3.6 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- connectivity_plus_linux 1.3.1 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.4 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.1 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.3 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.2 [connectivity_plus_platform_interface flutter]
- convert 3.0.2 [typed_data]
- cross_file 0.3.3+1 [js meta]
- csslib 0.17.2 [source_span]
- dbus 0.7.4 [args ffi meta xml]
- device_info_plus_linux 2.1.1 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 2.2.3 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 2.3.0+1 [flutter meta plugin_platform_interface]
- device_info_plus_web 2.1.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 2.1.1 [device_info_plus_platform_interface ffi flutter win32]
- easy_logger 0.0.2 [flutter]
- fake_async 1.3.0 [clock collection]
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.2.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.1+1 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.4.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 4.1.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.12 [collection firebase_core flutter meta plugin_platform_interface]
- fixnum 1.0.1
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- google_sign_in_android 6.0.1 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.4.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.2.0 [flutter quiver]
- google_sign_in_web 0.10.2 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- html 0.15.0 [csslib source_span]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image 3.2.0 [archive meta xml]
- image_cropper_for_web 0.0.4 [flutter flutter_web_plugins image_cropper_platform_interface js]
- image_cropper_platform_interface 2.0.0 [flutter plugin_platform_interface http]
- image_picker_android 0.8.5+1 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.5+6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.5.0 [cross_file flutter http plugin_platform_interface]
- in_app_purchase_android 0.2.3+1 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_purchase_platform_interface 1.3.1 [flutter plugin_platform_interface]
- in_app_purchase_storekit 0.3.1 [collection flutter in_app_purchase_platform_interface json_annotation]
- js 0.6.4
- list_ext 1.0.4 [quiver collection]
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- mime 1.0.2
- mime_type 1.0.0
- modal_bottom_sheet 2.1.0 [flutter]
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 1.0.2 [flutter flutter_blurhash]
- package_info_plus 1.4.2 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.5 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.1
- path_drawing 0.5.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_android 2.0.16 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.10 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.7 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_android 10.0.0 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.0 [flutter permission_handler_platform_interface]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pointycastle 3.6.1 [collection convert js]
- process 4.2.4 [file path platform]
- protobuf 2.1.0 [fixnum collection meta]
- quiver 3.1.0 [matcher]
- rxdart 0.27.5
- share_plus_linux 3.0.0 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 3.0.1 [share_plus_platform_interface flutter]
- share_plus_platform_interface 3.0.3 [flutter meta mime plugin_platform_interface]
- share_plus_web 3.0.1 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 3.0.1 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences_android 2.0.12 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- sqflite 2.0.3 [flutter sqflite_common path]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0+2
- tencent_im_sdk_plugin_platform_interface 0.2.8 [flutter plugin_platform_interface]
- tencent_im_sdk_plugin_web 0.2.4 [flutter flutter_web_plugins mime_type tencent_im_sdk_plugin_platform_interface js path]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- universal_platform 1.0.0+1
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.12 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- win32 2.6.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]

```

</details>

---

**Comment by alectogeek** [comment]
I have the same issue, here is stacktrace:

```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
       at io.flutter.plugin.common.BasicMessageChannel.setMessageHandler(BasicMessageChannel.java:132)
       at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$MultiFactorUserHostApi$-CC.setup(GeneratedAndroidFirebaseAuth.java:358)
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.onDetachedFromEngine(FlutterFirebaseAuthPlugin.java:131)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:270)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:280)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:288)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:121)
       at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:425)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:699)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:715)
       at android.app.Activity.performDestroy(Activity.java:8428)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5294)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5338)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2182)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8093)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:676)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

**Comment by alectogeek** [comment]
what version did you upgrade from?
I want to downgrade the package and quickly send a hotfix of my app but don't know which version didn't have this problem

**Comment by fpasalioglu** [comment]
This was the version that worked fine: firebase_auth: 3.4.2

> what version did you upgrade from? I want to downgrade the package and quickly send a hotfix of my app but don't know which version didn't have this problem

**Comment by alectogeek** [comment]
> This was the version that worked fine: firebase_auth: 3.4.2
> 
> > what version did you upgrade from? I want to downgrade the package and quickly send a hotfix of my app but don't know which version didn't have this problem

well, I get a build error with the version 3.4.2:
```
../../../.pub-cache/hosted/pub.dartlang.org/firebase_auth-3.4.2/lib/src/recaptcha_verifier.dart:57:27: Error: Required named parameter 'auth' must be provided.
      _factory.delegateFor(
```

**Comment by fpasalioglu** [comment]
> > This was the version that worked fine: firebase_auth: 3.4.2
> > > what version did you upgrade from? I want to downgrade the package and quickly send a hotfix of my app but don't know which version didn't have this problem
> 
> well, I get a build error with the version 3.4.2:
> 
> ```
> ../../../.pub-cache/hosted/pub.dartlang.org/firebase_auth-3.4.2/lib/src/recaptcha_verifier.dart:57:27: Error: Required named parameter 'auth' must be provided.
>       _factory.delegateFor(
> ```

I'm pretty sure I was using this version. I don't know what is this error. Try flutter clean.

**Comment by darshankawar** [comment]
> at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$MultiFactorUserHostApi.setup(GeneratedAndroidFirebaseAuth.java:358)
>        at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$MultiFactorUserHostApi$-CC.setup(GeneratedAndroidFirebaseAuth.java:3)
>        at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.onDetachedFromEngine(FlutterFirebaseAuthPlugin.java:131)

Looking at these logs, it seems to be coming from https://github.com/firebase/flutterfire/blob/f2d791a713124163493c645cb6017b515f4140cd/packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/GeneratedAndroidFirebaseAuth.java#L350

Wherein, `binaryMessenger` is `null`

The `GeneratedAndroidFirebaseAuth$MultiFactorUserHostApi.setup` is coming from `GeneratedAndroidFirebaseAuth.MultiFactorUserHostApi.setup(null, this);` 

https://github.com/firebase/flutterfire/blob/f2d791a713124163493c645cb6017b515f4140cd/packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java#L131

**Comment by darshankawar** [comment]
Another report of same error : https://github.com/firebase/flutterfire/issues/9193 and a possible workaround until the issue is fixed: https://github.com/firebase/flutterfire/issues/9193#issuecomment-1193741513

**Comment by Lyokone** [comment]
Hello, thanks for the report, it's should be fixed by #9218
I'll post when deployed

**Comment by alectogeek** [comment]
> Hello, thanks for the report, it's should be fixed by #9218 I'll post when deployed

Thanks!

**Comment by alectogeek** [comment]
So the crash was caused by closing the app when a user clicks the back button from the home screen, right?
So it couldn't affect the user experience much, could it?

**Comment by fpasalioglu** [comment]
> Hello, thanks for the report, it's should be fixed by #9218 I'll post when deployed

Thanks!

**Comment by marcellocamara** [comment]
> So the crash was caused by closing the app when a user clicks the back button from the home screen, right? So it couldn't affect the user experience much, could it?

The crash report is, on my dash, 100% background. So, I don't think it will affect the UX.

Thanks, @Lyokone 
I will wait for the new release version with the fix 👍🏻

**Comment by timobaehr** [comment]
It does, Android makes alerts:
![photo_2022-07-26 19 57 57](https://user-images.githubusercontent.com/13302336/181078009-388bbe60-535c-4b1d-88a0-d05b216659aa.jpeg)
