### ISSUE TITLE
🐛 [firebase_auth] Previous auth state lost after `firebase_auth: ^3.6.0`

### ISSUE THREAD

**Issue by OutdatedGuy** [firebase/flutterfire#9243]
## Bug report

**Describe the bug**
After [PR 9138](https://github.com/firebase/flutterfire/pull/9138) fixed the issue of auth persistence in web, a new problem has occurred.

Previously, auth data was stored in browser's `IndexedDB` but it is now stored in the `Local Storage`. Hence after upgrading the package the previous auth state is lost due to change in storage location.

This is a **HUGE** deal breaker for apps which rely on `Anonymous` auth (i.e. something like guest mode) as data which depended on the previous auth will be lost.

### Expected behavior

Previous auth state before package upgrade shouldn't be lost.

### Sample project

Github: https://github.com/OutdatedGuy/Whats-That-Anime
Guest Mode App Example: https://whats-that-anime.outdatedguy.rocks/

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22622.436], locale en-IN)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.69.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.6
Flutter SDK 3.0.5
whats_that_anime 2.1.0+4

dependencies:
- cached_network_image 3.2.1 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- chewie 1.3.4 [cupertino_icons flutter provider video_player wakelock]
- cloud_firestore 3.4.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.5
- desktop_drop 0.3.3 [flutter flutter_web_plugins cross_file]
- dotted_border 2.0.0+2 [flutter path_drawing]
- firebase_auth 3.6.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.20.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 10.3.3 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_easyloading 3.0.5 [flutter flutter_spinkit]
- flutter_native_splash 2.2.5 [args flutter flutter_web_plugins image js lint meta path universal_io xml yaml]
- get_storage 2.0.3 [flutter get path_provider]
- http 0.13.4 [async http_parser meta path]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- internet_connection_checker_plus 1.0.1 [flutter http]
- motion_toast 2.3.0 [flutter]
- package_info_plus 1.4.3 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- paginate_firestore 1.0.3 [flutter bloc flutter_bloc cloud_firestore provider]
- pasteboard 0.2.0 [flutter flutter_web_plugins js]
- url_launcher 6.1.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- video_player 2.4.5 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]

dev dependencies:
- change_app_package_name 1.1.0
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- icons_launcher 1.2.1 [args image path universal_io yaml]

transitive dependencies:
- archive 3.3.1 [crypto path]
- args 2.3.1
- async 2.8.2 [collection meta]
- bloc 7.2.1 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 5.7.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.0 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- fake_async 1.3.0 [clock collection]
- ffi 2.0.1
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 6.4.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 4.1.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]      
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.12 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.3.1 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]      
- flutter_bloc 7.3.3 [flutter bloc provider]
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_spinkit 5.1.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- get 4.6.5 [flutter]
- html 0.15.0 [csslib source_span]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image 3.2.0 [archive meta xml]
- image_picker_android 0.8.5+1 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.5+6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.5.0 [cross_file flutter http plugin_platform_interface]
- intl 0.17.0 [clock path]
- js 0.6.4
- lint 1.8.2
- lints 2.0.0
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- nested 1.0.0 [flutter]
- octo_image 1.0.2 [flutter flutter_blurhash]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 2.0.0 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.1
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.16 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.10 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.0 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- provider 6.0.3 [collection flutter nested]
- rxdart 0.27.5
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- sqflite 2.0.3 [flutter sqflite_common path]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0+2
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.12 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- video_player_android 2.3.8 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.5 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.3 [flutter plugin_platform_interface]
- video_player_web 2.0.12 [flutter flutter_web_plugins video_player_platform_interface]
- wakelock 0.6.2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- win32 2.7.0 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by Lyokone** [comment]
Hey, thanks a lot for the report, it should be fixed by #9247

**Comment by kaumudpa** [comment]
It is not fixed.

**Comment by Lyokone** [comment]
@kaumudpa it's not deployed yet

**Comment by kaumudpa** [comment]
Nope! I am sorry but there is another problem with the auth state in web since `firebase_auth: 3.5.0` - If browser page is refresh/reloaded after the initial authentication of a user sends out `unauthorised` while trying to access firestore.

**Comment by deepak786** [comment]
@Lyokone I have the following error with `firebase_auth: 3.6.0`

```
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.


    at Object.createErrorWithStack (http://localhost:64794/dart_sdk.js:5093:12)
    at Error._throw (http://localhost:64794/dart_sdk.js:20399:18)
    at Error.throwWithStackTrace (http://localhost:64794/dart_sdk.js:20396:18)
    at async._AsyncCallbackEntry.new.callback (http://localhost:64794/dart_sdk.js:40921:18)
    at Object._microtaskLoop (http://localhost:64794/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:64794/dart_sdk.js:40784:13)
    at http://localhost:64794/dart_sdk.js:36261:9
```

Will this PR https://github.com/firebase/flutterfire/pull/9247 resolved the above issue?

**Comment by cruftmonger** [comment]
> 

Deployed? Wasn't the problem in `firebase_auth < 3.6.* `?

**Comment by Lyokone** [comment]
@OutdatedGuy It should be fixed with 3.6.1

**Comment by OutdatedGuy** [comment]
@Lyokone, thanks for the update. But I have one doubt about [PR 9247](https://github.com/firebase/flutterfire/pull/9247)

This PR introduces a new enum value `Persistence.INDEXED_DB` to store the auth state in browser's `IndexedDB`.
However, the [official firebase docs](https://firebase.google.com/docs/reference/js/auth.persistence) states that:
> 'LOCAL' is used for long term persistence such as `localStorage` or `IndexedDB`.

Also, from [this answer on stackoverflow](https://stackoverflow.com/a/51029091), we understand that when `Persistence.LOCAL` is used, `IndexedDB` is given priority to be used, but if not available then `Local Storage` will be used.
> Firebase Auth used to rely on `localStorage` but the latest version uses more reliable `indexedDB` to persist the user state. When this is not available, it falls back to `localStorage`.

So is there a need for this new enum value?

**Comment by Lyokone** [comment]
@OutdatedGuy, the new enum is mapping the full Persistence enum of the underlying JS SDK. If you don't set any persistence value, it will be the default of the JS SDK which is IndexedDB

**Comment by MatthewPatience** [comment]
Confirmed that this has resolved the issue for me with today's release of `3.6.1`.

**Comment by OutdatedGuy** [comment]
Hey @Lyokone thanks for the explanation, I understand the mapping, but doesn't the `JS` public usage for Persistence only contains 3 values? [Here](https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/model/public_types.ts#L324-L332)

I think the `IndexedDB` mapping should be done internally instead of have a Public enum value. Just to keep consistency between APIs between js and dart.

Please correct me If I'm missing something

**Comment by OutdatedGuy** [comment]
Never mind, the v9 JS SDK has complete changes and the docs are not well provided. New enum is necessary to be compatible with v9 JS `setPersistence` method. Thanks @Lyokone
