### ISSUE TITLE
🐛 [firebase_messaging] Firebase report a lot of crash by FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate

### ISSUE THREAD

**Issue by windows7lake** [firebase/flutterfire#9244]
## Bug report

After I upgrade firebase_messaging to a new version, a lot of crash was reported.
```
Fatal Exception: android.os.BadParcelableException: Parcelable protocol requires subclassing from Parcelable on class com.google.firebase.messaging.T
       at android.os.Parcel.readParcelableCreator(Parcel.java:3357)
       at android.os.Parcel.readParcelable(Parcel.java:3288)
       at android.os.Parcel.readValue(Parcel.java:3190)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3583)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:296)
       at android.os.BaseBundle.unparcel(BaseBundle.java:240)
       at android.os.Bundle.getParcelable(Bundle.java:1001)
       at android.content.Intent.getParcelableExtra(Intent.java:8307)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate(FlutterFirebaseMessagingBackgroundExecutor.java:232)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.lambda$onHandleWork$0(FlutterFirebaseMessagingBackgroundService.java:146)
       at io.flutter.plugins.firebase.messaging.-$$Lambda$FlutterFirebaseMessagingBackgroundService$MMnhHFRTKULlQAZ4ruNMt0KzQOI.run(lambda:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:263)
       at android.app.ActivityThread.main(ActivityThread.java:8283)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

### Steps to reproduce

No yield reproduce by myself, I receive it  from firebase console.

## Additional context

old version (it works well)
```
  firebase_core: 1.13.1
  firebase_analytics: 9.1.2
  firebase_crashlytics: 2.5.3
  firebase_messaging: 11.2.11
```

new version 
```
  firebase_core: 1.19.1
  firebase_analytics: 9.1.12
  firebase_crashlytics: 2.8.4
  firebase_messaging: 11.4.4
```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
 flutter pub deps -- --style=compact
Dart SDK 2.17.3
Flutter SDK 3.0.2
flutter100 5.8.5+228

dependencies:
- ad_cache 0.0.1 [flutter sqflite shared_preferences]
- ad_extension 0.0.1 [flutter intl crypto convert]
- ad_global 0.0.1 [flutter device_info_plus package_info_plus crypto url_launcher screenshot_callback flutter_keychain]
- ad_mvc 0.0.1 [flutter provider flutter_easyloading flutter_easyrefresh ad_route ad_network]
- ad_network 0.0.1 [flutter dio]
- ad_route 0.0.1 [flutter]
- ad_widget 0.0.1 [flutter provider flutter_easyrefresh flutter_easyloading]
- android_intent_plus 3.1.1 [flutter platform meta]
- appear 0.0.1 [flutter]
- apple_sign_in_safety 0.0.6 [flutter]
- auto_orientation 2.2.1 [flutter]
- cached_network_image 3.2.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- connectivity_plus 2.2.1 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- cupertino_icons 1.0.4
- device_info_plus 3.2.2 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- expandable 5.0.1 [flutter]
- expandable_text 2.3.0 [flutter]
- extended_image 6.2.1 [extended_image_library flutter meta]
- facebook_app_events 0.15.0 [flutter]
- firebase_analytics 9.1.12 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 1.19.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.8.4 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 11.4.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.8.1+1 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_applinks 0.0.1 [flutter]
- flutter_ble_near 0.0.1 [flutter]
- flutter_group_data 0.0.1 [flutter]
- flutter_html 2.1.2 [html csslib flutter_layout_grid video_player chewie webview_flutter chewie_audio flutter_svg flutter_math_fork collection numerus wakelock flutter]
- flutter_im 0.0.1 [flutter dio web_socket_channel crypto]
- flutter_local_notifications 9.6.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_login_facebook 1.4.1 [flutter list_ext]
- flutter_luban 0.1.13 [flutter image]
- flutter_native_image 0.0.6+1 [flutter]
- flutter_open_setting 0.0.2 [flutter]
- flutter_push_badge 0.0.1 [flutter]
- flutter_screenutil 5.3.1 [flutter]
- flutter_swiper 1.1.6 [flutter transformer_page_view flutter_page_indicator]
- flutter_swiper_null_safety 1.0.2 [flutter]
- fluttershare 0.0.2 [flutter]
- gallery_saver 2.3.2 [flutter path_provider http path]
- geocoding 2.0.4 [flutter geocoding_platform_interface]
- geolocator 8.2.1 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- google_sign_in 5.3.3 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- image_cropper 1.4.1 [flutter]
- image_picker 0.8.5+2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- jpush_flutter 2.1.4 [platform flutter]
- launch_review 3.0.1 [flutter]
- path 1.8.1
- path_provider 2.0.9 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- permission_handler 9.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- qr_code_scanner 0.7.0 [js flutter flutter_web_plugins]
- qr_flutter 4.0.0 [flutter qr]
- sensors_plus 1.1.0 [flutter sensors_plus_web sensors_plus_platform_interface]
- shimmer 2.0.0 [flutter]
- solid_bottom_sheet 0.1.10 [flutter]
- synchronized 3.0.0+2
- umeng_common_sdk 1.2.4 [flutter]
- url_launcher 6.0.20 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- voo 0.0.1 [flutter flutter_screenutil]
- waterfall_flow 3.0.2 [collection extended_list_library flutter]
- webview_flutter 3.0.0 [flutter webview_flutter_android webview_flutter_wkwebview]
- youtube_player_flutter 8.0.0 [flutter flutter_inappwebview]

dev dependencies:
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver archive async boolean_selector characters charcode clock collection crypto matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- test 1.21.1 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

dependency overrides:
- crypto 3.0.2 [typed_data]
- device_info_plus 3.2.2 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- dio 4.0.6 [http_parser path]
- permission_handler 9.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- url_launcher 6.0.20 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- webview_flutter 3.0.0 [flutter webview_flutter_android webview_flutter_wkwebview]

transitive dependencies:
- _fe_analyzer_shared 43.0.0 [meta]
- analyzer 4.3.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.1.11 [crypto path]
- args 2.3.1
- asn1lib 1.1.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- chewie 1.1.0 [cupertino_icons flutter video_player wakelock]
- chewie_audio 1.3.0 [cupertino_icons flutter video_player]
- clock 1.1.0
- collection 1.16.0
- connectivity_plus_linux 1.3.1 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.4 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.1 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.3 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.2 [connectivity_plus_platform_interface flutter]
- convert 3.0.1 [typed_data]
- coverage 1.2.0 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.3+1 [js meta]
- csslib 0.17.2 [source_span]
- dbus 0.7.3 [args ffi meta xml]
- device_info_plus_linux 2.1.1 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 2.2.3 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 2.3.0+1 [flutter meta plugin_platform_interface]
- device_info_plus_web 2.1.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 2.1.1 [device_info_plus_platform_interface ffi flutter win32]
- extended_image_library 3.3.0 [crypto flutter http_client_helper path path_provider]
- extended_list_library 3.0.0 [flutter]
- fake_async 1.3.0 [clock collection]
- ffi 1.2.1
- file 6.1.2 [meta path]
- firebase 9.0.3 [http http_parser js]
- firebase_analytics_platform_interface 3.3.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.2 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.12 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.5.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.4.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance_platform_interface 0.1.1+12 [firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.1+1 [firebase firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_easyloading 3.0.3 [flutter flutter_spinkit]
- flutter_easyrefresh 2.2.1 [flutter]
- flutter_inappwebview 5.4.3+7 [flutter]
- flutter_keychain 2.0.1 [flutter]
- flutter_layout_grid 1.0.6 [flutter collection meta quiver]
- flutter_local_notifications_linux 0.5.0+1 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_math_fork 0.5.0 [flutter flutter_svg provider meta collection tuple]
- flutter_page_indicator 0.0.3 [flutter]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_spinkit 5.1.0 [flutter]
- flutter_svg 0.23.0+1 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 2.1.3 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- geocoding_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- geolocator_android 3.2.1 [flutter geolocator_platform_interface]
- geolocator_apple 2.2.1 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.6 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.6 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.1 [flutter geolocator_platform_interface]
- glob 2.1.0 [async collection file path string_scanner]
- google_sign_in_android 5.2.8 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.4.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.2.0 [flutter quiver]
- google_sign_in_web 0.10.2 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- html 0.15.0 [csslib source_span]
- http 0.13.4 [async http_parser meta path]
- http_client_helper 2.0.3 [http]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image 3.1.3 [archive meta xml]
- image_picker_android 0.8.5+1 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.5+6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.5.0 [cross_file flutter http plugin_platform_interface]
- intl 0.17.0 [clock path]
- io 1.0.3 [meta path string_scanner]
- js 0.6.4
- list_ext 1.0.4 [quiver collection]
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- mime 1.0.2
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- node_preamble 2.0.1
- numerus 1.1.1
- octo_image 1.0.2 [flutter flutter_blurhash]
- package_config 2.1.0 [path]
- package_info_plus 1.3.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.5 [package_info_plus_platform_interface ffi flutter win32]
- path_drawing 0.5.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_android 2.0.16 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.10 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.7 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_android 9.0.2+1 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.0 [flutter permission_handler_platform_interface]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pointycastle 3.6.1 [collection convert js]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- provider 6.0.1 [collection flutter nested]
- pub_semver 2.1.1 [collection meta]
- qr 2.1.0 [meta]
- quiver 3.1.0 [matcher]
- rxdart 0.27.5
- screenshot_callback 1.1.1 [flutter permission_handler]
- sensors_plus_platform_interface 1.1.1 [flutter meta plugin_platform_interface]
- sensors_plus_web 1.1.1 [flutter sensors_plus_platform_interface flutter_web_plugins]
- shared_preferences 2.0.8 [flutter meta shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.3.1 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.1 [path shelf shelf_static]
- shelf_static 1.1.1 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.2 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.2 [collection path term_glyph]
- sqflite 2.0.0+4 [flutter sqflite_common path]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- sync_http 0.3.0
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.13 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timezone 0.8.0 [path]
- transformer_page_view 0.1.6 [flutter]
- tuple 2.0.0 [quiver]
- typed_data 1.3.0 [collection]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.12 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- video_player 2.4.5 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.3.8 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.5 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.3 [flutter plugin_platform_interface]
- video_player_web 2.0.12 [flutter flutter_web_plugins video_player_platform_interface]
- vm_service 8.2.2
- wakelock 0.5.3+3 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.1.0+3 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.1+3 [flutter meta]
- wakelock_web 0.2.0+3 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.1.0+2 [flutter wakelock_platform_interface win32]
- watcher 1.0.1 [async path]
- web_socket_channel 2.2.0 [async crypto stream_channel]
- webdriver 3.0.0 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.1.0 [logging]
- webview_flutter_android 2.8.0 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.8.0 [flutter plugin_platform_interface]
- webview_flutter_wkwebview 2.7.1 [flutter webview_flutter_platform_interface]
- win32 2.6.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.4.1 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
> new version
> 
> ```
>   firebase_core: 1.19.1
>   firebase_analytics: 9.1.12
>   firebase_crashlytics: 2.8.4
>   firebase_messaging: 11.4.4
> ```

@windows7lake Can you again try to upgrade all plugins to their latest versions and see if you still get same crash ?

```
firebase_core: ^1.20.0
firebase_analytics: ^9.3.0
firebase_crashlytics: ^2.8.6
firebase_messaging: ^12.0.1
```

**Comment by windows7lake** [comment]
Yeah, I will try.

**Comment by windows7lake** [comment]
```
  firebase_core: 1.20.0
  firebase_analytics: 9.3.0
  firebase_crashlytics: 2.8.6
  firebase_messaging: 12.0.1
  firebase_performance: 0.8.2+1
```
After upgrade all plugin, I also get same crash.

**Comment by darshankawar** [comment]
Thanks for the update. Keeping this issue open and labeling for further insights from the team, as this is coming from crashlytics and there doesn't seem to be concrete steps to replicate or code sample.

Similar issue was raised but was closed when OP said they don't see the error anymore in the crashlytics: https://github.com/firebase/flutterfire/issues/8134. Another instance of same crash: https://github.com/firebase/flutterfire/issues/7443

**Comment by ljmatan** [comment]
Hey @darshankawar replicable steps are:

1. Implement FCM to Flutter (code examples can be found [here](https://pub.dev/packages/firebase_messaging).
2. App is in background, notification arrives, user clicks on notification.

**Comment by windows7lake** [comment]
I also reproduce with above steps. @darshankawar，a lot of crash was report everyday，pls fixed it. Thanks!

**Comment by darshankawar** [comment]
@windows7lake 
I am unable to replicate this on Android Samsung S10 device. Can you try using latest plugin version ? https://github.com/firebase/flutterfire/issues/9244

Note: please be aware of https://github.com/firebase/flutterfire/issues/9430 while you verify on latest version.
