### ISSUE TITLE
🐛 [core-web] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

### ISSUE THREAD

**Issue by Ahmadre** [firebase/flutterfire#9269]
## Bug report

**Describe the bug**
Under no versions of firebase_web I am able to run my app on Flutter Web (3.0.5).

I am struggling since one month with this an trying all kind of versions...

firebase_core: 1.20.0
firebase_core_platform_interface: 4.5.0
firebase_core_web: 1.7.1

---

## Bug

```bash
Error: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
    at Object.throw_ [as throw] (http://localhost:42765/dart_sdk.js:5405:11)
at firebase_core_web.FirebaseCoreWeb.new.app (http://localhost:42765/packages/firebase_core_web/firebase_core_web.dart.lib.js:272:23)
at Firebase.app (http://localhost:42765/packages/firebase_core/firebase_core.dart.lib.js:119:50)
at get instance [as instance] (http://localhost:42765/packages/firebase_auth/firebase_auth.dart.lib.js:100:55)
at init (http://localhost:42765/packages/app/app/services/firebase_service.dart.lib.js:264:44)
    at init.next (<anonymous>)
    at http://localhost:42765/dart_sdk.js:43063:33
    at _RootZone.runUnary (http://localhost:42765/dart_sdk.js:42919:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:42765/dart_sdk.js:37493:29)
    at handleValueCallback (http://localhost:42765/dart_sdk.js:38088:49)
    at _Future._propagateToListeners (http://localhost:42765/dart_sdk.js:38126:17)
    at [_completeWithValue] (http://localhost:42765/dart_sdk.js:37955:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:42765/dart_sdk.js:37991:35)
    at Object._microtaskLoop (http://localhost:42765/dart_sdk.js:43223:13)
    at _startMicrotaskLoop (http://localhost:42765/dart_sdk.js:43229:13)
    at http://localhost:42765/dart_sdk.js:38359:9
```

## Additional Context

This issue was posted several times and yes I cleared my Pub-Cache locally and re-cloned my repository several times!

I also tried lower versions, but with no versions I am able to run web.

## Firebase Init

```dart
if (Firebase.apps.isEmpty) {
  await Firebase.initializeApp(
    name: ”MY-APP",
    options: DefaultFirebaseOptions.currentPlatform,
  );
}
```

I didn't change any of DefaultFirebaseOptions and yes I am targeting the correct flavor! 

App is working for mobile! But not for web!

**Comment by Ahmadre** [comment]
![Bildschirmfoto 2022-07-30 um 02 01 24](https://user-images.githubusercontent.com/18512224/181861871-9ccfbe90-4f0c-4b49-bf55-0d8b39fce8d9.png)

**Comment by Ahmadre** [comment]
![Bildschirmfoto 2022-07-30 um 02 02 32](https://user-images.githubusercontent.com/18512224/181861903-028b45ac-30b9-47e6-b729-1cb01aa73dea.png)

**Comment by Ahmadre** [comment]
![Bildschirmfoto 2022-07-30 um 02 02 51](https://user-images.githubusercontent.com/18512224/181861917-da54dd08-c5de-4400-b993-fb5c92ed908a.png)

**Comment by Ahmadre** [comment]
I switched to manual installation and it works directly.... (https://firebase.flutter.dev/docs/manual-installation/web)

**Comment by darshankawar** [comment]
@Ahmadre 
There's similar issue open describing same case: https://github.com/firebase/flutterfire/issues/9256. According to [this](https://github.com/firebase/flutterfire/issues/9256#issuecomment-1198876909) comment from Flutterfire team member, it works using latest version on web. Can you try the same and confirm ?

Also, I suggest you to try the `firebase_core` or `firebase_auth` plugin example and see if it works for you. I reckon, the issue could be related to some mis-config at your end.

Also, let's track this issue in the linked one. Closing this as a duplicate.

**Comment by siisee11** [comment]
Exactly same error here with ` firebase_core: ^1.21.0`

**Comment by darshankawar** [comment]
I tried to replicate this error but have been unable to trigger as mentioned per my verification [here](https://github.com/firebase/flutterfire/issues/9400#issuecomment-1225333347).

@siisee11 Can you try the same as mentioned above and see if you still get same error or not ?
