### ISSUE TITLE
🐛 [firebase_app_installations] Adding library in pubspec.yaml causes an Unhandled Exception when Firebase.initializeApp() is called

### ISSUE THREAD

**Issue by adgeg** [firebase/flutterfire#9286]
## Bug report

Using together previous versions of `firebase_core` with `firebase_app_installations` cause an Exception when calling `Firebase.initializeApp()`. Even when I dont use any method of `firebase_app_installations`.

It is fixed when I upgrade version of `firebase_core` to `1.20.0` and `firebase_app_installations` to `0.1.1+3`, but it forces to update iOS minimum version. And I don't want to lose some of our customers.
 

### Steps to reproduce

1. Properly add `google-services.json` file in your project.
2. In `pubspec.yaml`, add `firebase_core: '1.16.0'` and `firebase_app_installations: '0.1.0'`
3. In `main.dart`, add the following method: 
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
}
```

4. The following exception occurs:
```
E/flutter ( 8250): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
E/flutter ( 8250): #0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:193:5)
E/flutter ( 8250): #1      Firebase.app (package:firebase_core/src/firebase.dart:53:41)
E/flutter ( 8250): #2      FirebaseCrashlytics.instance (package:firebase_crashlytics/src/firebase_crashlytics.dart:33:55)
E/flutter ( 8250): #3      main.<anonymous closure> (package:pass_emploi_app/main.dart:13:44)
E/flutter ( 8250): #4      _rootRunBinary (dart:async/zone.dart:1450:47)
E/flutter ( 8250): #5      _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter ( 8250): #6      runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1832:18)
E/flutter ( 8250): #7      _Zone._processUncaughtError (dart:async/zone.dart:1109:14)
E/flutter ( 8250): #8      _CustomZone.handleUncaughtError (dart:async/zone.dart:1312:5)
E/flutter ( 8250): #9      Future._propagateToListeners (dart:async/future_impl.dart:680:16)
E/flutter ( 8250): #10     Future._completeError (dart:async/future_impl.dart:574:5)
E/flutter ( 8250): #11     _completeOnAsyncError (dart:async-patch/async_patch.dart:287:13)
E/flutter ( 8250): #12     main.<anonymous closure> (package:pass_emploi_app/main.dart)
E/flutter ( 8250): <asynchronous suspension>
E/flutter ( 8250): 
```

### Expected behavior

`Firebase.initializeApp();` should still works properly.

## Additional context

Finally, we use this other library `flutterfire_installations` in version `'0.1.0'`. It works perfectlly fine even with `firebase_core: '1.16.0'`, which allow us to keep all of our iOS users, even with old iOS versions. 

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale fr-FR)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.1
Flutter SDK 3.0.1
pass_emploi_app 1.8.1

dependencies:
- cloud_firestore 3.1.14 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- collection 1.16.0
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- equatable 2.0.3 [collection meta]
- firebase_app_installations 0.1.0 [firebase_app_installations_platform_interface firebase_app_installations_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.3.17 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.16.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.7.2 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 11.3.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 2.0.6 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_appauth 2.4.1+1 [flutter flutter_appauth_platform_interface]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_dotenv 5.0.2 [flutter]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_local_notifications 9.5.0 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_redux 0.10.0 [redux flutter]
- flutter_secure_storage 5.0.2 [meta flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- google_fonts 2.3.2 [flutter http path_provider crypto]
- http 0.13.4 [async http_parser meta path]
- http_interceptor 1.0.2 [http]
- intl 0.17.0 [clock path]
- logger 1.1.0
- matomo 1.1.0 [flutter fk_user_agent http uuid package_info_plus shared_preferences logging universal_html]
- open_file 3.2.1 [flutter ffi]
- package_info 2.0.2 [flutter]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- share_plus 4.0.4 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- smooth_page_indicator 1.0.0+2 [flutter]
- synchronized 3.0.0+2
- url_launcher 6.1.0 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.6 [crypto]

dev dependencies:
- dart_code_metrics 4.15.0 [analyzer analyzer_plugin ansicolor args collection crypto file glob html meta path source_span xml yaml]
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _fe_analyzer_shared 36.0.0 [meta]
- analyzer 3.3.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- analyzer_plugin 0.9.0 [analyzer collection dart_style pub_semver yaml]
- ansicolor 2.0.1
- args 2.3.0
- asn1lib 1.1.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 5.5.5 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.14 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- convert 3.0.1 [typed_data]
- crypto 3.0.2 [typed_data]
- csslib 0.17.1 [source_span]
- dart_style 2.2.3 [analyzer args path pub_semver source_span]
- dbus 0.7.3 [args ffi meta xml]
- fake_async 1.3.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_app_installations_platform_interface 0.1.1+12 [firebase_core flutter meta plugin_platform_interface]
- firebase_app_installations_web 0.1.1+1 [firebase_app_installations_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.2.5 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.14 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.5 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.4.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.3.0 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config_platform_interface 1.1.5 [firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.0.11 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- fk_user_agent 2.1.0 [flutter]
- flutter_appauth_platform_interface 4.1.0 [flutter plugin_platform_interface]
- flutter_local_notifications_linux 0.4.2 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_secure_storage_linux 1.1.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 1.1.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.0 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.0.2 [flutter flutter_web_plugins flutter_secure_storage_platform_interface js]
- flutter_secure_storage_windows 1.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- glob 2.0.2 [async collection file path string_scanner]
- html 0.15.0 [csslib source_span]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- js 0.6.4
- linkify 4.1.0
- lints 1.0.1
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- mime 1.0.2
- package_config 2.0.2 [path]
- package_info_plus 1.4.2 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.5 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.1
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider_android 2.0.13 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pointycastle 3.6.0 [collection convert js]
- process 4.2.4 [file path platform]
- pub_semver 2.1.1 [collection meta]
- redux 5.0.0
- rxdart 0.27.3
- share_plus_linux 3.0.0 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 3.0.1 [share_plus_platform_interface flutter]
- share_plus_platform_interface 3.0.3 [flutter meta mime plugin_platform_interface]
- share_plus_web 3.0.0 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 3.0.0 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences 2.0.13 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.0.11 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.0 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.3 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- sqflite 2.0.2+1 [flutter sqflite_common path]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- typed_data 1.3.0 [collection]
- universal_html 2.0.8 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_android 6.0.16 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.9 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.0 [flutter url_launcher_platform_interface]
- vector_math 2.1.2
- watcher 1.0.1 [async path]
- win32 2.5.2 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]

```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @adgeg 
I am unable to replicate the error after adding said plugin versions. 



> It is fixed when I upgrade version of `firebase_core` to `1.20.0` and `firebase_app_installations` to `0.1.1+3`

This seems to be correct way of going ahead as one would like to be on latest versions of plugins as they fix underlying issues and also to get most up-to-date features offered by them.

I also suggest you to use dart only initialization that FlutterFire CLI offers, that now supports writing the Google config files for your native platforms. 

You may do that by running `dart pub global activate flutterfire_cli` first.

Once you do above, you can initialize firebase app as below and see if you still get same error or not.

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(MyApp());
}
```

**Comment by adgeg** [comment]
Thanks for your quick answer @darshankawar :)

According to the Dart only initialization, it requires some effort to do it locally (as we have many flavors) and in our CI. So I'll postpone it to later. As everything works as expected with `flutterfire_installations` library, I won't try to use `firebase_app_installations` anymore. Even if its not clear for me why there are 2 libs provided by  `https://pub.dev/publishers/firebase.google.com` for the same purpose.

**Comment by darshankawar** [comment]
`flutterfire_installations` is actually not developed or maintained by FlutterFire team. The original plugin is https://pub.dev/packages/firebase_app_installations.  Not sure about the latter though :)

**Comment by adgeg** [comment]
Hum… It's strange as it is mentioned [here](https://pub.dev/packages/flutterfire_installations) as published by verified Firebase Google team. I don't talk of this other [lib](https://pub.dev/packages/firebase_installations) which is clearly not official.
