### ISSUE TITLE
🐛 [firebase_functions] HandshakeException: Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:359)) 

### ISSUE THREAD

**Issue by kinex** [firebase/flutterfire#9302]
One of my users gets this exception:

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: [firebase_functions/unavailable] UNAVAILABLE

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167)
<asynchronous suspension>
#2      MethodChannelHttpsCallable.call (package:cloud_functions_platform_interface/src/method_channel/method_channel_https_callable.dart:23)
<asynchronous suspension>
#3      HttpsCallable.call (package:cloud_functions/src/https_callable.dart:49)
<asynchronous suspension>
. Error thrown handleSyncError/FirebaseFunctionsException.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:607)
       at MethodChannel._invokeMethod(platform_channel.dart:167)
       at MethodChannelHttpsCallable.call(method_channel_https_callable.dart:23)
       at HttpsCallable.call(https_callable.dart:49)
       at .callCloudFunction(cloud_functions.dart:28)

```

There is another exception from the same user which is probably the root cause:

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393)). Error thrown Instance of 'ErrorDescription'.
       at _RawSecureSocket._tryFilter(_RawSecureSocket.java)
```

Maybe related to https://github.com/dart-lang/http/issues/627, but this is not an old device or old OS version.

### Device

Galaxy S21 5G / Android 12 (en-AU)

### Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.1826], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.69.2)
[√] HTTP Host Availability

• No issues found!
```
---

### Flutter dependencies

cloud_functions: ^3.3.3

**Comment by kinex** [comment]
The issue was caused by VPN (a company managed phone).
