### ISSUE TITLE
🐛 [firebase_core] Firebase cannot establish a connection when working with **multi-window** on macOS

### ISSUE THREAD

**Issue by GroovinChip** [firebase/flutterfire#9310]
When working with Firebase, Flutter desktop ( macOS specifically), and the [desktop_multi_window](https://pub.dev/packages/desktop_multi_window) plugin, Firebase will throw a `PlatformException` with the following logs when creating and showing a new window:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:199:7)
<asynchronous suspension>
#1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
<asynchronous suspension>
#2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
<asynchronous suspension>
#3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:40:31)
<asynchronous suspension>
#4      main (package:fulcrum/main.dart:18:3)
<asynchronous suspension>
```

I suspect that this problem has something to do with the nature of multi-window at this time, which works by creating a whole new instance of the Flutter engine for the new window; specifically, I suspect that Firebase has no connection with this new instance of the engine, and therefore cannot initialize because the platform channels cannot reach the native libraries (or something).

I have attempted to utilize the `DesktopMultiWindow.setMethodHandler` and `DesktopMultiWindow.invokeMethod` functions (which seems to allow executing functions on the new engine instance) in the hopes that they would allow me to initialize Firebase on the new instance of the engine, but I have not been successful.

### Steps to reproduce

1. Set up a new Flutter app, create a widget that will be used as the content of a new window, and a button that will launch the new window
2. Set up a Firebase project that corresponds to your Flutter app
3. Add Firebase to your app, making sure to do so for macOS specifically
4. Add `desktop_multi_window` to your app 
5. Launch the second window and observe that Firebase will not be able to establish a connection and therefore no content will be shown in the second window

### Expected behavior

I expect that the already-initialized and connected Firebase app will be present when creating and showing a new window, which would mean that the `initializeApp` function will not run and therefore not fail, and that I can continue to use Firebase functionality in the new window.

### Sample project

Here are the relevant snippets from my code (which is not currently public):

#### main.dart
```dart
import 'package:collection/collection.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:fulcrum/app/app.dart';
import 'package:fulcrum/firebase_options.dart';
import 'package:fulcrum/services/auth_service.dart';
import 'package:fulcrum/services/favorites_service.dart';
import 'package:fulcrum/services/preferences_service.dart';
import 'package:fulcrum/views/preferences_window.dart';
import 'package:window_manager/window_manager.dart';

const minimumWindowSize = Size(600, 630);

Future<void> main(List<String> args) async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  final authService = await AuthService.init();
  final prefsService = await PreferencesService.init();
  final favoritesService = await FavoritesService.init(prefsService);
  await windowManager.ensureInitialized();

  WindowOptions windowOptions = const WindowOptions(
    minimumSize: minimumWindowSize,
  );
  windowManager.waitUntilReadyToShow(windowOptions, () async {
    await windowManager.show();
    await windowManager.focus();
  });

  if (args.firstOrNull == 'multi_window') {
    runApp(
      const PreferencesWindow(),
    );
  } else {
    runApp(
      FulcrumApp(
        authService: authService,
        favoritesService: favoritesService,
        prefsService: prefsService,
      ),
    );
  }
}
```

#### Creating and showing the second window:
```dart
final window = await DesktopMultiWindow.createWindow();
final rootPosition = await windowManager.getPosition();
window
  ..setFrame(
    rootPosition.translate(50, 200) & const Size(800, 400))
  ..setTitle('Preferences')
  ..resizable(false)
  ..show();
```

---

## Additional context

In macOS applications it is very common for application preferences to be managed in a separate window, which is what I'm trying to achieve, and is how I came across this bug.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2022.2)
[✓] VS Code (version 1.70.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.6
Flutter SDK 3.0.5
fulcrum 0.13.1+28

dependencies:
- bluejay 1.5.0 [flutter http]
- cloud_firestore 3.4.3 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- collection 1.16.0
- cupertino_icons 1.0.5
- desktop_multi_window 0.2.0 [flutter]
- firebase_auth 3.6.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.20.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_highlighter 0.1.1 [flutter highlighter]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_octicons 0.10.0 [flutter]
- github 9.4.0 [http http_parser json_annotation meta]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- http 0.13.5 [async http_parser meta path]
- intl 0.17.0 [clock path]
- macos_ui 1.7.1 [flutter]
- markdown_widget 1.2.9 [flutter markdown highlight flutter_highlight html video_player_web video_player scrollable_positioned_list]
- material_design_icons_flutter 5.0.6996 [flutter]
- oauth2 2.0.0 [collection crypto http http_parser]
- path 1.8.1
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- primer_flutter 1.0.0 [flutter]
- provider 6.0.3 [collection flutter nested]
- rxdart 0.27.5
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- simple_gql 2.0.0 [http meta]
- timeago_flutter 1.1.0 [timeago flutter]
- url_launcher 6.1.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- window_manager 0.2.5 [flutter path screen_retriever]
- window_to_front 0.0.3 [flutter]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- args 2.3.1
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 5.7.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.3 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- fake_async 1.3.0 [clock collection]
- ffi 2.0.1
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 6.5.2 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 4.2.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_highlight 0.7.0 [flutter highlight]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- highlight 0.7.0 [collection]
- highlighter 0.1.1 [collection]
- html 0.15.0 [csslib source_span]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- js 0.6.4
- json_annotation 4.6.0 [meta]
- linkify 4.1.0
- lints 2.0.0
- markdown 5.0.0 [args charcode meta]
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- nested 1.0.0 [flutter]
- path_provider_android 2.0.17 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.1 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- screen_retriever 0.1.2 [flutter]
- scrollable_positioned_list 0.3.2 [flutter collection]
- shared_preferences_android 2.0.12 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timeago 3.2.2
- typed_data 1.3.1 [collection]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.12 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.2
- video_player 2.4.5 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.3.8 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.5 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.3 [flutter plugin_platform_interface]
- video_player_web 2.0.12 [flutter flutter_web_plugins video_player_platform_interface]
- win32 2.7.0 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
```

</details>

---

**Comment by GroovinChip** [comment]
@wolfenrain, any thoughts on this issue?

(Wolf has worked on his own version of multi-window and may be able to provide some insight here)

Also CC'ing @pr-Mais, @nilsreichardt, and @Lyokone

**Comment by darshankawar** [comment]
Thanks for the detailed report @GroovinChip.
Can you try couple of below options and see if they help ?

1. Can you check if any of the community plugin you are using could be using an older version of firebase plugin ? Looking into `pubspec.lock` may give you an idea on this.

2. Try to register flutter engine, (something like mentioned [here](https://github.com/firebase/flutterfire/issues/9113#issuecomment-1188429009)).

**Comment by GroovinChip** [comment]
So it turns out that the problem here is that the `desktop_multi_window` plugin is [only registering itself](https://github.com/GroovinChip/flutter-plugins/blob/main/packages/desktop_multi_window/macos/Classes/FlutterWindow.swift#L77), and not any other plugins, on the new engine. I asked around, and it seems that the plugin will not be able to get a list of plugins from the main engine in order to register them on the new engine. 

Therefore, the solution seems to be to pass data between engine instances and perform functions requiring other plugins on the main instance. I have, with some help, been able to successfully set this up by: 
1. Utilizing the `DesktopMultiWindow.setMethodHandler` and `DesktopMultiWindow.invokeMethod` functions
2. Ensuring that Firebase will not try to reinitialize itself on the new engine instance using the following check at the top of the `main()` method in `main.dart` (prior to ensuring `WidgetsBinding` is initialized and initializing Firebase)
3. Abstracting out the preference-related operations to an interface that doesn't require any of the service classes & firebase functionality that the rest of the `main()` method sets up

```dart
if (args.firstOrNull == 'multi_window') {
  runApp(
    const PreferencesWindow(),
  );
  return; // This line is crucial - without it, the rest of main() will be run
}

WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
);

// Rest of main method: setting up service classes, window manager, and runApp
```

Since `args` will always be empty when the main instance starts up, and since new windows will always have an `args` with the first value being `multi_window`, the check works well.

While all this works, it's quite clunky and, in my opinion, hacky. In an ideal world, engine isolates spun up from the main isolate should be able to get and register all the plugins being used. I certainly hope that the Flutter team's implementation of multi-window, whenever they get around to it, is a better system than what's available to us now.

In any event, I think this issue can be closed because the problem is external and unrelated to FlutterFire.
