### ISSUE TITLE
🐛 [firebase_crashlytics] Unable to upload reports to Firebase

### ISSUE THREAD

**Issue by rasitayaz** [firebase/flutterfire#9352]
## Bug report

I'm trying to send crashlytics reports manually using `runZonedGuarded` and its `onError` function. I'm simply calling;

```
await FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
```
and crashlytics prints some information on the console:
```
I/flutter (16588): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (16588): **exception and stack trace**
I/flutter (16588): ----------------------------------------------------
I/TRuntime.CctTransportBackend(16588): Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
```

And after that, it tries to upload the report but this error shows up:

<details>
<summary>logs</summary><br/>

```
E/TRuntime.CctTransportBackend(16588): Couldn't open connection, returning with 500
E/TRuntime.CctTransportBackend(16588): java.net.ConnectException: Failed to connect to crashlyticsreports-pa.googleapis.com/127.0.0.1:443
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.cct.CctTransportBackend.doSend(CctTransportBackend.java:303)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.cct.CctTransportBackend.$r8$lambda$bLAzIpNF4NtapXlUpPVGhzxyNT8(Unknown Source:0)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.cct.CctTransportBackend$$ExternalSyntheticLambda0.apply(Unknown Source:4)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.runtime.retries.Retries.retry(Retries.java:54)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.cct.CctTransportBackend.send(CctTransportBackend.java:372)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.logAndUpdateState(Uploader.java:144)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.lambda$upload$1$com-google-android-datatransport-runtime-scheduling-jobscheduling-Uploader(Uploader.java:104)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader$$ExternalSyntheticLambda1.run(Unknown Source:8)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(SafeLoggingExecutor.java:47)
E/TRuntime.CctTransportBackend(16588): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/TRuntime.CctTransportBackend(16588): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/TRuntime.CctTransportBackend(16588): 	at java.lang.Thread.run(Thread.java:920)
I/TRuntime.CctTransportBackend(16588): Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
E/TRuntime.CctTransportBackend(16588): Couldn't encode request, returning with 400

E/TRuntime.CctTransportBackend(16588): java.net.SocketTimeoutException: failed to connect to crashlyticsreports-pa.googleapis.com/2a00:1450:4017:802::2003 (port 443) from /fec0::94e6:befb:5ad:1b96 (port 49326) after 30000ms
E/TRuntime.CctTransportBackend(16588): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:236)
E/TRuntime.CctTransportBackend(16588): 	at libcore.io.IoBridge.connect(IoBridge.java:180)
E/TRuntime.CctTransportBackend(16588): 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
E/TRuntime.CctTransportBackend(16588): 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
E/TRuntime.CctTransportBackend(16588): 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
E/TRuntime.CctTransportBackend(16588): 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
E/TRuntime.CctTransportBackend(16588): 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
E/TRuntime.CctTransportBackend(16588): 	at java.net.Socket.connect(Socket.java:621)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
E/TRuntime.CctTransportBackend(16588): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.cct.CctTransportBackend.doSend(CctTransportBackend.java:303)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.cct.CctTransportBackend.$r8$lambda$bLAzIpNF4NtapXlUpPVGhzxyNT8(Unknown Source:0)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.cct.CctTransportBackend$$ExternalSyntheticLambda0.apply(Unknown Source:4)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.runtime.retries.Retries.retry(Retries.java:54)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.cct.CctTransportBackend.send(CctTransportBackend.java:372)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.logAndUpdateState(Uploader.java:144)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.lambda$upload$1$com-google-android-datatransport-runtime-scheduling-jobscheduling-Uploader(Uploader.java:104)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader$$ExternalSyntheticLambda1.run(Unknown Source:8)
E/TRuntime.CctTransportBackend(16588): 	at com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(SafeLoggingExecutor.java:47)
E/TRuntime.CctTransportBackend(16588): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/TRuntime.CctTransportBackend(16588): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/TRuntime.CctTransportBackend(16588): 	at java.lang.Thread.run(Thread.java:920)
```

</details>

And from time to time, it shows the error below:

<details>
<summary>logs</summary><br/>

```
E/TRuntime.CctTransportBackend(17034): Couldn't encode request, returning with 400
E/TRuntime.CctTransportBackend(17034): java.net.SocketTimeoutException: failed to connect to crashlyticsreports-pa.googleapis.com/2a00:1450:4017:812::2003 (port 443) from /fec0::94ff:4a5f:5bde:f849 (port 34388) after 30000ms
E/TRuntime.CctTransportBackend(17034): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:236)
E/TRuntime.CctTransportBackend(17034): 	at libcore.io.IoBridge.connect(IoBridge.java:180)
E/TRuntime.CctTransportBackend(17034): 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
E/TRuntime.CctTransportBackend(17034): 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
E/TRuntime.CctTransportBackend(17034): 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
E/TRuntime.CctTransportBackend(17034): 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
E/TRuntime.CctTransportBackend(17034): 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
E/TRuntime.CctTransportBackend(17034): 	at java.net.Socket.connect(Socket.java:621)
E/TRuntime.CctTransportBackend(17034): 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
E/TRuntime.CctTransportBackend(17034): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
E/TRuntime.CctTransportBackend(17034): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
E/TRuntime.CctTransportBackend(17034): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
E/TRuntime.CctTransportBackend(17034): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
E/TRuntime.CctTransportBackend(17034): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
E/TRuntime.CctTransportBackend(17034): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
E/TRuntime.CctTransportBackend(17034): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
E/TRuntime.CctTransportBackend(17034): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
E/TRuntime.CctTransportBackend(17034): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/TRuntime.CctTransportBackend(17034): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
E/TRuntime.CctTransportBackend(17034): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
E/TRuntime.CctTransportBackend(17034): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
E/TRuntime.CctTransportBackend(17034): 	at com.google.android.datatransport.cct.CctTransportBackend.doSend(CctTransportBackend.java:303)
E/TRuntime.CctTransportBackend(17034): 	at com.google.android.datatransport.cct.CctTransportBackend.$r8$lambda$bLAzIpNF4NtapXlUpPVGhzxyNT8(Unknown Source:0)
E/TRuntime.CctTransportBackend(17034): 	at com.google.android.datatransport.cct.CctTransportBackend$$ExternalSyntheticLambda0.apply(Unknown Source:4)
E/TRuntime.CctTransportBackend(17034): 	at com.google.android.datatransport.runtime.retries.Retries.retry(Retries.java:54)
E/TRuntime.CctTransportBackend(17034): 	at com.google.android.datatransport.cct.CctTransportBackend.send(CctTransportBackend.java:372)
E/TRuntime.CctTransportBackend(17034): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.logAndUpdateState(Uploader.java:144)
E/TRuntime.CctTransportBackend(17034): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.lambda$upload$1$com-google-android-datatransport-runtime-scheduling-jobscheduling-Uploader(Uploader.java:104)
E/TRuntime.CctTransportBackend(17034): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader$$ExternalSyntheticLambda1.run(Unknown Source:8)
E/TRuntime.CctTransportBackend(17034): 	at com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(SafeLoggingExecutor.java:47)
E/TRuntime.CctTransportBackend(17034): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/TRuntime.CctTransportBackend(17034): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/TRuntime.CctTransportBackend(17034): 	at java.lang.Thread.run(Thread.java:920)
```

</details>

### Steps to reproduce

My main function:

```dart
Future main() async {
  runZonedGuarded(
    () async {
      WidgetsFlutterBinding.ensureInitialized();
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;
      runApp(const App());
    },
    (error, stack) async {
      await FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    },
  );
}
```

I ran the app on Android emulator with API 32 and threw an exception inside an async function, which causes `runZonedGuarded` to catch the error.

### Expected behavior

To be able to see the error reports on Firebase console

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1889], locale en-US)
    • Flutter version 3.0.5 at D:\sdk\flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\sdk\android
    • Platform android-32, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.70.1)
    • VS Code at C:\Users\Rasit Ayaz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 104.0.1293.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.6
Flutter SDK 3.0.5
rezervem 0.3.2+6

dependencies:
- bloc 8.1.0 [meta]
- cached_network_image 3.2.1 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- conditional_wrap 0.0.1 [flutter]
- easy_rich_text 1.1.0 [flutter url_launcher]
- email_validator 2.1.17
- equatable 2.0.3 [collection meta]
- expandable_page_view 1.0.17 [flutter]
- firebase_core 1.20.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.8.6 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.0.1 [flutter bloc provider]
- flutter_keyboard_visibility 5.3.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_launcher_icons 0.9.3 [args image path yaml]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_spinkit 5.1.0 [flutter]
- font_awesome_flutter 10.1.0 [flutter]
- http 0.13.4 [async http_parser meta path]
- intersperse 2.0.0
- intl 0.17.0 [clock path]
- logger 1.1.0
- retry 3.1.0
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sliver_tools 0.2.7 [flutter]
- spaced_flex 0.1.0 [flutter]
- table_calendar 3.0.6 [flutter intl simple_gesture_detector]
- table_sticky_headers 2.0.1 [flutter]
- top_snackbar_flutter 2.1.1 [flutter]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- archive 3.3.0 [crypto path]
- args 2.3.1
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- crypto 3.0.2 [typed_data]
- fake_async 1.3.0 [clock collection]
- ffi 1.2.1
- file 6.1.2 [meta path]
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.12 [collection firebase_core flutter meta plugin_platform_interface]
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image 3.2.0 [archive meta xml]
- js 0.6.4
- lints 2.0.0
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- nested 1.0.0 [flutter]
- octo_image 1.0.2 [flutter flutter_blurhash]
- path 1.8.1
- path_provider 2.0.10 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.14 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.9 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.6 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.6 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- provider 6.0.3 [collection flutter nested]
- rxdart 0.27.3
- shared_preferences_android 2.0.12 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- simple_gesture_detector 0.2.0 [flutter]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- sqflite 2.0.2+1 [flutter sqflite_common path]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0+2
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- url_launcher 6.1.2 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.11 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- win32 2.6.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.0.1 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
@rasitayaz 
Looking at the error from the log you shared:

`Couldn't encode request, returning with 400` seems to be coming from native Android sdk:

https://github.com/firebase/firebase-android-sdk/blob/fa4586a58267df04ba5310e269582b0672e02af0/transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java#L313

And `Couldn't open connection, returning with 500`:

https://github.com/firebase/firebase-android-sdk/blob/fa4586a58267df04ba5310e269582b0672e02af0/transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java#L310

So probably, the request isn't properly being received at the server from native sdk. I suggest you to reach out to [Firebase support](https://firebase.google.com/support) or native Firebase sdk github https://github.com/firebase/firebase-android-sdk/issues for further resolution.

Closing from here. If you disagree, write in comments and I'll reopen it.
