### ISSUE TITLE
🐛 [cloud_firestore] Query operator "isNotEqualTo" does not work

### ISSUE THREAD

**Issue by Wizzel1** [firebase/flutterfire#9353]
## Bug report

**Describe the bug**
I am trying to query documents based on their status with a `isNotEqualTo` operator but I get no documents returned.

### Steps to reproduce

1. Create a collection with 3 documents and add a "status: string" and a 'createdAt: Timestamp' field to it.
2. Set the status values to 1) `pending` 2) `processing` 3) `completed` and the createdAt to a random value.
3. Set up a query with a `isNotEqualTo` operator like this : 

```dart
return firebaseFirestore
        .myCollectionPath
        .orderBy('createdAt', descending: true)
        .where('status', isNotEqualTo: 'completed')
        .get();
```

### Expected behavior

I was expecting to get 2 documents from the query. One with status `pending` and one with status `processing`

Instead I got no documents.

## Additional context

When I alter the query to for example 

```dart
return firebaseFirestore
        .myCollectionPath
        .orderBy('createdAt', descending: true)
        .where('status', isEqualTo: 'pending')
        .get();
```

I get the expected results.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.1889], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.70.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.6
Flutter SDK 3.0.5
podsuite 1.0.0+1

dependencies:
- async 2.8.2 [collection meta]
- cloud_firestore 3.4.4 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 3.3.4 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- cupertino_icons 1.0.5
- easy_debounce 2.0.2+1
- email_validator 2.1.17
- extended_image 6.2.1 [extended_image_library flutter meta]
- file_picker 5.0.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_auth 3.6.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.20.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 10.3.5 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- fl_chart 0.46.0 [flutter equatable]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_colorpicker 1.0.3 [flutter]
- flutter_layout_grid 2.0.1 [flutter collection meta quiver]
- flutter_reorderable_list 1.2.0 [flutter]
- flutter_staggered_animations 1.0.0 [flutter]
- flutter_svg 1.1.3 [flutter meta path_drawing vector_math xml]
- fluttertoast 8.0.9 [flutter flutter_web_plugins]
- go_router 4.2.7 [collection flutter flutter_web_plugins logging meta]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- hooks_riverpod 1.0.4 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- intl 0.17.0 [clock path]
- just_the_tooltip 0.0.12 [flutter]
- multiple_result 1.0.4 [meta]
- package_info_plus 1.4.3 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- page_view_indicators 2.0.0 [flutter]
- percent_indicator 4.2.2 [flutter]
- scroll_to_index 3.0.1 [flutter]
- sentry_flutter 6.9.0 [flutter flutter_web_plugins sentry package_info_plus meta]
- styled_widget 0.4.0+3 [flutter lint]
- syncfusion_flutter_datagrid 20.2.43 [flutter syncfusion_flutter_core collection]
- syncfusion_flutter_datepicker 20.2.43 [flutter intl syncfusion_flutter_core]
- uuid 3.0.6 [crypto]

dev dependencies:
- build_runner 2.2.0 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- coverage 1.3.2 [args logging package_config path source_maps stack_trace vm_service]
- fake_async 1.3.0 [clock collection]
- fake_cloud_firestore 1.3.0 [flutter cloud_firestore cloud_firestore_platform_interface collection plugin_platform_interface quiver rxdart]
- faker 2.0.0 [crypto]
- firebase_storage_mocks 0.5.1 [flutter firebase_storage]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- freezed 2.1.0+1 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- freezed_annotation 2.1.0 [collection json_annotation meta]
- json_serializable 6.3.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- mocktail 0.3.0 [collection matcher test]
- remove_from_coverage 2.0.0 [args]

transitive dependencies:
- _fe_analyzer_shared 41.0.0 [meta]
- analyzer 4.2.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.0
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.3.0 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.9 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.2.0 [built_collection collection fixnum meta]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- clock 1.1.0
- cloud_firestore_platform_interface 5.7.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.4 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.1.13 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.3.2 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.16.0
- convert 3.0.1 [typed_data]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.2.3 [analyzer args path pub_semver source_span]
- equatable 2.0.3 [collection meta]
- extended_image_library 3.3.0 [crypto flutter http_client_helper path path_provider]
- ffi 2.0.1
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 6.5.3 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 4.2.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.13 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.3.3 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.0
- flutter_hooks 0.18.5+1 [flutter]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_riverpod 1.0.4 [collection flutter meta riverpod state_notifier]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 2.1.2 [async path]
- glob 2.0.2 [async collection file path string_scanner]
- graphs 2.1.0 [collection]
- http 0.13.4 [async http_parser meta path]
- http_client_helper 2.0.2 [http]
- http_multi_server 3.2.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- io 1.0.3 [meta path string_scanner]
- js 0.6.4
- json_annotation 4.6.0 [meta]
- lint 1.8.2
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- mime 1.0.1
- node_preamble 2.0.1
- package_config 2.0.2 [path]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 2.0.0 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.1
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.0.9 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.12 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.0 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.1 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1+1 [matcher]
- riverpod 1.0.3 [collection meta state_notifier]
- rxdart 0.27.3
- sentry 6.9.0 [http meta stack_trace uuid]
- shelf 1.3.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.1.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.2.2 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.2 [analyzer collection source_gen]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.2+1 [meta]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- syncfusion_flutter_core 20.2.43 [vector_math flutter]
- term_glyph 1.2.0
- test 1.21.1 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.13 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- vector_math 2.1.2
- vm_service 8.3.0
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.0.0 [logging]
- win32 2.7.0 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
> ```dart
> .where('status', isNotEqualTo: 'completed')
> ```

@Wizzel1 Can you try something like `isNotEqualTo: true`, where in this query does not return documents with `status` where the 'status` field does not exist. 

`Not-equal (!=) and not-in queries exclude documents where the given field does not exist.`

**Comment by Wizzel1** [comment]
@darshankawar I tried 
```dart
.where('status', isNotEqualTo: true)
```
and the result is an empty list.

**Comment by darshankawar** [comment]
Thanks for the update. Can you provide the complete query along with minimal code sample that we can directly use to verify this ?

**Comment by darshankawar** [comment]
Revisiting this issue, I verified this as below and observed that `isNotEqualTo` works properly and returns correct data:

1. Firestore documents data:

<img width="225" alt="Screenshot 2022-08-23 at 5 17 51 PM" src="https://user-images.githubusercontent.com/67046386/186150613-f8d84a0b-261f-4d50-9159-e8899cea0f41.png">
<img width="246" alt="Screenshot 2022-08-23 at 5 17 57 PM" src="https://user-images.githubusercontent.com/67046386/186150620-6d9f21b3-7823-4745-bc42-b3732ace6bf4.png">
<img width="256" alt="Screenshot 2022-08-23 at 5 18 03 PM" src="https://user-images.githubusercontent.com/67046386/186150622-64320a0a-ad9e-48db-b706-cb19048e9ec3.png">

2. Query to retrieve data wherein `state` is not equal to `MN`:

```
final query = FirebaseFirestore.instance.collection('cities').orderBy('state', descending: true).where('state', isNotEqualTo: 'MN').get().
    then((QuerySnapshot snapshot) {
      snapshot.docs.forEach((element) {
        print('The result of isNotEqualTo query is: ${element.data()}');
      });
    });
```

Result:

<img width="984" alt="Screenshot 2022-08-23 at 5 22 54 PM" src="https://user-images.githubusercontent.com/67046386/186151221-7f44f70a-4a55-4ca9-9859-7476223c284e.png">

**Comment by Wizzel1** [comment]
@darshankawar thanks for checking back. Can you also confirm that it works with this query : 

```dart
final query = FirebaseFirestore.instance.collection('cities').orderBy('population', descending: true).where('state', isNotEqualTo: 'MN').get().
    then((QuerySnapshot snapshot) {
      snapshot.docs.forEach((element) {
        print('The result of isNotEqualTo query is: ${element.data()}');
      });
    });
   ```
   Where the documents get ordered by "population" ?

**Comment by darshankawar** [comment]
I had tried that earlier, wherein, the `orderBy` field and `where` clause fields are different, and it throws below error:

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:cloud_firestore/src/query.dart': Failed assertion: line 677 pos 11: 'field == orders[0][0]': The initial orderBy() field '[[FieldPath([population]), true]][0][0]' has to be the same as the where() field parameter 'FieldPath([state])' when an inequality operator is invoked.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      _JsonQuery.where (package:cloud_firestore/src/query.dart:677:11)
#3      _HomeListState._setCityData (package:pet_medical/home_list.dart:273:107)
#4      _HomeListState._buildHome.<anonymous closure> (package:pet_medical/home_list.dart:180:13)
#5      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1076:21)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627<…>

```

Indicating:

`The initial orderBy() field '[[FieldPath([population]), true]][0][0]' has to be the same as the where() field parameter 'FieldPath([state])' when an inequality operator is invoked.` and hence, passing same field in both clauses, for example, `state` then gives correct output.

Also, if you look at the error message carefully, it says `initial orderBy()`, that means, we can probably have another use of `orderBy()` after our initial query, something like below and see if it works in your case:

```
final query = FirebaseFirestore.instance.collection('cities').orderBy('state', descending: true).where('state', isNotEqualTo: 'MN').orderBy('population, descending: true').get().
    then((QuerySnapshot snapshot) {
      snapshot.docs.forEach((element) {
        print('The result of isNotEqualTo query is: ${element.data()}');
      });
    });
```

For above query to run though, you'll need to have index setup in your firebase console, otherwise it will throw below error:

`[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: [cloud_firestore/failed-precondition] Operation was rejected because the system is not in a state required for the operation's execution. If performing a query, ensure it has been indexed via the Firebase console.`

**Comment by Wizzel1** [comment]
@darshankawar Interesting. Adding the additional orderBy works fine. Thanks!
