### ISSUE TITLE
🐛 [firebase_messaging] Android: Crash to allow camera permissions.

### ISSUE THREAD

**Issue by hukusuke1007** [firebase/flutterfire#9429]
## Bug report

It crashes when I grant camera permissions.
The same applies to photos.

It happens with firebase_messaging 13.0.0 and not with 12.0.0.

```
E/AndroidRuntime(30046): FATAL EXCEPTION: main
E/AndroidRuntime(30046): Process: xxxxxxx.product.xxxx PID: 30046
E/AndroidRuntime(30046): java.lang.AssertionError
E/AndroidRuntime(30046): 	at io.flutter.plugins.firebase.messaging.FlutterFirebasePermissionManager.onRequestPermissionsResult(FlutterFirebasePermissionManager.java:33)
E/AndroidRuntime(30046): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
E/AndroidRuntime(30046): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
E/AndroidRuntime(30046): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:752)
E/AndroidRuntime(30046): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:748)
E/AndroidRuntime(30046): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8535)
E/AndroidRuntime(30046): 	at android.app.Activity.dispatchActivityResult(Activity.java:8392)
E/AndroidRuntime(30046): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5361)
E/AndroidRuntime(30046): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5407)
E/AndroidRuntime(30046): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime(30046): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(30046): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(30046): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(30046): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
E/AndroidRuntime(30046): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(30046): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(30046): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(30046): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
E/AndroidRuntime(30046): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30046): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(30046): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### Steps to reproduce

1. Allow camera permissions.
2. Crash app.

### Expected behavior

The app should not crash.

## Additional context

Android 12
Google Pixel 6a, Real Device

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale
    ja-JP)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.6
Flutter SDK 3.0.5

dependencies:
- adaptive_dialog 1.8.0 [animations collection dynamic_color flutter intersperse macos_ui meta]
- app_settings 4.1.8 [flutter]
- auto_size_text 3.0.0 [flutter]
- badges 2.0.3 [flutter]
- carousel_slider 4.1.1 [flutter]
- cloud_firestore 3.4.6 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 3.3.6 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- collection 1.16.0
- cron 0.3.2
- crypto 3.0.2 [typed_data]
- cupertino_icons 1.0.5
- device_info 2.0.3 [flutter device_info_platform_interface]
- dismissible_page 0.7.3 [flutter]
- dots_indicator 2.1.0 [flutter]
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- expandable_page_view 1.0.17 [flutter]
- extended_image 6.2.1 [extended_image_library flutter meta]
- extended_nested_scroll_view 5.1.3 [flutter visibility_detector]
- firebase_analytics 9.3.3 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.7.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.21.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.8.9 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 4.3.6 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 12.0.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 10.3.7 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_app_badger 1.4.0 [flutter]
- flutter_hooks 0.18.5+1 [flutter]
- flutter_image_compress 1.1.1 [flutter]
- flutter_inappwebview 5.4.3+7 [flutter]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_local_notifications 9.8.0+1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_native_timezone 2.0.0 [flutter_web_plugins flutter js]
- flutter_rating_bar 4.0.1 [flutter]
- flutter_slidable 1.3.2 [flutter]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- freezed_annotation 2.1.0 [collection json_annotation meta]
- geocoding 2.0.5 [flutter geocoding_platform_interface]
- geojson 1.0.0 [geodesy geopoint iso pedantic]
- geolocator 9.0.1 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- google_maps_flutter 2.1.12 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface]
- google_mobile_ads 2.0.1 [meta flutter visibility_detector]
- google_sign_in 5.4.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- hashids2 2.0.0
- hive 2.2.3 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- hooks_riverpod 1.0.4 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- http 0.13.5 [async http_parser meta path]
- image_cropper 3.0.0 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_gallery_saver 1.7.1 [flutter]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- in_app_notification 1.1.2 [flutter]
- in_app_review 2.0.4 [flutter in_app_review_platform_interface]
- intl 0.17.0 [clock path]
- json_annotation 4.6.0 [meta]
- keyboard_utils 1.3.4 [flutter]
- launch_review 3.0.1 [flutter]
- map_launcher 2.3.0+1 [flutter]
- nonce 1.2.0
- numberpicker 2.1.1 [flutter infinite_listview]
- package_info 2.0.2 [flutter]
- page_transition 2.0.9 [flutter]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- permission_handler 10.0.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- pull_to_refresh_flutter3 2.0.1 [flutter]
- purchases_flutter 4.2.0 [flutter freezed_annotation json_annotation]
- rxdart 0.27.5
- share_plus 4.0.10+1 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 4.1.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- simple_logger 1.9.0 [logging stack_trace]
- sqflite 2.0.3+1 [flutter sqflite_common path]
- step_progress_indicator 1.0.2 [flutter]
- synchronized 3.0.0+2
- table_calendar 3.0.6 [flutter intl simple_gesture_detector]
- timezone 0.8.0 [path]
- toggle_switch 2.0.1 [flutter]
- url_launcher 6.1.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.6 [crypto]

dev dependencies:
- analyzer 3.4.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- build_runner 2.2.0 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_gen_runner 4.3.0 [flutter_gen_core build collection crypto glob]
- flutter_launcher_icons 0.9.3 [args image path yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- freezed 2.0.4 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- hive_generator 1.1.3 [build source_gen hive analyzer source_helper]
- json_serializable 6.3.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- pedantic_mono 1.19.2 [flutter_lints]

transitive dependencies:
- _fe_analyzer_shared 38.0.0 [meta]
- animations 2.0.4 [flutter]
- archive 3.3.1 [crypto path]
- args 2.3.1
- asn1lib 1.1.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.3.0 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.9 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.4.1 [built_collection collection fixnum meta]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- clock 1.1.0
- cloud_firestore_platform_interface 5.7.3 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.6 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.1.15 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.3.4 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.2.0 [built_collection built_value collection matcher meta]
- color 3.0.0
- convert 3.0.2 [typed_data]
- cross_file 0.3.3+1 [js meta]
- dart_style 2.2.3 [analyzer args path pub_semver source_span]
- dartx 1.1.0 [characters collection crypto meta path time]
- dbus 0.7.3 [args ffi meta xml]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- dynamic_color 1.4.0 [flutter flutter_test material_color_utilities]
- extended_image_library 3.3.0 [crypto flutter http_client_helper path path_provider]
- extra_pedantic 1.5.0
- fake_async 1.3.0 [clock collection]
- ffi 1.2.1
- file 6.1.4 [meta path]
- firebase_analytics_platform_interface 3.3.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.2+3 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.6.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 4.3.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.15 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.3+11 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.1.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.1.3 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.15 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.3.5 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.1
- flutter_gen_core 4.3.0 [path yaml mime xml dartx color collection json_annotation dart_style analyzer args pub_semver source_span]
- flutter_lints 2.0.1 [lints]
- flutter_local_notifications_linux 0.5.1 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_riverpod 1.0.4 [collection flutter meta riverpod state_notifier]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 2.1.3 [async path]
- geocoding_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- geodesy 0.4.0-nullsafety.0 [latlong2 pedantic]
- geolocator_android 4.1.0 [flutter geolocator_platform_interface]
- geolocator_apple 2.2.1 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.6 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.6 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.1 [flutter geolocator_platform_interface]
- geopoint 1.0.0 [latlong2 slugify]
- glob 2.1.0 [async collection file path string_scanner]
- google_maps_flutter_android 2.1.10 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.1.11 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.2.2 [collection flutter plugin_platform_interface stream_transform]
- google_sign_in_android 6.0.1 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.4.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.2.0 [flutter quiver]
- google_sign_in_web 0.10.2 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- graphs 2.1.0 [collection]
- http_client_helper 2.0.3 [http]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image 3.1.3 [archive meta xml]
- image_cropper_for_web 1.0.2 [flutter flutter_web_plugins image_cropper_platform_interface js]
- image_cropper_platform_interface 3.0.2 [flutter plugin_platform_interface http]
- image_picker_android 0.8.5+2 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.5+6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- in_app_review_platform_interface 2.0.3 [flutter url_launcher plugin_platform_interface platform]
- infinite_listview 1.1.0 [flutter]
- intersperse 2.0.0
- io 1.0.3 [meta path string_scanner]
- iso 1.0.0 [extra_pedantic meta pedantic]
- js 0.6.4
- latlong2 0.8.1 [intl]
- linkify 4.1.0
- lints 2.0.0
- logging 1.0.2
- macos_ui 1.7.4 [flutter]
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- mime 1.0.2
- package_config 2.1.0 [path]
- path 1.8.1
- path_drawing 0.5.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_android 2.0.20 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.7 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_android 10.0.0 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.0 [flutter permission_handler_platform_interface]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pointycastle 3.6.1 [collection convert js]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.1 [collection meta]
- pubspec_parse 1.2.1 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.1.0 [matcher]
- riverpod 1.0.3 [collection meta state_notifier]
- share_plus_linux 3.0.0 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 3.0.1 [share_plus_platform_interface flutter]
- share_plus_platform_interface 3.0.3 [flutter meta mime plugin_platform_interface]
- share_plus_web 3.0.1 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 3.0.1 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences_android 2.0.12 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.3.2 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.2 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- simple_gesture_detector 0.2.0 [flutter]
- sky_engine 0.0.99
- slugify 2.0.0
- source_gen 1.2.2 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.2 [analyzer collection source_gen]
- source_span 1.8.2 [collection path term_glyph]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.2+1 [meta]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- time 2.1.2 [clock]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.1 [collection]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.13 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.2
- visibility_detector 0.3.3 [flutter]
- watcher 1.0.1 [async path]
- web_socket_channel 2.2.0 [async crypto stream_channel]
- win32 2.6.1 [ffi]
- xdg_directories 0.2.0+2 [meta path process]
- xml 5.4.1 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]

```

</details>

---

**Comment by darshankawar** [comment]
@hukusuke1007 
Do you have `android:exported="true"` permission set in manifest file ? If not, can you add this property and try again to see if you still get same crash or not ?

**Comment by hukusuke1007** [comment]
> @hukusuke1007 Do you have `android:exported="true"` permission set in manifest file ? If not, can you add this property and try again to see if you still get same crash or not ?

`android:exported="true"` is given to Activity. This code .

```
    <application
        android:label="@string/app_name"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true"
        requestLegacyExternalStorage="true"
        tools:targetApi="m">

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:exported="true">
      ...
     </activity>
</application>
```

**Comment by darshankawar** [comment]
@hukusuke1007 
Since the new plugin version (13.0.0) is a breaking change, you'll need to set target API level to 33. See the [CHANGELOG](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/CHANGELOG.md#1300) for details.

Try the same and see if you still get same crash or not.

**Comment by hukusuke1007** [comment]
@darshankawar Probably the same cause as this one. 
https://github.com/firebase/flutterfire/issues/9430

**Comment by darshankawar** [comment]
Yes, I've already referenced this issue in it. Do you have same use case ? like `targetSdkVersion` is less than 33 ?
If you set it to 33, does it work properly ?

**Comment by hukusuke1007** [comment]
>If you set it to 33, does it work properly ?

No. App crash...

**Comment by Tom3652** [comment]
I am seeing the same behavior because of camera permissions https://github.com/firebase/flutterfire/issues/9430#issuecomment-1229514886

**Comment by darshankawar** [comment]
Keeping this issue open and labeling for further insights, as I don't have Android 12 or 13 device to verify this.

/cc @russellwheatley

**Comment by ps9310** [comment]
I got the same exception on camera permission request.

compileSdkVersion & targetSdkVersions' are set to 33 and testing on Android 11

**Comment by rlueders** [comment]
Getting the same when granting location and microphone permission.  Compile and target settings both set to 33.  Testing on Android 13.

**Comment by russellwheatley** [comment]
Hey folks, the fix will be released tomorrow.

**Comment by xieenming** [comment]
With the new version 13.0.1 of firebase_messaging https://pub.dev/packages/firebase_messaging/changelog , there is no crash any more.
Thanks a lot~
