### ISSUE TITLE
🐛 [firebase_messaging] Crash when request  notification permission to Android 13 users

### ISSUE THREAD

**Issue by aya2453** [firebase/flutterfire#9488]
## Bug report

**Describe the bug**
Crash when request  notification permission to Android 13 users

### Steps to reproduce

I can't reproduce this crash with my devices.

### Versions
- AGP 4.2.0
- Flutter 3.3
- Firebase Messaging  13.0.0

### My code

``` dart
await FirebaseMessaging.instance.requestPermission()
```

### Stack Trace

<details><summary>Click To Expand</summary>

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {jp.tokyomixcurry/jp.tokyomixcurry.MainActivity}: com.google.android.gms.tasks.d: Complete with: result {authorizationStatus=0}
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5347)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5386)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7898)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
```
Caused by com.google.android.gms.tasks.d: Complete with: result {authorizationStatus=0}
       at com.google.android.gms.tasks.zzw.zzh(zzw.java:5)
       at com.google.android.gms.tasks.zzw.zzb(zzw.java:3)
       at com.google.android.gms.tasks.TaskCompletionSource.setResult(TaskCompletionSource.java:2)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin.lambda$requestPermissions$7(FlutterFirebaseMessagingPlugin.java:9)
       at io.flutter.plugins.firebase.messaging.-$$Lambda$FlutterFirebaseMessagingPlugin$gjpjjjWG2GyfLX_2gV6_fSq-m60.onSuccess(lambda:4)
       at io.flutter.plugins.firebase.messaging.FlutterFirebasePermissionManager.onRequestPermissionsResult(FlutterFirebasePermissionManager.java:16)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:20)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:13)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:59)
       at io.flutter.embedding.android.FlutterFragment.onRequestPermissionsResult(FlutterFragment.java:10)
       at io.flutter.embedding.android.FlutterFragmentActivity.onRequestPermissionsResult(FlutterFragmentActivity.java:5)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8759)
       at android.app.Activity.dispatchActivityResult(Activity.java:8617)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5340)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5386)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7898)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

</details>

### Affected Users

<img width="1114" alt="スクリーンショット 2022-09-07 22 20 18" src="https://user-images.githubusercontent.com/9216900/188888692-b59e832d-68f7-46d0-b967-40c049942a9c.png">

**Comment by aya2453** [comment]
Same issue https://github.com/firebase/flutterfire/issues/9430
