### ISSUE TITLE
🐛 [firebase_storage] An unknown error occurred, please check the server response. on macos

### ISSUE THREAD

**Issue by Ali1Ammar** [firebase/flutterfire#9506]
## Bug report

**Describe the bug**
if i try to use storage method (putString,listAll,getMeta,getDownloadURL,getMetadata)
I get this below error :
```
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-001A35010AE2001E }
{ platform:macOS, arch:x86_64, id:00008103-001A35010AE2001E }
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
Connecting to VM Service at ws://127.0.0.1:62695/3SK749usmn4=/ws
2022-09-09 22:14:06.544 teststorage[36974:224014] FLTFirebaseStorage: An unknown error occurred while calling method Reference#getMetadata
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_storage/unknown] An unknown error occurred, please check the server response.
#0      StandardMethodCodec.decodeEnvelope
#1      MethodChannel._invokeMethod
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod
<asynchronous suspension>
#3      MethodChannelReference.getMetadata
<asynchronous suspension>

```

### Steps to reproduce

1. create new flutter project
2. run flutterfire configure
3. add firebase_core, firebase_storage
4. write below code
5. run the app
 

### Expected behavior

every things work.

### Sample project

```
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: Scaffold(
          body: ElevatedButton(
              onPressed: () {
                FirebaseStorage.instance.ref("file.png").getMetadata();
              },
              child: Text("run")),
        ));
  }
}
```

---

## Additional context

the bugs appears on desktop macos (i test on m1 cpu) 
on ios simulator every things work fine

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-arm, locale
    en-IQ)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
mac@Macs-MacBook-Air teststorage % flutter pub deps -- --style=compact
Dart SDK 2.18.0
Flutter SDK 3.3.1
teststorage 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- firebase_core 1.22.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 10.3.8 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- collection 1.16.0
- fake_async 1.3.1 [clock collection]
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.16 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.3.6 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- js 0.6.4
- lints 2.0.0
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- path 1.8.2
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- vector_math 2.1.2
mac@Macs-MacBook-Air teststorage % 
```

</details>

---

**Comment by darshankawar** [comment]
@Ali1Ammar 
I am unable to replicate the error you reported. Using your code sample, ran it on macOS, wherein I get a different error as below, which is expected considering I tried the code as-is:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_storage/object-not-found] No object exists at the desired reference.
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:499:43)
<asynchronous suspension>
#3      MethodChannelReference.getMetadata (package:firebase_storage_platform_interface/src/method_channel/method_channel_reference.dart:67:36)
<asynchronous suspension>

```

The error that you are getting : `[firebase_storage/unknown] An unknown error occurred, please check the server response.`, probably is similar to https://github.com/firebase/flutterfire/issues/7706, so I suggest you to follow-up in it for further updates.

Closing this as a duplicate.
