### ISSUE TITLE
🐛 [FlutterFire CLI] Cannot complete configuration - Unhandled Exception

### ISSUE THREAD

**Issue by giaesp** [firebase/flutterfire#9608]
I'm not able to complete the Flutter project configuration. After launching the command I was able to select my Firebase project, I selected desired platform (android, ios and web). It seemed to do something, then I obtainer this error message:

```
Unhandled exception:
Exception: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- xcodeproj (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

#0      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:517:11)
<asynchronous suspension>
#1      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#2      main (file:///Users/gianlucaesposito/.pub-cache/hosted/pub.dartlang.org/flutterfire_cli-0.2.6/bin/flutterfire.dart:57:5)
<asynchronous suspension>
```

Please note: I've updated XCode to the latest version (Version 14.0 (14A309)) just a couple of days ago.

**Comment by giaesp** [comment]
I was able to get it working. I needed to launch this command

`gem install xcodeproj`

As stated in this thread `https://github.com/CocoaPods/pod-template/issues/222`
