### ISSUE TITLE
[Android][cloud_firestore] Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException

### ISSUE THREAD

**Issue by SOG-web** [firebase/flutterfire#9666]
Describe your environment
Android Studio version: 2021.2.1
Firebase Component: _____ Firestore
Component version: _____
Describe the problem
Steps to reproduce:

iam working on a flutter app  just initialized firebase for my project , added the firestore package and anytime i try to get docs from firestore i get this error. The app works perfectly on the web, but it throws error on emulator. This error just started two days ago, it has been working perfectly before then.

```
/ManagedChannelImpl(23932): [{0}] Failed to resolve name. status={1}
W/Firestore(23932): (24.3.1) [WatchStream]: (5cc1395) Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(23932): 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
W/Firestore(23932): 	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
W/Firestore(23932): 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
W/Firestore(23932): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/Firestore(23932): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/Firestore(23932): 	at java.lang.Thread.run(Thread.java:920)
W/Firestore(23932): Caused by: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(23932): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
W/Firestore(23932): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
W/Firestore(23932): 	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
W/Firestore(23932): 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
W/Firestore(23932): 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
W/Firestore(23932): 	... 5 more
```

**Comment by darshankawar** [comment]
@SOG-web Thanks for the report.
Looking at the error, it doesn't seem to be coming from plugin, but could be a glitch at native Android side or from firebase tools if you are using firebase emulator.

I suggest you to reach out to firebase support for further resolution. https://firebase.google.com/support/troubleshooter/contact

Closing from here, as there's nothing actionable from client side.
