### ISSUE TITLE
🐛 [Firebase_auth] Randomly signs user out after account creating and navigation from page

### ISSUE THREAD

**Issue by MbohBless** [firebase/flutterfire#9693]
## Bug report

**BUG DESCRIPTION**
My system uses firebase phone number auth to generate tokens for my backend now when i use signIn with google account and link the phone auth credentials. but when i use phone number auth only, it actually signs in then after navigating to the next page, it then goes well requesting it data from the backend and after a second or 2 i get the message "Notifying about signout event"

### Steps to reproduce

User creates account using just phone number signin as a means of authentication from firebase --> navigate to home screen then signout is automatically triggered

### Expected behavior

The authenticated state persist as if the user was authenticated using google or apple credentials
---

## Additional context

Because i need to refresh the token 
```flutter:
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_auth/user-token-expired] The user's credential is no longer valid. The user must sign in again.
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:499:43)
<asynchronous suspension>
#3      MethodChannelUser.getIdToken (package:firebase_auth_platform_interface/src/method_channel/method_channel_user.dart:44:36)
```
---

### Flutter doctor

This is`flutter doctor` 
<details><summary>This indicates everything is properly install</summary>

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 11.6.2 20G314 darwin-x64, locale en-CM)          
 Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] VS Code (version 1.69.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Quite extensive list for all platforms</summary>

```
dependencies:
- auto_route 5.0.1 [flutter path collection meta]
- bottom_loader 0.2.2 [flutter]
- camera 0.10.0+1 [camera_android camera_avfoundation camera_platform_interface camera_web flutter flutter_plugin_android_lifecycle quiver]
- connectivity_plus 2.3.6+1 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- device_info_plus 4.1.2 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- dio 4.0.6 [http_parser path]
- dio_cache_interceptor 3.3.1 [dio uuid string_scanner]
- dots_indicator 2.1.0 [flutter]
- equatable 2.0.5 [collection meta]
- firebase_auth 3.8.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.24.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 4.3.7 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 13.0.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 10.3.8 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_credit_card 3.0.3 [flutter]
- flutter_hooks 0.18.5+1 [flutter]
- flutter_local_notifications 9.9.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_offline 2.1.0 [flutter connectivity_plus network_info_plus]
- flutter_rating_bar 4.0.1 [flutter]
- flutter_riverpod 1.0.4 [collection flutter meta riverpod state_notifier]
- flutter_signin_button 2.0.0 [flutter font_awesome_flutter]
- flutter_stripe 5.0.0 [flutter stripe_android stripe_ios stripe_platform_interface]
- fluttercontactpicker 4.7.0 [flutter contact_picker_platform_interface contact_picker_web]
- fluttertoast 8.0.9 [flutter flutter_web_plugins]
- form 0.0.5 [flutter validators]
- form_field_validator 1.1.0 [flutter intl]
- freezed 2.1.0+1 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- google_sign_in 5.4.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- hive 2.2.3 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- hooks_riverpod 1.0.4 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- image_cropper 3.0.0 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- image_stack 2.1.1 [flutter]
- infinite_scroll_pagination 3.2.0 [flutter sliver_tools]
- intl 0.17.0 [clock path]
- intl_phone_field 3.1.0 [flutter]
- json_serializable 6.3.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- lazy_load_scrollview 1.3.0 [flutter]
- line_icons 2.0.1 [flutter]
- local_auth 2.1.2 [flutter intl local_auth_android local_auth_ios local_auth_platform_interface local_auth_windows]
- lottie 1.4.2 [archive flutter path vector_math]
- mask_text_input_formatter 2.4.0 [flutter]
- pinput 2.2.12 [flutter smart_auth]
- qr_flutter 4.0.0 [flutter qr]
- rate_my_app 1.1.3 [shared_preferences flutter_rating_bar flutter]
- sentry_flutter 6.9.1 [flutter flutter_web_plugins sentry package_info_plus meta]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 2.0.0 [flutter]
- timeago 3.3.0 [intl]
- url_launcher 6.1.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- web_socket_channel 2.2.0 [async crypto stream_channel]

dev dependencies:
- auto_route_generator 5.0.2 [build source_gen analyzer path build_runner code_builder dart_style xml args auto_route]
- build_runner 2.2.0 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- crypto 3.0.2 [typed_data]
- flutter_launcher_icons 0.10.0 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 2.0.1 [lints]
- flutter_native_splash 2.2.9 [args flutter flutter_web_plugins html image js lint meta path universal_io xml yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- hive_generator 1.1.3 [build source_gen hive analyzer source_helper]
- sign_in_with_apple 4.1.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]

dependency overrides:
- firebase_messaging_platform_interface 4.2.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]

transitive dependencies:
- _fe_analyzer_shared 43.0.0 [meta]
- _flutterfire_internals 1.0.2 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 4.3.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.3.1 [crypto path]
- args 2.3.1
- async 2.9.0 [collection meta]
- basic_utils 3.9.4 [http logging json_annotation pointycastle]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.3.0 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.9 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.4.1 [built_collection collection fixnum meta]
- camera_android 0.10.0+2 [camera_platform_interface flutter flutter_plugin_android_lifecycle stream_transform]
- camera_avfoundation 0.9.8+5 [camera_platform_interface flutter stream_transform]
- camera_platform_interface 2.2.0 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.3.0 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.2.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 5.7.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.10 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.2.0 [built_collection built_value collection matcher meta]
- collection 1.16.0
- connectivity_plus_linux 1.3.1 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.4 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.1 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.3 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.2 [connectivity_plus_platform_interface flutter]
- contact_picker_platform_interface 4.7.0 [flutter meta plugin_platform_interface]
- contact_picker_web 4.7.0 [flutter flutter_web_plugins js contact_picker_platform_interface]
- convert 3.0.2 [typed_data]
- cross_file 0.3.3+1 [js meta]
- csslib 0.17.2 [source_span]
- dart_style 2.2.3 [analyzer args path pub_semver source_span]
- dbus 0.7.8 [args ffi meta xml]
- device_info_plus_linux 3.0.0 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 3.0.0 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 3.0.0 [flutter meta plugin_platform_interface]
- device_info_plus_web 3.0.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 4.1.0 [device_info_plus_platform_interface ffi flutter win32]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- firebase_auth_platform_interface 6.7.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 4.4.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_dynamic_links_platform_interface 0.2.3+12 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.1.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.16 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.3.6 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.1
- flutter_local_notifications_linux 0.5.1 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- font_awesome_flutter 9.2.0 [flutter]
- freezed_annotation 2.1.0 [collection json_annotation meta]
- frontend_server_client 2.1.3 [async path]
- glob 2.1.0 [async collection file path string_scanner]
- google_sign_in_android 6.1.0 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.5.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.3.0 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.10.2 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- graphs 2.1.0 [collection]
- html 0.15.0 [csslib source_span]
- http 0.13.5 [async http_parser meta path]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image 3.2.0 [archive meta xml]
- image_cropper_for_web 1.0.2 [flutter flutter_web_plugins image_cropper_platform_interface js]
- image_cropper_platform_interface 3.0.2 [flutter plugin_platform_interface http]
- image_picker_android 0.8.5+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- io 1.0.3 [meta path string_scanner]
- js 0.6.4
- json_annotation 4.6.0 [meta]
- lint 1.10.0
- lints 2.0.0
- local_auth_android 1.0.12 [flutter flutter_plugin_android_lifecycle intl local_auth_platform_interface]
- local_auth_ios 1.0.9 [flutter intl local_auth_platform_interface]
- local_auth_platform_interface 1.0.4 [flutter intl plugin_platform_interface]
- local_auth_windows 1.0.3 [flutter local_auth_platform_interface]
- logging 1.0.2
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- mime 1.0.2
- network_info_plus 2.1.4+1 [flutter meta network_info_plus_platform_interface network_info_plus_linux network_info_plus_macos network_info_plus_windows network_info_plus_web]
- network_info_plus_linux 1.1.2 [collection flutter meta network_info_plus_platform_interface nm]
- network_info_plus_macos 1.3.0 [network_info_plus_platform_interface flutter]
- network_info_plus_platform_interface 1.1.2 [flutter meta plugin_platform_interface]
- network_info_plus_web 1.0.1 [flutter flutter_web_plugins network_info_plus_platform_interface]
- network_info_plus_windows 1.0.2 [flutter network_info_plus_platform_interface]
- nm 0.5.0 [dbus]
- package_config 2.1.0 [path]
- package_info_plus 1.4.3+1 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 2.1.0 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.2
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.20 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pointycastle 3.6.2 [collection convert js]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.1 [collection meta]
- pubspec_parse 1.2.1 [checked_yaml collection json_annotation pub_semver yaml]
- qr 2.1.0 [meta]
- quiver 3.1.0 [matcher]
- random_string 2.3.1
- riverpod 1.0.3 [collection meta state_notifier]
- sentry 6.9.1 [http meta stack_trace uuid]
- shared_preferences_android 2.0.13 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.1.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.3.2 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.2 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- sliver_tools 0.2.8 [flutter]
- smart_auth 1.0.5 [flutter flutter_web_plugins]
- source_gen 1.2.2 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.2 [analyzer collection source_gen]
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.2+1 [meta]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.1 [source_span]
- stripe_android 5.0.0 [flutter]
- stripe_ios 5.0.0 [flutter]
- stripe_platform_interface 5.0.0 [flutter freezed_annotation json_annotation meta plugin_platform_interface]
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.1 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_android 6.0.18 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.13 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- validators 2.0.1 [vin_decoder]
- vector_math 2.1.2
- vin_decoder 0.1.4 [basic_utils http random_string]
- watcher 1.0.1 [async path]
- win32 3.0.0 [ffi]
- xdg_directories 0.2.0+2 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]

```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @MbohBless 
Is your main issue that you are getting `"Notifying about signout event"` or `Unhandled Exception: [firebase_auth/user-token-expired] The user's credential is no longer valid. The user must sign in again.` ?

Or after signing out, you get the said exception ?

Are you able to replicate this behavior consistently everytime ? If so, can you provide a minimal reproducible code sample that shows this behavior ?

I would also suggest you to try the [official plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example) and see if using it, you get same behavior / log as you reported.

**Comment by MbohBless** [comment]
_userServices.fetchUserMe().then((value) {
                    if (value != null) {
                      UserBox.putUserName(value["name"]);
                      FirebaseCloudMessagingServices.tokenRefreshListener();
                      Future.delayed(Duration.zero, () {
                        if (ref.read(whatRoute) == "create_acct") {
                          Toaster.toastInfo("You have an account already");
                          auth.homeHandler(link, context, ref);
                        }
                        auth.homeHandler(link, context, ref);
                      });
                    } else {
                      if (ref.read(whatRoute) == "create_acct") {
                        _userServices.postUser().then((value) {
                          setState(() {
                            isLoading = false;
                          });
                          if (value.statusCode == 201 ||
                              value.statusCode == 200) {
                            UserBox.putUserName(value.data["data"]["name"]);
                            auth.homeHandler(link, context, ref);
                          } else {
                            return false;
                          }
                        }).onError((error, stackTrace) {
                          setState(() {
                            isLoading = false;
                          });
                          return null;
                        });
                      } else {
                        // Toaster.toastInfo("An error occured");
                        context.router.replaceNamed("/name_email");
                        return false;
                      }
                    }
                  }).onError((error, stackTrace) {
                    setState(() {
                      isLoading = false;
                    });

after successful account creation done by the above  
`_userservices.postUser` 
 which makes use of the firebase generated auth token the application normally navigates using the 
`auth.homeHandler(link,context,ref)`
to the application home page 
but after creating account and navigating, the user is automatically logged out

**Comment by darshankawar** [comment]
@MbohBless The code you provided still contains custom code that we can't directly use. Please provide a complete code sample (ex: main.dart) that we can directly copy paste and run to verify the reported behavior.

Also provide the platform on which you are seeing this error (ex: Android, iOS, web).

**Comment by darshankawar** [comment]
@MbohBless 
Can you try the [official plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example) with your setup and check if using it, you get same behavior as you reported earlier ?

**Comment by MbohBless** [comment]
ok i did try and did not get thesame issue i guess the issue is coming from my end i will try to rectify and continue working

**Comment by darshankawar** [comment]
Closing based on above comment as it looks more like an implementation issue rather than plugin's.
