### ISSUE TITLE
🐛 [flutterfire_ui] Inserting 2 times a wrong SMS code raises the exception "Bad state: Future already completed"

### ISSUE THREAD

**Issue by AlbertoNoris** [firebase/flutterfire#9737]
## Bug report

**Describe the bug**
On android (I've not tested on ios or web) when using the phone as the login provider after the code has been sent to the device if you type it manually wrong 2 times inside the code field it raises the exception "StateError (Bad state: Future already completed)".

### Steps to reproduce

1. Use the PhoneProviderConfiguration() as a provider
2. Insert the phone number and click "next". The sim card musn't be inside the phone you are testing with otherwise the sms is read automatically.
3. Wait for the sms code to arrive.
4. Type inside the sms code field a wrong code for 2 times.

### Expected behavior

Since typing the SMS code wrongly is something that can happen a lot the expected beahviour should be ... nothing (?)

### Sample project
Simply add the PhoneProviderConfiguration() inside a SignInScreen()
```dart
class LoginWithPhone extends StatelessWidget {
  const LoginWithPhone({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SignInScreen(
      providerConfigs: [PhoneProviderConfiguration()],
    );
  }
}
```
---

## Additional context
Exception raised
![image](https://user-images.githubusercontent.com/61833464/196247070-57abeccb-270e-49c7-9604-c92662205b94.png)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.3, on Microsoft Windows [Versione 10.0.22000.1098], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.8)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.72.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.18.2
Flutter SDK 3.3.3
lookpark_application_flutter 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- firebase_auth 3.11.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.24.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_mapbox_autocomplete 2.0.0 [flutter http]
- flutter_riverpod 2.0.2 [collection flutter meta riverpod state_notifier]
- flutter_svg 1.1.5 [flutter meta path_drawing vector_math xml]
- flutterfire_ui 0.4.3+14 [cloud_firestore collection crypto desktop_webview_auth email_validator firebase_auth firebase_core firebase_database firebase_dynamic_links flutter flutter_facebook_auth flutter_localizations flutter_svg google_sign_in sign_in_with_apple twitter_login]
- geojson 1.0.0 [geodesy geopoint iso pedantic]
- geopoint 1.0.0 [latlong2 slugify]
- intl_phone_number_input 0.7.1 [flutter libphonenumber_plugin equatable collection]
- latlong2 0.8.1 [intl]
- location 4.4.0 [flutter location_platform_interface location_web]
- map_launcher 2.4.0 [flutter]
- mapbox_gl 0.16.0 [flutter mapbox_gl_platform_interface mapbox_gl_web collection]
- mapbox_search 3.0.1+2 [http]
- pinput 2.2.16 [flutter smart_auth]
- provider 6.0.4 [collection flutter nested]
- sms_autofill 2.2.0 [pin_input_text_field flutter]
- very_good_analysis 2.4.0

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.0.2 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- archive 3.3.1 [crypto path]
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore 3.5.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_firestore_platform_interface 5.7.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.10 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- crypto 3.0.2 [typed_data]
- desktop_webview_auth 0.0.9 [crypto flutter http]
- email_validator 2.1.17
- equatable 2.0.5 [collection meta]
- extra_pedantic 1.5.0
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 6.10.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 4.6.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database 9.1.7 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_database_platform_interface 0.2.2+7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.1+9 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_dynamic_links 4.3.11 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.3+15 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- flutter_facebook_auth 4.4.1+1 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_facebook_auth_platform_interface 3.2.0 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 3.2.0 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- geodesy 0.4.0-nullsafety.0 [latlong2 pedantic]
- google_sign_in 5.4.2 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web] 
- google_sign_in_android 6.1.1 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.5.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.3.0 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.10.2 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image 3.2.0 [archive meta xml]
- intl 0.17.0 [clock path]
- iso 1.0.0 [extra_pedantic meta pedantic]
- js 0.6.4
- libphonenumber 2.0.2 [flutter meta]
- libphonenumber_platform_interface 0.3.1 [flutter plugin_platform_interface]
- libphonenumber_plugin 0.2.3 [flutter flutter_web_plugins libphonenumber_platform_interface libphonenumber_web libphonenumber] 
- libphonenumber_web 0.2.0+1 [flutter flutter_web_plugins js libphonenumber_platform_interface]
- lints 1.0.1
- location_platform_interface 2.3.0 [flutter meta plugin_platform_interface]
- location_web 3.1.1 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- mapbox_gl_dart 0.2.1 [js]
- mapbox_gl_platform_interface 0.16.0 [flutter meta]
- mapbox_gl_web 0.16.0 [flutter flutter_web_plugins meta mapbox_gl_platform_interface mapbox_gl_dart image]
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- nested 1.0.0 [flutter]
- path 1.8.2
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- pedantic 1.11.1
- petitparser 5.0.0 [meta]
- pin_input_text_field 4.2.0 [flutter]
- plugin_platform_interface 2.1.3 [meta]
- quiver 3.1.0 [matcher]
- riverpod 2.0.2 [collection meta stack_trace state_notifier]
- sign_in_with_apple 3.3.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- slugify 2.0.0
- smart_auth 1.0.6 [flutter flutter_web_plugins]
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.2+1 [meta]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- twitter_login 4.2.3 [flutter crypto http]
- typed_data 1.3.1 [collection]
- vector_math 2.1.2
- xml 6.1.0 [collection meta petitparser]
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report. Using plugin's example and running it on latest master with plugin's latest version, entering wrong OTP twice throws below error:

```
======== Exception caught by gesture ===============================================================
The following StateError was thrown while handling a gesture:
Bad state: Future already completed

When the exception was thrown, this was the stack: 
#1      PhoneAuthFlow.verifySMSCode (package:flutterfire_ui/src/auth/flows/phone_auth_flow.dart:93:23)
#2      _SMSCodeInputViewState.submit (package:flutterfire_ui/src/auth/views/sms_code_input_view.dart:39:12)
#3      _SMSCodeInputViewState.build.<anonymous closure>.<anonymous closure> (package:flutterfire_ui/src/auth/views/sms_code_input_view.dart:75:21)
#4      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1077:21)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:276:7)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:163:27)
#10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:464:20)
#11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:334:11)
#13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#17     _invoke1 (dart:ui/hooks.dart:164:13)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
(elided one frame from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#bd36e
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(203.0, 457.0)
  finalLocalPosition: Offset(165.0, 15.5)
  button: 1
  sent tap down
====================================================================================================

======== Exception caught by gesture ===============================================================
The following StateError was thrown while handling a gesture:
Bad state: Future already completed

When the exception was thrown, this was the stack: 
#1      PhoneAuthFlow.verifySMSCode (package:flutterfire_ui/src/auth/flows/phone_auth_flow.dart:93:23)
#2      _SMSCodeInputViewState.submit (package:flutterfire_ui/src/auth/views/sms_code_input_view.dart:39:12)
#3      _SMSCodeInputViewState.build.<anonymous closure>.<anonymous closure> (package:flutterfire_ui/src/auth/views/sms_code_input_view.dart:75:21)
#4      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1077:21)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:276:7)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:163:27)
#10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:464:20)
#11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:334:11)
#13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#17     _invoke1 (dart:ui/hooks.dart:164:13)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
(elided one frame from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#bd36e
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(203.0, 457.0)
  finalLocalPosition: Offset(165.0, 15.5)
  button: 1
  sent tap down
====================================================================================================

```

**Comment by darshankawar** [comment]
My bad, this is already reported and assigned : https://github.com/firebase/flutterfire/issues/7691

@AlbertoNoris Please follow-up in linked issue for further updates. Closing this as duplicate.
