### ISSUE TITLE
🐛 firebase_database: Uncaught exception in Firebase Database runloop (20.1.0)

### ISSUE THREAD

**Issue by rullyalves** [firebase/flutterfire#9839]
## Bug report

**Describe the bug**
This error ocurs only on production mode when firebase database query is called.

stack trace:
```
java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.1.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
        at com.google.firebase.database.t.n$a$a.run(AndroidPlatform.java:1)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7889)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

Caused by: java.lang.NoSuchMethodError: No virtual method object()Lr/a/g; in class Lr/a/g; or its super classes (declaration of 'r.a.g' appears in base.apk)
        at com.google.firebase.database.a0.b.e(JsonMapper.java:2)
        at com.google.firebase.database.a0.b.d(JsonMapper.java:9)
        at com.google.firebase.database.a0.b.c(JsonMapper.java:1)
        at com.google.firebase.database.v.q.v(WebsocketConnection.java:2)
        at com.google.firebase.database.v.g.l(Connection.java:5)
        at com.google.firebase.database.v.g.m(Connection.java:4)
        at com.google.firebase.database.v.n.A0(PersistentConnectionImpl.java:6)
        at com.google.firebase.database.v.n.r0(PersistentConnectionImpl.java:1)
        at com.google.firebase.database.v.n.B0(PersistentConnectionImpl.java:4)
        at com.google.firebase.database.v.n.v0(PersistentConnectionImpl.java:7)
        at com.google.firebase.database.v.n.c(PersistentConnectionImpl.java:5)
        at com.google.firebase.database.v.g.e(Connection.java:3)
        at com.google.firebase.database.v.g.i(Connection.java:7)
        at com.google.firebase.database.v.g.g(Connection.java:11)
        at com.google.firebase.database.v.g.a(Connection.java:7)
        at com.google.firebase.database.v.q.j(WebsocketConnection.java:7)
        at com.google.firebase.database.v.q.o(WebsocketConnection.java:6)
        at com.google.firebase.database.v.q.f(WebsocketConnection.java:1)
        at com.google.firebase.database.v.q$e$b.run(WebsocketConnection.java:1)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by darshankawar** [comment]
@rullyalves 
As the error log says :

`java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.1.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk`

It seems to be related to Firebase SDK and not firebase_database, so you'll probably need to open this in native [repo](https://github.com/firebase/firebase-android-sdk/issues) as suggested in the error message itself.

Closing from here, as it doesn't seem to be actionable from Flutterfire.
