### ISSUE TITLE
Firebase analytics is not allowed to use anymore on Android for auto-restart code?

### ISSUE THREAD

**Issue by lanistor** [firebase/flutterfire#9840]
Recently in China, firebase analytics is not allowed to use because it will request auto restart.

Our app was taken down because of this reason, and we have received this report from Xiaomi, Oppo until now, and this will happen in other brands soon, for chinese law. So we now have to find another to replace firebase analytics, but we really what to use firebase.

This problem will happend to all apps selling in China, so i think it's really a big problem.

So if firebase can add a switch to `auto-restart` code? After user agree app's protocol, then run the code?

The detail log is here:
```
	at android.app.JobSchedulerImpl.schedule()
	at p3.v0.a(com.google.android.gms:play-services-measurement@@21.1.1:15)
	at t3.u9.n(com.google.android.gms:play-services-measurement@@21.1.1:30)
	at t3.ia.M(com.google.android.gms:play-services-measurement@@21.1.1:63)
	at t3.ia.D(com.google.android.gms:play-services-measurement@@21.1.1:375)
	at t3.ia.j(com.google.android.gms:play-services-measurement@@21.1.1:113)
	at t3.ia.l(com.google.android.gms:play-services-measurement@@21.1.1:19)
	at t3.ia.q(com.google.android.gms:play-services-measurement@@21.1.1:192)
	at t3.v5.run(com.google.android.gms:play-services-measurement@@21.1.1:2)
	at t3.x5.C0(com.google.android.gms:play-services-measurement@@21.1.1:3)
	at t3.x5.D(com.google.android.gms:play-services-measurement@@21.1.1:2)
	at t3.g8.run(com.google.android.gms:play-services-measurement-impl@@21.1.1:4)
	at t3.a9.D(com.google.android.gms:play-services-measurement-impl@@21.1.1:6)
	at t3.a9.x(com.google.android.gms:play-services-measurement-impl@@21.1.1:4)
	at t3.u8.run(com.google.android.gms:play-services-measurement-impl@@21.1.1:5)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at t3.a5.run(com.google.android.gms:play-services-measurement-impl@@21.1.1:6)
``` 

and we have removed `com.google.gms:google-services` by this tutorial: https://medium.com/@samstern_58566/how-to-use-firebase-on-android-without-the-google-services-plugin-93ecc7dc6c4

**Comment by darshankawar** [comment]
@lanistor 
This issue isn't actionable from FlutterFire. You will probably need to reach out to [Firebase support](https://firebase.google.com/support) or native Firebase sdk repo : https://github.com/firebase/firebase-android-sdk/issues

Closing from here.

**Comment by lanistor** [comment]
Thanks.
