### ISSUE TITLE
🐛 [firebase_core] Can't initialize Firebase on web in release mode

### ISSUE THREAD

**Issue by matthew-carroll** [firebase/flutterfire#9863]
## Bug report

**Describe the bug**
When I build my Flutter web app in release mode, Firebase initialization fails.

I'm trying to run:
```dart
final firebaseApp = await Firebase.initializeApp(
   // This project only runs on web
   options: DefaultFirebaseOptions.web,
);
```

I get the following error:
```
Uncaught TypeError: Cannot read properties of null (reading 'oH$')
    at al.glF (main.dart.js:46756:18)
    at main.dart.js:46765:14
    at ajD.a (main.dart.js:3974:62)
    at ajD.$2 (main.dart.js:28184:14)
    at Object.u (main.dart.js:3960:10)
    at al.N0 (main.dart.js:46770:10)
    at al.ad (main.dart.js:46759:21)
    at main.dart.js:33495:92
    at ajD.a (main.dart.js:3974:62)
    at ajD.$2 (main.dart.js:28184:14)
```

This only happens when I build for release mode. It doesn't happen when running from Android Studio, nor does it happen when I build for `--profile`.

### Steps to reproduce

1. Initialize Firebase
2. Build the web project in `--release` mode
3. Open the web project in a browser

### Expected behavior

Firebase initializes

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.18.2
Flutter SDK 3.3.3
flutter_bounty_hunters_blog 1.0.0+1

dependencies:
- any_syntax_highlighter 0.0.4 [flutter]
- blog_posts 1.0.0 [json_annotation]
- firebase_analytics 10.0.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.1.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_highlighter 0.1.1 [flutter highlighter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- font_awesome_flutter 10.2.1 [flutter]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- http 0.13.5 [async http_parser meta path]
- json_annotation 4.7.0 [meta]
- markdown 4.0.1 [args charcode meta]
- super_editor 0.2.2 [flutter attributed_text characters collection http linkify logging super_text_layout uuid flutter_test flutter_test_robots]
- super_editor_markdown 0.1.3 [flutter super_editor logging markdown]
- url_launcher 6.1.6 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- youtube_player_iframe 3.1.0 [flutter meta webview_flutter url_launcher youtube_player_iframe_web]

dev dependencies:
- build_runner 2.3.0 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- json_serializable 6.5.4 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]

dependency overrides:
- attributed_text 0.2.0 [characters collection logging meta test]
- super_editor 0.2.2 [flutter attributed_text characters collection http linkify logging super_text_layout uuid flutter_test flutter_test_robots]
- super_text_layout 0.1.4 [flutter attributed_text logging]

transitive dependencies:
- _fe_analyzer_shared 47.0.0 [meta]
- _flutterfire_internals 1.0.7 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 4.7.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.1
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.3.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.10 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.7 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.4.2 [built_collection collection fixnum meta]
- characters 1.2.1
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 5.8.4 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.0.4 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.3.0 [built_collection built_value collection matcher meta]
- collection 1.16.0
- convert 3.1.1 [typed_data]
- coverage 1.6.1 [args logging package_config path source_maps stack_trace vm_service]
- crypto 3.0.2 [typed_data]
- dart_style 2.2.4 [analyzer args path pub_semver source_span]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- firebase_analytics_platform_interface 3.3.12 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.1+3 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.5.2 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.0.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.1
- flutter_test_robots 0.0.17 [flutter flutter_test]
- frontend_server_client 2.1.3 [async path]
- glob 2.1.0 [async collection file path string_scanner]
- graphs 2.2.0 [collection]
- highlighter 0.1.1 [collection]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- io 1.0.3 [meta path string_scanner]
- js 0.6.4
- linkify 4.1.0
- lints 2.0.0
- logging 1.1.0
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- mime 1.0.2
- node_preamble 2.0.1
- package_config 2.1.0 [path]
- path 1.8.2
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.20 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.5 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.0
- plugin_platform_interface 2.1.3 [meta]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.2 [collection meta]
- pubspec_parse 1.2.1 [checked_yaml collection json_annotation pub_semver yaml]
- shelf 1.4.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.1 [path shelf shelf_static]
- shelf_static 1.1.1 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.2 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.2.6 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.3 [analyzer collection source_gen]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.1.0
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test 1.21.4 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.16 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.1 [collection]
- url_launcher_android 6.0.19 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.1 [flutter plugin_platform_interface]
- url_launcher_web 2.0.13 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- vm_service 9.4.0
- watcher 1.0.2 [async path]
- web_socket_channel 2.2.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.2.0 [logging]
- webview_flutter 3.0.4 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 2.10.4 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.9.5 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 2.9.5 [flutter path webview_flutter_platform_interface]
- win32 3.0.1 [ffi]
- xdg_directories 0.2.0+2 [meta path process]
- yaml 3.1.1 [collection source_span string_scanner]
- youtube_player_iframe_web 1.0.4 [flutter flutter_web_plugins webview_flutter webview_flutter_platform_interface]
```

</details>

---

**Comment by karthikraja001** [comment]
Instead of 

```
final firebaseApp = await Firebase.initializeApp(
   // This project only runs on web
   options: DefaultFirebaseOptions.web,
);

```
Try this one. This might work,

```
void main() async{
     WidgetsFlutterBinding.ensureInitialized();
     await Firebase.initializeApp(
        // This project only runs on web
        options: DefaultFirebaseOptions.currentPlatform,
     );
}
```

Method 2:

In web/index.html, add this code.

```
<html>
  ...
  <body>
     // Import Firebase core web
    <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-app.js"></script>

    <!-- Firebase Configuration -->
    <script>
      var firebaseConfig = {
        apiKey: "...",
        authDomain: "[YOUR_PROJECT].firebaseapp.com",
        databaseURL: "https://[YOUR_PROJECT].firebaseio.com",
        projectId: "[YOUR_PROJECT]",
        storageBucket: "[YOUR_PROJECT].appspot.com",
        messagingSenderId: "...",
        appId: "1:...:web:...",
        measurementId: "G-...",
      };

      // Initialize Firebase
      firebase.initializeApp(firebaseConfig);
    </script>

  </body>
</html>
```

Hope this works

**Comment by matthew-carroll** [comment]
I tried both of those approaches, but neither worked.

I got slightly different error messages on each of the above.

**Comment by karthikraja001** [comment]
Can I See what are those error messages displayed

**Comment by matthew-carroll** [comment]
Actually, the errors on Method 1 are pretty much the same as Method 2:

![Screen Shot 2022-11-06 at 9 51 32 PM](https://user-images.githubusercontent.com/7259036/200236097-01539b2e-c327-4cc8-9a64-267a38cea98c.png)
![Screen Shot 2022-11-06 at 9 51 38 PM](https://user-images.githubusercontent.com/7259036/200236101-3f959cab-b64d-4892-917e-66b41dbe1e3c.png)

**Comment by darshankawar** [comment]
@matthew-carroll 
I am assuming you are already calling `WidgetsFlutterBinding.ensureInitialized();` before initializing FirebaseApp, as below:

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}
```

Also, the latest error screenshot you shared shows `[core/no-app]`, probably indicating it is unable to find any app to initialize. For that, can you try `dart pub global activate flutterfire_cli` followed by `flutterfire configure` which writes native config / service files and see if it helps ?

Another variant of this is `[core/not-initialized]` which indicates the Firebase is not correctly initialized.
Please also see below link for your reference:

https://github.com/firebase/flutterfire/issues/9400

**Comment by matthew-carroll** [comment]
> I am assuming you are already calling WidgetsFlutterBinding.ensureInitialized();

Yeah, here is my main method:

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  setUrlStrategy(PathUrlStrategy());

  try {
    final firebaseApp = await Firebase.initializeApp(
      options: DefaultFirebaseOptions.web,
    );
    print("Firebase app: $firebaseApp");
  } catch (exception) {
    print("Failed to initialize Firebase");
    print(exception);
  }

  runApp(const BlogReaderApp());
}
```

> For that, can you try dart pub global activate flutterfire_cli followed by flutterfire configure which writes native config / service files

I did that at the beginning. It generated a file called `firebase_options.dart`, which as a `web` configuration, which is what I'm referencing in my `main()` method.

> Another variant of this is [core/not-initialized] which indicates the Firebase is not correctly initialized.
Please also see below link for your reference

That linked issue seems to be about passing a `name` into the Firebase initialization. But I'm not passing a name...

**Comment by darshankawar** [comment]
Thanks for the update. I tried this scenario using `firebase_core` example in release mode, but didn't get the reported error.

output:

```
Firebase app: minified:fs([DEFAULT])
js_primitives.dart:47 Initialized default app minified:fs(foo)
js_primitives.dart:47 Initialized minified:fs(foo)
js_primitives.dart:47 Currently initialized apps: [minified:fs([DEFAULT]), minified:fs(foo)]
```

Keeping this issue open for further insights from the team on expected behavior.

**Comment by russellwheatley** [comment]
@matthew-carroll, I've just tested the example apps for Firestore and Messaging, they both successfully built in release mode. I'm not sure what setup you have, but be sure that you call:

```
await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
```

before using any Firebase services as the below noted error implies:

<img width="577" alt="Screenshot 2022-11-11 at 14 00 32" src="https://user-images.githubusercontent.com/16018629/201355664-2c88f417-31ab-40e0-98b3-d603654f3e1e.png">

**Comment by Lyokone** [comment]
@matthew-carroll Can you try the latest version of FlutterFire?
Since we cannot reproduce this, I assume it's caused by a cross-dependency and an issue in how Dart is minifying/optimizing the code.
Do you mind creating the smallest reproducible example (without all the dependencies)?

**Comment by araafat3** [comment]
this issue solved by put  initialize Firebase like that
 Firebase.initializeApp(options:
    FirebaseOptions(
        apiKey: "",
        authDomain: "",
        projectId: "",
        storageBucket: "",
        messagingSenderId: "",
        appId: "",
        measurementId: ""));
